### ISSUE TITLE
uplink hangs on malformed url

### ISSUE THREAD

**Issue by daddyo** [storj/storj#1043]
To reproduce, invoke uplink with single slash after protocol descriptor 

`uplink cp ~/keybase_amd64.deb sj:/foo/keybase_amd64.deb`

Notice that 'sj:/foo' should be 'sj://foo'

The command works correctly when URL is correctly formed.

Local build on Ubuntu 18.04.1
```
14:58 $ git log -1
commit 273c3924ca9d6a3b6effebded89ea2e8a08d00e7 (HEAD -> master, origin/master, origin/HEAD)
Author: Bill Thorp <bill3000@hotmail.com>
Date: Fri Jan 11 13:15:49 2019 -0500
```

**Comment by stefanbenten** [comment]
@littleskunk FYI

**Comment by stefanbenten** [comment]
Hello @daddyo,
good news!
This issue is fixed with the latest versions 👍
