### ISSUE TITLE
Makefile broken on FreeBSD

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj/storj#1108]
Please add FreeBSD support for storj-sdk v3

Here is the problem with build storj-sdk v3 network on FreeBSD:

- [ ] install latest [Go language for freebsd](https://golang.org/dl/)
`wget https://dl.google.com/go/go1.11.4.freebsd-amd64.tar.gz`
`tar -xvf go1.11.4.freebsd-amd64.tar.gz`
`sudo mv go /usr/local`

- [ ] Setup Go Enviroment
Open your `.profile`file and add global variable as follow at the end of the file. You may want to add this into .zshrc or.bashrc file as per your shell configuration.
```
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```

- [ ] Update current shell session
`source ~/.profile`

- [ ] Verify Installation
`go version`
> go version go1.11.4 freebsd/amd64

`go env`

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/storj/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="freebsd"
> GOOS="freebsd"
> GOPATH="/home/storj/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD="/home/storj/storj/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build436043875=/tmp/go-build -gno-record-gcc-switches"

- [ ] Install [storj-sdk v3 network](https://github.com/storj/storj/wiki/Test-network)
```
git clone https://github.com/storj/storj.git storj
cd storj
make install-sim
```
- [ ] Got Error

> make: "/usr/home/storj/storj/Makefile" line 6: Missing dependency operator
> make: "/usr/home/storj/storj/Makefile" line 8: Need an operator
> make: "/usr/home/storj/storj/Makefile" line 10: Need an operator
> make: "/usr/home/storj/storj/Makefile" line 14: Missing dependency operator
> make: "/usr/home/storj/storj/Makefile" line 16: Need an operator
> make: "/usr/home/storj/storj/Makefile" line 216: Missing dependency operator
> make: "/usr/home/storj/storj/Makefile" line 222: Need an operator
> make: "/usr/home/storj/storj/Makefile" line 224: warning: duplicate script for target "clean-images" ignored
> make: "/usr/home/storj/storj/Makefile" line 221: warning: using previous script for "clean-images" defined here
> make: "/usr/home/storj/storj/Makefile" line 225: warning: duplicate script for target "clean-images" ignored
> make: "/usr/home/storj/storj/Makefile" line 221: warning: using previous script for "clean-images" defined here
> make: "/usr/home/storj/storj/Makefile" line 226: warning: duplicate script for target "clean-images" ignored
> make: "/usr/home/storj/storj/Makefile" line 221: warning: using previous script for "clean-images" defined here
> make: "/usr/home/storj/storj/Makefile" line 227: warning: duplicate script for target "clean-images" ignored
> make: "/usr/home/storj/storj/Makefile" line 221: warning: using previous script for "clean-images" defined here
> make: "/usr/home/storj/storj/Makefile" line 228: Need an operator
> make: Fatal errors encountered -- cannot continue
> make: stopped in /usr/home/storj/storj
>

**Comment by egonelbre** [comment]
From first glance it seems that the Makefile has incompatibilities with the make on FreeBSD.

Can you try running:

```
go install -race -v storj.io/storj/cmd/...
```

_It installs a bit more tools than necessary, but is easier to type._

Of course, even if manual installation works, we'll still need to fix the Makefile.

**Comment by AlexandrTyshchenko** [comment]
@egonelbre Thanks for looking this issue again!
I tryed this command (from ## install storj-sim section of Makefile): 
`go install -race -v storj.io/storj/cmd/storj-sim storj.io/storj/cmd/bootstrap storj.io/storj/cmd/satellite storj.io/storj/cmd/storagenode storj.io/storj/cmd/uplink storj.io/storj/cmd/gateway storj.io/storj/cmd/identity storj.io/storj/cmd/certificates`

And evrything builded fine, GOPATH/bin contain binary after success build:

> bootstrap
> certificates
> identity
> satellite
> storagenode
> storj-sim

So, it working and you can change Makefile for add freebsd support.

**Comment by AlexandrTyshchenko** [comment]
Sorry, I try to move forward with 
`storj-sim network setup`

> Error: some executables cannot be found: [gateway]
And realize that gateway binary is missing

tryed to rebuild it:
`go install -race storj.io/storj/cmd/gateway`
And got error:

> # github.com/hanwen/go-fuse/fuse
> go/src/github.com/hanwen/go-fuse/fuse/types.go:433:2: undefined: Attr
> # github.com/minio/minio/pkg/cpu
> go/src/github.com/minio/minio/pkg/cpu/cpu.go:53:22: undefined: newCounter

**Comment by egonelbre** [comment]
Thanks for trying all of this on FreeBSD, it's really helpful.

I've made a PR #1109 that disables mounting support for uplink/gateway. `gateway` actually doesn't need it, but we haven't yet properly split the binaries so there's some unfortunate coupling.

The `github.com/minio/minio/pkg/cpu` is related to minio S3 gateway, I'll try to get it sorted.

**Comment by AlexandrTyshchenko** [comment]
@egonelbre Thanks for you help!
I will waiting for merge this commit and test it again.

**Comment by AlexandrTyshchenko** [comment]
Hi @egonelbre 
I see that #1109 is merged and I try to move forward again:
`go install -race -v storj.io/storj/cmd/storj-sim storj.io/storj/cmd/bootstrap storj.io/storj/cmd/satellite storj.io/storj/cmd/storagenode storj.io/storj/cmd/uplink storj.io/storj/cmd/gateway storj.io/storj/cmd/identity storj.io/storj/cmd/certificates`
now i see that gateway build without any issues and GOPATH/bin contain binary:
> bootstrap
> certificates
> gateway
> identity
> satellite
> storagenode
> storj-sim
> uplink

Try to setup network:
`storj-sim network setup`

> bootstrap/0              22:10:50.359 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/bootstrap/0/config.yaml
> storagenode/1            22:10:50.398 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/1/config.yaml
> storagenode/6            22:10:50.398 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/6/config.yaml
> storagenode/0            22:10:50.399 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/0/config.yaml
> storagenode/4            22:10:50.404 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/4/config.yaml
> storagenode/7            22:10:50.419 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/7/config.yaml
> storagenode/5            22:10:50.422 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/5/config.yaml
> storagenode/9            22:10:50.433 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/9/config.yaml
> storagenode/2            22:10:50.433 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/2/config.yaml
> storagenode/3            22:10:50.433 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/3/config.yaml
> storagenode/8            22:10:50.443 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/storagenode/8/config.yaml
> satellite/0              22:10:50.467 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/satellite/0/config.yaml
> gateway/0                22:10:50.473 | Configuration saved to: /usr/home/storj/.local/share/storj/local-network/gateway/0/config.yaml

And try to run network:

`storj-sim network run`

> bootstrap/0              22:13:19.005 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/bootstrap/0/config.yaml
> bootstrap/0              22:13:19.026 | INFO    Operator email: bootstrap@example.com
> bootstrap/0              22:13:19.026 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> bootstrap/0              22:13:19.029 | DEBUG   Initialized telemetry batcher with id = "12TdnfcaAsZJgWxKivsKgbxN2QWGE343MmR7Gc8zNRhPpnny3nG"
> bootstrap/0              22:13:19.046 | INFO    Bootstrap node 12TdnfcaAsZJgWxKivsKgbxN2QWGE343MmR7Gc8zNRhPpnny3nG started on 127.0.0.1:9999
> storagenode/0            22:13:19.151 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/0/config.yaml
> storagenode/1            22:13:19.151 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/1/config.yaml
> storagenode/5            22:13:19.156 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/5/config.yaml
> storagenode/8            22:13:19.161 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/8/config.yaml
> storagenode/1            22:13:19.175 | INFO    Operator email: storage1@example.com
> storagenode/0            22:13:19.176 | INFO    Operator email: storage0@example.com
> storagenode/1            22:13:19.176 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/0            22:13:19.176 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/1            22:13:19.179 | DEBUG   Initialized telemetry batcher with id = "1yjDx6EbRCHNYMgYPL6yUFrRRfmRjsGY4a9BzFTw24kaHrPT2c"
> storagenode/0            22:13:19.179 | DEBUG   Initialized telemetry batcher with id = "1y8CCSDZ5F8mBkvUazEz7ykXSzu26APYFT2hyjahVoshQ8uGZM"
> storagenode/3            22:13:19.182 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/3/config.yaml
> storagenode/5            22:13:19.182 | INFO    Operator email: storage5@example.com
> storagenode/5            22:13:19.183 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/4            22:13:19.184 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/4/config.yaml
> storagenode/2            22:13:19.185 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/2/config.yaml
> storagenode/5            22:13:19.185 | DEBUG   Initialized telemetry batcher with id = "1fMiCzuHa7MSGrZsA1tGeTvp8ej7gRum2HQfdpck9t5rJkyzC6"
> storagenode/8            22:13:19.188 | INFO    Operator email: storage8@example.com
> storagenode/8            22:13:19.189 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> satellite/0              22:13:19.190 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/satellite/0/config.yaml
> storagenode/8            22:13:19.191 | DEBUG   Initialized telemetry batcher with id = "1Fwd43zumSUtUNWrcrtfVGNmALuakeBZejEJL7xr6kCM6CYi8N"
> storagenode/9            22:13:19.194 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/9/config.yaml
> storagenode/6            22:13:19.199 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/6/config.yaml
> storagenode/7            22:13:19.201 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/storagenode/7/config.yaml
> storagenode/3            22:13:19.206 | INFO    Operator email: storage3@example.com
> storagenode/3            22:13:19.206 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/4            22:13:19.208 | INFO    Operator email: storage4@example.com
> storagenode/3            22:13:19.208 | DEBUG   Initialized telemetry batcher with id = "125yUa2NTBrNtG3yj8VHQZPauYoJQWHUF2B1uMJ5S1d4V9Cg4AH"
> storagenode/4            22:13:19.208 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/4            22:13:19.211 | DEBUG   Initialized telemetry batcher with id = "12jUxhPfMn6wwqgqvuPkfYpiRq7LMix4meJaNrAKemKBQMND8Xt"
> storagenode/2            22:13:19.214 | INFO    Operator email: storage2@example.com
> storagenode/2            22:13:19.214 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> satellite/0              22:13:19.216 | DEBUG   Initialized telemetry batcher with id = "1eJ6cDD5tDBMbH6Kf3czdb9GSALTv2Pw7vEGR72baC7bHabm9r"
> storagenode/2            22:13:19.217 | DEBUG   Initialized telemetry batcher with id = "1UozbgTGGcUrtXmxRU6DpAMeHhfSiwqy5TMBBtipTzFbVcRniD"
> storagenode/9            22:13:19.217 | INFO    Operator email: storage9@example.com
> storagenode/9            22:13:19.218 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/9            22:13:19.220 | DEBUG   Initialized telemetry batcher with id = "1DMUaiU2uEMEZyMtgmaFjfQKTTdzDefY6TL1nFUNPGCYktSYT1"
> storagenode/6            22:13:19.223 | INFO    Operator email: storage6@example.com
> storagenode/6            22:13:19.223 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/7            22:13:19.225 | INFO    Operator email: storage7@example.com
> storagenode/7            22:13:19.225 | INFO    Operator wallet: 0x0123456789012345678901234567890123456789
> storagenode/6            22:13:19.225 | DEBUG   Initialized telemetry batcher with id = "12o9AxKML1asU2bnYkANdmE3zKrrjpBmEN69zKjB4GfctkYKtxX"
> storagenode/7            22:13:19.227 | DEBUG   Initialized telemetry batcher with id = "126zdjCjXnH4oN4jES5WnJnAdVEF4zc4qfc4VYRD9sSbNcchoCD"
> storagenode/0            22:13:19.280 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/1            22:13:19.280 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/0            22:13:19.281 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/0            22:13:19.282 | DEBUG   piecestore      Getting Stats...
> storagenode/1            22:13:19.282 | DEBUG   piecestore      Getting Stats...
> storagenode/1            22:13:19.282 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/0 1y8CCSDZ5F 22:13:19.282 | INFO    Node 1y8CCSDZ5F8mBkvUazEz7ykXSzu26APYFT2hyjahVoshQ8uGZM started on 127.0.0.1:11000
> storagenode/1 1yjDx6EbRC 22:13:19.282 | INFO    Node 1yjDx6EbRCHNYMgYPL6yUFrRRfmRjsGY4a9BzFTw24kaHrPT2c started on 127.0.0.1:11001
> storagenode/5 1fMiCzuHa7 22:13:19.301 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
>                                       | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
>                                       | DEBUG   piecestore      Getting Stats...
>                                       | INFO    Node 1fMiCzuHa7MSGrZsA1tGeTvp8ej7gRum2HQfdpck9t5rJkyzC6 started on 127.0.0.1:11005
> storagenode/8            22:13:19.322 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/8            22:13:19.323 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/8 1Fwd43zumS 22:13:19.323 | INFO    Node 1Fwd43zumSUtUNWrcrtfVGNmALuakeBZejEJL7xr6kCM6CYi8N started on 127.0.0.1:11008
> storagenode/8 1Fwd43zumS 22:13:19.324 | DEBUG   piecestore      Getting Stats...
> storagenode/3            22:13:19.359 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/3 125yUa2NTB 22:13:19.360 | INFO    Node 125yUa2NTBrNtG3yj8VHQZPauYoJQWHUF2B1uMJ5S1d4V9Cg4AH started on 127.0.0.1:11003
> storagenode/3 125yUa2NTB 22:13:19.360 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/3 125yUa2NTB 22:13:19.360 | DEBUG   piecestore      Getting Stats...
> storagenode/4            22:13:19.368 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/4 12jUxhPfMn 22:13:19.370 | INFO    Node 12jUxhPfMn6wwqgqvuPkfYpiRq7LMix4meJaNrAKemKBQMND8Xt started on 127.0.0.1:11004
> storagenode/4 12jUxhPfMn 22:13:19.370 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/4 12jUxhPfMn 22:13:19.371 | DEBUG   piecestore      Getting Stats...
> storagenode/2            22:13:19.373 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/9            22:13:19.374 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/2            22:13:19.374 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/2            22:13:19.374 | DEBUG   piecestore      Getting Stats...
> storagenode/2 1UozbgTGGc 22:13:19.374 | INFO    Node 1UozbgTGGcUrtXmxRU6DpAMeHhfSiwqy5TMBBtipTzFbVcRniD started on 127.0.0.1:11002
> storagenode/9 1DMUaiU2uE 22:13:19.375 | INFO    Node 1DMUaiU2uEMEZyMtgmaFjfQKTTdzDefY6TL1nFUNPGCYktSYT1 started on 127.0.0.1:11009
> storagenode/9 1DMUaiU2uE 22:13:19.376 | DEBUG   piecestore      Getting Stats...
> storagenode/9 1DMUaiU2uE 22:13:19.376 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/7            22:13:19.378 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/7            22:13:19.379 | DEBUG   piecestore      Getting Stats...
> storagenode/7            22:13:19.379 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/7 126zdjCjXn 22:13:19.380 | INFO    Node 126zdjCjXnH4oN4jES5WnJnAdVEF4zc4qfc4VYRD9sSbNcchoCD started on 127.0.0.1:11007
> storagenode/6            22:13:19.381 | INFO    piecestore      Remaining Bandwidth     {"bytes": 536870912000}
> storagenode/6            22:13:19.382 | DEBUG   agreements      AgreementSender is running      {"duration": "1h0m0s"}
> storagenode/6            22:13:19.382 | DEBUG   piecestore      Getting Stats...
> storagenode/6 12o9AxKML1 22:13:19.383 | INFO    Node 12o9AxKML1asU2bnYkANdmE3zKrrjpBmEN69zKjB4GfctkYKtxX started on 127.0.0.1:11006
> gateway/0                22:13:19.383 | INFO    Configuration loaded from: /usr/home/storj/.local/share/storj/local-network/gateway/0/config.yaml
> gateway/0                22:13:19.384 | INFO    Invalid configuration file key: identity.version
>                                       | INFO    Invalid configuration file key: identity.overwrite
> satellite/0   1eJ6cDD5tD 22:13:19.406 | INFO    Node 1eJ6cDD5tDBMbH6Kf3czdb9GSALTv2Pw7vEGR72baC7bHabm9r started on 127.0.0.1:10000
> satellite/0   1eJ6cDD5tD 22:13:19.407 | DEBUG   pdb.1   Iterate {"prefix": "", "first": "", "recurse": true, "reverse": false}
> gateway/0                22:13:19.409 | Starting Storj S3-compatible gateway!
>                                       |
> gateway/0                22:13:19.409 | Endpoint: 127.0.0.1:9000
>                                       | Access key: 8ee6dc00efd6582aa2dc
>                                       | Secret key: 44d1dc048ef796feebe1
> gateway/0                22:13:19.422 | DEBUG   Initialized telemetry batcher with id = "12PoREqV3Gi13xJh64nzSgw2VcefNCkRPmSAX6tJpVMkj6nvGpb"
> bootstrap/0              22:13:19.427 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11000
> satellite/0   1eJ6cDD5tD 22:13:19.435 | DEBUG   pdb.1   Iterate {"prefix": "l/", "first": "", "recurse": false, "reverse": false}
> gateway/0                22:13:19.445 | Created minio configuration file successfully at /usr/home/storj/.local/share/storj/local-network/gateway/0/minio
> satellite/0   1eJ6cDD5tD 22:13:19.460 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000
> storagenode/8 1Fwd43zumS 22:13:19.544 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11001
> storagenode/0 1y8CCSDZ5F 22:13:19.581 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11000
> storagenode/5 1fMiCzuHa7 22:13:19.605 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11005
> storagenode/1 1yjDx6EbRC 22:13:19.607 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11000
> storagenode/2 1UozbgTGGc 22:13:19.781 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11009
> storagenode/7 126zdjCjXn 22:13:19.801 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11003
> storagenode/9 1DMUaiU2uE 22:13:19.839 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11009
> storagenode/3 125yUa2NTB 22:13:19.961 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11003
> storagenode/4 12jUxhPfMn 22:13:20.008 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11004
> storagenode/6 12o9AxKML1 22:13:20.215 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:11004
> satellite/0   1eJ6cDD5tD 22:13:49.406 | DEBUG   pdb.1   Iterate {"prefix": "", "first": "", "recurse": true, "reverse": false}
> satellite/0   1eJ6cDD5tD 22:14:19.406 | DEBUG   pdb.1   Iterate {"prefix": "", "first": "", "recurse": true, "reverse": false}
> bootstrap/0              22:14:37.540 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> satellite/0   1eJ6cDD5tD 22:14:47.526 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/1 1yjDx6EbRC 22:14:48.491 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/3 125yUa2NTB 22:14:48.497 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/7 126zdjCjXn 22:14:48.504 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/6 12o9AxKML1 22:14:48.510 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/4 12jUxhPfMn 22:14:48.518 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/2 1UozbgTGGc 22:14:48.545 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/8 1Fwd43zumS 22:14:48.545 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/9 1DMUaiU2uE 22:14:48.556 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/0 1y8CCSDZ5F 22:14:48.564 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times
> storagenode/5 1fMiCzuHa7 22:14:48.575 | DEBUG   kademlia:endpoint       Successfully connected with 127.0.0.1:10000 100x times

So, everythig is working! 
You can change Makefile.

**Comment by AlexandrTyshchenko** [comment]
I think we can close it because it building and working on FreeBSD
