### ISSUE TITLE
Links in wiki are malformed

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#1115]
https://github.com/storj/storj/wiki/Test-network#running-tests
It should be 

> For a real-world example you can take a look in [test-sim.sh](https://github.com/storj/storj/blob/master/scripts/test-sim.sh) and [test-sim-aws.sh](https://github.com/storj/storj/blob/master/scripts/test-sim-aws.sh).

and not the

>For a real-world example you can take a look in [https://github.com/storj/storj/blob/master/scripts/test-sim.sh](test-sim.sh) and [https://github.com/storj/storj/blob/master/scripts/test-sim-aws.sh](test-sim-aws.sh).

**Comment by egonelbre** [comment]
Should be now fixed. Thanks.
