### ISSUE TITLE
V3 Test: Invalid API credential

### ISSUE THREAD

**Issue by Fatfish90** [storj/storj#1163]
When I execute:   `storj-sdk network run`

It show this error:
![image](https://user-images.githubusercontent.com/46210862/51896650-d5080180-23e7-11e9-8b26-5725b0c84e71.png)

**Comment by egonelbre** [comment]
Do you also see this with latest code. Note `storj-sdk` was renamed to `storj-sim` so maybe it's running the old version?

**Comment by Fatfish90** [comment]
OK, it is better to update this article: [link](https://medium.com/@storjproject/getting-started-with-the-storj-v3-test-network-storj-sdk-5c153a9bfea0)

**Comment by stefanbenten** [comment]
@Fatfish90 Is this issue still there?
If not, please report back and close the issue 👍
