### ISSUE TITLE
I18N for Storj Docs

### ISSUE THREAD

**Issue by 0xYuan90** [storj/storj#1174]
Storj is a great project.
I support a Chinese translation for storj-wiki.
Link is:  https://github.com/Fatfish90/storj-wiki

So could I make a pull request to merge?

**Comment by Fatfish90** [comment]
![image](https://user-images.githubusercontent.com/46210862/51970672-765b8a00-24b2-11e9-91b1-32d1249f0204.png)

**Comment by jtolds** [comment]
Hi @Fatfish90! We expect this documentation to change quite a bit over the coming months. Is this something you'd be willing to keep up to date? I'm worried that they'll get stale pretty quickly. Translations are super, super helpful, when they're up to date, and our documentation is a moving target. Thoughts?

**Comment by Fatfish90** [comment]
Hi @jtolds, It is my pleasure.

**Comment by iglesiasbrandon** [comment]
This issue has become stale; if you are still interested in this, please let us know @0xYuan90.
