### ISSUE TITLE
S3 Gateway setup error

### ISSUE THREAD

**Issue by Luca8991** [storj/storj#1287]
I wanted to try the **S3 gateway**, so I executed
```bash
gateway setup --api-key abc123 --satellite-addr 127.0.0.1:7778 \
  --enc-key highlydistributedridiculouslyresilient
```
successfully.
Next, when I tried to execute
```bash
gateway run --address :7776
```
it came out with:
```bash
FATAL	file or directory not found error: open /home/<my-username>/.local/share/storj/identity/gateway/identity.cert: no such file or directory
```

**Comment by stefanbenten** [comment]
That is not a issue, you simply forget to generate an identity for the s3 gateway.
Please generate it like this (make sure you have installed the binary):
`identity create gateway`
(you can get more information about the tool by executing `idenitity create --help`

Please note, that you have to run against a local running satellite to be able to use the gateway.

**Comment by Luca8991** [comment]
I can't join the chat on [https://community.storj.io/](url) because it tells "User is not activated", and I can't contact anyone... @stefanbenten can u help me?

**Comment by stefanbenten** [comment]
Could you please file a ticket to support@storj.io? @Luca8991 
They will help you immediately, sorry for the inconvenience!

**Comment by Luca8991** [comment]
I'll do it. Thanks
