### ISSUE TITLE
About the competitive power with Filecoin

### ISSUE THREAD

**Issue by Fatfish90** [storj/storj#1319]
As you know, the Filecoin Project open source today:  https://github.com/filecoin-project/go-filecoin 
How do you think about the advantage of storj compare with Filecoin ?

**Comment by stefanbenten** [comment]
Hello @Fatfish90,

thank you for the interest in a comparison to their project. But this isn’t an issue related to our project development and shouldn’t be discussed here.

Feel free to head over to our community chat at https://community.storj.io to talk about that with the entire community!
