### ISSUE TITLE
Identity directory not found

### ISSUE THREAD

**Issue by Uddeshya-1812** [storj/storj#1418]
file or directory not found error: open /home/uddeshya/.local/share/storj/identity/uplink/identity.cert: no such file or directory
above error was reported while creating a bucket...please provide a solution

**Comment by jtolds** [comment]
We currently have a bug where storage node identities are required for uplinks as well. We're working on fixing it but in the meantime you can create an identity by running `go install storj.io/storj/cmd/identity && identity create uplink`

**Comment by BlueNokia** [comment]
Even after generating the identity I am served with `Uplink configuration error: failed to connect to overlay: transport error: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:7778: connect: connection refused"
`

**Comment by stefanbenten** [comment]
Do you have a local network running? @BlueNokia 
At this stage there is no public network you can use the uplink against. Per default it tries to connect to a satellite running in your local environment.
You can see how that works here:
https://storj.io/blog/2019/01/getting-started-with-the-storj-v3-test-network-storj-sdk/

**Comment by rohan-chakra** [comment]
> Do you have a local network running? @BlueNokia
> At this stage there is no public network you can use the uplink against. Per default it tries to connect to a satellite running in your local environment.
> You can see how that works here:
> https://storj.io/blog/2019/01/getting-started-with-the-storj-v3-test-network-storj-sdk/

I am having a different error when I execute the command "uplink ls"  or any uplink command at all. The error is "rpc error: code = Unauthenticated desc = Invalid API credential". And yes, I ran the storj network before I excuted the uplink commands. Can't find a way out, please help!

**Comment by stefanbenten** [comment]
@rohan-chakra You have to use the ENV Variables of the storj-sim network to take the correct API Credentials for authorization.
You can find the description in detail here:
https://github.com/storj/docs/blob/master/Test-network.md#running-tests

**Comment by rohan-chakra** [comment]
> @rohan-chakra You have to use the ENV Variables of the storj-sim network to take the correct API Credentials for authorization.
> You can find the description in detail here:
> https://github.com/storj/docs/blob/master/Test-network.md#running-tests

Can you please tell me the instructions of how to change the ENV variables and the steps to set the correct API credentials because it is not mentioned in this link or any link of storj blogs that I have visited yet.

**Comment by stefanbenten** [comment]
@rohan-chakra You can point your local uplink at the gateway config that is automatically being started by storj-sim like this:
`uplink --config-dir $GATEWAY_0_DIR <other-config-flags-you-want>`

Reason for using the gateway config is that the uplink is an extended version of the former.
For additional flags that you might want to use the `--help` flag is very self explanatory.

**Comment by rohan-chakra** [comment]
> @rohan-chakra You can point your local uplink at the gateway config that is automatically being started by storj-sim like this:
> `uplink --config-dir $GATEWAY_0_DIR <other-config-flags-you-want>`
> 
> Reason for using the gateway config is that the uplink is an extended version of the former.
> For additional flags that you might want to use the `--help` flag is very self explanatory.

![image](https://user-images.githubusercontent.com/39150396/54012538-682d1780-419c-11e9-9e81-fb50e961f9d4.png)
Hey Stefan I am sorry to have to constantly ask you this but I am honestly not sure how to configure the correct API credentials and what additional flags from gateway would resolve my problem. In this screenshot you can see the error is appearing in the storj network running in the background as well. Does this mean I am connected? and how do I solve this error?

**Comment by ng1091** [comment]
@rohan-chakra 
Hey Rohan, I have the same problem.
`uplink --config-dir $GATEWAY_0_DIR ls`
Because $GATEWAY_0_DIR  is empty on my MacOS,  I set it  to gateway directory using `export $GATEWAY_0_DIR=<path to gateway config>`, and this works for me.

**Comment by Twisterblack** [comment]
Hello everyone ! 
I thank you in advance for your help. 

I am running Linux Debian, when I try to create a bucket with "uplink mb sj: // thename" I get an error message: "file or directory not found error: open /home/daylight/.local/share /storj/identity/uplink/identity.key: no such file or directory ". 

How is it that the directory does not exist and how to solve this problem? 

Thank you so much.

**Comment by stefanbenten** [comment]
@Twisterblack 

your install command is incorrect.
Please use: `go install ./cmd/identity && identity create uplink`

**Comment by stefanbenten** [comment]
Closing as there is no further issue being reported!
