### ISSUE TITLE
S3 Gateway running error

### ISSUE THREAD

**Issue by BlueNokia** [storj/storj#1424]
As instructed in [https://github.com/storj/storj/wiki/S3-Gateway](url) test-network setup was successful. 
But when trying to run it by `~/go/bin/gateway run --address :7776` it gives

`Error: unknown flag: --address`

Then going for  `gateway run` 
it shows

`Uplink configuration error: failed to connect to overlay: transport error: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:7778: connect: connection refused"`

**Comment by stefanbenten** [comment]
@BlueNokia The flag is now called `server.address`
You can always find the help using `gateway run --help`

As referenced in the other issue #1418 You need to run the testnetwork while trying to access it via the gateway.
I will update the S3-Gateway document to reflect the new config flag.
