### ISSUE TITLE
Used powershell with docker to run storj v3 in microsoft windows but it kept restarting.

### ISSUE THREAD

**Issue by shrluxiao** [storj/storj#1588]
Hello, every one.
I tried to run with below Microsoft powershell script but the storj v3 kept restarting.
Docker CE 18.09.2 has been install in OS.

docker run -d --restart unless-stopped -p 28967:28967 -e wallet="0x???" -e email="89324667@qq.com" -e address="???.???.???.???:28967" -e bandwidth="2TB" -e storage="3TB" -v "c:\\users\\shrlu\\appdata\\roaming\\storj\\identity\\storagenode\\":/app/identity -v "g:\\data\\storj\\":/app/config --name storagenode storjlabs/storagenode:alpha

the result would be like below:

PS C:\WINDOWS\system32> docker ps -a
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS                         PORTS               NAMES
76f7201319e5        storjlabs/storagenode:alpha   "./entrypoint.sh"   20 seconds ago      Restarting (1) 6 seconds ago                       storagenode

Would some one help me on troubleshooting and solving this issue? : )

**Comment by stefanbenten** [comment]
Hey @shrluxiao !
From the above command it looks like you have " around your Windows Storage Paths. Please remove them and rerun the command. Then it should work.

For getting rid of your failing container run:
```
docker stop storagenode
docker rm storagenode
docker run <your previous config options with correct paths>```

If that doesnt solve your problem, please reach out to us on the communitychat here:
https://community.storj.io

**Comment by shrluxiao** [comment]
This issue has been solved by me earlier, the path should be -v /f/data/storj/:/app/config in microsoft windows powershell for docker. now the nodes has running for days.
