### ISSUE TITLE
storage node last contact "Never"

### ISSUE THREAD

**Issue by Femtes** [storj/storj#1671]
I have since start never have any "last contact" or any "disk or badwidth used", have i done somting wrong?

Storage Node Dashboard
======================
ID           xxxxxxxxxxxxxxxxxxxxx
Last Contact NEVER
Uptime         98h49m58s
                       Available     Used
Bandwidth       30.0 TB          0
Disk                  2.0 TB           0

Bootstrap bootstrap.storj.io:8888
Internal  xxxxxx:xxxx
External  xxxxx:28967

Neighborhood Size 48

**Comment by littleskunk** [comment]
NEVER means your node is offline. For support questions please use community.storj.io

**Comment by Femtes** [comment]
Trust me, waiting and waiting to get access to the community.storj.io. Can’t logo on to the community befor admin accept my inv.

**Comment by americanbanshee** [comment]
did you verify your email address?

**Comment by Femtes** [comment]
Yep, Clicked at the link and after that I tried to log on and now it says that a admin need to manually activate the account. I can trie to create a new account but I think a cant use the same email address.

**Comment by americanbanshee** [comment]
hI, i n order to check your issue, I need some identifying details so I can find it to look at. Feel free to DM me with your email &/or username

**Comment by Femtes** [comment]
femtes(at)me.com

**Comment by americanbanshee** [comment]
hi there, your account is activated. If you continue to see issues, give a shout

**Comment by shrluxiao** [comment]
@ americanbanshee I have met the same issue, would you take a while to check mine as well. the email address is: 89324667@qq.com
