### ISSUE TITLE
Failed to do periodic version check

### ISSUE THREAD

**Issue by fab-io** [storj/storj#1687]
I have just updated my storagenode to v0.8.8, and found this error in the logs

```
2019-04-05T16:17:32.848Z        ERROR   Failed to do periodic version check: %!(EXTRA *url.Error=Get https://version.alpha.storj.io: x509: certificate signed by unknown authority)
```

**Comment by stefanbenten** [comment]
@fab-io  This is an issue with the docker container.
Its is missing the ca-certificates package internally and thus not able to verify the Lets Encrypt Certificate on the Versioning Server.
This is not critical and will be fixed with the next release.

**Comment by minhng99** [comment]
Hi, I'm getting a similar error, not while running docker container but while `authorize storagenode`

> ./identity_linux_amd64 authorize storagenode xx
> 2019-05-01T05:32:20.097+0200    ERROR   Failed to do periodic version check: %!(EXTRA *url.Error=Get : unsupported protocol scheme "")
> Fatal error: error occurred while signing certificate: rpc error: code = Unknown desc = authorization error: claim timestamp is outside of max delay window: 1556681540
> (identity files were still generated and saved, if you try again existing files will be loaded)

**Comment by GoldZeus** [comment]
> Hi, I'm getting a similar error, not while running docker container but while `authorize storagenode`
> 
> > ./identity_linux_amd64 authorize storagenode xx
> > 2019-05-01T05:32:20.097+0200    ERROR   Failed to do periodic version check: %!(EXTRA *url.Error=Get : unsupported protocol scheme "")
> > Fatal error: error occurred while signing certificate: rpc error: code = Unknown desc = authorization error: claim timestamp is outside of max delay window: 1556681540
> > (identity files were still generated and saved, if you try again existing files will be loaded)

Hello, I'm having the exact same issue, how can we solve this?
Thanks

**Comment by minhng99** [comment]
@GoldZeus it looks like this issue only happen on some OS, I tried Ubuntu and it didn't happen but on Arch Linux it does, maybe missing some package?

**Comment by AlexeyALeonov** [comment]
This issue could be easily fixed - just sync your system clock

> /identity_linux_amd64 authorize storagenode xx
2019-05-01T05:32:20.097+0200 ERROR Failed to do periodic version check: %!(EXTRA *url.Error=Get : unsupported protocol scheme "")
> Fatal error: error occurred while signing certificate: rpc error: code = Unknown desc = authorization error: claim timestamp is outside of max delay window: 1556681540
(identity files were still generated and saved, if you try again existing files will be loaded)

**Comment by werwercat** [comment]
I've tried running this on windows 10, debian 9, and unbuntu 16.04 and 18.04 and I consistently get the  ERROR   Failed to do periodic version check: %!(EXTRA *url.Error=Get : unsupported protocol scheme "")

I have validated that I am able to resolved the cert servers dns and I have created the proper IPtables rules. What is the resolution for this?

**Comment by Pixxelcrasher** [comment]
Please Help I have this Issue when I try to create a new certificate for my Storage node !!

**Comment by AlexeyALeonov** [comment]
This error doesn't prevent you to successfully generate a new identity.

**Comment by stefanofa** [comment]
Yes, it is preventig me.

**Comment by stefanbenten** [comment]
@stefanofa No it cannot. Please see https://github.com/storj/docs/issues/51
