### ISSUE TITLE
Need help setting up

### ISSUE THREAD

**Issue by Byrd1083** [storj/storj#1690]
I've tried telegram for support, they tell me to get on rocket chat for support. I tried to join the RC server and log in with my github account and it says user does not exist. I've requested 2 times through the website to get an auth code. I have not received the email either. I have over 80TB and xeon processors waiting to be used. Should I just stick them on burst coin or is someone going to help me get this setup correctly?

**Comment by littleskunk** [comment]
Please use github only if for bugs.
