### ISSUE TITLE
Difference between bandwidth usage shown in 'dashboard.sh' and 'docker stats'

### ISSUE THREAD

**Issue by JeromeGillard** [storj/storj#1789]
When comparing the output of `dashboard.sh` and `docker stats` the bandwidth figures are not the same.
I do detect a constant traffic of ~1GB per 24h that is not counted by `dashboard.sh`.

Maybe there's a part of the traffic that is not counted for a good reason (internal docker network traffic?), but it should be good to add a notice in the output of `dashboard.sh` that the node is consuming 1GB/day traffic.

A picture to illustrate:
- Node started since more than 24h.
- Constant docker net I/O increase of ~1GB/day
- Regular Storj V3 traffic correlated to disk space consumption at 13:000 and 23:00 (red pointers).

![sjv3](https://user-images.githubusercontent.com/10224878/56410159-6a46c380-627c-11e9-87d2-ef6e1fc0b78a.png)

**Comment by stefanbenten** [comment]
Hello @JeromeGillard !
As you correctly assumend, Docker writes internal data (due to the mapping of folders to the container).
This traffic is only happening on localhost and does not utilize any of your ISP bandwidth!

**Comment by meetyg** [comment]
Hi, @JeromeGillardr
I would like to know how you got that cool grafana dashboard? Did you build it yourself?
How do you know what your reputation is?

**Comment by JeromeGillard** [comment]
I've just published it here: https://grafana.com/dashboards/10121
I did a quick and dirty documentation, do not hesitate to ping me if I missed something to make it work.

**Comment by barlock** [comment]
@JeromeGillard I'm looking for a docker image that has that telegraph config in it. Do you have one?

**Comment by dragelecpc** [comment]
Hi, i install your dashboard, but the Storage size Chart always show 4KB (i run command in server and got true value). Can you please help me?

**Comment by JeromeGillard** [comment]
> 
> 
> Hi, i installed your dashboard, but the Storage size Chart always show 4KB (i runned command in server and got true value). Can you please help me?

Sure, please tell me your data folder location and the part of `telegraf.conf` where `folder_size.sh` is run.
If your directory is > 1TB, the script may take more than 30sec. In that case Telegraf kills it and add a line in the logs.
You can review the logs by `docker logs telegraf --since 2h`
A work around is currently being developed in this repo: https://github.com/gsxryan/storj_telegraf_mon

**Comment by JeromeGillard** [comment]
> 
> 
> @JeromeGillard I'm looking for a docker image that has that telegraph config in it. Do you have one?

Once the repo in the previous comment is stable, I might ship a docker image with InfluxDb, Telegraf and Grafana. I'll tag you once I'll have a running version.

**Comment by dragelecpc** [comment]
> telegraf.conf

Hi, my  data foder location is "/usr/local/storj/storage", and my exec telegraf conf is:
[[inputs.exec]]
   commands = [ "sh /etc/telegraf/script/folder_size.sh /usr/local/storj/storage" ]
   timeout = "5s"
   interval = "5m"
   name_suffix = "_myexeccollector"
   data_format = "json"
   tag_keys = [ "path" ]
My folder size is 550GB
(I can run the script in command line with successful)

**Comment by JeromeGillard** [comment]
Your Telegraf conf seems ok.
I just note small detail that can be bad. You are running the folder_size.sh with `sh`. But the interpreter definer in the script itself (first line) is `bash`. Could you try to change the script to use `#! /bin/sh` as first line and in your conf, remove the `sh`:
`commands = [ "/etc/telegraf/script/folder_size.sh /usr/local/storj/storage" ]`

It would be useful to test it and see the logs. Here is how you can:

- Stop your Telegraf container: `docker container stop telegraf` then `docker container rm telegraf`
- Run Telegraf wth your settings: `docker run ...`
- Enter container by running bash: `docker exec -i -t telegraf /bin/bash`
- Test input plugins: `telegraf --debug --config /etc/telegraf/telegraf.conf --input-filter exec --test`

That way, you will have the precise logs portion.
