### ISSUE TITLE
Can't connect to community Chat

### ISSUE THREAD

**Issue by barlock** [storj/storj#1795]
Almost certainly this isn't the right place to open this issue, but I honestly don't know where else. 

I've just set up a new node 🎉 and it's been going for about 3 days now. I don't see any traffic in storage or bandwidth using `dashboard.sh`. (Maybe a lul over easter?)

My assumption is there is user error somewhere since I'm using a non-standard port (443). "Last Contact" is always under 10s.

I'm not sure how to debug, and I can't log into rocket chat `community.storj.io` to ask there. Resetting my password gives a big red X with no description and logging in with GitHub says "User is Inactive".

I'd love help with either problem!

**Comment by vedalken254** [comment]
So as far as user error, there likely is. In the setup docs, it does say it has to be port 28967 forwarded and that's what the docker application expects. As far as rocket chat goes, you'll want to email support@storj.io and provide information like the email you used or any other sort of authentication information that may be useful.

**Comment by subwolf** [comment]
Port 443 is reserved for https, I'm not sure why you would do that. Whats wrong with 28967?

**Comment by barlock** [comment]
I was running the node through a k8s nginx-ingress which only allows 80 and 443. Having only been able to see anything over https (🤷‍♂️ haven't spent a lot of time looking at the underlying architecture) I had assumed 443 would be the better of the choices. Maybe 80 is better?

I've bypassed the ingress now but it makes the deployment a bit more fragile. 

@subwolf Do you know if 80 would be any better? I'm assuming no.

**Comment by subwolf** [comment]
nginx-ingress, interesting. The normal nginx will run on any port you want. May I ask for more details on your running environment?

**Comment by barlock** [comment]
Sure, it's a k8s cluster running in my house across 4 machines. I have a [nginx-ingress](https://github.com/kubernetes/ingress-nginx) to map ports from pods out to the network. 

The ingress only exposes 80/443 https://github.com/kubernetes/ingress-nginx/issues/1449

I have a router connected to my ISP that maps 80/443 to the node running the ingress. 

What would be ideal is the storj container runs on any machine in the cluster and the k8s ingress always exposes storj at a specific domain name. 

Right now, I'm locking the storj container to a known machine and mapping the router at 28967 to that machine. It works fine, it's just not the most ideal and requires a bit more thinking when modifying the cluster.

**Comment by subwolf** [comment]
There is no reason you cannot use 443, with the understanding that many less hosts use port 443 - the vast majority are port 80. I'll ask other members about the community chat issue.

**Comment by barlock** [comment]
I should probably close this issue, the chat was resolved by emailing support@storj.io 🎉
