### ISSUE TITLE
Out of space error when node has enough free space

### ISSUE THREAD

**Issue by Storj39419** [storj/storj#1839]
"2019-04-25T10:31:45.863Z	ERROR	piecestore protocol: out of space
	storj.io/storj/storagenode/piecestore.(*Endpoint).Upload:219
	storj.io/storj/pkg/pb._Piecestore_Upload_Handler:602
	storj.io/storj/pkg/server.streamInterceptor:19
	google.golang.org/grpc.(*Server).processStreamingRPC:1182
	google.golang.org/grpc.(*Server).handleStream:1254
	google.golang.org/grpc.(*Server).serveStreams.func1.1:690"

The node has free space and I've never seen this error prior to update.

**Comment by Storjeez** [comment]
Same here - when the storagenode helpfully automagically calculates free space for me, which I've already manually provided, it unhelpfully miscalculates free space for me and uploads don't work. Reducing the storage size manumagically makes the uploads work. Check algorithm.

**Comment by ReneSmeekes** [comment]
I think I found the source of this problem.

If the available space on the disk is lower than the assigned disk space - what the node is already using, the assigned disk space is set to equal the available space on disk. 

```	// the available disk space is less than remaining allocated space,
	// due to change of setting before restarting
	if freeDiskSpace < service.allocatedDiskSpace-totalUsed {
		service.allocatedDiskSpace = freeDiskSpace
		service.log.Warn("Disk space is less than requested. Allocating space", zap.Int64("bytes", service.allocatedDiskSpace))
	}```

However, the allocated disk space should be the total disk space the node can use, including what it's already using, so I think the code should be.
```
	// the available disk space is less than remaining allocated space,
	// due to change of setting before restarting
	if freeDiskSpace < service.allocatedDiskSpace-totalUsed {
		service.allocatedDiskSpace = freeDiskSpace**+totalUsed**
		service.log.Warn("Disk space is less than requested. Allocating space", zap.Int64("bytes", service.allocatedDiskSpace))
	}```

**Comment by stefanbenten** [comment]
I will take a look at the issue and report back.
@ReneSmeekes Thank you for the debugging!

**Comment by stefanbenten** [comment]
@Storj39419 @Storjeez The PR #1899 fixes this issue and i will close the issue.
Feel free to report back, if this issue still persists after the next release!
