### ISSUE TITLE
Another noobie setup issue

### ISSUE THREAD

**Issue by Byrd1083** [storj/storj#1877]
Trying to just follow along with a windows setup is not working as expected. I followed a everything and was good up to running the docker code. I am using powershell windows 10 pro.

![image](https://user-images.githubusercontent.com/42227809/57029751-812fd300-6bf7-11e9-8a24-0a3646ece788.png)

I'm trying to run:
docker run -d --restart unless-stopped -p 28967:28967 -e WALLET="0x4b276a69425db8ad1d0ba59d368c0583acfcf1a2" -e EMAIL="westong83@yahoo.com" -e ADDRESS="domain.ddns.net:28967" -e BANDWIDTH="1TB" -e STORAGE="10TB" -v c:\users\rig2\appdata\raoming\storj\identity\:/app/identity -v I:\Storj\:/app/config --name storagenode storjlabs/storagenode:alpha

The ID dir path is correct and the storage drive is correct. Is there a syntax error I'm missing? Also the 10tb drive is not exactly 10tb of course. Is this going to cause error as well?

**Comment by stefanbenten** [comment]
Your Path to the identity is wrong and that exactly what it stated.. 
Please copy it when possible or go to it via tab completion.
It should be Roaming not Raoming.

Regarding your Drive Size, you should never allocate 100%, better to use 90% to prevent an overflow and possible data loss. This also takes care of the partition "overhead" which reduces the available space.

And again, we provide the proper assistance via our communitychat.
Issues here are for problems with the software not user input errors 👍
