### ISSUE TITLE
add more arm tags for watchtower repo

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj/storj#1885]
Please add more arm tags for [watchtower repository ](https://hub.docker.com/r/storjlabs/watchtower/tags). You can compare tags with [original repository](https://hub.docker.com/r/containrrr/watchtower/tags).

The main reason of this change is unify string for all arm based platforms:

> docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtower

and no need specify addition tags like it:

> docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtower:latest-arm32v6

for example: string `docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower` working fine on rpi, nano-pi etc.

**Comment by aligeti** [comment]
For now we support only raspberry pi.

**Comment by Velociraptor85** [comment]
This seems to be related https://github.com/storj/storj/issues/2538

**Comment by ifraixedes** [comment]
Closing this issue, our watchtower image has several architecture tags publish through a docker manifest.

**Comment by AlexandrTyshchenko** [comment]
Confirmed, it fixed.
