### ISSUE TITLE
image operating system "linux" cannot be used on this platform

### ISSUE THREAD

**Issue by dinhhung2512** [storj/storj#1892]
I can not download the docker container from docker hub

PS C:\windows\system32> docker pull storjlabs/storagenode:alpha
alpha: Pulling from storjlabs/storagenode
image operating system "linux" cannot be used on this platform

PS C:\windows\system32> docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   
 Built:        Tue Sep 26 22:50:27 2017
 OS/Arch:      windows/amd64
 Experimental: false

PS C:\windows\system32> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.09.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: ics l2bridge l2tunnel nat null overlay transparent
 Log: awslogs etwlogs fluentd json-file logentries splunk syslog
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.2906.amd64fre.rs1_release_inmarket.190401-1809)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 1.798GiB
Name:
ID: 
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by ReneSmeekes** [comment]
https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

Be aware that linux containers require Hyper-V to be enabled.

For quicker support please ask in the community at community.storj.io in channel #storagenode

**Comment by dinhhung2512** [comment]
I enabled Hyper-V

PS C:\windows\system32> Install-WindowsFeature Hyper-V

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             NoChangeNeeded {}


PS C:\windows\system32> Install-WindowsFeature containers

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             NoChangeNeeded {}

**Comment by ReneSmeekes** [comment]
did you also look at the link to see how to switch to linux containers?

**Comment by dinhhung2512** [comment]
> did you also look at the link to see how to switch to linux containers?

I tried it but not work.

"Failed to switch because your Windows version is not compatible.

Keep previous configuration."

**Comment by ReneSmeekes** [comment]
That message seems pretty self explanatory to me. Linux containers are not supported for Windows server 2016 with docker CE. I didn't notice your os before. Storj explicitly mentioned only windows 10 pro is supported for now.

That said, I did find a messy workaround, but you'll be on your own if you take this approach. https://forums.docker.com/t/linux-container-in-w2k16/26321

**Comment by TechAUmNu** [comment]
maybe use a recent version of docker not one from 2017. I am using 18.09.2 and it works fine on windows server 2016.

**Comment by stefanbenten** [comment]
@dinhhung2512 Is this issue still persistent?
