### ISSUE TITLE
Fail to initialize database: invalid argument

### ISSUE THREAD

**Issue by luzemario** [storj/storj#1947]
Hi folks,

I am starting the storagenode for the fisrt time, but the init fails with the following message:

Fatal error: Error starting master database on storagenode: boltdb error: invalid argument

Docker says that the image is in sync with latest version, so I am raising this issue to follow the case.

**Comment by luzemario** [comment]
Full log:
`2019-05-11T14:36:43.760851608Z 2019-05-11T14:36:43.760Z INFO Configuration loaded from: /app/config/config.yaml
2019-05-11T14:36:43.784444528Z 2019-05-11T14:36:43.784Z INFO Operator email: <email>
2019-05-11T14:36:43.784683113Z 2019-05-11T14:36:43.784Z INFO Operator wallet: <wallet>
2019-05-11T14:36:43.794234852Z Fatal error: Error starting master database on storagenode: boltdb error: invalid argument
2019-05-11T14:36:43.794254801Z storj.io/storj/storage/boltdb.NewShared:71
2019-05-11T14:36:43.794264434Z storj.io/storj/storagenode/storagenodedb.New:58
2019-05-11T14:36:43.794273634Z main.cmdRun:134
2019-05-11T14:36:43.794293896Z storj.io/storj/pkg/process.cleanup.func1.2:259
2019-05-11T14:36:43.794303076Z storj.io/storj/pkg/process.cleanup.func1:273
2019-05-11T14:36:43.794311905Z github.com/spf13/cobra.(*Command).execute:762
2019-05-11T14:36:43.794320450Z github.com/spf13/cobra.(*Command).ExecuteC:852
2019-05-11T14:36:43.794328794Z github.com/spf13/cobra.(*Command).Execute:800
2019-05-11T14:36:43.794337021Z storj.io/storj/pkg/process.Exec:56
2019-05-11T14:36:43.794345201Z main.main:288
2019-05-11T14:36:43.794353269Z runtime.main:200`

**Comment by luzemario** [comment]
Additional info:

`root@docker:/home/luzemario# docker version
Client:
Version: 18.09.6
API version: 1.39
Go version: go1.10.8
Git commit: 481bc77
Built: Sat May 4 02:36:00 2019
OS/Arch: linux/amd64
Experimental: false

Server: Docker Engine - Community
Engine:
Version: 18.09.6
API version: 1.39 (minimum version 1.12)
Go version: go1.10.8
Git commit: 481bc77
Built: Sat May 4 01:59:36 2019
OS/Arch: linux/amd64
Experimental: false`

**Comment by ifraixedes** [comment]
Can you post the output of `docker image ls storjlabs/storagenode:alpha`?

**Comment by luzemario** [comment]
luzemario@docker:~$ docker image ls storjlabs/storagenode:alpha
REPOSITORY              TAG                 IMAGE ID            CREATED             SIZE
storjlabs/storagenode   alpha               4a90c9f50266        2 weeks ago         31.5MB

**Comment by ifraixedes** [comment]
you definitely have the last image.

Have you modified the default configuration?
Is the data directory empty?
What file system format is used for the data directory?
Which linux version are you using?

**Comment by luzemario** [comment]
- No.
- Yes.
- 9p/virt-io. It is a libvirt exported folder to a VM running docker using mapped mode. The host FS is a ZFS filesystem.
- tested with Devuan ASCII and Debian Stretch guests. The host is running Devuan ASCII.

**Comment by luzemario** [comment]
I am wondering to check that argument is invalid to database initialisation. How can I check this inside the image?

**Comment by luzemario** [comment]
Most of time I use ServerWorld info when making setups, so you can check the link below if necessary:

[https://www.server-world.info/en/note?os=Debian_9&p=download](https://www.server-world.info/en/note?os=Debian_9&p=download)

Steps to  reproduce the issue:

1. Set up a minimal Devuan/Debian installation using text mode on a boot USB stick or flashcard, and allow only SSH server package to be installed at first. Once installed, I did all the rest by a SSH connection. The hardware I have is a headless 32GB RAM / 5x8TB disks AMD FX8320, but any hardware setup can be used for testing;
2. Set up OpenZFS following the instructions given on [https://github.com/zfsonlinux/zfs/wiki/Debian](https://github.com/zfsonlinux/zfs/wiki/Debian). Since Devuan has no Systemd, you must follow the instructions below to put the ZFS init scripts on the porper initialization directory [https://github.com/zfsonlinux/zfs/tree/master/etc/init.d](https://github.com/zfsonlinux/zfs/tree/master/etc/init.d), in case you use Devuan;
3. Create a filesystem for Storj. I created a filesystem with 2TB quota on a 24TB raidz tank. You can get instructions at [https://docs.oracle.com/cd/E19253-01/819-5461/6n7ht6qu3/index.html](https://docs.oracle.com/cd/E19253-01/819-5461/6n7ht6qu3/index.html) about how to use the `zfs create` command;
4. Set up / Install KVM: [https://www.server-world.info/en/note?os=Debian_9&p=kvm&f=1](https://www.server-world.info/en/note?os=Debian_9&p=kvm&f=1);
5. Create a minimal Debian/Devuan guest, using either installation method (I used virt-manager): [https://www.server-world.info/en/note?os=Debian_9&p=kvm&f=2](https://www.server-world.info/en/note?os=Debian_9&p=kvm&f=2);
6. Share the filesystem created to Storj use to the guest, following the instructions at [http://rabexc.org/posts/p9-setup-in-libvirt](http://rabexc.org/posts/p9-setup-in-libvirt). Make sure the mount is writable inside the guest;
7. Install Docker on guest: [https://docs.docker.com/install/linux/docker-ce/debian/](https://docs.docker.com/install/linux/docker-ce/debian/). For Devuan, please check [https://dev1galaxy.org/viewtopic.php?id=2583](https://dev1galaxy.org/viewtopic.php?id=2583), since it has no Systemd;
8. Follow the Storj guide to get the image, install and run it. The docker image keeps restarting, falling in the topic of this issue.

**Comment by jtolds** [comment]
I would be shocked if boltdb worked over 9pvirtio. The way boltdb works is with mmap, and I don't think 9pvirtio works with mmap. We don't currently support other database backends on the storage node, so you'll have to do something else besides storing data outside of the VM running the storage node binary.

**Comment by ifraixedes** [comment]
@luzemario could you give a try with other storing mechanism and let us know, please?

**Comment by luzemario** [comment]
Hi folks, sorry for the delay.
As @jtolds stated, I think the mmap is the thing here. I deleted all VMs and restarted from scratch, this time giving enough disk space insde the new VM created and not using 9p transport.

All went flawlessly on both OSes, being Devuan my choice for production.

So, one can put all things inside a "docker" virtual machine (for organization purposes), but cannot use external filesystems storage mapped by 9p transport (maybe other "virtual" mechanisms too). VirtIO works, but only if obscured by the guest's native storage mechanism (ext4 in my case).

I must note that a physical disk mapped directly to the VM actually works too, since for boltdb it is a "normal" ext4 FS, but it is not needed in case the VM is given sufficient disk space. Data coming in/out from my Docker VM is rare, so it was the choosen solution.

I suggest you guys to add a note at the instructions page for this case, to avoid 9p or other "external" storage mechanisms.

I am online now. Thank you all for your support. This ticket can be closed  if you want.

**Comment by ifraixedes** [comment]
@luzemario Thanks for the tip.

I've sent a PR to our docs repository to add a note for the _mmap_ requirement on the SN storage file system.
