### ISSUE TITLE
open identity/identity.cert: no such file or directory

### ISSUE THREAD

**Issue by Soubh04** [storj/storj#1948]
Received the following error while trying update my storagenode   
C:\WINDOWS\system32>docker logs -t storagenode

2019-05-11T16:12:00.442505700Z Your configuration is saved to: /app/config/config.yaml
2019-05-11T16:12:00.507605400Z 2019-05-11T16:12:00.507Z INFO    Configuration loaded from: /app/config/config.yaml
2019-05-11T16:12:00.509257300Z 2019-05-11T16:12:00.508Z FATAL   file or directory not found error: open identity/identity.cert: no such file or directory

Followed the instructions mentioned below 
https://github.com/storj/docs/blob/master/Explorer-Release-Setup-Instructions.md#upgrading-your-storage-node

I'm running it on Windows 10 Pro and here is the command 

docker run -d --restart unless-stopped -p 28967:28967 -e WALLET="<My Wallet Info>" -e EMAIL="<Email>" -e ADDRESS="<MyDNS>" -e BANDWIDTH="1TB" -e STORAGE="1TB" -v C:\Users\Soubh\AppData\Roaming\Storj\Identity\storagenode\ -v E:\storagenode\ --name storagenode storjlabs/storagenode:alpha

Please suggest!

**Comment by ReneSmeekes** [comment]
Your paths are not in the right format, try this in CMD.

```
docker run -d --restart unless-stopped -p 28967:28967 -e WALLET="" -e EMAIL="" -e ADDRESS="" -e BANDWIDTH="1TB" -e STORAGE="1TB" -v "C:\\Users\\Soubh\\AppData\\Roaming\\Storj\\Identity\\storagenode\\":/app/identity -v "E:\\storagenode\\":/app/config --name storagenode storjlabs/storagenode:alpha
```

For further help in storagenode set up and much quicker responses, you can join channel #storagenode at community.storj.io .

**Comment by Soubh04** [comment]
It worked, Thanks for your quick response @ReneSmeekes
