### ISSUE TITLE
pkg/transport: Should be the observers be called in DialAddress?

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#2014]
I'm wondering if the transport observers should be called in the [`DialAddress` method](https://github.com/storj/storj/blob/4319b637bf3e1179d2073df3e93196b6201f095b/pkg/transport/transport.go#L141) as they are called in the [`DialNode` method](https://github.com/storj/storj/blob/4319b637bf3e1179d2073df3e93196b6201f095b/pkg/transport/transport.go#L108)

**Comment by jtolds** [comment]
Yes, if we can extract the node id for the observer call. DialAddress does not have a node id before the dial, but after a successful TLS handshake it should be able to get the peer's node id. If we can gather the node id, then the observers should be called.

It's not super important of a case to handle though, so it's low priority. Filed https://storjlabs.atlassian.net/browse/V3-1835

**Comment by ifraixedes** [comment]
Thanks @jtolds I wanted to confirm before opening an issue, but you basically went ahead and opening it.

About the priority, I agree, it should very low.
