### ISSUE TITLE
Segmentation faults showing in the logs

### ISSUE THREAD

**Issue by meetyg** [storj/storj#2022]
I'm running the latest v3 storagenode (v.0.11.1) on an arm64 SBC.
It has been running ok for a while now, but lately it crashes very often. I see that the last logs show some segmentation faults:
```
panic: runtime error: invalid memory address or nil pointer
dereference [recovered]
        panic: runtime error: invalid memory address or nil
pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc
=0x183d0]

goroutine 1 [running]:
gopkg.in/spacemonkeygo/monkit%2ev2.newSpan.func1(0x190c708)
        /go/pkg/mod/gopkg.in/spacemonkeygo/monkit.v2@v2.0.0-
20180827161543-6ebf5a752f9b/ctx17.go:150 +0x2d0
panic(0x880ff0, 0xfc5988)
        /usr/local/go/src/runtime/panic.go:522 +0x1a0
runtime/internal/atomic.goCas64(0x1828e1c, 0x0, 0x0, 0x1, 0x
0, 0x19d8800)
        /usr/local/go/src/runtime/internal/atomic/atomic_arm
.go:83 +0x1c
storj.io/storj/internal/sync2.(*Cycle).Stop(0x1828e0c)
        /go/src/storj.io/storj/internal/sync2/cycle.go:149 +
0x4c
storj.io/storj/internal/sync2.(*Cycle).Close(...)
        /go/src/storj.io/storj/internal/sync2/cycle.go:132
storj.io/storj/storagenode/monitor.(*Service).Close(...)
        /go/src/storj.io/storj/storagenode/monitor/monitor.g
o:121
storj.io/storj/storagenode.(*Peer).Close(0x19dd630, 0xa4e170
, 0x19f5e80)
        /go/src/storj.io/storj/storagenode/peer.go:302 +0x24
8
main.cmdRun(0xfcb6f8, 0x1912cb0, 0x0, 0xe, 0x0, 0x0)
        /go/src/storj.io/storj/cmd/storagenode/main.go:165 +
0x4cc
storj.io/storj/pkg/process.cleanup.func1.2(0xa4e2d0, 0x19147
20)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:259
+0xdc
storj.io/storj/pkg/process.cleanup.func1(0xfcb6f8, 0x1912cb0
, 0x0, 0xe, 0x0, 0x0)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:273
+0x1104
github.com/spf13/cobra.(*Command).execute(0xfcb6f8, 0x1912b6
0, 0xe, 0xe, 0xfcb6f8, 0x1912b60)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go
:762 +0x360
github.com/spf13/cobra.(*Command).ExecuteC(0xfcb5c8, 0x187e0
60, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go
:852 +0x22c
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go
:800
storj.io/storj/pkg/process.Exec(0xfcb5c8)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:56 +
0x154
main.main()
        /go/src/storj.io/storj/cmd/storagenode/main.go:288 +
0x20
```
I guess this is not normal...
I have run a few tests (like memtester) just to make sure that the device's memory is not faulty. But it seems that everything is ok.
Probably just a software bug. Will this be fixed soon ?

**Comment by kaloyan-raev** [comment]
@meetyg are you compiling the `storagenode` binary yourself from source? Or are you using the docker container as per these instructions: https://github.com/storj/storj/wiki/Explorer-Release-Setup-Instructions ?

**Comment by meetyg** [comment]
Just using the Docker container, running watchtower also. I suspect something that maybe these errors apear as watchtower tries to stop the container (not sure why, I'm running the latest version) but as it takes a long time to shutdown, it forcefully kills it.
I have stopped using watchtower for now, so I will check if these errors arise again.

If the problem is like I suspect, a solution would be to adjust watchtower's timeout. Even when I manually run `docker stop storagenode` it takes a while untill it shuts down.

**Comment by jtolds** [comment]
Will you confirm that our latest release (which includes https://github.com/storj/storj/commit/dc2e6b9370a39b3b72a197f2876d41abf4f9d8fd) fixed it?

**Comment by ifraixedes** [comment]
>  I suspect something that maybe these errors apear as watchtower tries to stop the container 

We have those panics in the logs when the container is stopped, we have an open issue to solve it, but it's a low priority now.
If your suspicions are correct, then that's the source of those panics.

@jtolds, we'll check if that fixed that issue.

**Comment by meetyg** [comment]
@ifraixedes 
> Will you confirm that our latest release (which includes [dc2e6b9](https://github.com/storj/storj/commit/dc2e6b9370a39b3b72a197f2876d41abf4f9d8fd)) fixed it?

Looking at the commit, it seems like it should be done anyways (even without the errors I am seeing), because Storj doesn't currently have arm64 images, only 32 bit (right?)

So I updated to latest version (12.1 i think) using watchtower. I will have a look to see if I get errors again (maybe excluding when I know that the container has been stoppedb either manually or by watchtower).
Thanks for your feedback. I will update you after having the latest running for at least a day.

**Comment by meetyg** [comment]
Just now I tried to stop the container, and I don't see the segmentation faults. So changing the atomics to 32 bit might have fixed that.
I will keep an eye on the logs to make sure they don't appear again.

**Comment by aligeti** [comment]
Just checking @meetyg how it working so far for you now? If it fixed then we can close this ticket. Let me know

**Comment by ifraixedes** [comment]
I confirm that stoping the container which runs the last ARM docker image doesn't panic anymore, so https://github.com/storj/storj/commit/dc2e6b9370a39b3b72a197f2876d41abf4f9d8fd fixed the issue.

@meetyg if you have other panic open a new issue or contact with us through our support channels.

**Comment by meetyg** [comment]
It looks fine for now :+1:
