### ISSUE TITLE
storj/src/storj.io/storj/pkg/kademlia/config.go:7:2: cannot find package "context" in any of:

### ISSUE THREAD

**Issue by alebeta90** [storj/storj#203]
Hello friends,

I'm trying to run the test and I'm getting the next message:

storj@storj:~$ go test storj.io/storj/...
storj/src/storj.io/storj/pkg/kademlia/config.go:7:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/alebeta/storj/src/context (from $GOPATH)
	/home/alebeta/storj/vendor/src/context

I'm running the node on Ubuntu Server 16.04 up to date.

Let me know if you need more logs or information.

Kind Regards,
Alebeta

**Comment by kaloyan-raev** [comment]
It looks like you have an older version of Go. Make sure to manually install the latest one from https://golang.org/dl/

**Comment by alebeta90** [comment]
@kaloyan-raev 
thanks for you help, yes with Ubuntu 16.04 go version is 1.6.x and is better to use the go repo to have an up to date version.

Now I manage to perform the test.

Thanks and all the best

**Comment by alebeta90** [comment]
thanks
