### ISSUE TITLE
Create a faulty/non deleteable bucket or it is possible to create a bucket without encryption key

### ISSUE THREAD

**Issue by BlackDuck888** [storj/storj#2075]
I missed to set/correct my enc.key in config.yaml of uplink. In this result, it is possible to create a bucket without or with incorrect encryption settings. 

A bucket created in this way can't be deleted, overwritten or used for uploads.

```
./uplink version
Release build
Version: v0.12.2
Build timestamp: 29 May 19 06:52 CEST
Git commit: d174bef3449a6c1409e5794523a644afe5831cce
```

in my config.yaml `enc.encryption-key` and `enc.key-filepath` are missing.

```
./uplink mb sj://test1234
Bucket test1234 created

./uplink rb sj://test1234
Fatal error: libuplink: No encryption key chosen
2019-05-29T19:39:03.677+0200    DEBUG   Fatal error: libuplink: No encryption key chosen
        storj.io/storj/lib/uplink.(*Project).OpenBucket:161
        storj.io/storj/cmd/uplink/cmd.(*UplinkFlags).GetProjectAndBucket:125
        storj.io/storj/cmd/uplink/cmd.deleteBucket:49
        storj.io/storj/pkg/process.cleanup.func1.2:270
        storj.io/storj/pkg/process.cleanup.func1:284
        github.com/spf13/cobra.(*Command).execute:762
        github.com/spf13/cobra.(*Command).ExecuteC:852
        github.com/spf13/cobra.(*Command).Execute:800
        storj.io/storj/pkg/process.Exec:59
        main.main:12
        runtime.main:200
```

I would expect if a bucket can't be used without encryption, that I am not able to create it in that way.

**Comment by ifraixedes** [comment]
The issue that you comment regarding creating buckets without an encryption key and after no being able to operate with them, was identified a few weeks ago, however we haven't solved yet.

On the other hand the `enc.encryption-key` was never meant to appear in the configuration file, there is a new setting `enc.key-filetpath` which should point to a file which, for now, it contains the encryption key. Nonetheless, we have identified a bug in the current release, which is causing to write the `enc.encryption-key` in the configuration file and we are working on it

Thanks for reporting it and for your patience.

**Comment by BlackDuck888** [comment]
The Problem is more than `create bucket` should through an error when there no encryption key, file or what else is missing. A incorrect setup should not create a bucket.

**Comment by ifraixedes** [comment]
> The Problem is more than create bucket should through an error when there no encryption key, file or what else is missing. A incorrect setup should not create a bucket.

As I said, we haven't solved yet, we are still discussing if a bucket must require an encryption key or not, so depending of the decision the fix is what you're saying otherwise would be another one.

**Comment by jtolio** [comment]
`uplink rb --force sj://bucket` exists now, does that solve this ticket?

**Comment by BlackDuck888** [comment]
It did. Thanks a lot.
