### ISSUE TITLE
[Feature] Support i2p

### ISSUE THREAD

**Issue by ghbjklhv** [storj/storj#2218]
We should implement i2p for better IP anonymity among users.

**Comment by 2mf** [comment]
@ghbjklhv 
I2P is far too slow in the means for transfer speed.
If you really wanna run a satellite behind behind i2P or as TOR hidden service, you can do that but what for?
The stored data on a node, is already encrypted on the client side and so far what is your concern for anonymity, you still have to pay for the data that is stored in the network.
