### ISSUE TITLE
Error while 'Starting the network'

### ISSUE THREAD

**Issue by anujpahade** [storj/storj#223]
$ go install -v storj.io/storj/cmd/captplanet
This command terminates unsuccessfully because of a syntax error at

https://github.com/storj/storj-vendor/tree/master/src/github.com/anacrolix
Here's a screenshot.
![storjisssuesettingupnetwork](https://user-images.githubusercontent.com/23260728/43994974-b30d648a-9dc3-11e8-911c-e4d0355d70c5.png)

**Comment by jtolds** [comment]
Please upgrade the Go version you're using. We're using Go 1.10.
