### ISSUE TITLE
Storage node should send back-off to satellite when overloaded

### ISSUE THREAD

**Issue by JL421** [storj/storj#2290]
**Background**
As storage nodes start filling with more data SNOs are finding that their nodes are taking longer to startup (dashboard being available). The issue appears to be related to the time it takes to verify the info.db file during startup. During this verification the node is actually online and receiving requests. This is a good thing as it helps a SNO avoid more of a downtime penalty as more data is added, and at ~1TB of data a normal HDD will take between 5 and 15 minutes to read through the info.db file.

**Problem**
When testing a node startup time of about 30 minutes I noticed that the satellite requested an audit, and the node didn't respond. The satellite requested the same piece again about 5 minutes later and still no response from the node. After the third request without a response the satellite appeared to stop sending any requests to the node for about an hour, after which time it requested the same piece again, the node responded, and requests started coming in again.

The concern is that after a number of unanswered audits the satellite will consider the audit failed and eventually disqualify an otherwise "healthy" node that may have triggered the info.db verification for some reason.

**Solution**
Node behavior should be changed to account for situations of extremely delayed responses to piece requests. This includes node startup or other situations like garbage collection where a disk may be extremely overloaded or the database could be locked. In these types of situations the workflow should be as follows:
1) Any piece request is received from satellite
2) Node is overloaded and responds with a back-off message instead of nothing
3) Satellite puts node in a back-off containment mode but does not count a audit failure if that was the initial request
4) While in back-off containment the node is sent no further requests until a 5 minute timer expires
5) When the timer expires the satellite can send a hello, resume normal requests, or retry the requested audit
6) If node is available again, proceed normally, otherwise repeat steps 2-5
7) If node reaches more than 12 hours of consecutive back-offs (or another time length) it is put into normal containment and is treated as a potentially misbehaving host

**Comment by littleskunk** [comment]
The issue is that the database is locked while the order sender is active. We are working on a fix.

> Any piece request is received from satellite
That will catch only repair and audit traffic. Uploads and downloads are no satellite requests.

> Node is overloaded and responds with a back-off message instead of nothing
This would mean the storage node is offline and we support that offline periode. That is not going to work. We are sensitive to repair. If the node goes offline and the repair threshold gets triggered we have to repair it asap because otherwise we risk loosing files. We can't wait a few hours and ask the node if it can now respond. We have to repair as quickly as possible.

Instead we should fix the reason why the storage node gets into this state. It should take seconds to read the info.db file. The issue right now is that the order sender is locking the database for a long time. We are working on a fix.

**Comment by JL421** [comment]
`It should take seconds to read the info.db file.`
If it was a non-fragmented sequential read, you're right, but you are processing a 2GB+ sqlite db with a single thread, probably on rotational media that is severely fragmented. That file is written to between every request, and normal disk write scheduling is going to end up throwing that file all over the disk, unless it is stored on a COW filesystem. Normal operation will never see that taking seconds to read, and it will get exponentially worse as more data is stored on a node.

**Comment by littleskunk** [comment]
> Then prevent the node from accepting connections at all until it is fully operational. If you are going to accept requests that could disqualify a node when not answered at a time when the node will not answer them, you need to provide an "I'm busy" response rather than no response.

The node will get disqualified for that as well. The result is the same. Keep in mind we have to run repair asap because otherwise we risk loosing files.

Once again. We identified the issue (database is locked) and are working on a fix.

**Comment by JL421** [comment]
> The node will get disqualified for that as well. The result is the same. Keep in mind we have to run repair asap because otherwise we risk loosing files.

If you have reached the threshold for repair, and the node is requesting a back-off then by all means start a repair. However in normal network operation, one node offline or busy isn't going to trigger a repair function.

Let's look at this a different way. Say a piece is nearing the repair threshold through normal node failure/offline status. For the sake of argument, let's say we're two pieces from that threshold.

Now Node A is sent an audit but reports busy. We honor the request because up until this point the reputation has been fine and it hasn't been disqualified. The node is in the temporary containment state and the piece is marked out. This leaves us one piece before the threshold.

Next, Node B has a power outage and starts rejecting all connections. The degraded piece now triggers the repair threshold and the repair process starts. The satellite contacts all known nodes for the pieces, but Nodes C, D, F, and K have had silent corruption of the piece since the last audit. We suddenly no longer have enough healthy nodes to rebuild the data, and normally would be unable to recover the data until enough nodes came back online.

However, Node A voluntarily told us it was just busy, and rather than continuously spamming audit requests until we marked it a confirmed failure and discarding the piece, we can at least wait until the node responds and possibly recover the full stripe.

-----

By allowing the mechanism for nodes to tell the satellite they are busy and to skip them **for now**, the network only benefits. We can still practice zero trust for repair purposes and mark pieces as down, but retaining the ability to possibly recover later. We can allow the satellite to provide a non-busy node to a client and improve client-side performance. We allow nodes to not fully be disqualified when they may still be alive, but just temporarily overloaded.

There's probably a way to abuse it, but that'd get detected by the other reputation mechanisms fairly quickly.

**Comment by littleskunk** [comment]
> However, Node A voluntarily told us it was just busy, and rather than continuously spamming audit requests until we marked it a confirmed failure and discarding the piece, we can at least wait until the node responds and possibly recover the full stripe.

We will just disqualify the node if it fails too many audits or is offline. Your example is showing the reason. We can't tollerate that the file is not available for downloads.

*We are working on a fix*
