### ISSUE TITLE
info.db auto corrupting

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj/storj#2300]
I found issue that info.db can be automatically corrupted during regular operations with storage node.
For example:
`docker stop storagenode`
look into cat syslog `cat /var/log/syslog`
`Jun 23 10:27:26 docker02 dockerd[459]: time="2019-06-23T10:27:26.297789988+03:00" level=info msg="Container ff207cc0f05838dddd7947eac866b0adf17440069c870d692a1eee2ef0fb90d6 failed to exit within 10 seconds of signal 15 - using the force"
`
So, docker waiting only 10 sec. by default for container stop and then killing it.
The same situation with watchtower during storagenode upgrade.

The root cause: 10 sec. is not enough for correct stop storage node on any hardware (and ultrafast too).

I propose just update documentation and extend timeout limits.

for stop storagenode:
`docker stop storagenode -t 300`

for watchtower:
`docker run -d --restart=always --name watchtower -v /var/run/docker.sock:/var/run/docker.sock storjlabs/watchtower storagenode watchtower --stop-timeout 300s`

**Comment by littleskunk** [comment]
Would you like to open a PR? https://github.com/storj/storj/wiki/Explorer-Release-Setup-Instructions

**Comment by AlexandrTyshchenko** [comment]
Yep, will try it

**Comment by AlexandrTyshchenko** [comment]
@ReneSmeekes Thanks a lot!

**Comment by kaloyan-raev** [comment]
Thank you @AlexandrTyshchenko and @ReneSmeekes for identifying the issue and improving the documentation with the solution.

I am closing this issue. If there is still anything else to do, please reopen it.
