### ISSUE TITLE
Voucher request denied. Node does not meet voucher requirements: ANY (disqualified?, total audit count, total uptime check count)

### ISSUE THREAD

**Issue by Jason7124** [storj/storj#2344]
How do I findout why my request is denied?

**Comment by kaloyan-raev** [comment]
Soon we will have a dashboard for storage node operators to check their stats on the satellites.

For the time being, we can check them manually if you provide the ID of your storage node.

**Comment by Jason7124** [comment]
Ok thanks.  I thought I was missing something. 

1X1usWVChWYGpwekPLqqkrs7xCAWCTnjZU8VdJ67nDnacn85ya

**Comment by heunland** [comment]
Hi, I have checked your nodeID. This node has only been online for 2 days, so it is still in the early vetting stage. This is why you got the "Voucher request denied" message. Your node will remain in vetting until you have successfully completed 500 audits, and during that stage you will be receiving less data than a vetted node. Please keep the node online as much as possible to achieve the best reputation and not miss any audits.

**Comment by alekosa** [comment]
Hi @heunland ,

Would you please also check ID 1VSbb4e5Agu4BaeG3CGG9ZuTAUT6UQLTjQMYA8g5vV9zwHK8fn
Updated to latest alpha and just found out by accident the same message. Surprisingly, storage still gets utilized, neighborhood size is above 300, satellites send and receive data, as judging by log. 

Thank you.

**Comment by heunland** [comment]
This node has been online a few months but it still has not completed sufficient audits for vetting to be finished. The uptime could be improved a bit. Keep the node online with minimum downtime possible and eventually you should achieve good reputation. This node is not disqualified (as of yesterday, which is the latest snapshot I have of the node stats) It is normal to see the message you encountered after you updated the storagenode version, as the node is unvetted.

**Comment by alekosa** [comment]
Thanks!

**Comment by cryptonotifier** [comment]
Can you also please chek ID 1EV2NkMcv7X2rrdDbQgbqsLfu8HBjC77VbMbFe7TX2XtndKwBU ?

**Comment by heunland** [comment]
When did you start running that node? If you just installed it, it is now in vetting.

**Comment by heunland** [comment]
If not, please make a support ticket at support@storj.io rather than adding to an already closed issue here on github.
