### ISSUE TITLE
V3 Dashboard only reports config path and Node ID

### ISSUE THREAD

**Issue by Jason7124** [storj/storj#2371]
Once I upgraded to 14.3 the dashboard no longer works properly  All I get when I run:

docker exec -it storagenode /app/dashboard.sh

is:

2019-06-28T04:23:01.004Z        INFO    Configuration loaded from: /app/config/config.yaml
2019-06-28T04:23:01.026Z        INFO    Node ID: 1X1usWVChWYGpwekPLqqkrs7xCAWCTnjZU8Vd.....

Any ideas?

**Comment by kaloyan-raev** [comment]
How long do you wait before you kill the command?

Could you leave it for a longer time? Sometimes storage nodes are busy with some operations like order sending and the info database is locked for a long period. This would affect the dashboard too. We are aware of such issues and will improve them in the next releases.

**Comment by Jason7124** [comment]
I’ve run it for 8-10 minutes and then I gave up.  I will try longer

**Comment by stefanbenten** [comment]
@Jason7124 Any updates if that issue is resolved? Especially on low powered devices, this process can take quite some time, due to current database operations during startup.

**Comment by Jason7124** [comment]
It is working very quickly now. Thinking back on it, I was expanding my raid5 at the time and the volume was heavily utilized.  It a good chance that was my whole trouble
