### ISSUE TITLE
The container does not start with a total disk size of 961 GB, but the free space is less than 500 GB

### ISSUE THREAD

**Issue by Crash343** [storj/storj#2393]
mount not available when docker container starts.

Docker runs on a unraid Server.
Data and identity moved from a debian Server.

[log.txt](https://github.com/storj/storj/files/3341789/log.txt)
[start commands and disk usage.txt](https://github.com/storj/storj/files/3341790/start.commands.and.disk.usage.txt)

**Comment by AlexeyALeonov** [comment]
As figured out, the mapping was incorrect. There was another copy of the data
