### ISSUE TITLE
Peer Verification error

### ISSUE THREAD

**Issue by shivam201312** [storj/storj#2468]
Hi...
I am getting this error while i am trying to connect storj developer lib code to storj test network .

**metainfo error: transport error: connection error: desc = "transport: authentication handshake failed: tls peer certificate verification error: not signed by any CA in the whitelist: CA cert**

Any solution for this error ?

And from where i can find **encryption key** for storj developer lib ?

**Comment by stefanbenten** [comment]
Hello @shivam201312 ,

you need to skip the CA whitelist check like so:
```
var cfg uplink.Config
cfg.Volatile.TLS.SkipPeerCAWhitelist = true
upl, err := uplink.NewUplink(ctx, &cfg)
```

In which sense do you mean find encryption key?

**Comment by shivam201312** [comment]
Thank you @stefanbenten  for replying. now my  program is working fine.
