### ISSUE TITLE
Error Uploading object (ecclient error)

### ISSUE THREAD

**Issue by shivam201312** [storj/storj#2530]
Hi....
My code is running fine when i am try to upload data to bucket on  storj-sim (storj test network) but when i am running same program for uploading larger data on storj network . 
I am getting this error 
**Error uploading object  segment error**: ecclient error: successful puts (0) less than or equal to repair threshold (35); segment error: ecclient error: successful puts (0) less than or equal to repair threshold (35)

Program is working fine when i upload small amount of data .

Question 
1) I want to know more about this error.
2) How can i resolve this error ?

**Comment by ifraixedes** [comment]
How are you uploading the data with the uplink CLI or with a program that you have built which uses the libuplink?

**Comment by shivam201312** [comment]
Hi.... @ifraixedes  , I am uploading data  using program  and i am getting encryption error while trying to access bucket created by uplink CLI .

**Comment by ifraixedes** [comment]
Could you post the implementation or at least, the part that creates the uplink and uploads the data please? 

We'll try to spot time to takes a look.

**Comment by littleskunk** [comment]
The reason for this was a problem on the storage node side. We have fixed it with v0.15.3. Uploads should now work fine.

**Comment by stefanbenten** [comment]
@shivam201312 Is that issue still persistent?
If not please close here, thank you!

**Comment by shivam201312** [comment]
@stefanbenten Problem is solved . Thank you
