### ISSUE TITLE
Watchtower pull not working on Odroid N2

### ISSUE THREAD

**Issue by riegaz** [storj/storj#2538]
```
root@odroid:~# docker rmi storjlabs/watchtower:latest
Error: No such image: storjlabs/watchtower:latest
```

```
root@odroid:~# docker pull storjlabs/watchtower
Using default tag: latest
latest: Pulling from storjlabs/watchtower
no matching manifest for unknown in the manifest list entries
```

:latest-arm32v6 

works.

I guess it should work since it works for rpis?

**Comment by ifraixedes** [comment]
What's exactly your question or problem?

Does the `storjlabs/watchtower:latest-arm32v6` image work?

**Comment by riegaz** [comment]
Yes, it works. Aleksey told me to create a bug report because it should work with just putting :latest

https://docs.storj.io/discuss/5d281061bcf7d80056a16d89

**Comment by ifraixedes** [comment]
Ok, I'm clear now what we should fix.

**Comment by riegaz** [comment]
Perfect. Sorry in case I didn't made myself clear enough.

**Comment by ifraixedes** [comment]
I've opened an ticket related to this issue.
https://storjlabs.atlassian.net/browse/V3-2155

**Comment by Velociraptor85** [comment]
have a similar problem with my pine64 which is based on an arm64 ... seems like the watchtower docker repository has no such [tag ](https://hub.docker.com/r/storjlabs/watchtower/tags)

**Comment by Velociraptor85** [comment]
so apparently this works now on my pine64
thanks! for adding the tag ;) https://hub.docker.com/r/storjlabs/watchtower/tags

**Comment by ifraixedes** [comment]
@riegaz have you tried to swap back to use `storjlabs/watchtower:latest`? it would be cool to know if it currently works.

Thanks for your cooperation.

**Comment by riegaz** [comment]
```
root@odroid:~# docker pull storjlabs/watchtower
Using default tag: latest
latest: Pulling from storjlabs/watchtower
a6426269837d: Pull complete
56668425aeba: Pull complete
d35e28fb0195: Pull complete
Digest: sha256:6accfdce9f39eedb957dd8ce20db3eff0872b33a4708b897ecaddfe967b2b941
Status: Downloaded newer image for storjlabs/watchtower:latest
```
Seems to work now!
