### ISSUE TITLE
Memory leak in v0.14.11

### ISSUE THREAD

**Issue by nathandragun** [storj/storj#2552]
After the jump to version 0.14.11 there has been a steady increase in ram usage until program termination.  It managed to consume 8GB of ram and an addition 3.5GB of swap space in under twenty four hours.

The current screenshots below shows the node running after only 12h consuming approximately 6GB of ram.  (Since I started writing this issue the current usage values have grown to 96.4% ram usage and 5% swap space.)

![ram usage](https://user-images.githubusercontent.com/40903109/61164956-62e42e80-a4e8-11e9-9c0d-2526e81b2688.PNG)

Once the container is manually restarted the usage reduces down to expected levels.

![ram usage reset](https://user-images.githubusercontent.com/40903109/61165034-48f71b80-a4e9-11e9-879a-b498966a7793.PNG)

Node details:
OS: Ubuntu 18.04.02 LTS
Docker version 18.09.7, build 2d0083d
Bandwith:   638.5TB / 1.5TB / 583.6GB / 0.9TB
Disk:    17.1TB / 0.9TB

**Comment by 2mf** [comment]
it seems the memory issue is tied to `storage2.max-concurrent-requests` been 7 by default and resulting in many/a lot of rejected uploads due to the concurrency level being higher than 7.

I did run into memory issues as @nathandragun did. 
However after setting  `storage2.max-concurrent-requests` to 25 or even higher seemed ease the memory problem a bit.

**Comment by nathandragun** [comment]
> it seems the memory issue is tied to `storage2.max-concurrent-requests` been 7 by default and resulting in many/a lot of rejected uploads due to the concurrency level being higher than 7.
> 
> I did run into memory issues as @nathandragun did.
> However after setting `storage2.max-concurrent-requests` to 25 or even higher seemed ease the memory problem a bit.

This is very interesting as I thought there was a correlation around `storage2.max-concurrent-requests` as well, but from a completely different angle.  I have a 1G symmetric fiber connection and noticed that before the recent updates, while very low, traffic would occasionally burst to 150Mbps with GET/PUT requests.  With the new `storage2.max-concurrent-requests` default value of 7 the overall network speeds dropped to an average of 5Mbps for GET/PUT requests.  As a result I bumped the value up to 200.  While I was not seeing the previous levels of 150Mbps for throughput with the increased value, at least it was no longer dropping requests.  The OP results reflect a value of 200 for `storage2.max-concurrent-requests`.


UPDATE
After the OP data was presented I set `storage2.max-concurrent-requests` to a value of 50, thinking that setting the value that high was causing the issue.  After another twelve hours the ram usage numbers were a bit lower, with about 7% less ram usage.

![mem usage concurrent 50](https://user-images.githubusercontent.com/40903109/61172646-0cf9a000-a555-11e9-8d6b-f273977694ee.PNG)

Since the issue is seen with both high and low values for `storage2.max-concurrent-requests` it makes me wonder if the issue is related to the actual number of requests received during a specific time period and not so much the request hard limits.

**Comment by 2mf** [comment]
This is indeed interesting. After watching a node of mine still using more and more memory until the OoM killer hits, even with values around 25 or 50 it still has this leak. So it can't be that.
Compared to another node of mine which is 100% full the memory issues doesn't exists, so it must be correlated to upload requests rather than downloads.

**Comment by littleskunk** [comment]
Fixed with v0.14.13.
