### ISSUE TITLE
Audit Failed Due to busy Satellite?

### ISSUE THREAD

**Issue by gsxryan** [storj/storj#2636]
This is just a warning audit failure, but is this acceptable since it's recoverable?

![image](https://user-images.githubusercontent.com/2055136/61893399-97d28700-aed3-11e9-9845-e35419fb3968.png)

**Comment by coyle** [comment]
Looks like a timed out connection while downloading in `stream.Recv()`

**Comment by gsxryan** [comment]
Is that fault of the SNO or Sat?  Or, not enough info to determine?

**Comment by stefanbenten** [comment]
This error is acceptable and not a problem. As @coyle mentioned it was a timeout during the recv, which can be a problem on either end.
You will be in containment mode and can pass the audit on the next cycle (thus its recoverable) 👍
