### ISSUE TITLE
blob-226380426.partial remains in temp directory

### ISSUE THREAD

**Issue by fgrueninger** [storj/storj#2639]
Just noticed that there's one .partial file in my temp directory that has neither deleted or moved since over 24h.
No errors in my logs around when the file has been created.

**Comment by ifraixedes** [comment]
If you stop the docker container and the file is still there, then you can delete it and start the container again.

**Comment by fgrueninger** [comment]
Well, the question is why did it happen, and is a piece now missing on my disk.

**Comment by egonelbre** [comment]
If move out of the temp directory fails the piece will not be committed in the database, so all the pieces should be fine. This can be cross validated by checking whether all pieces in pieceinfo table are in the blob directory.

I don't know your exact setup, but my best guess is that the upload to the storage node was canceled for some reason and then something prevented the deletion, which is quite common with Windows.

**Comment by fgrueninger** [comment]
>This can be cross validated by checking whether all pieces in pieceinfo table are in the blob directory.

How do I get the filenames from the pieceinfo table?

**Comment by fgrueninger** [comment]
Never mind, figured it out - will reopen if required.

Thanks!
