### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vatov** [storj/storj#2672]
Node is stuck in restarting mode:
cenots7
log error:

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb7b1a2]

goroutine 1 [running]:
gopkg.in/spacemonkeygo/monkit%2ev2.newSpan.func1(0xc00018d610)
        /go/pkg/mod/gopkg.in/spacemonkeygo/monkit.v2@v2.0.0-20190612171030-cf5a9e6f8fd2/ctx17.go:150 +0x366
panic(0xd70ca0, 0x18761a0)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
storj.io/storj/storagenode/bandwidth.(*Service).Close(0x0, 0xfcb640, 0xc000156410)
        /go/src/storj.io/storj/storagenode/bandwidth/service.go:60 +0x22
storj.io/storj/storagenode.(*Peer).Close(0xc000158dd0, 0xc00021adc0, 0x13)
        /go/src/storj.io/storj/storagenode/peer.go:397 +0x3e4
storj.io/storj/storagenode.New(0xc0002c5ce0, 0xc00013aba0, 0xfd2a00, 0xc0003565a0, 0xc00021abe0, 0x16, 0xc00021ac60, 0x15, 0xc0001de300, 0x1c, ...)
        /go/src/storj.io/storj/storagenode/peer.go:170 +0x2ad9
main.cmdRun(0x18822a0, 0xc0001d36b0, 0x0, 0xb, 0x0, 0x0)
        /go/src/storj.io/storj/cmd/storagenode/main.go:143 +0x535
storj.io/storj/pkg/process.cleanup.func1.2(0xfc9040, 0xc000220140)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:321 +0x103
storj.io/storj/pkg/process.cleanup.func1(0x18822a0, 0xc0001d36b0, 0x0, 0xb, 0x0, 0x0)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:335 +0x17cb
github.com/spf13/cobra.(*Command).execute(0x18822a0, 0xc0001d3600, 0xb, 0xb, 0x18822a0, 0xc0001d3600)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x1882040, 0xc00007c180, 0x1, 0x1)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
storj.io/storj/pkg/process.Exec(0x1882040)
        /go/src/storj.io/storj/pkg/process/exec_conf.go:75 +0x180
main.main()
        /go/src/storj.io/storj/cmd/storagenode/main.go:288 +0x2d

**Comment by stefanbenten** [comment]
@ethanadams Is that related to your recent PR?

**Comment by ethanadams** [comment]
I've committed a fix for the nil pointer issue on close. However, the issue that's causing the close to happen seems to be while initializing the server listener.  Can you provide more logs around this incident?

**Comment by vatov** [comment]
Hi, this happened after updating to ver. 16.1 yesterday. Even removed container and installed again.
log is generating only attached part of the log above. which logs will help you to troubleshoot?

**Comment by ethanadams** [comment]
Can you provide your config.yaml (removing any private data) and any arguments used when starting the storagenode process?

**Comment by vatov** [comment]
Hi, sorry for late replay

root@centos2:~# cat /mnt/storj/config.yaml
identity.cert-path: "identity/identity.cert"
identity.key-path: "identity/identity.key"
kademlia.external-address: ""
kademlia.operator.email: ""
kademlia.operator.wallet: ""
log.level: info
server.address: "*****:28967"
server.debug-log-traffic: false
server.private-address: "127.0.0.1:7778"
storage.allocated-bandwidth: 20.0 TB
storage.allocated-disk-space: 10.0 TB

-----
docker run -d --restart unless-stopped -p 28967:28967 \
    -e WALLET="************************ \
    -e EMAIL="***************" \
    -e ADDRESS="*********:28967" \
    -e BANDWIDTH="20TB" \
    -e STORAGE="10TB" \
    -v "/root/.local/share/storj/identity/storagenode":/app/identity \
    -v "/mnt/storj":/app/config \
    --name storagenode storjlabs/storagenode:alpha

**Comment by ethanadams** [comment]
Please provide some hardware details.

And has any of your configuration/startup changed since you last successfully ran the storage node?

**Comment by vatov** [comment]
No - nothing changed, but node started after changing following (to defaults i think):

# total allocated bandwidth in bytes$
storage.allocated-bandwidth: 500.0 GiB$
# total allocated disk space in bytes$
storage.allocated-disk-space: 1.0 TB$

**Comment by egonelbre** [comment]
Based on the stack trace it looks like it's unable to start the server. Unfortunately there's a bug that prevents the actual error being printed.

```
storj.io/storj/storagenode.New(0xc0002c5ce0, 0xc00013aba0, 0xfd2a00, 0xc0003565a0, 0xc00021abe0, 0x16, 0xc00021ac60, 0x15, 0xc0001de300, 0x1c, ...)
/go/src/storj.io/storj/storagenode/peer.go:170 +0x2ad9
```

The config shows that `server.address: "*****:28967"`, note this should be the listening address not the external address i.e. `127.0.0.1:28967`. Since docker doesn't have access to your external address. The external address should be specified in: 

```
kademlia.external-address: ""
kademlia.operator.email: ""
kademlia.operator.wallet: ""
```

Or the full external address as an argument to docker. `-e ADDRESS=":28967" `

**Comment by vatov** [comment]
ok - thank you for the support, editing config.yaml brings node up without errors.

**Comment by uofm-matt** [comment]
I'm getting this error now as well in a docker container.  Been working just fine up until now, but it's restarting constantly. Error below.  All databases test clean.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc90bd8]

goroutine 1107 [running]:
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a1e0)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a210)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a250)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a3d0)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
storj.io/storj/storage/filestore.(*Dir).EmptyTrash.func1({0x1437c30, 0xc00045bf20})
        /go/src/storj.io/storj/storage/filestore/dir.go:486 +0x458
storj.io/storj/storage/filestore.walkNamespaceWithPrefix({0x1437920, 0xc00049e500}, 0x0?, {0xc000310140, 0x20, 0x20}, {0xc0008f4730?, 0x7f062bdb41d8?}, {0xc0008d0170, 0x2}, ...)
        /go/src/storj.io/storj/storage/filestore/dir.go:797 +0x3c6
storj.io/storj/storage/filestore.(*Dir).walkNamespaceInPath(0xc0000b6240, {0x1437920, 0xc00049e460}, {0xc000310140, 0x20, 0x20}, {0xc0008e60a8, 0x14}, 0x40ebc7?)
        /go/src/storj.io/storj/storage/filestore/dir.go:743 +0x692
storj.io/storj/storage/filestore.(*Dir).EmptyTrash(0xc0000b6240, {0x1437920, 0xc00049e3c0}, {0xc000310140, 0x20, 0x20}, {0x7f062bdb41d8?, 0x20?, 0x1b26fa0?})
        /go/src/storj.io/storj/storage/filestore/dir.go:479 +0x2ea
storj.io/storj/storage/filestore.(*blobStore).EmptyTrash(0xc00000e558, {0x1437920, 0xc00049e320}, {0xc000310140, 0x20, 0x20}, {0x78c8cb?, 0x1437450?, 0x1b26fa0?})
        /go/src/storj.io/storj/storage/filestore/store.go:155 +0x1c7
storj.io/storj/storagenode/pieces.(*BlobsUsageCache).EmptyTrash(0xc000042380, {0x1437920, 0xc00049e320}, {0xc000310140, 0x20, 0x20}, {0x8?, 0x16?, 0x1b26fa0?})
        /go/src/storj.io/storj/storagenode/pieces/cache.go:316 +0x10e
storj.io/storj/storagenode/pieces.(*Store).EmptyTrash(0xc0000a7860, {0x1437450, 0xc000640900}, {0x84, 0xa7, 0x4c, 0x2c, 0xd4, 0x3c, 0x5b, ...}, ...)
        /go/src/storj.io/storj/storagenode/pieces/store.go:381 +0x1d2
storj.io/storj/storagenode/pieces.(*TrashChore).Run.func1.1({0x1437450, 0xc000640900})
        /go/src/storj.io/storj/storagenode/pieces/trashchore.go:83 +0x2f8
storj.io/common/sync2.(*Workplace).Start.func1()
        /go/pkg/mod/storj.io/common@v0.0.0-20230201101354-04e35e465ace/sync2/workplace.go:89 +0xc9
created by storj.io/common/sync2.(*Workplace).Start
        /go/pkg/mod/storj.io/common@v0.0.0-20230201101354-04e35e465ace/sync2/workplace.go:67 +0x30a

**Comment by stefanbenten** [comment]
@uofm-matt Would you mind opening a new issue for this? That way its easier to track and reference 👍
