### ISSUE TITLE
Satellite GUI did not work

### ISSUE THREAD

**Issue by yangjian102621** [storj/storj#2792]
I start a test-net of storj according to the doc [Run Storj Test Network](https://github.com/storj/storj/wiki/Test-network).

There is no errors in terminal console, but when  i visited Satellite Console (http://127.0.0.1:10002)
it return a 404 error page.

> Note: the Gateway(http://127.0.0.1:11000) works well.

**Comment by stefanbenten** [comment]
Hello!
You have to compile the frontend first, to get it working.
Change into the directory web/satellite and run npm install and npm run build.
You might also need to set the folder in the config file of the storj-sim Satellite.

**Comment by yangjian102621** [comment]
@stefanbenten 

Thanks,  the probelm disappeared, but there is another error in chrome console

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' *.stripe.com cdn.segment.com".


    at Object../src/main.ts (app.js:12450)
    at __webpack_require__ (app.js:724)
    at fn (app.js:101)
    at Object.0 (app.js:13317)
    at __webpack_require__ (app.js:724)
    at app.js:791
    at app.js:794
```
> Note: i build the Satellite with `--mode=development`, because i don't hava a account.
