### ISSUE TITLE
ERROR while creating a bucket through lib/uplinkc

### ISSUE THREAD

**Issue by engrvivs-neosoft** [storj/storj#3137]
Hi

On executing the [bucket_test.c](https://github.com/storj/storj/blob/master/lib/uplinkc/testdata/bucket_test.c), I am getting the following error:
```
failed:
	bucket_test.c:31: bucket: metainfo error: rpc error: code = Unauthenticated desc = rpc error: code = Unauthenticated desc = Missing API credentials
	storj.io/storj/uplink/metainfo.(*Client).CreateBucket:318
	storj.io/storj/uplink/storage/buckets.(*BucketStore).Create:44
	storj.io/storj/uplink/metainfo/kvmetainfo.(*Project).CreateBucket:63
	storj.io/storj/lib/uplink.(*Project).CreateBucket:110
	main.create_bucket:51
	main._cgoexpwrap_47469d2ce0e9_create_bucket:337
	runtime.cgocallbackg1:314
	runtime.cgocallbackg:191
	runtime.cgocallback_gofunc:773
```

Set-up at my end:
- Operating System: Ubuntu 16.04.4 (xenial) LTS
- Compiler: gcc (GCC) 8.3.1 20190809
- Golang version: go1.12.9 linux/amd64

I first created a shared object file, within [lib/uplinkc](https://github.com/storj/storj/tree/master/lib/uplinkc) folder, through following command:
```
go build -o uplink.so -buildmode=c-shared
```

Then, I copied the uplink.h and uplink_definitions.h within the testdata folder

Thereafter, created the executable in testdata folder through:
```
gcc -L/home/hpcs/go/src/storj.io/storj/lib/uplinkc -Wl,-rpath=/home/hpcs/go/src/storj.io/storj/lib/uplinkc -Wall -o test_bucket bucket_test.c -l:uplink.so
```

On executing following command, I got the above error:
```
SATELLITE_0_ADDR=mars.tardigrade.io:7777 GATEWAY_0_API_KEY=1-give-valid-api-key-Y ./test_bucket
```

Details are shared in the following snapshot.
![issue_lib_uplinkc_create_bucket](https://user-images.githubusercontent.com/46558335/65773944-e235e580-e15a-11e9-9008-b3dba009b7ec.png)

May someone help me resolve this issue?

Kind Regards
Vivek

**Comment by engrvivs-neosoft** [comment]
In case, it is relevant, same error comes even with 
SATELLITE_0_ADDR=us-central-1.tardigrade.io:7777

**Comment by engrvivs-neosoft** [comment]
Thanks @mniewrzal for your response!

Let me test the share version and get back.

**Comment by iglesiasbrandon** [comment]
Hey @engrvivs-neosoft did you have a chance to test with an updated version?

**Comment by egonelbre** [comment]
We have significantly updated out uplink-c bindings. The new bindings are inhttps://github.com/storj/uplink-c. It has example code here https://github.com/storj/uplink-c/blob/master/testsuite/testdata/example_test.c.

I'm closing this for now, but when you encounter issues with the new library, you can let us know there.
