### ISSUE TITLE
Getting panic error in download function of storj uplinkc.

### ISSUE THREAD

**Issue by shivam201312** [storj/storj#3144]
The download Method dies with this message when downloadPathStorj does not exist : 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7fbb2f02bbe4]

goroutine 17 [running, locked to thread]:
main.download(0x1c, 0x2a42270, 0x0, 0x7fbb2f328470)
/tmp/storj/lib/uplinkc/object.go:270 +0x1d4
main._cgoexpwrap_47469d2ce0e9_download(0x1c, 0x2a42270, 0x0, 0x0)
_cgo_gotypes.go:650 +0x41

How we can do proper error handling while calling storj uplinkc download function from nodejs ?

**Comment by kaloyan-raev** [comment]
This is the line that panics: https://github.com/storj/storj/blob/master/lib/uplinkc/object.go#L270

The only reason I can see for the panic is that `cErr` is `NULL` and it cannot dereference with `*cErr`.

@kmozurkewich are you sure the node.js bindings pass a valid `cErr` value to the C `download` method?
