### ISSUE TITLE
How do I know the API key of test network?

### ISSUE THREAD

**Issue by satoshi999** [storj/storj#3190]
I want to operate an object using Uplink on a test network.
The test network was built on local followed the following page.
https://github.com/storj/storj/wiki/Test-network
I tried the Uplink as next step.
https://github.com/storj/docs/blob/master/Uplink-CLI.md
Looking at the read me on GitHub, it seems that it need the API key of the test network.
How do I know the API key?
```
API key: The API key that you generate for a project on the Satellite console. If you are using the test network, you can use the API key provided when you run it.
```

**Comment by kaloyan-raev** [comment]
It's true we should make the API Key generated for the test network more accessible.

For now, I can give you a workaround. Setup the Uplink CLI with this command:
```
uplink setup --non-interactive --scope $(storj-sim network env GATEWAY_0_SCOPE)
```
This will setup the Uplink CLI with the scope generated for the S3 Gateway. The "scope" is a serialized tuple of 1) the satellite address (localhost:10000 for test network); 2) the API Key; and 3) the Encryption Key.

**Comment by kaloyan-raev** [comment]
https://github.com/storj/storj/commit/9cbb0c437421879b174fd53bc2629d0f28aca786 now exposes the API Key in the `storj-sim network env` command. This improvement will be available with the next release.
