### ISSUE TITLE
Windows Identity Cmdlet is broken - error in the name 

### ISSUE THREAD

**Issue by no-good-usernames-left** [storj/storj#3278]
The app is broken and is not working on Windows 8.1 Pro with the latest set of updates and also tested on Windows 10 Pro 1903, errors are below. 

Powershell:
identity_windows_amd64.exe : The term 'identity_windows_amd64.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ identity_windows_amd64.exe
\+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (identity_windows_amd64.exe:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException

CMD:
identity_windows_amd64.exe' is not recognized as an internal or external command, or operable program or batch file.

**Comment by ifraixedes** [comment]
Thanks for reporting it.
Note that we only aim to support Windows 10, but as you commented it isn't also working on it.

We'll take a look to figure out what's wrong.

**Comment by stefanbenten** [comment]
I just tested the latest version from release v0.23.4 and it works just fine for me:
![image](https://user-images.githubusercontent.com/17809724/66991886-29aff180-f0c9-11e9-895e-2e7ad5c0adf8.png)

**Comment by bneyjr** [comment]
My only solution was to generate the identity on a linux box and move the files into the windows 10 machine before installing the node.

**Comment by no-good-usernames-left** [comment]
bneyjr,
The identity cmdlet has started working 

But now, the Storj dashboard doesn't work, it says connection refused. 

https://github.com/storj/storj/issues/3664

**Comment by stefanbenten** [comment]
I am closing this issue as the author confirmed, that it is working as expected now.
