### ISSUE TITLE
Windows Identity Binary does not work (linux also not!)

### ISSUE THREAD

**Issue by charlz-crypto** [storj/storj#3323]
Tested the identity process on five different PCs. getting always the same error.

D:\STORJ\tools\identity_windows_amd64.exe>identity_windows_amd64.exe authorize storagenode xxxx@xxxx.de:storj.token

2019-10-20T20:56:49.144+0200    INFO    running on version v0.23.4
2019-10-20T20:56:49.787+0200    FATAL   Unrecoverable error     {"error": "error occurred while signing certificate: rpc error: code = Internal desc = certificates peer error\n(identity files were still generated and saved, if you try again existing files will be loaded)", "errorVerbose": "error occurred while signing certificate: rpc error: code = Internal desc = certificates peer error\n(identity files were still generated and saved, if you try again existing files will be loaded)\n\tmain.cmdAuthorize:212\n\tstorj.io/storj/pkg/process.cleanup.func1.2:275\n\tstorj.io/storj/pkg/process.cleanup.func1:293\n\tgithub.com/spf13/cobra.(*Command).execute:762\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:852\n\tgithub.com/spf13/cobra.(*Command).Execute:800\n\tstorj.io/storj/pkg/process.Exec:74\n\tmain.main:83\n\truntime.main:203"}

D:\STORJ\tools\identity_windows_amd64.exe>pause

**Comment by charlz-crypto** [comment]
![storj_error](https://user-images.githubusercontent.com/56801520/67164621-cea62500-f37c-11e9-941e-89eccd0d2bf9.JPG)

**Comment by charlz-crypto** [comment]
![storj_error_linux](https://user-images.githubusercontent.com/56801520/67165132-a66cf500-f381-11e9-86ac-edf50a50d060.JPG)

Same on Linux

**Comment by ifraixedes** [comment]
@charlz-crypto thanks for reporting it.

We have a few other people with this problem, so far we have identified as a bug and it has been registered in our internal issue tracker for being considered in the next sprint planning.

We'll keep updating this issue.

**Comment by stefanbenten** [comment]
The Error means the auth token has either been claimed already, your clock is out of sync or your identity difficulty is too low.
We are working on passing those errors straight through again.

**Comment by ayaseen** [comment]
I don't think this related to time, I have 5 new nodes facing the same issues while 3 other nodes share the same time with those 5 nodes working fine.

**Comment by stefanbenten** [comment]
@ayaseen As i said above, its one of the three errors. I am 99% sure in your case its the first one.

**Comment by ayaseen** [comment]
So how to solve this issue

**Comment by stefanbenten** [comment]
You cannot use an auth token twice. Please sign up again on the waitlist for a new token (with a different email).

**Comment by ayaseen** [comment]
I already did, but some of my request still waiting for them, I wish if someone releases the tokens soon

**Comment by charlz-crypto** [comment]
> @ayaseen As i said above, its one of the three errors. I am 99% sure in your case its the first one.

Thx for reply.
I can not remember that i claimed the token. 
Can i get a new one?

**Comment by AlexeyALeonov** [comment]
To receive a new authorization token you should subscribe to the waitlist with a different email address

**Comment by ayaseen** [comment]
I submit a list of emails to run my nodes, waiting 10 days to get the tokens is difficult for me, I wish if there away to get the tokens quickly

**Comment by ayaseen** [comment]
The main resone this happens is the difficulty was low, and when you run the sign it will fail, run it again this indicate the token was used.

**Comment by ifraixedes** [comment]
> The main resone this happens is the difficulty was low, and when you run the sign it will fail, run it again this indicate the token was used.

Thanks for letting about this problem.
We'll look for how we can avoid or at least warn the user about it if she/he tries to sign the identity with low difficulty.

**Comment by stefanbenten** [comment]
This issue should be resolved with the release of v0.26.0. I am going to close this, please reopen if the issue still exists.
