### ISSUE TITLE
Improve connectivity and stability for Satellites

### ISSUE THREAD

**Issue by D4rk4** [storj/storj#3411]
Fact:
Owners of Storj nodes must be aware about nodes reputation. As result (I'm guess) most operators of storage nodes get some headache with network reservation and configuration.

Solution:
Satellites can use Multipath TCP extension, for communicates with Storage nodes. Like it's already implemented in Apple services, Aliexpress/Alibaba cloud and selected Android devices. 

Ref:
http://multipath-tcp.org/data/MultipathTCP-netsys.pdf

**Comment by iglesiasbrandon** [comment]
Hey, @D4rk4, thank you for the suggestion, this issue has become stale, but we do not believe we need Multipath TCP at this time. We are going to close this issue until it becomes relevant.
