### ISSUE TITLE
API: upToDate always true

### ISSUE THREAD

**Issue by Krey81** [storj/storj#3627]
Now available 26.2 version. But API returns true for 25.1 version node
```
PS C:\Projects\Repos\Storj> ((Invoke-WebRequest -Uri http://192.168.156.204:4404/api/dashboard).content | ConvertFrom-Json).data

nodeID              : 12ZuJYWz9iah8T21UTVvGNckADkooRuNwFqKgYRGV5kZEWSCTPx
wallet              : x
satellites          : {@{id=121RTSDpyNZVcEU84Ticf2L1ntiuUimbWgfATz21tuvgk3vzoA6; disqualified=}, @{id=12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs; disqualified=}, @{id=12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZ    
                      HeLUtdps3S; disqualified=}, @{id=118UWpMCHzs6CvSgWd9BfFVjw5K9pZbJjkfZJexMtSkmKxvvAW; disqualified=}}
diskSpace           : @{used=3098583534080; available=11000000000000}
bandwidth           : @{used=809723524096; available=200000000000000}
lastPinged          : 2019-11-21T15:39:12.650124266+03:00
lastPingFromID      : 1111111111111111111111111111111112m1s9K
lastPingFromAddress :
version             : 0.25.1
upToDate            : True
startedAt           : 2019-11-08T17:01:00.73496755+03:00
```

**Comment by kaloyan-raev** [comment]
@Krey81 It seems your node hasn't updated yet.

Which OS are your running on your node? Windows or Linux?

If it is Linux, can we have the logs from watchtower?
```
docker logs watchtower
```

If it is Windows (without Docker) can we have the `C:\Program Files\Storj\Storage Node\storagenode-updater.log` file?

**Comment by Krey81** [comment]
> @Krey81 It seems your node hasn't updated yet.

Exactly. But in this case it dashboard api should return false in upToDate field. But value is true. This is error.

**Comment by kaloyan-raev** [comment]
I've just checked the code and it looks like `upToDate` reflects if the storage node is running a supported version, i.e. above the minimum required, not the latest released.

https://github.com/storj/storj/blob/61c8bcc9a6a6bcf456b94e805135bbd5491069e0/storagenode/console/service.go#L137

However, even if it shows if the storage node runs the latest versions, this information will always be delayed as the storage node does not query the version server every second.

If you want a real-time check about the latest version, I recommend you to query the version server directly:

https://version.storj.io/

**Comment by Krey81** [comment]
> https://version.storj.io/
Yes, thanks. I change my script https://github.com/Krey81/Storj/tree/master/Storj3Monitor
this way.
I don't know how many SNO's used my script in monitoring mode or other script like my but potentially it can create an undesirable load on your service. I think that an additional field "isLatest" in dashboard json will simplify everything
