### ISSUE TITLE
Availability to check node is accessible from internet

### ISSUE THREAD

**Issue by wivern-co-uk** [storj/storj#3643]
```INFO    version running on version v0.26.2```

So node is up and running, but in dashboard it remains offline for hours. How it's possible to check storagenode availability without waiting and guessing? Is there any request I can send to publicly available port 28967 in order to check node is ready for connections; using telnet, postman or whatsoever? 

Just a regular `GET /` gives `104: Connection reset by peer`.

**Comment by kaloyan-raev** [comment]
Yes, you can try `telnet your-public-ip-address 28967` or a web tool like https://portchecker.co/check to check if the port of your storage node is visible from the Internet.

If it is not then you should check the port forwarding configuration on your router.

**Comment by wivern-co-uk** [comment]
@kaloyan-raev that's the first thing I did, but how to simulate request? Having a port open is not guarantee storagenode is healthy and works as expected.

```
root@448067f:~# telnet 127.0.0.1 28967
GET / HTTP/1.1
Connection closed by foreign host
```

**Comment by wivern-co-uk** [comment]
Found a way connecting and checking whether certificate on responding side is self-signed by Storj
`openssl s_client -connect 127.0.0.1 28967`
In this case I know it's storagenode response. Pretty enough for the healthcheck I've been looking for.

**Comment by stefanbenten** [comment]
@wivern-co-uk I am going to close this issue, as you found a way to check the node yourself.
Feel free to reopen if there are any other issues with this request.
