### ISSUE TITLE
Storage Manager Dashboard Connection refused on :14002

### ISSUE THREAD

**Issue by no-good-usernames-left** [storj/storj#3664]
I got Storj setup and installed on Windows 10 using the GUI method. 

The SMD is not working as :14002 is not opened according to NetStat. 

What is needed to fix this?

**Comment by bneyjr** [comment]
Check the logs. It gives pretty good info on that. I had the same issue and it was because the storage manager had not completely started. It was blocked because it could not open my storage location. I had tried to use a NAS and Storj apparently doesnt like SMB type NAS systems.

**Comment by no-good-usernames-left** [comment]
Where are the logs located for the non-docker installation?

I guess Storj needs a round of robust programming because it should error out when attempting to map network drives and/or be able handle SMB connections. 

Plus, the manager should at least be able to start regardless of a valid storage path.

**Comment by bneyjr** [comment]
The log is in the same directory as the executables

**Comment by ifraixedes** [comment]
Closed because of a lack of response.
If the issue persists please, comment.
