### ISSUE TITLE
storjshared is runing and 137 peers 

### ISSUE THREAD

**Issue by drkamine** [storj/storj#3727]
hello it's my first time here and i just start with storjshare . i install it in my serevr  and i runit without any issue 
 but i see
 status = runing 
uptime =23h30m
peers=137
Allocs =0 
port =4000(tcp)
shared = ...
...(%)
bridgeds = connected 
it is normal to don't have any Allows ???

**Comment by stefanbenten** [comment]
@drkamine Storjshare is the deprecated V2 Network Software. We are currently in Beta with our V3 Network which you can sign up for here: https://storj.io/sign-up-node-operator/
The V2 Network is going to be sunset very soon, thus no new data will be uploaded to it.
