### ISSUE TITLE
2 week ans storage used is 6.3 

### ISSUE THREAD

**Issue by drkamine** [storj/storj#3738]
Hello it's been a week since my status is connected but the use of space and the same 6.3 it does not increase. I'm on docker beta.
ff118c031c8a storjlabs / storagenode: beta "/ entrypoint" 2 weeks ago Up 13 days 127.0.0.1:14002->14002/tcp, 0.0.0.0:28967->28967/tcp

**Comment by keleffew** [comment]
Hi @drkamine.  Please repost in [forum.storj.io](forum.storj.io) for support issues like these.

The community there should be able to help you quickly.

Let's be the cloud!

Kevin

**Comment by drkamine** [comment]
Hello @keleffew  thank for you answer can you please check the link isn't work

**Comment by ifraixedes** [comment]
@drkamine the URL to our community forum is https://forum.storj.io
