### ISSUE TITLE
Docker: Invalid Reference format

### ISSUE THREAD

**Issue by Fellane** [storj/storj#3741]
I did all steps in the instruction and the last command doesn't work. I got Docker: Invalid Reference format. But all destinations are correct.

docker run -d --restart always -p 28967:28967 \
-e WALLET="my address" \
-e EMAIL="email" \
-e ADDRESS="ip:28967" \
-e BANDWIDTH="100TB" \
-e STORAGE="850GB" \
--memory=800m \
--log-opt max-size=50m \ 
--log-opt max-file=10 \--mount type=bind,source=/home/pi/.local/share/storj/identity/storagenode,destination=/app/identity \
--mount type=bind,source=/mnt/storagenode,destination=/app/config \
--name storagenode storjlabs/storagenode:beta

**Comment by Fellane** [comment]
Solved. But now I got another problem. Container is restarting for almost 30 minutes.
Container bc4ba677433428e1e2c1185380d5ed0a427ee784e55d073108fd4c8 is restarting, wait until the container is running. I got this message for almost 30 minute? I am running the node on RBPI 3B+.

**Comment by Fellane** [comment]
it was up for a few seconds but then it started to restarting again.
Ports looked liked this > 0.0.0.0:14002->14002/tcp, 0.0.0.0:28967->28967/tcp it's ok?

**Comment by Fellane** [comment]
This is my ned docker settings I used last time.

docker run -d --restart unless-stopped -p 28967:28967 \
-p 14002:14002 \
-e WALLET="0xa9c2445400C10CC56a42a1acA8D5C6c6151bdc7C" \
-e EMAIL="myemail \
-e ADDRESS="184.13.38.72:28967" \
-e BANDWIDTH="100TB" \
-e STORAGE="850GB” \
--mount type=bind,source="/home/pi/.local/share/storj/Identity/storagenode",destination=/app/identity \
--mount type=bind,source="/mnt/storagenode",destination=/app/config \
--name storagenode storjlabs/storagenode:beta

**Comment by ifraixedes** [comment]
Hi @Fellane
Please, post the logs of the docker container so we can try to understand what is going on.

To get the logs, do `docker logs storagenode`

**Comment by Fellane** [comment]
Solved. It was wrong e storage value. I change it to 800 GB and it worked out pretty well. My nose is up and running.
