### ISSUE TITLE
uplinkc: DownloadRange not buffering?

### ISSUE THREAD

**Issue by TopperDEL** [storj/storj#3743]
I'm using the DownloadRange-function via uplinkc (from my .NET-wrapper). I try to use it to stream the data for a 29MB-video. The stream gets used by the MediaPlayer and that one loads data in chunks. During Playback I see that my Connection is used by around 20MBit/s, but it takes seconds to retrieve those chunks (of around 260kB).

For me it seems the DownloadRange-function starts downloading pieces all over again to reconstruct the requested part of the whole file. 

I need to get the requested Bytes as fast as possible to make videostreaming possible. Do I do something wrong calling DownloadRange or is this function not intended to be used for "loading chunks one after another" from an object?

**Comment by egonelbre** [comment]
Yes, DownloadRange is intended to download a subrange from an object. There's no caching from any previous call.

Maybe calling `Download` and disallow seeking (if possible) and then just wait until need to read more. To make it more efficient you could also implement a cache for the downloaded segments.

I have some ideas how to make seeking work, however these are not in the near term plans.

**Comment by TopperDEL** [comment]
That was my first Approach - downloading from the beginning and prevent seeking. But that does not work with Universal Windows Platform (UWP) as I Need a RandomAccessStream there that supports seeking. 

How do other implementations implement seeking?

This is not top priority - but otherwise my DownloadStream-implementation is currently useless.

**Comment by TopperDEL** [comment]
I just talked to Egon (Thank Egon!) and he clarified what's Happening here. My expectation for the DownloadRange-function was wrong. It loads the requested chunk but does not Buffer anything so it cannot be used that way for a completely seekable-stream.

I'm therefore Closing this issue. I would love to see Seeking included in the full stack, but there are other topics of much more importance that Need to be done before this. So - whenever it's Ready it's good and otherwise I'm happy with what we have. :)
