### ISSUE TITLE
uplinkc: RestrictScope-issue with uplink.Net

### ISSUE THREAD

**Issue by TopperDEL** [storj/storj#3747]
I need help with the restrict_scope-implementation of the Uplink.Net-wrapper. It generates a correct scope (as far as I can see) but when trying to us it to download an object, I get an "Unauthorized API credentials" on open_bucket.

I think that the restrictions do not get transferred correctly but I do now know how to check this further.
This is my testcode:
https://github.com/TopperDEL/uplink.net/blob/5d02eb1f2b7fc5f497d2caebb80d3d1071f629a0/uplink.NET/uplink.NET.Test/ScopeTest.cs#L57

Due to the SWIG-wrapping issues of EncryptionRestrictions, I've created some helper-functions in C to supply an EncryptionRestrictions-Array:
https://github.com/TopperDEL/uplink.net/blob/5d02eb1f2b7fc5f497d2caebb80d3d1071f629a0/SWIG/storj_uplink_second.i#L116

**Comment by mniewrzal** [comment]
I wrote an example test case for different problem with `restrict_scope` but it might be helpful also here. Can you take a look and tell me if this is way how you are using `restrict_scope` function?

https://review.dev.storj.io/c/storj/storj/+/460

**Comment by TopperDEL** [comment]
Yes, I've seen that and checked my test against it. I think I'm doing exactly the same. But my error message is different. I have no Access - so I think that something with providing the EncryptionRestrictions does not work. Maybe they get supplied, but something with string-conversion is wrong to that the bucketname and prefix is simply a different string.

I'll try to Output what C gets froms C# later and see if this is the error. Maybe I'll Need to adjust my helper function to not receive a complete EncryptionRestriction but the fields separately. Then the in other functions working string-supplying should work.

**Comment by mniewrzal** [comment]
If you have `"Unauthorized API credentials"` it means that the problem is with our api key, not encryption restriction.

**Comment by TopperDEL** [comment]
Ok. But I get that API-Key from the deserialized Scope. And it Returns me at least a correct satellite address, so it cannot be completely wrong.
How could I investigate this, then? Shall I provide you with my restricted and serialized scope, would that help?

**Comment by mniewrzal** [comment]
I noticed that in your C# code you are not checking errors, maybe there is an error during restricting and you are missing it?

**Comment by TopperDEL** [comment]
It would throw an exception with the error message supplied from uplinkc. And I get a scope back and can retrieve satellite, apikey and encryptionaccess from it. So restriction itself seems to work.

**Comment by TopperDEL** [comment]
See here: https://github.com/TopperDEL/uplink.net/blob/5d02eb1f2b7fc5f497d2caebb80d3d1071f629a0/uplink.NET/uplink.NET.Shared/Models/Scope.cs#L122

**Comment by TopperDEL** [comment]
Ok, it seems by passing the border from C# to C to Go, my strings get not handled correctly when nested within a struct. Go then has some weird string for "Bucket" and "PathPrefix" within an EncryptionRestriction. I assume These are the pointer-adresses or so.

So I tried moving my Workaround ("prepare_restrictions", "add_restrictions") to go. Basically I want to create a temporary Array of EncryptionRestrictions and add every EncryptionRestriction on it's own by providing the strings itself. But I'm now struggling calling the restrict_scope-function with my EncryptionRestricions-array.

I tried:
- copy&paste the restrict_scope-function and Change it so that it uses my prepared Array. Here I get go-compile-errors regarding the caveat. Seems it collides with the macaroon-package when I "sideload" my function. Don't understand this. But copying the function is not the best idea either (as I would have to adjust it whenever the original changed). So I tried:
- calling the original restrict_scope with my prepared array. But therefore I would Need to convert it back to a c-array again. But I don't know how to do this, too.

So it all breaks down to this question: does someone see a way to provide an EncryptionRestrictions-array to restrict_scope by having plain strings for Bucket and PathPrefix? I also tried supplying a JSON-string and to Marshal it into a Go-Array - but was not successfull either.
This is frustating for me but should be an easy one for Go/c-pro's like @mniewrzal or @bryanchriswhite .

Thank you!

**Comment by TopperDEL** [comment]
My latest attemp. It compiles but crashes silently at runtime:

```
package main

// #include "uplink_definitions.h"
import "C"

import  (
	libuplink "storj.io/storj/lib/uplink"
)

var restrictions []libuplink.EncryptionRestriction;

//export prepare_restrictions
// prepare_restrictions lala
func prepare_restrictions(restrictionsLen C.size_t) {
	irestrictionsLen := int(restrictionsLen)
	
	restrictions = make([]libuplink.EncryptionRestriction, 0, irestrictionsLen)
}

//export append_restriction
// append_restriction lala
func append_restriction(bucket *C.char, path_prefix *C.char){
	restriction := libuplink.EncryptionRestriction{
				Bucket:     C.GoString(bucket),
				PathPrefix: C.GoString(path_prefix),
			}
	
	restrictions = append(restrictions, restriction)
}

//export restrict_scope2
// restrict_scope2 restricts a given scope with the provided caveat and encryption restrictions
func restrict_scope2(scopeRef C.ScopeRef, caveat C.Caveat, restrictionsLen C.size_t, cerr **C.char) C.ScopeRef {
	irestrictionsLen := int(restrictionsLen)
	
	var restrictionsC **C.EncryptionRestriction
 
	restrictionsCArray := make([]C.EncryptionRestriction, 0, irestrictionsLen)
	for _, restriction := range restrictions {
        restrictionsCArray = append(restrictionsCArray, C.EncryptionRestriction{
			bucket: C.CString(restriction.Bucket),
			path_prefix: C.CString(restriction.PathPrefix),
		})
    }
	*restrictionsC = &restrictionsCArray[0]
	
	return restrict_scope(scopeRef, caveat, restrictionsC, restrictionsLen, cerr)
}
```

**Comment by TopperDEL** [comment]
The main Thing seems to be the next-to-the-latest line:

`*restrictionsC = &restrictionsCArray[0]`

If someone could help me bring "restrictionsCArray" to a variable that restrict_scope accept and can use should last, I guess. @mniewrzal 

Sorry to bother you again...

**Comment by mniewrzal** [comment]
@TopperDEL sorry I was busy last days. I will try to take a look at this today.

**Comment by TopperDEL** [comment]
Thank you @mniewrzal ! I tried something like this before, but it doesn't compile:

`# storj.io/storj/lib/uplinkc
.\restrict_scope_helper.go:50:48: cannot use caveatGo (type "storj.io/common/macaroon".Caveat) as type "storj.io/storj/pkg/macaroon".Caveat in argument to scope.APIKey.Restrict`

I've placed it in the file "restrict_scope_helper.go" and copy it to the uplinkc folder before running the Go-compiler. For any reason it does not treat that file like all other go-files from the storj-repo.

I'll investigate this one again, though. Thanks for your help!

**Comment by TopperDEL** [comment]
Sorry for the confusion.

I add that Code (my one or your one) during build of my wrapper. I just copy an extra go-file to uplinkc to include it with my wrapper. This does not work (either with your one or with my one).
I just tried pulling your fork from GitHub directly and that works. So there seems to be some difference between "adding a file by XCOPY" and "adding it to the storj-uplinkc-repo". I do not understand it, but your solution at least compiles!

Testing my wrapper now.

Is this something you would include with uplinkc for all? As my XCOPY does not work for whatever reason I currently do not know how I could add this Code to my wrapper otherwise.

**Comment by TopperDEL** [comment]
Your Code works with my wrapper! Great, Thank you!

**Comment by mniewrzal** [comment]
> Is this something you would include with uplinkc for all? As my XCOPY does not work for whatever reason I currently do not know how I could add this Code to my wrapper otherwise.

No, this code won't be part of `uplinkc`. It's just hack :)

**Comment by TopperDEL** [comment]
It's working now! I've added your file to my XCOPY-root and it worked. I'm not sure, if the problem came from a different file format (the content should have been the same) or because I moved on from storj-tag v0.28.4 to v0.30.2.

**TL/DR:** It works and I can now finally create restricted scopes within uplink.NET. Thank you - once again - @mniewrzal !

Closing this issue, it is resolved.
