### ISSUE TITLE
Node full but still gets new data

### ISSUE THREAD

**Issue by kevinkk525** [storj/storj#3751]
My node got full and correctly stopped receiving data. Then some data got deletedand not even 1GB was free and it started to get data again. 
However, it has been full since more than 36 hours now, with the dashboard showing -10GB and it is still receiving new data.
The trash directory was 3GB most of the time and is 750M at the moment.
There are no errors in the logs and it gets uploads from all active satellites.

I didn't restart it yet (which would probably "solve" the issue), just in case there's something you'd like me to try while the bug is active.

Maybe I should also add that I allocated 900GB to the node, both dashboards show -10GB available. The disk however has only 850GB used from a total of 910GB.
Version is 0.29.3 running on docker 19.03.04-rc1 on ubuntu.

**Comment by ifraixedes** [comment]
@kevinkk525 thanks for reporting the bug very descriptively.

Do you know if that the data was deleted was of normal delete requests or from the garbage collector?

**Comment by kevinkk525** [comment]
I checked the logs and new data started to come in when delete operations started, so I assume it is because of those.
But which one ultimately freed enough space to start accepting new data is probably hard to tell since garbage collection isn't logged. But since new data and delete operations started at the same time without a bigger drop in used space it is probably very likely to be due to delete operations.

**Comment by kevinkk525** [comment]
After the upgrade to 0.31.9 both my full nodes started to receive data again!
Please fix this soon! 

Even after a restart of those node they receive upload requests, however currently all uploads fail with "context canceled" error, even on my not full node. But the full nodes should throw a few "node full" errors and not receive those requests at all.
Therefore I have to stop my 2 full nodes so they don't get data while I'm not watching and run out of harddrive space..

**Comment by ifraixedes** [comment]
We are on it, there are some teammates working in trying to identify the problem and fix it.

Thanks for your patience.

**Comment by ifraixedes** [comment]
@kevinkk525 it's fixed.
There is a new version, see https://forum.storj.io/t/changelog-v0-31-10/4235

Please update and observe and if it works fine for you, close the issue, otherwise report it.
Currently, a few SNOs have observed that it's working.

**Comment by kevinkk525** [comment]
There's currently not much upload traffic so I had to watch a while to be sure but it looks to me like it is resolved. 
The not-full node gets the occasional upload from PUT and mainly PUT_REPAIR while the 2 full nodes don't get any upload messages.
Thanks for the fast bugfix!
