### ISSUE TITLE
AWS Gateway: enable ETag

### ISSUE THREAD

**Issue by arno01** [storj/storj#3761]
It appears that the gateway does not send the ETag.
This causes ``S3DataError: BotoClientError: ETag from S3 did not match computed MD5`` messages on file upload by the python-boto clients such as duplicity.

https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html

> Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.

### Test

```
aws s3 cp --debug --endpoint http://127.0.0.1:7777 gateway_linux_amd64.zip s3://backups/
```

Etag is empty as you can see:

```
2020-01-26 20:27:06,864 - ThreadPoolExecutor-0_3 - botocore.parsers - DEBUG - Response headers: {'Accept-Ranges': 'bytes', 'Content-Security-Policy': 'block-all-mixed-content', 'Content-Type': 'application/xml', 'Etag': '""', 'Server': 'Minio/DEVELOPMENT.GOGET (linux; amd64)', 'Vary': 'Origin', 'X-Amz-Request-Id': '15ED89AE81413711', 'X-Xss-Protection': '"1; mode=block"', 'Date': 'Sun, 26 Jan 2020 20:27:06 GMT', 'Transfer-Encoding': 'chunked'}
```

- gateway version: ``v0.30.5`` 72805d55ca6dcbc5dd32883e64538d77fcb35b8a
- aws-cli/1.14.44 Python/3.6.9 Linux/4.15.0-74-generic botocore/1.8.48

**Comment by mniewrzal** [comment]
@arno01 
Sorry for not responding earlier. Currently, we are working to improve `gateway`. Can you say which tool is returning error (`S3DataError: BotoClientError: ETag from S3 did not match computed MD5`)? Is it `aws cli` or something else?

**Comment by arno01** [comment]
> @arno01
> Sorry for not responding earlier. Currently, we are working to improve `gateway`. Can you say which tool is returning error (`S3DataError: BotoClientError: ETag from S3 did not match computed MD5`)? Is it `aws cli` or something else?

anything that is using `python-boto`, e.g. clients such as `duplicity`.
I've described a workaround that I am using here https://github.com/storj/storj/issues/620#issuecomment-578499674
basically I'm making sure the ETag isn't getting checked there, when it sees `Minio/DEVELOPMENT.GOGET (linux; amd64)` server name (which is the Storj `gateway`).

**Comment by mniewrzal** [comment]
Thanks for the fast answer. Yesterday I tried new gateway version which is under development and basic backup with `duplicity` looks to be working. I will let you know when new version will be available.

**Comment by stefanbenten** [comment]
Hello @arno01 !
As @mniewrzal pointed out before, we should now have a gateway that handles the ETag properly.
You can find the source code and its release here: https://github.com/storj/gateway.
If you still encounter issues, please open a new issue in that repo!

Thank you!
