### ISSUE TITLE
uplinkc: Problems with RestrictScope and Caveats

### ISSUE THREAD

**Issue by TopperDEL** [storj/storj#3762]
I'm using uplinkc through my uplink.Net-Wrapper. RestrictScope is working until I have a Caveat with any of the fields DisallowReads/Writes/Lists/Deletes being "true".

I've checked "the border" between C# and Go and it seems the info is transferred correctly. If I return the Caveat via a ToString after creating it, I get the following Caveat-Objects:

`{DisallowReads:true DisallowWrites:false DisallowLists:false DisallowDeletes:false AllowedPaths:[] NotAfter:<nil> NotBefore:<nil> Nonce:[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}`

`{DisallowReads:false DisallowWrites:false DisallowLists:false DisallowDeletes:false AllowedPaths:[] NotAfter:<nil> NotBefore:<nil> Nonce:[] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}`

The first one has "DisallowRead" set to "true". The last one has it set to "false". If I create a restricted scope with the DisallowRead=true, I get an "unauthorized API credentials"-error while trying to upload an object to a valid path.

And I don not know why. The test-code [here](https://github.com/storj/storj/blob/9bcb81108f3f28d5bd9330158ee6bd6d1f667a4f/lib/uplinkc/testdata/access_scope_test.c#L62) only checks if a restricted scope got created but makes no upload-tests. Maybe the error is reproducable there?

**Comment by TopperDEL** [comment]
I tried to add test-code for this scenario, but I'm again failing with C-code. @mniewrzal Sorry to bother you again - but adding a test for this (uploading an object to a restriced-scope-bucket) should be easy for you. :)

**Comment by mniewrzal** [comment]
@TopperDEL I think the issue is on our side, not an issue with shared library. Give me some time and I will try to confirm that.

**Comment by TopperDEL** [comment]
Thank you @mniewrzal!

**Comment by mniewrzal** [comment]
Can you summary what exactly you want to do? My understanding is:
* restrict scope with `DisallowRead=true`
* upload file with this restricted scope
am I right?

**Comment by TopperDEL** [comment]
> Can you summary what exactly you want to do? My understanding is:
> 
> * restrict scope with `DisallowRead=true`
> * upload file with this restricted scope
> 
> am I right?

Yes, thats right. Download works, the restricted scope is valid but cannot be used to upload something. The exact same code works if I Set that Disallow to false and change nothing Else. @mniewrzal

**Comment by TopperDEL** [comment]
It does not matter which Disallow is true (though DisallowWrite should fail obviously).

**Comment by TopperDEL** [comment]
Any news on this one? @mniewrzal

**Comment by ifraixedes** [comment]
@TopperDEL it's a complicated week for @mniewrzal 
we are having the all-hands week and almost everybody is in the Atlanta office having company, teams, guilds meetings, and events and at the same time working in very important niche things.

Not saying that this problem isn't important, but be patient with @mniewrzal he may get the time during the next week to come back to this.

Our apologies for the delay!

**Comment by TopperDEL** [comment]
Ah, nevermind! I was just curious what the reason was and how it is going. This is not urgend, sorry for stressing!

**Comment by ifraixedes** [comment]
@TopperDEL no problem, I wanted to let you know that we haven't forgotten about this.

**Comment by mniewrzal** [comment]
@TopperDEL sorry for no info for so long, I remeber about your problem but it was hard for me to help this week.

I updated my PR about `restrict_scope` to add a case you have. Please take a look if its something that will help you https://review.dev.storj.io/c/storj/storj/+/460/5/lib/uplinkc/testdata/download_restricted_test.c#220
Test are passing (other erros from pipline). 
https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/2833/pipeline
Next week I'm not available but ping this thread in case of issues. I will try to help when back or someone else will jump to help.

**Comment by TopperDEL** [comment]
@mniewrzal Thank you for coming back to this topic! Now I have been knocked out for some day. But I finally came back to it today and found it working out of the box with the latest storj-repo. It seems something changed in between - now my uplink.Net-Tests pass and my real-world-app (where I originally found the issue) is working, too. Even old Scopes do now work with the new uplinkc under the hood.

So, this issue is resolved now. Thanks for the heads-up!
