### ISSUE TITLE
storage size configuration rounding inconsistency

### ISSUE THREAD

**Issue by kevinkk525** [storj/storj#3764]
When configuring the storage size for storj in the docker run command the value gets rounded.
I put it to 2.65TB and had at some point only 25GB available so I wanted to change that. I wanted to give my storagenode 100GB more space, so I changed it to 2.75GB. However suddenly I had 225GB of space available according to the dashboard. 
So I changed it to 2.7TB, then I had 125GB available. 

So it seems that there's some rounding of these values going on but it seems to be inconsistent.
2.65TB -> +0GB
2.7TB -> +100GB
2.75TB -> +200GB
That would mean that 2.65TB got rounded down to 2.6TB while 2.75 got rounded up to 2.8TB?

Also why isn't the given value used? Why is that value rounded?

**Comment by AlexeyALeonov** [comment]
I cannot reproduce.
```
                   Available         Used       Egress     Ingress
     Bandwidth           N/A     379.6 GB     377.3 GB      2.3 GB (since Apr 1)
          Disk        9.7 GB       1.0 TB
```
Stopped and removed the container. Run a new one with a changed the `STORAGE="1TB"` to `STORAGE="1.1TB"` parameter:
```
                   Available         Used       Egress     Ingress
     Bandwidth           N/A     379.6 GB     377.3 GB      2.3 GB (since Apr 1)
          Disk      109.7 GB       1.0 TB
```

Please, try to restart the container before the change. Sometimes it can't calculate a free space accurately because of `database is locked` issue.

**Comment by AlexeyALeonov** [comment]
I reproduced it. I should change to `1.16TB`, then it will display the `209.7 GB` instead of `169.7 GB`

**Comment by pacproduct** [comment]
I noticed the same behavior. I don't get why this would be a necessary limitation?

If I own a 600GB disk, I should give 600/1.1 to my Node to allow for a 10% overhead, that is 545GB.
Setting the allocated space to 545GB ends up being rounded down to 500GB: 45GB are "lost" in the process. I don't see this as a serious issue as 45GB won't really change the world... even though on such a small node it's still 8% of capacity lost.

(related to https://forum.storj.io/t/storage-size-rounding/6266)

**Comment by ifraixedes** [comment]
@pacproduct thanks for reporting it.
We have a ticket on our issue tracked to work on this bug, but so far hasn't been scheduled in a sprint due to the team capacity.

Thank you for your patience.

**Comment by pacproduct** [comment]
@ifraixedes No problem! It's a minor bug anyway :)
Thx for your feedback.
