### ISSUE TITLE
Nextcloud: Uploading bytes to Storj in a already exiting object

### ISSUE THREAD

**Issue by TRIPTI2110** [storj/storj#3767]
I was getting segment error while uploading a large file.

I have read the file data in chunks of bytes using the Read method through io.Reader. Now, I need to upload the bytes of data continuously into the StorJ.

**Comment by ifraixedes** [comment]
@TRIPTI2110 please be more descriptive about how you were doing so and which version of whatever you used have used.

Thanks!

**Comment by TRIPTI2110** [comment]
// Create a list of all files with their respective paths for transfer to storj
				err = nextcloud.GetFilesWithPaths(nextCloudClient, filePath)
				if err != nil {
					log.Fatal("Path/directory not found. Terminating...")
				}
				fmt.Println(nextcloud.AllFilesWithPaths)

				// Create connection with the required storj nextwork
				ctx, uplinkStorj, project, bucket, storjConfig, scope, err := storj.ConnectStorjReadUploadData(fullFileNameStorj, keyValue, restrict)
// // Transfer required data from nextcloud to storj
				// for i := 0; i < len(nextcloud.AllFilesWithPaths); i++ {
				// 	var fileData [][]byte
				// 	file := nextcloud.AllFilesWithPaths[i]
				// 	nextCloudReader := nextcloud.DownloadSingleFile(nextCloudClient, file)
				// 	buffer := make([]byte, 200)
				// 	for {
				// 		numofBytes, err := nextCloudReader.Read(buffer)
				// 		 	storj.ConnectUpload(ctx, bucket, fileData, file, fileNamesDEBUG, storjConfig, err)
				// 		fmt.Print(fileData)

				// 		if err == io.EOF {
				// 			break
				// 		}
				// 	}

**Comment by TRIPTI2110** [comment]
I am trying to upload the bytes of Data into StorJ. I need to append the bytes of data into already uploaded file in StorJ. How will I be able to do so?

**Comment by kevinkk525** [comment]
I read this issue to find out what it was about and seeing "nextcloud" I am wondering even more!
But you are not providing nearly enough information to understand what you are trying to do!

Please share more information:
- what's this about "nextcloud"
- what libraries are you using?
- what version of libraries are you using?
- ...

**Comment by ifraixedes** [comment]
@TRIPTI2110 @kevinkk525 is right.

Now we know that you're trying to upload bytes of data to Storj in an already existing object, but how are you doing so?

__NOTE__ that we haven't started to work in these integrations, Nexcloud is one that we'd like to support, but we haven't started the planning of the new teams.

Anyway, if you post detailed information we'll have the chance to help you through.

**Comment by TRIPTI2110** [comment]
I have made a client of NextCloud Using https://github.com/partitio/gonextcloud/ repositry and trying to upload the data to StorJ. Anything more you would like to know?

**Comment by kevinkk525** [comment]
Well you provided some lines of code and we might understand what you are trying to do but you didn't say in which line an error is thrown and you did not provide the error message/trace.

**Comment by TRIPTI2110** [comment]
I am getting segment error while uploading large file in StorJ. How should I upload chunks of byte array of data then to resolve the error?

**Comment by ifraixedes** [comment]
@TRIPTI2110 great to know that you are using https://github.com/partitio/gonextcloud/ that's something that we couldn't find out without saying it.

Are you using the last [lib uplink](https://godoc.org/storj.io/uplink)?
Could you share the code or a snippet of the code where you're doing the upload, please?

**Comment by TRIPTI2110** [comment]
![image](https://user-images.githubusercontent.com/52169869/73624509-11a7b200-4667-11ea-8ac8-895ac3e8674d.png)
![image](https://user-images.githubusercontent.com/52169869/73624547-4582d780-4667-11ea-9caf-27f2a1c9ec0a.png)
![image](https://user-images.githubusercontent.com/52169869/73624616-91ce1780-4667-11ea-9c86-cc73febaf6b7.png)

I am uploading a single object to the bucket, I need to append bytes of data into that object.

**Comment by kaloyan-raev** [comment]
It is not possible to append additional data to an existing object. All the object data must be provided by the `io.Reader` passed to the `bucket.UploadObject` bucket. Subsequent calls to `bucketUploadObject` for the same object will overwrite it.

**Comment by TRIPTI2110** [comment]
How should I append the data to object, then?
