### ISSUE TITLE
storj won't stay running, updates aren't happening

### ISSUE THREAD

**Issue by sixcorners** [storj/storj#3768]
![image](https://user-images.githubusercontent.com/585501/73504898-8395a800-4396-11ea-961e-8f4210968bcf.png)
I installed storj on windows. Every time I check it the service isn't running. I got an email saying the software is out of date. The only part of it that does stay running is the auto update service. Is there something that can be done to make this thing stay running? Is there something that can make it easy to monitor this thing?

**Comment by sixcorners** [comment]
It says error 1067 The process terminated unexpectedly when I try to start it...

**Comment by kevinkk525** [comment]
What does the log say?

**Comment by sixcorners** [comment]
ERROR	Invalid configuration: invalid contact.external-address: split host-port "zzz" failed: address zzz: missing port in address

I'm pretty sure this was running before. I guess it has been updating versions. I don't know.
How do you all keep this stuff monitored?

**Comment by kevinkk525** [comment]
We check the logs when our node doesn't start and fix the problem or report the bug..

So were you able to correct the missing port problem in your configuration or by installing the node again?

**Comment by sixcorners** [comment]
I changed the yaml file.
I guess what was happening before was that the program would start but then run with errors.
I was kind of under the assumption that it would assume the port because the installer didn't fail without the port information.

**Comment by kevinkk525** [comment]
That might be an oversight in the installer, we'll see when the next STORJling reads the messages.
Good that you got it running again.

**Comment by sixcorners** [comment]
What is a STORJling?
Are emails sent out when the node goes offline or isn't working properly? What is that thing that sends emails from hello@storj.io?

**Comment by kevinkk525** [comment]
Do you know the forum? https://forum.storj.io

I meant the employees of STORJ.
No your node does not send emails when it is offline.

**Comment by sixcorners** [comment]
I don't mean any emails from my node. It looks like the email I got came from customer.io.
Hmm.. I guess I wasn't looking for a forum. I kind of just think that running these things should be less prickly. That these errors should surface themselves easier.
I guess I'll use that forum if it's more of a kind of issue that warrants discussion.

**Comment by kevinkk525** [comment]
The email was an announcement from Storj.
This software is still beta and the forum is the best place to get information and troubleshooting help.
You probably don't need the forum for discussing this specific issue but to generally get information.

**Comment by sixcorners** [comment]
Ok I'll try to read stuff there.
Right now it seems kind of easy to install this thing, lose track of it, and get a horrible reputation.

**Comment by ifraixedes** [comment]
The splitting address was a bug and it has been fixed.

**Comment by sixcorners** [comment]
How was it fixed?
Could the installer be changed to check for a port if it is required?
Could the program check for and use a default port if it isn't there?

**Comment by stefanbenten** [comment]
@sixcorners We do that already. The problem was, that we enforced to have a hostname as well as a port being set. This would fail in the case of `:28967`, but not for `localhost:28967`.
