### ISSUE TITLE
Documentation: change 'minimum of 500GB' to '250GB'

### ISSUE THREAD

**Issue by xfilokolo** [storj/storj#3769]
Hi, there is a mistake in the documentation:
https://documentation.storj.io/before-you-begin/prerequisites
https://documentation.storj.io/setup/cli/storage-node

According to [this page](https://storj.io/storj-share-terms/), I think you need to update the documentation.

**Comment by MaxMaximus** [comment]
Pages to which you link are newer than the Storage Sharing Terms 
So I think it "Storage Sharing Terms and Conditions" needs to be updated, not docs. It already > 1 year old.
There are other discrepancies also: monthly Bandwidth available  (0.5 TB vs 2 TB minimum) for example.
And few other point, like "Operate more than one (1) Storage Nodes behind the same IP address"
This restriction was removed (after introducing IP filtering for data distribution) but it is still present in the "Storage Sharing Terms"

**Comment by ifraixedes** [comment]
@xfilokolo thanks for reporting it.
@MaxMaximus is right, we have to update the TOS.

Our legal team has recently addressed it and it's planned to publish the update this week.

**Comment by xfilokolo** [comment]
@ifraixedes 
So which is correct information? Minimal required space is 250GB or 500GB?

**Comment by stefanbenten** [comment]
500GB is the correct value @xfilokolo

**Comment by iglesiasbrandon** [comment]
@xfilokolo The Storj Operator terms have been updated to reflex the 500 GB minimum required storage space. https://storj.io/storj-operator-terms/ thank you for pointing this out!
