### ISSUE TITLE
win doker run err,help~

### ISSUE THREAD

**Issue by rectinajh** [storj/storj#3774]
anyone help me?

my script:

C:\Users\xsj>docker run -d --restart unless-stopped -p 28967:28967 -p 127.0.0.1:
14002:14002 -e WALLET="0xdC18bEA424211c4c0E85fF5268C2D4467D240584" -e EMAIL="rec
tinajh@gmail.com" -e ADDRESS="huajiang.ddns.net:28967" -e BANDWIDTH="20TB" -e ST
ORAGE="550GB" --mount type=bind,source="C:\Users\xsj\AppData\Roaming\Storj\Ident
ity\storagenode",destination=/app/identity --mount type=bind,source="D:\storj",d
estination=/app/config --name storagenode storjlabs/storagenode:beta

docker: Error response from daemon: invalid mount config for type "bind": invali
d mount path: 'C:/Users/xsj/AppData/Roaming/Storj/Identity/storagenode' mount pa
th must be absolute.
See 'docker run --help'.

**Comment by ifraixedes** [comment]
I'm not a Windows user, so I don't know that much about it and I cannot directly help, but I fund that in Window you have to indicate the directories that you want to share with Linux containers.

See https://docs.docker.com/docker-for-windows/#file-sharing

**Comment by rectinajh** [comment]
find the solution:
On Windows, you need to format the paths using double backslashes: D:\\identity\\storagenode\\ or D:\\data\\
