### ISSUE TITLE
Storj blog’s ‘subscribe’ button not working

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#3776]
It's been a month since it was [reported](https://forum.storj.io/t/storj-blogs-subscribe-button-not-working/3623). The button is broken so new blog posts go unnoticed.

**Comment by mniewrzal** [comment]
Hey @nerdatwork,
Thank you for keeping eye on it. Can you refresh forum topic? This repository is mainly for issues related to a product, not a web site.
