### ISSUE TITLE
Strange "lag" of space used in local node statistic

### ISSUE THREAD

**Issue by MaxMaximus** [storj/storj#3779]
Hello.

I have noticed strange lag/delay of local statistic collection for space used (GB**hours). 
Beginning from ~10 Feb statistics shown in node dashboard started to decrease slowly while actual space usage (checked by volume of "blobs" folder) was actually increasing all 3-4 days. Discrepancy grows larger each day until yesterday node suddenly "found" all lost data making huge spike on GB*hour graph. Screenshot:
![Storj-Space](https://user-images.githubusercontent.com/6316214/74519883-9deb8c00-4f27-11ea-91f8-5027f37a98c3.png)

There were no actual huge jump of space used on 13 Feb as dashboard shows. It "lost" data from 10-12 Feb was accounted in 13 Feb data point.

**Comment by MaxMaximus** [comment]
Exactly the same happened on both nodes i am currently running.
![storj-usage](https://user-images.githubusercontent.com/6316214/74521957-55ce6880-4f2b-11ea-9fce-1a2b0a1efe71.png)

They are separate physical machines with quite different hardware but similar software setup and running same node client - win-GUI ver 0.31.12

Per satellite stats shows that glitch was caused by one satellite: europe-west-1.tardigrade.io:7777
Stats for all other Sats looks about normal.  And for europe-west-1 it was at 0 (zero) for about 3.5 days and then all data placed on 4th day. Also something similar visible on egress traffic for this Sat (traffic went to exatly zero for day or two then jums while in logs i see activity for days shows as zero in stats):
![storj-satelliteusage](https://user-images.githubusercontent.com/6316214/74522497-5b787e00-4f2c-11ea-9ac9-6455c51ab77a.png)
Same apply to second node - all caused by same europe-west-1 sat - there is same gap with zero data for ~3.5 days then all data accounted on 4th day.

**Comment by littleskunk** [comment]
We had problems with the used space calculation and the repair checker on the satellite side. Both services are running side by side with garbage collection. Garbage collection was running out of memory and the process restarted. The used space calculation and the repair checker didn’t finish. Short term we increased the memory. Mid term garbage collection will not run on the first iteration. It will start on the second iteration after the used space calculation and the repair checker finished once. Long term we will split garbage collection into multiple processes.

As a side effect, you should see a used space spike on the storage node dashboard because the used space calculation is compensating the gap.

**Comment by MaxMaximus** [comment]
Hello.
Looks like issues is back again? 
Now saltlake.tardigrade.io and europe-west-1.tardigrade.io is lagging? As corresponding disk space usage graphs became "spiky" again, while other satellites looks OK:
![saltlake-usage](https://user-images.githubusercontent.com/6316214/80272516-fc28ae00-86d2-11ea-89b3-cc0fe6314357.png)

**Comment by MattJE9601** [comment]
Seeing the same issue.  First image is saltlake second is europe-west.
![index](https://user-images.githubusercontent.com/7246559/80285711-c1377200-86f4-11ea-8f5b-d0aa755f3301.png)
![index2](https://user-images.githubusercontent.com/7246559/80285738-f643c480-86f4-11ea-99f9-e57e9c13f1d2.png)

**Comment by MaxMaximus** [comment]
It getting worse - some satellites now drops to flat zero for 1 or 2 days like in this example for 3 and 4 May. While there were no any significant changes of real space usage at all.

![изображение](https://user-images.githubusercontent.com/6316214/81124586-80362d80-8f3e-11ea-8fb0-b80ae1b9c445.png)
