### ISSUE TITLE
"Out of space" message on available disk space node

### ISSUE THREAD

**Issue by Quake4** [storj/storj#3783]
![image](https://user-images.githubusercontent.com/29517243/74630260-3f165480-516b-11ea-99f7-5942aa3eb23b.png)

**Comment by Derkades** [comment]
What does `df -h` report?

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/74653921-40ab4100-519a-11ea-9510-2d1c7f0543b6.png)

**Comment by Quake4** [comment]
1 Tb drive
64Gb free
yaml: `storage.allocated-disk-space: 0.9 TB`

**Comment by phpbg** [comment]
Hi, same here.
* Dashboard reports `669.11MB Free`
* 500GB allocated
* `df -h`

    ```
    size    used    free
    541G  467G   47G  91% /var/storj
    ```
* lots of free inodes
* some successful uploads
* but in the end, I'm getting very low upload success rate (<10%)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/74717301-38f2a780-5241-11ea-8efa-b2481aeb9243.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/74717376-57f13980-5241-11ea-921d-e2d4861a0c0b.png)

**Comment by Quake4** [comment]
![image](https://user-images.githubusercontent.com/29517243/74717435-75be9e80-5241-11ea-83a9-8357d3c45b2a.png)

**Comment by Quake4** [comment]
0.33.4
![image](https://user-images.githubusercontent.com/29517243/74819704-d9b09800-5311-11ea-943f-1405d436132a.png)
![image](https://user-images.githubusercontent.com/29517243/74819754-eb923b00-5311-11ea-8397-ffc61a17af8f.png)
![image](https://user-images.githubusercontent.com/29517243/74819901-285e3200-5312-11ea-9fdb-b2c66fcdffb3.png)
![image](https://user-images.githubusercontent.com/29517243/74819967-42981000-5312-11ea-876a-2ac282dfa02f.png)

**Comment by Quake4** [comment]
Is it joke, you calc 0.9TB as 900 000 000 000 bytes?

**Comment by gsxryan** [comment]
Same errors here.  Dashboard shows 5.91GB Freespace.
df -h shows 730G Freespace
Getting "out of space" messages with Negative storage space remaining values in the logs.

**Comment by zeebo** [comment]
> Is it joke, you calc 0.9TB as 900 000 000 000 bytes?

Technically, that is what TB means: https://en.wikipedia.org/wiki/Terabyte. The power of two version is called a Tebibyte (https://en.wikipedia.org/wiki/Tebibyte) and would be written `0.9TiB`.

---

> Same errors here. Dashboard shows 5.91GB Freespace.
> df -h shows 730G Freespace
> Getting "out of space" messages with Negative storage space remaining values in the logs.
> 
> v1.1.1

What, if anything, do you have set for the `storage.allocated-disk-space` config value? The available space is controlled entriely by that value, and we only look at `df` output to determine that it's set sanely.

---

As I explained some in https://github.com/storj/storj/issues/3821#issuecomment-622209483, we have a cache that we look at to determine how much space is used for pieces and trash for various reasons. The storagenode should periodically walk the filesystem and update how much space is being used. Given that, plus the understanding that the `storage.allocated-disk-space` config value controls how much is available, does that account for all of the issues? If not, I'd love to hear and help diagnose it.

**Comment by Quake4** [comment]
Waiting https://github.com/storj/storj/commit/6c4d3f133fe38a6ea885abc505311c8b98fd1472 and retest all.

**Comment by Quake4** [comment]
@ifraixedes 
![image](https://user-images.githubusercontent.com/29517243/80913816-2ff97880-8d50-11ea-946d-cd492a0a7fc3.png)

**Comment by ifraixedes** [comment]
@Quake4 Thanks for posting an update. I let you know that I'm not personally working on this, I only labeled the issue for easy tracking.

Nonetheless, I'm wondering how you get the new result, did you build yourself the storagenode binary?

I'm asking because the https://github.com/storj/storj/commit/6c4d3f133fe38a6ea885abc505311c8b98fd1472 change has not been released yet.

**Comment by phpbg** [comment]
@Quake4 Why did you close this issue?

**Comment by ifraixedes** [comment]
@phpbg the issue is fixed in the lat release https://github.com/storj/storj/releases/tag/v1.4.2

Please check it once you update your node and if it's still not fixed we'll reopen it.

**Comment by Quake4** [comment]
reopen new
https://github.com/storj/storj/issues/3880
