### ISSUE TITLE
Unable to setup Storj-Sim, potentially due to update to Postgres

### ISSUE THREAD

**Issue by lucianstroie** [storj/storj#3803]
I'm unable to set up a test network following the instructions laid out [here](https://github.com/storj/storj/wiki/Test-network).

When I run `storj-sim network setup --postgres=postgres://postgres@localhost/<dbName>?sslmode=disable`
I get `zsh: no matches found: --postgres=postgres://postgres@localhost/<dbName>?sslmode=disable`

It's worth mentioning that running the previous instruction as listed now generates the following error:
```
$ docker run --rm -p 5432:5432 --name postgres postgres
Error: Database is uninitialized and superuser password is not specified.
       You must specify POSTGRES_PASSWORD to a non-empty value for the
       superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".

       You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
       connections without a password. This is *not* recommended.

       See PostgreSQL documentation about "trust":
       https://www.postgresql.org/docs/current/auth-trust.html
```

I've tried both suggested responses, was able to build the Postgres docker, but couldn't execute the `storj-sim network setup` command without removing `?sslmode=disable` but that doesn't setup correctly.

**Comment by ifraixedes** [comment]
Hi @lucianstroie,

You have, first to create a database in postgres, and then use the database name in such URL. For example, if you create a DB with name "testnet", then you have to pass the following URL `--postgres=postgres://postgres@localhost/testnet?sslmode=disable`.

Please try that and get back to us.

**Comment by lucianstroie** [comment]
Hi @ifraixedes ,
Yes, I'm sure I've created a db because I can login with  `psql postgres://postgres:<dbPASSWORD>@localhost/teststorj`
If you aren't getting an error when running just ` docker run --rm -p 5432:5432 --name postgres postgres` then your local docker image of Postgres is probably out of date. This was a new error for me as well after having run this successfully before as well.
Running `docker pull postgres` should update the image and allow you to replicate the error I'm experiencing. Note how there is no Postgres version specified in the instructions.

**Comment by mniewrzal** [comment]
@lucianstroie try URL with password specified like postgres://postgres:your_pass@localhost/<dbName>?sslmode=disable

**Comment by lucianstroie** [comment]
@mniewrzal ,it seems like your missing the db name in your URL example.
In my example, I replaced <dbPASSWORD> with my db password.

So, when I type the exact same Postgres URL I connect to the psql console with the following versions:
```
psql postgres://postgres:<dbPASSWORD>@localhost/teststorj                
psql (12.1, server 11.7 (Debian 11.7-2.pgdg90+1))
```

While I get this error when using the exact same Postgres URL:
```
storj-sim network setup --postgres=postgres://postgres:<dbPASSWORD>@localhost/teststorj?sslmode=disable 
zsh: no matches found: --postgres=postgres://postgres:<dbPASSWORD>@localhost/teststorj?sslmode=disable
```

**Comment by mobyvb** [comment]
@lucianstroie I am not super familiar with zsh, but it looks like the question mark in the postgres connection string might be the culprit based on this: https://github.com/ohmyzsh/ohmyzsh/issues/31

Looks like you can just surround the connection string with quotes or put a backslash in front of the question mark - `--postgres="postgres://postgres:<dbPASSWORD>@localhost/teststorj?sslmode=disable"`

Also, if you want, you can set an environment variable `$ export STORJ_SIM_POSTGRES=postgres://....` and then you don't need to provide the flag at all!

Please let me know if these solutions do/do not work.

**Comment by lucianstroie** [comment]
Hi @mobyvb , thank you. That did resolve the error I was getting but I was still not able to get strop-sim set up locally on my Mac with error messages similar to those where it couldn't find the db. 
I was able to set up on a Debian instance just fine so I will close this issue.
