### ISSUE TITLE
Uploads to node above free space threshold

### ISSUE THREAD

**Issue by kevinkk525** [storj/storj#3807]
My node has been almost full for quite some time now and didn't receive any new uploads. It is running 0.34.6, has 2.6 TB stored and 2.6TB assigned, dashboard says 2.43GB available.
However today it started to see uploads again, at least in short spikes.

According to the latest changelog, the node should tell the satellite when it is below a certain threshold (I think it was 100GB?) and only then start receiving new data.
So unless the threshold is suddenly at around 2.5GB, this might be a bug.

This is the traffic on my node from the last 24 hours (red is egress, purple is ingress):
![grafik](https://user-images.githubusercontent.com/9607123/76864269-1d3ee900-6861-11ea-96c7-a8135277e514.png)

And this is the storage IO for the last 24 hours:
![grafik](https://user-images.githubusercontent.com/9607123/76864463-5f682a80-6861-11ea-93e7-b02090ab7adf.png)

There were only 233 delete requests within the last 24 hours so there was hardly any space released from the node. However it received 403 successful uploads. 
The trash directory currently has 1.4GB so that shouldn't throw off the calculations.

**Comment by cam-a** [comment]
@kevinkk525 the threshold is actually 100MB, so this looks okay

**Comment by kevinkk525** [comment]
oh it was only 100MB? But then shouldn't the node get more uploads until it is below 100MB of free space and not be stuck at around 2.5GB of free space with only 1.1GB in trash?

**Comment by cam-a** [comment]
Yes that's correct, though I'm not sure I completely understand. I thought you said you received 403 successful uploads in the last 24 hours?

**Comment by kevinkk525** [comment]
Yes I received 403 successful uploads. 
I just re-checked my logs and the free space calculation on the dashboard is not the same as the available space calculation in the logs. There it says "Available Space: 96913792" after the last upload message, so this actually seems to work correctly. Only the available space shown in dashboard is differently.
Sorry for the trouble.

**Comment by ifraixedes** [comment]
@kevinkk525 you're welcome.

Regarding the dashboard, we are aware that we have a bug in the CLI and Web dashboard; they are not showing the correct number.
Thanks for mentioning.
