### ISSUE TITLE
node dashboard adaptivity  bug

### ISSUE THREAD

**Issue by katelinlis** [storj/storj#3811]
node dashboard adaptivity  bug
![image](https://user-images.githubusercontent.com/56870191/76968184-86922b00-6939-11ea-98c2-60cb7e700abe.png)
![image](https://user-images.githubusercontent.com/56870191/76968189-8a25b200-6939-11ea-83ee-9fba12993f79.png)

**Comment by NikolaiYurchenko** [comment]
Hi @katelinlis. Thank you for creating this issue. Tablet and mobile styles adaptation is currently in progress and should be finished in the nearest future. Have a nice day!

**Comment by masavoyat** [comment]
Same issue on PC (chrome 83.0.4103.97) when scrolling without moving:
![image](https://user-images.githubusercontent.com/12132957/84434465-5ef8e900-ac30-11ea-8d91-775046829c24.png)

**Comment by iglesiasbrandon** [comment]
This issue has been resolved. going to close this for now.
