### ISSUE TITLE
[Translate] Required to do multilingual support for many pages of the project

### ISSUE THREAD

**Issue by katelinlis** [storj/storj#3812]
Required to do multilingual support for many pages of the project
For storj.io , nodepage, tardisgrade

![image](https://user-images.githubusercontent.com/56870191/76989407-55c0ee80-6957-11ea-8b3b-650fac2b5228.png)
google translate broken style button and translate incorrect 

this good change for to attract a large audience of users

**Comment by ifraixedes** [comment]
@katelinlis thanks for your suggestion.

Please post this feature in our ideas.storj.io portal. It's better to track ideas like this and have people voting for them.
