### ISSUE TITLE
[Feature] node dashboard and more statistic and calculator

### ISSUE THREAD

**Issue by katelinlis** [storj/storj#3813]
In order to reduce the time to get an information about the profit for the node, it is possible to implement a special page, instead of downloading a python script and realize the possibility of statistics share in social networks

**Comment by ifraixedes** [comment]
@katelinlis thanks for your suggestion.

Please post this feature in our [ideas.storj.io](https://ideas.storj.io/) portal. It's better to track ideas like this and have people voting for them.
