### ISSUE TITLE
Uplink setup error

### ISSUE THREAD

**Issue by grafael** [storj/storj#3814]
### Issue
If you setup uplink with access name, and do not pass `--access`  as parameter, it will fail returning the error:

`Error: error setting up project: api key format error: invalid api key format `

### Steps to reproduce
1) Run `uplink setup` and pass an access name (not default)
2) Run any uplink command. For example `uplink ls`

If you run `uplink --access <access_name> ls` it will work.

**Comment by zeebo** [comment]
I was unable to reproduce this on master. What version of the uplink command were you using? You can find out by running `uplink version`.
