### ISSUE TITLE
Uplink: Add a recursive copy command to Uplink cp

### ISSUE THREAD

**Issue by phthano** [storj/storj#3817]
I can't copy directories in a sane way without resulting to xargs and witchcraft. I understand the aws cli can be used to do this with the sync command but that isn't also natively available in the Uplink tool. Please add this to the uplink binary.

**Comment by stefanbenten** [comment]
@phthano 👋 You should take a look at rclone, that should help you for now as well.
https://github.com/rclone/rclone/pull/3699

**Comment by dcrystalj** [comment]
@phthano  You can use https://www.npmjs.com/package/@dcrystalj/storj wrapper to transparently use recursive for folder when using `cp` or `rm` command.
Of you can switch to aws s3 gateway

**Comment by mniewrzal** [comment]
This is possible now with `uplinkng` binary which will replace existing uplink binary in near future.
