### ISSUE TITLE
Docker "invalid reference format" error on raspberry pi 3 node

### ISSUE THREAD

**Issue by Wndmldrs** [storj/storj#3818]
I am almost done setting a raspberry pi 3 up as a node. This is the code I need to use but for some reason I get an error (invalid reference format).
`docker run -d --restart always -p 28967:28967 \
-p 127.0.0.1:14002:14002 \
-e WALLET="0x000000....” \
-e EMAIL=“email@example.com” \
-e ADDRESS="externaladdress:28967" \
-e BANDWIDTH=“4TB" \
-e STORAGE=“600GB” \
--memory=800m \
--log-opt max-size=50m \ 
--log-opt max-file=10 \
--mount type=bind,source=/home/pi/.local/share/storj/identity/storagenode,destination=/app/identity \
--mount type=bind,source=/mnt/storagenode,destination=/app/config \
--name storagenode storjlabs/storagenode:beta`
I don't have a lot off experience with these things. Does somebody know what I'm doing wrong? Thanks in advance!

**Comment by Wndmldrs** [comment]
I think the error is in the `--log-opt max-size=50m`

**Comment by ifraixedes** [comment]
Hey @Wndmldrs,

Please paste here the docker log of the container: `docker logs storagenode`

**Comment by Wndmldrs** [comment]
Hi there, got it fixed. The issue was a space behind the line. Then I got another error but adding sudo did the trick.
