### ISSUE TITLE
Garbage accumulation by storage node

### ISSUE THREAD

**Issue by MaxMaximus** [storj/storj#3823]
Hello.

I see my storage nodes slowly accumulating garbage: volume files actually stored on disk ("blob" folder) grows faster compared to "TB * hours" (divided by 24) counters in nodes Dashboard / API.
"trash" folder is accumulating files too. Currently about 10 GB / ~ 10 000 files per node.
While my nodes were 100% uptime current month.

Looks like a lot of request from satellites to delete data pieces are not processing correctly and became  "garbage" until garbage collector found it and move to "trash" for 7 days before final deletion.
Or satellite does not send proper delete requests to SN at all and just remove piece meta generation garbage.

P.S.
Running Windows GUI. Currently on version v0.34.6

**Comment by zeebo** [comment]
> I see my storage nodes slowly accumulating garbage: volume files actually stored on disk ("blob" folder) grows faster compared to "TB * hours" (divided by 24) counters in nodes Dashboard / API.
"trash" folder is accumulating files too. Currently about 10 GB / ~ 10 000 files per node.
While my nodes were 100% uptime current month.

If you wouldn't mind, can you try collecting a couple data points of `(timestamp collected, size of blobs folder, TB*hours in dashboard)` for me? That may help me figure this out.

> Looks like a lot of request from satellites to delete data pieces are not processing correctly and became "garbage" until garbage collector found it and move to "trash" for 7 days before final deletion.
> Or satellite does not send proper delete requests to SN at all and just remove piece meta generation garbage.

Did you see any log messages about deletes from the satellite that make you believe they're not being processed correctly, or is this just due to the calculations mismatching?

**Comment by MaxMaximus** [comment]
I did not scan logs for delete errors. It based on 2 facts:
1. Calculations mismatching between `TB*hours` in dashboard and actual size of the "blob" folder
2. Significant files accumulation in "trash" folder even while node has 100% uptime and accessibility.  AFAIK regular (normal) deletes request executed instantly without storing deleted files in the "trash" folder for additional 7 days.

And about  data points collection. I can collect it, but i think it does not make sense right now due to related issue with high spikes of  `TB*hours` calculation of few satellites: https://github.com/storj/storj/issues/3779
It marked as resolved but that issue is back again for last few weeks. For example that i see for saltlake sat right now:
![изображение](https://user-images.githubusercontent.com/6316214/81124586-80362d80-8f3e-11ea-8fb0-b80ae1b9c445.png)
It makes individual `TB*hours` data points very unreliable: one day it much lower compared to actual size of data stored on disk, next day it can be much higher. I think total sum in the long term will be about right, but it still makes individual data points useless.

Actually i think  closed iisue https://github.com/storj/storj/issues/3779 can be primary source of garbage on 100% online nodes. If some scripts on few satellites can not cope with load - it can cause missing of proper delete requests to SN.

**Comment by MaxMaximus** [comment]
I close this issue as in all latest versions of storagenode space used calculations looks pretty accurate. I did not see significant discrepancies for some months.
