### ISSUE TITLE
Linksharing feature does not work with files with whitespace

### ISSUE THREAD

**Issue by phthano** [storj/storj#3829]
The "share" command will produce invalid URLs when whitespace is involved. I suggest we escape the spaces programatically. 

e.g.

https://link.tardigradeshare.io/blahblahblah/music/Warren-Zevon/04 - Werewolves Of London.flac

**Comment by zeebo** [comment]
Thanks for the bug report. I've opened https://review.dev.storj.io/c/storj/storj/+/1718 to address this issue.
