### ISSUE TITLE
Node dashboard doesn't want April to begin

### ISSUE THREAD

**Issue by lbndev** [storj/storj#3840]
Today is April 1st.
The graph knows.
The header believes it is still in March.

![image](https://user-images.githubusercontent.com/7209311/78111162-8c3d4580-73fc-11ea-8ddf-c2a461ac8679.png)

**Comment by stefanbenten** [comment]
@lbndev Hello and thank you for bringing this up. I'll investigate where this mismatch is coming from.
On my nodes they now match correctly, so i assume its a mismatch due to timezones.

**Comment by lbndev** [comment]
Hello @stefanbenten,
Today it looks fine on my nodes too.
So it's probably only happening on the first day of the month ?
Or could it be a browser refresh / cache problem ?

**Comment by VietTPham** [comment]
It uses UTC time, so it might not match your timezone

**Comment by stefanbenten** [comment]
Okay, i just checked to code and as i initially thought, it can simply happen due the timezone differences. Especially if a specific satellite is further in the timezones, this is impossible to circumvent.
Iam closing this until there is someone else able to find another evidence of where its wrong.
