### ISSUE TITLE
Tardigrade website: misleading mistake on website

### ISSUE THREAD

**Issue by xfilokolo** [storj/storj#3845]
Hello,
Tardigrade site says:
![image](https://user-images.githubusercontent.com/34312961/78348585-94cf8080-75a2-11ea-881a-886e4c5bb182.png)
But I think it should be “$0.045 per 1GB downloaded”, not “per 1GB bandwidth”.
Tardigrade users pay only for storage and download files from Tardigrade, not for both side transfer.
New users may mistakenly think that they are paying for both inbound and outbound traffic.

**Comment by stefanbenten** [comment]
@xfilokolo Please reopen this in the correct repo https://github.com/storj/tardigrade.io
