### ISSUE TITLE
Make database paths configurable

### ISSUE THREAD

**Issue by Hoeze** [storj/storj#3852]
Hi, can we please have those two lines configurable independently of the storage folder?
https://github.com/storj/storj/blob/02613407ae1543417dbcb4aa0c863a62a7f61a4e/cmd/storagenode/main.go#L130-L131

This is super annoying. I would like to try storj storagenode but I cannot since months because of this stupid, very easy-to-fix issue.

**Comment by zeebo** [comment]
I've created https://review.dev.storj.io/c/storj/storj/+/1716 to address this. Let me know if it wouldn't satisfy your use case.
