### ISSUE TITLE
storj text-based dashboard bandwidth line shifted

### ISSUE THREAD

**Issue by bacoboy** [storj/storj#3853]
Not sure which version this started, but the text based dashboard now shows the `Bandwidth` line shifted to the right so it no longer lines up with the columns:

![storj-shifted](https://user-images.githubusercontent.com/874597/79049763-223a5280-7beb-11ea-9a14-514060d2b6f1.jpg)

These are my settings:
```
    -e BANDWIDTH="50TB" \
    -e STORAGE="8TB" \
```

**Comment by nerdatwork** [comment]
Temporary solution is to try accessing it without `--color` option on your dashboard command

**Comment by JessicaGreben** [comment]
Thanks for the report @bacoboy, looks like we have a change merged that should fix the indentation. It should get released in the next version in a week or two.  https://review.dev.storj.io/c/storj/storj/+/1517

I will close this issue for now, but if the problem shows back up we can open it up.

**Comment by bacoboy** [comment]
@JessicaGreben is bandwidth not something used anymore?  I'm wondering if I even need to be setting the `BANDWIDTH` environment variable on startup...

**Comment by bacoboy** [comment]
Nevermind -- looks like it got removed [looking at the docs](https://documentation.storj.io/setup/cli/storage-node) -- must have missed the announcement.
