### ISSUE TITLE
1.3.3 dashboard error

### ISSUE THREAD

**Issue by Quake4** [storj/storj#3866]
![image](https://user-images.githubusercontent.com/29517243/80317987-b32a4400-880f-11ea-8aba-543a3fb611af.png)
![image](https://user-images.githubusercontent.com/29517243/80318022-e10f8880-880f-11ea-9249-44f6ba63208c.png)

**Comment by zeebo** [comment]
From the looks of it, this should have fixed itself within about 5 minutes of the node being online. Is that the case?

Regardless, the change at https://review.dev.storj.io/c/storj/storj/+/1714 should fix this so that there is no window where this error occurs.

**Comment by Quake4** [comment]
Yes. Its working after 5-10 min from start. 
localhost:14002, sno dashboard.
