### ISSUE TITLE
Unit incosistency for average storage usage in storage node dashboard

### ISSUE THREAD

**Issue by MaxMaximus** [storj/storj#3870]
Hello

I know that Payout Information section of Dashboard is not fully finished yet and there are few known issues. But i think this one was not listed as already known.
There is a mess with units for storage usage. For last month (April) `TB*month` is used. For previous months its `TB*hours` while displayed as `TB*month` too. 

Here is an example:

![изображение](https://user-images.githubusercontent.com/6316214/80764818-2b637300-8b4a-11ea-8dee-6a1bfcd514ae.png)

It is not 183 `TB*month` of course - its 183 `TB*hours` (= 0.25 TB*month)

It creates even more mess if few month selected as range as incosisten units summarized into one value .

**Comment by zeebo** [comment]
Thanks for bringing this up. I'm going to make sure it's discussed with the owners of the dashboard so that we can get the calculations right and with the right units.

For what it's worth, the I believe the correct unit should be `TB*hours` because months do not have a consistent number of hours in them, and the code that calculates the payments uses `TB*hours`.

**Comment by littleskunk** [comment]
The problem with `TB*hours` or more likely `PB*hours` is that it doesn't mean anything to the user. How much used space is it? For that reason I would prefer to show `TB*month` everywhere on the storage node dashboard.

**Comment by zeebo** [comment]
Maybe a compromise is `TB*days` so that it's at least a real fixed unit while being a factor of 24 smaller?

**Comment by MaxMaximus** [comment]
I think in the code fixed conversions is used `1 TB*month = 730 TB*hours`.
It have been this way even in Storj V2.

730 was chosen as an average number of hours in month: `365 * 24 / 12 = 730`
So `TB*hours, TB*days and TB*months`  can be consistently converted in any ways.

P.S.
As a SNO i prefers `TB*month` as primary unit for payout calculation pages (as payment rate for storage is set per 1 `TB*month` basis - e.g. 1.5 USD currently).
But for storage usage graphs on dashboard `TB*days` units will be much more convenient compared with both alternatives (hours or months). Just because 1 data point on graphs is 1 day. So if usage is shown in the `TB*days` units on graphs- then this values will coincide with the actual average amount of disk space used on the corresponding days without the need for any additional conversions or calculations.
E.g. if 2.5 TB is stored on disk of my node - i expect to see 2.5 TB*days on the graph after day is finished and usage data collected.

**Comment by profclems** [comment]
@zeebo was this issue ever discussed internally with the dashboard owners?

**Comment by Erikvv** [comment]
I've gone back to March and April 2020 on my payout page and I don't have this issue where it mixes TB*month and TB*hour.

This looks fixed so I propose to close the issue. There is another ticket about the graph on the dashboard.
