### ISSUE TITLE
New Feature: Split blobs in 2 or more directories 

### ISSUE THREAD

**Issue by victorelec14** [storj/storj#3875]
It would be very useful to be able to split the data directory (blobs) into 2 or more directories, to be able to divide it into 1 or more disks without having to create Raids or create more nodes (which I believe is not allowed to have more than 1 node per IP public?)

For many people creating a RAID is very complicated or they must deal with passing the information to another disk before putting it in the raid, or the problem of whether the RAID is too small.

It would be more useful to be able to divide into directories so you could unify the data in case you need the other disk or divide in case it is filling up.

Thanks ! :D

**Comment by stefanbenten** [comment]
Hey @victorelec14 ,

Please propose this feature in our forum via this link: https://forum.storj.io/c/parent-cat/sno-feature-requests-voting/38

Thanks!

**Comment by jtolio** [comment]
@victorelec14 also worth pointing out that you absolutely can run more than one node on the same IP
