### ISSUE TITLE
Unable to use network drives

### ISSUE THREAD

**Issue by Beddhist** [storj/storj#3892]
I have a 4-bay NAS and set up the Windows GUI to use this.

Here are the errors I have encountered:

Store data to: \\\qt\storj\
Error: Object must be a root dir or a drive letter.

Store data to: c:\mnt\qt\storj\
Error: the drive has only 499 GB disk size. The min is 550 GB.
Here the net share is mounted permanently in the dir mnt, but setup doesn't understand that. Other drives can be mounted the same way, both external and internal. It's even a feature of Diskmgmt.

Mapped drive letter worked, but the service cannot be started.
When I try to run the service from cmd:
```
C:\Users\Dell>"C:\Program Files\Storj\Storage Node\storagenode.exe" run --config-dir "C:\Program Files\Storj\Storage Node\\"
Error: couldn't open sink "winfile:///C:\\Program Files\\Storj\\Storage Node\\\\storagenode.log": open C:\Program Files\Storj\Storage Node\\storagenode.log: Access is denied.
```

My last resort is now to try iSCSI.

**Comment by Beddhist** [comment]
Progress: iSCSI lets me almost install the storage node. It still fails to start the service.
Workaround:
Open Notepad as admin, open config.yaml.
Remove the extra \ from the log file name:
`log.output: winfile:///C:\Program Files\Storj\Storage Node\storagenode.log`

Installation completes.

New problem: unable to open the console:
`  | Hmmm... cannot reach this page                                 Try this                                                                                                           Make sure that you’ve got the right web address:  http://localhost:14002`

**Comment by super3** [comment]
@Beddhist what NAS make and model are you using?

**Comment by Beddhist** [comment]
It's a QNAP TS-431, with 16 TB.
The specs are very constrained:

Dual core ARM v7l CPU
Linux 32-bit, old kernel.
No distro, an old version of Busybox.
512 MB RAM, about 1/2 free
Disks managed by LVM2 and adm as RAID (even single volumes)
Lack of std. libraries, probably requiring a statically linked compile to use any non-QNAP binaries.
I tried copying binaries and libs from an SBC, but didn't get it to work.
Docker not supported.

The SN is now installed on a dedicated PC, accessing the NAS via iSCSI. I've documented the other errors encountered while installing it in the forum.

**Comment by super3** [comment]
Is it not running the default qnap software? Can you run virtualization station or container station?

**Comment by Beddhist** [comment]
Yes, it is, the latest supported version. But no, both stations are not supported, I think because of small RAM. It also doesn't do storage pools, block-based iSCSI, snapshots and probably a few more. It's an entry-level NAS.

However, there is something called Entware, which gives access to a repository of software for embedded Linux devices and through that you can get GCC, glibc and a few thousand more things, which *MAY* enable us to compile it on the box. (I do have ssh access.)

Personally, I don't need this any more, now that I have it running on my mining PC (except for a problem of port not open through 2 routers). But if you want to go down that route I'm happy to be a tester. It may or may not yield a way of installing SN on a bunch of other devices, like routers with attached disk.

**Comment by super3** [comment]
Ok. We will still look into why that is not working. 

Maybe you had a similar issue to me where you have an ISP router, and your personal router connected to it? You have to setup port forwarding on both.

**Comment by Beddhist** [comment]
Yes, that is exactly the case: there is a ZTE 612 FON, which I believe is owned by the ISP. I do have access to it and set up port forwarding to my Linksys X3000 wifi router's WAN IP. On this I have set up forwarding to the PC. The X3000 is my gateway and DHCP server. The PC has a reserved DHCP address. When I run the port forwarding tester it shows the port as closed. Debug logging on the ZTE shows nothing, but I don't know whether that might be normal behaviour. The incoming connections log on the X3000 shows nothing incoming at all.

I tried turning off firewalls on PC and X3000, but no change. I also cannot access the dashboard from my laptop, which is strange, as I had a Burstcoin miner running on it and never had a problem getting to its web page. I also set up an incoming firewall rule on the SN PC for TCP port 14002 and turned off the firewall on the laptop.

I have used these as guides:
https://portforward.com/zte/f612w/
https://portforward.com/cisco-linksys/x3000/

I have considered making the ZTE our gateway, but I am worried that one day the ISP will replace it and then I will have a bigger problem.

Since this is not related to the network drives problem, should we move this discussion to the forum?

**Comment by super3** [comment]
Sure lets do that..

**Comment by ifraixedes** [comment]
@Beddhist @super3 can we close this issue now that the conversation is moved to the forum?

**Comment by Beddhist** [comment]
Yes, but somebody needs to look at the errors that occurred during installation. I just saw another post by a new user who had similar problems, with the only indication being that the service refuses to start.

Thanks for all your help.
