### ISSUE TITLE
Incorrect calculation of month number on SNOboard

### ISSUE THREAD

**Issue by ReneSmeekes** [storj/storj#3902]
After looking into differences between month numbers in my earnings calculator and the web dashboard I ran into an issue with displaying of month numbers in the web dashboard. Find a breakdown below.

https://github.com/storj/storj/blob/427bfc13fb12829b0785d70a230e586c8841c08c/web/storagenode/src/app/store/modules/node.ts#L157:L163

```
const now = new Date();
```
Not entirely sure, but I think this would use local date, not UTC.

```
const secondsInMonthApproximately = 2628000;
```
An average number of seconds in a month is used... why? This will lead to rounding errors. And since we're trying to count calendar months and not 30 day periods, this is not the right approach to begin with.

```
return Math.ceil(differenceInSeconds / secondsInMonthApproximately);
```
Number of months is calculated as the number of "approximate" months between join and now rounded up. Which is simply wrong as it shouldn't be counting a time difference, but the number of calendar months.

If you join on January 31st and it is now February 1st, it is your second month, but that one day difference rounded up would be counted as 1 month with this method. So it displays 1 instead of 2.

The strange part is that it's so simple to do it right:
(utcnowYear - joinYear) * 12 + (utcnowMonth - joinMonth) + 1
No need to bother with number of seconds in a month.

So I'm left to conclude the calculation on the web dashboard is currently not correct.

**Comment by ifraixedes** [comment]
@ReneSmeekes thank you very much for reporting it.

We have tracked the bug in our issue tracker and we started to work on it.
We'll keep you post it once it's fixed.

Thank you for your patience.

**Comment by NikolaiYurchenko** [comment]
@ReneSmeekes thank you for reporting it.

We are aware of the difference between satellite- and node-side months-online calculations and I am currently busy with changes that will be fixing it soon. 
In the nearest future, this issue will be fixed. I`ll attach link to commit when it will be merged to the master branch. 

Thank you and have a nice day.

**Comment by NikolaiYurchenko** [comment]
Resolved in https://github.com/storj/storj/commit/18914e4d1af9e79d9246c8172273e325bcb05b24

**Comment by ReneSmeekes** [comment]
Compliments on the quick resolution. Looks great now!
