### ISSUE TITLE
Flags stability (--storage2.database-dir)

### ISSUE THREAD

**Issue by hekmon** [storj/storj#3907]
Hello,

This issue is more a question about something that can become an issue.

I have tuned my node to separate the blobs (which use the default config path `config/storage`) on an array of slow but dense disks and the db files on fast and reliable SSD array (same as the system) using the `--storage2.database-dir` and another docker mount.

While this works perfectly, I wonder about the stability of this setup: for now user configuration stability is ensured thru the docker [entry point](https://github.com/storj/storj/blob/v1.6.3/cmd/storagenode/entrypoint) by converting the env vars to flags values. It has the advantage of abstracting them to the user: if one flag change in the future, you will just have to update the entrypoint script the fix the mapping. 

But what about custom flags allowed by the image on the `exec` [last line](https://github.com/storj/storj/blob/v1.6.3/cmd/storagenode/entrypoint#L19) with `"$@"` ? How will I handle on my side a change in the flags interface if any ?

**Worse case scenario**

Flag is silently discarded and after an auto update of the docker image, the node is restarted without the knownledge of the locations of the DB: it starts "clean" with orphan blobs. All audits fails while the data is actually here and the node is banned from the network without the operator being alerted.

**Best case scenario**

- First deprecate the flag by converting its value to the new one and print a warning during a first phase
- Secondly, if the flag is still used on a second phase, starting the node fails. This will allow any monitoring setup by the user to detect something is going one and allow the operator to fix the situation while looking at the logs

Any insight on this question would be greatly appreciated :)

**Comment by ifraixedes** [comment]
@hekmon thanks for expressing your worries.

I have to confirm with team in charge of the storage node application but I believe that we are already caring when deprecating flags to inform about it in our changelogs and deprecate them during a few versions so the storage node operators have time to tweak their configurations before the flag is ultimately removed.

About your _worse case scenario_ I let you know that if you pass a flag that doesn't exist then the application doesn't run reporting `unknown flag`, so if we remove a flag and you still passing it, it won't run.

**Comment by hekmon** [comment]
An even worse scenario crossed my mind...

Storj removes the exec [last line](https://github.com/storj/storj/blob/v1.6.3/cmd/storagenode/entrypoint#L19) parameters passthru `"$@"` silently ignoring the actual location of db files :scream:

**Comment by egonelbre** [comment]
We currently have https://github.com/storj/storj/blob/master/scripts/testdata/satellite-config.yaml.lock to keep track of satellite flag changes. We probably could do something similar with storage nodes and add them to release notes.

**Comment by ifraixedes** [comment]
@hekmon the parameters aren't passed from docker to the [`entrypoint` script](https://github.com/storj/storj/blob/v1.6.3/cmd/storagenode/entrypoint) because [Dockerfile `ENTRYPOINT` instruction](https://github.com/storj/storj/blob/v1.6.3/cmd/storagenode/Dockerfile#L12) doesn't allow dynamic input arguments.

If you want to run the storagenode with specific parameters then you have to the container specifying the entrypoint, e.g. `docker run storjlabs/storagenode /app/entrypoint --storage2.database-dir /my/db-files/path ...`

Nonetheless, we have to do something about it, unless it may only be improving our documentation about how to run it with custom parameters.

**Comment by hekmon** [comment]
@ifraixedes are you sure ?

From [the docs](https://docs.docker.com/engine/reference/builder/#entrypoint):

> Command line arguments to docker run <image> will be appended after all elements in an exec form ENTRYPOINT

Because if that's not the case I don't see how my node can guess my db mount/folder :)

Actually I run my storage node as a systemd service unit with the following
```
[Unit]
Description=Storj distributed storage node
After=network-online.target docker.service
BindsTo=docker.service

[Service]
Type=simple
EnvironmentFile=/etc/default/storj
ExecStart=/usr/bin/docker run --rm -p "${PORT}":28967 -p 127.0.0.1:${DASHPORT}:14002 -e WALLET="${WALLET}" -e EMAIL="${EMAIL}" -e ADDRESS="${ADDRESS}:${PORT}" -e STORAGE=${STORAGE} --mount type=bind,source="${IDENTITY_DIR}",destination=/app/identity --mount type=bind,source="${STORAGE_DIR}",destination=/app/config --name storagenode storjlabs/storagenode:beta $FLAGS
Restart=always

[Install]
WantedBy=multi-user.target
```

My `FLAGS` env var being:
```bash
FLAGS="--storage2.database-dir /app/config/storage-db"
```

So the `--storage2.database-dir` is definitly appended to the `EXEC` form of the entrypoint as I can confirm that the db files are indeed stored in `/app/config/storage-db` ;)

**Comment by ifraixedes** [comment]
> @ifraixedes are you sure ?
> From the docs:
> Command line arguments to docker run  will be appended after all elements in an exec form ENTRYPOINT
> Because if that's not the case I don't see how my node can guess my db mount/folder :)

yes, you're right, I didn't read the documentation and I thought that [it was your problem](https://github.com/storj/storj/issues/3907#issuecomment-643798367) and for whatever reason, I thought that I tested yesterday and see that the arguments weren't passed but it turned that I didn't and I only tested with specifying the entrypoint script.

So, I didn't understand the issue that you commented

> An even worse scenario crossed my mind...
> Storj removes the exec last line parameters passthru "$@" silently ignoring the actual location of db files scream

**Comment by hekmon** [comment]
My bad, I will try to be more explicit:

1. docker run cmd with final arguments passed as sufix for the exec entrypoint directive
2. entrypoint receiving the env vars and the parameters is actually [a script](https://github.com/storj/storj/blob/v1.6.3/cmd/storagenode/entrypoint)
3. script which process en vars to prepare the storagenode start with correct flags but also pass the entrypoint extra parameters to the node start thanks to `"$@"` at the end

So if the entrypoint/script losse its final `"$@"` my extra parameters will be send to the entrypoint script but not passed to the storage node start, silently ignoring them.

**Comment by ifraixedes** [comment]
That's what I thought that we were doing with it, so I interested your comment as a bug and I thought that the problem was the `ENTRYPOINT` Dockerfile instruction.

Anyway why do you think that the `entrypoint/script` could lose its final `@` parameter?

**Comment by hekmon** [comment]
> Anyway why do you think that the `entrypoint/script` could lose its final `@` parameter?

No idea, just wondering !

I think my initial question is more political than technical: the idea is to know which level of confidence I can have on these interfaces.

For example storj could say:
> "neither the flags or the entrypoint should be considered stable their are reserved for the devs, only the ENV VAR stated within the doc is and will map what is necessary"

or
> "entrypoint and flags can change but extra parameters will always be passed to the storage node binary alowing operator to detect change afterward if not already alerted by the communication we did on email"

or
> "nothing is stable, yolo & good luck !"

The risk of being banned after several years of participation is not null and linked to these 2 things:
* the flag itself (will it stay, will it disapear, will it change ?)
* the transmission of the flag thru the docker image (docker run -> entrypoint script -> storage node binary)

Point is, do you have any policy for storage node operators interfacing storage nodes flags directly thru the docker image or not, idea being assessing the risk of using them :)

**Comment by ifraixedes** [comment]
Thanks for the feedback. Now, I've got your point.

I'm going to expose this and see if we could come up with some written deprecation and backward compatibility policy for storagnode.

**Comment by ReneSmeekes** [comment]
This isn't really a solution to your overarching question, but you can also set this db path in the config.yaml file. That saves you from having to pass the flag to the binary in the first place. Of course that comes with its own limitations and dangers.

```
# directory to store databases. if empty, uses data path
storage2.database-dir: /app/db
```

**Comment by hekmon** [comment]
> This isn't really a solution to your overarching question, but you can also set this db path in the config.yaml file. That saves you from having to pass the flag to the binary in the first place. Of course that comes with its own limitations and dangers.
> 
> ```
> # directory to store databases. if empty, uses data path
> storage2.database-dir: /app/db
> ```

Good to know !

**Comment by profclems** [comment]
Closing this: it was more of a question than an issue
