### ISSUE TITLE
Old versions of SN software can not update if previous update was missed

### ISSUE THREAD

**Issue by MaxMaximus** [storj/storj#3909]
Hello.

Two of my nodes "stuck" at ver. 1.3.3. I was not able to update them for about a 10 days. Today one node was "lucky" and got an update to  1.6.3 and second still refuses to update and keep running on 1.3.3.
updater-log shows this:
```
2020-06-16T04:50:41.302+0300	INFO	Downloading versions.	{"Server Address": "https://version.storj.io"}
2020-06-16T04:50:42.193+0300	INFO	New version available but not rolled out to this nodeID yet	{"Service": "storagenode"}
2020-06-16T04:50:42.193+0300	INFO	Downloading versions.	{"Server Address": "https://version.storj.io"}
2020-06-16T04:50:42.340+0300	INFO	New version available but not rolled out to this nodeID yet	{"Service": "storagenode-updater"}
```
I think there is no bugs in the updater itself, but it just designed to check for latest version ONLY. Which is 1.6.3 and probable does "not rolled out" to this nodeID yet, indeed.
And previous releases (1.4.2 and 1.5.2) not checked at all.

Not sure what will be to do best here. Allowing updates to intermediary version probable need a big redesign of update procedures.
May be just adjust server part to "roll-out" latest releases to nodes running old versions first?
E.g. if the latest release is 1.6.3, then nodes running previous stable release (1.5.2 in this example) go trough standard staged "roll-out" process and all nodes running older versions (< 1.5.2, like 1.4.2, 1.33, 1.2.x etc) can update to latest version without delay?

Without it you can "kick out" some nodes with next rise of min versions required to work (which is 1.3.0 now) and blocking update to latest release due to "roll-out" process. Only way out of this will be owner intervention and manual downloading and reinstall of SN software to the same directory instead of update.
And combined with missing notification about running outdated version in dashboard ( #3906) and "not rolled out" messages in logs some owners will not even understand what they need to do this ASAP.

**Comment by stefanbenten** [comment]
@MaxMaximus Is this issue still present for you? If not please close it :+1:

**Comment by MaxMaximus** [comment]
Yes, I haven't seen this problem in a long time. So I think it has already been resolved.
