### ISSUE TITLE
Audit after GE

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj/storj#3911]
My node successfully did GE about a month ago on Stefan satellite, but now I see in log audits of files than was deleted.
Node ID: 12EEcfwBgnh6K5t1CtSHDyoauLaJ4nAsWPs9Z2zNJ7tvzdZBhhU

![image](https://user-images.githubusercontent.com/46418015/85211945-98c79f00-b356-11ea-8857-83ca7fb9940c.png)

`docker logs storagenode 2>&1 | grep "118UWpMCHzs6CvSgWd9BfFVjw5K9pZbJjkfZJexMtSkmKxvvAW" | grep -c "file does not exist" `                                                                                                                                                       `3290`

The logfile [is here](https://drive.google.com/file/d/1U27_CkGg_CCcYkpns6xPJFJ-88yAy_g7/view?usp=sharing).

**Comment by andriikotko** [comment]
Hi, thanks for your help. We open the bug for that case https://storjlabs.atlassian.net/browse/SUP-170

**Comment by NikolaiYurchenko** [comment]
Hi @AlexandrTyshchenko. 

Thank you for reporting this issue. We are already working with disabling satellite-node communication after Graceful Exit and in the nearest future, this will be fixed.

Thank you and have a nice day.

**Comment by profclems** [comment]
@NikolaiYurchenko @andriikotko can you confirm this issue is fixed?

**Comment by iglesiasbrandon** [comment]
This issue is stale, closing it for now. Please reopen this issue if this bug is observed again.

**Comment by AlexandrTyshchenko** [comment]
So, please provide a link to the common with a fix, or at least describe how you resolved this issue.

**Comment by iglesiasbrandon** [comment]
hey @AlexandrTyshchenko we are looking for the commit we believe fixed the issue and will post it here when we find it. cc @profclems
