### ISSUE TITLE
Bucket empty in uplink but not in Tardigrade dashboard

### ISSUE THREAD

**Issue by Erikvv** [storj/storj#3922]
Tardigrade dashboard says I have 1 object in the bucket but uplink says 0.

I have full access to the bucket but can't delete it

I don't know how I got myself in this situation :)

```
$ ./uplink ls
BKT 2020-07-11 23:13:01 literature
BKT 2020-07-11 23:18:18 literature2

$ ./uplink ls sj://literature
(no output)

$ ./uplink rb sj://literature
Bucket literature have NOT been deleted
Error: uplink: bucket not empty ("literature")
```

**Comment by VinozzZ** [comment]
Have you tried to use `uplink rb --force` to delete the bucket?

**Comment by Erikvv** [comment]
That solves that. I think the issue may be that at some point there was some memory corruption when using uplink-c but I haven't found a root cause. It may just be that I was passing an invalid pointer.
