### ISSUE TITLE
Web-Dashboard not showing returned held amount

### ISSUE THREAD

**Issue by kevinkk525** [storj/storj#3925]
This is the same issue as reported on the forum: https://forum.storj.io/t/web-dashboard-not-showing-returned-held-amount-bug-report/8483

My node now got the data from the July payout and when checking it, I was a bit surprised that “it didn’t calculate correctly”:
![grafik](https://user-images.githubusercontent.com/9607123/89415500-3b33ba00-d72c-11ea-83f7-884d8ee754a6.png)

```
Download $13.97
+ Repair+A $1.91
+ DiskUsea $6.48
= $22.36
-  $8.65 Held Amount
= $13.71
```

So Dashboard shows a Total of $16.42 although the calculation would suggest that $13.71 would be the correct payout total.

What happened? My node got $2.72 from the Held Amount from us-central-1 back but that doesn’t show up in the Dasboard anywhere so you’re left wondering where the difference originates from.

I found out using earnings.py:
![grafik](https://user-images.githubusercontent.com/9607123/89415527-44248b80-d72c-11ea-8470-5adab254b959.png)

**Comment by ifraixedes** [comment]
@kevinkk525 thanks for reporting it.

I let you know that this work is almost done. We'll close this ticket once is ready and know in which version will be released.

**Comment by stefanbenten** [comment]
The new version v1.13.1 that just started to be rolled out, is fixing this problem. I am going to close this issue, feel free to reopen if it doesnt work as expected.
