### ISSUE TITLE
Node Appears to Write to Depreciated storj_reports.log

### ISSUE THREAD

**Issue by gbaker3** [storj/storj#3928]
Node v1.9.5 is running in Docker on Debian Stretch on arm64. There is a file located at /var/log/storj_reports.log that seems to indicate the node is trying to call a binary that doesn't exist anymore.

The last successful log entry (there are no time stamps):

```
Sending report for node config
{'current_size': 44534882811, 'node_capacity': 3580000000000.0, 'report_uuid': 'd3135e7c-3f3c-4ea6-8470-f286ba163b29', 'version': '0.3.12', 'server_uuid': 'b44b9322-54a3-44a4-bffe-ef39826f5d77', 'node_name': 'config', 'storj_node_id': 'c8xxx3x9xx5x6939xx4x1x0x77828x279397x1xc'}
```
After this line is nearly 16,000 lines of:
```
/bin/sh: 1: /usr/local/bin/send_storj_reports: not found
```
The file was last written to as of this morning, so I believe this is an ongoing issue and not an old log file. Looks like a depreciated reporting feature that should be disabled/removed if no longer in use.

**Comment by littleskunk** [comment]
Wrong repository. Take a look here: https://github.com/sibblegp/Storj-Dashboard-Client

**Comment by gbaker3** [comment]
My mistake, sorry.

Thanks for pointing me in the right direction!
