### ISSUE TITLE
Incorrect documentation regarding identity creation and authorization

### ISSUE THREAD

**Issue by nkbphazon** [storj/storj#3931]
The documentation at [https://documentation.storj.io/v/alpha/getting-started/setup-a-storage-node#create-an-identity](url) lists the steps to create an identity as

>1. Open a terminal window.
>2. Go to the directory with your identity binary. 
>3. Use the create command to create an identity: 
>`./identity_linux_amd64 create storagenode`
>4. This process will continue until it reaches a difficulty of 30. On completion, it will look something like this:

This process does in fact create an identity using the default difficulty of 30. Later in the instructions it has you use the following command to sign:

`./identity_linux_amd64 authorize storagenode <email:characterstring>`

This fails due to the difficulty being too low:

`me@storj:~/identity$ ./identity_linux_amd64 authorize storagenode redacted@mail.com:tokenstringfromemail`
`2020-08-19T17:33:28.156Z        ERROR   Failed to do periodic version check: Get https://version.alpha.storj.io: dial tcp: lookup version.alpha.storj.io: no such host`
`2020-08-19T17:33:28.490Z        FATAL   error occurred while signing certificate: rpc error: code = InvalidArgument desc = certificates peer error: authorization claim error: difficulty must be greater than: 35
(identity files were still generated and saved, if you try again existing files will be loaded)`

**The documentation should be updated to include the difficulty parameter for identity creation, and should not imply in the steps that 30 is an acceptable difficulty:**
`./identity_linux_amd64 create --difficulty 36 storagenode`

**Comment by stefanbenten** [comment]
This has been solved/fixed!
