### ISSUE TITLE
Hosting Sign-Up Page Does Not Work

### ISSUE THREAD

**Issue by chlarsen** [storj/storj#3932]
Greetings,
This seems to be na old issue, first reported in the forum in November 2019. It is impossible to continue beyond the (successful) hardware requirement check, notwithstanding the type of browser or operating system used.
Any thoughts? Thank you!
Chris

**Comment by nerdatwork** [comment]
Have you tried this ? 

https://registration.storj.io/

**Comment by chlarsen** [comment]
Thank you, this link worked, indeed. Much appreciated.
