### ISSUE TITLE
Storj Dashboard: See Audit/Uptime Percentages for all satellites at once

### ISSUE THREAD

**Issue by ThePiGuy** [storj/storj#3937]
Can we replace the Audit/Uptime Percentage area with a table that populates for every satellite at once, instead of having to pick a specific satellite from the dropdown at the top? This table could ideally include the following columns:

- Satellite
- Suspension Score
- Audit Score
- Bandwidth Used This Month
- Disk Space Used this Month

It would show the above stats for each Satellite, where each row is a different Satellite.

**Comment by stefanbenten** [comment]
With the new version (v1.13.1 that just started to roll out), we mostly addressed your improvement ideas.
We have an audit and suspension table that easily gives you the requested overview.

As far as i understood, we do not want to create a table for the individual traffic values.
For that reason i am closing the issue for now. 

If this issue gets enough upvotes however, we might have to change the plan 👍

**Comment by ThePiGuy** [comment]
Extremely reasonable! Looking forward to seeing the Audit Score table. Thank you!
