### ISSUE TITLE
storagenode.msi    Installation error

### ISSUE THREAD

**Issue by xinli6991** [storj/storj#3951]
storagenode.msi    Installation error
I’m sorry to bother you. I don’t know if there is a problem with my installation steps or other problems.
![1](https://user-images.githubusercontent.com/54928470/95759247-07e94a80-0cdc-11eb-844d-20180b3e9f08.PNG)

**Comment by nerdatwork** [comment]
Hi @xinli6991 !

I am not aware if the latest version has this issue but the version that worked for me was 1.9.5

https://github.com/storj/storj/releases/download/v1.9.5/storagenode_windows_amd64.msi.zip

It will automatically update to the latest version.

When its done do update this thread.

**Comment by stefanbenten** [comment]
Hey @xinli6991 , 

is this still valid with the most recent installer?
Please report back, else we are going to assume that it is fixed and close this issue.
