### ISSUE TITLE
More information in docker exec -it storagenode /app/dashboard.sh

### ISSUE THREAD

**Issue by HeroHann** [storj/storj#3962]
Hello,
I am setting up new nodes and I noticed, that important information like uptime, vetting and so on are missing in the cli dashboard. Why is that?
Would be great to have it all in there not just a few things!

Thanks!

**Comment by stefanbenten** [comment]
Hello @HeroHann !
The CLI Dashboard is outdated and not further developed. The Web UI has all the necessary information and is backed by an API, which you can use to create your own monitoring via the CLI.
Does that explain enough why?

**Comment by HeroHann** [comment]
Yeah I guess so.

**Comment by stefanbenten** [comment]
If you are okay with this, would you mind closing this issue then?
