### ISSUE TITLE
Mismatching Overview and Satellite view for Suspension & Audit

### ISSUE THREAD

**Issue by Doom4535** [storj/storj#3965]
The overview reports a different percent score when `All Satellites` is selected from that of when a single satellite is selected.

`All Satellites` view:
![storj_overview](https://user-images.githubusercontent.com/6473994/98551789-b8ab2100-226b-11eb-864d-12948804c1d8.png)

Single satellite view (in my case `europe-west-1`):
![storj_europe_west](https://user-images.githubusercontent.com/6473994/98551799-bd6fd500-226b-11eb-8c07-aa50ba85465e.png)

I suspect that this is solely a difference in rounding, and that changing the following line from `return this.amount.toFixed(1);` to `return this.amount.toFixed(2);` will solve the issue.https://github.com/storj/storj/blob/1e356f1c5f0f78107e5ff6433fb099be9f042745/web/storagenode/src/app/components/ChecksArea.vue#L56 This matches with the `us-central-1` satellite, where it has an audit score of 97.01 on the `All Satellites` view, and an audit score of 97.0 on the single satellite view.

With that said, I don't have a Vue.js environment currently setup to easy test/debug this.  There is a chance that the two views reference different values/locations (I'm still trying to run through the code to locate where the original value for each view is pulled from).

Potentially a separate request, but it would be nice to add the online score to the single satellite view as well.

**Comment by stefanbenten** [comment]
Hello @Doom4535 !
Would you kindly open a PR with your proposed fix?
Then we can get this sorted out!

**Comment by Doom4535** [comment]
@stefanbenten Sure, I'll open a request for what I posted.
