### ISSUE TITLE
panic in uplink share command

### ISSUE THREAD

**Issue by AlexFihman** [storj/storj#3979]
OS: Ubuntu 20.04 LTS, on WSL, official installation of uplink and libraries

uplink version
Release build
Version: v1.17.4
Build timestamp: 20 Nov 20 03:25 IST
Git commit: f37a5bc6630ac66a507a058ac09b6400cbd611f5

running following command:

uplink share sj://data

Receiving this error:
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa3dd66]

goroutine 1 [running]:
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00028f9c0)
/go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.7/ctx.go:147 +0x3bb
panic(0xbc8c20, 0x1172ca0)
/usr/local/go/src/runtime/panic.go:975 +0x47a
storj.io/monkit-jaeger.(*UDPCollector).Stop(0xc000254000)
/go/pkg/mod/storj.io/monkit-jaeger@v0.0.0-20200518165323-80778fc3f91b/udp.go:181 +0x26
storj.io/private/process.cleanup.func1.3(0xc000254000, 0xc000212280, 0xc000211620, 0xc000345800, 0xc00028f9d0)
/go/pkg/mod/storj.io/private@v0.0.0-20201026143115-bc926bfa3bca/process/exec_conf.go:317 +0x45
storj.io/private/process.cleanup.func1(0xc0002eeb00, 0xc00028f9b0, 0x1, 0x1, 0x0, 0x0)
/go/pkg/mod/storj.io/private@v0.0.0-20201026143115-bc926bfa3bca/process/exec_conf.go:403 +0x1ac0
github.com/spf13/cobra.(*Command).execute(0xc0002eeb00, 0xc00028f980, 0x1, 0x1, 0xc0002eeb00, 0xc00028f980)
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x117dbc0, 0xc000138101, 0xcde5c0, 0x1)
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
storj.io/private/process.ExecWithCustomConfig(0x117dbc0, 0xffffff01, 0xcde5c0)
/go/pkg/mod/storj.io/private@v0.0.0-20201026143115-bc926bfa3bca/process/exec_conf.go:88 +0x178
main.main()
/go/src/storj.io/storj/cmd/uplink/main.go:16 +0x3e

**Comment by storj-antonio** [comment]
![uplink_version](https://user-images.githubusercontent.com/82116084/148114827-b8f28683-2a56-497b-ab26-816cfcf4c085.png)
![WSL_UbuntuVersionInfo](https://user-images.githubusercontent.com/82116084/148114828-e9974829-0827-4693-b679-d80b45b86ab6.png)

I was unable to reproduce this issue using Ubuntu 20.04 lts running under WSL 2. Attached you will find the version information as well as the commit I tested against.
