### ISSUE TITLE
Not installing  per steps.

### ISSUE THREAD

**Issue by mocallins** [storj/storj#4000]

**Comment by mocallins** [comment]
"""
root@truenas[~]#
root@truenas[~]#
root@truenas[~]# curl -L https://github.com/storj/storj/releases/latest/download/identity_linux_amd64.zip -o identity_linux_amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   147  100   147    0     0    597      0 --:--:-- --:--:-- --:--:--   597
100   650  100   650    0     0   1543      0 --:--:-- --:--:-- --:--:--  1543
100 9281k  100 9281k    0     0  3518k      0  0:00:02  0:00:02 --:--:-- 5879k
root@truenas[~]# unzip -o identity_linux_amd64.zip
root@truenas[~]# chmod +x identity
root@truenas[~]# mv identity /usr/local/bin/identity
root@truenas[~]# identity create storagenode
ELF binary type "0" not known.
zsh: exec format error: identity
root@truenas[~]#
"""

**Comment by mocallins** [comment]
Uuuugghhh,  How to get the code to post, readable ?

**Comment by mocallins** [comment]
'''
root@truenas[~]#
root@truenas[~]# uname -a
FreeBSD truenas.local 12.2-RELEASE-p2 FreeBSD 12.2-RELEASE-p2 663e6b09467(HEAD)TRUENAS  amd64
root@truenas[~]#
'''

**Comment by egonelbre** [comment]
Did you try the instructions in README? https://github.com/storj/storj#download-and-compile-storj

**Comment by mocallins** [comment]
Holy crap. this  isn't ready to go ?

Looks like the README wants me to compile and test the whole thing ?  NOT !

**Comment by egonelbre** [comment]
@mocallins I assume you already tried the freebsd_amd64 binaries from https://github.com/storj/storj/releases/tag/v1.18.1, hence why suggested compiling from scratch.

**Comment by stefanbenten** [comment]
The issue is a freebsd 11 and freebsd 12 binaries are different and do not work properly interchangable.

**Comment by mocallins** [comment]
Attaching to a NAS server i guess isn't recommended and I installed TrueNAS just for this purpose.
So I got it all runing without using TrueNAS and just a large additional disk, in the vm.
