### ISSUE TITLE
Storj simualtor failing on storj-sim network run

### ISSUE THREAD

**Issue by aneyzberg** [storj/storj#4029]
When running the test network using the following tutorial - https://github.com/storj/storj/wiki/Test-network

When running `storj-sim network run` I get the following error 

```satellite-migration/0                     15:20:01.115 | DEBUG	process/exec_conf.go:394	Unrecoverable error	{"error": "Error creating new master database connection for satellitedb migration: satellitedb: failed opening database via DBX at \"postgres://postgres@localhost/teststorj?sslmode=disable&options=--search_path%3D%22satellite%2F0%22&application_name=satellite-migration\": satellitedb: failed to connect to `host=localhost user=postgres database=teststorj`: server error (FATAL: database \"teststorj\" does not exist (SQLSTATE 3D000))\n\tstorj.io/storj/satellite/satellitedb.open:131\n\tstorj.io/storj/satellite/satellitedb.Open:105\n\tmain.cmdMigrationRun:412\n\tstorj.io/private/process.cleanup.func1.4:363\n\tstorj.io/private/process.cleanup.func1:381\n\tgithub.com/spf13/cobra.(*Command).execute:842\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:950\n\tgithub.com/spf13/cobra.(*Command).Execute:887\n\tstorj.io/private/process.ExecWithCustomConfig:88\n\tstorj.io/private/process.ExecCustomDebug:70\n\tmain.main:710\n\truntime.main:204", "errorVerbose": "Error creating new master database connection for satellitedb migration: satellitedb: failed opening database via DBX at \"postgres://postgres@localhost/teststorj?sslmode=disable&options=--search_path%3D%22satellite%2F0%22&application_name=satellite-migration\": satellitedb: failed to connect to `host=localhost user=postgres database=teststorj`: server error (FATAL: database \"teststorj\" does not exist (SQLSTATE 3D000))\n\tstorj.io/storj/satellite/satellitedb.open:131\n\tstorj.io/storj/satellite/satellitedb.Open:105\n\tmain.cmdMigrationRun:412\n\tstorj.io/private/process.cleanup.func1.4:363\n\tstorj.io/private/process.cleanup.func1:381\n\tgithub.com/spf13/cobra.(*Command).execute:842\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:950\n\tgithub.com/spf13/cobra.(*Command).Execute:887\n\tstorj.io/private/process.ExecWithCustomConfig:88\n\tstorj.io/private/process.ExecCustomDebug:70\n\tmain.main:710\n\truntime.main:204\n\tmain.cmdMigrationRun:414\n\tstorj.io/private/process.cleanup.func1.4:363\n\tstorj.io/private/process.cleanup.func1:381\n\tgithub.com/spf13/cobra.(*Command).execute:842\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:950\n\tgithub.com/spf13/cobra.(*Command).Execute:887\n\tstorj.io/private/process.ExecWithCustomConfig:88\n\tstorj.io/private/process.ExecCustomDebug:70\n\tmain.main:710\n\truntime.main:204"}
Error: exit status 1```

I am running on Mac. Any insight you have I would really appreciate!

**Comment by VinozzZ** [comment]
Hi there, it looks like the database `teststorj` isn't created in your postgres instance. Maybe try to create the database before starting storj-sim?

**Comment by aneyzberg** [comment]
Hi there - Thank you for the quick response. I do in fact have the teststorj created in my postgres instance. I have tried to run this command both with postgres running locally and vi docker and I still get the same error. Any other insight you have would be helpful.

**Comment by AlexeyALeonov** [comment]
Please, try to check your postgres instance

```
$ psql -h localhost -U postgres
\l teststorj
```
Should return the database if it's exist
Also, could you specify - what the postgres you are running? The standalone one or a docker version?

**Comment by aneyzberg** [comment]
hey @AlexeyALeonov Thank you for the notes. There was a permissions issue with my postgres user. I was able to resolve the issue. Thank you for the help!
