### ISSUE TITLE
Manual update

### ISSUE THREAD

**Issue by GrannyCryptomaster** [storj/storj#4040]
I'm running storagenode GUI Windows version. It seems that the updater fails to update the storagenode. I want to update the files mannualy.
I found these files to download: "identity.exe", "uplink.exe", "storagenode.exe", "storagenode-updater.exe".
My node is running in "C:\Program Files\Storj\Storage Node\".
I stopped both services, node and updater.
I replaced: "storagenode.exe", "storagenode-updater.exe", "identity.exe". I couldn't find "uplink.exe". I restarted the PC.
1. Is this OK?
2. What files I need to download and where to put them? 
3. Are there any commands that I should run after? Or just restart the PC?

**Comment by stefanbenten** [comment]
Hello @GrannyCryptomaster !

Somehow your issue has been overseen. Are you still looking for information on this?
Normally, the updater shouldnt fail and it would be valuable to fetch the respective logs and attach them to this issue if it still doesnt work for you.

If you resolved the problem, please close the issue :+1:

**Comment by GrannyCryptomaster** [comment]
Yes, it worked mannualy and I see that autoupdate is working too, but it takes like 10-14 days, from the day of the release.

**Comment by stefanbenten** [comment]
@GrannyCryptomaster There is a rollout involved to make sure not all nodes update at the same time. It is following a cursor on https://version.storj.io
