### ISSUE TITLE
"Create Access Grant in CLI" docs missing

### ISSUE THREAD

**Issue by flokli** [storj/storj#4047]
I'm having some trouble creating the Access grant from the CLI.

I went to https://europe-west-1.tardigrade.io, created an access grant name, kept all permission checked, clicked "Continue in CLI".

I get shown a "Satellite Address" and "Token":

![image](https://user-images.githubusercontent.com/183879/108925490-faa27c00-763c-11eb-8df6-261255f80d9c.png)

The "Visit the Docs" button below only brings me to the document main page, not a specific subpage explaining how to do this from the CLI.

I found my way to https://documentation.tardigrade.io/getting-started/uploading-your-first-object/create-first-access-grant, and this paragraph:

> However, if you are still reluctant to enter your passphrase into our web application for end-to-end encryption purposes, that's completely understandable, and you should select "Continue in CLI" and follow these [instructions](https://documentation.tardigrade.io/getting-started/generate-access-grants-and-tokens/generate-a-token).

That link however seems to show an outdated flow - the screenshots there only show a "Token", no "Satellite Address".

Maybe those could be updated, and the "Visit the docs" link directly link to it.

**Comment by profclems** [comment]
AFAIK, the docs have been updated
