### ISSUE TITLE
multinode - nodes' names

### ISSUE THREAD

**Issue by TheGoblinHero** [storj/storj#4059]
I've installed techical preview of the multinode binary. And I have an suggestion:
We need an ability to name the nodes. Node ID is not convenient. I'd like to name my nodes like "server 1, big disk", "remote nas"...

**Comment by nerdatwork** [comment]
It was posted back in October 2020 :)

https://forum.storj.io/t/add-storage-node-name-in-the-dashboard/9549

**Comment by ifraixedes** [comment]
Thanks, @nerdatwork for reporting it.

I close the issue because the right venue is our forum and the idea is already registered.
