### ISSUE TITLE
uplink: Access grant can't be imported 

### ISSUE THREAD

**Issue by hberg539** [storj/storj#4089]
Hello,

OS: Windows 10

Uplink version:
```
Release build
Version: v1.26.3
Build timestamp: 06 Apr 21 13:04 CEST
Git commit: a760b8bc4a0c66b1d721bfb0143663a8bc3e509f
```

Steps to reproduce:
1. Put access grant in text file
2. Run uplink.exe import <text file>

On the first run:
![grafik](https://user-images.githubusercontent.com/902223/115110464-e19eb300-9f7b-11eb-94e0-d94ba2ae39d0.png)
```
C:\Users\kk\Desktop>uplink.exe import access_grant.txt
Error: rename C:\Users\kk\AppData\Roaming\Storj\Uplink\config.yaml500922287 C:\Users\kk\AppData\Roaming\Storj\Uplink\config.yaml: Zugriff verweigert; close C:\Users\kk\AppData\Roaming\Storj\Uplink\config.yaml500922287: file already closed
```
config.yaml is empty:
![grafik](https://user-images.githubusercontent.com/902223/115110470-e6fbfd80-9f7b-11eb-8355-72d18d65c143.png)

On the second run, result is success:
![grafik](https://user-images.githubusercontent.com/902223/115110487-fd09be00-9f7b-11eb-9981-b79d599b3ae8.png)
```
C:\Users\kk\Desktop>uplink.exe import access_grant.txt
default access imported.
```

.. but the config.yaml doesn't have the access grant in it:
![grafik](https://user-images.githubusercontent.com/902223/115110503-0bf07080-9f7c-11eb-962e-cea0e8f18936.png)

Subsequent runs don't change anything.

**Comment by egonelbre** [comment]
This should get fixed with change https://github.com/storj/storj/commit/75ca01e3813498e932fcae3632b432d88c7243a1. Once it gets released, of course.

**Comment by ihaid** [comment]
fixed here https://github.com/storj/storj/releases/tag/v1.27.6
