### ISSUE TITLE
Confusing Access-Grant-Creation-flow

### ISSUE THREAD

**Issue by TopperDEL** [storj/storj#4093]
If I create a new Access Grant in the Satellite-Dashboard and "continue with CLI" it shows me a satellite-adress and a token.

The "uplink setup" command still wants an "API key" whereas the dashboard provides me a "Token". Technically it is the same and the token gets accepted as an API key - but the wording is confusing here. Either of them should be renamed to the other one.

**Comment by littleskunk** [comment]
Was fixed with the last release
