### ISSUE TITLE
Missing Windows Cli - Link is posted on Wiki, but fails?

### ISSUE THREAD

**Issue by shaneholloman** [storj/storj#4106]
**Lx, Mac and Pi links are all good here.**
<https://github.com/storj/storj/wiki/Uplink-CLI>
However the Windows Cli exe link reports "none"

- Link: <https://github.com/storj/storj/releases/latest/download/uplink_windows_amd64.exe.zip> Failing : (

**Comment by ifraixedes** [comment]
I've just fixed it.

@shaneholloman thanks for reporting it.
