### ISSUE TITLE
Idea: StorJ Relays and DS-Lite (IPv6)

### ISSUE THREAD

**Issue by victorelec14** [storj/storj#4164]
Hello, I leave an idea that I wrote in the StorJ forum.

https://forum.storj.io/t/idea-storj-relays-and-ds-lite-ipv6/14633

**Comment by stefanbenten** [comment]
Since you posted it in the right place already, i am closing it here. No need for double book keeping 👍 
Thank you very much for your help, thoughts and suggestions!
