### ISSUE TITLE
[multinode] Impossible to choose 'All time'

### ISSUE THREAD

**Issue by profclems** [storj/storj#4197]
1. Go to Payouts
2. Choose some month (Jan 2021 for ex.)
3. Choose 'All Time'

Actual result: impossible to choose All Time

See video attachment

https://user-images.githubusercontent.com/41906128/134155416-a44421b6-4b9d-4382-ac75-ce9aad1f5f3d.mp4

**Comment by ptdatta** [comment]
@profclems Please review this [PR](https://github.com/storj/storj/pull/7130)
