### ISSUE TITLE
Bug in the onboarding workflow for QA satellite

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4217]
**Contact Support hyperlink is linking to Node support instead of Storj DCS support.**
  
  ![image](https://user-images.githubusercontent.com/15882196/137344030-50086b42-423f-40a5-a388-9c2c728f5170.png)
  
  During sign up after entering credentials the last step is to confirm the verification email. In this page the ` Contact our support team` hyperlink links to Node Support instead of Storj DCS support @ https://supportdcs.storj.io/hc/en-us

**Comment by littleskunk** [comment]
Fix incoming: https://review.dev.storj.io/c/storj/storj/+/6001
