### ISSUE TITLE
Tooltip hides behind textbox

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4218]
When the focus is in the textbox to enter the passphrase if user hovers over the tooltip icon then the tooltip hides behind the textbox.  If it is shown above the tooltip icon rather than below then it would look much more clean.

![image](https://user-images.githubusercontent.com/15882196/137358866-76f7dc7e-45be-4739-a42b-98010edab362.png)

**Comment by VitaliiShpital** [comment]
Hello! We have a ticket to fix this. Thanks for reporting!
