### ISSUE TITLE
Typo in 2FA popup

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4219]
The word `get` is used twice

![image](https://user-images.githubusercontent.com/15882196/137381882-c5d1bd0a-9fe5-4e88-97ca-2d1c680d3aa5.png)

**Comment by profclems** [comment]
Thanks for reporting this issue @nerdatwork.

Do you mind opening a quick PR to fix this?

**Comment by nerdatwork** [comment]
I will make a PR soon :)
