### ISSUE TITLE
Hyperlink for "Command Line" solution

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4223]
Under `Encrypt your data` an option is presented to the user to opt for `command line` solution but no way to get to it. 

Adding a hyperlink to the *CLI* `https://<region>/onboarding-tour/cli/api-key` tour section will definitely be more user friendly.

![image](https://user-images.githubusercontent.com/15882196/137572827-91267cb9-026f-4f7e-8b6d-b68d8a667e34.png)

**Comment by VitaliiShpital** [comment]
Hello! Fix is on the way. Thank you for reporting this!

**Comment by iglesiasbrandon** [comment]
This issue is no longer relevant, closing it for now.
