### ISSUE TITLE
[Satellite UI] Onboarding process. The multiline code-blocks doesn't have a copy button

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#4231]
**Description**

When you restart the on-boarding wizard and select Continue in CLI, on the few screens with multiline code-blocks there is no "copy" button. The one-liner code-blocks have it.

**Screenshots**

![image](https://user-images.githubusercontent.com/26858949/138158508-9fe47602-e07a-495d-a986-81c599b14efc.png)
![image](https://user-images.githubusercontent.com/26858949/138158784-af496c32-df51-4ad4-b62f-2f29ad00c58f.png)

**Steps to reproduce the issue:**

1. Click the button with question mark - (?)
2. Select Continue in the CLI
3. Click next until screen with download commands
4. Switch to Linux or MacOS
5. The code block doesn't have a copy button
6. Click next until the one-line code blocks - they have a copy button

**Describe the results you expected:**

The copy button should be on multiline code-blocks

**Describe the results you received:**

We do not have a copy button in multi-line code-blocks

**Your environment**

- Operating system and version: Windows 10
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): Chrome browser

**Comment by VitaliiShpital** [comment]
Hey! We created a ticket to fix this. Thanks for reporting
