### ISSUE TITLE
Adding test CC doesn't give error message to the user

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4253]
**Steps to reproduce:**

1. After logging in, click `Upgrade Now` link/button at top right. 
2. In `Upgrade to Pro Account` pop up enter test credit card details.

![image](https://user-images.githubusercontent.com/15882196/139518033-c576b8f4-b896-4237-a53a-e41064dd96b8.png)

**Observed Result:**
Infinite loading and page being not responsive. Refreshing the webpage is the only way to fix it.

**Expected Result:** 
An error message should tell user about invalid CC or Test CC being used.

```
Request URL: https://api.stripe.com/v1/tokens
Request Method: POST
Status Code: 402 
{
  "error": {
    "code": "card_declined",
    "decline_code": "live_mode_test_card",
    "doc_url": "https://stripe.com/docs/error-codes/card-declined",
    "message": "Your card was declined. Your request was in live mode, but used a known test card.",
    "param": "",
    "type": "card_error"
  }
}

```

**Comment by mobyvb** [comment]
Tracked in JIRA for the User Growth team to fix

**Comment by NikolaiYurchenko** [comment]
fix merged

**Comment by mobyvb** [comment]
@nerdatwork can you check again? I believe the fix should be deployed as of this week.

**Comment by nerdatwork** [comment]
@mobyvb I just checked and I could successfully add test credit card. I even got "card successfully added" message.

**Comment by mobyvb** [comment]
Awesome, thanks! I will close this issue.
