### ISSUE TITLE
[Satellite UI] Have a warning when user creates an unrestricted access grant

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#4258]
Expected behavior:
Customer opens file browser and uploads a file and want to send a link to a friend. There should be no way for the customer to send unrestricted access grants that would expose all files.

Actual behavior:
Customers downloads a file them self and generates a share link. If they click download and copy the URL they get an unrestricted access grant without knowing the danger. This violates our core values. We want to be secure by default and even user errors shouldn't change that.

<img width="1193" alt="screenshot" src="https://user-images.githubusercontent.com/82845192/139841971-6e3e9f92-75b4-4d26-af39-9237f1018a2c.png">

Steps to Reproduce
1. On bucket download page, have browser console opened
2. Click download dropdown on object
3. Copy download link from said download action on browser console, and use that as share link

Possible solutions:
Generate restricted download links even if the customer downloads the file them self so that the user can copy any URL and would always share restricted access grants.
or
Add a big red warning any time they use an unrestricted access grant. For education that would be great but users might still find ways to share a link without reading the warning. First solution has the beauty that customers would always get restricted access grants by default and would have to ask how to generate unrestricted access grants.

Your environment

Operating system and version: mac Big Sur
Additional environment details (Raspberry PI, Docker, VMWare, etc.): Chrome browser

**Comment by mobyvb** [comment]
Tracked for the user growth team. 
Just my opinion, but I often want to generate an unrestricted access grant for personal uplink use - I wouldn't want to remove this functionality. But I definitely agree that a prominent warning would be useful.
