### ISSUE TITLE
uplinkng: port command to RegisterAccess in gateway

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4263]

**Comment by mjpitz** [comment]
@mniewrzal I'm happy to hop on this

**Comment by mniewrzal** [comment]
@mjpitz that would be great! One important thing is that we are moving this command from using HTTP endpoint to DRPC endpoint https://review.dev.storj.io/c/storj/storj/+/5530. Changes are still not merged because we are waiting for the last infrastructure changes to fully support it but that should be done next few days. Uplinkng change should follow this new approach from @Erikvv change. Just assign it to yourself when you will be ready to start.

**Comment by mjpitz** [comment]
Review is here: https://review.dev.storj.io/c/storj/storj/+/6487

I merged this change in the meantime. @mniewrzal we can update that PR off main while we wait for the last of the infra changes to roll out. I'm happy to give that change a review in the meantime... looks like we just need certificates added as part of the flags?
