### ISSUE TITLE
Flaky UI stage

### ISSUE THREAD

**Issue by egonelbre** [storj/storj#4269]
This could be due to the coordination problems between the vue and test code.

* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/16997/pipeline/340/
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/17006/pipeline/340/

**Comment by mniewrzal** [comment]
recent fail https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/17913/pipeline

**Comment by mobyvb** [comment]
Some more
Failure during UI stage ("panic: timeout for starting browser exceeded")
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18112/pipeline

No failure, but timeout during UI stage:
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18118/pipeline
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18115/pipeline
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18117/pipeline
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18109/pipeline
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18084/pipeline
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18083/pipeline
* https://build.dev.storj.io/blue/organizations/jenkins/storj-gerrit/detail/storj-gerrit/18104/pipeline

Here are the changes for the above builds:
* https://review.dev.storj.io/c/storj/storj/+/6600
* https://review.dev.storj.io/c/storj/storj/+/6420
* https://review.dev.storj.io/c/storj/storj/+/6610
* https://review.dev.storj.io/c/storj/storj/+/6362
* https://review.dev.storj.io/c/storj/storj/+/6152

**Comment by mobyvb** [comment]
By the way, for the above changes, I wouldn't even consider the behavior "flaky". It seems that any change which affects the console or web/satellite package is almost guaranteed to fail build due to timeout (over the past few weeks). This happens often even for very small changes that shouldn't affect the outcome of tests.

**Comment by egonelbre** [comment]
The summary so far: Jenkins is failing to start chromium. Why -- we have no good ideas. It seems to be the same reason why the last "check-clean-directory" stalls out.

There are few guesses, why jenkins fails, but we haven't been able to pin it down:
1. there's a resource exhaustion in docker (e.g. out of ports or similar)
2. there's a bug in jenkins with regards to waiting for completion (e.g. it doesn't start the next stage, because there's still something running in the background)
3. there's disk issues (e.g. the host throttles the docker container or jenkins node, which makes thing fail)

Ephemeral builds could potentially fix it... but if it's the first or third point, then it might hide it for some time and it comes back. If it's second, then it potentially will fix it.

We potentially could also start it in a separate Jenkins job... but I've been able to repro similar issues with only the UI job.

We could try to use github actions to potentially fix these as well... but might hit some other issues along the way.

**Comment by egonelbre** [comment]
We've decided to use playwright -- hopefully, it will give a better experience. https://review.dev.storj.io/c/storj/storj/+/12015
