### ISSUE TITLE
SNO: mobile web view of the dashboard / minor css issues

### ISSUE THREAD

**Issue by bjoerrrn** [storj/storj#4272]
On the iPhone Safari, the payout sub-page of the node dashboard has difficulties showing correctly the boxes within the section "balance": the dollar values are shown outside the boxes here. 

I've never seen this correctly, so it is an issue with older node software versions as well. 

version 1.42.4
iOS version: 15.1
iPhone 13 mini

![IMG_9830](https://user-images.githubusercontent.com/91031217/141699845-6ccfe2cc-a3b3-4916-bb64-ecc543230ee7.jpg)

**Comment by profclems** [comment]
Hi @dusselmann, thanks for opening this issue. This will be fixed asap, but it is open in case you or anyone would like to submit a quick PR to fix this

**Comment by dusselmann** [comment]
It is working, when you add something like 

```
@media screen and (max-width: 640px)
    .info-container {  
       width: 100%!important; 
       margin-bottom: 20px;
}
```

**Comment by iglesiasbrandon** [comment]
Hey @bjoerrrn, this issue is also related. https://github.com/storj/storj/issues/3691 we closed this one because the dashboard is responsive. We are closing this issue for now; please let us know if you see any other issues with responsiveness.
