### ISSUE TITLE
No navigation section while creating project

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4284]
![image](https://user-images.githubusercontent.com/15882196/142475356-5419ec4f-adb2-4a0a-b23f-d8cda9983b9d.png)

This should either be a pop up or must have navigation panel like other pages.

**Comment by mobyvb** [comment]
Thank you. Tracked in the customer growth team's backlog.

**Comment by NiaStorj** [comment]
@cam-a needs story points

**Comment by NiaStorj** [comment]
linked to https://github.com/storj/storj/issues/4372 and this ticket was completed under it. closing for that reason
