### ISSUE TITLE
[website] The padding is not equal for some pieces of the page on mobile devices

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#4287]
**Description**

If you open page on mobile device, the vertical blue lines not matches for some parts. See screenshot for explanation.

**Screenshots**

![image](https://user-images.githubusercontent.com/26858949/142718310-e703c2ac-9697-47d3-b32a-2ff4d9637a8b.png)

**Steps to reproduce the issue:**

1. Open https://storj.io on mobile device (screen 678 x 2048)
2. Slide up the page

**Describe the results you expected:**

Vertical lines aligned

**Describe the results you received:**

Vertical lines are not matches

**Possible Fix**

Add more padding?

**Additional information you deem important (e.g. issue happens only occasionally):**

The ticket was created based on Twitter request.

**Your environment**

- Operating system and version: n/a
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): Screen resolution 678 x 2048

**Comment by mobyvb** [comment]
@AlexeyALeonov I cannot find this section on the storj website. I looked on storj.io and on storj.io/cost-analysis
If you can direct me to a specific page, I can change it.

**Comment by nerdatwork** [comment]
@mobyvb 

![image](https://user-images.githubusercontent.com/15882196/143182942-e5cc46e0-d5bb-4f1e-aa6d-3eb9f5756825.png)

**Comment by mobyvb** [comment]
Thank you @nerdatwork. I didn't check storj.io/pricing

**Comment by iglesiasbrandon** [comment]
This issue does not seem to be relevant anymore. The current pricing page is very different.
