### ISSUE TITLE
No visible difference between Standard and Pro accounts

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4290]
Visually there is no difference between `Standard` (non pro) and `Pro` accounts besides the banner at the top disappearing from Pro account. 

Some suggestions to showcase Pro account.

1. 
![image](https://user-images.githubusercontent.com/15882196/142879512-f31c556c-7d5c-4cb1-b892-4a4c4cb51bb0.png)

2. 
![image](https://user-images.githubusercontent.com/15882196/142879541-6a510221-a4bf-4700-a58c-8ef396a27ab5.png)

3.
![image](https://user-images.githubusercontent.com/15882196/142879582-27b8e318-e5c8-4a64-96ea-42ea2cbe765c.png)

A ribbon placed at the top right of the page at an angle or shown in the center of all pages.

**Comment by mobyvb** [comment]
I have added a new label to this issue, "Design/Marketing Suggestion". These types of design and marketing decisions are outside of the scope of the customer growth developer team.
