### ISSUE TITLE
Update Storj's website URL under CoinPayments

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4294]
The website details in CoinPayments hasn't been updated to `Storj.io`. It still shows `tardigrade.io`.  Even though it redirects to `Storj.io`, new users who are unaware of the rebranding will be thrown off guard.

![image](https://user-images.githubusercontent.com/15882196/143768878-2053f394-58df-4901-be65-5e3f16ecabc5.png)

Feedback page on Coinpayments.

![image](https://user-images.githubusercontent.com/15882196/143768914-17edf1e9-5dcd-405a-8ba0-88dc32d08602.png)

**Comment by iglesiasbrandon** [comment]
coinpayments.net is no longer used, so I am closing this issue.
