### ISSUE TITLE
Release vs Development version when building

### ISSUE THREAD

**Issue by stefanofornari** [storj/storj#4303]
Following up the forum discussion https://forum.storj.io/t/is-anybody-having-issues-with-v1-41-and-1-42/16128, I would suggest the following change in release.sh script:

```
diff release.sh release.new.sh 
11a12
>   echo "Changes detected, building a development version"
14a16
>   echo "Building a release version"
```

**Comment by littleskunk** [comment]
Yes please make that code change and open a pull request.

**Comment by stefanofornari** [comment]
done. it seems there is an error: The contributors @stefanofornari have not signed the CLA, let me know if I have do do anything

**Comment by littleskunk** [comment]
Thank you for your contribution.
