### ISSUE TITLE
Error executing `GetBucketVersioning` with Self-hosted S3 Compatible Gateway

### ISSUE THREAD

**Issue by victorgsfigueiredo** [storj/storj#4323]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

I am running an application (Nextcloud) that requires an API call to `localhost:7777/bucket-name?versioning`. This is a native API from Amazon S3 (https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketVersioning.html) which is not available on the Storj gateway, which can cause problems to implement it with S3-compatible plugins from several places.

**Steps to reproduce the issue:**

1. Install S3-compatible gateway according to the [documentation](https://docs.storj.io/dcs/downloads/download-self-hosted-s3-compatible-gateway) to a fresh Ubuntu 20.04 LTS server.
2. Run gateway as a daemon with `gateway run` after following all steps on documentation (authentication, configuration, etc.)
3. Perform an authenticated API call to `localhost:7777/bucket-name?versioning`.

**Describe the results you expected:**

The same on the Amazon S3 documentation. One example from AWS docs below:
```
         GET /?versioning HTTP/1.1
         Host: myBucket.s3.<Region>.amazonaws.com
         Date: Wed, 12 Oct 2009 17:50:00 GMT
         Authorization: authorization string
         Content-Type: text/plain
```

**Describe the results you received:**
```
AWS HTTP error: Server error: `GET http://127.0.0.1:7777/nextcloud1?versioning` resulted in a `501 Not Implemented` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NotImplemented</Code><Message>A header you provided implies function (truncated...) NotImplemented (server): A header you provided implies functionality that is not implemented - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>NotImplemented</Code><Message>A header you provided implies functionality that is not implemented</Message><BucketName>nextcloud1</BucketName><Resource>/nextcloud1</Resource><RequestId>16C4F3DE44B08B0D</RequestId><HostId>18a5133a-f8cb-4687-a8af-05f7402fa59f</HostId></Error>
```

**Possible Fix**
Implement the `GetBucketVersioning` on Self-hosted S3-compatible API.

**Logs:**

```
All important logs above.
```

**Your environment**

- Operating system and version: Ubuntu 20.04 LTS
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): none.

**Comment by stefanbenten** [comment]
@victorgsfigueiredo I am not sure if you are aware, but for nextcloud we have a native app that does not require the Gateway, which you can find here: https://apps.nextcloud.com/apps/storj

Aside that, you should reopen this issue in https://github.com/storj/gateway-st , since that is the binary you are using 👍

**Comment by nunesgh** [comment]
Hi @stefanbenten!

Is there a repository for the native Nextcloud app?

I have just installed it and enabled the PHP FFI extension, but the app is now flooding my logs with the following error:
`[PHP] Error: Module 'FFI' already loaded at Unknown#0`

Thank you for your attention!

**Comment by nunesgh** [comment]
Just found it: https://github.com/storj-thirdparty/nextcloud-app

**Comment by Erikvv** [comment]
I've changed this in Nextcloud https://github.com/nextcloud/server/pull/31498
But I do recommend the native app.

**Comment by nunesgh** [comment]
Awesome! Thank you, @Erikvv!
