### ISSUE TITLE
native token payments design doc

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4336]
Consolidate design notes around native token payments/storjscan into confluence page.

**Comment by shaupt131** [comment]
Acceptance Criteria: Create an **outline** containing the rationale and implementation steps of native token payment, then assign different sections to different people based on their area of expertise (with follow-up tickets). Outline will include sections that HAVE already been implemented, as well as sections that are in progress or upcoming.

**Comment by jenlij** [comment]
https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2310733825/Native+Token+Payments+Design
