### ISSUE TITLE
Buckets not visible on QA satellite

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#4338]
![image](https://user-images.githubusercontent.com/15882196/148509727-687fb0a0-c5a5-4dd4-acf4-966c0ea9ec9b.png)

**Comment by stefanbenten** [comment]
@nerdatwork Could you kindly try again?
There was some ongoing redeployments that caused downtime unexpectedly.

**Comment by nerdatwork** [comment]
I think there is a problem. The link opens and page correctly displays the size.  The downloaded file is of ZERO size when actual size is 200KB.
