### ISSUE TITLE
Remove redundant suspension column from nodes and reputations

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4344]

**Comment by jenlij** [comment]
https://review.dev.storj.io/c/storj/storj/+/6158

**Comment by rikysya** [comment]
merged change with column removal
https://review.dev.storj.io/c/storj/storj/+/6158 

backwards compatibility fix
https://review.dev.storj.io/c/storj/storj/+/7089

This needs another change with migration in the next release after release with those two changes above.

**Comment by jenlij** [comment]
@rikysya these both have been released. What is left?

**Comment by rikysya** [comment]
That means I can proceed with last change adding the migration
