### ISSUE TITLE
add Storjscan claim system - ability to add and sum claims per Storjscan wallet

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4348]
This is on the satellite side.

**Comment by shaupt131** [comment]
https://review.dev.storj.io/c/storj/storj/+/7453
https://review.dev.storj.io/c/storj/storj/+/7490
https://review.dev.storj.io/c/storj/storj/+/7488

**Comment by shaupt131** [comment]
Redundant ticket https://github.com/storj/storj/issues/4349 closed.  Not all captured under this ticket.

**Comment by iglesiasbrandon** [comment]
The most relevant PR is https://review.dev.storj.io/c/storj/storj/+/7374

**Comment by shaupt131** [comment]
Retro notes: Very similar to https://github.com/storj/storj/issues/4347 notes.  Lots of design decisions to be made before any implementation could occur.
