### ISSUE TITLE
Add line item with unclaimed Storjscan wallet balance during invoice generation.

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4350]
Also need to update claims database.

**Comment by jenlij** [comment]
WIP: Adding the storjscan payment line items to the stripe invoice. It needs work, like adding unit tests, and updating the DB migrations in the relation chain, but it has the main logic for how to actually do the update.
https://review.dev.storj.io/c/storj/storj/+/7496
It would also be nice if it didn't live in the stripecoinpayments package.

**Comment by shaupt131** [comment]
- Priority 1: Refactor Billing DB - https://review.dev.storj.io/c/storj/storj/+/7787 
   - @jenlij approved
   - @rikysya assigned to review.


- Priority 2: storjscan invoice generation - https://review.dev.storj.io/c/storj/storj/+/7496 
   - dependant on 7787
   - @thepaul approved
   - @rikysya assigned to review.


- Priority 3: add billing update to chore - https://review.dev.storj.io/c/storj/storj/+/7790 
   - dependant on 7787
   - @jenlij and @rikysya assigned to review.
