### ISSUE TITLE
Create a new RepairControl process

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4353]
Create a new satellite process similar to the API process. Add a DRPC service exposing GetRepairWork and SubmitRepairWork interfaces. Add a config item controlling whether satellites still perform their own repair. (Satellites with this process will continue to do their own repair until external repair workers are deployed and tested and ready to take over.)

**Comment by iglesiasbrandon** [comment]
closing this ticket until we begin work on this item: https://github.com/storj/roadmap/issues/48
