### ISSUE TITLE
Fix audit reputation calculation

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4354]
https://forum.storj.io/t/tuning-audit-scoring/14084

**Comment by shaupt131** [comment]
Related ticket: https://github.com/storj/storj/issues/4567

**Comment by thepaul** [comment]
@jggleeson! (Moving over a question from a thread in #team-data that might not have been seen):

Can you tell me what rate of data loss our model can tolerate from the storage nodes? I mean on an ongoing basis, not with respect to the Russia situation.

If possible, I would also like to know how long we can tolerate “bad” nodes being online, preferably as a function of the rate of data loss. For example, if a node has 1% higher data loss than our limit, and it takes us two months to determine that, is that ok? What if the node has 3% higher data loss than our limit, etc.

This will determine how fast reputation scores will go down or up when audits pass or fail.

**Comment by jggleeson** [comment]
Right now, the most important thing is durability. We can address the unit economics later. We should optimize for durability, so having more repair but no risk to durability is the right approach. If part of the math of segment heath is related to the quality of the node storing pieces, in the near term, I would calculate based on the assumptions that pieces on suspected bad nodes are missing.

If we can measure the frequency with which suspected bad nodes recover and become good nodes vs. ultimately getting DQ'd that might also have an impact on what the decision matrix is for repair.

Maybe we can look at the last 6 months of DQ data and the last 6 months of nodes that recovered from a bad stretch of reputation events and see if there is a pattern.

**Comment by shaupt131** [comment]
Moving back to in-progress status.  @thepaul please let us know if you need more info to proceed.

**Comment by thepaul** [comment]
Consensus achieved on the forum that we'll implement this ticket according to this post: https://forum.storj.io/t/tuning-audit-scoring/14084/72 .

**Comment by jenlij** [comment]
Large story point ticket because of the long discussion in the forum and all the follow up that was needed.
