### ISSUE TITLE
convert coinpayments transaction value from a gob encoded float to ints

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4355]
if you do select * from coinpayments_transactions limit 10; on redash for any satellite db, the amount column is a gob encoded big.Float. 

strictly using integer cents for dollars and big.Int for cryptocurrencies. cryptocurrencies always have a smallest denomination. for STORJ, it's 1/100,000,000th of a STORJ token. you can't go smaller, so, our tracking and bookkeeping should be in integer terms of 1/100,000,000th of a STORJ. if this is hard, at least decimal.Decimal would be better.

evaluate eliminating floats everywhere for cryptocurrency values

1. Figure out how to decode the amount and convert the amount into the desired units

2 .migrate old data to new units (add column, drop old)

3. Make sure to read and write to the new column appropriately

4. Find other places where we need to convert units

https://review.dev.storj.io/c/storj/storj/+/6153
https://review.dev.storj.io/c/storj/storj/+/6311

Final Steps: 

- [ ] #4689

**Comment by jenlij** [comment]
6311 still needs to be deployed

**Comment by jenlij** [comment]
waiting for next release

**Comment by thepaul** [comment]
Finally, all gob-encoded values on all satellites (that I know about) are cleared out. Starting the final phase (removing the extra code and columns) now.

**Comment by iglesiasbrandon** [comment]
closing this issue, @thepaul we will track the final phase of this in a separate ticket #4689
