### ISSUE TITLE
Get caching to work in object browser

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4362]
This task is dependent on https://review.dev.storj.io/c/storj/gateway-mt/+/6608 being merged, but we can (and should) start work before that

AC: 

use the aws-sdk library to create a signed URL https://github.com/aws/aws-sdk-js-v3/blob/b0e1422630/packages/signature-v4/src/SignatureV4.ts#L165 , and use this to get the object map and preview from linksharing, rather than a public access

Relates to  https://storjlabs.atlassian.net/browse/FIRE-133

The only part that is different is Credential

**Comment by VitaliiShpital** [comment]
https://review.dev.storj.io/c/storj/storj/+/6731
