### ISSUE TITLE
Update tables in the satellite GUI with new table component design

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4367]
When using storj DCS I want all of the tabes to be consistent in the satellite GUI so that the user has a better experience.

Figma:  https://www.figma.com/file/b3QhctHccKl3ihR8Q063Af/DCS-Design-Library?node-id=102%3A735

Acceptance Criteria:

- [x] Common table component
- [x] Buckets table

for another ticket:

- projects table
- project members table
- access grants table (new flow, since we will get rid of the old one)
- file browser table

**Comment by mobyvb** [comment]
deployed in v1.58
https://github.com/storj/storj/commit/b4e486f3fc183e037e986db51ff125f717b06a52
