### ISSUE TITLE
The DCS signup page logo at the top of the screen does not redirect the user to storj.io homepage

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4369]
The DCS signup page logo at the top of the screen does not redirect the user to storj.io homepage

Specifically, the DCS logo on the signup and login pages, not the logo when you are logged in already

Do not update the URL for the logo once the user is already logged in.

**Comment by cam-a** [comment]
https://review.dev.storj.io/c/storj/storj/+/7352
