### ISSUE TITLE
Change "create a project" page to a modal you can close out of

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4372]
dupe: https://github.com/storj/storj/issues/4284

Figma fixes: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=8504%3A18817

AC: add close button to create a project page

**Comment by mobyvb** [comment]
We should implement https://github.com/storj/storj/issues/4785 first, then use the new common modal to do this change

**Comment by liviolanda** [comment]
it's a modal, but fullscreen, with a close button. @VitaliiShpital 
I can make it more like a modal too, so we use the component you're creating. We're not using fullscreen modal any place else. It's prettier full screen, but I understand it's better to use the components we already have, and they work very well.

if we could have full-screen AND popup modals would be awesome. could we?
