### ISSUE TITLE
Write design doc on how to send data to stripe for metered billing

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4408]
[DRAFT Design Doc Metered Billing Service](https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2175270913/DRAFT+Design+Doc+Metered+billing+service)

We need a service to push usage data from the satellite accounting system to stripe

What data are we sending specifically?

Describe where and how the service will run 

event-driven (which event?)

idempotent key to prevent double-spending

non-core service like repair workers

This should allow a generic subscriber to get usage info (in our case it will be stripe, but this service will be able to send to other data collection services)

other option: cron job to send data to stripe on a regular interval

[Formerly DUR-133](https://storjlabs.atlassian.net/browse/DUR-133?atlOrigin=eyJpIjoiMGU4Y2IxMThjMGVhNDBmZGI1YzFiZTZlOWQxNDA1YjYiLCJwIjoiaiJ9)

**Comment by iglesiasbrandon** [comment]
Not going to implement it at this time, closing this ticket.
