### ISSUE TITLE
Write design doc to implement stripe subscription model

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4409]
- [DRAFT Design Doc Stripe Subscription Model](https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2175139841/DRAFT+Design+Doc+Stripe+Subscription+Model)

- This design doc needs to take into account the product requirements listed in 

- [Metered Billing](https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2165735425/Metered+Billing)

- Include details on how to migrate existing customers to new subscription model

[Formerly DUR-132](https://storjlabs.atlassian.net/browse/DUR-132?atlOrigin=eyJpIjoiMTAwMjUwMTc0OWM1NDc2YzhiZGU5ODJjY2I4YWVkNzYiLCJwIjoiaiJ9)

**Comment by iglesiasbrandon** [comment]
Not going to implement it at this time, closing this ticket.
