### ISSUE TITLE
Investigate and improve performance of uTP

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4413]
[Formerly DUR-54](https://storjlabs.atlassian.net/browse/DUR-54?atlOrigin=eyJpIjoiZjU0MmEyM2ZiMTU3NGQwNWFiZGNjODdkZWZkNmVlZWEiLCJwIjoiaiJ9)

**Comment by ifraixedes** [comment]
The former ticket was canceled, is it still valid?

**Comment by shaupt131** [comment]
DUR-54 was cancelled in Jira only after it was migrated to Github.  It should still be valid.

**Comment by iglesiasbrandon** [comment]
closing this ticket until we have something more concrete to investigate.

**Comment by Erikvv** [comment]
So this was about μTP (https://en.wikipedia.org/wiki/Micro_Transport_Protocol). I'm not sure where we use this.

**Comment by thepaul** [comment]
We don't use it at all currently. There is some idea that µTP would be faster or lower latency than QUIC in some network configurations, and that it would help us solve NAT traversal more easily. We made a golang port of libutp at https://github.com/storj/utp-go.
