### ISSUE TITLE
Stage 3: Select Satellites and Nodes Speak QUIC

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4414]
https://storjlabs.atlassian.net/wiki/spaces/TD/pages/1353810034/QUIC+Test+Plan

**Setup:**

Arrange a storj network where satellites and nodes are separate hosts, at least somewhat distributed on the public internet. (Possibly this is the actual Storj network.)

At least two nodes and maybe a satellite on the network should have QUIC code and listen for QUIC connections (to involve a satellite, this may involve figuring out load balancing difficulties) and use the hybrid connector. If any of these are running on Linux, ensure that the sysctl net.core.rmem_max is set to at least 2500000.

Put one of the QUIC-enabled nodes behind a home router performing NAT, configured to forward the appropriate UDP port (and TCP port) to the node.

Custom-build a libuplink that uses the hybrid connector

Stand up a retrievability-checker instance using this custom libuplink

Build rclone with this custom libuplink as well

**Requirement: QUIC does not take significantly more bandwidth when used on a good network connection**

Measure the average bandwidth used over some period of time on the retrievability-checker, while it only makes TCP+TLS connections

Measure the average bandwidth used over the same time period on the retrievability-checker, while QUIC support is enabled

Perform an rclone operation copying some large number of objects to a storj bucket (with QUIC disabled, or with QUIC support not built in). Measure the overall bandwidth used and the bandwidth from the rclone host to the QUIC-enabled satellite and some specific QUIC-enabled nodes. Ensure that at least some pieces get sent to the QUIC-enabled nodes. (A directory with over 100,000 files in it of size 8kB+, should suffice.)

Perform another rclone operation copying the same large number of objects into a different bucket, with QUIC enabled. Again measure the overall bandwidth used and the bandwidth from the rclone host to the QUIC-enabled satellite and the specific QUIC-enabled nodes.

Compare bandwidth usage from the previous steps. Bandwidth-with-QUIC is expected to be within 50% of bandwidth-with-TCP+TLS. Bandwidth to specific QUIC-enabled nodes might differ by more than this if there are only a small number of pieces sent there.

Ensure retrievability-checker and rclone work correctly with QUIC enabled; no surprising errors

Before and after each step of this test, get a copy of /proc/net/dev from each QUIC-enabled host. (Or find the equivalent data, if a host is running something other than Linux.)

Check how many packet drops happen on each side of the connection when QUIC is being used. The number of dropped packets should be low compared to the overall number of packets received during some interval. Say, below 10%. If the number of dropped packets is higher than that, we may have a problem that needs to be resolved before we move forward with QUIC.

**Requirement: QUIC can be forwarded correctly through an average NAT-performing home router**

Ensure the node(s) behind NAT successfully participated in the above test operations.

[Formerly DUR-16](https://storjlabs.atlassian.net/browse/DUR-16)

**Comment by iglesiasbrandon** [comment]
this work has already been completed.
