### ISSUE TITLE
Stage 4: All satellites and many nodes speak QUIC

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4418]
**Setup:**

- Wait until QUIC-listening code has been pushed to all Storj satellites and most storage nodes, and at least 20% of nodes are actually accepting QUIC connections. (Get a list of which nodes have support for it, as determined by their registered software version numbers, and try connecting to each one in turn over QUIC, to see whether it’s working.)

**Requirement: QUIC doesn’t cause any widespread difficulties for SNOs or users**

- Watch hybrid_connector_established_*_connection events on satellites, to see how many outgoing connections of each type they make

- Watch error rates from functions implementing common API calls, to ensure they keep functioning as normal as nodes and satellites begin to use QUIC connections

- Try another QUIC-enabled rclone large-directory-copy operation, as above, monitoring overall bandwidth usage categorized by TCP and UDP. Compare bandwidth usage to the collected data from stage 3.

https://storjlabs.atlassian.net/wiki/spaces/TD/pages/1353810034/QUIC+Test+Plan

[Formerly DUR-38](https://storjlabs.atlassian.net/browse/DUR-38)

**Comment by iglesiasbrandon** [comment]
this work has already been completed.
