### ISSUE TITLE
influx updates for multiple rs schema

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4422]
And remove the non rs tagged monkit metrics from repair checker

[Formerly DUR-79](https://storjlabs.atlassian.net/browse/DUR-79)

**Comment by shaupt131** [comment]
**Jennifer Johnson 
April 28, 2021, 1:12 PM**

waiting for metainfo metrics changes


**Jennifer Johnson 
March 17, 2021, 1:29 PM**

do something with “repair unnecessary” metric

**Comment by iglesiasbrandon** [comment]
This issue is no longer relevant, closing this issue.
