### ISSUE TITLE
RS testing

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4424]
**Satellite 1: SaltLake**

Original RS Scheme: 29/52/80/110

Trial RS Scheme: 16/23/37/50

Start Date: 2/8/21

- [ ] Get the past 30 days of data for the original RS Scheme from the Retrievability Checker
- [ ] Satellite deployed with new RS scheme
- [ ] Periodically get data from RC and compare against previous RS scheme’s data
- [ ] Upload objects to the network
- [ ] Periodically check the time to repair, total number of segments by schema, number of injured segments per iteration, segment health percentiles
- [ ] Compare against statistical durability models
- [ ] If performance from Retrievability checker is good, test performance with larger objects.
- [ ] Evaluate the "time to repair" for older schema

[Formerly DUR-59](https://storjlabs.atlassian.net/browse/DUR-59)

**Comment by shaupt131** [comment]
**Jennifer Johnson 
February 8, 2021, 2:44 PM**

Notes from 1669

At the bottom of this file are different options for new RS numbers https://github.com/storj/datascience/blob/master/repair_and_durability/StorjNetworkRepairEconomicModel.ipynb

test dimensions

repair traffic

upload speed from a variety of internet connections

download speed from a variety of internet connections

average expansion factor (SNO payout)

garbage generated

average piece sizes per RS numbers

https://storj.slack.com/archives/CT9KZ18NQ/p1599073703037700

**Comment by iglesiasbrandon** [comment]
This issue is no longer relevant, closing this issue.
