### ISSUE TITLE
Submit patch to quic-go

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4425]
allowing receive-buffer-size to be configurable

return error if quic-go is not able to set receive-buffer-size to desired value (or access to raw connection)

[Formerly DUR-17](https://storjlabs.atlassian.net/browse/DUR-17)

**Comment by shaupt131** [comment]
**Jennifer Johnson 
April 5, 2021, 10:37 AM**

First, see how performance is without this change. Tests indicate that this is not impactful for smaller files, which is most prevalent.

**Comment by iglesiasbrandon** [comment]
Closing this issue, its no longer relevant.
