### ISSUE TITLE
Design GetRepairWork and SubmitRepairWork interfaces

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4428]
As would be used by trusted delegated repair workers (see trusted-delegated-repair.md blueprint).

AC: rpcs are defined in protobufs that will meet the needs of trusted delegated repair.

[Formerly DUR-61](https://storjlabs.atlassian.net/browse/DUR-61)

**Comment by shaupt131** [comment]
**Paul Cannon 
November 30, 2021, 11:38 AM**

See satellite/internalpb/delegated_repair.proto in the main storj/storj repo.


**Jennifer Johnson 
October 28, 2020, 1:37 PM**

Keeping this open until something uses the interfaces.

**Comment by iglesiasbrandon** [comment]
closing this ticket until we begin work on this item: https://github.com/storj/roadmap/issues/48
