### ISSUE TITLE
(TDR phase 3) Blueprint for repair on storage nodes

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4431]
https://storjlabs.atlassian.net/wiki/spaces/TD/pages/1009287179/2021+Priorities+Brainstorm

[Formerly DUR-62](https://storjlabs.atlassian.net/browse/DUR-62)

**Comment by iglesiasbrandon** [comment]
closing this ticket until we begin work on this item: https://github.com/storj/roadmap/issues/48
