### ISSUE TITLE
Document existing backend flow for MSP feature request

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4437]
https://docs.google.com/document/d/1UtsRHKfW9gvnxKyClmXOKRA6CF8pGmQ037_4H8a-12c/edit#heading=h.n2dpmg8f5gdo

[Formerly DUR-147](https://storjlabs.atlassian.net/browse/DUR-147)

**Comment by iglesiasbrandon** [comment]
closing this issue; its the account management API the UG team is working on
