### ISSUE TITLE
Remove need for client IP session affinity for quic-go

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4438]
- the client IP session affinity is a setting in gcp

- with the current quic-go implementation, this setting is required

- creates load-balancer imbalances if there are many clients on the same IP or if one client creates a lot of load - the traffic will not be distributed across the multiple servers

- We can either increase server resources or fix this issue is quic-go (lots of work)

- Not fixing it in quic-go will have some performance issues because the client’s mtu will be too small

- at the moment, windows (and possibly linux and mac), path discovery isn’t working. (causing performance issues) 

[Formerly DUR-129](https://storjlabs.atlassian.net/browse/DUR-129)

**Comment by iglesiasbrandon** [comment]
No longer relevant, closing this issue.
