### ISSUE TITLE
Account Mgmt API -project update

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4444]

**Comment by NiaStorj** [comment]
@cam-a may work on this ticket in sprint 5. depends on if the ticket below has been deployed. 
https://github.com/orgs/storj/projects/26/views/1?filterQuery=account+label%3A%22account+mgmt+api%22#:~:text=End%20point%20for%20getting%20project%20usage

**Comment by NiaStorj** [comment]
@NikolaiYurchenko please add story points even though this has been merged
