### ISSUE TITLE
Storj saying QUIC is misconfigured

### ISSUE THREAD

**Issue by saxobroko** [storj/storj#4446]
Storj says QUIC is misconfigured randomly after it working for the past few months. Although I've port forwarded and verified that the ports are forwarded.

![image](https://user-images.githubusercontent.com/18757374/151643336-38df1d5a-e366-4484-9d9a-5bbd5d07053f.png)
![image](https://user-images.githubusercontent.com/18757374/151643365-3aac34a8-1c7a-46e6-bb4f-01044b66872f.png)

**Logs:**
[log.txt](https://github.com/storj/storj/files/7962804/log.txt)

**Your environment**
- Operating system and version: Windows 10 ; Version	10.0.19044 Build 19044

**Comment by profclems** [comment]
Hi @saxobroko, thanks for opening this issue.

Obviously, the screenshot and logs show that your node is offline and none of the satellites are able to reach your node. So when the node sends a pingMe request to the satellite to verify that QUIC is properly configured

**Comment by saxobroko** [comment]
The issue was my isp rotated my public ip so I just needed to change that in the config.

**Comment by profclems** [comment]
Hope QUIC status is showing "OK" now?

**Comment by saxobroko** [comment]
Yep all good now!
