### ISSUE TITLE
Add documentation to not run storagenode as root

### ISSUE THREAD

**Issue by Erikvv** [storj/storj#4458]
Motivated by https://github.com/storj/storj/pull/2472. I referenced this request in the #guild-documentation channel. 

I would like to add 2 pieces of documentation to https://docs.storj.io/node/setup/cli/storage-node to follow best practices and instruct our users to not run the storage node image as root.

1. In the table at `<storage-dir>` add:

"Please create the directory beforehand to prevent permission errors. Run `mkdir -p <storage-dir>` to create the directory."

2. At the `docker run` commands for Linux and macOS add the argument:

```
--user $(id -u):$(id -g) \
```

That's in 4 places. Only for the storage node, not for watchtower.

I am not familiar with docker permissions on Windows so those commands can stay as-is.

**Comment by AlexeyALeonov** [comment]
Added for review: https://app.gitbook.com/o/-Lij5OMtVUHTiJ2J0i52/s/-LiiXe2K6q6NwWAdegg5/~/changes/nwALX9MIDqGPRUiwkHkc/setup/cli/storage-node

**Comment by heunland** [comment]
@AlexeyALeonov I do not see that the requested sentence for 1) has been added yet to the <storage-dir> description:

"Please create the directory beforehand to prevent permission errors. Run mkdir -p <storage-dir> to create the directory."

Is this intentional?

**Comment by AlexeyALeonov** [comment]
> Is this intentional?

Yes!
You need to have this location exist using any setup anyway. For example in Windows you cannot create a disk with this command. The `-p` option will create the requested path even if it could be wrong, especially for Linux and Mac.
So, let it throw an error, and not we will offer a command to help hide the user's error when specifying the wrong directory.

**Comment by heunland** [comment]
fixed some grammar and added clarifications, changes are merged
