### ISSUE TITLE
The storagenode web dashboard never updates the TX information for the last payout until restart the service

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#4464]
**Description**
When the payout it finished, the satellites sends receipts to the storagenodes, storagenode updates most of the information on dashboard after approximately 12 hours.
However, the TXs in the payout history doesn't update until you restart the service (the only clear cookies and cache is not enough).

**Screenshots**
Today is 2/11/2022, and the [Payout cycle has been completed several days ago](https://forum.storj.io/t/feb-7-2022-ethereum-layer-1-zksync-and-polygon-payouts-for-the-month-of-january-are-now-complete/17197) (four days to be precise). So the information on the dashboard is expected to be updated.
See
![image](https://user-images.githubusercontent.com/26858949/153536172-edf5e2cc-7fcf-4e11-bc6c-b25173f7af96.png)

Hard refresh (Shift-F5) doesn't help. After restart of the service (or container):
![image](https://user-images.githubusercontent.com/26858949/153536280-2c0a1359-1632-43fe-9b63-493ac39ef36a.png)

**Steps to reproduce the issue:**
1. Run storagenode
2. Receive payout
3. Make sure, that it's appear in the [Payout information -> Payout History](http://localhost:14002/payout-information) for the last month
4. Expand any satellite - you will not see a TX
5. Restart the service
6. Now you can see a TX

**Describe the results you expected:**
When payout is received for the last month, it should show TX under each satellite in the Payout History without restart of the service/container.

**Describe the results you received:**
The TXs will appear only if you restart the service/container.

**Your environment**
- Operating system and version: Windows 10 Pro `10.0.19042 N/A Build 19042`, Ubuntu 20.04.3 LTS `Linux ubuntu 5.4.0-1050-raspi #56-Ubuntu SMP PREEMPT Thu Jan 13 13:09:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): PC `Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3401 Mhz`, Raspberry Pi3B+

**Comment by shaupt131** [comment]
Unable to replicate.  What's our next move here?

**Comment by iglesiasbrandon** [comment]
let's close this ticket since we have not been able to replicate it. if it comes up again we can do a deeper dive. @shaupt131 @profclems @AlexeyALeonov
