### ISSUE TITLE
Remove ValidateSegmentLimit when feature will be live

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4470]
We have a feature flag for segment limit but we won't need it when the feature will be fully enabled for all satellites. We should remove it from the code.

**Comment by Erikvv** [comment]
Change needs to be on top of https://github.com/storj/storj/issues/4719 to prevent conflict.

**Comment by Erikvv** [comment]
https://review.dev.storj.io/c/storj/storj/+/7916
