### ISSUE TITLE
Verify if we need more monitoring around Copy 

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4487]
We have basic information about BeginCopyObject and FinishCopyObject methods like execution time, errors, number of executions. We need to investigate to find out if we have any other statistics that we would like to collect. We may need to review also parts indirectly related to copy method e.g. object deletion, bucket deletion.
AC:
* possible ideas should be put into the ticket and pass to the team

**Comment by Fadila82** [comment]
We collect:
- calls to BeginCopyObject and FinishCopyObject
- calls to DeleteObjectExactVersion 
- successful FinishCopyObject (finish_copy_object)

We could collect the following things:
- make the distinction between deleting an object copy, deleting a copied object, and deleting an 'standard' object
- calls to promoteNewAncestors (maybe not necessary if we distinguish between deletes)
- time to live of a copied object (i.e. time after which the original is deleted)
- reason of failure of a FinishCopyObject
- number of copied segments
