### ISSUE TITLE
Rate limiter does not permit enough retries when MFA is enabled

### ISSUE THREAD

**Issue by NiaStorj** [storj/storj#4491]
The IP rate limiter is connected to the login endpoint in satellite/console/consoleweb/server.go in this line:
authRouter.Handle("/token", server.ipRateLimiter.Limit(http.HandlerFunc(authController.Token))).Methods(http.MethodPost)
Because of the way MFA is implemented (see Token() in satellite/console/service.go), we require multiple calls to this endpoint in order to authenticate  a user with MFA.
As a result, a user with MFA enabled can hit the rate limit with half the number of login attempts as defined in the rate limiter defaults (see private/web/ratelimiter.go)
AC: Permit 5 failed login attempts when MFA is enabled. The easiest way to test is to attempt logging in with correct username/password, but then put the incorrect MFA code until you see the rate limit

**Comment by NiaStorj** [comment]
cc @heunland @jenlij

**Comment by heunland** [comment]
related issue opened by the person who first reported the bug #4492

**Comment by jewharton** [comment]
Shortly after this issue was created, we merged storj/storj@dedccbd which locked accounts after 3 unsuccessful login attempts. This means that users won't be able to log in regardless of whether we increase the burst limit for MFA requests.
