### ISSUE TITLE
remove gob encoded float migration chore once all values have been converted

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4498]
Acceptance Criteria:

- *_Gob encoded migration chore is no longer in the source

**Comment by thepaul** [comment]
This will also involve removing the *_gob fields from the database, and any remaining code that knows how to read the _gob fields.

**Comment by thepaul** [comment]
Upon review, it turns out the migration code was removed back in March, once the _gob columns were not in use in new code. And the removal of the columns can be covered by #4689. This ticket can be considered done.
