### ISSUE TITLE
Review suspension metrics

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4518]
Blocks https://github.com/storj/storj/issues/4344

Clean up query related to this PR: https://review.dev.storj.io/c/storj/storj/+/6158

**Comment by thepaul** [comment]
The identified queries using nodes.suspended have been fixed. Still got the list of queries using reputations.suspended to fix, plus then I'll do one more sweep to see if any new queries have been added that need fixing.

**Comment by thepaul** [comment]
All Redash queries I can identify using nodes.suspended or reputations.suspended are fixed now (excluding queries that were already broken and queries that are archived).
