### ISSUE TITLE
Uplink is not deleting prefix

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4525]
I'm trying remove a prefix "test2"
```
OBJ                            0             test2/hello-storj/.idea/encodings.xml
OBJ                            0             test2/hello-storj/.idea/compiler.xml
OBJ                            0             test2/hello-storj/.idea/modules.xml
OBJ                            0             test2/hello-storj/.idea/copyright/profiles_settings.xml
OBJ                            0             test2/hello-storj/.idea/vcs.xml
```
Command I executed
```
[wywrzal@lapex rclone]$ uplink rm sj://michal/test2/
removed sj://michal/test2/
```
but nothing was removed. I also noticed that no matter what I type it will say its removed.
```
[wywrzal@lapex rclone]$ uplink rm bla
removed bla
```

**Comment by Erikvv** [comment]
Doesn't seem right to remove multiple objects without the user explicitly asking for that

uplinkng has a flag `--recursive`

**Comment by mniewrzal** [comment]
Most probably but at least I would expect different result output. I would like to know that nothing was removed at the end.

**Comment by Erikvv** [comment]
This is libuplink behavior.

Not returning ErrObjectNotFound is justified by some so that the operation is idempotent. I agree with you that it should give an error but I was not able to convince others about this, I think @egonelbre but he wasn't the only one.

**Comment by Erikvv** [comment]
By the way you can distinguish between these situations: if the object existed, DeleteObject will return ObjectInfo, else it will be null.

But if this is the correct approach we should document this at https://pkg.go.dev/storj.io/uplink#Project.DeleteObject

**Comment by mniewrzal** [comment]
Yes, this is the only way we can figure out that something was really deleted. I will make a thicket to improve go doc for `DeleteObject`.

**Comment by iglesiasbrandon** [comment]
this issue is stale, if this comes up we will open a new issue.
