### ISSUE TITLE
Ensure audit system can recognize responses from QUIC so we can use QUIC with the audit system

### ISSUE THREAD

**Issue by jenlij** [storj/storj#4541]

**Comment by jenlij** [comment]
The Audit system is sensitive to return responses and errors so we disabled QUIC since there may be differences in responses from TCP. 
Figure out what types of responses/errors QUIC returns compared to TCP and adjust audit system to account for these.

**Comment by jenlij** [comment]
see comment here https://review.dev.storj.io/c/storj/storj/+/6922/7/satellite/core.go

**Comment by thepaul** [comment]
Entirely a PM decision. It seems like we've stopped pushing QUIC as hard as before, but if QUIC is going to be a first-class transport like TCP, then audits need to work under QUIC. If we don't care about QUIC, we can close this.

**Comment by iglesiasbrandon** [comment]
I'm closing this ticket until we decide if QUIC will be pushed more. (fyi @jtolio )
