### ISSUE TITLE
folder with more than 1000 objects the datetime of new objects are 0001-01-01-0100

### ISSUE THREAD

**Issue by zoltix** [storj/storj#4555]
**Description**

I have a directory with more than 16324 objects.
Now when I try to add an object I have the date of the object which is 0001-01-01 01:00:00.
I have the problem with rclone/uplink/webinterface(file are not visible).
I have the problem with Linux and Windows platforms,
I have no problem in a directory with less objects.
I can repeat this problem with creating a folder with more than 1000 objects

Have you already encountered this problem?

**Screenshots**
![image-1](https://user-images.githubusercontent.com/10147618/155016560-1eca299e-d343-4db7-882f-1037ead16b6f.png)
![signal-2022-02-21-14-38-57-473](https://user-images.githubusercontent.com/10147618/155017599-c4c52612-691b-4486-9ad7-c13144de5c23.png)

**Steps to reproduce the issue:**
```
echo "\n"
echo "\n"
echo "\n"
echo  "##################################################" 
echo  "################# small folder ###################" 
echo  "##################################################" 
echo "folder list "
uplink ls sj://backuppcloud/configuration/
echo "upload test file"
uplink cp test.data  sj://backuppcloud/configuration/test.data
echo "looking for the date"
uplink ls sj://backuppcloud/configuration/ 
echo "clean"
uplink rm sj://backuppcloud/configuration/test.data
echo  "##################################################" 
echo  "################# huge folder ###################" 
echo  "##################################################" 
echo "count number of objects"
uplink ls sj://backuppcloud/duplicatibackup/ |  wc -l
echo "count number of objects with the bad date"
uplink ls sj://backuppcloud/duplicatibackup/ | grep '0001-01-01 00:17:30' | wc -l
echo "count number of objects with other date"
uplink ls sj://backuppcloud/duplicatibackup/ | grep -v '0001-01-01 00:17:30' | wc -l
echo "upload test file"
uplink cp test.data  sj://backuppcloud/duplicatibackup/test.data
echo "looking for the date"
uplink ls sj://backuppcloud/duplicatibackup/ | grep test.data
echo "clean"
uplink rm sj://backuppcloud/duplicatibackup/test.data
echo "############# end test ############################"
echo  "##################################################" 

```

**My environment**
archlinux, window.

**Comment by amwolff** [comment]
Hi! Yes. This was fixed with https://github.com/storj/uplink/commit/9e00d72711dcc9b3cac23f1bcfeed4396573949c. The fix should be live soon.

**Comment by iglesiasbrandon** [comment]
Closing this issue since it was fixed already.
