### ISSUE TITLE
Add validation error in case trying to create a folder with the same name in browser

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#4557]
**Describe the feature or problem you'd like to solve**
For now if user trying to create a folder with the same  name -> we highlight input field red and disable 'Save Folder' button. But for users it might be unclear, especially if they have a long list of folders. See attachment
**Propose a Solution**
Add validation error in case trying to create a folder with the same name 
**Additional context**
<img width="1792" alt="Screenshot 2022-02-23 at 13 04 17" src="https://user-images.githubusercontent.com/14928042/155307343-18f7cf4b-eb0d-4dd1-9894-c67e69195c75.png">
<img width="1792" alt="Screenshot 2022-02-23 at 13 03 45" src="https://user-images.githubusercontent.com/14928042/155307375-0bda5a99-55b1-427e-a4f4-51332021cd0f.png">

**Comment by iglesiasbrandon** [comment]
this issue has been fixed, we show an error message if its the same!
