### ISSUE TITLE
Remove users table column last_verification_reminder

### ISSUE THREAD

**Issue by cam-a** [storj/storj#4560]
Remove column last_verification_reminder from users table. It's not needed anymore due to new column verification_reminders

**Comment by lizzythomson** [comment]
Waiting for this change (https://review.dev.storj.io/c/storj/storj/+/9231) to be deployed before dropping the last_verification_reminder column

**Comment by lizzythomson** [comment]
Deployed in v1.73.0 [f733cb2](https://github.com/storj/storj/commit/f733cb2)
