### ISSUE TITLE
New Project Dashboard. Confusing line smoothing

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4564]
**Expected Behavior**
Accurate graph.

**Actual Behavior**
![image](https://user-images.githubusercontent.com/6333390/155516466-6f00faf6-3afe-4ff9-a9d0-2b306ccad481.png)
The beginning of the month is correct with almost no used space. I uploaded a single file. That gets me up to 16.6 MB. Take a look at the transation from 0 to 16.6 MB. The line looks like I had a higher usage for a moment. That is caused by line smoothing. We shouldn't do it. Accuracy is more important here.

**Comment by NiaStorj** [comment]
@VitaliiShpital needs story points, please

**Comment by mobyvb** [comment]
deployed in 1.57. Commit: https://github.com/storj/storj/commit/289be4f1e9bc3ffa6be5e9068dee08a58686e9a3
