### ISSUE TITLE
[Objects browser] The preview of the object and nodes map doesn't work

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#4568]
**Description**

The preview of images for example doesn't work anymore - it showed infinity load, but never loads

**Screenshots**

![image](https://user-images.githubusercontent.com/26858949/155867883-8a6470d3-b5e1-4969-8397-684315b713d7.png)

**Steps to reproduce the issue:**

1. Upload image
2. The preview window will be opened
3. Neither preview nor map are loaded

**Describe the results you expected:**

The preview of the object (images in particular) and nodes map should be showed

**Describe the results you received:**

The preview of the object (images in particular) and nodes map are broken

**Your environment**

- Operating system and version:
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): Chrome browser Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by littleskunk** [comment]
Duplicate: https://github.com/storj/storj/issues/4548
