### ISSUE TITLE
Create Overview of Durability Dashboards

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4573]
Assemble a list of currently available durability dashboards/metrics, and highlight important/most valuable information that they contain.  This request originated from 3/1 Durability Sprint Retrospective and is part of a greater goal of setting up a rotation for checking durability metrics/alerts.

**Comment by shaupt131** [comment]
Output will be a confluence page containing a breakdown of what dashboard we have, what they contain, alerts, etc.

**Comment by jenlij** [comment]
https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2333704203/Durability+Monitoring+Reference

**Comment by shaupt131** [comment]
Please review the above documentation and respond with any questions or feedback by Friday 6/24.
