### ISSUE TITLE
Test plan for Account Management API

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4612]
Moby is back from vacation next week. We should ask him how we can support his team best. What we would like to add for sure are some security tests. Who is allowed to call a specific function of the Account Management API?

**Comment by littleskunk** [comment]
A good example how we can test it would be this: https://github.com/storj/storj/blob/main/satellite/console/consoleweb/endpoints_test.go

**Comment by ihaid** [comment]
https://github.com/storj/storj/blob/main/satellite/console/consoleweb/consoleapi/gen/README.md
