### ISSUE TITLE
Billing -> Coupons

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4634]
Figma Links:
- https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=11672%3A83058
- https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=11672%3A83083

Acceptance Criteria: must contain information about total estimated charges, coupon usage, available balance, costs by project, and everything else that is outlined in the mockups.

![Screen Shot 2022-03-18 at 4 39 39 PM](https://user-images.githubusercontent.com/5313116/159080223-abc8618a-a3b9-4755-b607-73907d38e4f7.png)

**Comment by hovex023** [comment]
@NiaStorj done

**Comment by mobyvb** [comment]
task to enable in production tracked here https://github.com/storj/storj/issues/5133
