### ISSUE TITLE
UX updates to Bucket Details Screen

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4635]
When a user views the details of a bucket, I want an Overview Table that shows the details per topic so that the user can see a simple details breakdown.

Figma Link: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=12444%3A77581

AC:
- Access Bucket Details from settings nav https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=12447%3A69576
- table headers/ bucket details topics: 
> - Name
> - Description
> - Date Created
> - Last Updated
> - Object Count 
> - Access Grants (skip this, not possible)
> - Users

- Details per topic:
> - Name: name of bucket 
> - Description: user can add or edit bucket description
> - Date Created: date and time bucket was created — time can be UTC
> - Last Updated: date and time bucket was updated — time can be UTC
> - Object Count: # of Objects within the bucket
> - Access Grants: # of access grants within a bucket (skip this, not possible)
> - Users: # of users that have access to the bucket

**Comment by stoweandi** [comment]
<img width="623" alt="Screen Shot 2022-03-18 at 3 05 59 PM" src="https://user-images.githubusercontent.com/48924196/159076554-1d5c537a-c8f2-405e-9725-ead726b60d1b.png">
<img width="617" alt="Screen Shot 2022-03-18 at 3 10 46 PM" src="https://user-images.githubusercontent.com/48924196/159076626-290e032d-21a9-4d80-8fe0-e6b023e81d80.png">

**Comment by mobyvb** [comment]
We will not be able to list the number of access grants, so I am updating the ticket to remove that as a requirement

**Comment by mobyvb** [comment]
for now, get to this page by adding a menu item to the kebab menu on /buckets/management page - right now there is only "delete", but we can add a new item called "details"
