### ISSUE TITLE
UX update for Quick Start Guide for CLI

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4640]
Updates to the current CLI quick start guide include:

-  Update the finish step
-  Add a title to the guide
-  Add progress bar
-  Update buttons
-  Update styles
-  Update graphics
-  Add the missing two access grants steps

Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=11691%3A87710

Prototype:
https://www.figma.com/proto/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=11691%3A87710&scaling=scale-down&page-id=11690%3A76302&starting-point-node-id=11691%3A87378

**Comment by stoweandi** [comment]
<img width="568" alt="Screen Shot 2022-03-18 at 3 41 41 PM" src="https://user-images.githubusercontent.com/48924196/159080412-8a58fb63-d60c-44d0-847b-0c5a22a1dc41.png">

**Comment by NiaStorj** [comment]
@VitaliiShpital needs story points
