### ISSUE TITLE
2FA - Two buttons with the same functionality

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#4644]
**Description**

**Screenshots**
<img width="1027" alt="Screenshot 2022-03-21 at 13 06 59" src="https://user-images.githubusercontent.com/14928042/159252928-c75a825f-8316-4759-abdb-2f2b97087391.png">

**Steps to reproduce the issue:**
1. Enable 2FA, enter code and go further
2. Pay attention on 'Save recovery codes" screen both buttons has the same functionality

**Describe the results you expected:**
Leave only "Done" button

**Describe the results you received:**

**Comment by NiaStorj** [comment]
not present in V2, so not worrying about fixing in production
