### ISSUE TITLE
2FA - problems on Login Page (with 2FA enabled)

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#4645]
**Description**
On login page with 2FA - 2 problems:
1. If click on "Use recovery code" - user can't go back to using code from authenticator (can only cancel login process and start again)
2. if using recovery code change hint text "You'll need the six-digit code from your authenticator" -> "Use saved recovery code"

**Screenshots**

**

https://user-images.githubusercontent.com/14928042/159254660-98eeaf30-6308-46c2-bcb7-2309034cad79.mp4

**Comment by NiaStorj** [comment]
Bug is not present in V2 (Vuetify), but still present in production.

**Comment by boshevski** [comment]
Now that v2 is in production, we can close this issue.
