### ISSUE TITLE
Deleting folder with a lot of files - add loader

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#4649]
**Description**
if user delete folder with lot of files -> loader appears only for one second. After that it disappear but folder still in list ( on the background we doing stuff - delete files one by one, but for user it's unclear). For folders with thousands files it can take minutes
**Screenshots**

https://user-images.githubusercontent.com/14928042/159463836-2fd5a44d-c156-4979-8822-e76f45a7df27.mp4

**Comment by NiaStorj** [comment]
@mobyvb test in V2. do not worry or test in production app.

**Comment by NiaStorj** [comment]
This is in V2. so closing ticket
