### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Key') while uploading folders

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#4650]
**Description**
Error appears when uploading folders - and only in case if using OWN PASSPHRASE ( I used '555') -> with autogenerated passphrase - works correct
Impossible to download these files - Chrome has blocked it
see attachments
**Screenshots**
<img width="399" alt="Screenshot 2022-03-22 at 12 56 31" src="https://user-images.githubusercontent.com/14928042/159467314-a6620edd-a897-4217-b8ef-08bd7c4e0062.png">

https://user-images.githubusercontent.com/14928042/159467363-e7c5a9b2-afa0-46da-aa45-b51ee1fd0e20.mp4

**Comment by NiaStorj** [comment]
@andriikotko is this still relevant?

**Comment by ferristocrat** [comment]
Closing as it's so old.
