### ISSUE TITLE
Metric payed / free tier transfers by user agent

### ISSUE THREAD

**Issue by wthorp** [storj/storj#4659]
**Describe the feature or problem you'd like to solve**

We have metrics which allow us to ballpark transfer statistics by user agent.  We'd like to augment this, showing how much of this corresponds to paying customers instead of free tier users.

**Propose a Solution**
We need to somehow determine (as best as reasonable) if the active user is payed user, and add it to version_collector.go's collectTransferStats() function (WIP as of 03/24/22).

**Additional context**
https://review.dev.storj.io/c/storj/storj/+/7063

**Comment by iglesiasbrandon** [comment]
Closing this issue, no longer relevant.
