### ISSUE TITLE
Review which test cases from test plan are still not covered

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4667]
QA team defined test plan for server-side copy feature https://github.com/storj/storj/pull/4317. We need to review this plan to find out which tests cases are still not covered in code base. For this ticket we need:
* find not covered (also not covered fully) cases
* make a tickets to create missing test cases

If some cases will related its possible to put them under single ticket. Add all created tickets to milestone https://github.com/storj/storj/milestone/5.

Acceptance Criteria:
* list of test cases we are missing comparing to test plan
* list should be added to this ticket

**Comment by Qweder93** [comment]
[Server-side copy test plan verification.pdf](https://github.com/storj/storj/files/8454755/Server-side.copy.test.plan.verification.pdf)
