### ISSUE TITLE
Investigate 'not enough pieces' errors in audit and repair

### ISSUE THREAD

**Issue by thepaul** [storj/storj#4670]
We've been seeing intermittent errors from the audit and repair subsystems indicating failures to download enough pieces to reconstruct segments. In each case so far, it looks like the problem has been some sort of networking blip where the satellite can't communicate with nodes that are actually online.

Review the code in both audit and repair to see if there are extra steps we can take to handle this situation more completely. For example, we might retry the operation attempting to contact all nodes holding pieces, even if the overlay says they're offline. Or if most of the failures were network timeouts, we should consider retrying immediately in a loop up to a max count.

**Comment by iglesiasbrandon** [comment]
@jenlij @thepaul is this still an issue that should be open? it feels quite stale to me I have not heard or seen this error in some time. @shaupt131

**Comment by thepaul** [comment]
It could be argued that this was sufficiently solved by #4669.

**Comment by iglesiasbrandon** [comment]
sounds good I'm going to close this ticket then. thank you @thepaul
