### ISSUE TITLE
Horizontally Scalable Node Auditing Blue Print

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4690]
### Summary:
When a node joins the network they go through a vetting process. One aspect of the node vetting process is auditing the nodes for pieces they should be storing. A node must successfully complete a certain number of audits to pass the vetting process. As more and more nodes join the network the vetting process for each individual node takes longer because the satellite is limited by how many total audits it can perform. Because we are not able to scale our audit workers horizontally the satellite is limited by how many audits it can perform. This means that as we onboard new nodes and store more data on the network the node vetting process takes longer and longer for individual nodes. We need to be able to scale node auditing on the fly depending on how many new nodes have joined the network recently or how much more data is being stored on the network.

Acceptance Criteria: 
- A blueprint is created describing how we intend to implement this feature. 
- The blueprint must contain a section with product requirements. (please work with the @iglesiasbrandon on this section)

**Comment by shaupt131** [comment]
https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2343010305/Design+Audit+Scaling

**Comment by jenlij** [comment]
https://review.dev.storj.io/c/storj/storj/+/8041
