### ISSUE TITLE
Server Side Copy. s3 CLI copy object fails when object is larger than default multipart threshold

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#4706]
Expected Behavior
User should be able to copy objects larger than 8mb on selfhosted gateway mt using aws s3 cli

Actual Behavior
![Capture](https://user-images.githubusercontent.com/82845192/161983767-09a080c5-9dfc-4169-88f6-c782695601b4.JPG)

Default segment size for aws s3 cli is 8mb for copy, if it is above this then it tries to use multipart, hence increasing this segment default allows even more larger objects to be copied since segment limit equals max object size that can be copied
 - (1st) copied object is a low-res gif under 1mb, and it gets copied flawlessly
 - (2nd) copied object is a 20mb text file that fails to get copied, shows respective error message (copy failed)
 - (3rd) copied object is the same 20mb text file that gets copied, after default aws s3 threshold gets increased

**Comment by mniewrzal** [comment]
Server-side copy was not enabled for this test. Closing.
