### ISSUE TITLE
Navigation from main Buckets screen to individual Bucket Details

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4720]
When a user is on the main bucket selection screen, I want them to have the option to navigate to the individual bucket details view, so that they can be brought right into the bucket details view. 

AC:
- 

Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=12749%3A68399

**Comment by mobyvb** [comment]
deployed in v1.57 https://github.com/storj/storj/commit/e01daa538e7dc62018d38281f31b5abac64e1480
