### ISSUE TITLE
[storagenode]: CRIT level logs by supervisord 

### ISSUE THREAD

**Issue by profclems** [storj/storj#4728]
**Description**

There are 3 critical level logs logged by supervisord in the current storagenode image:

1. CRIT level message when running the docker image as root:
    ```
    CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
    ```

2. CRIT level message when run as a non-root user or a user id is specified:
    ```
    CRIT could not write pidfile /run/supervisord.pid
    ```

3. CRIT level message for authentication checks
    ```
    2022-03-18 20:08:27,218 CRIT Server 'inet_http_server' running without any HTTP authentication checking
    ```
Originally reported at https://forum.storj.io/t/crit-messages-in-log-after-update-docker/17859
<!--

**Comment by profclems** [comment]
> 3. CRIT level message for authentication checks
>     ```
>     2022-03-18 20:08:27,218 CRIT Server 'inet_http_server' running without any HTTP authentication checking
>     ```

This is logged at critical level by supervisord because it is assumed as a critical security concern when running supervisord without authentication checks. This is safe to ignore as long as we do not allow HTTP access outside the container; it is configured to only listen to localhost, so it’s reasonable to run without HTTP authentication checks

**Suggested Solution**: set dummy user/password in the [[unix_http_server] ](http://supervisord.org/configuration.html#unix-http-server-section-settings)and [[supervisorctl] ](http://supervisord.org/configuration.html#supervisorctl-section-settings)sections of the config file to remove the CRIT log entries as suggested here: [CRIT Server 'unix_http_server' running without any HTTP authentication checking · Issue #717](https://github.com/Supervisor/supervisor/issues/717#issuecomment-176860145)

> 1. CRIT level message when running the docker image as root:
>    ```
>    CRIT Supervisor is running as root. Privileges were not dropped because no user is specified in the config file. If you intend to run as root, you can set user=root in the config file to avoid this message.
>    ```

We intentionally unset the user=root in the supervisord.conf to allow running the container as a non-root user. When running as a root user, supervisord will automatically run as a root user but logs this warning. If the container is run as a restricted user, supervisord will run using the user privileges.

Suggested Solution: set user=root in supervisord.conf when container is run as root??

**Comment by mniewrzal** [comment]
Ticket was split into separate issues:
https://github.com/storj/storj/issues/4729
https://github.com/storj/storj/issues/4730
https://github.com/storj/storj/issues/4731
