### ISSUE TITLE
Integrate sessions into satellite UI

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4735]
Final step for [this design](https://github.com/storj/storj/blob/main/docs/blueprints/webapp-session-management.md). Take the functionality implemented in #4734, and complete step 3 from the blueprint:

3: Integrate new table with the web app (and remove old Claim authentication):

a) Logging in:

When a user logs in, create a new session. Store the signed session ID in a cookie, similarly to how we were storing a signed Claim

b) Authorizing a request:

Update the authorization middleware in server.go to validate the signature in the cookie, then retreive the session from the new table given the session ID in the cookie.

If the session is NotFound or ExpiresAt has passed, delete the cookie and do not authorize the request.

If the session is valid, retreive the User struct from the database using the UserID in the session. Store this in the context like before.

c) Logging out:

When calling the logout endpoint, before deleting the cookie, attempt to delete the session from the database

**Comment by NiaStorj** [comment]
We need to verify if these session management changes fixed https://github.com/storj/storj-private/issues/7 @xaresys @mobyvb

**Comment by mobyvb** [comment]
deployed in v1.58
https://github.com/storj/storj/commit/58c5d44f44b1531de86f6a6660d7be860f94dd44
