### ISSUE TITLE
uplink should fail if it can't open enough file descriptors for requested parallelism

### ISSUE THREAD

**Issue by thepaul** [storj/storj#4736]
**uplink command currently does not error out when socket creation fails with EMFILE**

In the course of researching a different problem with uplink, we found that the binary seems to succeed silently when asked for a high level of parallelism (e.g., `-p 100`) while its `RLIMIT_NOFILE` was not high enough to allow downloading that many segments in parallel (e.g., `ulimit -n 1024`). Under these conditions, and while downloading a specific type of object and outputting it to stdout, this would also trigger another bug causing data corruption in the download (see commit 1422a1ff).

But the main point here is that the uplink should error out with an explanatory message when asked to use more parallelism than allowed by `RLIMIT_NOFILE`. It should advise the user either to use a lower level of parallelism or to raise the limit on file descriptors.

This could be done by:

1. checking the rlimits explicitly, or
2. exiting when socket creation fails with `EMFILE`

I _have_ verified using `strace` that the uplink binary does encounter `EMFILE` errors frequently when run under these conditions, usually (always?) during `socket(2)` calls, and I'm not sure why they seem to be ignored. I don't see any code explicitly looking for that error, so perhaps we are using `net.(Error).Temporary()` and it considers `EMFILE` to be temporary?

(Whether we honor the soft limit or the hard limit on `RLIMIT_NOFILE` is not addressed here. Either approach is reasonable to me)

**Comment by mniewrzal** [comment]
Change https://review.dev.storj.io/c/storj/storj/+/7664 should improve visibility of `too many open files` erro but I'm still looking if there is something more to improve.
```
failed to download part 0: uplink: eestream: failed to download stripe 0: 
error retrieving piece 09: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 2.227.240.117:28972: socket: too many open files
error retrieving piece 16: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 178.33.37.11:28967: socket: too many open files
error retrieving piece 17: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 89.184.83.12:28967: socket: too many open files
error retrieving piece 42: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 130.61.154.60:28967: socket: too many open files
error retrieving piece 43: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 5.252.194.19:29027: socket: too many open files
error retrieving piece 45: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 87.106.204.246:28967: socket: too many open files
error retrieving piece 52: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 195.60.5.30:28967: socket: too many open files
error retrieving piece 57: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 46.29.160.117:28967: socket: too many open files
error retrieving piece 60: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 31.18.140.167:28283: socket: too many open files
error retrieving piece 73: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 199.204.82.72:28970: socket: too many open files
error retrieving piece 94: ecclient: piecestore: rpc: tcp connector failed: rpc: dial tcp 213.186.246.115:28967: socket: too many open files
	main.(*cmdCp).parallelCopy:417
	main.(*cmdCp).copyFile:262
	main.(*cmdCp).Execute:156
	main.(*external).Wrap:123
	github.com/zeebo/clingy.(*Environment).dispatchDesc:126
	github.com/zeebo/clingy.(*Environment).dispatch:53
	github.com/zeebo/clingy.Environment.Run:34
	main.main:26
	runtime.main:250
```

**Comment by mniewrzal** [comment]
I think after this change will be merged https://review.dev.storj.io/c/storj/storj/+/7668 when `too many open files` occur it should be clear what happened while doing upload or download.
