### ISSUE TITLE
Generated REST API: Write basic documentation

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4737]
The API is defined here: https://github.com/storj/storj/blob/main/satellite/console/consoleweb/consoleapi/gen/main.go

But there needs to be some resource to describe how to use it

AC: A small markdown file in satellite/console/consoleweb/consoleapi/gen is sufficient. It must include
* how to authenticate API (assuming you already have an API key)
* every endpoint, with the full path, a short description of what it does, and request/response types

It does not need to be too detailed. Just the basic information to get someone up and running

**Comment by Erikvv** [comment]
Can you prefix the issue title with a topic or attach to a milestone?

There is no indication what feature this is about.

**Comment by mobyvb** [comment]
done

**Comment by mobyvb** [comment]
https://github.com/storj/storj/pull/4743

**Comment by mobyvb** [comment]
@egonelbre yes, that is the plan, but for now we just need something quick that we can provide to the customer so that we can begin testing and receiving feedback on the specific endpoints we have implemented.
