### ISSUE TITLE
Add endpoint to generated API for creating API key for uplink

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4738]
We want an end point for uplink API key [access grant without encryption key] so that we can create access grant / credentials without having to access the GUI

AC:
- an MSP user can create credentials without having to login into the gui

**Comment by Erikvv** [comment]
Will this be in Uplink (DRPC) or through HTTP?

**Comment by mobyvb** [comment]
@Erikvv this is for our generated HTTP API defined here: https://github.com/storj/storj/blob/main/satellite/console/consoleweb/consoleapi/gen/main.go

**Comment by mobyvb** [comment]
deployed in 1.57 https://github.com/storj/storj/commit/d916b26e0ee5906d875e00d1c01487665d3255a6
