### ISSUE TITLE
Create a method for updating users in the DB without requiring all fields

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4742]
The existing [usersDB.Update()](https://github.com/storj/storj/blob/main/satellite/satellitedb/users.go#L142) function expects all fields to be passed into it. This means that we cannot do something like:

```
usersDB.Update(&console.User{ ID: <someID>, FullName: "updated full name" })
```
as it will end up setting many other fields on the user to blank/default values.

So rather, all update calls are required to be called like:

```
user, err := usersDB.GetUserByEmail("something@mail.test")
...
user.Name = "updated name"
usersDB.Update(user)
```

AC: create a method for updating some fields in the users struct without providing all other fields. This method should keep the existing values for fields that are not provided.

**Comment by stoweandi** [comment]
Duplicate[ ](https://github.com/storj/storj-private/issues/36)
