### ISSUE TITLE
Buckets -> Upload Progress Bar

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4746]
Update the upload progress bar on the buckets page when a user uploads 1 or many objects. The update MUST include all of the states in the Figma designs for success and failure. 

Figma Designs: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/?node-id=12640%3A65315

**Comment by stoweandi** [comment]
@liviolanda @iglesiasbrandon can you help me add the right link in here?

**Comment by liviolanda** [comment]
Page on Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/?node-id=12640%3A65315

Screens by line:

1. Upload to bucket + Upload to folder
Show the user dragging and dropping the file inside a bucket or folder. While dragging, we display a thumbnail of the doc, and the alert on the top. 

2. Uploading condensed + Upload exposed 
 - show the upload progress, after a user dropped or added files. 
 If one object was added - condensed view
 If multiple files were added - exposed view by default, that becomes condensed if the user clicks on the chevron.
 
 3. Upload cancelled + Upload finished + Upload failed = Upload failed variations
 - show interactions when upload progress is interrupted

@alexsytnikk could you double-check if I described it the way you thought?

**Comment by iglesiasbrandon** [comment]
this issue is stale, if this comes up we will open a new issue.
