### ISSUE TITLE
Write Testplan for Session Management

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4757]
https://storjlabs.atlassian.net/wiki/spaces/ENG/pages/2232221701/Security+Requirements

https://github.com/storj/storj/commit/3397886

**Comment by nadimhq** [comment]
<google-sheets-html-origin>

Test Scenario | Test Case | Description | Comments
-- | -- | -- | --
Cookie Handling | Session ID | When user logs in and creates a new session, there should be a signed session ID in a cookie |  
  | Request Authorization | With a signed session ID in a cookie, there should be a request to recieve the session from the WebappSessions table w/ the given session ID in the cookie |  
  | Authorization 1 | First the session checked if NotFound or ExpiresAt has passed from the new table given the session ID in the cookie, then the cookie is deleted and request is not authorized |  
  | Authorization 2 | Second, if there were no issues with authorization from the previous step and if the session is valid from the new table given the session ID in the cookie, then the User struct should be received from the database using the UserID in the session |  
  | Logout- Delete Session | If logout endpoint is called, then session should be deleted from database |  
  | Cookie Deletion | Cookie should be deleted only after session is deleted from database |  
  | Inactivity Timout | Session should be invalidated if user is inactive for a set period of time |  
  | Closing the Browser | A session should be invalidated once the user closes their browser for a session |  
  | New IP Address | If a session is created from a new IP(different than previous session), then there should be two-factor authentication to verify the user |  
  | Valid Authorization | If the session is valid from the new table given the session ID in the cookie, then User struct should be received from the database using the UserID in the session |  
Multiple Sessions | Logout- Delete Session | If a user is logged into multiple sessions, then all sessions should be invalidated once the user logs out from one of the sessions |  
  | Reset Password | If a user resets their password, then all sessions should be invalidated once the user successfully resets their password |  
  | Inactivity Timeout | Regardless of how many sessions there are, if there is inactivity in one sessions then all sessions should be invalidated for security purposes |  
  | Closing the Browser | Regardless of how many sessions there are all sessions should be invalidated once the user closes the browser used for a session |

**Comment by littleskunk** [comment]
looks good to me

**Comment by nadimhq** [comment]
need reviews on https://github.com/storj/storj/pull/4800

**Comment by nadimhq** [comment]
https://github.com/storj/storj/blob/3397886b1492b76bcbb175f5d65665bfc5c05e05/docs/blueprints/webapp-session-management.md

This is Moby's blueprint for session management, I will also fix and add to your comments on the PR @littleskunk
