### ISSUE TITLE
Create Access grant flow

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4760]
API key 
I want the ability to get generate an access grant in the satellite GUI.

Acceptance Criteria: 
- When a user selects the "access grant" button in the modal window this option is automatically selected
- The info icon displays the 'copy' that is on the CLI access/ API key card

**The following fields/ checkboxes are available**

> - Access Name (required)
> - Permissions (required)
> - Expiration date (optional)
> - Select Buckets to add (default to all buckets selected) 
> - Description (optional) (new field, this is a new feature)

- once all required fields are entered or selected the 'encrypt my access' button should turn blue 
- the user must have the ability to generate or enter their down passphrase 
- the user must have the ability to download a txt file with the passphrase if they select generate passphrase
- once the user accepts the warning checkbox they must have the ability to click the create my access button. 
- the user must have the ability to copy the access 
- the user must have the ability to download a txt file that has them (new functionality) 

Figma link: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=11724%3A81188

**Comment by Erikvv** [comment]
Maybe you should be able to create an access grant for a bucket you haven't created yet? I do that often, first create the access grant and then the bucket.

**Comment by Erikvv** [comment]
> But we can ask the design team about it so that they can decide how the UI for creating an access for a non-existing bucket would look

Let's tag them in the ticket? Don't they use Github?

**Comment by mobyvb** [comment]
cc @liviolanda @boshevski

**Comment by iglesiasbrandon** [comment]
I'm going to close the tickets below because the work described in this ticket is being done as a part of this issue.

@hovex023 @cl-mitch @mobyvb @stoweandi

https://github.com/storj/storj/issues/4641

Please let me know if this is ok.
