### ISSUE TITLE
Generated REST API: generate documentation

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4762]
Similarly to how we are generating the Go code, we should generate some basic documentation for each endpoint defined.
This documentation should include

* Endpoint path and method (e.g. GET, POST, etc...)
* Request types
* Response types
* Any descriptive information in the API definition

It can be a .md file, or whatever makes the most sense

**Comment by stoweandi** [comment]
closing per more relevant ticket: https://github.com/storj/storj/issues/4985
