### ISSUE TITLE
[Multinode Dashboard] Empty egress and ingress charts

### ISSUE THREAD

**Issue by ghost** [storj/storj#4764]
Storage node v1.53.1

Tested browsers: Chrome, Firefox

![Screenshot_20220428_230205](https://user-images.githubusercontent.com/22368256/165845546-2f4fb040-890b-4a8c-9d16-b3128ae45d52.png)

**Comment by AlexeyALeonov** [comment]
The workaround: https://forum.storj.io/t/dashboard-issue-with-v1-53-1/18183/14?u=alexey

**Comment by stefanofornari** [comment]
fyi still in 1.54.2

**Comment by iglesiasbrandon** [comment]
@AlexeyALeonov can you confirm if this issue has been resolved?

**Comment by profclems** [comment]
This was fixed by https://github.com/storj/storj/pull/5020

cc: @iglesiasbrandon
