### ISSUE TITLE
Website copyright is not renewed

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#4779]
***This ticket was escalated from Zendesk by Aleksey Leonov:***

  **Ticket:** [#16810](https://storj.zendesk.com/agent/tickets/16810)
  **Type:** Ticket
  **Priority:** -
  **Requester:** Krishnangopalcs
  **Organization:** -
  **Assignee:** -
***

You have not renewed or may be forget to mention it  (may be), that the copyright is not updated to 2022.

>
**Storj**  
1450 W. Peachtree St. NW [#200](/agent/tickets/200)  
PMB 75268  
Atlanta, GA 30309-2955  
  
**© 2021 Storj Labs Inc.** 

Attachments:<br/> [Screenshot (119).png](https://storj.zendesk.com/attachments/token/XkH5tPml9hF5Jj6yYsEdiV173/?name=Screenshot+%28119%29.png) gz#16810

**Comment by egonelbre** [comment]
Based on https://stackoverflow.com/a/2391555/192220, the copyright should state the time the content was first written not the current year. However, as pointed out in the stackoverflow comments, the copyright date serves no purpose (https://www.reddit.com/r/webdev/comments/1p9tao/auto_updating_the_year_on_copyright_notices/).
