### ISSUE TITLE
Create a common Vue modal component for Satellite UI

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4785]
This will allow us to use a common component for all of our modals across the UI

**Comment by liviolanda** [comment]
We have a component for modals in our design library that could help:
https://www.figma.com/file/b3QhctHccKl3ihR8Q063Af/DCS-Design-Library?node-id=133%3A4841

**Comment by mobyvb** [comment]
@liviolanda are there any other common components in your design library that we should make other issues for?

**Comment by liviolanda** [comment]
Yes, you can check in this Figma link.
For sure we **won't** change anytime soon:
- Buttons
- Colors
- Inputs
- Tables
- Typography
