### ISSUE TITLE
Ensure strong object consistency while object upload

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4788]
We have one known issue with object consistency while uploading objects. When we are uploading object to the location where a different object already exists we are deleting the existing object right away. Main issues with this approach are:
* if uploading a new object fails we don't have a new and old object
* during upload we don't have access to the old object

The idea is to:
* upload object always to new version e.g. 1, 2, 3
* when object is committed always set version 1 as currently the whole system is hardcoded to this value
* after successful commit object we are deleting old object with should be with version 1

The main challenge is to do old object deletion after committing new object because old and new will have version 1.

Scope of this work will be:
* metabase
* metainfo
* maybe metainfo protobuf and libuplink if pending objects listing wont support multiple versions

Acceptance criteria:
* we should preserve old object until new object if fully uploaded and then delete old one

**Comment by halkyon** [comment]
Here is also some information on how AWS S3 works in their consistency model, including examples of "last writer wins" when objects are written concurrently: https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel

**Comment by shaupt131** [comment]
Note for when this ticket is picked back up: Please inform edge team when this issue is resolved so that checks can be performed relating to https://github.com/storj/gateway-mt/issues/214

**Comment by mniewrzal** [comment]
When https://github.com/storj/storj/issues/4871 will be released and deployed we can start enabling feature flag `metainfo.multiple-versions` on our satellites. First QA, SLC, EUN1 and later on production satellites.
```
# feature flag to enable using multple objects versions in the system internally
# metainfo.multiple-versions: false
```

**Comment by shaupt131** [comment]
Based on your comments earlier @mniewrzal, I vote we close this issue since it's being tracked in the object consistency milestone: https://github.com/storj/storj/milestone/14.  Any objections?

**Comment by mniewrzal** [comment]
No. Let's close it.

śr., 2 lis 2022, 20:43 użytkownik Steve Haupt ***@***.***>
napisał:
