### ISSUE TITLE
Switch metainfo listing from iterator to single list request

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4805]
Current `metainfo.ListObjects` implementation is using metabase iterator to list objects. Iterator implementation is rather complex and in fact we are not using its capabilities because `metainfo.ListObjects` method is returning only requested set of objects and should never do it in pages as it can cause consistency issues.

Acceptance Criteria:
* implement new metabase metod `ListObjects` (similar to ListSegmentPosition)
* new method should have the same options like iterator used atm (except BatchSize should be replaced with Limit)
* new method should be used in `metainfo.ListObjects` method instead iterator

**Comment by egonelbre** [comment]
As I mentioned in the review. I don't think there's a way to avoid easily the consistency issues.

There are two main issues:
1. The listing on the uplink side still would need to batch things
2. Non-recursive listing may require traversing the whole bucket (which may contain millions of objects)

It might make sense to keep the consistency guarantee more relaxed here. Alternatively, we could try using `AS OF SYSTEM TIME` to have a consistent view at a given point in time. This would fix both of the issues.
