### ISSUE TITLE
web/satellite: avoid mutating props directly

### ISSUE THREAD

**Issue by egonelbre** [storj/storj#4806]
Code that's using HeaderlessInput and some other components are showing errors in development builds:

```
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders.
    Instead, use a data or computed property based on the prop's value. Prop being mutated: "optionsShown"
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders.
    Instead, use a data or computed property based on the prop's value. Prop being mutated: "value"
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders.
    Instead, use a data or computed property based on the prop's value. Prop being mutated: "inputClicked"
```

The `value` one seems to come from `<HeaderlessInput> at src/components/common/HeaderlessInput.vue`.

All `@Prop` values should be declared as `readonly` and they should not be modified as the warning states.

Note: this should also be fixed in web/storagenode and web/multinode.

**Comment by VitaliiShpital** [comment]
this will be partly fixed by this PR
https://review.dev.storj.io/c/storj/storj/+/7441
