### ISSUE TITLE
Investigate what subtasks need to be completed in order to remove the aws sdk library

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4810]
See https://github.com/storj/storj/issues/4803 for context

### AC:
* Determine what steps need to be done to complete the migration described in #4803 
* Add a tasklist to #4803 with the steps after investigation, create tickets from each task, and add "needs estimation" and "needs grooming" labels to the tickets

**Comment by VitaliiShpital** [comment]
https://review.dev.storj.io/c/storj/storj/+/11237/5
https://review.dev.storj.io/c/storj/storj/+/11271/2

https://storj.slack.com/archives/C0490040EDR/p1695294871101289
https://storj.slack.com/archives/C0490040EDR/p1695295088881019

to use minio-js with vite I used an approach provided by minio dev from here 
https://github.com/prakashsvmx/minio-js-vite-react-app

unfortunatelly this approach increases bundle size dramatically

**Comment by VitaliiShpital** [comment]
so basically we should fix bundle size issue somehow. 
Also we'd need to fork minio-js repo to implement upload with progress or use my weird approach from first PR
