### ISSUE TITLE
Design: Cleanup job for nodes that never paticipated in node selection

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4812]
In the database we have a lot of nodes that never had a successful contact: `SELECT * FROM nodes WHERE nodes.last_contact_success <= '01/01/01 00:00'` 
That also means we never selected them for an upload. If we want to double-check this we could also check the storage node accounting tables for any data. Some of these nodes have been disqualified because we disqualified offline nodes after 30 days.

The reason a cleanup job makes sense is that it helps to boost performance. The node selection will be able to find nodes for uploads a tiny bit faster.

**Comment by littleskunk** [comment]
It looks like the performance impact is bigger than expected. On the US satellite with 300K garbage nodes all the nodes queries take significant longer than on the other satellites.

Unfortunalty for some of the nodes we have data in other tables like paystubs. We don't have cascading deletes. This means the cleanup job needs to delete all the other tables as well.

**Comment by jenlij** [comment]
@littleskunk Do we want to delete the disqualified nodes as well?

For reference here are the results from `SELECT count(*) FROM nodes WHERE nodes.last_contact_success <= '01/01/01 00:00'`
us1: 309130
us2: 2678
slc: 4430
qa: 41
euw1: 4934
eun1: 4271
ape1: 4952

**Comment by jenlij** [comment]
Also is this a cleanup job that we expect to run once, or on a regular interval?

**Comment by littleskunk** [comment]
Disqualified nodes without any successful contact should be safe to delete. These nodes could technically rejoin. Since we never stored a single piece on them our system would treat them as brand new nodes after the delete operation. The second query I send over will filter out the nodes that are not yet disqualified and could in theory fix their connection issues.

**Comment by jenlij** [comment]
https://storjlabs.atlassian.net/wiki/spaces/TD/pages/2359590952/Design+Node+Cleanup
