### ISSUE TITLE
Create e2e integration test for storj->storjscan integration with storj-up

### ISSUE THREAD

**Issue by elek** [storj/storj#4823]
We need a way to test storj (especially the satellite) and storjscan together without adding additional dependency to `storj/go.mod`.

One option is to create a new submodule similar to `tesuite/` in storj repository which also depends on storjcan and can start a testplanet + storjscan + testchain. 
As we have ui test in `testsuide` we may need to refactor it to `testsuite/ui` and `testsuite/storjscan` with separated go.mod for each with extended dependencies.

Another option is to use storjup for the integration test

(pinging @egonelbre, who may have better ideas or comments)

The implementation will be chosen by whoever works on this ticket after gathering options from the QA team and @egonelbre about our current approach. 

Acceptance Criteria
- adding the ability to run integration tests
- writing all of the necessary integration tests

**Comment by egonelbre** [comment]
It depends on how much control you need.

* Separating go.mod in `testsuite` would be completely fine and probably the easiest to setup.
* Using storj-up would work, however, it's probably going to be more difficult to make work on other computers.

I would go the separate go.mod route, unless there's a good reason not to. (e.g. storjscan builds are way too slow, the compilation requires special setup).

**Comment by littleskunk** [comment]
Our testplan is ready: https://github.com/storj/storj/pull/4672

**Comment by shaupt131** [comment]
This ticket will be split into 2 parts.  Create test suite for testing Storjscan will be a separate ticket, and this ticket is now to just Create e2e integration test with storj-up.  Will need to be resized.

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/up/+/8181
https://review.dev.storj.io/c/storj/up/+/8182

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/up/+/8246
https://review.dev.storj.io/c/storj/up/+/8247
https://review.dev.storj.io/c/storj/storj/+/8196
These tickets need approval before this ticket can be merged.

**Comment by dlamarmorgan** [comment]
Test Steps
1) If https://review.dev.storj.io/c/storj/storj/+/8196 has not been merged, build this branch locally. It will need to be built for a linux target.
1a) If you had to build the branch locally, add the command `storj-up local storjscan,satellite-api,satellite-core,satellite-admin -d <path to binary>` just below the `storj-up init storj,db,billing` command.
2) from the root directory, run `mage integration`. If you don't already have mage installed, you may need to install mage as well.
https://magefile.org/
3) the test will take several minutes, and run a series of commands against the system it will spin up for you. Verify at the end of the test, that the final balance returned is not 0.
