### ISSUE TITLE
Refactor/ cleanup stripecoinpayments package

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4824]
Currently, we have a package called stripecoinpayments, this package has the service (it has a stripe client, a coinpayments client, etc..) we should consider refactoring this so that it's cleaner. We can create a generic billing service or something else. 

The purpose of this ticket is to clean up this service once we have removed the dependency for coinpayments.net. 

Acceptance Criteria: 
- name change
- removing code that was previously used for coinpayments.net
- moving some code to areas that make more sense

Steps:
1) Remove no-longer needed coinpayments logic from `satellite/payments/stripecoinpayments` pkg
2) Check where `stripecoinpayments.Service` is used directly and not abstracted via `payments` pkg interfaces

**Comment by jenlij** [comment]
This can be completed after storjscan is deployed (not a blocker)

**Comment by shaupt131** [comment]
Needs reviews: https://github.com/storj/storj/issues/4824
