### ISSUE TITLE
Report audit score to grafana

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4835]
I am running a storage node and I am feeding a grafana dashboard including some alerts with the metrics endpoint of my storage node. I would like to improve my email alerts.

I had a problem with firewall. It dropped a few packages every now and than. My online score dropped but my grafana instance didn't notice it because it tracks incoming audit requests and doesn't notice any audit request that was dropped before reaching my storage node.

A possible solution for this would be some additional metrics inside the data collector job. Every few hours the storage node will contact the satellite and ask for the current audit score, the audit history and all that data. If someone could pass the audit score to the metrics endpoint that would allow me to include it into my grafana dashboard. Next time my firewall has some problems I would get an email alert days before I get suspended.

**Comment by profclems** [comment]
Related PR: https://review.dev.storj.io/c/storj/storj/+/8432
