### ISSUE TITLE
migration to remove duplicate emails in users table

### ISSUE THREAD

**Issue by cam-a** [storj/storj#4838]
Description:
There are multiple entries in the users table with the same email address. This is because in the past users were able to register multiple times if the email was not verified. This is no longer the case. If a user tries to register with an unverified email already in the DB, we send a verification email instead of creating another entry. However, since these old entries in the table with duplicate emails were never cleaned up, the email reminder chore will send out email verification reminders to them. A single person will get one separate email per entry in the DB with their email and where status = 0.

AC:
Migrate the users table so there is only one entry per email. If one of the duplicate emails is verified (status = 1) that is the one that should remain. If none of them is verified, pick one and delete the rest (which one do we keep? Maybe the latest created?)

**Comment by mobyvb** [comment]
may be unnecessary after this change is deployed and enabled in production: https://github.com/storj/storj/issues/6197
After the cleanup chore is enabled, any unverified user will be automatically deleted after a certain amount of time of being unverified. Then, we don't need to be as concerned about duplicates

**Comment by mobyvb** [comment]
I just checked, and the console cleanup chore is running in all production satellites. So there is no need to do an additional migration to remove duplicate emails - these should be cleaned up by the chore after a long enough time being unverified
