### ISSUE TITLE
Active and Hover states in the nav bar

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4845]
When a user is interacting with the Navbar in the satellite UI, I want them to see a hover state and an active state, so that the interaction with the nav bar is more intuitive.

AC:
- User sees hover state when hovering over nav buttons
- User sees the active state when they are on selected page

Link to Figma screen: https://www.figma.com/file/b5Ch0EN8GJl6oNUKcw0NLM/Production-DCS?node-id=913%3A4409

**Comment by stoweandi** [comment]
![Image](https://user-images.githubusercontent.com/48924196/171208540-89119c32-2192-4514-9fc9-8b45e5e56bc2.png)

**Comment by mobyvb** [comment]
in v1.58 https://github.com/storj/storj/commit/b25faf30abb8382056f8348d7afc3073ba5ad1e3
