### ISSUE TITLE
Active and Hover states - Sub menu items on the nav bar

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4847]
When a user is interacting with the sub menu items in the Navbar on the satellite UI, I want them to see a hover state and an active state, so that the interaction with the navbar is more intuitive.

AC:
- User sees hover state when hovering over nav sub-menu items
- User sees the active state when they are on selected a page
Link to Figma screen: https://www.figma.com/file/b5Ch0EN8GJl6oNUKcw0NLM/Production-DCS?node-id=914%3A13421

**Comment by mobyvb** [comment]
in v1.58 https://github.com/storj/storj/commit/b25faf30abb8382056f8348d7afc3073ba5ad1e3
