### ISSUE TITLE
Collapsed nav bar adjustments

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4848]
Logo in collapsed nav bar appears to be squished/distorted.
We want to update the nav bar with the layout in this figma file, so the when the nav bar is collapsed it looks like the figma designs attached.

When the navbar is collapsed, we want to add in the page titles so that the user doesn't have to think about what the icons represented in order to navigate 

AC:
- logo is updated from this figma file
- logo is not squished when nav bar is collapsed 
- Below each icon in the collapsed state is the page name

https://www.figma.com/file/b5Ch0EN8GJl6oNUKcw0NLM/Production-DCS?node-id=913%3A11052

**Comment by mobyvb** [comment]
in v1.59 https://github.com/storj/storj/commit/5f1390e1d55024df6b51c4f917f0dbc37fb8585e
