### ISSUE TITLE
Storj Logo in the nav takes you back to the dashboard of the project you are currently working in

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4850]
When a user is in the GUI and clicks on the Storj logo, I want the Storj logo to take the user to the project dashboard of the project they are currently working in, so that they have a quick way back — atm when the Storj logo is clicked it just refreshes the page.

AC:
- Storj Logo when clicked sends user back to the project dashboard 
- the project dashboard they are directed to is the project they currently have selected in the nav

Figma link: https://www.figma.com/file/b5Ch0EN8GJl6oNUKcw0NLM/Production-DCS?node-id=924%3A7657

**Comment by mobyvb** [comment]
in v1.58 https://github.com/storj/storj/commit/b25faf30abb8382056f8348d7afc3073ba5ad1e3
