### ISSUE TITLE
Add "Limit" visual component into Dashboard

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4859]
We want to move the placement of project limits so that they are not attached to usage graphs that can have different date selections than the current month. We want to avoid usage limit confusion if someone is looking at graphs for a different time period than the current billing period.

AC:
- usage limits are not attached to graphs
- user can see their fixed usage limits 

New dashboard: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=14389%3A131872

**Comment by mobyvb** [comment]
@liviolanda is the link above the latest design for this?

**Comment by liviolanda** [comment]
@mobyvb yes! let me know your thoughts

**Comment by stoweandi** [comment]
![Screen Shot 2022-06-16 at 8 58 41 AM](https://user-images.githubusercontent.com/48924196/174086662-a71aa03a-4a18-4a68-abe1-d6ebb5d26b90.png)

@NikolaiYurchenko

**Comment by mobyvb** [comment]
deployed in v1.60 https://github.com/storj/storj/commit/d571b04ac897261bd40682be12fd2279d3658220
