### ISSUE TITLE
Add public ID column to projects table

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4861]
detail ticket based on thread here https://storj.slack.com/archives/CT7F9N1EY/p1650599311008689

Context: We currently use project ID as a salt in metainfo, and this is one step to stop exposing encryption-related information unnecessarily (for example, when calling endpoints which use project ID to get, update, etc... projects)

AC:
* Create new public project ID field
* Migrate existing projects to have a random "public project ID"
* ~~Update all user-facing endpoints to use public project ID rather than "project ID"~~

**Comment by cam-a** [comment]
One AC removed because it is separated into a new ticket
