### ISSUE TITLE
Resolve redirect link breaking issue with new docs

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4863]
We need a solution for resolving the current issue of links breaking in the documentation. 
Documentation is being built out in Archbee (transitioning over from gitbooks) 

Game plan (written August 3rd):
For each page on the new docs in Archbee, go to "SEO Meta Controls" and set the "URL key" to the path from the old docs
For example, to get a page published in the "dcs" space in Archbee to show up at the URL https://docs.storj.io/dcs/api-reference/uplink-cli/rm-command/, set the URL Key to "api-reference/uplink-cli/rm-command". Do not include a beginning forward slash or it will not work

**Comment by jtolio** [comment]
Oh no.

Okay, so, every solution we've had so far for adding URL redirects for Gitbooks has been a HUGE HACK and we should really use this opportunity to stop doing huge hacks.

If there are old URLs we need to preserve, than one of two things should happen:

1) Archbee should support this. We should be able to give Archbee a list of old URLs and their new destinations. This is the ideal outcome. If it's not possible it's a serious downside to Archbee.
2) If we must use Archbee and Archbee doesn't support old URLs, then we should not continue doing the proxy hack that we did for Gitbooks. This means, at minimum, starting a new subdomain. Right now docs are at docs.storj.io. If option (1) can't be done, we should start a new subdomain (doc.storj.io, or info.storj.io, or help.storj.io), and have Archbee host that. Then, we need to make an exhaustive list of all URLs at docs.storj.io currently, and then all we should host at docs.storj.io is a redirector that redirects all requests to their correct place on the new domain. 

These two options are the only way to avoid proxying, which is what broke all sorts of SEO, TLS certificate renewal, and Javascript things on Gitbooks.

**Comment by stoweandi** [comment]
Right, to clarify, we aren't looking for a hack—sorry for the confusion by linking the slack thread!

**Comment by NiaStorj** [comment]
needs story points @mobyvb

**Comment by mobyvb** [comment]
we've figured out how to handle the page paths in Archbee, and all of the paths from the old docs should now exist on testdocs.storj.io.
