### ISSUE TITLE
Estimate work needed to complete UploadPartCopy

### ISSUE THREAD

**Issue by onionjake** [storj/storj#4875]
We need to understand the effort involved in implementing [UploadPartCopy](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html).  This is used by the amazon SDK's when the source object is larger than 5 GB.

~It is okay to assume we will not support [x-amz-copy-source-range](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html#API_UploadPartCopy_RequestSyntax)~

AC:
- T-shirt size estimation of effort involved
- Document any limitations or caveats that the estimation is assuming

**Comment by shaupt131** [comment]
For reference: https://docs.google.com/document/d/13VsXB01S7rK_4v3F_aiSXLW1INz4JoOTTVRKEgKjnvQ/edit

**Comment by Fadila82** [comment]
User story provided in the doc above:

> As a Storj DCS User I want to be able to use UploadPartCopy to copy large objects already within a Storj DCS bucket so that I can switch from my existing S3 compatible storage to Storj without having to change my multipart copy configuration.

**Comment by wthorp** [comment]
I didn't realize that [the documentation's](https://docs.aws.amazon.com/AmazonS3/latest/API/API_UploadPartCopy.html)  description of the partNumber parameter references specifically the **destination** part number and not the source part number.  It seems that x-amz-copy-source-range is the main input.

**Comment by Erikvv** [comment]
I think we discussed proposals:

1. Ask customers (Iconic) to configure large byte ranges for `x-amz-copy-source-range` instead of the default 8MiB. Reject calls which don't match segment boundries (on satellite?)
2. Same  as 1 but download and re-encrypt first and last segment of the range if necessary (in uplink).
3. Gather ranges of UploadPartCopy on satellite side for pending object, when CompleteMultipartUpload is called copy the entire object. If range does not match the entire object, reject the call.
4. Same as 3 but gather ranges on gateway side

**Comment by onionjake** [comment]
We also discussed being able to "collapse" parts as the upload part copy is called (perhaps this is just an optimization for the approaches above?). Not sure it helps but wanted to document it here.

For example, if Object A has the following segments:

```
Segment:1 Bytes 0-200
Segment:2 Bytes 201-400
```

Then assume this sequence of `UploadPartCopy` calls and the resulting state that the satellite or gateway uses to keep track.

```
UploadPartCopy request: Part: 1 Object: A Offset:0 Length: 100
State: Part: 1 Segment:1 Offset:0 Length: 100

UploadPartCopy request: Part:2 Object: A Offset:101 Length: 100
# The satellite looks at the previous entries and notices that the parts are contiguous parts
# it then updates the ranges on the original parts
State: Part: 1 Segment:1 Offset:0 Length: 200

UploadPartCopy request: Part: 3 Object: A Offset:201 Length: 100
State: Part: 1 Segment:1 Offset:0 Length: 200
          Part: 3 Segment:2 Offset:0 Length: 100


UploadPartCopy request: Part: 4 Object: A Offset:301 Length: 100
# Once again it extends the previous part because it is contiguous
State: Part: 1 Segment:1 Offset:0 Length: 200
          Part: 3 Segment:2 Offset:0 Length: 200
          
CompleteMultipartUpload -> Does a regular copy of those segments because they are complete.
```

This processing/collapsing as you go might be problematic if the S3 API allows you to overwrite parts multiple times before calling `Complete` which I suspect it does.

**Comment by Erikvv** [comment]
Would like to discuss last design decisions, will set an appointment soon. 

https://github.com/storj/storj/blob/byte-range-multi-part-copy/docs/blueprints/byte-range-multipart-copy/byte-range-multipart-copy.md

**Comment by Erikvv** [comment]
We had a meeting 2022-07-20 with Arthur, Egon, Steve, Michal, Michael and me.

Egon and I agreed that "faking" support for custom byte ranges was best, but when committing only allow full object copies. This is to keep down complexity of our current serverside copy implementation, and possibly avoid performance regressions. 

But there was inconclusive brainstorming on how to implement it. I will write down the ideas we had.

Recording (intro is missing) https://drive.google.com/file/d/1cUOICe7jZUrqML080amfc656Z0gCYpvg/view?usp=sharing

**Comment by Erikvv** [comment]
Last meeting last Wednesday 2022-07-27 

recording: https://drive.google.com/file/d/1Fl4Z9YaxbF2S9O0j9tjtkfwlFPDBUBKV/view?usp=sharing
notes: https://docs.google.com/document/d/1w77zrtDFhD9GBbf302Tj4YpqhjQrpKLhNqUPsBFvZOs/edit

Gonna make it more neat.

**Comment by shaupt131** [comment]
Current ROM: 4-8 sprints (L to XL effort).  Will continue to refine as this is broken down into milestones and tickets.
