### ISSUE TITLE
Fix SVG styling in web/satellite

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4876]
context: Our svg loader was recently reworked so that snapshots of UI tests are smaller, causing an issue preventing us from styling svgs

AC: we can style SVGs in the satellite UI (e.g. change stroke color)

**Comment by egonelbre** [comment]
It's also possible to add that specific behavior directly into the svg.

**Comment by mobyvb** [comment]
@egonelbre wouldn't we need two separate svgs in that case if we wanted to change the stroke color/thickness on something like hover?

**Comment by egonelbre** [comment]
svg-s can containing styling. e.g. https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/SVG_and_CSS

**Comment by mobyvb** [comment]
we can just change the scoping of the existing css to solve this ticket: https://review.dev.storj.io/c/storj/storj/+/7718

**Comment by mobyvb** [comment]
deployed in v1.57
https://github.com/storj/storj/commit/4e0acba9ba14871e5f64e883bab77a5548e1896c
