### ISSUE TITLE
Update Storjscan client payment type with USD value

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4878]
Job Story: 
When the satellite requests payments from the storj scan I want storj scan client to return the USD value of the transaction So that this information can be saved in the satellite DB and displayed to the user in the future. 

Acceptance Criteria
- Storj scan client must return the USD value of the transaction back to the satellite

**Comment by rikysya** [comment]
https://review.dev.storj.io/c/storj/storj/+/7797

**Comment by shaupt131** [comment]
Retro notes:  Team absences made the code review process slower than normal, but otherwise ticket was originally sized correctly.
