### ISSUE TITLE
Update Storjscan DB cached payment types with USD value

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4879]
Job Story: 
When we use the storj scan client to get objects that represent payments and contain the USD value of them there is a sep structure in the DB we want to add the USD value to the cached payment types (go struct) I want that structure to have the USD values so that we can pass and store the USD value of the payment in the database

Acceptance Criteria: 
- The USD value is saved in the DB 
    - (the satellite DB schema already has a field for USD value)

**Comment by rikysya** [comment]
https://review.dev.storj.io/c/storj/storj/+/7841
