### ISSUE TITLE
Test Concurrent Download limit of storage node network

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#4886]
> How many concurrent downloads can 80 (more realistic would be 50) storage nodes handle? My expectation is that a single download doesn't utilize all the bandwidth. If we spin up 2 downloads I would expect that both downloads will finish more or less at the same time. Ok now let's scale this up. At some point I would expect that let's say 100 concurrent downloads from the same 50 storage nodes will take longer and longer. If we would plot that into a graph I would expect to see some kind of curve and as soon as we max out even the fastest node in the mix it should turn into a linear graph. Not sure if I can explain that. Basically I would like to know how many concurrent downloads can we handle before we would have to tell a customer that his usecase requires hot file detection. Ofc the answer also depends on the number of segments this file would have. To keep it simple let's say one 64 MB segment and maybe try the same also with different other file sizes like 6 KB or 5 MB. I believe if a customer wants to share 1 GB files we can upload 10 files of that size, measure the distribution over the node population and run some math based on our 64MB test result.
> littleskunk

> It only takes about 11.2 GB to have enough pieces that we are storing on almost all nodes. Unless they start all the downloads at the exact same moment then they are usually at different points in the file and naturally loadbalanced. This should also be easy to experimentally figure out what our upper bounds are on throughput on a single segment.
On get we also return a smaller subset of the total nodes that each segment is stored on, so there is additional capacity that isn't used on a single stream of a single segment.
> jacob

> ((((5 TB) / (64 MB)) * 80) / 14 000) * (2.2 MB) =
982.142857 megabytes
So a 5 TB object has enough pieces that it will probably end up with about a GB stored on every node in the network.
Now obviously there is going to be long tail cutoff so there will in practice actually be a greater concentration on some nodes rather than others.
It feels like we can afford to increase the segment size? The challenge when you do that is you feel the pain of the xth percentile nodes that are selected for the upload.
So might want to increase the total connections established to increase the chance of being able to cutoff more on the long-tail.
Do we actually have anything that is preventing us from experimenting with larger segments sizes? Can repair handle it?
> jacob

> In an interviewer with a customer yesterday they noted they would pay double for more erasure coding to get higher TOTAL throughput when syncing potentially hundreds of nodes in parallel.
> Dominick

If we want to test different reed solomon numbers we should try out `metainfo.rs: 16/23/37/50-256 B`

**Comment by littleskunk** [comment]
First test results from @BlackDuck888 

[performance-improvement-ideas.ods](https://github.com/storj/storj/files/8885715/performance-improvement-ideas.ods)

> He downloaded some old and some new files 10 times each from different locations. This test was without any concurrency. It is just the baseline for future tests. The obversavations so far:
The location seems to have no impact on the download performance. Latency isn't a problem here.
The amount of bytes transfered is insane. Even the slowest node is able to deliver most of the data before long tail cancelation kicks in. This means the transfer would have the same speed even if we would download from less storage nodes to begin with.
The machine he used for downloads was mostly idle. Both sides are not bottlenecked by hardware. We have a bottleneck in our protocol!
Maybe too many context switches? If that would be the case we could throw even fast server CPUs into the mix and the transfer would still be bottlenecked unless we can identify how to reduce the context switches.
Are we able to modify some TCP options? By default a storage node will send just one package first, wait until it gets a confirmation, sends 2 packages next, waits for the next confirmation and so on. By the time the transfer might reach maximum performance the download is already finished because of the small pieces size. A CDN will start with 100 packages by default. That might be too agressive for us but even if we start with just 10 packages the hole transfer should be way faster especially for smaller files.

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/
