### ISSUE TITLE
Optimize listing prefixes

### ISSUE THREAD

**Issue by Erikvv** [storj/storj#4893]
Problem reported by @ifraixedes on Slack https://storj.slack.com/archives/CH6LU8Y64/p1654767867391509?thread_ts=1650560600.034159&cid=CH6LU8Y64

**Describe the feature or problem you'd like to solve**

Listing prefixes is slow. 

```
$ uplink ls sj://satellite/backups/crdb/eu1/2022/
KIND    CREATED    SIZE    KEY
PRE                        06/
PRE                        05/
PRE                        01/
PRE                        03/
PRE                        04/
PRE                        02/
```

This seems to be because the metabase code internally iterates over all objects in the prefix, rather than at the cockroachdb level.

https://github.com/storj/storj/blob/main/satellite/metabase/iterator.go#L140

**Propose a Solution**

Make recursive and non-recursive listing separate code paths or queries. The query/queries for non-recursive listing should take care to skip objects under prefix.

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/

**Comment by amwolff** [comment]
If we moved non-recursive listing logic into CockroachDB, it might be useful to utilize expression indexes to skip keys: https://www.cockroachlabs.com/docs/stable/expression-indexes.html.

**Comment by egonelbre** [comment]
@amwolff I'm not following how it would help non-recursive listing?

**Comment by ifraixedes** [comment]
I confirm that the issue isn't happening anymore.
