### ISSUE TITLE
Clean up pending entries in the billing table

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4894]
Job Storj: 
Any invoices that are not finalized will have pending entries in the billing table that need to be cleaned up.  

TBD
- How frequently we need to run this cleanup?
Every 90 Days

Acceptance Criteria: 
- It would be nice to have a history of unfinalized charges.  Instead of deleting charges, we should add a new entry that offsets the previous entry.

**Comment by AdministratorSupportTeam** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam

https://direct.lc.chat/14201763/

**Comment by shaupt131** [comment]
Pending billing transactions should be accounted for when computing balance.

**Comment by jenlij** [comment]
not a blocker but important!

**Comment by iglesiasbrandon** [comment]
this issue is stale because when we run the finalize invoices command it will mark ALL invoices as finalized regardless of when they were generated.
