### ISSUE TITLE
Investigate and fix watch mode build crashing (npm run dev)

### ISSUE THREAD

**Issue by VitaliiShpital** [storj/storj#4908]
Running `npm run dev`  to watch the files is constantly crashing because it can’t find the `legacy-assets-index` file and developer has to run the `npm run dev` again.

AC:

In package.json, update browsers list field to browsers over the last two years
Update `npm run build` with modern flag

**Comment by mobyvb** [comment]
try updating package.json `dev` command to

```
 "dev": "vue-cli-service build --mode development --watch --modern",
```

**Comment by NiaStorj** [comment]
@VitaliiShpital needs story points

**Comment by NiaStorj** [comment]
@VitaliiShpital needs story points

**Comment by mobyvb** [comment]
fixed with https://github.com/storj/storj/commit/b3f909051a05671510d7ab0c72d61b9076093e82
