### ISSUE TITLE
Bucket Details navigation fix

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4909]
- [x] Bug: bread crumbs from bucket details back to bucket isn't enabled. 
Fix: when I'm in bucket details, I should be able to click the breadcrumb to navigate back to the bucket page

![Image](https://user-images.githubusercontent.com/48924196/174098211-5606c48f-87d7-4e19-9267-d28457f77875.png)

- [x] Bug: NavigationDuplicated error as you cannot access bucket details when already on bucket details
-Fix: remove the bucket details drop down on the bucket details screen

![Image](https://user-images.githubusercontent.com/48924196/174098725-933e111f-cba2-4440-acee-36e5789bc9ec.png)

**Comment by NiaStorj** [comment]
@cam-a please don't forget to add story points. Thanks!
