### ISSUE TITLE
Invalid credentials message

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4910]
When a user tries to login with invalid credentials for a selected satellite, I want to provide an invalid credentials message that hints for the user to try and login on a different satellite.

Figma:https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=13807%3A80416

AC:
- do not include whether an account exists or not in the error message
- we give them a helpful tip to try logging in on a different satellite
- we provide direction to a user that may have not verified their email yet

**Comment by mobyvb** [comment]
There was a discussion recently regarding how much detail to provide in this type of message https://storj.slack.com/archives/CT7F9N1EY/p1656516294338459
I think the design needs to be updated after that discussion before we can work on it. Comment also added in Figma

**Comment by stoweandi** [comment]
Dupe: https://github.com/storj/storj-private/issues/37
