### ISSUE TITLE
Access Grant UI finessing work

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4918]
Pixel perfecting work specified below:

Cards 
- Space between cards - 16px
- Same height for all of them
- Space between buttons - 8px
<img width="1071" alt="Screen Shot 2022-06-17 at 2 48 25 PM" src="https://user-images.githubusercontent.com/40433655/174407630-57c9975f-148c-4456-9c86-c75c22e71dd4.png">

Modal to Create Access:
- Keep the spacing between items 24px
- Delete the line in the bottom, right before the button
<img width="652" alt="Screen Shot 2022-06-17 at 2 44 47 PM" src="https://user-images.githubusercontent.com/40433655/174406526-6d66582e-7ef9-44b6-8403-8673916a6d23.png">

Modal to Encrypt
- When selecting options, the icon becomes blue following the radiobutton 
<img width="574" alt="Screen Shot 2022-06-17 at 3 03 45 PM" src="https://user-images.githubusercontent.com/40433655/174406908-a5ff7e8d-b80a-4f4d-85ab-11b0dc2783f1.png">
as in 
<img width="580" alt="Screen Shot 2022-06-17 at 3 07 09 PM" src="https://user-images.githubusercontent.com/40433655/174407029-d9ba4666-44ee-422a-aaab-890432b3fa87.png">
- The passphrase or input field appears under the option selected, as in this [Figma file](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/?node-id=10277%3A46858):
[Prototype of this interaction]( https://www.figma.com/proto/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?page-id=10277%3A46858&node-id=15049%3A109058&viewport=585%2C-9510%2C0.65&scaling=min-zoom&starting-point-node-id=15049%3A108948&show-proto-sidebar=1)

- Selecting buckets : add blue to checkmark and align middle in the pills 
<img width="356" alt="Screen Shot 2022-06-17 at 2 47 48 PM" src="https://user-images.githubusercontent.com/40433655/174407794-9431a8d2-416a-4741-a663-747b3f53d7bc.png">
<img width="338" alt="Screen Shot 2022-06-17 at 2 47 40 PM" src="https://user-images.githubusercontent.com/40433655/174407796-fba5a5d7-a648-47ba-bbe4-01a170fe6f2c.png">

Modal Access Created
- Font size for the text - 16
- Space between info - 24px
- The copy icon looks distorted. Let me know if you need me to export an SVG file.
<img width="618" alt="Screen Shot 2022-06-17 at 2 48 14 PM" src="https://user-images.githubusercontent.com/40433655/174407878-548d1a92-9805-4c1a-b34d-7db8acaaa377.png">

Mobile version - for the future
-  Navbar becomes a topbar
- Space between buttons inside cards should be at least 8 px
- Treat columns on the table list
<img width="320" alt="Screen Shot 2022-06-17 at 2 58 36 PM" src="https://user-images.githubusercontent.com/40433655/174408091-7f61649a-f2c4-466a-846a-c2646928fe23.png">

**Comment by mobyvb** [comment]
deployed in v1.60
https://github.com/storj/storj/commit/5b550a192cc4d159afec421ce132c34edfa59b3a
https://github.com/storj/storj/commit/1f66bb3931285de2c07924e90b3dbf33efdbafca
