### ISSUE TITLE
Update value attribution command to take filename as an argument

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4929]
Update VA command to take in an additional required argument for the filename the csv should be written to, like

```
satellite reports partner-attribution ./path/to/file.csv yyyy-mm-dd yyyy-mm-dd
```

AC:
* If file exists, the command does not run and notifies the user the file already exists
* If file does not exist, VA writes to a new file with that name
* If `-` is passed in instead of a filename, print to stdout like VA does currently
* Update https://storjlabs.atlassian.net/wiki/spaces/OPS/pages/349044868/Storj+DCS+Customer+Invoice+Generation with the new command (see "value attribution" at the bottom)
* Change `log.Error`s that do not prevent VA from continuing to `log.Warn`s (minor, not related to other changes, but easy)

**Comment by stoweandi** [comment]
We've created a process to run VA in Redash. We no longer need this issue — we can add it back in the future if needed
