### ISSUE TITLE
IX Systems expectations

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4935]
Listed below are items we need to split into tickets. This is mainly a milestone ticket for a specific Partner. 
Due Date, early to mid August. 

-  logo/images on the signup page when using their referral URL

- they want to know when a bucket is attributed to them
> - rclone ls and get all buckets, and see attribution code; we could add attribution code to "get bucket" 
> > Get bucket [user agent] (call it attribution code) "Attribution Code" — only pull ones that look like a giant UUID of one we've assigned (potentially in the partners table—or wherever we store these

Questions for get bucket attribution  
> - Do we need to expose this in the S3 API in order for them to access it?

**Comment by stoweandi** [comment]
Associated tickets:
#4943 
https://github.com/storj/storj-private/issues/41

**Comment by NiaStorj** [comment]
https://www.figma.com/file/Yzgkpah3gDUbVjaqEfJoke/Liv-Labs-(WIP)?node-id=3271%3A287557t
