### ISSUE TITLE
Native token payments UI - see transactions

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4941]
See the "Payment Method > STORJ Tokens" page from this figma design:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=14093%3A98866

Relevant backend code:

Endpoint stubs: https://review.dev.storj.io/c/storj/storj/+/7384
Wallet payments API: https://review.dev.storj.io/c/storj/storj/+/7783
Wallet implementation: https://review.dev.storj.io/c/storj/storj/+/7398

AC (based on figma design): 
* When a user clicks "See transactions" on the STORJ Token card on the payment methods screen (new billing UI), show the STORJ Token payments page linked in Figma above
* The page should show available balance, a QR code, and deposit address
* A table with a list of STORJ token transactions; should include historical coin payments transactions
* The UI should be the same as before if the `native-token-payments-enabled` flag is false
* Split up into multiple commits as needed to avoid very large reviews

**Comment by NiaStorj** [comment]
@cam-a @mobyvb @stoweandi let's discuss getting this into sprint 16 tomorrow.  Durabilty is hoping to have everything wrapped up on their part by the end of sprint 16.

**Comment by mobyvb** [comment]
@NiaStorj Wilfred has already volunteered to start work on this :)

**Comment by shaupt131** [comment]
Hi, I see this is blocked.  Anything we can do to help?

**Comment by wilfred-asomanii** [comment]
Thanks! I'm actually in talks with someone on the durability team about it. I will move it back to "in progress"

**Comment by mobyvb** [comment]
deployed in 1.66 https://github.com/storj/storj/commit/05e57edb20648be95165ce5a366b9473f9537001
