### ISSUE TITLE
Bucket Page > Renaming bucket

### ISSUE THREAD

**Issue by liviolanda** [storj/storj#4944]
When a user wants to Rename a bucket, I want them to click on the "rename bucket" under the "more actions" button on the top right side of the buckets page. 

Figma design:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=23541-320329&t=3v94C3L0LD5S652z-0

**Comment by iglesiasbrandon** [comment]
We do not support renaming buckets fundamentally. Closing this issue.
