### ISSUE TITLE
Bucket Page > Sharing bucket

### ISSUE THREAD

**Issue by liviolanda** [storj/storj#4945]
When a user wants to share a bucket, we want to be able to do it in the web interface. 

AC:
- a user can shar a bucket from the menu inside thee bucket

Figma design for modal:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15174%3A114779

**Comment by stoweandi** [comment]
![Image](https://user-images.githubusercontent.com/48924196/183738846-0aef0d99-7c60-4623-83b2-1c2c9dceafca.png)
![Image](https://user-images.githubusercontent.com/48924196/183738845-51f03b3b-6c80-4f5e-9eb4-14d0a054441b.png)
![Image](https://user-images.githubusercontent.com/48924196/183738844-a884f2e0-b8ff-407c-ac7d-fc04d81d1a9e.png)
