### ISSUE TITLE
Bucket Page > Creating new folder

### ISSUE THREAD

**Issue by liviolanda** [storj/storj#4947]
When a user wants to create a new folder in a bucket, I want them to add a name for the folder in a modal, instead of opening an input field in the table list. 

They'll do it by clicking on the "New folder" button in the top right corner of the page.

Figma design:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15421%3A118590

**Comment by liviolanda** [comment]
moved to https://github.com/storj/storj/issues/4947

**Comment by mobyvb** [comment]
deployed in 1.64 https://github.com/storj/storj/commit/8e3aa4d25b4ac3938b3121b3dc74bcd9fc27bda2
