### ISSUE TITLE
Satellite UI / Download Bucket

### ISSUE THREAD

**Issue by liviolanda** [storj/storj#4948]
When a user wants to download a bucket, I want them to do it easily by clicking on the Download in the "More Actions" button in the top right corner of the page.

AC:
- a user can download a bucket from the menu within a bucket 

Figma design:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=23541-321023&t=3v94C3L0LD5S652z-0

**Comment by mbouzi** [comment]
There is work that needs to be done in linksharing to allow for the download of buckets. The conversation where this solution is discussed: https://storj.slack.com/archives/C0196DNUML0/p1663264705842619?thread_ts=1663260819.601979&cid=C0196DNUML0

**Comment by mobyvb** [comment]
Recent discussion regarding folder/bucket zip download: https://storj.slack.com/archives/C0196DNUML0/p1689226039456439

**Comment by mobyvb** [comment]
Closing this issue - merging with #5645
