### ISSUE TITLE
Low hit rates on object delete

### ISSUE THREAD

**Issue by Erikvv** [storj/storj#4952]
From CockroachDB metrics it seems that the majority of delete operations are on non-existent objects, especially on US1 satellite.

This seems unexpected. I'd like to see if we have some better metrics on this, for example per user-agent.

From cockroach:

| sat | Mean rows/bytes read | Mean rows written |
|---|---|---|
| eu1 |  1.71 / 872.9 B |  0.41 |
| us1 | 0.21 / 115.0 B | 0.07 |
| ap1 | 0.84 / 388.2 B | 0.42  |

**Comment by Fadila82** [comment]
I don't manage to get github to notice my PR mentions this issue, so here it is:
https://github.com/storj/storj/issues/4952

**Comment by Fadila82** [comment]
This does not seem to be the metric we think it is (example deleting only objects that exist):
![image](https://user-images.githubusercontent.com/17983871/177767705-3cc2d66b-4600-498e-a0eb-2d90b60ce3ae.png)

**Comment by Erikvv** [comment]
Does it go up if the object has more segments?

**Comment by Fadila82** [comment]
- It does go up with the number of segments.
- to find the number of NotFound errors, we can go to this dashboard: https://chronograf.datasci.storj.io/sources/3/dashboards/95?tempVars%5Bsatellite%5D=US1&tempVars%5Bkind%5D=success&lower=now%28%29%20-%2024h There is a BeginDeleteObject error rate graph. The error corresponding to "NotFound" is drpc_5.
- The error corresponding to a specific error code can be found in https://github.com/storj/common/blob/main/rpc/rpcstatus/status.go
