### ISSUE TITLE
Switching the satellite on the signup page should pass along query parameters

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4955]
When I go to us1.storj.io/signup?partner=xyz, then use the dropdown to switch to the EU1 satellite, I am taken to eu1.storj.io/signup, without the partner query param at the end.

AC:
Using the dropdown to switch satellites on the signup page should pass query parameter

**Comment by NiaStorj** [comment]
https://www.figma.com/file/Yzgkpah3gDUbVjaqEfJoke/Liv-Labs-(WIP)?node-id=3271%3A287557t
