### ISSUE TITLE
Query Revenue attribution per Bucket

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#4956]
We want to be able to calculate invoiced amounts per bucket that have user agents 
so that Sales has invoiced dollar amounts per user agent with a bucket view breakdown for Partners.

AC:
- Take VA generated csv that contains: _userAgent, projectID, bucketName, gbHours, segementHours, objectHours, hours, gbEgress_ and join with associated tables (projects table and stripe table) to output a calculation of percent of invoice per bucket
- Final query should output a csv that shows: _userAgent, projectID, bucketName, gbHours, segementHours, objectHours, hours, gbEgress, invoiced $ amount per bucket

**Comment by mobyvb** [comment]
todo for me before I want to mark this as done:
copy this query so there are three (ap1, us1, eu1) https://redash.datasci.storj.io/queries/2995/source
all using the [BI] datasource so they do not directly hit the satellite
then, update this query: https://redash.datasci.storj.io/queries/2994/source?p_monthStart=2022-07-01&p_userAgent=rclone
to pull from the three new queries

**Comment by mobyvb** [comment]
related to https://github.com/storj/datascience/issues/192

**Comment by mobyvb** [comment]
replaced by this ticket https://github.com/storj/datascience/issues/248
