### ISSUE TITLE
Bucket deletion is extremely slow for large buckets

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#4957]
We need to investigate why the deletion of bucket with a large number of objects is doing deletes very slow. The problem was reported initially by the customer in https://github.com/storj/customer-issues/issues/127. The bucket with 11M objects was not deleted after 48h. @mniewrzal made attempt to delete it on his own with `uplink ... --force` command and objects were deleted but the speed of this operation was extremely slow, 50k objects deleted after 14h.
![Screenshot from 2022-06-30 19-30-47](https://user-images.githubusercontent.com/7313031/176849243-1bfc2624-c71a-419e-a531-845e5a42ce8c.png)
![Screenshot from 2022-06-30 19-31-02](https://user-images.githubusercontent.com/7313031/176849251-fa023f2a-d1ab-416c-959d-83d1c9a02538.png)

One potential reason for this full table scan for delete queries (see screenshots) but we should investigate if that's the only reason.

**Comment by Erikvv** [comment]
The full scan is no longer in the current prod query plan. I would like to verify that a bucket can now be deleted in reasonable time.

**Comment by Erikvv** [comment]
(wip)

Wrote this benchmark and ran it on eu1 https://link.storjshare.io/s/jvakv4ddjeprfyi6iqcbrgxy5nda/public/delete-bucket-w-objects-benchmark.go

Results:
| batches | objects | time | time/batch | time/obj |
|---|---|---|---|---|
| 1 | 50 | 1,95 s | 1,95 s | 38ms |
 | 20 | 1000 | 25 s | 1,25 s | 25ms |
| 200 | 10.000 | 151 s | 0,755 s | 15ms |
| 2000 | 100.000 | 2359 s | 1,18 s | 23 ms |

I've observed the cockroach dashboard during these last two scenario's and you can see that the time/batch reflects the increasing query execution time. 

At 15ms per object it would still take  46 hours to delete the 11M objects which was the scenario which triggered this ticket.

(test with segment)
(test parallel delete)

Discussed with Michal and decided to add some metrics so we can measure deletion time per object.

**Comment by Erikvv** [comment]
> Discussed with Michal and decided to add some metrics so we can measure deletion time per object.

I am actually not sure how to do this. We already measure execution time using mon.Task() and I thought I could add it there. But a new tag would be too high cardinality, and the extra arguments seem to not end up in InfluxDB. 

I guess I can add a separate counter for number of objects but that would put the execution time and the number of objects in different records.

**Comment by Erikvv** [comment]
Was discussed in standup but we don't really know in metainfo team. Posted an open question in Slack #team-data.

**Comment by Erikvv** [comment]
Discussed with michael that a low-friction solution is to put each batch in a separate function and just record it using `defer mon.Task()(&ctx)(&err)`

**Comment by mniewrzal** [comment]
Verification ticket https://github.com/storj/team-metainfo/issues/119

**Comment by Erikvv** [comment]
With our current DB schema it will always be a heavy long operation.

I it would be good to have a progress indicator on uplink-cli side before we optimize the backend further. Would be nice to get this in a sprint.
