### ISSUE TITLE
Notify users about Billing under My account

### ISSUE THREAD

**Issue by liviolanda** [storj/storj#4962]
When we deploy the change to move "Billing" to under "My Account" (https://github.com/storj/storj/issues/4846), I want to notify the users that a change was made to the interface, and now they can find their "Billing" under "My account".

Figma designs
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15108%3A108760

AC:
- set a flag in local storage when a user sees the notification for the first time.
- if a flag was already set when a user enters the gui, don't show the notification

**Comment by xaresys** [comment]
deployed in v1.63.1
https://github.com/storj/storj/commit/ffd35ecfdcb4fe5d6744c571f8a733426dafd717
