### ISSUE TITLE
Display in the Dashboard the session will expire in 10 min

### ISSUE THREAD

**Issue by liviolanda** [storj/storj#4963]
If the user is inactive for 10 minutes, they will be logged out.
Thread https://storj.slack.com/archives/CT7F9N1EY/p1646069009358269

from https://github.com/storj/team-product/issues/97

**Figma designs**
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15026%3A105979

**Comment by stoweandi** [comment]
Duplicate
