### ISSUE TITLE
Multinode should not ask for an identity to the user

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#4974]
Multinode requires an identity because it connects to the Storagenode through DRPC. 
Uplink does the same but it doesn't require any identity.

Asking to SNOs for an identity for running the multinode creates friction for using it and it seems counterintuitive. Moreover, this identity doesn't require any minimal difficulty, hence, the SNO mostly has to generate one with difficulty 0.

Multinode should do something similar to what uplink does for not requiring an identity. If it has to generate on the fly, we should consider caching/storing it somewhere for avoiding to generate one every time that runs.

**Comment by mniewrzal** [comment]
Acceptance Criteria:
* generate identity on multinode startup if identity flag was not set
* initially we don't need to cache it
* leave identify flag for backward compatibility
