### ISSUE TITLE
Research - current node audit vetting times

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4981]
Questions we have to inform our approach to solving the problem: How do we get new nodes audited mroe quickly to get though the node vetting process? 

- What takes the most time in the node vetting process? the audits? something else?
- How many audits are going to nodes that are not vetted?
- How long does it take nodes to get fully audited for the vetting process with the current number of audit workers we have running per satellite?
    - percentiles, mean, median, mode
    - How many audit workers are running per satellite? 
- Can the vetting criteria be adjusted? 
    - Identity concerns around this

**Comment by jenlij** [comment]
https://redash.datasci.storj.io/queries/2941/source#4683

**Comment by jenlij** [comment]
![Image](https://user-images.githubusercontent.com/12438950/183502504-b417ccdb-e7ab-4253-b179-6080591db203.png)

**Comment by jenlij** [comment]
https://redash.datasci.storj.io/dashboard/vetting?p_FILTER=created_at&p_PERIOD=year

**Comment by jenlij** [comment]
Default: WorkerConcurrency=2
