### ISSUE TITLE
Generated console api - initial openapi generation

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4985]
There is an initial prototype of openapi generation on a Github branch that we need to clean up and move somewhere for code review. This ticket can be marked as done once the code from the demo is merged, even if openapi generation isn't complete.

AC:
* Changes related to openapi generation from the api-generation branch are merged
* Tickets for additional openapi generation tasks are created and put in the team User Growth backlog

**Comment by stoweandi** [comment]
https://storjlabs.atlassian.net/wiki/spaces/PM/pages/2196045827/Send+Node+Status+Emails+via+the+Satellite+or+update+logic+in+c.io

**Comment by mobyvb** [comment]
closing as we do not have any plans to work on this any time soon. We can recreate or reopen this issue if necessary.
