### ISSUE TITLE
Rework satellite webapp to use the Vue3 composition api rather than class components

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#4988]
For now, this is a high-level ticket to track the overall progress of the conversion to Vue3. We should probably add subtasks for specific components so that the work can be divided across more people

* Get rid of classes using property decorators and class components
* Get rid of packages that are not compatible with Vue 3 and replace them
* Rewrite classes to use <script setup>

```
<script setup>
```

AC:
* All components in web/satellite reworked to use the composition api (TODO list)
* create a ticket list under a milestone

**Comment by stoweandi** [comment]
NOTE: assign to someone to create the tickets and split up the work
