### ISSUE TITLE
Update all instances on the satellite & StojScan to use currency.MicroUnit instead of currency.USD

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#4996]
This ticket is the result of the conversation we had in this PR comment: https://review.dev.storj.io/c/storj/storj/+/7841/13/satellite/payments/storjscan/chore.go#83

Acceptance Criteria: 
- We need to update everything to use currency.MicroUnit so that we can get subcent precision. 
- Both on Storjscan and the satellite side.

**Comment by jenlij** [comment]
[tokens: use currency to represent storj and usd values](https://review.dev.storj.io/c/storj/storjscan/+/8313/1)
[tokenprice: update PriceQuote db to use USDDollarsMicro](https://review.dev.storj.io/c/storj/storjscan/+/8274/1)
[tokenprice: update client to return price as currency.Amount](https://review.dev.storj.io/c/storj/storjscan/+/8273/1)
