### ISSUE TITLE
Listing behavior returns inconsistent between CLI and web

### ISSUE THREAD

**Issue by jtolio** [storj/storj#4997]
Customer report:
> when I can get the s3 command line client to return results, I get a list that differs from what is returned via the storj web app. screenshots (highlighting one example not returned, but there are many). this is probably related and maybe the storj web client is timing out and returning and some results are missed before sorting and showing? but in case it is surprising I wanted to report it
<img width="531" alt="Screen Shot 2022-07-21 at 11 38 08 AM" src="https://user-images.githubusercontent.com/109603/180293969-5c070e39-2603-447e-9372-a805ca320f6d.png">

![Screen Shot 2022-07-21 at 11 37 33 AM](https://user-images.githubusercontent.com/109603/180294101-01d60199-58f7-4ad0-811d-be2f66b9bacb.png)

**Comment by jtolio** [comment]
customer says:
>  oh, the aws commandline result isn’t sorted, that’s me piping it through sort to be able to compare the two

**Comment by jtolio** [comment]
CLI output created via:

```
aws s3api list-objects-v2 --endpoint-url "https://gateway.us1.storjshare.io/" --bucket <bucket> --prefix 'phones/' --delimiter '/' --output text
```

**Comment by mniewrzal** [comment]
Can we ask the customer about the number of items in this prefix?

**Comment by mobyvb** [comment]
I tried to reproduce it in a local environment to try to figure out if there's something in the satellite that could cause the issue. I ran this script

```
#!/bin/bash
start=1
end=1000
for((i=$start;i<=$end;i++))
do
    mkdir "folder${i}"
    touch "folder${i}/file.txt"
done
```
then uploaded the whole folder via the file browser in storj-up. When looking at the view of all the folders - the same part of the UI from the screenshot shared by the customer - all 1000 appeared on the same page, in the correct ordering. No pagination or anything.

I know it's not super helpful, but thought I'd share my experiment here.

**Comment by mobyvb** [comment]
Cc @NiaStorj

**Comment by iglesiasbrandon** [comment]
this issue is stale, if this comes up we will open a new issue or reopen this one.
