### ISSUE TITLE
Get a local install of Rucio working with Storj

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#5017]
### Description:
We want to get a local install of Rucio working with a Rucio Storage Element (RSE) that uploads/downloads/syncs to Storj.

If there is a low-effort out-of-the-box solution that would work for potential users, document the process for setting it up and share it in the [#dirac-boosty-internal](https://storj.slack.com/archives/C03DHTV5CDD) Slack channel.  If the solution is not relatively straightforward, document your findings, notify me, and we will create a follow-up ticket to further optimize.  

### Links:
All relevant information and links should be here: [Edge Rucio](https://docs.google.com/document/d/1VmtsUiFfBNRaw_QrAbeokTW-dExsJ3i94sTkWQxsPQo/edit
)

### Acceptance Criteria:
A working local installation of Rucio that uploads/downloads/syncs to Storj
A "how-to" document detailing how to set it up

**Comment by pwilloughby** [comment]
### Configuring Rucio with Storj
Rucio is working on s3 documentation https://github.com/rucio/rucio/issues/5450 Their draft instructions https://docs.google.com/document/d/1ofV5iIgpCKCnANNuqIavN_6FvvMTE6QPtQKK_n1P3SE/ work with storj.

#### Setup a demo environment see https://rucio.cern.ch/documentation/setting_up_demo/
```console
git clone https://github.com/rucio/rucio
cd rucio
docker-compose --file etc/docker/dev/docker-compose.yml up -d
docker exec -it dev_rucio_1 /bin/bash
```

#### init the database
```console
tools/run_tests_docker.sh -i
```
#### update the ca-certificates package
```console
# the image has python3 linked in /usr/bin/python but yum requires python2
# one workaround is to change the first line of /usr/bin/yum and /usr/libexec/urlgrabber-ext-down
# to use /usr/bin/python2
yum update ca-certificates
```
#### configure the storj RSE
```console
# replace YOUR_BUCKET_NAME with your storj bucket
rucio-admin rse add STORJ
rucio-admin rse add-protocol --hostname gateway.storjshare.io --scheme https --port 443 --prefix YOUR_BUCKET_NAME --impl rucio.rse.protocols.gfal.NoRename --domain-json '{"wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy_read": 1, "third_party_copy_write": 1}, "lan": {"read": 1, "write": 1, "delete": 1}}' STORJ
rucio-admin rse set-attribute --rse STORJ --key sign_url --value s3
rucio-admin rse set-attribute --rse STORJ --key skip_upload_stat --value True
rucio-admin rse set-attribute --rse STORJ --key verify_checksum --value False
rucio-admin rse set-attribute --rse STORJ --key strict_copy --value True
```
#### create rse-accounts.cfg 

```console
# get your rse_id
rucio-admin rse info STORJ

# use your rse_id and keys below
cat >> etc/rse-accounts.cfg <<EOL
{
    "YOUR_RSE_ID": {
        "access_key": "YOUR_ACCESS_KEY",
        "secret_key": "YOUR_SECRET_KEY",
        "signature_version": "s3v4",
        "region": "us-east-1"
    }
}
EOL
```
#### Upload and Download a file
```console
rucio upload --rse STORJ --scope archive tools/test.file.1000
rucio download archive:test.file.1000
```

**Comment by ferristocrat** [comment]
@ferristocrat - add doc (from above comment) to https://docs.storj.io/dcs/how-tos/

**Comment by ferristocrat** [comment]
@pwilloughby - Question came up regarding the use of the the [gfal protocol](https://github.com/rucio/rucio/blob/master/lib/rucio/rse/protocols/gfal.py ) - can you give a quick synopsis of why this was chosen and what it's doing?

**Comment by pwilloughby** [comment]
gfal was chosen because s3boto was recently removed and the draft rucio doc suggested using it to support s3. gfal is used to send requests like get, put, delete, rename, and copy to the RSE.

**Comment by ferristocrat** [comment]
I updated the draft doc with that info. Thanks @pwilloughby !
