### ISSUE TITLE
Satellite UI: New billing screen bug fixes

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5018]
- By default the page is empty. I have to select one of the tabs. Maybe open the overview tab by default?
- I have a test credit card in place but the payment method view doesn't show it.
- Coupon show "$$1.65". So we add one addition dollar sign somewhere.
- The coupon expires "January 1, 1970" (this is a 100% off stripe coupon which never expires)

AC: 
* Overview should be visible when first navigating to billing page
* A previously added credit card should be visible when first navigating to the "payment methods" tab
* A double dollar sign should not appear for coupon quantity. Some coupons are also percentage-based, so the current page would show something like $50% off for one of these
* A coupon that does not have an expiration date should not show an expiration date in the UI. See https://stripe.com/docs/billing/subscriptions/coupons#coupon-duration - I (moby) believe that the old billing page handled the different types of coupon duration. @xaresys (Jeremy) would likely know more about this

**Comment by stoweandi** [comment]
duplicate
