### ISSUE TITLE
Satellite console API: Rework "unauthenticated" handling

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5022]
Right now, there is a function called `withAuth` which the console server uses to determine whether an `http.Request` is authenticated. If there is an error during authentication, it is passed to the service layer via a context variable. The service layer is then expected to properly handle the authentication layer.

It would be preferable if the authentication was designed in a way so that the service layer can always assume that the request is authenticated.

AC:
* "unauthenticated" error is sent to the client _before_ any service-level logic specific to the particular endpoint is called
* `withAuth` error is not passed via a context

**Comment by xaresys** [comment]
deployed in v1.63.1
https://github.com/storj/storj/commit/5f6892f95c93e38300681fd5b2fc4c2647079ff2
