### ISSUE TITLE
Coupon edits for the new billing page in QA

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5026]
(In QA) Coupon page issues:

- There's an extra "$" sign next to the coupon amount. Coupon show "$$1.65". So we add one addition dollar sign somewhere
- font is displaying as serif, instead of sans serif
- "c" in Coupon is not capitalized 
- change "coupons" to singular "Coupon"
- The coupon expires "January 1, 1970" (this is a 100% off stripe coupon which never expires). A coupon that does not have an expiration date should not show an expiration date in the UI. See https://stripe.com/docs/billing/subscriptions/coupons#coupon-duration - I (moby) believe that the old billing page handled the different types of coupon duration. @xaresys (Jeremy) would likely know more about this

AC:
- removed the extra dollar sign
- update font to not be serif but sans serif
- Capitalize the "c" in coupon, so that it's header is "Coupons"
- A coupon that does not have an expiration date should not show an expiration date in the UI

![Image](https://user-images.githubusercontent.com/48924196/182238032-6310a0c7-d441-41da-8e22-784aef0ddbd6.png)

![Image](https://user-images.githubusercontent.com/48924196/182237773-fed2588e-1a3d-4a64-a369-be1f71510d0e.png)

**Comment by cl-mitch** [comment]
All AC's are complete and on branch BillingScreenBugFixes
