### ISSUE TITLE
Remove individual project buttons from new Billing UI

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5028]
in QA, on the Overview tab of the new billing ui, 
We want to remove the individual "Edit Payment" and "See Payment" buttons from the individual project components since we can't set individual payment methods per project. We want to move the two buttons below the "Cost per Project" header

![Image](https://user-images.githubusercontent.com/48924196/182241415-7c5b95a2-f753-4015-8df7-cacfbc81ebd0.png)

![Image](https://user-images.githubusercontent.com/48924196/182241439-65f35319-8152-4dfe-8bb0-6ef093c5391f.png)

![Image](https://user-images.githubusercontent.com/1323312/181835855-da8c54b7-d24b-497e-8467-bd42a3c7955c.png)

**Comment by mobyvb** [comment]
this is fixed in qa now. New billing screen is not in production yet, but the bug is fixed
