### ISSUE TITLE
Investigate complexity of supporting Server-side copy in the Object browser

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5030]
We want to enable the possibility of renaming a bucket in the UI. 

AC:
- determine what code changes would need to be done in order to support server-side copy in the object browser (e.g. via the gateway)
- make tickets for this task

**Comment by wilfred-asomanii** [comment]
I've found there's no direct way to rename buckets using the AWS SDK
The `objectCopy` function of the SDK could work but that’ll require looping over all objects in a bucket and copying them over to a new bucket and deleting them from the old one afterward. This may not be a desired solution.
Object rename and copy however, are straightforward.

PS: The AWS SDK support creating a batch job to perform long running copy operations such as "renaming" buckets. But this also may not be the way to go for us.
