### ISSUE TITLE
Investigation: User has the ability to change their email address

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5040]
We want to think through what the implications of enabling users to change their email, so that we know the effects it will have on our system and integrations 

Current process according to @heunland :
> the email verification is as follows: We ask the current user to make a helpdesk account in zendesk with the same email they used on the account, this shows that they have control of this email address. We also ask the owner of the new email address to make a helpdesk account and confirm they agree that the account is changed to that email. After prod owner is done with changing the email on the account, we also change it on stripe, and then delete the helpdesk account from the old email that is no longer needed.

The new email needs to get verified before the switch is complete. If possible, we need to change the email for the user on Stripe as well. Otherwise we need to describe what the process should be for notifying Support that the email address needs to be updated in Stripe.

AC:
- list out discovered implications of when a user's email changes
    - how does it impact marketing? (even for users who have already changed their email)
    - how does it impact billing?
- propose solutions for implications 
- determine if any designs will be necessary

**Comment by mobyvb** [comment]
**Hubspot**:

Looks like there are a couple ways:

* [Add additional email address to contact, then switch that to their primary email](https://www.webdew.com/kb/multiple-email-addresses)
* [Delete existing contact and add with new email](https://community.hubspot.com/t5/CRM/I-can-t-edit-my-contact-s-email-address/m-p/30777) (ew)

The link for adding a new email and switching to primary goes through the manual steps, but we would need to investigate if we can do this in an automated way using the Hubspot API

**Segment**:
Segment is not unique on email address, so it should be pretty easy to update it here

**Billing (Stripe):**
Should be easy enough to update email in Stripe with the [customer update endpoint](https://stripe.com/docs/api/customers/update)

Stripe has its own customer ID, which will not change if email does.

**Potential issues**

* If Hubspot does not make it easy to programatically change a customer's email, this process would need to be manual. At the very least we would want to figure out how to turn off Hubspot emails to the old address automatically
  * Even with an "automatic" process, it would be multi-step for Hubspot (add new email, then switch to primary). More points for failure
* Recovering from failure of some of these email changes succeeding but not others would be tricky. We may want to ensure we have clear logs indicating which "email changes" succeeded and which ones failed - that way we could identify and debug any issues that occur

**Next steps**

I think a light design might be useful, but not totally necessary. The most important part is we should make sure this behavior is feature-flagged, so we can adequately QA it before turning it on in production. If there is a feature flag, we can do the bulk of the work that we know how to do, and figure out the weird edge cases later (e.g. changing Hubspot email)

**Comment by mobyvb** [comment]
Hubspot information
From @wilfred-asomanii 

> looks like [this API](https://legacydocs.hubspot.com/docs/methods/contacts/update_contact-by-email) can be used to update an email address on hubspot.

from @VitaliiShpital 

> yeah, it says
> Email address - It is possible to update the email address of contacts using this endpoint. The current email address must be used in the URL to identify the existing contact in HubSpot, and the new email would go in the JSON in the request body.

**Comment by mobyvb** [comment]
More notes:
* Changing email in Stripe is essential
* Changing email in Segment and Hubspot is good, but it's not the worst thing in the world if those fail - it would potentially affect our analytics/marketing, but it wouldn't break the product. Email changing is also probably pretty infrequent, so most users would not be affected regardless

**Comment by mobyvb** [comment]
created implementation ticket here: https://github.com/storj/storj/issues/5692
But it probably needs to be split up into several tickets, and needs grooming by the team
