### ISSUE TITLE
rclone and uplink intermittent transfer issue #emergency-2022-04-15-uplink-multipart-issue-eu1

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5041]
The original request (see the linked zendesk ticket):

using same access key, I have uploaded some files from Linux VPS to storj network using uplink.However, I can not download those files using Filezilla in my Windows Laptop. I can see the files but the size show zero, also I got below error messages:1) for a small file i got this error:Error:  download failed receiving data: metainfo error: Used uplink version cannot download multipart objects.Error:  File transfer failed2) for a large file (~119MB) i got below error:Error:  download failed receiving data: object not found: segment not found: segment missingError:  File transfer failedany idea to solve above error so i can download my files?

I was able to reproduce:

- Upload files using uplink or rclone
```
$ rclone copy Пленка/denj_programmista_POWT.avi eu-gw-mt:images/Пленка/ -P -vv
$ rclone version
rclone v1.58.0
- os/version: ubuntu 20.04 (64 bit)
- os/kernel: 4.4.0-19041-Microsoft (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.17.8
- go/linking: static
- go/tags: none
```
- In the FileZilla free (native integration) 3.58.0 (or FileZillaPro 3.58.1 and native integration) this file has 0 size
![image-20220415-210152](https://user-images.githubusercontent.com/7313031/182551828-0152e80f-7aff-4c70-a6ec-f2f3c74f9d8c.png)
- Trying to download this file with FileZilla free (native integration) throws an error:
```
Error:	download failed receiving data: object not found: segment not found: segment missing
Error:	File transfer failed
```
- Checking existence of the file (eu-gw-mt connection is configured using eu1 satellite with GW MT [gateway.eu1.storjshare.io](http://gateway.eu1.storjshare.io/), eu is configured using native connector):
```
$ rclone ls eu-gw-mt:images/Пленка/denj_programmista_POWT.avi
292894910 denj_programmista_POWT.avi

$ rclone ls eu:images/Пленка/denj_programmista_POWT.avi
292894910 denj_programmista_POWT.avi

$ uplink ls sj://images/Пленка/denj_programmista_POWT.avi
2022/04/16 00:48:41 failed to sufficiently increase receive buffer size (was: 160 kiB, wanted: 2048 kiB, got: 320 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
KIND    CREATED                SIZE         KEY
OBJ     2022-04-16 00:38:12    292894910    denj_programmista_POWT.avi
```
- The file can be downloaded with uplink or rclone.

If we would use a FileZillaPro 3.58.1 and GW MT - the file has a normal size and can be downloaded without issues

![image-20220415-205724](https://user-images.githubusercontent.com/7313031/182551824-8a9f5112-1fb4-41df-9dcf-08492ca8ecad.png)

If we upload the same file with uplink , the file in FileZilla free will have 0 size too.
```
$ uplink version
Release build
Version:            v1.52.2
Build timestamp:    04 Apr 22 20:14 +04
Git commit:         bfc3d4c9d51d1b3e5ed0acbb74f8e01b7421ebf0

PATH                VERSION
storj.io/storj      (devel)
storj.io/common     v0.0.0-20220328200721-dd5c8642e8cf
storj.io/drpc       v0.0.30
storj.io/private    v0.0.0-20220323114243-08c4b5e752f4
storj.io/uplink     v1.8.2-0.20220328201716-2ca4df442232
```

The parallel issue - when I tried to reproduce, I meet the problem when the rclone was stuck in uploading these three files. Even if I deleted them and tried to upload back - the rclone always stuck on the same percentage level, i.e.
```
Transferring:
 *                Пленка/VID_20210303_193539.mp4: 85% /300.289Mi, 132/s, 97h5m26s
 *             Пленка/denj_programmista_POWT.avi: 91% /279.326Mi, 132/s, 51h7m27s
 *                Пленка/VID_20200422_225848.mp4: 47% /533.532Mi, 141/s, 569h47m54s
```
And sat here forever. They were visible in uplink ls --pending and aws --profile eu1 s3api list-multipart-uploads --bucket images too, in FileZilla they have had 0 size (but now I think, that I saw a previously uploaded objects, while the new upload of the same files was stuck. If files doesn’t exist yet, then FileZilla is unable to show them until upload is completed).

The rclone connector is configured like this:
```
[eu-gw-mt]
type = s3
provider = Other
access_key_id = ***
secret_access_key = ***
endpoint = https://gateway.eu1.storjshare.io
acl = private
bucket_acl = private
chunk_size = 64Mi
```

Then suddenly the upload started to work after approximately 2 hours of attempts.

This problem is started to happen since this message (maybe a little bit earlier):
https://storj.slack.com/archives/C8XV676QJ/p1650035843025559
https://storj.slack.com/archives/C03BLP56S93/p1650054973511099

Blocks: https://storjlabs.atlassian.net/browse/USR-2021

Moved from https://storjlabs.atlassian.net/jira/software/projects/FIRE/boards/60?selectedIssue=FIRE-147

**Comment by mniewrzal** [comment]
Comments:
```
Michal Niewrzal 
25 04 2022 12:17
Most probably the issue is related to old version of libuplink used to build Filezilla. We are waiting for a response from them about the used libuplink version.

Aleksey Leonov 
16 04 2022 08:06
If we upload files with uplink 1.43.1, these files can be downloaded by actual FileZilla free (3.58.0).
```

**Comment by mniewrzal** [comment]
So far its very hard to get any answer about used libuplink version from Filezilla. Karl tried to ask but they were not able to answer which version of libuplink FileZilla free is using . After some investigation it's rather sure its an old version which will cause issues like described in the ticket.

**Comment by iglesiasbrandon** [comment]
It looks like this issue has become stale. I am closing it for now.
