### ISSUE TITLE
Test uplink list performance

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5045]
https://review.dev.storj.io/c/storj/storj/+/8043

Test results from a long time ago looks more like we have an exponential slow down. Doubling the number of objects in a bucket increased the time needed to list them more than we would expect. That means even after this code change we might still have an exponential growth in list timings for bigger buckets.

**Comment by iglesiasbrandon** [comment]
this issue is stale, if this comes up we will open a new issue.
