### ISSUE TITLE
Track signup captcha scores in database

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5067]
I want the captcha score for a successful signup to be stored with the user in the database so that we have visibility into users which were likely created with scripts.

A failure to complete a captcha challenge results in a failed signup. However, it is possible for a captcha challenge response to "pass" while still being suspicious. The score is returned to the backend via the captcha "siteverify" endpoint.

AC:
* Add `signup_captcha` column to the `users` table in the satellite database
* Populate the new column during signup, if captcha is enabled on the satellite
* Send signup captcha score to Segment via the Track Create User call

**Comment by stoweandi** [comment]
@mobyvb can we verify with @adaRn that these scores are aligning with the data he's getting so that we know we don't have any false positives? We ultimately want to verify that this is a good indicator

**Comment by mobyvb** [comment]
@stoweandi yeah, once the scores are in the DB and Segment, it should be really easy to compare the captcha scores against the list of users @adaRn has. We just need to sync once the data is available.
