### ISSUE TITLE
when trying to setup network I get error

### ISSUE THREAD

**Issue by SideRocketeer0** [storj/storj#5068]
this is the entire error message:

Unrecoverable error	{"error": "CA certificate and/or key already exists, NOT overwriting!", "errorVerbose": "CA certificate and/or key already exists, NOT overwriting!\n\tmain.cmdNewService:121\n\tstorj.io/private/process.cleanup.func1.4:372\n\tstorj.io/private/process.cleanup.func1:390\n\tgithub.com/spf13/cobra.(*Command).execute:852\n\tgithub.com/spf13/cobra.(*Command).ExecuteC:960\n\tgithub.com/spf13/cobra.(*Command).Execute:897\n\tstorj.io/private/process.ExecWithCustomConfigAndLogger:93\n\tstorj.io/private/process.ExecWithCustomConfig:75\n\tstorj.io/private/process.Exec:65\n\tmain.main:84\n\truntime.main:250"}
Error: identity/storagenode/0 failed: exit status 1

and this is the command I used:
storj-sim network setup --postgres=postgres://postgres@localhost/teststorj?sslmode=disable

I've been stuck on this for far too long and I haven't got past the network setup phase which is quite embarrassing any help would be appreciated!

**Comment by profclems** [comment]
Hi @SideRocketeer0, looks like you've already run `storj-sim network setup`. You need to run `storj-sim network destroy` to destroy and clean up the network if it already exists before running `storj-sim network setup` again:

```sh
storj-sim network run
storj-sim network setup --postgres=postgres://postgres@localhost/teststorj?sslmode=disable
storj-sim network run
```

See https://github.com/storj/storj/wiki/Test-network on how to run `storj-sim` for testing.
