### ISSUE TITLE
Satellite GUI: AB new varieties of "Upgrade" banner

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5075]
We want to implement a new Upgrade banner. We also want to AB test the banner to see what performs better:
- AB test metric: users adding their credit card aka upgrading to pro 

Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15026%3A109892

Here is an example of some previous abandoned AB testing work
https://review.dev.storj.io/c/storj/storj/+/5170
https://review.dev.storj.io/c/storj/storj/+/3799
(look at both, they are two different approaches)

AC:
- make it possible to get a version of the banner to AB test via Flagship in the satellite — this should be using the user email or id
- display the banner in the UI according to flagship 
- when the upgrade button is clicked on each banner, trigger a "hit"  for the banner on flagship

**Comment by stoweandi** [comment]
Larger story points  per first AB test

**Comment by mobyvb** [comment]
available as of 1.67 https://github.com/storj/storj/commit/4edef9e05c49a7a5c73a788f8797f117e13a8cb0
deployed in QA, but not configured for prod yet. We can set these configs whenever we want.
