### ISSUE TITLE
Design Doc: Project passphrase in satellite UI

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5082]
This figma design moves the encryption passphrase dialog from the bucket-level to the project-level in the satellite UI:
https://www.figma.com/file/9AkyC4G87MeKoUiH4yvtlm/In-Progress?node-id=14541%3A174770#225117846

Acceptance Criteria:
* Write a design document that outlines the technical steps necessary for implementing the project passphrase figma design
* Create tickets for these tasks and put them in the UG Backlog or Todo statuses. These tickets should each have acceptance criteria

**Comment by iglesiasbrandon** [comment]
We had a design sync on Tuesday 8/30 to review and provide feedback. The product design team is itterating on designs based on the feedback.

**Comment by mobyvb** [comment]
Blueprint is ready for review https://review.dev.storj.io/c/storj/storj/+/8350
It can be revised if needed once Figma designs are ready

**Comment by mobyvb** [comment]
We have begun implementation with #5280, which currently has a wip change at https://review.dev.storj.io/c/storj/storj/+/8780
