### ISSUE TITLE
Put back feature flag controlling whether repair feeds info to the audit/reputation system

### ISSUE THREAD

**Issue by thepaul** [storj/storj#5089]
See #4939.

Updates to the reputation table are taking up too much of our database resources. The vast majority of the input for these updates comes from the repair subsystem.

We need to put back the feature flag controlling whether repair feeds info to the audit/reputation system. This way, we can turn off the extra input on _some_ repair workers and leave it enabled on others, letting us scale up and down between "all possible info goes to reputation & db load is as high as possible" versus "only audit information goes to reputation & db load is as light as possible".

**Comment by mobyvb** [comment]
https://review.dev.storj.io/c/storj/storj/+/8985

**Comment by mobyvb** [comment]
deployed in 1.69.1 https://github.com/storj/storj/commit/3501656e98c5fa1592b77edc6d0f84abb9544da6
