### ISSUE TITLE
Satellite UI: Update common table component in browser/FileEntry.vue to use the common TableItem component for rows

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5090]
Followup change for https://github.com/storj/storj/issues/4991, which implemented the common table component in the file browser.

AC:
* TableItem.vue component should be used rather than `<tr>` inside `FileEntry.vue`
* remove bootstrap styling from this component

**Comment by lizzythomson** [comment]
Currently there is Vue2 to Vue3 migration in process and due to needing to refactor the TableItem to be able to integrate it in with FileEntry, this issue will be simpler to refactor only once. As such we are waiting until the Vue3 refactor to also implement this issue.

**Comment by mobyvb** [comment]
1.70 https://github.com/storj/storj/commit/66b4509276ff31
