### ISSUE TITLE
Storj test network

### ISSUE THREAD

**Issue by SideRocketeer0** [storj/storj#5091]
I am running or trying to run a test network inside a VM with an ubuntu OS and I think I have not given it enough memory space.

when I run "storj-sim network run" I don't get any results, this is what I get, no keys:
redis/0                                   21:14:54.702 | 16412:C 18 Aug 2022 21:14:54.702 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis/0                                   21:14:54.704 | 16412:C 18 Aug 2022 21:14:54.704 # Redis version=6.0.16, bits=64, commit=00000000, modified=0, pid=16412, just started
redis/0                                   21:14:54.704 | 16412:C 18 Aug 2022 21:14:54.704 # Configuration loaded
redis/0                                   21:14:54.705 | 16412:M 18 Aug 2022 21:14:54.705 * Increased maximum number of open files to 10032 (it was originally set to 1024).
redis/0                                   21:14:54.708 | 16412:M 18 Aug 2022 21:14:54.708 * Running mode=standalone, port=10004.
redis/0                                   21:14:54.709 | 16412:M 18 Aug 2022 21:14:54.709 # Server initialized
redis/0                                   21:14:54.711 | 16412:M 18 Aug 2022 21:14:54.711 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis/0                                   21:14:54.712 | 16412:M 18 Aug 2022 21:14:54.712 * Ready to accept connections
multinode/0                               21:14:54.827 | INFO	process/exec_conf.go:299	Configuration loaded	{"Location": "/home/daniel/.local/share/storj/local-network/multinode/0/config.yaml"}
                                                       | INFO	process/tracing.go:72	Anonymized tracing enabled
multinode/0                               21:14:54.828 | DEBUG	tracing collector	monkit-jaeger@v0.0.0-20220726162929-c3a9898b5bca/udp.go:140	started
multinode/0                               21:14:54.835 | DEBUG	db	multinodedb/database.go:72	Connected to:	{"db source": "file:/home/daniel/.local/share/storj/local-network/multinode/0/master.db?_journal=WAL&_busy_timeout=10000"}
multinode/0                               21:14:54.839 | INFO	db	migrate/versions.go:216	Database Created	{"version": 0}
multinode/0                               21:14:54.859 | DEBUG	servers	lifecycle/group.go:100	started	{"items": ["console:endpoint"]}
versioncontrol/0                          21:14:54.874 | INFO	process/exec_conf.go:299	Configuration loaded	{"Location": "/home/daniel/.local/share/storj/local-network/versioncontrol/0/config.yaml"}
                                                       | INFO	process/tracing.go:72	Anonymized tracing enabled
versioncontrol/0                          21:14:54.876 | DEBUG	tracing collector	monkit-jaeger@v0.0.0-20220726162929-c3a9898b5bca/udp.go:140	started
versioncontrol/0                          21:14:54.877 | DEBUG	process/debug.go:37	debug server listening on 127.0.0.1:12009
versioncontrol/0                          21:14:54.879 | DEBUG	versioncontrol/peer.go:175	Setting version info.	{"Value": "{\"Satellite\":{\"major\":0,\"minor\":0,\"patch\":1},\"Storagenode\":{\"major\":0,\"minor\":0,\"patch\":1},\"Uplink\":{\"major\":0,\"minor\":0,\"patch\":1},\"Gateway\":{\"major\":0,\"minor\":0,\"patch\":1},\"Identity\":{\"major\":0,\"minor\":0,\"patch\":1},\"processes\":{\"satellite\":{\"minimum\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"suggested\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"rollout\":{\"seed\":\"0000000000000000000000000000000000000000000000000000000000000001\",\"cursor\":\"\"}},\"storagenode\":{\"minimum\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"suggested\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"rollout\":{\"seed\":\"0000000000000000000000000000000000000000000000000000000000000001\",\"cursor\":\"\"}},\"storagenode-updater\":{\"minimum\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"suggested\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"rollout\":{\"seed\":\"0000000000000000000000000000000000000000000000000000000000000001\",\"cursor\":\"\"}},\"uplink\":{\"minimum\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"suggested\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"rollout\":{\"seed\":\"0000000000000000000000000000000000000000000000000000000000000001\",\"cursor\":\"\"}},\"gateway\":{\"minimum\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"suggested\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"rollout\":{\"seed\":\"0000000000000000000000000000000000000000000000000000000000000001\",\"cursor\":\"\"}},\"identity\":{\"minimum\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"suggested\":{\"version\":\"v0.0.1\",\"url\":\"\"},\"rollout\":{\"seed\":\"0000000000000000000000000000000000000000000000000000000000000001\",\"cursor\":\"\"}}}}"}
versioncontrol/0                          21:14:54.881 | INFO	versioncontrol/peer.go:281	Versioning server started.	{"Address": "127.0.0.1:12000"}
satellite-migration/0                     21:14:56.588 | INFO	process/exec_conf.go:299	Configuration loaded	{"Location": "/home/daniel/.local/share/storj/local-network/satellite/0/config.yaml"}

it then just goes on repeat of this and other debug messages:

storagenode/3                  12NvkHV5mr 21:42:10.347 | DEBUG	orders	orders/service.go:176	sending	{"Process": "storagenode"}
storagenode/3                  12NvkHV5mr 21:42:10.347 | DEBUG	orders	orders/service.go:188	no orders to send	{"Process": "storagenode"}
satellite-core/0                          21:42:15.948 | DEBUG	core-zombie-deletion	zombiedeletion/chore.go:80	deleting zombie objects
satellite-core/0                          21:42:15.950 | DEBUG	core-expired-deletion	expireddeletion/chore.go:79	deleting expired objects
satellite-core/0                          21:42:25.947 | DEBUG	core-zombie-deletion	zombiedeletion/chore.go:80	deleting zombie objects
satellite-core/0                          21:42:25.950 | DEBUG	core-expired-deletion	expireddeletion/chore.go:79	deleting expired objects

sorry if this has already been answered i could not find it in the community page, like i said i think this may be because i have not assigned enough memory to the VM. Or is it something I need to do with the redis server?

**Comment by iglesiasbrandon** [comment]
hey @SideRocketeer0, apologise; it looks like this ticket was lost, and we did not respond in a timely manner. 
are you still having problems with this? if so we recommend using https://github.com/storj/up
