### ISSUE TITLE
Hide Bucket guide - make guide disabled on clicking "OK" button , not on “I understand…” 

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5094]
we set flag to local storage not when click on “OK” button , but when click “I understand…”
see video

https://user-images.githubusercontent.com/14928042/185956974-e6f5537a-5fbe-4636-b560-6b83936be4ba.mp4

**Comment by littleskunk** [comment]
I agree with Andrii. The Ok button is maybe too much of an eye catcher compared to the tiny link. The first time the message was displayed I didn't understand that this is a choice. In other places we use links mainly for reading documentation so I wouldn't expect an action pressing it. Is there a better way to visualize it? Maybe a checkbox? That might draw my attention and be more self explaining for the user.

**Comment by mobyvb** [comment]
deployed in 1.64 https://github.com/storj/storj/commit/b60c3ea0a151fccb158f3f6207957fae2a819d1f
