### ISSUE TITLE
New Billing - Request “billing-history” return BALANCE history , not BILLING history

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5097]
Bug: 
The billing history table is not displaying the correct data or styling. 

Acceptance Criteria: 
- The billing history table must be properly styled
- all columns of the billing history table must have the correct values 
- ensure the call to /billing-history endpoint is filtered per correctly per tab on the page

<img width="805" alt="Screenshot 2022-08-19 at 16 59 08" src="https://user-images.githubusercontent.com/14928042/185958159-6e092292-9394-4494-b962-736637a5abb4.png">

![Image](https://user-images.githubusercontent.com/5313116/188715472-a974e177-25a2-4096-a16f-7d0e26603937.png)

**Comment by wilfred-asomanii** [comment]
After investigating, it's confirmed that the data from /billing-history is correct and is filtered properly on the Billing history tab. The table styling has been fixed [here](https://review.dev.storj.io/c/storj/storj/+/8457)

**Comment by mobyvb** [comment]
deployed in 1.65 https://github.com/storj/storj/commit/d6c7aa929026ba7d5b41153c560693ded90fa2f2
