### ISSUE TITLE
Objects cannot be downloaded after move operation

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5099]
@joshdougall  reposrted the after doing move operation on prefix he cannot download some of move objects. Not all object are broken, just some of them.
Error:
```
<Error>
<Code>InternalError</Code>
<Message>We encountered an internal error, please try again.: cause(uplink: eestream: failed to download stripe 0: error retrieving piece 04: file does not exist error retrieving piece 06: file does not exist error retrieving piece 100: file does not exist error retrieving piece 108: file does not exist error retrieving piece 11: file does not exist error retrieving piece 17: file does not exist error retrieving piece 37: file does not exist error retrieving piece 54: file does not exist error retrieving piece 59: file does not exist error retrieving piece 88: file does not exist error retrieving piece 93: file does not exist)</Message>
<Key>shows/<censored></Key>
<BucketName>cody</BucketName>
<Resource>/cody/shows/<censored></Resource>
<RequestId>170DB10EEF0D542F</RequestId>
<HostId/>
</Error>
```
Command:
`uplink mv sj://media/cody/shows/ sj://cody/shows/ --recursive`

We tried to move one of broken objects back to its original location but that didn't help and object still cannot be downloaded.
Some observation that I was able to do:
* entry in `objects` table looks to be intact and correct
* all object segments are in `segments` table
* `file does not exist` error most probably implies that pieces were deleted from SN but not from satellite DB.

**Comment by mniewrzal** [comment]
So the issue is combination of server-side copy, delete and GC. GC is processing lots of segments and with server-side copy + delete operation we can change state of `remote_segment_pieces` column which is needed to calculate GC bloom filter correctly. Short description is: when copied segment is already processed by GC and we delete ancestor segment before it will be processed by GC, then pieces related to those segments won't be calculated by bloom filter.

Segment Loop + GC is processing such structure:
```
SegmentA   [copy of SegmentB, no pieces]
SegmentB
SegmentC  [ancestor for SegmentA, have pieces]
```
1. GC is processing SegmentA but its a copy so it has no pieces attached
2. GC is processing SegmentB and at the same time we are deleting object which contains SegmentC
   * SegmentC is deleted and pieces entries are moved to SegmentA
 3. SegmentC was deleted so it won't be processed by GC and it's pieces won't be put into bloom filter
 4. Because those pieces are not put into bloom filter storage node will delete them

**Comment by Erikvv** [comment]
Michal and I did some brainstorming

Long-term idea I have to solve this
---

The problem which is making our copies complex, and incidentally  **small file packing**, is that we don't have a separate "block" abstraction. We do have it conceptually, but it is stored denormalized in segments: remote_alias_pieces, inline_data, and some other columns related to the remote opaque data.

Rough idea:
- drop table `segment_copies`
- add table `block(s)` with columns `root_piece_id` (is this immutable?), `remote_alias_pieces`, `created_at` and further columns related to repair administration like `redundancy`, `repaired_at`
- use `root_piece_id` (or something immutable) as foreign key from segment to block. For **small file packing**, add offset.
- introduce a new "block loop" and move observers from the segment loop to there.
- remove duplicat columns from segment table. This table seems now more immutable.
- maybe we can denormalize remaining segment columns into object table.

**Comment by mniewrzal** [comment]
Will be fixed when https://github.com/storj/team-metainfo/issues/120 and https://github.com/storj/team-metainfo/issues/121 will be merged and deployed.

**Comment by kristaxox** [comment]
Waiting on https://github.com/storj/infra/issues/3092

This is an umbrella ticket and has no work associated directly with it.

**Comment by mniewrzal** [comment]
New GC process was deployed and executed on all satellites. Issue should be fixed,
