### ISSUE TITLE
Satellite UI: Date picker improvements on new project dashboard

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5105]
Date picker is excluding the end date. Selecting 2022-08-10 - 2022-08-10 should show the entire day until 23:59:59. This problem exists for any date range. The selected end day is always missing because it defaults to 00:00:00

AC:
- include any activity that occurred on the end date in the queries for storage and bandwidth usage on the project dashboard
- do not change the way the underlying query handles the end time stamp, just update the end timestamp before passing it into the query as an argument

**Comment by mobyvb** [comment]
deployed in 1.65 https://github.com/storj/storj/commit/01735c82d81f942d166aabf2b8cf7c49865e4360
