### ISSUE TITLE
Satellite UI: Project cards

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5107]
On the all projects dashboard, I want to see all my projects as cards. If I can create new projects, I want to see a "create project" card. If I am at the free tier limit for my projects, I want to see a card asking me to upgrade my account if I want a new project
If I am in the paid tier and at my project limits, I want to see a card asking me to file a support ticket if I want a new project

**Comment by ferristocrat** [comment]
Functionality covered in https://github.com/storj/storj/issues/5514
