### ISSUE TITLE
Generated API: Add endpoints for listing and revoking api keys

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5111]
I want to be able to get a list of my api keys from the generated/external API, and I want to be able to revoke api keys, so that I can do common tasks related to uplink api keys via scripts.

Current "api key management" endpoint group: https://github.com/storj/storj/blob/d6054214c34da00acf6e7beb244f86c6007e06a8/satellite/console/consoleweb/consoleapi/gen/main.go#L97

AC:
* Endpoint for listing accesses in the external API
* Endpoint for revoking accesses in the external API

**Comment by xaresys** [comment]
Deployed in v1.64
storj/storj@1613d37
