### ISSUE TITLE
Satellite UI: make account settings page responsive

### ISSUE THREAD

**Issue by cam-a** [storj/storj#5128]
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=8467%3A6353
AC:
Make account settings page responsive, according to the figma above

**Comment by mobyvb** [comment]
deployed in 1.64 https://github.com/storj/storj/commit/fc9bd515fd9121f37f010e2ad3e34beffd3e701e
