### ISSUE TITLE
Satellite UI: make create bucket flow responsive

### ISSUE THREAD

**Issue by cam-a** [storj/storj#5129]
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=14633%3A115039
AC: ensure the create bucket flow is responsive on mobile, desktop, and tablet

**Comment by mobyvb** [comment]
deployed in 1.64 https://github.com/storj/storj/commit/e4412fa4809091ad2d49153ea6d8f02e84b75759
