### ISSUE TITLE
Satellite UI: truncate long names in tables

### ISSUE THREAD

**Issue by cam-a** [storj/storj#5130]
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=19036%3A162613

AC:
Truncate names in tables with an ellipsis if too long.
Table on mobile screens needs to be updated
When you hover over the name, show the whole name

**Comment by iglesiasbrandon** [comment]
The design team is going to create mockups for how we should tackle this design problem. @liviolanda @boshevski @alexsytnikk fyi ^

**Comment by NiaStorj** [comment]
@boshevski following up on the above comment.

**Comment by boshevski** [comment]
Hey, we already have this, @alexsytnikk created these designs:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=19036%3A162613
