### ISSUE TITLE
Turn new billing pages on in production

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5133]
The code for the new billing screens has been merged for some time. This ticket tracks that we still need to switch it on in production, because the previous issues are closed and marked as "done".

Blocked by #5095 #5097

**Comment by iglesiasbrandon** [comment]
@mobyvb the 2 tickets above have been merged! are we able to change the config value and enable this for the deployment on Monday? @littleskunk @andriikotko @ihaid

**Comment by mobyvb** [comment]
set default to true https://review.dev.storj.io/c/storj/storj/+/8817

**Comment by mobyvb** [comment]
Deployed in 1.67
