### ISSUE TITLE
[storagenode]: used space graph should display values in TB instead of TB*h

### ISSUE THREAD

**Issue by profclems** [storj/storj#5146]
Following the fixes for the used space (#4178), the graph on the storage node dashboard looks good now.

However, the values may not really be accurate since we are only estimating the used space per day.
We should consider using just bytes (B) instead of bytes*hours (Bh) for the used space graph. At least that should give a more accurate data and would show the correct amount of space used each day as at that interval_end_time (i.e. "at this interval_end_time, the disk usage was x bytes").

**Comment by mniewrzal** [comment]
Acceptance Criteria:
* change calculation from bytes * hours to just have bytes in space chart
* adjust UI to display labels correctly

**Comment by Erikvv** [comment]
When you look at the graph there is the scale but also the header above it.

![sno-graph.png](https://link.storjshare.io/raw/jvakv4ddjeprfyi6iqcbrgxy5nda/public/sno-graph.png)

Am I right in saying that this ticket is only about the graph scale?

**Comment by profclems** [comment]
@Erikvv it is not only about the graph scale but all references using B*h

**Comment by Erikvv** [comment]
So let's say this scenario:

- Now is sept-4 at 0h00m00s
- On sept-1 I have average 1 GB
- On sept-2 I have average 2 GB
- On sept-3 I have average 3 GB
- On sept-3 end of the day I have 3.5 GB

What do you put in the header? 

Option 1: data at latest timestamp, so 3.5 GB
Option 2: average of last day, so like 3GB
Option 3: average data of the month far, so (1+2+3)/3 = 2GB
Option 4: data for billing so I can multiply with the payout rate of $1.5 / TBm, so (1+2+3)/30 = 0.2 GBm

(example assumes tally is always immediate and up-to-date)

**Comment by profclems** [comment]
Currently, the _**total used space**_ displayed on the dashboard shows the total of _each daily byte*hour data_ in the current month. So for the screenshot you sent above, the 107.97GB*h is the total of all the daily at_rest_total from September 1st to 15th.

> So let's say this scenario:
> 
> Now is sept-4 at 0h00m00s
> On sept-1 I stored average 1 GB
> On sept-2 I stored average 2 GB
> On sept-3 I stored average 3 GB
> On sept-3 end of the day I stored 3.5 GB

So for this ticket, we will display the total of the daily average, so (1+2+3) = 6GB

**Comment by Erikvv** [comment]
So that is option 5, only with unit GB*day instead of GB*month. I think we should still display `GB*day` explicitly else it is confusing.

**Comment by profclems** [comment]
> So that is option 5, only with unit `GB*day` instead of `GB*month`. I think we should still display `GB*day` explicitly else it is confusing.

Makes sense.

**Comment by profclems** [comment]
https://review.dev.storj.io/c/storj/storj/+/8608
