### ISSUE TITLE
Uploading Large files

### ISSUE THREAD

**Issue by liviolanda** [storj/storj#5148]
When a user is in the buckets page, we want to display a notification informing them that the browser is not the best for large files. 
When a user goes to upload a large file, we want to show them a warning notification about trying to upload large files.

AC:
- default to showing general notification, user can dismiss notification — store in local storage
- when user uploads large file, show warning notification, user can dismiss for the session 
- find our current docs around uploading in satellite UI, and ensure that they say something about uploading large files
  - if not, post in #guild-documentation

_________

Business Objective/Issue:
When uploading large files in the browser, the user needs to know what would be the best way to get the best result for this process.

The designs show solutions in multiple cases:
1. Fixed warning in bucket page - just disappears if dismissed
2. Warning on the page when a user tries to upload large files
3. Warning on the upload progress box when a user tries to upload large files
4. Modal interrupting when a user tries to upload large files
All solutions guide users to check for recommendations on Documentation: https://docs.storj.io/dcs/how-tos/

Figma designs
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15470%3A118467

Pending evaluation of the cost of implementation for the solutions presented.

Acceptance Criteria:

Roadmap Link: If applicable

Linked Tickets: https://github.com/storj/team-product/issues/120

Test Plan Link: If applicable

Blueprint Link: If applicable

**Comment by iglesiasbrandon** [comment]
@mobyvb we have a hand full of designs for this and would like your input. take a peak when you can @liviolanda

**Comment by ferristocrat** [comment]
Relevant page in docs: https://docs.storj.io/dcs/getting-started/quickstart-objectbrowser#WeS6v

**Comment by lizzythomson** [comment]
Deployed in 1.78 [3f8eb58](https://review.dev.storj.io/plugins/gitiles/storj/storj/+/3f8eb58e4c0df27180c37628ae2b5d3367016dab)
