### ISSUE TITLE
No visible cue as to which is default credit card

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#5160]
A card needs to be `removed` to determine which is the default card. 

There could be a "Default" keyword shown on top right of the card.
It could be a simple text or a text on a ribbon. The ribbon could be  shown across the edge of the card.

![image](https://user-images.githubusercontent.com/15882196/189379347-1d818dac-f1f5-461d-bd0b-19315ff794bc.png)

**Comment by iglesiasbrandon** [comment]
this issue has been resolved; we indicate which card is the default now.
