### ISSUE TITLE
Reset Password Page Satellite UI: Can't tab select satellite

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#5164]
**Description**
On the reset password page (https://satellite.qa.storj.io/forgot-password), one should be able to select said satellite with tab control as it doable on signup page and one would need the correct satellite for resetting password.

**Step to Reproduce**
1. Head to reset password page
2. Use tab control to change satellite region

**Results**
As stated before, **expected** to be able to change satellite region since its required to be in the correct region for an account to reset password and because this is doable on the signup page, but **actually** it was impossible to tab control to a different satellite region, besides this issue tab control works fine in the reset password page!

https://user-images.githubusercontent.com/82845192/189665509-791b1992-e9ed-4c87-87a2-2f71905bdc25.mp4

**Comment by mobyvb** [comment]
1.70 https://github.com/storj/storj/commit/9535444dcde12228a
