### ISSUE TITLE
Signup on a satellite does not complete in some cases without a refresh

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5167]
I want to be able to re-submit the signup form after fixing a mistake, and the signup should succeed.

This issue is likely related to captcha

Reproduction steps:
* Go to us1.storj.io/signup
* fill in name, email, password
* _DO NOT_ check "I agree to the Terms of Service and Privacy Policy"
* Click "Sign Up" button - it should fail due to the unchecked item
* Check "I agree to the Terms of Service and Privacy Policy"
* It is not possible to successfully sign up without refreshing

AC:
* If the problem preventing signup (e.g. checkbox not clicked) is fixed, it should be possible to submit a new signup request with the updated information

**Comment by xaresys** [comment]
Deployed in v1.65
storj/storj@07c337f
