### ISSUE TITLE
Design Library - drop down components states/ desired interactions

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5170]
The purpose of this ticket is to update the drop-down components we use in the satellite GUI so that they all have the same interactions and states as the prototype and mockups below. 

Interactive components in a prototype - https://www.figma.com/proto/bh6epdlxNfXLi9pd7sZvYh/States-%26-Interactions?page-id=0%3A1&node-id=7%3A1752&viewport=803%2C299%2C0.47&scaling=min-zoom&starting-point-node-id=7%3A1752

States & Interactions
https://www.figma.com/file/bh6epdlxNfXLi9pd7sZvYh/States-%26-Interactions?node-id=10%3A1743

Acceptance Criteria: 
- ALL drop-down componetes used in the satellite GUI MUST have the same states and interactions as the prototype.

NOTE:
- sync with UI devs on what we should make into components

**Comment by mobyvb** [comment]
deployed in 1.68 https://github.com/storj/storj/commit/e76915421d04b60f5703302c235bc06f8a84fcbb
