### ISSUE TITLE
web/satellite - Create loading screen design/ animation

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5171]
The purpose of this ticket is to write the node needed for the loading screen/ animation and to implement it in all of the areas in the satellite GUI that use a loading icon/ animation at the moment. 

Designs:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=12491%3A66112

Acceptance Criteria: 
- The new loading screen/ animation component is created
- the entire satellite GUI is updated to use this loading state whenever needed

**Comment by stoweandi** [comment]
@boshevski what loading screen should we use and when ?

**Comment by NiaStorj** [comment]
duplicate. closing ticket.
