### ISSUE TITLE
Satellite GUI - Redesign persistent notification to Upgrade Account experience

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5172]
The purpose of this ticket is to improve the experience around prompting use to upgrade their accounts. 

Ready for dev Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=15026%3A107362

Acceptance Criteria
- REPLACE the current persistent message in the GUI 
- the user must have the ability to dismiss the new notification by clicking on the 'x' on the right-hand side
- if the user clicks on 'upgrade now' in the notification they must be promoted to enter a payment method in the modal (this is the current behavior as well)

**Comment by cam-a** [comment]
Duplicate: https://github.com/storj/storj/issues/5075
This is part of an AB test for the banner
