### ISSUE TITLE
Satellite GUI - Navbar - add the right border

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5173]
The purpose of this ticket is to make the nav bar pixel perfect. it's missing the right border. 

https://github.com/storj/team-product/issues/136

Acceptance Criteria: 
- border-right: 1px solid #EBEEF1

![Image](https://user-images.githubusercontent.com/5313116/189988152-bd7a600d-fc41-4812-b235-5f6cd3a15b2d.png)

**Comment by mobyvb** [comment]
deployed in 1.66 https://github.com/storj/storj/commit/ff99392fd7f99abf25a7ec1ac40d2ff59b0e1ea7
