### ISSUE TITLE
Design missmatch share bucket vs share file

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5184]
1. The popup is in a different position on the page.
2. The link is displayed in a different way
3. The share file popup should be name "share file" instead of just "share"
4. Something looks wrong with the font itself.
5. Cancel Button and Copy Link Button.
6. "Share link via..." vs "Share link via"

![image](https://user-images.githubusercontent.com/6333390/190486312-d26e8660-e81e-41ff-851a-883e878f8e9d.png)

**Comment by stoweandi** [comment]
@liviolanda / @boshevski can you please share here the `share` modal we want to have as a standard design across the gui

**Comment by liviolanda** [comment]
Standard Share modal:
- The title of the modal changes depending on what the user is sharing: bucket, object, or folder. - as in these [examples on figma](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=18227%3A151496)
- Position: always centered horizontally and vertically on the page
- Removing "Share link via..."
- Removing button Cancel - user needs to click on the Close icon in the top right corner
- The opacity layer in the background is 50% color #000000

About Copy Link:
- Button Copy Link inside the text field, with the link 
- In the text field, the link and button are aligned to the middle vertically
- Once the button "Copy link" is clicked, the link is copied to the clipboard, and the button shows feedback of "Copied"

Follow this design: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=18227%3A151496

**Comment by mobyvb** [comment]
deployed in 1.66 https://github.com/storj/storj/commit/ff99392fd7f99abf25a7ec1ac40d2ff59b0e1ea7
