### ISSUE TITLE
uplink-cli share regression: can get eternal public access implicitly

### ISSUE THREAD

**Issue by Erikvv** [storj/storj#5188]
I noticed I didn't need to specify `--not-after=none` and still was able to register for linksharing. 

This code still exists, but seems not triggered somehow:

https://github.com/storj/storj/blob/a3a3ffd12316ceab647853530425a75e5ca406f2/cmd/uplink/cmd_share.go#L88

Background: it is desirable to have expiry set when possible so we can periodically clean out the Auth Service database and keep down its size.

**Comment by zeebo** [comment]
The problem is that the conditional https://github.com/storj/storj/blob/8422c395d61fc6bf414cfbaca156e9549f7098ad/cmd/uplink/cmd_share.go#L86

will never be true. The right check should be `c.ap.notAfter.IsZero()`.

**Comment by Erikvv** [comment]
https://review.dev.storj.io/c/storj/storj/+/8484
