### ISSUE TITLE
Satellite UI: Fix "Cannot set properties of undefined (setting 'src')" error in file browser

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5193]
See attached image. Message from Bill

>  have a customer reporting "Nearly every file I’m uploading via the file manager has the attached error message. I believe its a javascript error relating to normally hidden files I open in programs like Adobe Bridge (I also see these files uploaded to Storj when I transfer an entire folder over). Is there anything I can do to prevent these error messages?

![Image](https://user-images.githubusercontent.com/1323312/186502547-0e8ca6ed-dda4-46a9-bd21-26e05d604c92.png)

TODO: reproduction steps. I (moby) have not been able to reproduce, and I don't think we will be able to fix this until we know how

AC:
- investigate if you're able to reproduce

**Comment by stoweandi** [comment]
@iglesiasbrandon testifies to this bug happening quite often

**Comment by mobyvb** [comment]
we are not able to reproduce this. If we don't get reproduction steps within the next month, we'll archive this ticket

**Comment by mobyvb** [comment]
bump @iglesiasbrandon
