### ISSUE TITLE
Insert node events that do not require a new chore into node_events table

### ISSUE THREAD

**Issue by cam-a** [storj/storj#5198]
~~Implement the following node emails based on the [design document ](https://review.dev.storj.io/c/storj/storj/+/8353)~~

Insert the following node events into node_events table

Implement for the following events:
Node Online
Node Suspended (offline and unknown errors)
Node Unsuspended (offline and unknown errors)
Node Software Update
Node Disqualified

Instead of sending emails directly, they will be inserted into the new node_events table to be compiled and then sent, as described in the design update: https://forum.storj.io/t/design-draft-node-status-emails-from-satellite/19760/5

AC:
* Satellite -> SNO emails can be turned on with a new feature flag
* Insert into node_events for online, suspended, unsuspended, node software update, disqualified
~~* Satellite -> SNO emails for online, suspended, unsuspended, node software update, disqualified~~
~~* Add monkit counter for each of these emails, so that we can track how many get sent~~
(monkit metrics can be added to the chore)

**Comment by mobyvb** [comment]
deployed in 1.67
* https://github.com/storj/storj/commit/865974950dda3976e043f78928f3b40eec15c4df
* https://github.com/storj/storj/commit/68fe26ebe56f874281caf89eefbbb0facc31e431
* https://github.com/storj/storj/commit/cb0c359b8108857e4e54aae4afc159d52032d9c7
* https://github.com/storj/storj/commit/74ddfab810e17938860d7f5de9f6c3b5f883edb6
