### ISSUE TITLE
Insert node offline events into node_events table

### ISSUE THREAD

**Issue by cam-a** [storj/storj#5199]
~~Implement Node Offline emails as described in the [design document](https://review.dev.storj.io/c/storj/storj/+/8353)~~

Insert Node Offline events into node_events table.

Add a new timestamp column to the nodes table, last_offline_email.
Create a new chore on the satellite to periodically read the nodes table in the satellite DB for nodes where last_contact_success < (the offline threshold, 4h currently configured) AND last_offline_email < (new config) AND disqualified is NULL.
~~Send the emails and update last_offline_email in the DB.~~
Insert into node events table and update last_offline_email in the DB. 

AC:
* Same feature flag from #5198 can be used to turn on the new email
* New configuration for how frequently we want to send offline emails
* New column `last_offline_email` added to nodes table
* New chore added to satellite core that checks `last_offline_email` and inserts an offline event into node_events if the conditions detailed above AC are fulfilled.
~~* New chore added to satellite core that checks `last_offline_email` and sends an email to SNO if the conditions detailed above AC are fulfilled~~

**Comment by mobyvb** [comment]
deployed in 1.68 https://github.com/storj/storj/commit/87660bd9b33eb6b017706a611619594fda0d5fc3
