### ISSUE TITLE
Change color on Bandwidth Graph

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5200]
We want to change the color on the bandwidth graph in the project dashboard so that the pink/red colors don't conflict with updated notification styling

colors: Settled: #A18EFF / Allocated: #C5BAFF
Y axis with the limits
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=18357%3A162657

**Comment by lizzythomson** [comment]
Deployed in 1.66 `419fb9c`
