### ISSUE TITLE
Update customer accounting to use submission time instead of creation time for orders 

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5201]
When a storage node submits an order, we currently use the creation date of the order for storage node accounting and customer accounting. we can't change the storage node accounting because we use it for detecting double submissions made by the nodes. We can however use the submission time for the customer accounting which would allow us to calculate invoices for customers on the first day of the month regardless of how long an order is valid. 

Some more info can be found here: https://github.com/storj/storj/blob/b21cbc85f1f9b8688d394166fe32204198791d59/satellite/orders/endpoint.go#L370 

Acceptance Criteria: 
- update the code to use submission time for orders on customer accounting. 
- the storage node accounting needs to continue working with creation time (this is how it currently works and needs to stay like that)

**Comment by iglesiasbrandon** [comment]
poke @littleskunk @elek @ifraixedes @stoweandi @dlamarmorgan do any of you have any thoughts on this ticket?

**Comment by dlamarmorgan** [comment]
Not sure I fully understand the benefit here. Is moving the calculation of the invoices to the 1st from the 3rd/4th (I think that's what it is now?) really going to have a big impact to anything? I thought the real issue we wanted to address was to speed up the process, and potentially move towards a per customer rolling billing cycle?

I guess I just need clarification maybe on what is the importance of the 1st, if at some point we hope that customers could have an invoice created on any day of the month anyways.

**Comment by ifraixedes** [comment]
I don't actually see how that can change anything.

My understanding is that if we use submission time and we are going to close the billing on the 1st then we'll drag some orders of the previous month to the next one because they will be submitted after the billing is closed. If we use creation time, wouldn't it be the same?

**Comment by iglesiasbrandon** [comment]
after a few conversations, we are not 100 percent convinced we should do this. I am going to close this ticket for now.
