### ISSUE TITLE
Invoice with storjscan 

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5203]
We noticed 2 problems with invoice generation with storjscan. Screenshots added
1. Amount in Tokens was not subtracted from amount due
2. We should fill correct Description, Qty, Unit Price in Token line item (see screenshot)
<img width="804" alt="Screenshot 2022-09-27 at 19 38 49" src="https://user-images.githubusercontent.com/14928042/192591597-dbe64126-afc3-4f8d-8037-02ad50035c3b.png">

How to reproduce:
I did that with storj-up, storjscan and our custom test token STORJT. If you need some test tokens - ping someone from QA Team

git clone git@github.com:storj/up
cd up

#install storj.io/storj-up@latest
go install ./...

storj-up init
storj-up add storjscan

storj-up build remote github -b main storagenode satellite-api satellite-core satellite-admin uplink versioncontrol
storj-up build remote github -b main gateway-mt linksharing authservice
storj-up build remote github -b main storjscan

#stripe settings
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_PROVIDER=stripecoinpayments
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_STRIPE_PUBLIC_KEY=<insert stripe key here>
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_STRIPE_SECRET_KEY=<insert stripe key here>
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_COINPAYMENTS_STRIPE_FREE_TIER_COUPON_ID=3oGhQE3l
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_CONSOLE_COUPON_CODE_BILLING_UI_ENABLED=true
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_CONSOLE_NEW_BILLING_SCREEN=true
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_CONSOLE_NATIVE_TOKEN_PAYMENTS_ENABLED=true
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_BILLING_CONFIG_DISABLE_LOOP=false
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STORJSCAN_DISABLE_LOOP=false

#görli testnet
storj-up flags set storjscan tokens.endpoint=https://goerli.infura.io/v3/01f8bc2c72d24d14b067d8fc4f902c51
storj-up flags set storjscan tokens.contract=0xbb1068095C880c4bc72F76649bBc5981a9c47BBb

#Initialize storjscan
docker exec -it up-storjscan-1 /bin/sh
storjscan mnemonic > .mnemonic
storjscan generate --api-key us1 --api-secret us1secret --address http://127.0.0.1:12000

NOTE: Keys for stripe you can find in our QA Satellite config

**Comment by shaupt131** [comment]
@wilfred-asomanii, we're thinking we have a UI bug here.  It seems the UI may be moving the decimal place on the token USD balance.  Could you investigate?  Reach out in #native-token-payments if you need more context.

**Comment by dlamarmorgan** [comment]
Just verified, that the credit note "Qty" field must be -1. I cannot change it to +1 by using a -1 in the quantity field.

**Comment by iglesiasbrandon** [comment]
@andriikotko i think we can close this ticket because of @dlamarmorgan's comment above. let us know your thoughts.

**Comment by iglesiasbrandon** [comment]
issue is marked as done, closing
