### ISSUE TITLE
Update STORJ Token balance on billing -> overview -> token card to show the correct balance instead of the stripe balance

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5204]
Update the STORJ Token payment 'card' on the billing -> overview page to show the Storj Token balance instead of the user's available balance on stripe. The STORJ Token balance is NO longer going to be stored on stripe as the users available stripe balance so we need to update this. 

Change suggested:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=18536%3A164307

Acceptance Criteria: 
- The label on the card should change from "Available Balance" to "STORJ Token Balance".
- there's no credit: call to action can be Add Funds - takes to Add Storj Token flow
- there's credit: call to action can be See Credit - takes to Payment Methods > Storj Token

---------- ---------- ---------- ---------- ---------- ---------- 
Original Ticket Description from @andriikotko
---------- ---------- ---------- ---------- ---------- ---------- 

As a total balance we show Stripe balance - but our tokens are not added to Stripe Balance
see video attachment

https://user-images.githubusercontent.com/14928042/192593200-8448c4f3-4ce2-47d0-b34c-9f928be6cff4.mp4

How to reproduce:
I did that with storj-up, storjscan and our custom test token STORJT. If you need some tokens - ping someone from QA Team 

git clone [git@github.com](mailto:git@github.com):storj/up
cd up

 install storj.io/storj-up@latest
go install ./...

storj-up init
storj-up add storjscan

storj-up build remote github -b main storagenode satellite-api satellite-core satellite-admin uplink versioncontrol
storj-up build remote github -b main gateway-mt linksharing authservice
storj-up build remote github -b main storjscan

stripe settings
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_PROVIDER=stripecoinpayments
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_STRIPE_PUBLIC_KEY=
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_STRIPE_SECRET_KEY=
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STRIPE_COIN_PAYMENTS_COINPAYMENTS_STRIPE_FREE_TIER_COUPON_ID=3oGhQE3l
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_CONSOLE_COUPON_CODE_BILLING_UI_ENABLED=true
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_CONSOLE_NEW_BILLING_SCREEN=true
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_CONSOLE_NATIVE_TOKEN_PAYMENTS_ENABLED=true
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_BILLING_CONFIG_DISABLE_LOOP=false
storj-up env setenv satellite-api satellite-core satellite-admin STORJ_PAYMENTS_STORJSCAN_DISABLE_LOOP=false

#görli testnet
storj-up flags set storjscan tokens.endpoint=https://goerli.infura.io/v3/01f8bc2c72d24d14b067d8fc4f902c51
storj-up flags set storjscan tokens.contract=0xbb1068095C880c4bc72F76649bBc5981a9c47BBb

 #Initialize storjscan
docker exec -it up-storjscan-1 /bin/sh
storjscan mnemonic > .mnemonic
storjscan generate --api-key us1 --api-secret us1secret --address http://127.0.0.1:12000/

NOTE: Keys for stripe you can find in our QA Satellite config

**Comment by shaupt131** [comment]
Action: @iglesiasbrandon to investigate renaming “available balance” to “customer credit” or something similar to avoid confusion.  This is where we can add credits if we have outages, etc.

**Comment by iglesiasbrandon** [comment]
@andriikotko i  reassigned this ticket to the UG team since we are going to fix it in the UI.

**Comment by stoweandi** [comment]
@liviolanda / @alexsytnikk / @boshevski Do we have designs for modifying this overview pages to show STORJ token balance instead of the Storj credit?

**Comment by liviolanda** [comment]
Change suggested: 
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=18536%3A164307

The label on the card should change from "Available Balance" to "STORJ Token Credit".

If:
- there's no credit: call to action can be Add Funds - takes to Add Storj Token flow
- there's credit: call to action can be See Credit - takes to Payment Methods > Storj Token

**Comment by shaupt131** [comment]
@stoweandi and @iglesiasbrandon how do we feel about Livia's suggestion above?

**Comment by stoweandi** [comment]
@shaupt131 I worked through it with Livia and Moby. We will have it in the UG backlog to be reviewed in grooming before moving todo.

**Comment by shaupt131** [comment]
@NiaStorj yes, this is a change that we still want to make for Storjscan, but it's not super urgent.  If this can be done in the next sprint or two that would be great.

**Comment by NiaStorj** [comment]
Okay. Thanks. Still needs grooming though.

**Comment by iglesiasbrandon** [comment]
Hey @NiaStorj @shaupt131 and I updated the description of this ticket as well as the title to make it more clear specifically what needs to change. FYI @andriikotko @stoweandi 

It would be really great for us to work on this in the next sprint; I expect this is a really small change and it would greatly increase the UX because until we make this change it will be more difficult for the customer to know how much token balance they have. plus the stripe aviabale balance that we are currently showing is going to be blank for 99.99 percent of users all the time
