### ISSUE TITLE
[New Billing Page] Billing History tab doesn't send 'billing-history' request -> not shown billing history list

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5218]
Billing History tab doesn't send 'billing-history' request - as a consequence -> billing history list is not shown
Possible to see it only if user click Payment Methods tab ( which send 'billing-history' request)
see video attachment

https://user-images.githubusercontent.com/14928042/193305931-821b6dd6-7f51-4b7b-b605-f8658e52f773.mp4

**Comment by mobyvb** [comment]
fixed by https://review.dev.storj.io/c/storj/storj/+/8294/24/web/satellite/src/components/account/billing/billingTabs/BillingHistory.vue#56
as part of #8294

@andriikotko could you confirm if this is still an issue in QA?

**Comment by mobyvb** [comment]
deployed in 1.66 https://github.com/storj/storj/commit/05e57edb20648be95165ce5a366b9473f9537001
