### ISSUE TITLE
[New Billing Page] Overlapping on Storj Token card

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5219]
Go to Billing Page, open Payment Methods tab
see video attachment

https://user-images.githubusercontent.com/14928042/193306460-e9df07f0-f2ae-4249-86a4-af8b92ed9850.mp4

**Comment by stoweandi** [comment]
@andriikotko what specs did you test this at?

**Comment by mobyvb** [comment]
deployed in 1.68 https://github.com/storj/storj/commit/f84111ee694386f97e9ba09a6b5e1b4470f2cf85
