### ISSUE TITLE
Review metainfos endpoint for objects inconsistency

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5224]
So we resolved main object inconsistency issue described in milestone https://github.com/storj/roadmap/issues/18.

The purpose of this task is to verify we have at least strong read-after-write consistency.  

We need to review metainfo endpoints to verify if we provide at lest strong read after write consistency https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/ but ideally we should provide https://jepsen.io/consistency.

Acceptance Criteria:

- Verify the consistency throughout the protocol

**Comment by shaupt131** [comment]
So would this actually pertain to https://github.com/storj/roadmap/issues/18, or would this be more towards https://github.com/storj/roadmap/issues/31?

**Comment by mniewrzal** [comment]
oh I think because of comment in https://github.com/storj/roadmap/issues/18 I mixed two road map items in my head. So this should be more https://github.com/storj/roadmap/issues/31. In that case to finish https://github.com/storj/roadmap/issues/18 we just need.
* https://github.com/storj/storj/issues/5227
* https://github.com/storj/storj/issues/5274

And this can be moved outside this milestone.

**Comment by mniewrzal** [comment]
**Metainfo Endpoints:**
|Metainfo method         |Requests to Metabase DB  |Consistency Issue|Comments                                                                                                                                                                                                                              |
|------------------------|-------------------------|-----------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|BeginObject             |1                        |NO               |Its true for new 'multiple versions' implementation which will be enabled soon                                                                                                                                                        |
|CommitObject            |Many (single transaction)|NO               |                                                                                                                                                                                                                                      |
|GetObject               |1                        |NO               |                                                                                                                                                                                                                                      |
|ListObjects             |1                        |NO               |From endpoint perspective it's just single request to DB but libuplink is using multipe of those if number of listed elements is larger than 1000. Not sure if that really a problem but object can be always listed just after write.|
|BeginDeleteObject       |Many (single transaction)|NO               |* for pending object its just single SQL query * for committed object its multiple queries but as a single transaction Removing data from SNs is outside transaction but it doesn't affect object consistency                         |
|FinishDeleteObject      |0                        |NO               |It's not used (deprecated)                                                                                                                                                                                                            |
|GetObjectIPs            |1                        |NO               |                                                                                                                                                                                                                                      |
|ListPendingObjectStreams|1                        |NO               |From endpoint perspective it's just single request to DB but libuplink is using multipe of those if number of listed elements is larger than 1000. Not sure if that really a problem but object can be always listed just after write.|
|DownloadObject          |3                        |NO               |DB requests (not in transaction): * GetObjectLastCommitted * ListStreamPositions * GetSegmentByPosition                                                                                                                               |
|UpdateObjectMetadata    |1                        |NO               |Only for committed objects                                                                                                                                                                                                            |
|BeginMoveObject         |2                        |NO               |DB requests (not in transaction): * GetObjectLastCommitted * Select to get segments metadata                                                                                                                                          |
|FinishMoveObject        |Many (single transaction)|NO               |                                                                                                                                                                                                                                      |
|BeginCopyObject         |2                        |NO               |DB requests (not in transaction): * GetObjectLastCommitted * Select to get segments metadata                                                                                                                                          |
|FinishCopyObject        |Many (single transaction)|NO               |                                                                                                                                                                                                                                      |

Additional notes:
* we can move/copy only committed objects
* move/copy is a single operation from libuplink perspective
* list objects is a single operation from libuplink perspective"

**Libuplink methods:**
|Method                  |Comment                  |
|------------------------|-------------------------|
|StatObject              |Single request GetObject |
|UploadObject            |Many requests request to satellite, not guranted object persistence if not committed, we start sending requests to satellite after 4k of data|
|DownloadObject          |Single request to satellite DownloadObject, can be interupted by deleting object|
|DeleteObject            |Single request BeginDeleteObject|
|ListObjects             |Single request to 1000 results, after that we may have multiple requets and result can be from the past|
|MoveObject              |Requires two requests: BeginMoveObject, FinishMoveObject|
|CopyObject              |Requires two requests: BeginCopyObject, FinishCopyObject|
|UpdateObjectMetadata    |Requires two requests: GetObject, UpdateObjectMetadata|
|BeginUpload             |Single request BeginObject|
|CommitUpload            |Single request CommitObject|
|UploadPart              |Usually at least 2 requests (BeginSegment, CommitSegment), single request for part within inline size|
|ListUploads             |Single or multiple requests depends on number of results|
|ListUploadParts         |Single or multiple requests depends on number of results|

One potential inconsistency I can think of is for downloading in ranges:
* upload object A
* download half of the object with offset and length
* reupload object A with different content
* download second half of the object with offset and length
* at the end of download we have output which contains half of first version of object and half of second version of object

I didn't find other inconsistency issues. Of course it doesn't we have non as it was just single person review.

**Comment by mniewrzal** [comment]
@onionjake do you have any idea how we can finalize this? I made a review but now we are struggling how to define its done.
