### ISSUE TITLE
New peer to start loop as a new instance 

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5225]
Ranged loop needs to be separate cmd command. We need to prepare new `peer` (like core/api/gc) to be able to wire it up with new cmd command.

The purpose of this is to start a new peer which will be used with cmd command. 
Acceptance Criteria:
* new peer struct with will wire up all elements needed for `rangedloop` service, see https://github.com/storj/storj/blob/main/satellite/gc.go as an example

**Comment by Qweder93** [comment]
https://review.dev.storj.io/c/storj/storj/+/8737

**Comment by shaupt131** [comment]
Looks like the PR was deployed.  Moving to done/deployed and closing issue.
