### ISSUE TITLE
Migrate repair observer to ranged loop

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5226]
Repair observer is selecting segments which should be repaired and put them into repair queue. When https://github.com/storj/storj/issues/5239 will be finished we should be able to migrate repair loop observer to new ranged loop interface. For some time we should have both in our code base, old and new observer but we should have enabled only one at the time.

The repair observer is currently a chore that is connected to the segment loop (`satellite/repair/checker/checker.go`)
Migrating the repair observer to the new ranged loop interface will allow us to improve the speed of finding unhealthy segments.
The observers will be split into smaller observers which will be able to process more segments for repairs.

Acceptance Criteria:
* create new repair observer for ranged loop according to new interface from https://github.com/storj/storj/issues/5239
* cover new repair observer with tests
* new repair chore for ranged loops much have the same configuration values as the old repair chore
* we must have the ability to enable/ disable (feature flag) the new repair observer.

**Comment by Qweder93** [comment]
https://github.com/storj/storj/pull/5367

**Comment by Qweder93** [comment]
https://review.dev.storj.io/c/storj/storj/+/9335
