### ISSUE TITLE
Add alert about "multiple_committed_versions" metric

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5227]
With the current design, it should be possible to have multiple pending objects and always single committed version for the same location. We added in few places "multiple_committed_versions" metric to track if multiple committed version will be detected in the system. We need to add alert to detect such situation right away.

Acceptance Criteria:
* configure redash alert which will send a notification to `#team-satellite-events` slack channel if metric "multiple_committed_versions" will be higher than 0
* define what the action plan is when this alert is fired
* define the event source (this is on redash)

**Comment by Qweder93** [comment]
Alerts: 
https://redash.datasci.storj.io/alerts/128 us2
https://redash.datasci.storj.io/alerts/129 qa 
https://redash.datasci.storj.io/alerts/130 us1
https://redash.datasci.storj.io/alerts/131 saltlake 
https://redash.datasci.storj.io/alerts/132 asia-east1
https://redash.datasci.storj.io/alerts/133 eu-west1
https://redash.datasci.storj.io/alerts/134 eu-north1

**Comment by iglesiasbrandon** [comment]
@ethanadams please provide guidance on what we should do when an alert is triggered

**Comment by joshdougall** [comment]
just a quick note that I am currently looking at adding this to prometheus, and I will provide an update shortly with my progress.

**Comment by joshdougall** [comment]
Here is a separate PR that contains an alert ready to deploy and test - https://github.com/storj/infra/pull/3263

**Comment by joshdougall** [comment]
The alert has been rolled out across all environments with this PR - https://github.com/storj/infra/pull/3263

**Comment by mniewrzal** [comment]
@joshdougall it looks that alert directly from prometheus was not triggered. I received notification from redash (email) and we had also alert in ##team-satellite-events but not from prometheus. We need to take a look why,

**Comment by joshdougall** [comment]
The alert changes have been captured here: https://github.com/storj/infra/pull/3405

Note that there are use cases where the metric does not exist when there are no objects with multiple committed versions. I have added a condition to the alert for this.

**Comment by joshdougall** [comment]
Note that the above PR is deployed to QA, and is also being deployed to production now. I am hesitant to mark this as done as we have no way of testing this without comparing redash alerts to prometheus for a real event.

**Comment by mniewrzal** [comment]
> I am hesitant to mark this as done as we have no way of testing this without comparing redash alerts to prometheus for a real event.
We can still reopen if needed.

**Comment by joshdougall** [comment]
Marking as closed in that case!
