### ISSUE TITLE
Create new reverify methods

### ISSUE THREAD

**Issue by thepaul** [storj/storj#5229]
See audit scaling [blueprint](https://github.com/storj/storj/blob/main/docs/blueprints/audit-scaling.md).

Acceptance criteria:
 * new `reverify()` method, based on existing one, but targeting specific pieces
 * reverifier chore

**Comment by iglesiasbrandon** [comment]
@thepaul can you add the PR(s) for this on this ticket? should this still be in the merged column but don't done/deployed?

**Comment by thepaul** [comment]
The changesets that apply most directly to this issue are probably:

* https://review.dev.storj.io/c/storj/storj/+/8976 (https://github.com/storj/storj/commit/35f60fd5ebf232ec0a02e26ded290ca59539c8de)
* https://review.dev.storj.io/c/storj/storj/+/8647 (https://github.com/storj/storj/commit/c54c45c9c74b79d78429885308ce1b6185637c95)
