### ISSUE TITLE
Decouple logic around reverification

### ISSUE THREAD

**Issue by thepaul** [storj/storj#5230]
See audit scaling blueprint and #5228, #5229

Acceptance criteria:

* remove old reverify function and related logic
* update satellitedb/containment.go methods (delete old as appropriate, switch any that are still needed to use new system)
* add Reverifier service to core

The reverification chore and workers should be runnable as a separate, new process, but we can say that they run as part of the existing audit processes by default for now (to avoid requiring changes to storj-up, storj-sim, testplanet, etc)

**Comment by thepaul** [comment]
This corresponds to Part 2 in the blueprint plan.

**Comment by iglesiasbrandon** [comment]
PR: https://review.dev.storj.io/c/storj/storj/+/8855

**Comment by thepaul** [comment]
8855 was split into many commits; the best new PR for this is probably https://review.dev.storj.io/c/storj/storj/+/8982.
