### ISSUE TITLE
Migrate audit observer to ranged loop

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5232]
Audit observer is selecting segments which should be audited on storage nodes. When https://github.com/storj/storj/issues/5239 will be finished we should be able to migrate loop audit observer to new ranged loop interface. For some time we should have both in our code base, old and new observer but we should have enabled only one at the time.

The Audit observer is currently a chore that is connected to the segment loop (`satellite/audit/collector.go`). 
Migrating the audit observer to the new ranged loop interface will allow us to improve the speed of audits.
The observers will be split into smaller observers which will be able to process more segments for audits. 

Acceptance Criteria:
* create new audit observer for ranged loop according to new interface from https://github.com/storj/storj/issues/5239
* cover new audit observer with tests
* ~~new audit chore for ranged loops much have the same configuration values as the old audit chore~~ (ranged loop will have own chore and will be executed every defined interval)
* new audit loop observer should take into account configuration from old audit chore ([Config](https://github.com/storj/storj/blob/main/satellite/audit/worker.go#L23)), only flags related to loop observer
* we must have the ability to enable/ disable (feature flag) the new audit observer.

**Comment by Erikvv** [comment]
This is probably the most complex observer to migrate. It has internal state containing a random sampling per StorageNode, which must be merged at the end of the parallel segment loop. This must be done in a statistically sound way.

The lazy route would be to put a mutex around the state, which would still cause a 50% speedup but this observer could become a bottleneck for the entire loop.
