### ISSUE TITLE
Migrate metrics observer to sharded loop

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5236]
The metrics observer collects values and sets these values in monkit. When https://github.com/storj/storj/issues/5239 will be finished we should be able to migrate loop metrics observer to new ranged loop interface. For some time we should have both in our code base, old and new observer but we should have enabled only one at the time.

The metrics observer is currently a chore that is connected to the segment loop. Migrating the metrics observer to the new ranged loop interface will allow us to improve the speed of calculating node tallies. The observers will be split into smaller observers which will be able to process all segments quicker.

Existing observer: https://github.com/storj/storj/blob/8777523255f0b4c4d88c88a8bedfd56af2209832/satellite/metrics/counter.go

Acceptance Criteria:

- create a new metrics observer for the ranged loop according to the new interface from https://github.com/storj/storj/issues/5239
- cover new metrics observer with tests

**Comment by azdagron** [comment]
I've implemented this here: https://review.dev.storj.io/c/storj/storj/+/9084

> I suggest to keep the metrics but use this opportunity to make a change to store the monkit counters as scalar values instead of distributions.

I'm not super familiar with monkit (it's been a while). Are you proposing moving to Counter instead of IntVal?

**Comment by Erikvv** [comment]
I don't think there is a built-in StatsSource which just holds a scalar value, I guess it's considered too simple. 

I've done it in https://github.com/storj/storj/pull/5365/commits/e7bb8b62d44c2fbd82394147290713966fd0bb58 and https://github.com/storj/storj/pull/5366/commits/1dd3c01ee4944567158d538ffb4cc5ccb801f76c by implementing my own `monkit.StatSource`
