### ISSUE TITLE
Change invoice date input to ISO8601 format

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#5246]
## Goal

- Standardize the date input for invoicing commands.  They are currently using different formats, so it would be good to get them all standardized.  

## AC

- All date input formats for invoicing should be ISO compliant (YYYY-MM-DD).

**Comment by mobyvb** [comment]
@NiaStorj @stoweandi we should make a similar task for the Satellite UI. We noticed inconsistencies across different parts of the UI

**Comment by egonelbre** [comment]
@mobyvb for the satellite UI, the parts that the end-user sees, should use locale specific time formatting only.
