### ISSUE TITLE
Wallet address and balance is cached in browser cache

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5252]
Preconditions: User1 and User2 
Steps: 
1. Login as User1 , go to Billing 
2. check wallet address and Balance
3. Logout
4. Login as User2, go to Billing
5. Pay attention to wallet address and balance 
Actual result: wallet address and balance for User2 is the same as for User1
Expected result: Users should have their own wallets and balance )
NOTE: refresh page fixing it
see video attachment 

https://user-images.githubusercontent.com/14928042/196435393-e90ef88b-a32a-4b43-991c-8bc71a5209eb.mp4

**Comment by wilfred-asomanii** [comment]
https://review.dev.storj.io/c/storj/storj/+/8666

**Comment by andriikotko** [comment]
Unfortunately, this fix doesn't help - still the same behaviour

**Comment by andriikotko** [comment]
and after login and till Payment-methods screen I don't see any `.../api/v0/payments/wallet` request
maybe if we add one, it'll help
<img width="734" alt="Screenshot 2022-11-03 at 14 25 18" src="https://user-images.githubusercontent.com/14928042/199720148-188cbab2-5b7f-453b-8934-e34b8e7c0bd4.png">

**Comment by wilfred-asomanii** [comment]
Okay. I will check this and revert

**Comment by wilfred-asomanii** [comment]
i checked and was able to reproduce this on main
i followed these steps;

> Login as User1 , go to Billing
check wallet address and Balance
Logout
Login as User2, go to Billing

i went further to add a 3rd account and still got different results.

**Comment by mobyvb** [comment]
deployed in 1.66 https://github.com/storj/storj/commit/56128b972b0a03bbe442989dc08bcb12d14dfdaa
