### ISSUE TITLE
cmd/satellite: add segment repair command

### ISSUE THREAD

**Issue by egonelbre** [storj/storj#5254]
Add a command that allows to trigger a manual repair on a specific segment.

It needs to repair a single segment, with these considerations:

* it must not affect reputation of nodes
* it should try to download all available pieces
* as usual -- use compare and swap to update the segment in metabase

The command should take segment uuid and segment index as the arguments.

**Comment by iglesiasbrandon** [comment]
@egonelbre I unassigned this task from you so that we can assign it to someone on the satellite team who is familiar with the repair system. thank you

**Comment by iglesiasbrandon** [comment]
@rikysya would you be interested in working on this issue?

**Comment by egonelbre** [comment]
@iglesiasbrandon there shouldn't be any "repair workers" involved. The tool itself should do the whole repair. The segment checker isn't involved here.

**Comment by iglesiasbrandon** [comment]
PR: https://review.dev.storj.io/c/storj/storj/+/8859

**Comment by mniewrzal** [comment]
https://review.dev.storj.io/c/storj/storj/+/8891
