### ISSUE TITLE
Investigate if we can find better chunk size increments for piece downloads

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5260]
The purpose of this ticket is to investigate if the chunk size increments we currently use in production are optimal for downloads. 

Currently, we start with 64k chunk sizes, after 64k we do a signature calculation (for orders) which slows down the download because it is CPU heavy (this is an assumption). We then increment 150% after each chunk download all the way up to 1 MB. 

Acceptance Criteria
- Record baseline performance on storage node throughput
- Record throughput performance on storage nodes with different chunk size defaults 
- Determine if a different chunk size should be set as the default from the results of the lines above. 
- If we determine there is a more optimal chunk size create PRs to set it as the default.

**Comment by iglesiasbrandon** [comment]
do the measurement, share the results, then we can decide if we want to merge the tool

**Comment by elek** [comment]
https://hackmd.io/@elek/r1pVAxYrs
