### ISSUE TITLE
Update loading screen styling to be branded and more attractive

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5278]
We want an updated loading screen that is branded so that our product looks for polished for enterprise users

Loading screen: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI-Public?node-id=18916%3A158963

Revision notes: we do not keep track of the % of where the loading is at. We will need an animation that is looping vs % completion based.

**Comment by stoweandi** [comment]
@boshevski can we modify the animation to be looping vs progress bar per the revision note above?

**Comment by mobyvb** [comment]
1.70 https://github.com/storj/storj/commit/5d13a5e0ed6c57
