### ISSUE TITLE
Enable `metainfo.multiple-versions` flat to fix consistency while upload

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5283]
At the moment fix for consistency issue while upload is behind feature flag and its disabled. When new feature will be tested on QA and SLC/EUN1 we need to enable it in production. We can do this be setting `metainfo.multiple-versions` to true in deployment configuration but more permanent step will be to enable it by default in source code.

Acceptance Criteria:
* set config default value `Config.MultipleVersions` to true (see https://github.com/storj/storj/blob/main/satellite/metainfo/config.go)
* adjust tests in needed

**Comment by kristaxox** [comment]
Currently blocked by:
- fix for upload object consistency
- deployment of above to QA, prod test, and prod

**Comment by iglesiasbrandon** [comment]
Its currently deployed on SLC and EU North

**Comment by iglesiasbrandon** [comment]
@storj/qa we would like to enable this on the customer-facing production satellites in the next deployment or the one after. Please let us know if you have found any bugs we need to address.

**Comment by mniewrzal** [comment]
https://review.dev.storj.io/c/storj/storj/+/8888
