### ISSUE TITLE
Invoice generation -> after the invoices are created and before the invoices are finalized we show the user a draft invoice but it has no link

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5284]
AC:
- we shouldn't show draft invoices
>- filter out draft invoices so that they aren't shown

after invoice generation and till finalize-invoices we show to the user an invoice draft, but it has no link
If user click download invoice - it just downloads an empty html file
it might be confusing for user
 
<img width="1733" alt="Screenshot 2022-11-01 at 09 11 40" src="https://user-images.githubusercontent.com/14928042/199742105-cc7e05e3-dff1-49a0-b162-ec59babf2e12.png">

**Comment by mobyvb** [comment]
deployed in 1.68 https://github.com/storj/storj/commit/5c2b111347b0cae1a3adeb7107cec6ca3021beef
