### ISSUE TITLE
UI bug: opening the latest project details by default

### ISSUE THREAD

**Issue by prerna-parashar** [storj/storj#5294]
If I click on a specific project I would expect to see the edit modal for the project I clicked on

Bug in the project details page - 

https://user-images.githubusercontent.com/78053555/200362172-bbe92cf5-0b36-47be-a306-f215c65fde53.mov

 Even though I am clicking on test2 or test4 project it is always opening test6 project.

**Comment by lizzythomson** [comment]
Deployed in v1.7 [eee79ec](https://github.com/storj/storj/commit/eee79ec)
