### ISSUE TITLE
Decide on a decision for how to keep TLS Pro Account only

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5296]
We want to make a decision on how we want to TLS available to Pro Accounts only, so that we can proceed with developing a solution!

related to https://github.com/storj/gateway-mt/issues/241

AC:
- decided path on how we want to implement

**Comment by mobyvb** [comment]
blueprint merged as https://github.com/storj/storj/commit/870eefbb5d6f8a6e49e3b8af71cdb55ab66dc888
