### ISSUE TITLE
Update the DBX method we use for reputations.ApplyUpdates method to not return columns

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5310]
We use DBX to update the reputations table but the DBX implementation returns a lot of useless columns (like id, which we provide) - we would decrease network load on CRDB by adding `noreturn` for columns we don't need. 

https://github.com/storj/storj/blob/0dcc0a9ee056597313f4addc2b13a95220e64725/satellite/satellitedb/reputations.go#L40

Acceptance Criteria: 
- Improve the size and efficiency of the reputations.ApplyUpdates method by adding 'noreturn' for columns we don't need.

**Comment by egonelbre** [comment]
DBX allows to specify `noreturn` to avoid returning columns.

**Comment by Fadila82** [comment]
It appears that we need to return at least one thing, to be sure the update has been applied. After discussion with Paul, I've decided to use a SQL query.

**Comment by Fadila82** [comment]
For context, here is an example on asia-east1: last hour we had 344k requests to get a node's reputation (mean statement time: 22ms) , and 326k requests to update a node's reputation. I hope to make this 344k requests to update a node.

**Comment by iglesiasbrandon** [comment]
We need to create new tickets that are more specific and close this one;
