### ISSUE TITLE
Update copy on Coupon Code modal

### ISSUE THREAD

**Issue by onionjake** [storj/storj#5314]
Existing wording:

![Image](https://user-images.githubusercontent.com/113088/202033462-618576d2-13b5-4382-a161-aa47a5cc8060.png)

Update: 

> If you have a coupon active, it will automatically be replaced.

To something like this:

> Entering a new coupon will replace any existing coupon.

**Comment by mobyvb** [comment]
1.70 https://github.com/storj/storj/commit/d20a2e9a7dd68782c
