### ISSUE TITLE
Date looks clickable, but isn't? (new billing screen)

### ISSUE THREAD

**Issue by onionjake** [storj/storj#5315]
![Image](https://user-images.githubusercontent.com/113088/202033700-4171e16a-a893-4371-bcb2-d9c00a43016b.png)

AC: see screenshot Andi posted in comment thread

**Comment by stoweandi** [comment]
@boshevski can we get a design for making this button not look clickable?
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH?node-id=11672:82186#309022044

**Comment by stoweandi** [comment]
[image: Screen Shot 2022-11-18 at 8.26.35 AM.png]
Andi Steinke

Sr. Product Manager

Storj Labs


[image: Storj Labs]

**Comment by stoweandi** [comment]
![image](https://user-images.githubusercontent.com/48924196/202753475-12f47106-c7e3-402c-ad82-d2fd95f55566.png)

**Comment by mobyvb** [comment]
1.70 https://github.com/storj/storj/commit/9a59b75159f63b
