### ISSUE TITLE
STORJ node disqualified after nearly 2 years by bug in node/db's

### ISSUE THREAD

**Issue by cryptocoinguru** [storj/storj#5319]
I've been running a STORJ node now for about 2 years. Yesterday I noticed docker-volume had less space so I decided to shutdown docker and resize the lvm-volume. Just for clarification the docker-volume is independend from STORJ volume (separate LVM volume).

After the resize was done, reboot and starting docker again the problems began:

**Logs**
```
2022-11-15T08:42:20.377Z	WARN	piecestore:monitor	Disk space is less than requested. Allocated space is	{"Process": "storagenode", "bytes": 28450369536}
2022-11-15T08:42:20.377Z	ERROR	piecestore:monitor	Total disk space is less than required minimum	{"Process": "storagenode", "bytes": 500000000000}
2022-11-15T08:42:20.377Z	ERROR	services	unexpected shutdown of a runner
Error: piecestore monitor: disk space requirement not met
2022-11-15 08:42:20,510 INFO exited: storagenode (exit status 1; not expected)
....
2022-11-15T13:01:23.462Z	ERROR	piecestore:cache	error getting current used space: 	{"Process": "storagenode", "error": "context canceled; context canceled; context canceled; context canceled; context canceled; context canceled; context canceled", "errorVerbose": "group:\n--- context canceled\n--- context canceled\n--- context canceled\n--- context canceled\n--- context canceled\n--- context canceled\n--- context canceled"}
Error: piecestore monitor: disk space requirement not met
2022-11-15 13:01:23,541 INFO exited: storagenode (exit status 1; not expected)
```

But that didn't make any sense. I've fsck'ed the storj-volume in separate LVM and there were no issues at all. And there still was free space (but no 500 GB of course, as the storage was already filled by STORJ node):

```
df -h /mnt/storj-storage/
Filesystem      Size  Used Avail Use% Mounted on
-               570G  522G   47G  92% /mnt/storj-storage
```

** Possible fixes **
After wasting hours of reading/discussing in STORJ forum all looks like there's something broken/corrupt in the db-files in STORJ-Node. It didn't look like sqlite error, as I checked using this script reporting no errors:

```
#!/bin/bash
_pwd=$(pwd)

for sqlite in ${_pwd}/*.db;
do
  sqlite=$(basename ${sqlite});
  echo "Checking $sqlite"

  docker run --rm -it \
    -v ${_pwd}:/data/ \
    sstc/sqlite3 \
    sqlite3 ./${sqlite} "PRAGMA integrity_check"
done
``` 

Finally I got a tip from user Alexey trying to add this command to my docker-compose.yaml for storj-node:
```
    command:
      - "--storage2.monitor.minimum-disk-space=20GB"
```

Now suddenly the node was starting up without the previous issues and it seems to do some garbage collection/repair on what happened before. In the meantime the node was running, but "offline" due to these errors all this happened between late night and next day.

Today my node reported this after I've checked everything is fine:
```
Your node has been disqualified on 12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs.
```

Well... thanks for nothing. I've kept up this node for month(!) without interruption and now got disqualification for an issue that is obviously some problem inside STORJ node not handling such errors in a more respectul way trying to do garbage collection, sqlite-db checking or something that helps keeping up the node.

I'm really disappointed after doing my best as operator and I even think about shutting down the node permanently if it is disqualified now finally.

**Comment by littleskunk** [comment]
> I've kept up this node for month(!) without interruption and now got disqualification for an issue that is obviously some problem inside STORJ node not handling such errors in a more respectul way trying to do garbage collection, sqlite-db checking or something that helps keeping up the node.

So just to recap what happened to your node. You might think that your node got disqualified for the downtime but that is not the case. The real problem was that the node had no access to the files it stored previously. The used space check ends with 0 Space and that means there is less than 500 GB total space for this node.

> - "--storage2.monitor.minimum-disk-space=20GB"
That change got you finally disqualified. The node crashed and prevented the disqualification. That check can be disabled as you did. The disqualification isn't a big surprise to me. If your node should have more than 500 GB of free space you should never ever reduce the minimum disk space check. Don't disable checks that are there to catch user errors.

> I even think about shutting down the node permanently if it is disqualified now finally.
Even if I would revert the disqualification in the database your storage node still has no access to the old files. It will get disqualified again and again.

In any case, this is more of a topic for the forum. I don't see any actionable ticket in here. For that reason closed.

**Comment by cryptocoinguru** [comment]
Ok thanks for pointing that out. Well I hope the problems that may have lead to disqualification will be fixed.

Regarding missing files, why will this throw final disqualification? Wouldn't it be smarter to set mode in "Repair" Mode to fresh up missing files against other nodes to fixup? Deleting the node and starting from scratch for some missing files doesn't look very smart.

I totally agree that a node that is out of sync or has some kind of instable state shouldn't deliver files anymore. But there should be a smart way to solve that instead of punishing operators for such problems, that obviously can happen!

Just think of these cases:
- Disk replacement & RAID Resync may cause node delays/offtime
- File-System has issues, needs fixup or disk replacement... may be restore from other backup-media, that causes delay and may require some missing files (due to backup time and crash) to be fixed up with help of other storage-nodes replica.

I Think restoring files in a distributed file-system to nodes that had some kind of trivial issues is not a reason to punish/disqualify a node that ran good for 2 (nearly 3) years!
