### ISSUE TITLE
Node code-hardening and improved auto-recovery / garbage collection

### ISSUE THREAD

**Issue by cryptocoinguru** [storj/storj#5321]
There are sometimes strange problems like piececake monitor errors or even sqlite/db's corruption or duplicate/invalid entries which are hard to find and even more hard to fix by operators. I had this myself which caused so much downtime that my node finally was disqualified one day later. I've fixed it after hours but it was finally waste of my time trying to bring the node up again due to the disqualification I got later.

This are no operator issues, it's an issue in STORJ node which obvisously can't handle such errors in a better way trying to backup such sensible db files, trying sqlite corruption check/cleanup itself or fixing duplicate/invalid db entries which cause the node to restart again in loop being offline and finally disqualified even if an operator is on it trying to give his best to fix that by hand.

This should not happen as operator's should not be punished for issues caused by the node software itself.

So what can be done to do some code-hardening and modules trying to do some kind of improvement?
-  garbage-collection?
- auto-repair f.e. sqlite check/repair
- backing up sqlite-files regulary and doing some kind of rollback/restore for db's causing issues?

Related #5319

**Comment by typoworx-de** [comment]
see:
- DEBUG Fatal error: infodb: UNIQUE constraint failed: bandwidth_usage_rollups.interval_start
https://forum.storj.io/t/debug-fatal-error-infodb-unique-constraint-failed-bandwidth-usage-rollups-interval-start/698/4?u=alexey
- Fix for piececake monitor issue
  https://forum.storj.io/t/node-having-issues-after-operating-for-long-time-without-problems/20306/13

related:
- https://github.com/storj/storj/issues/1869

**Comment by cryptocoinguru** [comment]
see:
- DEBUG Fatal error: infodb: UNIQUE constraint failed: bandwidth_usage_rollups.interval_start
https://forum.storj.io/t/debug-fatal-error-infodb-unique-constraint-failed-bandwidth-usage-rollups-interval-start/698/4?u=alexey
- Fix for piececake monitor issue
  https://forum.storj.io/t/node-having-issues-after-operating-for-long-time-without-problems/20306/13

related:
- https://github.com/storj/storj/issues/1869

**Comment by littleskunk** [comment]
Duplicate: https://github.com/storj/storj/issues/4213
