### ISSUE TITLE
Discuss about "disqualification" to be temporary or final depending on case

### ISSUE THREAD

**Issue by cryptocoinguru** [storj/storj#5322]
Node disqualification can happen without that an operator does stupid things caused f.e. by storj-node internal issues (see #5319).

The disqualification should be temporary and there should be options for super-users to allow to remove the disqualification and bring the node back to normal operation if the operator can approve that the issue was f.e. caused by bug/node internal issue that was not caused by permanent server-downtime or something else is in operators responsibility.

A final disqualification will - at least me, as just happend, think about doing a final shutdown and quit this project as it's not funny to start again from scratch needing to get good reputation in the network.

**Comment by littleskunk** [comment]
> The disqualification should be temporary and there should be options for super-users to allow to remove the disqualification
As a super user, I am able to remove the disqualification. That means this enhancement is already implemented.

**Comment by cryptocoinguru** [comment]
Good to know for future. Since long discussion in storj forum I were told it is final and therefore there were no other way than destryoing my node running nearly 2 years now. So this info comes far too late :-/
