### ISSUE TITLE
Drop SETUP=true env/flag which can cause accidently node quit/disqualification/data-loss

### ISSUE THREAD

**Issue by cryptocoinguru** [storj/storj#5323]
For intial setup the user should use SETUP=true env for STORJ-Node. I've recently had a node that had fails (restart loop due to some strange errors), trying to fix it up I've later tried SETUP=true to get it back in operation. Later after my note was disqualified I've got told this is totally stupid to do that.

So if it is that stupid and dangerous why even is there the need for operator to manually tell the node to do first-time setup?! I'm pretty shure the STORJ-Node can recognize it has no config.yaml and missing db's or even try to check if the node-identity was online once ago yet?

Long story short... STORJ-Node should remove SETUP=true flag and check itself if it needs to run setup-routine to create config.yaml, initial sqlite db's and folder inside storage-path. This is nothing an operator should do and should not even be possible if it is such dangerous and leads to node disqualification, possible loss of existing storage-data, database corruption and such sh*t.

It's totally disappointing and destroys the community of operators one gets punished for problems that are caused by storj-software and not a real problem the operator is responsible for like server-downtime and so on!

Related
#5319

**Comment by littleskunk** [comment]
This is not a bug it is a feature. Once upon a time we had no setup flag and the storage node would automatically create a new config when needed. The problem with that is that it also disabled a bunch of safety checks. If you mount the wrong directory the storage node will simply create a new directory and start from there. The outcome is a nice disqualification for losing the old files. Having the setup flag in place allows the operator to tell the storage node to create the directory only once and crash every time something is wrong with the directory instead of just creating a new one silently.

**Comment by thepaul** [comment]
If SETUP=true destroyed your node, that is a severe bug. It should not overwrite an existing config. Do you know how, specifically, it destroyed the node?

**Comment by cryptocoinguru** [comment]
@thepaul thanks for reply:
Well I'm not absolutely shure at all, but see #5319 for the errors. Piececake-Monitor complained about wrong storage reported (obviously the max-storage wasn't available as I still had it in use with my node storing data). Before that the info.db reported strange errors making the node restart in loop (restarted due to docker restart policy "unless stopped).

Therefore I've opened some tickets which may address some of these issues I think that happened.

May be.. this was some strange edge case that it happened due to SETUP=true. I don't know. Funnily during setting up a new node/identity SETUP=true didn't fire-up the initialisation I had to do by hand inside container CLI and then it worked.

**Comment by cryptocoinguru** [comment]
@littleskunk:
>  If you mount the wrong directory the storage node will simply create a new directory and start from there

I've thought about that. I think it's possible to determine wrong mount:

1. The target mount should have at least as much storage as the STORAGE-Quota given to the node to be possibly the storage-mount. Next you could check for the directories  that should be contained in storage (config/) path.
2. Furthermore it should not contain *.{cert,key} files, because this would indicate it isn't the config/storage mount, but identity. If the dir contains these files it is identifier mount.

I think these are simple aspects are good enough to determine wrong mount of directories inside the docker-container, so that these mounts are not mixed up with wrong data and an error could indicate the operator what's wrong.

**Comment by littleskunk** [comment]
All that is implemented. The text you quote would be if we remove the behavior around SETUP=true.
