### ISSUE TITLE
Bucket inconsistency between uplink and aws s3 clients

### ISSUE THREAD

**Issue by leszko** [storj/storj#5347]
**Description**

Objects in the buckets are different while accessing via uplink and different via AWS CLI.

**Screenshots**

**Steps to reproduce the issue:**

1. Create a bucket using AWS CLI

```
aws s3 --endpoint=https://gateway.storjshare.io mb s3://samplebucket
```

It's visible using the Uplink CLI

```
uplink ls
CREATED                NAME
2022-11-24 16:23:22    samplebucket
```

2. Upload a file using AWS CLI

```
aws s3 --endpoint=https://gateway.storjshare.io cp source.mp4 s3://samplebucket
upload: source.mp4 to s3://samplebucket/source.mp4
```

This file is not visible via uplink (but is visible via AWS CLI)

```
uplink ls samplebucket
```

**Describe the results you expected:**

I think the results should be the same for using both clients.

**Describe the results you received:**

Uplink does not see the file, while AWS CLI sees the uploaded file

**Possible Fix**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Logs:**

```
(paste your logs here)
```

**Your environment**

- Operating system and version:
- Additional environment details (Raspberry PI, Docker, VMWare, etc.):

**Comment by amwolff** [comment]
Is there a chance you are using a different encryption passphrase to view the contents of that bucket than the one you used for uploading with AWS CLI? The easiest way to check this would be to use the same access grant for Uplink CLI that you registered to get S3 credentials. You can also try viewing the contents of that bucket using `uplink ls --encrypted sj://samplebucket` to verify object is still there, but there's an encryption passphrase mismatch.

**Comment by leszko** [comment]
That was actually the case. Thank you for your help @amwolff
