### ISSUE TITLE
Problem with navigation for "Buckets" screen

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5361]
Problem ->while using "back" button in browser -> in the request body we have parameter "search" prefilled with user email 
As a result screen with "No results found"
NOTES: same for buckets on the Dashboard screen
see video

https://user-images.githubusercontent.com/14928042/204806745-83bfdd4a-0d4b-4f67-8ad0-068da7956af1.mp4

AC:
- the user email should not appear in the `Search` of the request body

**Comment by stoweandi** [comment]
Note: we don't think the parameters should be listing the user's email at all

@andriikotko is this the project owner's email or is this the logged-in user's email?
