### ISSUE TITLE
Remove all observers that were utilized by the segments loop package.

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5368]
We need to remove leftovers after moving to ranged loop. We need to check and cleanup:
* repair
* audit
* GC
* graceful exit
* metrics
* node tally

Main work will be to remove old chores and tests.

Acceptance Criteria:
* remove all unused code after switching to ranged loop from segments loop

**Comment by shaupt131** [comment]
Most of the work is done here, just need one final change.
