### ISSUE TITLE
Collect traces about Time to First Byte (ttfb)

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5376]
The purpose of this ticket is for us to collect data about TTFB so that we can start to understand what kind of improvements we should consider making. 

https://docs.google.com/document/d/1wRM0VczKD3ckteyEuU9dG9WsHSfJpp7EJ2xScwVMGac/edit#

https://storj.slack.com/archives/C03HL81FLRK/p1669657962142509?thread_ts=1669656186.098049&cid=C03HL81FLRK

**Comment by elek** [comment]
Closing it for now. We can collect more data / create special plan for TTFB when we will focus to it. 

Right now we optimize the 4mb upload/download performance.

Looks to be better to keep issues only for actionable items. Ideas can be collected in notes.
