### ISSUE TITLE
Measure upload / chunk size usage

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5377]
We already identified that the download doesn't use ideal chunk sizes:

https://hackmd.io/WtW63FkeRjyfee0JbKywug

Upload may have same problem, we should check it.

Exit criteria: 
 If there are possible problems, let's prove it with a performance report like the above one.

**Comment by elek** [comment]
I am closing this. I think latest proposal from JT covers this one. We can take care of this again when we see this area of the next bottleneck...
