### ISSUE TITLE
Investigate TTFB issues

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5378]
Would be great to understand what is the biggest bottleneck of having weak time-to-first-bytes (eg. 800-1000 ms during a 10Mb download).

Initial conversation: https://storj.slack.com/archives/C03HL81FLRK/p1669716402656379

 * [ ] check tls options and possible improvements, especially resumeable TLS connections
 * [ ] collect traces

**Comment by iglesiasbrandon** [comment]
@elek is this issue still valid? I thought we had collected traces and other things to further understand TTFB issues.

**Comment by elek** [comment]
I have some traces, and have a rough idea what's wrong with the TTFB (mainly the default usage of `sync2.Copy` which requires to read full 32k buffer before doing anything).

However the first parts (TLS resumption) is not clearly researched. It may help us to give better performance even with using normal TCP (not QUIC, NOISE or TCP Fast Open)

So it's still valid, but not sure if we should keep it open or not. There are more important steps right now, IMHO...

**Comment by iglesiasbrandon** [comment]
ok let's go ahead and close this issue for now and we can revisit it when we are ready to work on TTFB optimizations. @elek @shaupt131
