### ISSUE TITLE
Log segments that have been repaired by the repair workers

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5380]
### Description 

When a segment is repaired but one of the repair workers, I want a log to be created of it so that we can start to understand a segment's lifespan on the network. This will allow us to look at the logs to determine if we encounter issues. 

### Acceptance Criteria: 
- The log needs to have enough information to identify what piece is being repaired

### What we can answer with these kinds of logs:
- How many times has a specific segment been repaired?
- How often do the same segments get repaired?

### Open Questions: 
- Is this something that we should use one of the 'kits' for? (monkit or eventkit)?

**Comment by iglesiasbrandon** [comment]
@onionjake @jtolio @ethanadams @thepaul do you all think this ticket is till relevant? it was created during an emergency but I'm not sure if it's still useful.

**Comment by thepaul** [comment]
We'd probably get most of the possible benefit just by adding some log lines. It's at least worth doing that.

**Comment by iglesiasbrandon** [comment]
Thank you, @thepaul. I updated the description a bit based on your comment.

**Comment by iglesiasbrandon** [comment]
this issue is stale, if this comes up we will open a new issue.
