### ISSUE TITLE
Decide on direction for "custom state field" for users

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5382]
We want to be able to set arbitrary user-specific settings/states so that we don't need to do db migrations for each new setting/state we end up adding 

goal: We want to get ahead of adding multiple columns to the users table whenever we need to add a specific setting/state to a user

**Comment by mobyvb** [comment]
there might be a few options for this
* internal pb, similar to "online tracking" for nodes. You add a bytes column to the table, then marshal a protobuf into bytes, then store these bytes in the column. When reading a row, you unmarshal the bytes into the protobuf
    * has a strict schema based on protobuf (could be good or bad, idk)
    * can't query values within these columns
    * we have a precedent for this, but we should probably avoid it if we can do one of the other options
* jsonb - (cockroach should support this)
    * TODO is this supported in dbx?
    * https://www.cockroachlabs.com/docs/stable/jsonb.html
    * e.g. values for light/dark mode: 'lightMode: true`
* array of strings (cockroach has single dimensional array)
    * TODO is this supported in dbx?
    * https://www.cockroachlabs.com/docs/stable/array.html
    * can get O(logn) for search if list is sorted
    * e.g. values for light/dark mode: `lightModeOn`, `lightModeDetect`

examples of what we would want to use it for
* preferences, e.g. true/false for "light mode" or something
* custom content. e.g. "dashboard video" - introductory video for new user, or more advanced video for a user who has uploaded a lot of files

**Comment by jewharton** [comment]
DBX uses the `json` type which translates to `jsonb` for Cockroach and Postgres. DBX lacks a string array type.

**Comment by mobyvb** [comment]
see thread here https://storj.slack.com/archives/CAQV0AE2Z/p1672765169504039
we may want to consider an additional table with a 1-1 relationship with `users`

**Comment by mobyvb** [comment]
TODO - mark this ticket as done and create a new ticket for a "user config" (or similar) table that has a 1-1 relationship with `users`

**Comment by mobyvb** [comment]
follow up ticket: https://github.com/storj/storj/issues/5472
