### ISSUE TITLE
Release-v1.69 Test Admin UI with oauth

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5387]
[c1ed5c0](https://github.com/storj/storj/commit/c1ed5c0) satellite/{admin,ui}: implement changes for oauth2 proxy

**Comment by ihaid** [comment]
Before proceeding, you should make sure your storj-up setup includes the satellite-admin service. If you’re using the latest storj-up, running init will not include satellite admin by default.
Run storj-up add admin to add the satellite-admin service to your compose file.
Add the following volumes to the newly added service;
volumes:
    - type: bind
      source: /path/to/binary/of/satellite
      target: /var/lib/storj/go/bin/satellite
      bind:
        create_host_path: true
    - type: bind
      source: /path/to/storj/satellite/admin/ui/build/
      target: /var/lib/storj/storj/web/satellite/
      bind:
        create_host_path: true
3. Add STORJ_ADMIN_ALLOWED_OAUTH_HOST: localhost:4180 (the configured oauth2 proxy url) to the environment of the service.
There are two ways to go about setting up the proxy. After any of these steps, you will be set to test [this change](https://review.dev.storj.io/c/storj/storj/+/8878), PS: remember to rebuild your binaries after checking out the change also build the admin UI by navigating to /path/to/storj/satellite/admin/ui/build/ and running npm run build
A. Separate compose files for Storj-up and the proxy
Clone [the OAuth2-proxy code](https://github.com/oauth2-proxy/oauth2-proxy)
Open [proxy-dir]/contrib/local-environment/oauth2-proxy.cfg
change the value of upstreams to http://host.docker.internal:9080/ (Mac and Windows) or 172.17.0.1:9080 (Linux) (the admin API runs on port 9080)
open [proxy-dir]/contrib/local-environment/dex.yaml
take note of email under staticPasswords; you will use that to log in.
you can add your own email & password hash.
just make sure to add the new email’s domain to [proxy-dir]/contrib/local-environment/oauth2-proxy.cfg’s email_domains config
B. Add to Storj-up compose file
follow the steps in (A) that involve modifying files
copy the modified files to the location of your Storj-up compose file
modify your compose file to look like this;
version: "3.4"
services:
  .............
  # existing services
  .............
  oauth2-proxy:
    container_name: oauth2-proxy
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.4.0
    command: --config /oauth2-proxy.cfg
    ports:
      - 4180:4180/tcp
    hostname: oauth2-proxy
    volumes:
      - "./oauth2-proxy.cfg:/oauth2-proxy.cfg"
    restart: unless-stopped
    networks:
      dex: { }
    depends_on:
      - dex
  dex:
    container_name: dex
    image: ghcr.io/dexidp/dex:v2.30.3
    command: dex serve /dex.yaml
    ports:
      - 4190:4190/tcp
    hostname: dex
    volumes:
      - "./dex.yaml:/dex.yaml"
    restart: unless-stopped
    networks:
      dex:
        aliases:
          - dex.localhost
      etcd: { }
    depends_on:
      - etcd
  etcd:
    container_name: etcd
    image: gcr.io/etcd-development/etcd:v3.4.7
    entrypoint: /usr/local/bin/etcd
    command:
      - --listen-client-urls=http://0.0.0.0:2379/
      - --advertise-client-urls=http://etcd:2379/
    networks:
      etcd: { }
networks:
  dex: {}
  etcd: {}
After any of these steps,
go to http://localhost:4180/ in your browser
the proxy should initiate a log in flow, after which you should be redirected to the admin UI.
You can also go directly to the admin UI at http://localhost:9080/; nothing will change on the UI but making a request without filling the token field should not work (it works in certain situations now, which i’m working to resolve)
if anyone encounters a problem, please reach out to me; maybe, there’ll be something wrong with my steps.

**Comment by ihaid** [comment]
https://github.com/storj/storj/issues/5072
