### ISSUE TITLE
Admin API: Enable/set project limits for a customer's existing and new projects

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5395]
When a partner/customer of ours needs specific limits for all existing and new project limits to be higher, I want to be able to access the admin api and adjust said partner's projects to be at a specified limit, and I want all new projects the partner/customer creates to be created with those new set limits. _So that the customer doesn't have to wait for us to go into the admin ui and adjust the limits of every new project they create_

AC:
- in admin ui all projects created for that customer will have the set project limits applied to all current and future projects

Note: see similar functionality that's already implemented in the freeze / unfreeze admin endpoint

**Comment by lizzythomson** [comment]
Deployed in v1.73.0 [1b22994](https://review.dev.storj.io/plugins/gitiles/storj/storj/+/1b229946310824c9719c0a1f0608c78432a410b5)
