### ISSUE TITLE
Create DB table for account freeze events

### ISSUE THREAD

**Issue by jewharton** [storj/storj#5396]
Add a new database table in the satellite to store account freeze events.

**AC:**

* The table should contain columns for the event's ID, the event's type, the timestamp of the event's creation, the ID of the user that the event is for, and the user's limits at the time they were frozen.
* The table's key should be the event ID.
* No column should be nullable except for the column containing user limits because it is undefined for warning events.

Blueprint: https://github.com/storj/storj/blob/main/docs/blueprints/automatic-account-freeze.md

**Comment by mobyvb** [comment]
1.70 https://github.com/storj/storj/commit/021c98c17a79c3
