### ISSUE TITLE
Graceful exit: clean graceful_exit_segment_transfer_queue tables

### ISSUE THREAD

**Issue by Fadila82** [storj/storj#5399]
We had a bug in graceful exit that made some exit finish without having processed all transfer queue items. This bug resulted in the graceful_exit_segment_transfer_queue table growing.

Since this bug has been fixed, there have been no new 'ungraceful' exit, but `graceful_exit_segment_transfer_queue` tables haven't been cleaned. We can for example see problematic items for europe-north1 with this redash query https://redash.datasci.storj.io/queries/2443

We have to remove these items. There was a command about for this that could be updated, or we could choose to run an sql query to delete them.

**Comment by iglesiasbrandon** [comment]
Spoke about this during sprint planning and we want to update that tool to do this.

**Comment by Fadila82** [comment]
state of our nodes table:


|  satellite  |  total | exited  | disqualified | disqualified [1-3] months | disqualified > 3 months |
|---|---|---|---|---|---|
|  AP1  |58,012 |   2,007 | 37,145 | 1,688 | 34,613 |
|EU1 |  58,111 | 1,959 | 37,357 | 1,774 | 34,626 |
| europe-north1 |53,772|1,786  | 33,151 | 1,662 | 30,835 |
| saltlake  |  55,741 | 1,840 | 35,004| 1,664 | 32,489 |
|   US1 | 58,779 |1,961  | 37,460  |1,792 | 34,678 |
| US2 | 45,247 | 1,106 | 25,175 | 1,660 | 22,867 |

**Comment by iglesiasbrandon** [comment]
@ethanadams @thepaul @mniewrzal is this ticket still relevant and worth doing?

**Comment by thepaul** [comment]
Yes

**Comment by shaupt131** [comment]
@thepaul with the GE revamp, is this still relevant?

**Comment by thepaul** [comment]
It's not, exactly, but it brings up the need for a final graceful exit revamp ticket: remove all the old code and drop the old tables. We couldn't do that until we'd had a release and switched everything over to the new style of graceful exit.

**Comment by shaupt131** [comment]
Ticket created: https://github.com/storj/storj/issues/6484

Closing this issue.
