### ISSUE TITLE
Add publicId to be returned by getProject endpoints

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#5408]
Add publicId to [graphqlProject fields](https://github.com/storj/storj/blob/746c3b2d832dbba051d8d349557380c949f37e8a/satellite/console/consoleweb/consoleql/project.go#L109) to be returned by get project endpoints.

AC:
* All Graphql queries/mutations that return the project object should include the `publicID` field.

**Comment by mobyvb** [comment]
1.71 https://github.com/storj/storj/commit/5138bb1e4fe755
