### ISSUE TITLE
Change the delete-by-name endpoint to support both publicId and id

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#5410]
The [/delete-by-name](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/server.go#L332) endpoint should support both projectID and publicID query parameters.
* Update the [call to this endpoint](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/web/satellite/src/api/accessGrants.ts#L141) to use publicID instead of projectID.

AC:
* this endpoint should be able to be called using either (project) `publicID` or `id`

**Comment by mobyvb** [comment]
1.71 https://github.com/storj/storj/commit/05c83a5539cfe7524136
