### ISSUE TITLE
Update project endpoints to interpret their id params as publicId or id

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#5411]
Update the following endpoints to support both project id and publicID. They should first interpret the `{id}` param as `publicID` and fallback on `id` if that fails.
* [/api/v0/projects/{id}/usage-limits](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/server.go#L269).
* [/api/v0/projects/{id}/daily-usage](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/server.go#L277).
* [/api/v0/projects/{id}/salt](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/server.go#L258).

AC:
* These endpoints should be callable using either project `id` or `publicId`

**Comment by mobyvb** [comment]
1.71 https://github.com/storj/storj/commit/0773b4efbc58a
