### ISSUE TITLE
Update generated project APIs to support both project id and publicId

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#5412]
Change these to first interpret the {id} param as `publicID` and fallback to `id` if that fails.
* [/update/{id}](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/consoleapi/gen/main.go#L39)
* [/delete/{id}](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/consoleapi/gen/main.go#L51)
* [/apikeys/{projectID}](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/consoleapi/gen/main.go#L96)
* 
Add publicID as a query param to these
* [/bucket-rollup](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/consoleapi/gen/main.go#L69)
* [/bucket-rollups](https://github.com/storj/storj/blob/9fedc21fea1d38fa8e19f5e26cce42bf0875a547/satellite/console/consoleweb/consoleapi/gen/main.go#L83)

AC:
* These endpoints should be callable using project `id` or `publicId`
* Communicate to users who have generated API keys that “private ID” will eventually be deprecated.

**Comment by mobyvb** [comment]
1.71 https://github.com/storj/storj/commit/5da2544e6271d8
