### ISSUE TITLE
Update the frontend to reference publicId from the backend instead of id

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#5413]
Rename all id references to publicId in [api/projects.ts](https://github.com/storj/storj/blob/3c3bff6364b83aef9f66559e6087b4e573ae3c73/web/satellite/src/api/projects.ts) . e.g.: L71, L60, L37, L47, L93, L126, L257

This should be done after all project endpoints are changed to support both `id` and `publicId`

AC: 
* The frontend only uses project publicId

**Comment by mobyvb** [comment]
The other tasks relating to migrating api endpoints to accept/return public ID should be done before starting on this task

**Comment by mobyvb** [comment]
1.73 https://github.com/storj/storj/commit/e8cd096eecf16be51523546338fa
