### ISSUE TITLE
Finish wiring up `ranged-loop` command

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5414]
Recently we merged code to have new satellite command `satellite run ranged-loop` but its not fully operational. For example is has mocked  `RangeSplitter`. With this task we should cleanup ranged loop command, peer and service (if needed) to be able to run ranged loop as a separate command against real DB. It should be possible to enable only Metrics observer.

Ticket is only related to code changes and manual testing on local machine.

Acceptance Criteria:
* cleanup ranged loop command, peer and service to be able to run this command against real environment (qa or prod)
* only Metrics observer should be enabled
* test is manually with storj-sim or storj up (preferable)

**Comment by Qweder93** [comment]
https://review.dev.storj.io/c/storj/storj/+/9234
