### ISSUE TITLE
Layer 1 zkSync warning message

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5418]
Add warning message to STORJ token modal

Designs: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=14093%3A97037&t=fGb19KNqtgLH2cR8-3

**Comment by NiaStorj** [comment]
story points needed. Placed in the "effort field" @wilfred-asomanii

**Comment by wilfred-asomanii** [comment]
done @NiaStorj

**Comment by mobyvb** [comment]
1.70 https://github.com/storj/storj/commit/ab8f22a6d0c87577c
