### ISSUE TITLE
Write testplan for ranged loop

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5423]
https://storjlabs.atlassian.net/wiki/spaces/ENG/pages/2434531336/WIP+-+Metainfo+Loop+Sharding
Slack channel #feature-ranged-loop

**Comment by littleskunk** [comment]
Some notes from the meeting (yes that one legendary meeting you have not attended. I am not going to mention which one it was)

1. The ranged loop is for services that use the segment loop. -> Customer tally job is out of scope because it used the object loop.
2. Services using the segment loops are: graceful exit, storage node tally, audit reservoir sampling, repair checker, garbage collection
3. We can start the ranged loop without enabling any services. The segment loop would still report in metrics.
4. We want to do small steps enabling the ranged loop. Maybe start with graceful exit to see how stable it is. Garbage collection should be the last one. The plan is to enable that very late after all the other services have been running stable in production for some time.

**Comment by littleskunk** [comment]
https://github.com/storj/storj/tree/main/docs/blueprints/storagenode-graceful-exit
https://github.com/storj/storj/blob/main/docs/blueprints/audit-v2.md
https://github.com/storj/storj/blob/main/docs/blueprints/garbage-collection.md

**Comment by nadimhq** [comment]
<google-sheets-html-origin><style type="text/css"></style>

Test Scenario | Test Case | Description | Comments
-- | -- | -- | --
Garbage Collection General | Creation of Bloom filter | Create a test dataset of pieces of data and corresponding storage node IDs using pointerdb and then use the test dataset to create a bloom filter using the satellite's algorithm to verify that the integration of the bloom filter creation process with the data repair checker loop does not cause any additional overhead to the pointerdb | The test makes sure the Bloom filter is correctly created and the integration with the pointerdb does not cause any additional overhead . Also is the bloom filter creation process still integrated with the data repair checker loop? reword tc if thats the case
  | Push of Bloom filter to storage nodes | Create a test network of storage nodes and then use the satellite to push a new Bloom filter for each storage node in the network to verify that each storage node correctly receives the filter |  
  | Processing of Bloom filter by storage nodes | First, add some test data to each storage node that should be considered as garbage for this test, then have each storage node process the received Bloom filter by checking for pieces of data not included in the filter and older than the filter's creation date to verify that the storage nodes correctly identify and delete the test pieces of data considered garbage | are there cases where there can be piece failures and data considered garbage can't be deleted?
  | Handling of missed pushes (Storage Node Offline) | Create a test network of storage nodes and have some nodes simulate being offline during a push of the Bloom filter and lastly verify that the offline nodes correctly process the next push they receive and delete the correct pieces of data | offline duration? nodes that are offline extended periods? separate tests for that? we probably have (have not checked yet)
  | Overall garbage collection process E2E | Add test data to the storage nodes and simulate different scenarios such as data being replaced, deleted, or clients stopping payment and then use the satellite to notify the storage nodes of the garbage pieces and verify that the storage nodes correctly delete the data | just an e2e of the first three tests to make sure overall process works
  | Clock accuracy | Create a test network of storage nodes and have some nodes simulate inaccurate clock and then verify that the storage nodes with inaccurate clock will suffer reputation failure |  
  | Test on Saltlake | Test Garbage Collection on saltlake after change to verify that it can handle a large number of pieces and storage nodes |  
  | Performance | Measure the time it takes for the satellite to create the bloom filter and push it to the storage nodes, the time it takes for a storage node to process the bloom filter, and the memory usage on the satellite and storage nodes | make sure performance increases with ranged loop
Audit Resoirvoir Sampling | Reservoir Sampling Algorithm | Create a test dataset of segments and corresponding nodes. Use the reservoir sampling algorithm to select segments for each node. Verify that the segments selected for each node are chosen with uniform probability |  
  | Creation of The Audit Queue | Use a test network of nodes to simulate different scenarios such as new data being added or nodes being vetted. Use the audit observer to create the audit queue and verify that the segments selected for each node are added to the queue in a random order. |  
  | Selection Of Segments for Audit | Use the audit workers to select segments from the audit queue and verify that these segments selected for audit are chosen with uniform probability for every node. |  
  | Separate Reservoir for Unvetted Nodes | Use a test network of nodes and simulate different scenarios such as new data being added or nodes being vetted. Use the audit observer to create the audit queue and verify that the segments selected for each node are added to the queue in a random order with different reservoir size for unvetted and vetted nodes. |  
  | Performance | Measure the time it takes for the audit observer to create the reservoir sampling and the time it takes for the audit workers to select segments from the queue. Measure the memory usage of the system. | make sure performance increases with ranged loop
  | Test on Saltlake | Test ARS on saltlake after change to verify that it can handle a large number of segments and nodes. |  
Metrics | Collection of Metrics | Verify that all Storj peers (i.e. satellite, storage node, uplink, etc) are still able to correctly collect the metrics specified in the telemetry client |  
  | Storage of Metrics | Verify that metrics are still correctly stored in the specified datastores (postgres, influxDB, rothko) and that they are stored in the correct format and with the correct data |  
  | Data Visualization & Accessibility of Metrics | Verify that the metrics data from influxDB are still correctly fed to the grafana dashboard and that the dashboard is able to correctly display the metrics data |  
Graceful Exit | Graceful Exit Piece Gathering | Verify that the satellite is still able to correctly gather pieces that need to be transferred from a storage node for graceful exit when it is initiated |  
  | Graceful Exit Failure/Error Prevention | Verify that the protocol for transferring pieces from one storage node to another is still working as expected, including retransmission of pieces in case of errors or failures |  
  | Graceful Exit Reports | Verify that the satellite operator is still able to create accurate and complete reports for exited storage nodes and that the reports include all necessary information for releasing escrows |  
  | Ungraceful Exit Handling | Verify that the system is still able to handle ungraceful exits correctly, including cases where the storage node doesn't transfer pieces, transfers pieces incorrectly, is too slow to transfer pieces, or decides to terminate the process. |  
  | Graceful Exit Failure Handling | Verify that the system is still able to handle failures like network failures, system failures, and other failures that may occur during the graceful exit process. |  
  | Graceful Exit Error Handling | Verify that the system is still able to handle errors like piece hash mismatch, error in piece transfer, and other errors that may occur during the graceful exit process. |  
  | Graceful Exit Termination | Verify that the system is still able to allow SNO to terminate graceful exit |  
Repair Checker | Check for Missing Pieces | Verify the repair checker can still use the necessary info to do checks for missing pieces and insert segments into injured_segments table |  
  | Add Segment to Queue | Verify that repair checker can still add segment to the queue |  
  | Ensure Check | Verify that repair checker should be able to check before a satellite restart |  
  | Healthy Segments | Verify that repair checker could still clean the queue of segments that are deemed healthy |  
  | Initiate Repair | Verify that repair checker initiates repair when # of healthy pieces is less than or equal to repair threshold or greater than or equal to min required pieces in redundancy |  
  | Irreparable Segments | Verify that repair checker can still monitor irreparable segments |  
Storage Node Tally | At Rest Usage | Verify Tally can still calculate data-at-rest usage correctly |  
  | Live Accounting 1 | Verify that by the end of tally iteration one can have the project totals from cache seen during metainfo loop and assigned to latestLiveTotals |  
  | Live Accounting 2 | Also verify that the delta between latestLiveTotals and initialLiveTotals is correct with respect to previous test |

**Comment by littleskunk** [comment]
Nodes from our meeting:
```
Challanges with the new ranged loop
	2 or more workers might finish at different times. When is the following worklfow allowed to start? For example repair workers are allowed to start early. Do we need alerts?
	The results of the workers might have to be compined. For example the bloom filter for garbage collection.
	One of the workers might run into an error. Are the following processes allowed to start or do they require a complete run of all workers. For example bloom filter creation.
	
General tests
	Overlap of ranges? Is the range including or excluding the start and end value? Split a range for 2 workers. Put at least 3 segments into the total range exactly on the start and end values.

Graceful exit
	2 workers finish with an hour difference. -> Graceful exits waits for the last worker. Don't start too early.
	1 worker finished and 1 worker errors out. -> Graceful exit doesn't start.
	Work results will be added to a database table. No additional combination of works results needed.

storage node tally
	storage node tally is not allowed to continue early. The results of all works is required before continuing. Tally calculation are based on the time difference between 2 runs.
	storage node tally is not allowed to continue in case of one worker erroring out. Don't comit incomplete results to the database.
	Work results need to be combined before commiting to the database.

audit reservoir sampling
	is not allowed to continue early. A complete run will look like random audits from the storage node perspektive. An early start would mean storage nodes will get audits only for a certain range.
	is allowed to continue in case on of the works errors out. If one of the workers errors out we better audit just the range that finished instead of no audits.
	needs to combine works results. We want random audits over all segments.

repair checker
	Is not allowed to continue early. It is allowed to commit work results into the database so that the repair worker can start. The problem is if I remember correct we delete all segments from the repair queue that the repair checker has not seen in the current run. That part of the code needs to hold off until all workers finished.
	is not allowed to continue if one worker errors out. Same explaination.
	Doesn't need to combine the work results. All workers can add segments to the repair queue while they are running. But it needs to wait with the repair queue cleanup code until all workers finished.
	More information: https://github.com/storj/storj/commit/c2525ba2b5e6e74a0e3fd5a2cdd758708bf314d7

garbage collection
	Is not allowed to continue early. The bloom filter would be incomple and delete segments that we still need.
	Is not allowed to continue if one worker errous out. Same outcome. We would lose segments.
	Has to combine work results. The storage node expects a single bloom filter at the moment.
```

**Comment by storj-antonio** [comment]
I didn't see a PR for this but this looks like good coverage. I think its good to send over to engineering for review, run it thru a spell checker first I think I saw a spelling mistake on my second iteration through.
