### ISSUE TITLE
Remove the 'type' column from nodes table

### ISSUE THREAD

**Issue by Fadila82** [storj/storj#5426]
The nodes table has a column 'type' that was used back in the kademelia times. This column is now useless and should be removed.

https://storj.slack.com/archives/CAQV0AE2Z/p1671747445455989

**Comment by egonelbre** [comment]
Let's also remove it from our protobuf.

**Comment by profclems** [comment]
All changes for this issue are merged except for the change that contains the migration that completely removes the `type` column (https://review.dev.storj.io/c/storj/storj/+/11501/). That is blocked for now and we would have to wait for all the other changes to be released. Then It will be safe to do the migration in the next release

**Comment by shaupt131** [comment]
Data team to make changes to queries before this gets merged.

**Comment by shaupt131** [comment]
@profclems, @grafael has completed https://github.com/storj/team-delivery/issues/478, so this ticket should now be unblocked.

**Comment by profclems** [comment]
There was one last thing to remove before we can completely drop the column in the migration: removing dbx references to the type column https://review.dev.storj.io/c/storj/storj/+/11788. We will wait for that change to be release before adding a migration to drop the column.

**Comment by shaupt131** [comment]
Pending a release before we can merge the final change.

**Comment by shaupt131** [comment]
@profclems with the recent release, is this now unblocked?  If so, what can we do for you?

**Comment by profclems** [comment]
@shaupt131 final change is in code review now https://review.dev.storj.io/c/storj/storj/+/11878

**Comment by iglesiasbrandon** [comment]
hey @profclems @shaupt131 im going to close this issue since its been deployed to production.
