### ISSUE TITLE
Banner blocks billing page tabs

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5428]
Note - this may require new designs, but I wanted to track it somewhere. Maybe there is an easy fix that doesn't require new designs, but I don't know where a banner overlay could be positioned such that it won't inhibit UI interaction in any way

I noticed this for the new "your account is frozen banner", but it may apply to other banners as well.
Reproduction steps:
* Create a new account and log in
* Go to the satellite admin (localhost:9080) and freeze the new account
* On refresh, there should be a banner indicating account freeze in the UI. Click the link to navigate to the billing page
* Notice that the banner overlaps with the tabs, so you cannot navigate around the billing page without closing the banner

AC:
* It is possible to navigate between tabs on the billing page without closing the banner

**Comment by iglesiasbrandon** [comment]
no longer an issue.
