### ISSUE TITLE
Remove the satellite/rewards package and associated DB columns

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#5432]
It seems that we are not using `satellite/rewards` package anymore after there was some data migration of the static data to be stored in the database.

A simple test was to pass `nil` to all the components that were receiving an instance of the `rewards.PartnerService`, but the CI crashed, see https://review.dev.storj.io/c/storj/storj/+/9228/1#message-26f2c52322b8cfd5beb25e5bca6e01ad8b1c3856

We know that the package is deprecated, the question is can we get rid of it?

Acceptance criteria:
- Investigate if `satellite/rewards` package isn't used anymore.
- If it isn't used or only used in some logic that is unused or only tests, remove the package and clean the code that depends on it, otherwise set the `Deprecated: ` doc comment in all the public API or of the full package (if that's possible with Go `Deprecated: ` comment) for not creating confusion.

**Comment by mobyvb** [comment]
This document references the rewards package, so we should probably update the docs if we remove the package: https://docs.storj.io/dcs/how-tos/configure-tools-for-the-partner-program

**Comment by mniewrzal** [comment]
When code from https://review.dev.storj.io/c/storj/storj/+/9421 will be merged and deployed we may still need to cleanup DB schema. At least I saw `parnter_id` column in several tables.

**Comment by wilfred-asomanii** [comment]
That's the next thing to do I think

**Comment by mobyvb** [comment]
I am going to move this back to "in progress" until we remove the unnecessary db columns

**Comment by mobyvb** [comment]
Moving to "blocked" until this change is deployed: https://github.com/storj/storj/commit/3679e29a93203ad19ce98e1d161007c3716328fa

**Comment by mobyvb** [comment]
I'm moving this back to "up next" because we did not end up fully removing the columns - we reverted one of the changes when the migration broke
See:
* https://review.dev.storj.io/c/storj/storj/+/10467
* https://storj.slack.com/archives/C0490040EDR/p1685567209173449
* https://storj.slack.com/archives/CTLAYRPQB/p1685564997362689
