### ISSUE TITLE
Review Audit Scaling Tests

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5437]
Review testplan and current testautomation.

There is one edge case we might have missed up until now. It is possible that a segment gets deleted right at the moment the storage gets the audit. In this situation, the storage node will return a piece not found error. Before the satellite applies an audit failure it should check if the segment is still valid. If the segment has been modified or deleted the storage node should not get any penalty. I am not sure if we have tests for that. If not we should add them.

This commit makes me wonder how a piecewise audit can check if the segment is still valid: [1854351](https://github.com/storj/storj/commit/1854351) satellite/audit: teach Reporter about piecewise audits
[a66503b](https://github.com/storj/storj/commit/a66503b) satellite/audit: Begin using piecewise reverifications

Testplan: https://github.com/storj/storj/issues/5043

thepaul is avialable for any question.

**Comment by ihaid** [comment]
https://storjlabs.atlassian.net/wiki/spaces/ENG/pages/2509013140/Jan-5+Node+Audit+Scaling+Prep+for+QA
