### ISSUE TITLE
My Account menu (and Billing) doesn't accessible on tablet or phone

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/storj#5445]
**Description**

My Account menu (and Billing) doesn't accessible on tablet or phone

**Screenshots**
![Screenshot_2023-01-05-20-32-50-174_com brave browser](https://user-images.githubusercontent.com/26858949/210792632-c1b4160f-6297-4c72-9477-f0ffcd62af7b.jpg)

**Steps to reproduce the issue:**

1. Open satellite UI on tablet/phone
2. Try to scroll down to **My Account** on the left side

**Describe the results you expected:**
You can tap **My Account** and select **Billing**

**Describe the results you received:**
The **My Account** menu is not accessible

**Your environment**

- Operating system and version:
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): Android 11 tablet Xiaomi Mi pad 5

**Comment by mbouzi** [comment]
@AlexeyALeonov is there any way we can get a video of this occurring? When testing, no matter the screen size, I'm able to access My Account through scrolling.

**Comment by mobyvb** [comment]
one
dot
seven
three
that's when this went out
confirmed by me

https://github.com/storj/storj/commit/12f884e80205913c
