### ISSUE TITLE
Navbar Satellite UI: Can't fully navigate with tab control

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#5449]
**Description**
After logging in, you are presented with the side navigation bar. You can use the tab button and keyboard inputs to navigate between the landing page (dashboard) and the side navigation bar. However, the tab interaction on the navbar is not clear and it only allows you to tab through the 'dashboard', 'buckets', 'access', and 'users' pages. The user should also be able to tab through 'my first project', 'resources', 'quickstart', and 'my account'. Currently, you can click on 'my first project', 'resources', 'quickstart', and 'my account' and then use tabbing to interact with them. The tab interaction with these tabs is responsive, but a mouse click is currently required

**Step to Reproduce**

1. Login to your account.
2. From the landing page (dashboard), use the tab control to navigate through the navbar and visually see your current location on the navbar.
3. Attempt to tab through the options in 'my first project', 'resources', 'quickstart', and 'my account' and open the links using tabbing and keyboard inputs, for example, create an access grant from 'quickstart'.

**Results**
It is **expected** that you should be able to tab through the side navbar and see your current location. Additionally, you should be able to tab through every selection that has multiple links, such as 'my first project', 'resources', 'quickstart', and 'my account'. However, in **actuality**, you are unable to tab through 'my first project', 'resources', 'quickstart', and 'my account'. When tabbing through 'dashboard', 'buckets', 'access', and 'users' in the side navbar, the selection is not highlighted, making it difficult to visually see what you are tabbing through.

**AC**- One can tab through the entire side navbar and access each dropdown. The tabbing should also be responsive, for example, if you tab through the navbar and currently have the 'buckets' link selected, it should be highlighted and it should be clear that pressing enter will open the 'buckets' page

https://user-images.githubusercontent.com/82845192/211220775-cdf243d8-942b-45f8-ba9e-d2f8ca4735c8.mov

**Comment by lizzythomson** [comment]
Deployed v1.75 [0559d19](https://review.dev.storj.io/plugins/gitiles/storj/storj/+/0559d19db574ad1708f7e4d292de41c39e8084f1)
