### ISSUE TITLE
Access Management Satellite UI- Can't fully customize encryption keys with tab spacing

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#5450]
**Description**
Upon landing on the access management page, you can use the tab button and keyboard inputs to select between generating access grants, S3 credentials, or API keys. Selecting one of these options opens a create access modal for the user. However, the tab interaction in the modal is not clear and does not allow you to select custom permissions, custom buckets, or custom duration using tab spacing and keyboard inputs only. Custom permissions is only selectable using tab spacing if one clicks on the dropdown for permissions in the first place. Bucket permissions does not work with tab spacing and keyboard inputs only even when the dropdown for bucket list is clicked. Tab spacing and keyboard inputs for Custom duration should at-least allow the first six timed options  forever, 24 hours, 1 week, 1 month, 6 months, or 1 year.

**Step to Reproduce**

1. Login to your account.
2. Go to Access grants page by clicking on the side navbar- Access.
3. Attempt to create an access grant using only tab and keyboard inputs; customize the bucket, the duration and the permissions.

**Results**
It is **expected** that you should be able to tab through the access grants page and easily create a custom access grant using tab and keyboard inputs, while customizing the bucket, duration, and permissions of the access grant. In **actuality**, you are unable to set up custom buckets, permissions, and duration for the access grant using only tab and keyboard inputs. Additionally, it is difficult to see on the user interface (UI) where the tab is currently located in the create access modal.

**AC**- One can tab through the creation process in the create access modal and access each dropdown for customization- Tab spacing and keyboard inputs for Custom duration should at-least allow the first six timed options; forever, 24 hours, 1 week, 1 month, 6 months, or 1 year. The tabbing should also be responsive. For example, if you tab through the types, it does not highlight the selected type, and you must use the space bar to see which type is selected. If the selected type was highlighted, it would be more user-friendly

https://user-images.githubusercontent.com/82845192/211221781-bd82c192-ceb3-4dcc-9f60-e703ba2ce4f5.mov

**Comment by mobyvb** [comment]
wait until https://github.com/storj/storj/issues/5511 is done before picking up
