### ISSUE TITLE
Satellite UI / Fix Storj logo

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5458]
The Storj logo is skewed when viewing the collapsed version of the navbar:

![Image](https://user-images.githubusercontent.com/3217669/211776877-3d0d8859-c01b-4e83-854b-80ac2e9909ec.png)

Also on mobile the logo is cut off on the bottom of the icon and the right of the DCS text:

![Image](https://user-images.githubusercontent.com/3217669/211776986-feb74f65-4307-4861-90a4-8a68d4ec572f.png)

Here is the logo in the Design Library figma:

https://www.figma.com/file/b3QhctHccKl3ihR8Q063Af/DCS-Design-Library?node-id=102%3A6&t=9yrXs4RCmeqzYzkK-0

**Comment by mobyvb** [comment]
1.72 https://github.com/storj/storj/commit/b9c0bbce2f18c6e
