### ISSUE TITLE
Satellite UI / Replace Cancel with Back button in Manage passphrase modals

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5463]
Replace Cancel with Back button in the Manage passphrase modals. Remove margin top from the buttons.

![Image](https://user-images.githubusercontent.com/3217669/211880915-9db92f2e-18bd-4a7a-b3fa-1480a3c76d23.png)

![Image](https://user-images.githubusercontent.com/3217669/211880914-2141af89-63d0-40f4-a914-20328e73b8c1.png)

![Image](https://user-images.githubusercontent.com/3217669/211880913-f8497a83-2145-4943-9ef8-23449e9a5c49.png)

**Comment by mobyvb** [comment]
1.71 https://github.com/storj/storj/commit/d76f764b72f223c82
