### ISSUE TITLE
audit/repair results in redundant reputation updates for certain nodes

### ISSUE THREAD

**Issue by cam-a** [storj/storj#5464]
The sql query to get node info for audits/repair excludes disqualified, exited, and offline nodes.
However, these nodes are still given an offline audit result. 
If any of these nodes are also disqualified, unknown audit suspended, offline suspended, or vetted, the reputation service will always determine that a reputation status change has occurred and update the nodes table with redundant data.
We recently implemented a system to notify SNOs when reputation states change, and these recurring updates are resulting in many duplicate notifications. 
Since these nodes are skipped in the query, we also don't have their email addresses. 

AC:
* redundant reputation updates due to false nil reputation values do not occur.
* node email is accessible by the reputation service

**Comment by thepaul** [comment]
Shipped since 1.72.2.
