### ISSUE TITLE
Implement a better way to purge records from project_bandwidth_daily_rollups

### ISSUE THREAD

**Issue by ethanadams** [storj/storj#5465]
There is a chore the runs every 7 days to purge data from `project_bandwidth_daily_rollups` that is older than 3 months.  Recently the delete query has been hanging for hours on EU1, gets stuck in a retry loop.  We need to investigate a better way to purge the table.

Things to investigate:
- Use CRDB TTLs?
- Add index?
- Other ideas: https://www.cockroachlabs.com/docs/stable/bulk-delete-data.html

**Comment by ethanadams** [comment]
Possible solutions:
- Add index
- Use CRDB TTLs
- See https://www.cockroachlabs.com/docs/stable/bulk-delete-data.html

**Comment by NiaStorj** [comment]
When can this get into a sprint @iglesiasbrandon

**Comment by Fadila82** [comment]
As it happened again last week and we had to kill the statement again, I've started working on this using the bulk-delete solution as it is more straightforward than using TTLs (which we haven't done yet I think). We can also try TTLs later if we want.

**Comment by mniewrzal** [comment]
Wondering if for time being we could just add as of system time to `DELETE FROM project_bandwidth_daily_rollups WHERE interval_day < ?` to avoid contention.

**Comment by NiaStorj** [comment]
Thank you @iglesiasbrandon

**Comment by mniewrzal** [comment]
We agreed that for now easiest thing will be to add index on `interval_day` and reduce interval between deletions to one day,
