### ISSUE TITLE
Create ranged loop statistics dashboard

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5468]
This dashboard will help us observe the ranged loop implementation. We will expand the metrics we have on this dashboard over time but below are a few we can start with. 

Some of the things we want on the dashboard
- entire segments table execution time
- each range execution time
- number of segments processed
- successes/ failures
- etc...

**Comment by shaupt131** [comment]
@Erikvv I believe this was your suggestion during our sync meeting.  Would you mind adding some context to the ticket with what you were thinking?

**Comment by Erikvv** [comment]
@shaupt131 like existing segment loop https://chronograf.datasci.storj.io/sources/3/dashboards/82?tempVars%5Bapplication%5D=satelliteproduction-storj&tempVars%5Binstance%5D=US1&lower=now%28%29%20-%2030d

![img](https://link.storjshare.io/raw/jvakv4ddjeprfyi6iqcbrgxy5nda/public/chronograph-metainfo-loop.png)

**Comment by mniewrzal** [comment]
Yes, something like this ^ will be needed for sure. I believe it should be part of Thanos where we have all official dashboard. I guess we would also need a ticket to make some alerting around ranged loop. Initially it would be just coping what we have for segments loop.

**Comment by iglesiasbrandon** [comment]
This ticket is blocked by https://github.com/storj/infra/issues/3534

**Comment by mniewrzal** [comment]
I started collecting things here https://thanos.qa.storj.rodeo/d/_BqW1cA4k/ranged-loop?orgId=1

**Comment by mniewrzal** [comment]
I collected most important things under this dashboard https://thanos.storj.rodeo/d/GzBO_K0Vz/ranged-loop?var-environment_name=storj-prod-satellite-slc&orgId=1&from=now-2d&to=now. We can improve it later according to our needs.

**Comment by mniewrzal** [comment]
Most important elements of dashboard are added. We will improve it on regular basis when we decide we need more monitoring.
