### ISSUE TITLE
Automatic detect queries which are doing full table scan 

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5471]
CockroachDB have special statement to list queries recently perform full table scans. We can try to integrate this feature with out unit tests. Rough idea is to collect queries before unit test and after and compare results. If something new will be detected then fail test. Initially we should try to apply this to metabase tests and if everything will be working as expected extend it to other DB tests.

https://www.cockroachlabs.com/docs/stable/show-full-table-scans.html

Acceptance Criteria:
* implement automatic detection for full table scan queries for `metabase` unit tests
* if full automated implementation won't be possible then we may consider just helper function which can be used while development to review full table scan queries manually e.g.
```go
// naming should be improved :)
queries := db.TestingCollectFullTableScans(ctx, ...)
defer func(){
   db.TestingCollectAndCompareFullTableScans(ctx, queries)
}()
```

**Comment by egonelbre** [comment]
There's https://www.cockroachlabs.com/docs/stable/show-full-table-scans.html. We could run it at end of each testplanet test (and other), and check whether there is anything unexpected.

While researching this, I recall some tables changing the indexing method based on how much content there is. e.g. if it's 10 rows, it's doing a full table scan -- so we might need to change crdb config it doesn't do that optimization.

**Comment by mniewrzal** [comment]
Yes, I started to play with it here https://github.com/storj/storj/issues/5471.

> While researching this, I recall some tables changing the indexing method based on how much content there is. e.g. if it's 10 rows, it's doing a full table scan -- so we might need to change crdb config it doesn't do that optimization.

Yeah, that might be needed.

**Comment by mniewrzal** [comment]
Using `SHOW FULL TABLE SCAN` query is a bit problematic as while doing tests on CI we are doing them in parallel and tests that are failing are usual not related to query itself.

**Comment by egonelbre** [comment]
@mniewrzal can you restrict the queries to a single schema?

**Comment by mniewrzal** [comment]
I don't see any options to configure detection query.

It's still valuable function but maybe it won't be possible to run it fully automatic.

**Comment by mniewrzal** [comment]
@egonelbre have some promising findings
```
I think I found something in https://github.com/cockroachdb/cockroach/blob/4d987b3f0788c98fa358715b336a1c55e254ee50/pkg/sql/delegate/show_full_table_scans.go#L18:

cockroach sql --insecure -e "SELECT key as query, count, application_name FROM crdb_internal.node_statement_statistics WHERE full_scan = TRUE ORDER BY count DESC"

If we have the "application_name" then we could separate migrations to have a different name. Also, if we have unique "application_name" we should be able to separate each test as well. So we could check each test individually and not everything at once.
```

**Comment by mniewrzal** [comment]
Done.
