### ISSUE TITLE
Create user settings/configuration table

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5472]
Follow up to https://github.com/storj/storj/issues/5382
See discussion here for more details https://storj.slack.com/archives/CAQV0AE2Z/p1672765169504039

Create a new satellite table with a 1-1 relationship on `users.id` 

To start, let's create a single configuration value in the table, called `session-timeout` - this will indicate the preferred expiration duration for a user's session, e.g. 1 week or 15 minutes. A nil value indicates the default timeout, so it should be populated as `nil` by default.

AC:
* New table created for user settings/configurations
* Structs added for new table, similar to `console.User`
* Database methods for creating, retrieving, and updating user settings

**Comment by jewharton** [comment]
Deployed in v1.73.
