### ISSUE TITLE
Fix file/folder upload button on mobile/desktop Safari

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5476]
From Slack:
> the upload file/folder button in the GUI does not work for me on Safari on mac or Safari on iOS.

![Image](https://user-images.githubusercontent.com/1323312/212935554-55217333-af1c-4043-af64-601d9b287915.png)

AC: Fix upload file/folder button on Safari

**Comment by mobyvb** [comment]
@VitaliiShpital could you try reproducing?

**Comment by VitaliiShpital** [comment]
@mobyvb @wilfred-asomanii I couldn't reproduce the issue on desktop Safari


https://user-images.githubusercontent.com/46756926/216936292-43aea6c3-3e1d-43b7-b2d6-e33a7e17e51d.mov

**Comment by mobyvb** [comment]
closing because we are unable to reproduce
