### ISSUE TITLE
Satellite UI / Browser icons

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5477]
Update all of the browser icons.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=18161%3A149585&t=Mk9KCJUMRPWNVeCb-0

Design Library:
https://www.figma.com/file/b3QhctHccKl3ihR8Q063Af/DCS-Design-Library?node-id=102%3A11617&t=CbXLa4QTr1pGBcp6-0

Icons Preview:
![Image](https://user-images.githubusercontent.com/3217669/212937900-2c1cd9f0-8e13-4ab0-b095-62237e553e92.png)

Browser Preview:
![Image](https://user-images.githubusercontent.com/3217669/212937901-9d320874-101c-4365-8dff-e700bd1fb61c.png)

**Comment by boshevski** [comment]
Added Back button to replace the "..." for going up one folder.

**Comment by mobyvb** [comment]
1 point seven 5 https://github.com/storj/storj/commit/0676a4ca893e9313a7b
