### ISSUE TITLE
Satellite UI / Table states

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5478]
Update table rows hover and selected states (in browser and all other tables).

Selected row
background: Yellow 1

Hover row
background: Grey 1
name color: Blue 3

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=18161%3A149585&t=Mk9KCJUMRPWNVeCb-0

Previews:
![Image](https://user-images.githubusercontent.com/3217669/212938899-b5968a30-abf7-42e4-a5f9-923f3aab39fd.png)

![Image](https://user-images.githubusercontent.com/3217669/212938900-c1dbf6ef-2c0e-40fe-8122-8c1a5a99bd12.png)

**Comment by stoweandi** [comment]
@mobyvb can we move this out of the sprint per it being a lower priority to https://github.com/storj/storj/issues/5511 ?
Sorry I didn't catch this in Sprint Planning, cc: @NiaStorj

**Comment by jewharton** [comment]
Deployed in v1.73.
