### ISSUE TITLE
Satellite UI / Notifications for free account limits

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5482]
Add notifications for 80% usage limits and 100% usage limits, including an option to upgrade to Pro account.
This notification should replace the default notification for upgrade on the dashboard page, don't show two notifications.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=15032%3A107158&t=Mk9KCJUMRPWNVeCb-0

**Comment by lizzythomson** [comment]
@boshevski just verifying, when segment and rate usage limits are at or above 80%, there is only a notification, not a modal, correct?

**Comment by boshevski** [comment]
@lizzythomson i just made a few updates so we now have modals as well.
