### ISSUE TITLE
Satellite UI / Project limits notification

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5483]
Add notifications for project limits for free and pro accounts.

Projects limit notification for Pro Accounts, just on the manage projects page.

Projects Upgrade notification on Free accounts, just on the manage projects page.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=16925%3A157433&t=Mk9KCJUMRPWNVeCb-0

**Comment by mobyvb** [comment]
what if your project limits were so high that they literally stretched into another dimension?
I'd call that astral _project_ -ion
haha
ha
get it?

1.74 https://github.com/storj/storj/commit/ec4b0c8ff6b3c935e2
