### ISSUE TITLE
Satellite UI / Billing Information + VAT

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5484]
Add Billing Information tab on the billing page where people can add different billing information, email for invoices, and VAT number. Also add option to edit the information.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=13847%3A80483&t=Mk9KCJUMRPWNVeCb-0

Steps required:
* Create functionality in `satellite/payments` add/edit billing data for a customer in Stripe
  * first name, last name, company name, VAT Tax ID, billing address, city, zip code, state, country, email for invoices
  * Do not make any DB changes unless necessary. Preferably, implement the behavior using the Stripe Go library, and do not update the satellite db
* Create functionality in `satellite/payments` to retrieve new billing data for a customer from Stripe (same fields as above)
* Add new billing tab and components to add/edit billing info according to the Figma design above

**Comment by wilfred-asomanii** [comment]
@boshevski @ferristocrat I've started working on this but i need some clarifications.

- First name, Last name and company name: Stripe has only one field for name, which is currently the name a user signs up with. Do we want to replace that? If yes, we may have to choose between company name and first & last names. Though we can add the extra names as metadata.
- Email: Same for name, do we want to replace the email used on sign up? Stripe has just one email field. Though we can add the extra names as metadata.
- Country: Stripe requires the country sent to them to be ISO 3166-1 alpha-2 country codes so we should use a dropdown for that field instead.
- VAT Tax ID: What is the vat type? Stripe requires one tax type from [this list](https://stripe.com/docs/invoicing/customer/tax-ids).
- Are all the fields required?

**Comment by heunland** [comment]
@wilfred-asomanii 
1. we can only use the same fields that are available in Stripe. So we should call the single field for customer name something like `Company or Customer Name` so the user can decide if they want to enter the Company´s name or a personal customer first and last name all in one field. When people sign up for a business account they always just want to enter their company name, not a personal name. If we want to just offer a single form now for both personal and business accounts, then we need to use the field label I suggested above to cover both options.
2. Stripe allows you to add an additional billing email. It has a field where you can put a check mark if you DO NOT want to have a separate billing email that is different from the email used to sign up for the account. This way all invoicing emails would go to a different billing email address if the check box is NOT checked and the customer filled in the field below with the billing email. So no, we do not want to substitute the email they signed up with, but give them a check box below the title ¨Billing email¨ that allows them to add another email address for billing if the check box `same as account email` is NOT checked, so:

```
Billing Email
- [ ] same as account email
field to enter the billing email address appears when box above not checked
```

if the customer checks the box, then the same email as they used to sign up for the account should be copied to the billing email field

3. The country that the customer indicates as part of entering their mailing address is a separate field from the ISO 3166-1 alpha-2 country code used to define the Tax Type. So there should be a Heading `Tax ID` below which there are 2 fields. The left field is called `ID Type` and consists of a drop down which should ideally show for each country the Flag, Enum code from https://stripe.com/docs/invoicing/customer/tax-ids and next to it, name of the country. The customer should click on their country enum code and then in the empty field to the right of the `Tax ID` field they should see what format the Tax ID Number should be entered in for the country they chose. So it should display what is shown in the Example column in https://stripe.com/docs/invoicing/customer/tax-ids. Any Tax ID that does not conform to the correct format for the country should be rejected and customer should not be able to save it until they enter a valid Tax ID for their country. Stripe actually checks that Tax IDs entered are actually valid, so I dont know if you can let Stripe do the checking for you or if you need to code the checking routine for each country which woud be a lot of work I assume.

4. Are all the fields required? If the customer wants to enter a VAT number/tax ID they have to choose the proper enum code for their country and then enter the Tax ID number. They should be able to optionally enter either company or personal name in a single field (either one is required) a separate Billing email and mailing address is optional. I.e. they need to uncheck the check box that says that billing email is the same as account email so they could enter the separate billing email. 
Optionally they should also be able to enter a phone number

5. We might want to give them another optional field where they could enter any other data they might require that doesnt fit into any of the other boxes, if they need it to appear on the invoice. We have had some customers ask to add a second tax number or other sort of ID that is not an official VAT number recognized on that list you linked

It would be a lot easier for you to see what I mean if you had access to Stripe´s option to edit customer details on the left hand side of a customer account page. If you don´t have access maybe we need to have a meeting so I can show it to you.

**Comment by ferristocrat** [comment]
Have we considered using https://stripe.com/payments/elements? We still need to answer the questions above, but I think would make it a lot easier to implement since a lot of the logic is handled by Stripe elements.

**Comment by iglesiasbrandon** [comment]
just checked on prod and its deployed; closing this issue.
