### ISSUE TITLE
Satellite UI / Project ownership

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5485]
Add tags for project ownership so projects can be visually differentiated between My Projects and Shared with me projects. This way projects with the same name such as "My first project" will not be confusing to people.

Add tags in the Projects menu and on the Dashboard page. Future updates on the All Projects Dashboard.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=18540%3A163992&t=Mk9KCJUMRPWNVeCb-0

**Comment by mobyvb** [comment]
1.75 https://github.com/storj/storj/commit/172fcc4f6636
