### ISSUE TITLE
Satellite UI / Bug / Upload buttons don't work on Safari

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5486]
We have a bug report for uploading on Safari:

Kevin Leffew
Another thing I noticed – the upload file/folder button in the GUI does not work for me on Safari on mac or Safari on iOS.  I commonly use safari iOS to demo storj at conferences, etc. – so this is worth checking out imo

![Image](https://user-images.githubusercontent.com/3217669/212959597-dd81badf-c407-40a0-87bc-80141e8dfd05.png)

**Comment by mobyvb** [comment]
duplicate of https://github.com/storj/storj/issues/5476
