### ISSUE TITLE
Release-v1.71 Test Satellite UI access grant wizard and file browser enrcyption dialog

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5490]
[60cd245](https://github.com/storj/storj/commit/60cd245) web/satellite: access grant CreateForm modal migrated and slightly refactored
[e0f2087](https://github.com/storj/storj/commit/e0f2087) web/satellite: EncryptForm component migrated to use composition api

**Comment by nadimhq** [comment]
Create Access Modal- hovering over more info on access grant, S3 credentials, API access and then clicking outside of the info should close it, but after these changes it doesn't close unless you close the modal itself.
