### ISSUE TITLE
v1.71.0-rc -> Clicking "New folder" button in buckets screen doesn't open folder creation modal

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5501]
see video

https://user-images.githubusercontent.com/14928042/214057515-fddcc4e0-ad6d-4560-9b1b-28981120af21.mp4

**Comment by mobyvb** [comment]
fixed by https://github.com/storj/storj/commit/250f505f4df25205ea69f852851d4a2818fe0811 which was cherry-picked into 1.72.1
