### ISSUE TITLE
Create Access Modal Satellite UI- Shown Info Doesn't Go Away When Hovering Outside of It

### ISSUE THREAD

**Issue by nadimhq** [storj/storj#5502]
**Description**
Hovering over more info on access grant, S3 credentials, API access and then clicking outside of the info should close it- which is how it should work (in production), but right now in the newest release it doesn't close when you hover outside of the shown info. 

**Step to Reproduce**
1. Login to your account.
2. Go to Access grants page by clicking on the side navbar- Access.
3. Click on create an access grant, create s3 credentials or create keys for cli
4. Hover over any of the more info buttons under the types
5. Hover outside of the shown info to close it

**Results**
It is **expected** that hovering outside of the shown info should close it, but in **actuality** the shown info stays on indefinitely regardless if hovering outside of it unless one closes the modal itself.

**AC**- Hovering outside of the shown info closes it

(QA)

https://user-images.githubusercontent.com/82845192/214061235-fb85701c-3b5f-4427-89e0-cf024205e77b.mov

(prod)

https://user-images.githubusercontent.com/82845192/214061512-8f2063eb-0c83-4314-8c67-e0f64a444aef.mov

**Comment by mobyvb** [comment]
1.72 https://github.com/storj/storj/commit/e751ee3c1bf510bd1acf09
