### ISSUE TITLE
v1.71 - problem with passphrase behaviour in case if user was logged out by inactivity timer

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5504]
https://user-images.githubusercontent.com/14928042/214077414-e460bd29-32db-42f4-8efa-ce5c3af38e05.mp4

**Comment by NiaStorj** [comment]
@VitaliiShpital please provide an effort number. thanks :)

**Comment by mobyvb** [comment]
should be fixed by https://github.com/storj/storj/commit/d1c230fe4dfdbe03bc921d13b14bf0b466fc1fa7
was cherry-picked into 1.71.2, which was deployed as of today

**Comment by mobyvb** [comment]
@andriikotko are you able to confirm if this was fixed by 1.71.2?

**Comment by VitaliiShpital** [comment]
@NiaStorj done
