### ISSUE TITLE
Satellite UI / Access Creating Updates

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5511]
Figma designs:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=20756%3A241528&t=HxNnLpyHKICyfssu-0

This update focuses on updating the flow so it reflects the new project level passphrase, and improving the user experience when creating access grants.

Passphrase updates:
1. Use existing passphrase by default. This way people don't need to create new passphrase for all of their access grants.
2. Keep options to create new passphrase under Advanced options with a warning notification. Only proceed if you know what you are doing.

Access creation wizard updates:
1. Design updates to the modals
2. Split the first step into two.
3. Keep permissions and buckets checked by default.
4. Blur the generated access fields, add option to show them.

Using the new flow, creating an access grant would mean just entering an access name, and clicking continue to get the generated access. 

---

AC:
* create or update modal for encryption step when creating access. See [design](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=20799%3A243454&t=Km6u28pf9KJM4GW1-0)
    * if new project passphrase is enabled and set, "use the current passphrase" should be selected automatically, and the "advanced" menu should be closed
    * if new project passphrase is enabled, but not set for the user, select "enter my current passphrase" by default, and the "advanced" menu should be closed
* split permissions step out of the first step when creating an access grant
* update the overall access flow to match figma in terms of styling, icons, text
* Keep permissions and buckets checked by default.

**Comment by mobyvb** [comment]
blocked by https://github.com/storj/storj/issues/5521

**Comment by VitaliiShpital** [comment]
Hey @NiaStorj! I've updated story points of this ticket since I'm reworking this flow from scratch with a feature flag
