### ISSUE TITLE
Create Access modal: Selecting only read results in grey “encrypt my access”

### ISSUE THREAD

**Issue by stoweandi** [storj/storj#5512]
Selecting only read results in grey “encrypt my access”
To get past this you just select all then uncheck the items you want and it turns blue.

![Image](https://user-images.githubusercontent.com/48924196/214383752-6341bfd2-6487-4275-877f-2cdd0aff9b32.png)

AC:
* It is possible to create an access using any selection of read/write/list/delete/all (choosing readonly allows you to proceed)
* Ensure that the access has the selected permissions (e.g. readonly) when it is used with uplink

**Comment by mobyvb** [comment]
deployed in 1.72 https://github.com/storj/storj/commit/b4dbfa0cf8c0bbad7df77b0ecef9a58e5466c8ca
