### ISSUE TITLE
All Projects Dashboard: New page and feature flag

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5514]
Designs: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=14389%3A131874&t=VbBjOiv3oXvS8MLF-0

AC:
* All projects dashboard page added
    * Should have a card for each project that the user is a member of. Cards should have a tag like in Figma indicating if the user is the "owner" or "member"
    * Should be able to use the three dot menu of a project card to access settings
    * Should be able to "open project" to navigate to single project dashboard (current dashboard as of writing)
    * Does not need to include "invited"
    * Does not need to include bottom components (intro video or "need help" links)
    * Does not need to implement table view for projects
    * User should be able to navigate to billing without being prompted for project passphrase
* New feature flag to toggle whether "all projects dashboard" is enabled
    * if enabled, logging in will go to the all projects dashboard
    * onboarding flow will still end up on single project dashboard
    * should be disabled by default

**Comment by mobyvb** [comment]
@boshevski how does the onboarding flow change when the all projects dashboard is introduced?

**Comment by mobyvb** [comment]
in the AC we put "onboarding flow will still end up on single project dashboard". Is this correct?

**Comment by boshevski** [comment]
@mobyvb I added the onboarding steps in the figma.
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=21596%3A249813&t=0YnVoUnhYfn6dKdi-0

**Comment by mobyvb** [comment]
one
https://github.com/storj/storj/commit/31e386c6072d83da7b19e83
dot
https://github.com/storj/storj/commit/52abe8ddb44774f208048d34
seven
https://github.com/storj/storj/commit/bac4c863888122925426
five
https://github.com/storj/storj/commit/76d7bc6d189d07c4c2dd
(one dot seven five) - backup vocals
https://github.com/storj/storj/commit/9138e84fb173c62b
