### ISSUE TITLE
Crooked form on Partners page

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#5520]
![image](https://user-images.githubusercontent.com/15882196/215453359-2304c980-2704-4688-9118-1f5712d59b5c.png)

As you can see the textboxes are not aligned. Also this page is not mobile friendly.

The list of partners is an image which makes the page horizontally scrollable. This is annoying on mobile.

![image](https://user-images.githubusercontent.com/15882196/215453835-7c775666-9557-44f9-9230-ac0a41b4c87d.png)

**Comment by boshevski** [comment]
This has been fixed.
