### ISSUE TITLE
Satellite UI / Upgrade notification - move to be inside the page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5525]
The new "upgrade your account" banner for free tier users (one of the AB test cases) currently overlaps elements at the top of the page

https://www.figma.com/file/b5Ch0EN8GJl6oNUKcw0NLM/Production-DCS?node-id=1510%3A7325&t=gYXPAqbYi3oNbtKI-0

AC:
* New upgrade account banner is placed at the top of the page, and does not overlap anything
* Upgrade account banner shows up only on the dashboard
* Upgrade banner only shows a while (a week) after signup
* Remove AB test on the upgrade banner and make it the default.

**Comment by boshevski** [comment]
Please remove the AB test on this, and make the new version public.

**Comment by mobyvb** [comment]
wilfred moved banner
and made it look much better
this is a haiku

1.73 https://github.com/storj/storj/commit/8ec3bc5803b
