### ISSUE TITLE
Copyright year still 2022

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#5539]
![image](https://user-images.githubusercontent.com/15882196/216528990-4783e2c0-8772-4c76-b680-f4e4a2943a1b.png)

Why do we keep updating it every year when it can be automated?

Example code:
```
Copyright &copy; 2014-<script>document.write(new Date().getFullYear())</script>
```

I personally feel showing a date range helps customers get an idea that Storj has been in the business since 2014 till current year. Customers maybe reluctant to trust a new company with their data and this might help remove some of that doubt.

**Comment by egonelbre** [comment]
IANAL, but copyright indicates the first time the content was first published, so it shouldn't be updated.

See:
* https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated/2391555#2391555
* https://www.reddit.com/r/webdev/comments/1p9tao/auto_updating_the_year_on_copyright_notices/

Also, using just "© Storj Labs Inc." should be fine as well. Also, "All Rights Reserved" part is probably unnecessary.

**Comment by iglesiasbrandon** [comment]
The marketing team is responsible for the website and they work with the legal team to ensure these things are correct. I am going to close this issue for now.
