### ISSUE TITLE
Session timeout modal behavior

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5549]
Bug: session modal doesn't display at all when another modal is open

We currently have logic that doesn't enable more than 1 modal at a time. We want to make an exception for the Session Timeout modal, so that it appears over everything else, and keeps any modals that are open...open. 

AC:
- Show the session timer on top of other modals or dialogs.
- User should be able to interact with the session timeout modal using the keyboard
- clicking outside of the modal should close the modal and keep user logged in, same as the escape button

**Comment by mobyvb** [comment]
We could try to use Vue teleport feature - @VitaliiShpital
