### ISSUE TITLE
S3: provide true lexicographical ordering

### ISSUE THREAD

**Issue by dsnet** [storj/storj#5564]
Currently, the S3 list order is deterministically pseudo-random because it presumably lists based on the sorted key names after encryption. For applications where there is no direct relationship between keys, this is probably fine. However, this goes contrary to how AWS' S3 operates, which lists keys in lexicographical order.

In my application, ordering is important, and the names of the keys are not sensitive (i.e., they're either timestamps or sequence numbers), where the utility of proper ordering trumps privacy of key names. That is, my application would depend on key "012345" being listed before "012350". Also, a request to list keys after "012347", should list "012350" assuming it was the next key.

Thus, I propose a way to explicitly opt out of encrypted key names. You lose privacy, but gain functionality.
The alternative would be to store keys using a order preserving encryption scheme, but I'm no expert in such matters.

Whatever solution occurs, it must not have O(N) cost where N is the total number of objects in the bucket. Thus, on the gateway it should not do something like gather a list of all keys, do a sort on them, and then give you the tiny slice of what you asked for. That simply doesn't scale as the bucket size grows.

**Comment by jtolio** [comment]
Another excellent issue.

When necessary, our gateway services do exactly what you propose we don't do (O(N) cost), so you're right that we support this that way and that it is not what you're looking for.

To be honest, the only changes necessary here are client-side. There exist some old codepaths that support no-op path encryption, but they are not currently exposed in our public interfaces. I would imagine adding support for this wouldn't be very large, but ultimately we'd really want to make sure we get it right. Our last conversation about it led some team members into an implementation of order preserving encryption, as you say. That does indeed have promise.

I've raised this with our product team and we'll see what the prioritization ends up looking like. It's important to get the details of this right, but other than that a basic no-op path encryption option really could be a starter issue for external contribution!

**Comment by dsnet** [comment]
About a month ago, I came to the same conclusion that this *could* be done in with a custom build of `uplink`, but this solution presupposes that I am is using `uplink`.

Presently, I'm actually using the "github.com/aws/aws-sdk-go/aws" SDK to interact with Storj. The main advantage of this approach is to avoid vendor lock-in. Purely by changing the `aws.Config`, I can have the "github.com/aws/aws-sdk-go/service/s3" talk to the Storj Gateway instead of the default AWS endpoint. I can quickly switch between AWS and Storj to compare the behavior, performance, etc.

IIUC, by pointing the "s3" package to "https://gateway.storjshare.io", I am communicating with a Storj managed instance of https://github.com/storj/gateway-mt, in which case the change would probably need to be made there, right?

**Comment by kaloyan-raev** [comment]
There is a bit of a misunderstanding. You are correct that https://gateway.storjshare.io/ is served by the code from https://github.com/storj/gateway-mt.

But remember that Gateway-MT uses uplink to interact with the Storj network. And that our S3-compatible credentials are just a wrapper of an access grant. The access grant (and hence the S3 credentials) contain information for the uplink (and hence Gateway-MT) on how to encrypt the object key for new objects.

So following the instructions I gave you, you will get S3 credentials that won't encrypt object keys. They will work with Gateway-MT without any other modification required.

**Comment by jtolio** [comment]
Put another way - @kaloyan-raev's suggested uplink modifications only need to happen to the uplink generating the access grant! Every other uplink (including the gateway) will (surprisingly to me too) transparently work with that access grant with the encryption settings you chose. This is because the access grant stores the encryption settings, and EncNull is an old but well understood encryption type in our codebase across releases. So, yeah, surprising-magic-emoji.gif. Without changes the public gateway will work with the access grant generated by the modified uplink in this case.

**Comment by kaloyan-raev** [comment]
We improved the Uplink CLI and published a guide in our documentation on achieving lexicographical ordering:
https://docs.storj.io/dcs/lexicographically-sorted-object-listings.
