### ISSUE TITLE
Listing objects sometimes show duplicated entries

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5570]
We noticed that in some cases listing more than 1000 objects can show some duplicated entries. Turns out its related to internal object versions and we are constructing iteration cursor wrong. We are not providing satellite version cursor with listing request.

Basic test case to reproduce
```go
func TestListFoo(t *testing.T) {
	testplanet.Run(t, testplanet.Config{
		SatelliteCount: 1, StorageNodeCount: 0, UplinkCount: 1,
		Reconfigure: testplanet.Reconfigure{
			Satellite: func(log *zap.Logger, index int, config *satellite.Config) {
				config.Metainfo.RateLimiter.Enabled = false
			},
		},
	}, func(t *testing.T, ctx *testcontext.Context, planet *testplanet.Planet) {
		u := planet.Uplinks[0]
		s := planet.Satellites[0]

		const amount = 1001

		require.NoError(t, u.CreateBucket(ctx, s, "test"))
		for i := 0; i < 2; i++ {
			for i := 0; i < amount; i++ {
				require.NoError(t, u.Upload(ctx, s, "test", fmt.Sprintf("file-%d", i), nil))
			}
		}

		project, err := u.GetProject(ctx, s)
		require.NoError(t, err)
		defer ctx.Check(project.Close)

		keys := make(map[string]struct{})
		iter := project.ListObjects(ctx, "test", &uplink.ListObjectsOptions{})
		for iter.Next() {
			if _, ok := keys[iter.Item().Key]; ok {
				t.Fatal("duplicate", iter.Item().Key, len(keys))
			}
			keys[iter.Item().Key] = struct{}{}
		}
		require.NoError(t, iter.Err())
	})
}
```

Acceptance Criteria:
* listing doesn't show duplicated entries

**Comment by egonelbre** [comment]
A. option would be to send more responses than the listing limit says (for old uplinks without the fix)

B. option send only the largest entry in the satellitedb (for old uplinks without the fix)

**Comment by egonelbre** [comment]
Ah sorry, I meant `metabase` `objects` table

**Comment by mniewrzal** [comment]
Thanks for ideas.

I think sending more than limit is saying should be working well. Especially that we never set listing limit on client side, it was always 0 and satellite decided how much results to return.

**Comment by mniewrzal** [comment]
For workaround, at end I think I will use separate approach for committed and pending objects. For committed object I will hardcode maximum version (max for INT4 which is DB type). For pending objects I will make a change to return more than listing limit to avoid duplicate situations.

**Comment by mniewrzal** [comment]
Main problem with duplicates is fixed. I extracted similar problem with pending objects to close this ticket and back to pending objects issue later https://github.com/storj/storj/issues/5630.
