### ISSUE TITLE
Investigate high GE execution time with ranged loop

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5572]
After enabling ranged loop on SLC we are seeing sometimes very high execution time for GE observer. From attached svg profile it looks it's related to `infectious.NewFEC` method. We need to improve execution time for GE in ranged loop. 

![image](https://user-images.githubusercontent.com/7313031/218403107-8d3d9023-8640-4e28-a59a-2ecdf4ce1dfe.png)
![pprof001_ge](https://user-images.githubusercontent.com/7313031/218403297-b439a376-197b-4095-bab1-d5d69811c3d6.svg)

**Comment by mniewrzal** [comment]
I lost cpu profile collected when GE cpu usage was high but main slowdown point was `infectious.NewFEC` which is not as light operation as it looks like.

**Comment by mniewrzal** [comment]
I hope https://review.dev.storj.io/c/storj/storj/+/9643 will resolve this issue.

**Comment by mniewrzal** [comment]
We need to wait for another release to see if problem is resolved.

**Comment by shaupt131** [comment]
Do we have any additional info here?  Was this indeed fixed by another change that was made?

**Comment by mniewrzal** [comment]
I will monitor this problem until end of week and then we can decide if we can close it or not.

**Comment by mniewrzal** [comment]
Problem looks to be fixed.
