### ISSUE TITLE
Change ranged loop processing strategy

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5574]
Currently ranged loop is calculating number of ranges and for each range we have separate goroutine to process this range. Initially we assume that stream id distribution will be enough to split ranges in a way were each range will have similar number segments inside. Turns out that if we will have small number or ranges, those will be much different from each other e.g. SLC for 2 ranges is spliting 54M/10M and we are loosing advantage of parallel processing. 

We need to change strategy a bit. We should split segments table into much more ranges e.g. 10k but not start separate goroutine for each range but keep lower number of workers which will be taking range one by one.

**Comment by mniewrzal** [comment]
I checked US1 and stream_id distribution looks good. For 4 ranged each one had ~165M-167M segments. I don't think we will need to implement this ticket.

**Comment by shaupt131** [comment]
Sounds great!  I'll close as
