### ISSUE TITLE
Reduce number of round trips to DB while metainfo.DownloadObject 

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5575]
Current DownloadObject method is not super optimal from DB round trips perspective. We have visible latency between satellite and DB and we should aim to reduce round trips as much as possible. We have at least 3 separate calls to metainfo DB:
* first, get object
* second, list segments (but not all columns), number of segments depends on requested range
* third, get full data of first segment from requested range

Potential optimizations:
* remove third request by extending second listing segments with needed columns
* if object size is not needed for requesting segments we can:
   * do batch request to DB
   * or combine getting object with listing segment as a single DB query
 * not sure if possible but in theory we could move range calculation to DB side
 * other???

Acceptance Criteria: 
- research and determine what improvement should be made
- implement the improvement

**Comment by shaupt131** [comment]
https://review.dev.storj.io/c/storj/storj/+/9980

**Comment by shaupt131** [comment]
@zeebo or @mniewrzal will there be follow-up work or optimizations to make beyond the PR posted above? If so, should we capture them in another ticket for sprint 12?
