### ISSUE TITLE
Find a way to reduce loop memory consumption

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5577]
After deploying ranged loop to SLC we noticed some pod restarts. Those were all OOMs. After increasing to parallelism 4 loop was not able to work with available 1,5GB of memory. We would like to be able to bump parallelism to much more than 4 so we need to improve memory consumption. After taking heap profile dump turns out that ~90% of memory is consumed by `(*NodeAliasCache).ConvertAliasesToPieces`. This method is called for each segment after getting data from DB.

We need to improve method itself or a way how we are using it with loop e.g. by calling it less frequent but for larger data set.

TODO take fresh heap dump

![image](https://user-images.githubusercontent.com/7313031/218522999-c950cdd5-dea5-48bd-9845-561e4b492c50.png)

Acceptance Criteria:
Find a viable solution to reduce memory consumption.  Implementation will be a follow-up ticket.

**Comment by egonelbre** [comment]
You should be able to cut it by ~90% by switching to using alias pieces. Reusing `[]Piece` between calls should also help, however comes with overhead.

**Comment by egonelbre** [comment]
@mniewrzal you can still let each service convert locally. Not the whole slice at a time, but one ID at a time. The lookup should be a single index to a slice.

**Comment by mniewrzal** [comment]
hmm ok we would need to give access to AliasCache to all observers and just convert single alias at the time?

**Comment by egonelbre** [comment]
@mniewrzal not all observers, but yes.

**Comment by mniewrzal** [comment]
It looks that moving from using `metabase.Pieces` (which requires ConvertAliasesToPieces to be called) to `metabase.AliasPieces` will improve not only memory usage but also cpu usage (see https://review.dev.storj.io/c/storj/storj/+/9646). So raw plan to work on this would be:
* expose `metabase.AliasCache` to be used outside `metabase` package. Currently its only used by metabase methods but we would need ability to find real NodeID for NodeAlias
* convert node tally observer to use `metabase.AliasPieces` and `metabase.AliasCache`
* convert GE observer to use `metabase.AliasPieces` and `metabase.AliasCache`
* convert GC observer to use `metabase.AliasPieces` and `metabase.AliasCache`
* convert Repair observer to use `metabase.AliasPieces` and `metabase.AliasCache`
* Audit observer was already converted with https://review.dev.storj.io/c/storj/storj/+/9646
* Stop using `ConvertAliasesToPieces` while scanning segment fields from DB (https://github.com/storj/storj/blob/06f4aede9b94e853fe10855591afd61423cb2c39/satellite/metabase/loop.go#L405) and remove `Pieces` from `metabase.LoopSegmentEntry`
