### ISSUE TITLE
Satellite UI / Consistent bucket options menu

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5582]
The bucket options menu is different on the buckets page, and when opening inside the bucket.

On the buckets page, the menu is:
- View Bucket Details
- Delete Bucket
Missing the Share bucket option.

Inside the bucket, the menu is:
- View Bucket Details
- Share bucket
Missing the Delete Bucket option.

![Image](https://user-images.githubusercontent.com/3217669/218786503-d425124b-2ba6-4b51-9b15-0cf9f9594ad5.png)

![Image](https://user-images.githubusercontent.com/3217669/218786504-1922a810-52fa-4dcb-916c-f9dafbbc6a81.png)

AC:
1. Add the Share Bucket option in the bucket options menu on the buckets page.
2. Add the Delete Bucket option to the bucket options menu inside the buckets page.

**Comment by NiaStorj** [comment]
Closed because of migration to the new vuetify app
