### ISSUE TITLE
Satellite UI / Update delete object action

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5583]
"It seems the garbage can isn't always visible, but it's clickable.
It seems to appear if I click an item in the bucket or if choose "No"

https://user-images.githubusercontent.com/3217669/218789647-b0fe59c9-d241-42ad-9d17-5c19c44561fc.mov

Update the delete objects flow so it matches our designs.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=23372-311706&t=vSUog6jEyVkfQ0nc-0

**Comment by NiaStorj** [comment]
closed, due the migration to the new vuetify app
