### ISSUE TITLE
Satellite UI / Update object menu

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5584]
Update the objects menu as in the designs.

![Image](https://user-images.githubusercontent.com/3217669/218790030-f08b49bd-2abb-46c8-8b5b-e2513ccf3a52.png)

![Image](https://user-images.githubusercontent.com/3217669/218790031-47825979-05e4-4786-837e-5a81455bdcdc.png)

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=12073%3A49536&t=dpt9XTEU4E8QnHkn-0

**Comment by iglesiasbrandon** [comment]
this issue is completed, closing it.
