### ISSUE TITLE
panic when filesystem error is encountered during EmptyTrash

### ISSUE THREAD

**Issue by uofm-matt** [storj/storj#5586]
**Description** [panic: runtime error: invalid memory address or nil pointer dereference]

Been running this docker container just fine for more than a month and this morning it's restarting consistently with this error.  Have other storj containers on the same system with no error, running just fine, seems to have happened after update to 1.72.2.  Removed container and re-initialized with below command and still errors.  

Command line used to run: docker run -d --restart unless-stopped --stop-timeout 300     -e WALLET="0xxx"     -e EMAIL="xxx@gmail.com" -e ADDRESS="*****:27206" -e STORAGE="11200GB" --network=container:oc-storj2 --user $(id -u):$(id -g) --mount type=bind,source="/share/storj2/identity",destination=/app/identity --mount type=bind,source="/share/storj2",destination=/app/config --name storj2 storjlabs/storagenode:latest

**Logs:**

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc90bd8]

goroutine 1107 [running]:
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a1e0)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a210)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a250)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
github.com/spacemonkeygo/monkit/v3.newSpan.func1(0xc00054a3d0)
        /go/pkg/mod/github.com/spacemonkeygo/monkit/v3@v3.0.19/ctx.go:155 +0x30e
panic({0xf8e400, 0x1ab0080})
        /usr/local/go/src/runtime/panic.go:844 +0x258
storj.io/storj/storage/filestore.(*Dir).EmptyTrash.func1({0x1437c30, 0xc00045bf20})
        /go/src/storj.io/storj/storage/filestore/dir.go:486 +0x458
storj.io/storj/storage/filestore.walkNamespaceWithPrefix({0x1437920, 0xc00049e500}, 0x0?, {0xc000310140, 0x20, 0x20}, {0xc0008f4730?, 0x7f062bdb41d8?}, {0xc0008d0170, 0x2}, ...)
        /go/src/storj.io/storj/storage/filestore/dir.go:797 +0x3c6
storj.io/storj/storage/filestore.(*Dir).walkNamespaceInPath(0xc0000b6240, {0x1437920, 0xc00049e460}, {0xc000310140, 0x20, 0x20}, {0xc0008e60a8, 0x14}, 0x40ebc7?)
        /go/src/storj.io/storj/storage/filestore/dir.go:743 +0x692
storj.io/storj/storage/filestore.(*Dir).EmptyTrash(0xc0000b6240, {0x1437920, 0xc00049e3c0}, {0xc000310140, 0x20, 0x20}, {0x7f062bdb41d8?, 0x20?, 0x1b26fa0?})
        /go/src/storj.io/storj/storage/filestore/dir.go:479 +0x2ea
storj.io/storj/storage/filestore.(*blobStore).EmptyTrash(0xc00000e558, {0x1437920, 0xc00049e320}, {0xc000310140, 0x20, 0x20}, {0x78c8cb?, 0x1437450?, 0x1b26fa0?})
        /go/src/storj.io/storj/storage/filestore/store.go:155 +0x1c7
storj.io/storj/storagenode/pieces.(*BlobsUsageCache).EmptyTrash(0xc000042380, {0x1437920, 0xc00049e320}, {0xc000310140, 0x20, 0x20}, {0x8?, 0x16?, 0x1b26fa0?})
        /go/src/storj.io/storj/storagenode/pieces/cache.go:316 +0x10e
storj.io/storj/storagenode/pieces.(*Store).EmptyTrash(0xc0000a7860, {0x1437450, 0xc000640900}, {0x84, 0xa7, 0x4c, 0x2c, 0xd4, 0x3c, 0x5b, ...}, ...)
        /go/src/storj.io/storj/storagenode/pieces/store.go:381 +0x1d2
storj.io/storj/storagenode/pieces.(*TrashChore).Run.func1.1({0x1437450, 0xc000640900})
        /go/src/storj.io/storj/storagenode/pieces/trashchore.go:83 +0x2f8
storj.io/common/sync2.(*Workplace).Start.func1()
        /go/pkg/mod/storj.io/common@v0.0.0-20230201101354-04e35e465ace/sync2/workplace.go:89 +0xc9
created by storj.io/common/sync2.(*Workplace).Start
        /go/pkg/mod/storj.io/common@v0.0.0-20230201101354-04e35e465ace/sync2/workplace.go:67 +0x30a
[/share/storj2/storage] # docker stop storj2
```

**Your environment**

- Operating system and version: QNAP
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): Running Dockerized

**Comment by thepaul** [comment]
https://review.dev.storj.io/c/storj/storj/+/9593

**Comment by thepaul** [comment]
Thanks for the bug report! A fix has been committed at https://github.com/storj/storj/commit/0e1c99f75af84a3bc38e81c19ec877b50733cb57. A release should be prepared with that fix soon.

**Comment by stefanbenten** [comment]
Hello @uofm-matt!
Thanks for the report, we are preparing a point release and will be releasing it soon in order to avoid this special case.

**Comment by uofm-matt** [comment]
Thanks @stefanbenten!  I'll be glad to get my node back online.  My first real bug report!  Love storj!

**Comment by stefanbenten** [comment]
@uofm-matt Happy to report that v1.72.5 is in rollout and should reach your node soon. I am closing this, but feel free to reopen if after the update it keeps running into this error.

**Comment by uofm-matt** [comment]
@stefanbenten Thanks again.  Anyway to force it to update?  I know we slow-roll the updated versions, but it's in a constant state of restart right now.  It's odd, I'm getting:
2023-02-16T23:03:04.341Z        ERROR   db      Unable to read the disk, please verify the disk is not corrupt  {"Process": "storagenode"}
2023-02-16T23:03:04.341Z        ERROR   pieces:trash    emptying trash failed   {"Process": "storagenode", "error": "pieces error: filestore error: lstat config/storage/trash/pmw6tvzmf2jv6giyybmmvl4o2ahqlaldsaeha4yx74n5aaaaaaaa/os/4flz5hw7ihu7fdrdw5hxcqfeawuoy5kkzvp6lavdh3p4eqnaha.sj1: input/output error", "errorVerbose": "pieces error: filestore error: lstat config/storage/trash/pmw6tvzmf2jv6giyybmmvl4o2ahqlaldsaeha4yx74n5aaaaaaaa/os/4flz5hw7ihu7fdrdw5hxcqfeawuoy5kkzvp6lavdh3p4eqnaha.sj1: input/output error\n\tstorj.io/storj/storage/filestore.walkNamespaceWithPrefix:793\n\tstorj.io/storj/storage/filestore.(*Dir).walkNamespaceInPath:730\n\tstorj.io/storj/storage/filestore.(*Dir).EmptyTrash:471\n\tstorj.io/storj/storage/filestore.(*blobStore).EmptyTrash:152\n\tstorj.io/storj/storagenode/pieces.(*BlobsUsageCache).EmptyTrash:316\n\tstorj.io/storj/storagenode/pieces.(*Store).EmptyTrash:381\n\tstorj.io/storj/storagenode/pieces.(*TrashChore).Run.func1.1:83\n\tstorj.io/common/sync2.(*Workplace).Start.func1:89"}

The disk seems fine to me, I can touch files and remove them no problem, so the disk seems good.  All related to this bug?

**Comment by thepaul** [comment]
You should try to get rid of the file it’s mentioning, `config/storage/trash/pmw6tvzmf2jv6giyybmmvl4o2ahqlaldsaeha4yx74n5aaaaaaaa/os/4flz5hw7ihu7fdrdw5hxcqfeawuoy5kkzvp6lavdh3p4eqnaha.sj1`. There may be other files with problems, but that’s the one causing your current problem.

**Comment by uofm-matt** [comment]
@thepaul Thank you!
