### ISSUE TITLE
Vuetify: Add multiple selection in browser

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5596]
Add multiple selection in the browser.

Figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=21622%3A250104&t=1fPZLzM5ZApiGqcA-0

Selecting multiple files or folders, should present the available options we have at the moment, like Download, Delete, etc.

**Comment by iglesiasbrandon** [comment]
this issue has been completed.

**Comment by wilfred-asomanii** [comment]
v1.96.6  20d389b
