### ISSUE TITLE
Satellite UI / Edit default payment method is missing from Payment Methods screen

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5600]
Add "Edit Default" button in the credit cards cards next to the "Remove" button. This directly opens the Edit Default Payment Method dialog which already exists if you try to remove a default card.

![Image](https://github.com/storj/storj/assets/3217669/d69ce991-303d-4523-8936-be76cf694b46)

![Image](https://github.com/storj/storj/assets/3217669/e601fef2-69d4-4ba2-9313-b1a2181018b0)

**Comment by NiaStorj** [comment]
@boshevski is there a design for this? if so, please add to ticket.

**Comment by wilfred-asomanii** [comment]
This has already been done. Was there another ticket for it @VitaliiShpital ?

**Comment by boshevski** [comment]
Added info and design in the ticket description.
