### ISSUE TITLE
Add new user-level configuration for passphrase prompt

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5613]
AC:
* New column added to `user_settings` table to indicate whether or not the user would like to be prompted for encryption passphrase upon entering or switching projects
  * `NULL` by default (indicating user has not decided). Boolean value that indicates whether a user would like to be prompted for passphrase upon entering project, or only prompted when necessary
 * confirm that the next ticket for implementation of the column exists

**Comment by lizzythomson** [comment]
Deployed in v1.75 [54f0f47](https://review.dev.storj.io/plugins/gitiles/storj/storj/+/54f0f47839891755dc6569f5922fb60979e79d6f)
