### ISSUE TITLE
Enable user to remember "don't remind me again"

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#5616]
When a user dismisses prompt to enter passphrase after creating project/entering project have an option to not remind again - "Don't remind me again"

Allow user to opt out of entering passphrase EXCEPT when it is necessary for them to perform the intended (entering file browser, creating access grant

Designs: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=22627-264772&t=lbI7vSVts7RoDTLx-0

AC:
* If passphrase prompt (on creating/entering project) is dismissed, show a second modal allowing the user to say "don't remind me again"
* if user selects "don't remind me again", set the `user_settings.passphrase_prompt` db field to `false`
* If `user_settings.passphrase_prompt` field is `false` for a user, do not prompt for passphrase upon entering or creating a project
  * user should still be prompted for passphrase upon creating an access grant or entering a bucket in the object browser

**Comment by wilfred-asomanii** [comment]
this task blocks/overlaps with #5818
