### ISSUE TITLE
cmd/uplink: show info on how to enable secure custom domain support while sharing with `--dns`

### ISSUE THREAD

**Issue by amwolff** [storj/storj#5623]
**Describe the feature or problem you'd like to solve**

We should advertise secure custom domain support in Link Sharing Service while issuing `uplink share` with the `--dns` flag and instruct how to enable it, highlighting restrictions.

**Propose a Solution**

`uplink share` with the `--dns` flag should inform the user that there's an additional TXT record to be specified (`storj-tls: true`) to enable secure custom domain support, but only pro accounts will be able to use it. Consult @amwolff or @ferristocrat for exact wording.

**Additional context**

A ticket that this issue is an outcome of: storj/gateway-mt#306

**Comment by ferristocrat** [comment]
I think we could just add another flag something like `--tls` that prints the additional TXT record... then we could just update the help doc to say something like:

**Comment by halkyon** [comment]
A `--tls` flag seems like it might get forgotten. If it was me, I'd rather get all the details at the same time as getting the DNS details. How about the following?

```
uplink share sj://test-files --access us1 --not-after +2h --dns test.com
Sharing access to satellite 12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S@us1.storj.io:7777
=========== ACCESS RESTRICTIONS ==========================================================
Download  : Allowed
Upload    : Disallowed
Lists     : Allowed
Deletes   : Disallowed
NotBefore : No restriction
NotAfter  : 2023-03-31 04:58:28
Paths     : sj://test-files/ (entire bucket)
=========== SERIALIZED ACCESS WITH THE ABOVE RESTRICTIONS TO SHARE WITH OTHERS ===========
Access    : test
========== GATEWAY CREDENTIALS ===========================================================
Access Key ID: test
Secret Key   : test
Endpoint     : https://gateway.storjshare.io
Public Access: true
=========== DNS INFO =====================================================================
Remember to update the $ORIGIN with your domain name. You may also change the $TTL.
$ORIGIN example.com.
$TTL    3600
test.com    	IN	CNAME	link.storjshare.io.
txt-test.com	IN	TXT  	storj-root:test-files
txt-test.com	IN	TXT  	storj-access:test

(Pro Accounts only) To enable HTTPS for your domain, additionally add the following record:
txt-test.com	IN	TXT  	storj-tls:true
```
