### ISSUE TITLE
Storagenode webpage wrong ave disk usage

### ISSUE THREAD

**Issue by Quake4** [storj/storj#5625]
**Description**
The "Average disk space used in this month" is show average disk by satellite. It must be a SUMM of all satellites by day.
S1: 4GB
S2: 1TB
S3: 8GB
Average: (4 + 8 + 1024) / 3 = 345 GB
Why do I need this figure, what does it show me?

1036 GB shows disk usage by day.

**Screenshots**
![image](https://user-images.githubusercontent.com/29517243/221561358-1d021882-7202-48a6-ad27-8d1de9cb64fd.png)

**Steps to reproduce the issue:**

See stat webpage.

**Describe the results you expected:**
1.8 TB by day.

**Describe the results you received:**
300GB by day

**Possible Fix**

Change AVE to SUMM Satellite disk usage by day

**Your environment**

- Operating system and version: Windows 10
- Additional environment details (Raspberry PI, Docker, VMWare, etc.): No

**Comment by profclems** [comment]
@Quake4 which storagenode version are you running? This might be related to #5519 which has been fixed here https://github.com/storj/storj/commit/3d3f9d133a3416e33f013297ff23ad6fd7acd948 and released as part of v1.73.4

**Comment by Quake4** [comment]
last release v1.71.2

**Comment by profclems** [comment]
[v1.73.4](https://github.com/storj/storj/releases/tag/v1.73.4) will be rolled out soon with the patch. I'll close this issue as it's fixed now.
