### ISSUE TITLE
Bump the connection pool numbers in gateway-mt

### ISSUE THREAD

**Issue by elek** [storj/storj#5627]
## Motivation/Why?

- We use default settings (100 connection / max 5 per destination).
- Connection pool hit rate is very low (<10%)
- We should have enough memory to increase these numbers

## What needs to be done?
- Carefully increase the numbers, deploy new configuration and monitor the memory usage / cache hit rate

## Acceptance Criteria
- Gateway-mt deployed with higher number --> higher connection hit irate
- the graph in https://github.com/storj/storj/issues/5627#issuecomment-1449965749 is roughly 50 percent yellow and 50 percent green.

**Comment by iglesiasbrandon** [comment]
@elek can you please share details on how the edge team could measure this before and after they roll out a change?

**Comment by elek** [comment]
I already created a thanos dashboard:

https://thanos.storj.rodeo/d/z7WqRGbVk/connection-pools?orgId=1

Right now we have two metric:

 * `connection_dialed`: incremented only when we didn't have sg. in the pool
 * `connection_from_cache`: incremented when we used the pool instead of dialing
 
 The overall picture is sg. like this:
 
![image](https://user-images.githubusercontent.com/170549/222127360-44577534-2582-42f1-b6e9-0c88b2846f39.png)

I would like to have more yellow and less green :-)

Same time we need to monitor memory usage / open connections of the `gateway-mt` instances, just to be sure that we are fine.

We can also keep our eyes on performance via gateway. It should be improved when we see better hit/miss ratio for the connection pools

https://thanos.storj.rodeo/d/cdr6CT14z/4mb-performance-improvements?orgId=1

![image](https://user-images.githubusercontent.com/170549/222127926-e787f433-d9ba-483b-a191-d0687ce25f55.png)

I would be happy to help with checking all of these, but couldn't modify the gateway-mt (which is out of my expertise, and should be modified by sb. who is responsible for it ;-) )

**Comment by kaloyan-raev** [comment]
My expectation from past experience is that the overall cache hit rate won't exceed 50% no matter how large we make the connection pool. 50% hit rate is not much different than 10%.

The reason for the poor hit rate is that long-tail cancellation closes many of the connections to storage nodes and they are not returned to the pool. The connection pool is only efficient for the satellite connection where the hit rate is >99.9% if the pool is large enough.

The main benefit of the increased pool size will be that there will be more room for the satellite connections to stay longer in the pool, which would have a positive overall impact on the latency.

**Comment by kaloyan-raev** [comment]
However, it would be worth having again an arch discussion on connection pooling. As it is currently working efficiently only for satellite connections, it would make sense to split the pool into two parts: one small - just for the satellite connections, and another one for the storage nodes connections (which would require other significant changes to start working efficiently).

**Comment by mniewrzal** [comment]
Work for spiting pool into two parts is already in progress https://github.com/storj/storj/issues/5626

**Comment by elek** [comment]
> 50% hit rate is not much different than 10%.

Let's say the connection creation overhead is 200ms. With 50% hit rate we can be faster with 200ms at every 2nd request, which is a 100ms gain in average (compared to 0 pool)

With 10% hit rate, the connection overhead is 9 * 200ms / 10 = 180 ms.

That's a 80ms difference, but it depends on the average connection / handshake time. I have seen more and less than 200 ms connection times. Don't know the real average.

I would be interested to see real life results (what is the gain if we bump the pool to big enough for 50% hit rate).

**Comment by elek** [comment]
(Unit is 1000 ms. `414 977` means 414 ms. And this list contains the measured time of `storj.io/common/rpc.Dialer.dialEncryptedConn` calls )

**Comment by kaloyan-raev** [comment]
OK, worth trying if this satisfies you. Just wanted to point out that the hit rate won't go above 50%, and this is not the main issue with using the connection pool.

**Comment by elek** [comment]
We can wait for the separation of the pools in https://github.com/storj/storj/issues/5626. After that patch, we will have better picture (separated pool and metric for satellite/storagenode connections).

**Comment by elek** [comment]
Using [single thread uploader](https://github.com/elek/stbb/blob/d307738165ebc6f6fbdfce013c919889233706e8/pkg/uplink/download.go#L92) 100 times in sequence:

Without connection pool:

```
stbb uplink download -p 0 -n 100 sj://perf/1mb /tmp/aaa  | grep -E '(connection_|Executed)'
Executed 100 times during 101655 ms (average: 1016.550000 ms) 0.983719 req/secfunction,name=
connection_closed,scope=storj.io/common/netutil total 3923
connection_dialed,scope=storj.io/common/rpc/rpcpool total 4000
```

With 200/5/20*minute connection pool: 

```
Executed 100 times during 37797 ms (average: 377.970000 ms) 2.645713 req/secfunction,name=(*transformedRanger).Range,scope=storj.io/common/encryption current 0
connection_closed,scope=storj.io/common/netutil total 245
connection_from_cache,name=uplink,scope=storj.io/common/rpc/rpcpool total 3500
connection_dialed,name=uplink,scope=storj.io/common/rpc/rpcpool total 500
```

OR:

```
stbb uplink download -p 1 --pool-size 200 -n 100 sj://perf/1mb /tmp/aaa  | grep -E '(connection_|Executed)' 
Executed 100 times during 61058 ms (average: 610.580000 ms) 1.637787 req/secfunction,name=(*transformedRanger).Range,scope=storj.io/common/encryption current 0
connection_closed,scope=storj.io/common/netutil total 231
connection_from_cache,name=uplink,scope=storj.io/common/rpc/rpcpool total 3619
connection_dialed,name=uplink,scope=storj.io/common/rpc/rpcpool total 381
```

Here I download the __same file__ multiple times, which means that I need 81 connection max. 
We opened more connections (381) but the hit rate was 90%> despite the long-tail cancellation.

Looks the just bumping the numbers would give us a significant performance benefit.

**Comment by kaloyan-raev** [comment]
Oh, nice! I am interested to try this with the IPFS gateway too.

**Comment by NiaStorj** [comment]
@elek for connection pooling, are you expecting faster time to first byte or less dropped connections? If so, how would we test it?

**Comment by elek** [comment]
AFAIK first bytes are saved/reported back to Eventkit. We can double-check it, but it will be improved only with the missing connection handshake. For me, it's the same to check the full time vs time to first byte, as we should see the same difference.

I don't know about dropped connections. 
 * For download, they should be cancelled anyway. Don't know if we have good metric for that
 * Neither for upload, but the upcoming uplink refactor will improve that part (instead of giving up, it will try to continue to upload to different servers). I would measure it while we test that code.

**Comment by kaloyan-raev** [comment]
@elek https://review.dev.storj.io/c/storj/gateway-mt/+/9864 addresses most of the work on this issue, right?

So, what's left is to deploy it with proper pool sizes.

**Comment by NiaStorj** [comment]
cc @ferristocrat - see Marton's comments above.
