### ISSUE TITLE
Configure checkerng checks for the refactored upload

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5631]
### Description:
The purpose of this ticket is to compare the performance between the upload code path refactored branch and the main branch. 

### Acceptance Criteria: 
We should check the performance for 4MB and 400 MB objects
We should compare these results to determine how much of a performance improvement the refactor could make.

**Comment by azdagron** [comment]
@elek , everything should be merged into the main branch and enabled via testuplink hooks. Happy to review something when it is available.
