### ISSUE TITLE
Clean up audit error handling

### ISSUE THREAD

**Issue by jtolio** [storj/storj#5632]
Here is the existing audit error handling:

```
		if rpc.Error.Has(share.Error) {
			if errors.Is(share.Error, context.DeadlineExceeded) || errs.Is(share.Error, context.DeadlineExceeded) {
				// dial timeout
				offlineNodes = append(offlineNodes, share.NodeID)
				verifier.log.Debug("Verify: dial timeout (offline)",
					zap.Stringer("Node ID", share.NodeID),
					zap.String("Segment", segmentInfoString(segment)),
					zap.Error(share.Error))
				continue
			}
			if errs2.IsRPC(share.Error, rpcstatus.Unknown) {
				// dial failed -- offline node
				// TODO: we should never assume what an unknown
				// error means. This should be looking for an explicit
				// indication that dialing failed, not assuming dialing
				// failed because the rpc status is unknown
				offlineNodes = append(offlineNodes, share.NodeID)
				verifier.log.Debug("Verify: dial failed (offline)",
					zap.Stringer("Node ID", share.NodeID),
					zap.String("Segment", segmentInfoString(segment)),
					zap.Error(share.Error))
				continue
			}
			// unknown transport error
			unknownNodes = append(unknownNodes, share.NodeID)
			verifier.log.Info("Verify: unknown transport error (skipped)",
				zap.Stringer("Node ID", share.NodeID),
				zap.String("Segment", segmentInfoString(segment)),
				zap.Error(share.Error),
				zap.String("ErrorType", spew.Sprintf("%#+v", share.Error)))
			continue
		}

		if errs2.IsRPC(share.Error, rpcstatus.NotFound) {
			// missing share
			failedNodes = append(failedNodes, share.NodeID)
			verifier.log.Info("Verify: piece not found (audit failed)",
				zap.Stringer("Node ID", share.NodeID),
				zap.String("Segment", segmentInfoString(segment)),
				zap.Error(share.Error))
			continue
		}

		if errs2.IsRPC(share.Error, rpcstatus.DeadlineExceeded) {
			// dial successful, but download timed out
			containedNodes[pieceNum] = share.NodeID
			verifier.log.Info("Verify: download timeout (contained)",
				zap.Stringer("Node ID", share.NodeID),
				zap.String("Segment", segmentInfoString(segment)),
				zap.Error(share.Error))
			continue
		}

		// unknown error
		unknownNodes = append(unknownNodes, share.NodeID)
		verifier.log.Info("Verify: unknown error (skipped)",
			zap.Stringer("Node ID", share.NodeID),
			zap.String("Segment", segmentInfoString(segment)),
			zap.Error(share.Error),
			zap.String("ErrorType", spew.Sprintf("%#+v", share.Error)))
```

there are a couple of issues here, but they all fall into the class of not being specific enough about what case we're looking for.

We need to fix a few things:

1. use of rpc.Error - just because an error came from the common/rpc package does not decisively mean that the problem is something to do with dialing. instead of trying to guess what different error classes mean, we should make GetShare inside DownloadShares return more direct information about when the failure happened, but see point #4.
2. we need to clean up context.DeadlineExceeded error handling, and perhaps do an audit of errs.Is usage. Should we make zeebo/errs.Is also do errors.Is behavior? it currently doesn't, and the context.DeadlineExceeded line is weird and surprising. should errs.Is and errors.Is have identical behavior?
3. we need to be allergic to making assumptions about what unknown errors are. Currently we assume an unknown error means a known dialing error, but that's not at all reliable. We need to know the case we're looking for. Whenever there's a catch-all bucket (such as the rpcstatus.Unknown), we need to not assume we know what's in that bucket. rpcStatus.Unknown should absolutely go into the unknown errors bucket. if we want to make sure it's not an rpc status error, then we should check for the error types it should be.
4. dialing may eventually be 0RTT, in which case we need to do a better job preparing for and distinguishing between offline and contained outcomes.
5. we need to write an explicit test that checks that i/o timeout dial failures are handled appropriately. we don't have one and a change to the go standard library broke audit downtime detection and we didn't know.

**Comment by jtolio** [comment]
Here is the existing audit error handling:

```
		if rpc.Error.Has(share.Error) {
			if errors.Is(share.Error, context.DeadlineExceeded) || errs.Is(share.Error, context.DeadlineExceeded) {
				// dial timeout
				offlineNodes = append(offlineNodes, share.NodeID)
				verifier.log.Debug("Verify: dial timeout (offline)",
					zap.Stringer("Node ID", share.NodeID),
					zap.String("Segment", segmentInfoString(segment)),
					zap.Error(share.Error))
				continue
			}
			if errs2.IsRPC(share.Error, rpcstatus.Unknown) {
				// dial failed -- offline node
				// TODO: we should never assume what an unknown
				// error means. This should be looking for an explicit
				// indication that dialing failed, not assuming dialing
				// failed because the rpc status is unknown
				offlineNodes = append(offlineNodes, share.NodeID)
				verifier.log.Debug("Verify: dial failed (offline)",
					zap.Stringer("Node ID", share.NodeID),
					zap.String("Segment", segmentInfoString(segment)),
					zap.Error(share.Error))
				continue
			}
			// unknown transport error
			unknownNodes = append(unknownNodes, share.NodeID)
			verifier.log.Info("Verify: unknown transport error (skipped)",
				zap.Stringer("Node ID", share.NodeID),
				zap.String("Segment", segmentInfoString(segment)),
				zap.Error(share.Error),
				zap.String("ErrorType", spew.Sprintf("%#+v", share.Error)))
			continue
		}

		if errs2.IsRPC(share.Error, rpcstatus.NotFound) {
			// missing share
			failedNodes = append(failedNodes, share.NodeID)
			verifier.log.Info("Verify: piece not found (audit failed)",
				zap.Stringer("Node ID", share.NodeID),
				zap.String("Segment", segmentInfoString(segment)),
				zap.Error(share.Error))
			continue
		}

		if errs2.IsRPC(share.Error, rpcstatus.DeadlineExceeded) {
			// dial successful, but download timed out
			containedNodes[pieceNum] = share.NodeID
			verifier.log.Info("Verify: download timeout (contained)",
				zap.Stringer("Node ID", share.NodeID),
				zap.String("Segment", segmentInfoString(segment)),
				zap.Error(share.Error))
			continue
		}

		// unknown error
		unknownNodes = append(unknownNodes, share.NodeID)
		verifier.log.Info("Verify: unknown error (skipped)",
			zap.Stringer("Node ID", share.NodeID),
			zap.String("Segment", segmentInfoString(segment)),
			zap.Error(share.Error),
			zap.String("ErrorType", spew.Sprintf("%#+v", share.Error)))
```

there are a couple of issues here, but they all fall into the class of not being specific enough about what case we're looking for.

We need to fix a few things:

1. use of rpc.Error - just because an error came from the common/rpc package does not decisively mean that the problem is something to do with dialing. instead of trying to guess what different error classes mean, we should make GetShare inside DownloadShares return more direct information about when the failure happened.
2. we need dto clean up context.DeadlineExceeded error handling, and perhaps do an audit of errs.Is usage. Should we make zeebo/errs.Is also do errors.Is behavior? it currently doesn't.
3. we need to be allergic to making assumptions about what unknown errors are. Currently we assume an unknown error means a known dialing error, but that's not at all reliable. We need to know the case we're looking for. Whenever there's a catch-all bucket (such as the rpcstatus.Unknown), we need to not assume we know what's in that bucket.
4. dialing may eventually be 0RTT, in which case we need to do a better job preparing for and distinguishing between offline and contained outcomes.

**Comment by zeebo** [comment]
Go 1.20 includes support for errors.Is to look at things that wrap multiple errors by having the error implement `Unwrap() []error`. That's the main thing that errs.Is does that errors.Is does not do. The main thing errors.Is does that errs.Is does not do is call any `Is(error) bool` method if it exists. 

So to unify all that I think:
1. errs.Is should just call errors.Is on Go 1.20+
2. errs.Is should call any `Is` method while unwrapping. This means duplicating the body of `IsFunc` I think.
3. Groups should implement `Unwrap() []error`
4. errs.Is and errs.IsFunc should look for `Unwrap() []error` instead of `Ungroup() []error`

Then I think it matches with the errors package.

**Comment by jtolio** [comment]
Neat: https://github.com/zeebo/errs/commit/5a8c7a4ee1d394a8aeccd2ccb58090b8d3edffaa

**Comment by thepaul** [comment]
> Neat: https://github.com/zeebo/errs/commit/5a8c7a4ee1d394a8aeccd2ccb58090b8d3edffaa

Hmm, that seems to make breaking API changes in a few places. Are we sure it's safe to bump the v1.x series to that?

**Comment by iglesiasbrandon** [comment]
@thepaul what is left to finish up this issue?

**Comment by thepaul** [comment]
Need to finish up the test (bullet number 5). It's written, but not yet working like I expect.
