### ISSUE TITLE
Create uplink experiment to use more than 39 nodes to download...

### ISSUE THREAD

**Issue by elek** [storj/storj#5638]
When we download a file, we need pieces from 29 storagenodes (assuming 1 segment). 

We receive 39 address from satellite and we use all of them, but cancel the remaining downloads after we successfully downloaded from 29.

Sometimes we are not lucky enough to get 39 performant nodes out of the 80 available one. At least this is our assumption.

To prove this assumption we modified the protocol (in storj/common#38769821) to support different number of storagenodes, not just 29.

Once this feature is deployed. (1.74), we can create a patched uplink and compare the performance with uploading from the fastest 29 out of 80 nodes vs the fastest out of 39.

Note: for this experiment we will pay more ingress. If this experiment shows noticeable result, we need to refactor the download code to cancel downloads earlier (to avoid higher payments)

**Comment by elek** [comment]
Blocked on 1.74 release.

**Comment by elek** [comment]
It's not blocked any more...

In fact, I already created a modified version of uplink and started to measure the differences...

Results are here: 

![Image](https://github.com/storj/storj/assets/170549/e8bbfa2c-08d6-4d1e-8be4-42832b996318)

When I used 80 nodes to download (instead of 39) I got better performance with ~200ms (like 1.3 vs 1.5 sec)

--> during the download refactor, we can consider to use better node selection algorithm...

But during the creation of this test, I created an other patch: 

https://github.com/storj/infra/pull/4259

**Comment by shaupt131** [comment]
Also, are we going to act on this finding in any way?  Follow-up or implementation tickets?

**Comment by elek** [comment]
No follow-up tickets for now, but the learnings should be used during the download refactor (it should support more flexible node selection scheme).
