### ISSUE TITLE
Create a plan to reduce inter-region CRDB latencies

### ISSUE THREAD

**Issue by elek** [storj/storj#5639]
Satellite instances from different regions show different latencies to CRDB database:

![Image](https://user-images.githubusercontent.com/170549/222424607-442445a1-7c26-48b2-8a74-f6b840a0d58a.png)

As the difference is significant, we need to investigate how can it be decreased.

**Comment by iglesiasbrandon** [comment]
@elek, we are closing this ticket since @kristaxox and @ethanadams are working on this, and it's covered by other tickets. Let us know if we should reopen.
