### ISSUE TITLE
Satellite UI / Fix file dropdown menu

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5643]
The dropdown menu for files shows wrong icon for preview ( bucket icon ) and it says details. Please change to say Preview and check the correct icon in the Figma design. Also make sure the text in the dropdown items is aligned.

https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=14675%3A106470&t=gAiKRgODIOobysxe-0

![Image](https://user-images.githubusercontent.com/3217669/222522129-01f57a73-96a2-4f10-bd1d-d402fcbd5ee6.png)

**Comment by mobyvb** [comment]
deployed 1.75 https://github.com/storj/storj/commit/fafa6658a9ce2f3b4a7ed99a3
