### ISSUE TITLE
Satellite UI / Add folder sharing

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5644]
We have file sharing, and bucket sharing, and we are missing the folder sharing option.

### Acceptance Criteria

* Users should be able to share folders
  * See Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=23372-298100&t=v1uTP0oL2kNFxHXF-0
* Sharing dialog for files should match the design of folder sharing
  * See Figma: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=23541-311788&t=3v94C3L0LD5S652z-0

**Comment by ferristocrat** [comment]
@boshevski - the first figma link doesn't go to the right place. I just see the cover page:


![Image](https://user-images.githubusercontent.com/7063002/234187649-ce1adaff-7cff-4294-be7f-d0b2453d9fce.png)

**Comment by boshevski** [comment]
Updated the link.

**Comment by mobyvb** [comment]
v1.84 https://github.com/storj/storj/commit/074457fa4e03467cff0c871818d3bd260c15704b
