### ISSUE TITLE
Test blake3

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5649]
https://storj.slack.com/archives/CH6LU8Y64/p1677843027912499

Blake3 implementation inclusive a few tests was here: https://github.com/storj/storj/commit/4b1be6bf8e1bb8c147ef44d4607c755734d27016

- [x] Do we have good automated tests for blake3 uploads inclusive audits and repair? How about graceful exit?

- [x] It would be great to modify one of the upload for the backwards compatible test to use blake3. Olders uplinks should be able to download the file?

- [ ] We could also run some tests with storj-up. One issue is that storj-up is currently missing the new audit job. So this requires fixing storj-up in the first place.

**Comment by littleskunk** [comment]
We should modify the repair test a bit and add one test for GE.

Once upon a time, I was able to corrupt a file with the help of the repair service. I uploaded a file to 10 nodes. I took enough nodes offline that only the minimum pieces are available. This would still allow a successful repair. Now I copied one piece from a folder inside the storage node to a different location to override the important piece. This will make it so that there is one piece missing for a successful repair. The problem is the repair job can still download a corrupted piece from the storage node. So if it doesn't check for corruption it will continue to repair the file and with the corrupted piece in the mix, the entire file gets damaged. -> Solution: The repair job needs to verify the signed piece hash. This was later implemented but I don't know if we ever added a test for this special case. We would need that test for both hashing algorithms.

**Comment by ihaid** [comment]
`// verify that the original piece hash and replacement piece hash match
	if !bytes.Equal(originalPieceHash.Hash, replacementPieceHash.Hash) {
		return ErrInvalidArgument.New("Piece hashes for transferred piece don't match")
	}`

**Comment by littleskunk** [comment]
Meeting notes:
Igor has shown me some repair tests that are playing around with the signed piece hash / detecting a corrupted piece with that. Adding blake3 should be easy there.

For GE we also have some test in place that we should be able to change.

We didn't check audit. There shouldn't be a need for that because the audit job doesn't verify the hash at all.

For the backwards compatibility test we are still blocked. Let's get the automated test for repair and GE passing in jenkins before requesting a solution for the backwards compatibility test.

**Comment by ihaid** [comment]
merged to main
