### ISSUE TITLE
Implement design to set user’s preference to see encryption passphrase prompt

### ISSUE THREAD

**Issue by lizzythomson** [storj/storj#5651]
Implement design to remember the user's preference to skip encryption passphrase prompt when opening/changing projects. Set the passphrase_prompt column to true, if the user selects to “remember to skip prompt”.

Figma design https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=21815%3A254032&t=4ovArnpEgEpxtCD3-0

Issue that added the passphrase_prompt column to user_settings table  - https://github.com/storj/storj/issues/5613

**Comment by mobyvb** [comment]
closing because it is a duplicate
