### ISSUE TITLE
Strange spikes reported by checkerng instances

### ISSUE THREAD

**Issue by elek** [storj/storj#5652]
There are random spikes in the performance (5-10 second download times).

And we don't have any idea what are those.

We need to collect distributed (or local) traces to find them out

![Image](https://user-images.githubusercontent.com/170549/223088320-baf19e01-fa05-46ef-834c-b68c2071727f.png)

**Comment by elek** [comment]
Modification is created to collect traces:

https://review.dev.storj.io/c/storj/storj/+/9881

**Comment by shaupt131** [comment]
@elek do we have these traces now that the above PR is merged?  Or are we waiting on a deploy?

**Comment by elek** [comment]
We don't have traces yet. It should be enabled, but I prefer to use released uplink in the retrievability checkers. The easiest thing to do is just waiting for the next release ;-) 

But I have one test with `uplink-main` I can replace that one, and hope that we have spikes, there, too...

**Comment by elek** [comment]
After I switched to 1.75, I don't see the spikes any more. 

We have trace collection in place, will continue analyses when we see the problem again.



![Image](https://user-images.githubusercontent.com/170549/227472316-ee633b9c-88a8-4b04-af8e-e3dda77c9c0e.png)
