### ISSUE TITLE
stats.storjshare.io/data.json: Reports null on some metrics since 2023-02-08

### ISSUE THREAD

**Issue by Sembeth** [storj/storj#5657]
**Description**
On https://stats.storjshare.io/data.json some values report null.

**Steps to reproduce the issue:**
1. Go to https://stats.storjshare.io/data.json and copy everything.
2. Use a pretty json formatter to make it easier to read.
3. See all null values. In the following, only the null values are included:
12rfG3sh9NCWiX3ivPjq2HtdLmbqCrvHVEzJubnzFzosMuawymB@europe-north-1.tardigrade.io:7777": {
    "storage_median_healthy_pieces_count": null,
    "storage_min_healthy_pieces_count": null,
    "storage_remote_segments_lost": null,
 },
12tRQrMTWUWwzwGh18i7Fqs67kmdhH9t6aToeiwbo5mfS2rUmo@us2.storj.io:7777": {
    "storage_total_bytes": null,
 },
1wFTAgs9DP5RSnCqKV1eLf6N9wtk4EAtmN5DpSxcs8EjT69tGE@saltlake.tardigrade.io:7777": {
    "storage_median_healthy_pieces_count": null,
    "storage_min_healthy_pieces_count": null,
    "storage_remote_segments_lost": null,
}

**Alternative way to reproduce:**
If you scroll down to "Saltlake details" at https://storjstats.info/d/storj/storj-network-statistics?orgId=1, you will see "No data" instead of a graph. Please note that the absolute time range should be from 2023-02-08 00:00:00 to 2023-03-08 23:59:59. If the absolute time range is set from 2023-02-07 00:00:00 to 2023-03-08 23:59:59, then data will be displayed.

**Screenshots**
![image](https://user-images.githubusercontent.com/46921730/224057087-283196a7-a9f8-47b1-a7b2-be58dab169ad.png)

**Alternative steps to reproduce the issue:**
1. Go to https://storjstats.info/d/storj/storj-network-statistics?orgId=1
5. Scroll down to 'Saltlake details'
6. "No data" is displayed for:
- "Healthy Pieces Saltlake (Median)" https://storjstats.info/d/storj/storj-network-statistics?orgId=1&from=1677525060989&to=1678129860989&viewPanel=542
- "Healthy Pieces Saltlake (Min)" https://storjstats.info/d/storj/storj-network-statistics?orgId=1&from=1677525071387&to=1678129871387&viewPanel=543
- "Healthy Pieces Saltlake" https://storjstats.info/d/storj/storj-network-statistics?orgId=1&from=1677525079730&to=1678129879730&viewPanel=546

**Describe the results you expected:**
The graphs should display data.

**Additional information you deem important (e.g. issue happens only occasionally):**
I tried to solve the problem first at https://github.com/toconspiracy/storj-stats/issues/3, but copied it here because it can only be solved by someone who has access to the satellites and https://stats.storjshare.io/data.json.

**Your environment**
Browser: Chrome 64 Bit, Edge
Version: [Version 1.48.171 Chromium: 110.0.5481.177 (Offizieller Build) (64-Bit)]

**Comment by grafael** [comment]
The data for saltlake is back.

**Comment by Sembeth** [comment]
Amazing response time. Thank you very much.
