### ISSUE TITLE
Alternative way for storing orders in DB

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5669]
Currently we have problem with performance of inserting data into `bucket_bandwidth_rollups` table (see https://github.com/storj/storj/issues/5332). We did some attempts to tune existing solution to handle load but that did't solve problem completely. Most probably problem is generated by inserting from different API pods at the same time. This situation is causing lots of transaction retries and flushing is slow.

We want to try alternative approach which will first flush all orders to a bucket (DCS) and then insert that data from single pod (`core`) to DB. General flow will look like that:
* rollups write cache won't be limited to 1000 entries but will be unlimited, no flush after reaching cache limit
* rollups write cache will be flushing data every 15min
* rollups write cache will upload rollups to a bucket after marshaling data into JSON, each batch of data will be uploaded into unique key
* new chore will be added to `core` peer
* new chore will read bucket every minute and will:
   * process every object in root of bucket by downloading, unmarshaling and inserting data into `bucket_bandwidth_rollups`
   * processed object will be moved under prefix `processed`

The outcome of this ticket is to define the implementation that will be done as a part of another ticket.

**Comment by stefanbenten** [comment]
How large should these files uploaded to the DCS bucket be? It will either just hit the DB again (inlined) or create lots of overhead on the storagenodes to store just a couple of bytes of data..
I strongly encourage to not use a object storage for this, rather than something central like a redis/postgres instance.

**Comment by mniewrzal** [comment]
Of course size of uploaded file will be be related to interval time (longer interval larger file). I will get some data to estimate it.

>  It will either just hit the DB again (inlined)

I'm not sure if I agree with this. data should be better rolled up and we won't be hitting the same range from multiple locations. Now we are doing flushing data almost every second.

> create lots of overhead on the storagenodes to store just a couple of bytes of data.

Yes, that can be a problem. As wrote above I will try to do some calculations.

> I strongly encourage to not use a object storage for this, rather than something central/tailored for it like a redis/postgres instance.

By this you mean to just put data (e.g. JSON) I mentioned in redis or postgres instead of bucket?

**Comment by mniewrzal** [comment]
if we will have 10k of unique entries then JSON should have something about 1.5-2MB (compressed much less)

**Comment by mniewrzal** [comment]
I'm closing this ticket. We should continue with #5711
