### ISSUE TITLE
Check benefit of NOISE on full storagenode distribution space

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5671]
To make sure we won't have any new surprises when we globally enable NOISE, we can test NOISE connection.

One tool what we have is that we can upload/download piece to each of the existing storagenodes. That can be improved to support noise.

It would also help to understand the noise support of longtail, and the benefit of NOISE introduction...

**Comment by shaupt131** [comment]
https://thanos.storj.rodeo/d/cdr6CT14z/4mb-performance-improvements?orgId=1&from=1678967469000&to=now

**Comment by shaupt131** [comment]
Before: https://thanos.storj.rodeo/d/cdr6CT14z/4mb-performance-improvements?orgId=1&from=1678147200000&to=1678798072000

**Comment by elek** [comment]
Just repeated the measurement. Not so important for proving NOISE usefulness (it's proven), but it's good to save as a reference and see Noise / QUIC differences

https://storj.slack.com/archives/C03HL81FLRK/p1679646278584929
