### ISSUE TITLE
Satellite UI / Bug / Encryption passphrase prompts twice for new accounts

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5675]
Bug report:
Signed up for a new account and was immediately prompted to enter the project passphrase again after landing in the UI

Check out video here:
https://storj.slack.com/files/U035R7QAGBY/F04TUA21NDA/2023-03-13_16-38-31.mp4

**Comment by mobyvb** [comment]
1.76 https://github.com/storj/storj/commit/6857a48a0b61626
