### ISSUE TITLE
Allow retrieving a web UI session using a REST API key

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5688]
Provide a way to get a session cookie using a rest api key rather than providing email/password credentials

Current token endpoint set up here: https://github.com/storj/storj/blob/bf45e531699de7e06/satellite/console/consoleweb/server.go#L292

Implementation of the current endpoint: https://github.com/storj/storj/blob/bf45e531699de7e06f10df49f999d0a1277a5ece/satellite/console/consoleweb/consoleapi/auth.go#L85

For rest API key authentication, see references to `keyAuth` in consoleweb/server.go and `KeyAuth` in console/service.go

If an API key is provided, bypass captcha if enabled.

AC:

* If I have a REST API key, I can invoke a token endpoint authorized with this API key, without providing email/password, and a cookie will be set
* If hcaptcha is enabled on login, I do not receive an hcaptcha challenge upon requesting a token with API key authentication
* Another option is to simply alter the existing token endpoint to bypass captcha if a REST API toke is used

**Comment by onionjake** [comment]
Initially my gut said that there was a better way to do this than giving out another session cookie, but essentially the session cookie is already a token with an expiration that would be refreshed.

@jtolio Any thoughts on this? See any pitfalls or problems with the session cookie approach?  Would it be better now to switch to some other more standard's driven approach?

**Comment by jtolio** [comment]
this seems fine to me!

**Comment by mobyvb** [comment]
deployed in v1.80 https://github.com/storj/storj/commit/7e69b22dd44a6f0a75bf5696c7fe91db7bc1cb15
