### ISSUE TITLE
Handle account freeze warnings better

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5691]
When an account freeze warning event has been triggered, the user should be able to add a credit card and pay their unpaid invoice to be removed from the "warning" state.
When a user is removed from the warning state, a corresponding Segment event should be sent, so that workflows can be updated based on this trigger.

AC:
* User can exit from warning by adding a card, similar to unfreeze when adding a card
* Event is sent to segment when user pays invoices and they are frozen or warned
* After paying invoices, neither warn nor freeze events remain in the freeze events table
* Send us1, eu1, and ap1 events to segment, so that we can set up workflows based on these

**Comment by NiaStorj** [comment]
@ferristocrat follow up with Mary at LakeOne to determine if 1 event is fine or 1 event for each suspension and deletion email flows.

**Comment by mobyvb** [comment]
1.76 https://github.com/storj/storj/commit/ed70a03844b420fbe1e3dfb0
