### ISSUE TITLE
Implement email change functionality

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5692]
We should probably split this into multiple tickets

Design for this is in the Vuetify repo

See more details, e.g. how to change email in Stripe, Hubspot, etc... in original investigation ticket here https://github.com/storj/storj/issues/5040

First steps:
* new config flag
* new db columns
* email templates (two verification emails + email change success email)

AC below can be modified if a different approach is preferred by whoever is implementing it:

### AC:
* Config added, e.g. `console.email-change-enabled`
* UI added if feature enabled in satellite config (needs figma link)
* DB columns added to track "new, unverified email address" (default null), and "email change verification count" (default 0)
* "change email" endpoint implemented:
  * takes new email as an argument, updates DB "new unverified email address"
  * sends two verification emails - one to old/current email, one to new unverified email
* new verification email flow implemented:
  * these verification emails will contain links that hit a separate endpoint from the signup verification flow
  * exactly two verification emails are sent out per change request, and each link must be clicked exactly once to fully authorize the email change
  * for each verification link, if unused, increment the corresponding "email change verification count" in the DB
  * if after updating the email change verification count, it is 2, proceed with "email change finalization"
* "email change finalization" when both verification links have been clicked
  * change email in Stripe
  * change email in Hubspot/Segment (if easy - if not, create additional tickets)
  * set `email` and `normalized_email` columns in DB
  * unset "new, unverified email address column" in DB; set "email change verification count" to 0
  * send confirmation email to new address that email change finished successfully

**Comment by ferristocrat** [comment]
Pulling this out of "Up Next" since we need some design updates: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=22322%3A261874&t=FegXHb2ffcqMEeKr-1

@boshevski

**Comment by NiaStorj** [comment]
@boshevski have you been able to get to the design update request from above?

**Comment by boshevski** [comment]
We decided to postpone this for now.
