### ISSUE TITLE
Run Playwright tests in Jenkins

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5695]
Blocked by https://github.com/storj/storj/issues/6598

### AC:
* make it possible to run playwright tests with Go (no docker), e.g. by using something like testplanet + edge
* run these tests in Jenkins somewhere
* verify that all V2 tests are passing and remove V1 tests

**Comment by ferristocrat** [comment]
@storj-antonio knows the current status of playwrite tests and how they are running on GitHub changes.

**Comment by mobyvb** [comment]
This change enabled UI tests for Github builds:
https://github.com/storj/storj/commit/1cfb8d207af8ebf13b71cb7dcd400408c2dcb12c
