### ISSUE TITLE
Add bonus transactions on top of Storjscan transactions

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5702]
### Description 
We want to add the ability for the satelllite to add a small bonus transaction for each storjscan transaction it sees.

### Context
We incentivize customers to pay for their usage in STORJ Token by giving them a 10 percent 'bonus' for the amount they deposit into their accounts. Currently, if a customer deposits $100 USD worth of STORJ Tokens, we manually update their stripe customer balance to apply a $10 USD Credit to be used on one of their next invoices. We want to eliminate having to manually make these adjustments as well as removing these bonuses from the Stripe customer balance. 

### Acceptance Criteria:
- We can set a percentage for a bonus per transaction
- Only applies to storjScan transaction type
- Satellite added an additional transaction for bonus alongside the transactions it receives from storjScan

**Comment by iglesiasbrandon** [comment]
@dlamarmorgan You might be interested in reviewing this change, Andrew has a PR open!

**Comment by iglesiasbrandon** [comment]
@azdagron we need to make sure we only do the bonus transaction when the status of the user deposit is confirmed. (aka it meets the min block confirmations we have set in the config.)

**Comment by azdagron** [comment]
This is already the case. The billing chore only receives confirmed storjscan transactions from the storjscan "payment type".
