### ISSUE TITLE
502 errors in satellite ui

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#5703]
**Description**

- Dashboard and billing pages fail to load, with errors (see screenshots)
- Looks like the following GET request is what's failing:
  - https://us1.storj.io/api/v0/payments/account/charges

**Screenshots**
| Screenshot | Description |
|------------|-------------|
| ![image](https://user-images.githubusercontent.com/7063002/227316907-1e963f74-9252-4bdc-9022-b87da4a790f8.png) | Billing Screen Missing Project Breakdowns |
|![image](https://user-images.githubusercontent.com/7063002/227318303-902e53ab-231c-4374-9f56-e85d207a91ef.png) | UI Error |
|![image](https://user-images.githubusercontent.com/7063002/227423116-a9446071-c195-4bdb-bea7-a80481b9ce16.png)|Dev tools `502` error|

**Steps to reproduce the issue:**

Scenario 1
1. Login
2. Dashboard fails to load and observe the errors

Scenario 2
1. Navigate to Billing page
2. Project cost breakdown doesn't show up
3. "can not get project charges" error 

**Describe the results you expected:**
Project charges should appear.

**Describe the results you received:**

- Project stats fail to load.
- Project cost breakdown on billing page missing
- 502 errors on both dashboard and billing overview

**Additional information you deem important (e.g. issue happens only occasionally):**

- Seems like accounts with the "Storjlings" coupon have this problem but others do not
  - michael@storj.io >> sees errors
  - michael+test1@storj.io >> no errors

**Your environment**

- Operating system and version: Chrome or Brave on Windows 11

**Comment by jewharton** [comment]
This is possibly resolved by https://review.dev.storj.io/c/storj/storj/+/9984, but I currently lack enough information to know for certain.
