### ISSUE TITLE
accountfreeze chore. Account unfreeze logic problem

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5705]
Problem: unfreeze after adding CC, not after charging

We freeze accounts because invoices are unpaid. One possible way to end up there would be the use of a prepaid credit card that we can't charge. Now if the user just add the same credit card again we unfreeze them and allow them to abuse our service for additional 30 days. The user can repeat that over and over again. Our trigger to unfreeze an account should be the successful invoice and not adding a credit card that we can't charge.

Steps to reproduce with test Stripe - add CC 4000000000000341  (card with no funds)
User has unfrozen acc and can use it to next billing cycle. After new freezing -> just add it again -> unfrozen

**Comment by lizzythomson** [comment]
@andriikotko this change (https://review.dev.storj.io/c/storj/storj/+/9961) should have fixed this bug

**Comment by mobyvb** [comment]
deployed in v1.76 https://github.com/storj/storj/commit/ed70a03844b420fbe1e3dfb0d95bcdd58e597a51
