### ISSUE TITLE
Test Automation: Signed piece hash

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#5708]
### Goal:
This is test automation for the upload codepath refactor project.  

In this scenario, we're looking to test that uplink is unable to commit a segment without providing a signed piece hash. And the new uplink still needs to call the CommitSegment function.

### Acceptance Criteria:
- A functional test that the QA team can use to execute the test plan.

### Links:
Test Plan: https://github.com/storj/storj/blob/f0ea6afaa09b07e3ece9c3a5b98e2132f0249b7f/docs/testplan/uplink-refactor-testplan.md
Project Schedule: https://docs.google.com/spreadsheets/d/1ok5WOYNB_qeVOlsVS4-394vqp_IbmpN8MBPThdez6ew/edit?usp=sharing

**Comment by iglesiasbrandon** [comment]
We want to make sure that you can't commit an object to the satellite if the Storage nodes which should be storing pieces for it don't agree

**Comment by iglesiasbrandon** [comment]
We might already have an automated test for this. We did not change the commit segment functionality on the satellite as a part of the upload code path refactor. @littleskunk

**Comment by iglesiasbrandon** [comment]
Here is the applicable test! @littleskunk https://github.com/storj/storj/blob/main/satellite/metainfo/endpoint_segment_test.go#L504-L521 
closing this issue.
