### ISSUE TITLE
Test Automation: Duplicate pieces

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#5709]
### Goal:
This is test automation for the upload codepath refactor project.  

In this scenario, we need to request 80 pieces and claim that they didn't work, then request an additional 80 pieces and try to commit all 160 pieces as a result there shouldn't be duplicates in it

### Acceptance Criteria:
- We need to make sure that the commit segment API has an upper bound on the number of pieces the uplink can reference. 
- A functional test that the QA team can use to execute the test plan.

### Links:
Test Plan: https://github.com/storj/storj/blob/f0ea6afaa09b07e3ece9c3a5b98e2132f0249b7f/docs/testplan/uplink-refactor-testplan.md
Project Schedule: https://docs.google.com/spreadsheets/d/1ok5WOYNB_qeVOlsVS4-394vqp_IbmpN8MBPThdez6ew/edit?usp=sharing

**Comment by iglesiasbrandon** [comment]
We might have an automated test for this, If we do please add a link to it on this ticket and close it!

**Comment by jtolio** [comment]
okay: https://review.dev.storj.io/c/storj/storj/+/10165
