### ISSUE TITLE
Improve visibility of SN download times

### ISSUE THREAD

**Issue by elek** [storj/storj#5723]
When we download a small file, we download it from 29-39 nodes with different latencies. 

However the piece download times are (if we have pooled connections) are very similar. Like this:

![Image](https://user-images.githubusercontent.com/170549/228202690-397ec625-3168-4394-b34a-fcc76a6dda4f.png)

Our best explanation so far is the TCP back pressure (by JT). We EC chunks, therefore the reads supposed to be happen at roughly the same rate. 

But still we don't fully understand what's happening.

We should have better visibility here. Ideally we should have access to the following information from a distributed traces:

 * Which nodes were used to download pieces
 * Connection time for each nodes
 * Full download time for each nodes (excluding the time we waited for other downloads)

There are two ways to solve this:

 * Either we should do some monkit magic if possible
 * Or use this experimental download code: https://github.com/elek/stbb/tree/main/pkg/downloadng, but it requires a few days to be finished.

Let's use what is easier...

**Comment by shaupt131** [comment]
Being that this is in "code review", what action is required next?

**Comment by elek** [comment]
First step is down, but it was not a `5` story. With more improvements, maybe, but first let's wait for the production of this change...
