### ISSUE TITLE
spam emails after account creation

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5727]
**Expected Behavior**
I created a test account at the end of January. I would give you 2 maybe 3 emails. One of the emails would be the account activation email. I would also expect you to send me an upgrade to pro account email. And one you get as an bonus for some marketing you would like to send.

In the long run you might also send me one email per month. I will most likely be too lazy to hit the unsubscribe link so with one email per month you would still catch my attention.

User friendly would be an opt in approach. Give me a checkbox on signup would be best.

Just to be sure you understand this bug correct. Even the people that would opt in to these spam mails don't expect to receive an unlimited number of spam emails. So please do both. Limit the number of emails and add an opt in checkbox. With an opt in approach I would be willing to give you 2 emails per month.

**Actual Behavior**
I received 11 emails in a bit over 30 days. So one spam email every 3 days. Oh boy. This is escalating. One year ago I received about 5 emails. This is not Ok. This has to stop. I don't want to receive 20 spam emails in a year from now! Stop this spam mail flood!
```
Activate your email
Welcome to Storj - Here are resources to get you started
You did it! Your first object was uploaded on US1
Storj Intro: How can I help?
Your guide to start using Storj for backups
A simple way to test drive Storj for S3 compatibility
Your Feedback Matters. Would You Recommend Us?
A simple way to test drive Storj for sharing files
A simple way to test drive Storj for video streaming
We need your feedback about Storj DCS
A simple way to test drive Storj for IPFS pinning
```

**Comment by NiaStorj** [comment]
@mobyvb @ferristocrat discuss with Marketing on how to proceed with this.

**Comment by NiaStorj** [comment]
12/19/24:

Workflows have changed. Closing as not planned
