### ISSUE TITLE
Uplink cli with unencrypted-path doesn't list in alphabetical order

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5735]
**Expected Behavior**
uplink ls should print out in alphabetical order

**Actual Behavior**
The order is almost correct except for file names that start with a high cap
```
KIND    CREATED                SIZE        KEY
OBJ     2023-03-30 19:45:33    574061      Unicorn.gif
OBJ     2023-03-30 19:45:15    705         abort.sh
OBJ     2023-03-30 19:45:15    32768       abort.txt
```

**Comment by NiaStorj** [comment]
we probably can't support this unless there is an option for a bucket to use unencrypted paths. This would require some design and discussion.

**Comment by jtolio** [comment]
uplink with unencrypted paths are going to list in byte or ascii order, and capital letters come before lowercase in that ordering. doing something else is going to be a significant undertaking. i think this should be a won't fix

**Comment by ferristocrat** [comment]
Agreed.
