### ISSUE TITLE
Add STORJ Bonus Transaction to STORJ transactions table

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#5755]
### Goal

- We automated adding the STORJ 10% bonus as an additional StorjScan transaction and should show it in the STORJ transactions table in the UI (Billing > Payment Methods > See Transactions)

### Acceptance Criteria

- Transactions for bonus amounts present in table
- Implement the Figma designs [here](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=23823-317260&t=VPyBndwFONF29TtR-0)
    - ensure there is a row for both the deposit and the bonus transaction in the UI, like for the design
    - if it is easy to detect, when a transaction is confirmed, display a success notification like in the UI
    - if it is not easy (>2 story points of effort), create a new ticket to update the UI based on STORJ transactions that are in progress, so that we can display the number of confirmations and/or a success notification when enough confirmations have occurred

Transaction Details:
```
{
    UserID:      transaction.UserID,
    Amount:      calculateBonusAmount(transaction.Amount, bonusRate),
    Description: fmt.Sprintf("STORJ Token Bonus (%d%%)", bonusRate),
    Source:      StorjScanBonusSource,
    Status:      TransactionStatusCompleted,
    Type:        TransactionTypeCredit,
    Timestamp:   transaction.Timestamp,

}
```

### Links
- PR where change has been implemented: https://review.dev.storj.io/c/storj/storj/+/10029

**Comment by mobyvb** [comment]
@dlamarmorgan or @azdagron or @thepaul do any of you know what still needs to be implemented after https://review.dev.storj.io/c/storj/storj/+/10029?

**Comment by dlamarmorgan** [comment]
I don't know exactly what Product Team has in mind for the UI changes, but right now the user has no indication that their bonus has been added, unless they manually calculate what the bonus should be, and make sure the Storjscan balance total is the same as what they calculated. Personally, I think we should show the bonus as a separate row in the list of transactions on the GUI.

**Comment by boshevski** [comment]
Storj bonus transaction figma:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=23819-316960&t=1tcCE591zVuzI8u1-0

**Comment by littleskunk** [comment]
> if it is not easy (>2 story points of effort), create a new ticket to update the UI based on STORJ transactions that are in progress, so that we can display the number of confirmations and/or a success notification when enough confirmations have occurred

Has this been implemented? If not where do I find the follow up ticket?

**Comment by wilfred-asomanii** [comment]
No, I didn't

**Comment by mobyvb** [comment]
@littleskunk I created a ticket here https://github.com/storj/storj/issues/5978
