### ISSUE TITLE
Add pagination to common table component

### ISSUE THREAD

**Issue by jewharton** [storj/storj#5765]
## Motivation
We wish to allow users to limit the amount of items displayed on their screen at once.

## Acceptance Criteria
* Pagination is added to the common table component and is styled according to our designs.
* The default number of items is 10, but users can select other options.
  * Other options: 25, 50, 100, All. The "All" option should not be available for tables with a very large number of objects.

## Figma Designs
https://www.figma.com/file/b3QhctHccKl3ihR8Q063Af/DCS-Design-Library?node-id=3799-58701&t=ZUTh5vZBC6dur9L0-0

**Comment by boshevski** [comment]
Hey @jewharton the default should be 10, other options include 25, 50, 100, All. 
Depending on the table, maybe no All option in the table with the objects because it might have thousands of objects.
