### ISSUE TITLE
Satellite UI / Update modals for passphrase, projects, and buckets

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5777]
[Figma design.](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?node-id=22626-263722&t=PkuUPvzJNjkYYPmM-0)

Update all modals related to the passphrase, projects, and buckets, to match the new designs of the access grants.

There are some new modals in the designs, like the request for more projects on Pro Accounts, and Skip passphrase when opening a project.

**Comment by mobyvb** [comment]
we split this out into a bunch of other tasks

**Comment by mobyvb** [comment]
closing because the work is tracked in other tickets 
https://github.com/storj/storj/issues/5814
https://github.com/storj/storj/issues/5815
https://github.com/storj/storj/issues/5817
https://github.com/storj/storj/issues/5818
https://github.com/storj/storj/issues/5819
