### ISSUE TITLE
Release-v1.77 Test Project Accounting

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5779]
[4db3d33](https://github.com/storj/storj/commit/4db3d33) satellite/accounting: check bucket existance with GetProjectObjectsSegments

Modify the automated test that was added with this commit to also test billing estimation. We still expect the used space to show up on the final invoice and billing estimation after the customer deleted the bucket.

**Comment by ihaid** [comment]
was covered here https://github.com/storj/storj/blob/fc3d31e7322d720649fd5f9de1ddd03b97c81949/satellite/accounting/billing_test.go#L105
