### ISSUE TITLE
Create DB cleanup chore

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5790]
### Description: 

In order to minimize the amount of unnecessary information that satellites keep track of, we require a chore that periodically removes unwanted records from the database.

Initially, this chore should be responsible for removing records for unverified user accounts. An unverified account is one whose email address was never confirmed, so the user has never actually logged in or used the product. We should improve how we handle these unverified accounts so they are not in this state forever. 

### Acceptance Criteria: 

- A chore is added that removes unverified user account records whose creation date is earlier than a specified time in the past.
- A config flag is added for specifying the maximum lifetime of unverified user account records.
- A config flag is added for specifying the interval between cleanup chore cycles.

**Comment by ferristocrat** [comment]
My vote is for x=7 days
