### ISSUE TITLE
Map missing locations for object preview (server side copied objects)

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#5792]
**Description**

When an object is a server-side copy of another object, the map does not work on the copied object. (The map works on the original object.

A common s3 pattern is to upload, then copy as a type of rename...

**Screenshots**
<img width="637" alt="image" src="https://user-images.githubusercontent.com/7063002/232613116-1374c74f-413c-4bfe-a7b2-6c00d339a8a9.png">

**Steps to reproduce the issue:**

1. Upload object
2. Copy object as a type of rename (common s3 pattern)
3. See object preview in Satellite UI for copied object

**Describe the results you expected:**
Expect to see the geolocation details of which nodes are storing the object on the map. (the file size is well over the threshold to store on the network rather than just metadata)

**Describe the results you received:**
The map is empty.

**Comment by egonelbre** [comment]
Possibly related to https://github.com/storj/storj/issues/5789

**Comment by NiaStorj** [comment]
fixed. see ticket #5789
