### ISSUE TITLE
Investigate backwards compatibility tests regarding Blake3 and modify if necessary 

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#5796]
## Background:

As part of the Blake3 rollout, we need to test for backward compatibility.  

We would like to be sure that key which is uploaded with new uplink + blake3 can be downloaded with an old uplink.

backward compatible test of `storj/storj` tests only latest release with the main branch, but we have backward compatible test in `storj/uplink` which uses old uplink during testing: https://github.com/storj/uplink/blob/main/testsuite/backcomp/old_uplink_test.go

It should be modified to download both blake3/sha256 hashed keys with the old uplink.

## Acceptance Criteria:
-Confirmation that tests have been modified and are now suitable for use.

**Comment by elek** [comment]
https://github.com/storj/storj/issues/5796
