### ISSUE TITLE
Optimize redis round trips in `redisLiveAccounting.GetAllProjectTotals`

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#5800]
Bucket tally process on `core` peer is now taking much more time that some time ago (https://github.com/storj/storj-private/issues/232). It's because we reorganize which region keeps which pods. Turns out that `acconting/live` redis cache method `GetAllProjectTotals` is doing much more requests to redis than we anticipated. With latency spike it multiply time we need to execute `GetAllProjectTotals`. We need to optimize this method.

Acceptance Criteria:
* combine multiple GET requests into single MGET request to avoid roundtrips

**Comment by iglesiasbrandon** [comment]
i think we can close this issues since its been deployed @mniewrzal @shaupt131
