### ISSUE TITLE
Satellite UI: separate domains with user generated content

### ISSUE THREAD

**Issue by pwilloughby** [storj/storj#5805]
**Summary**
When storjshare.io domain is blocked the satellite file browser will not work for customers. This is becoming a bigger issue as our public storjshare.io domain continues to get flagged for hosting harmful/malicious content.

**Propose a Solution**
Have the satellite UI talk to edge on it's own dedicated domains that are never used for user generated content so they won't be blocked and the satellite UI always works.

* Configure the satellite UI to use the new dedicated domains: auth.storjsatelliteshare.io, gateway.storjsatelliteshare.io, link.storjsatelliteshare.io
* Enhance the satellite UI to use the storjshare.io domain as the base url for user generated linkshares 

**Additional context**
The issue for the corresponding edge side work is https://github.com/storj/gateway-mt/issues/320

**Acceptance Criteria**
* Determine if this can be accomplished with only a config change (see littleskunk's comment below). If so, create a WIP PR in storj/infra with the necessary changes, and contact Artur on the Edge team for next steps
* Otherwise, make a storj/storj code change with the necessary changes, and create a WIP PR in storj/infra with the necessary changes, and contact Artur on the Edge team for next steps

**Comment by littleskunk** [comment]
It might work with just a config change. Here is what I am currently using for storj-up tests. In my case I make sure I use a single address for all request but it might also work if we just set 2 different domains:
```` 
# running storjup on a remote server "datengrab" instead of localhost. Remove this block if you run it on localhost
storj-up env setenv satellite-api STORJ_CONSOLE_GATEWAY_CREDENTIALS_REQUEST_URL=http://datengrab:8888
storj-up env setenv satellite-api STORJ_CONSOLE_LINKSHARING_URL=http://datengrab:9090
storj-up env setenv authservice STORJ_ENDPOINT=http://datengrab:9999
storj-up env setenv linksharing STORJ_PUBLIC_URL=http://linksharing:9090,http://datengrab:9090
```
