### ISSUE TITLE
Update delete object method name

### ISSUE THREAD

**Issue by dlamarmorgan** [storj/storj#5821]
The method DeleteObjectAnyStatus that has been exported for testing purposes should have it name updated to something more descriptive (like InternalDeleteObjectAnyStatus) so as to not accidently get added to an rpc set.

**Comment by ifraixedes** [comment]
When a method is used only for testing we are using to prefix them with `Testing`.
Example: https://github.com/storj/storj/blob/efcae857ba859dfde055aae4b008c97e96c777b1/satellite/repair/checker/observer.go#L90
