### ISSUE TITLE
Make bandwidth/storage graphs in satellite UI smoother

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5826]
Existing storage and bandwidth graphs in the UI:

![Image](https://user-images.githubusercontent.com/1323312/234424021-b9d37175-09df-4cdf-bc3f-4390b9d482da.png)

For comparison, this is how similar line graphs look in the storagenode UI:

![Image](https://user-images.githubusercontent.com/1323312/234426497-c989083b-7c2f-4392-8c4d-1bf0e790fd36.png)

AC:
* Make the lines of the graphs in the Satellite UI project dashboard smooth, like on the storagenode dashboard

**Comment by VitaliiShpital** [comment]
@mobyvb I remember we made them less smooth because of some problem that may cause some missunderstandings for the user. Probably @littleskunk and @andriikotko know the details
