### ISSUE TITLE
Release-v1.78 Test Account Freeze / Unfreeze

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5828]
[8632e28](https://github.com/storj/storj/commit/8632e28) web/satellite: show freeze warning banner

account unfreeze should be fixed last realease

My thoughts for this test run:
1. Create a new storj-up instance, create a new user
2. Make sure to login with that user first before doing anything else -> Stripe customer gets created
3. Call storj-up testdata command to fix the customer creation date. Otherwise invoicing will fail.
4. Create unpaid invoice in stripe. https://storjlabs.atlassian.net/wiki/spaces/OPS/pages/349044868/Storj+DCS+Customer+Invoice+Generation
5. Wait for the account freeze job.
6. Check database if the warning state was set
7. Check satellite UI if account freeze status is warn (dev console)
8. Check if there is a message in the UI visible.

9a) What happens if the customer updates payment information with a test credit card that rejects payments. https://stripe.com/docs/testing#declined-payments
9b) What happens if the customer adds a valid credit card that can be charged.
9c) What happens if the customer ignores the message and waits for account freeze. Up next add credit card that rejects and a credit card that works.
9d) Token payments

**Comment by ihaid** [comment]
![Image](https://user-images.githubusercontent.com/38665104/234816373-bf34549b-5c96-4bf2-bbd0-50c9343a3343.png)

**Comment by ihaid** [comment]
`ERROR   payments.accountfreeze:chore    accountfreeze/chore.go:77       Could not get userID    {"invoice": "in_1MizavHUqQsjaswpNvrpQe5K", "error": "account-freeze-chore: stripecoinpayments service: customer doesn't exist", "errorVerbose": "account-freeze-chore: stripecoinpayments s`

**Comment by littleskunk** [comment]
Warning message looks good. That bug is fixed.

When adding a credit card that is unable to pay the outstanding invoices we show an error message but still add the credit card in the background. The account doesn't get unfrozen. So from that perspective bug fixed.
