### ISSUE TITLE
stats.storjshare.io/data.json: Reports null on some metrics since 2023-04-13 18:45:00

### ISSUE THREAD

**Issue by Sembeth** [storj/storj#5838]
**Description**
On https://stats.storjshare.io/data.json some values report null.

**Steps to reproduce the issue:**

1. Go to https://stats.storjshare.io/data.json and copy everything.
2. Use a pretty json formatter to make it easier to read.
3. See all null values. In the following, only the null values are included:
  "12EayRS2V1kEsWESU9QMRseFhdxYxKicsiFmxrsLZHeLUtdps3S@us1.storj.io:7777": {
    "storage_median_healthy_pieces_count": null,
    "storage_min_healthy_pieces_count": null,
  },
  "12L9ZFwhzVpuEKMUNUqkaTLGzwY9G24tbiigLiXpmZWKwmcNDDs@eu1.storj.io:7777": {
    "storage_median_healthy_pieces_count": null,
    "storage_min_healthy_pieces_count": null,
  }

**Describe the results you expected:**
The data should not be null or it will not be displayed in https://storjstats.info/d/storj/storj-network-statistics?orgId=1 for example.

**Additional information you deem important (e.g. issue happens only occasionally):**
As it happened before in https://github.com/storj/storj/issues/5657 it would be awesome if you could add some kind of monitoring to see if there is a null value.

**Comment by Sembeth** [comment]
@grafael you solved this the last time. Maybe you can help again?

**Comment by grafael** [comment]
Already solved and we are going to work in a long term solution soon. Also, this is the repot where we should create issues related to public API: https://github.com/storj/stats

**Comment by Sembeth** [comment]
That was a quick response. Sorry I didn't knew about the other repo.
