### ISSUE TITLE
Update default multipart size so filebrower can utilize refactored upload code

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#5851]
### Background:
We need to change this value: https://github.com/storj/storj/blob/19e9ca921a85f1e1a80bdfe9cd401172a5adf6d3/web/satellite/src/store/modules/objectBrowserStore.ts#L386 to something that will be optimal for the filebrowser to get the most benefit from the refactored upload codepath.  The initial thought is 1GB.  

Additional context here: https://storj.slack.com/archives/CH6LU8Y64/p1683118309355809 and here: https://forum.storj.io/t/upload-refactoring/22559

### Goal:
-Figure out the ideal setting
-Make it the default

**Comment by iglesiasbrandon** [comment]
@shaupt131 @ferristocrat @mobyvb @NiaStorj i think this is a team console item, I am going to move it to your project. Please let me know if you all have any issues with that.
