### ISSUE TITLE
Project Invites: Create and implement new invite emails

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5860]
Designs for existing users here: 
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=22865-266407&t=TrweD9M1Pe5Zg5Kc-0

Designs for new accounts here:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=22866-266406&t=TrweD9M1Pe5Zg5Kc-0

AC:
* Create files for the two emails above in web/satellite/static/emails, along with the existing invite email
* Replace logic that sends existing project invite email to use the new one (first link in this issue)
* Implementing "invite a new user" is not a part of this task - that will be handled in https://github.com/storj/storj/issues/5353

**Comment by NiaStorj** [comment]
https://storj.slack.com/archives/C0490040EDR/p1684783657361279

**Comment by NiaStorj** [comment]
@boshevski we will be going with no image versions for the invite email for now, to prevent being blocked on moving forward with this feature. 

cc @mobyvb @wilfred-asomanii @ferristocrat

**Comment by boshevski** [comment]
Ok, let me know if i can help to solve this issue, since we must add the logo in the emails.

**Comment by wilfred-asomanii** [comment]
I think we can add the logos to the emails. The images bellow the "accept invitation" buttons however are huge and we've not settled on how to add them without affecting initial load times.
