### ISSUE TITLE
Update project options menu

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5866]
This ticket concerns this portion of the UI when the "all projects dashboard" is enabled:

![Image](https://user-images.githubusercontent.com/1323312/237237975-22355d4b-b16c-4e34-a6e3-5ad2b1044019.png)

AC:
* Change "create new" to "create new project"
* When all projects dashboard is enabled:
  * do not display "manage projects" item
  * above "manage passphrase", add an item "all projects" with the project icon for now

project icon: 

![Image](https://user-images.githubusercontent.com/1323312/237238349-c86d233e-05b1-4f68-84bf-b1e8a776f498.png)

**Comment by boshevski** [comment]
Figma designs here: 
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=24006-329979&t=IbovTo37WQJwQ1mP-0
