### ISSUE TITLE
Make better notification in case if user exceed bandwidth limit

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5876]
For now when user exceed bandwidth limit we show them this
<img width="873" alt="Screenshot 2023-05-12 at 15 28 04" src="https://github.com/storj/storj/assets/14928042/33fc099a-e048-4fc8-b4ea-67caa48e9852">

**Comment by mobyvb** [comment]
this may be an edge task; @amwolff what do you think?
even if it is on edge services, perhaps console team can work on it

**Comment by mobyvb** [comment]
@andriikotko how are you reproducing this error? What actions do you perform to get to this error page?

**Comment by NiaStorj** [comment]
@andriikotko is this still relevant?
