### ISSUE TITLE
Add the ability to geofence at the account level automatically

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5879]
## Description

Customers need the ability to create new projects and buckets without having to file a support ticket to ensure those projects and buckers have the correct placement settings. with our current implementation a customer must request for us to manually add the placement settings on every single bucket they create. 

If a placement is set for that customers account
- all new projects and new buckets in the account inherit the geo fence setting from the account

If a placement is set for a project
- all new buckets created in the project inherit the geo fence settings from the project

If a placement is set for a bucket
- all data is stored in the geofence for the bucket

## Acceptance Criteria: 
- We are able to set a placement for customer's entire account 
- We are able to set a placement for a customers project
- We are able to set a placement for a bucket (this already exists) 
- If a customer creates a new project that project would inherit the placement set at the account level
- if a customer creates a new bucket that bucket would inherit the placement set at the project level

## Edge Cases
- What if we set the geo fence at the account level for a customer who already has a project with buckets? 
    - the existing project and buckets will NOT get the geofence added

**Comment by iglesiasbrandon** [comment]
@mniewrzal @jtolio  can you give me some initial feedback on this ticket?

**Comment by jtolio** [comment]
Seems fine to me. I don't really understand why a customer would want to make a bunch of projects, but okay.

**Comment by shaupt131** [comment]
A few questions to help me clarify scope: 

- the customer will still contact support to apply the desired geofence, but this gives them the choice of having us apply it at an account, project, or bucket level?
- Are we changing any of the current pre-set geofence location options or expanding the selection beyond what's currently available (EU and US I think)? 
- What if the customer has a custom geofence request? 
- What would the response be if they want to geofence an existing bucket?  Download > create new bucket > reupload?

**Comment by iglesiasbrandon** [comment]
> A few questions to help me clarify scope:
> 
> * the customer will still contact support to apply the desired geofence, but this gives them the choice of having us apply it at an account, project, or bucket level?
- That is correct.

> * Are we changing any of the current pre-set geofence location options or expanding the selection beyond what's currently available (EU and US I think)?
- We are expanding what is is currently available.

> * What if the customer has a custom geofence request?
- We can consider expanding the options we offer to accommodate the customer. Expanding our options should not be something we take lightly. 

> * What would the response be if they want to geofence an existing bucket?  Download > create new bucket > reupload?
- yes, I think so, but with the new functionality we are implementing, we might be able to update the setting on the bucket and the data would just be repaired out automatically. The issue with this is it would cost us money in terms of bandwidth when we have to repair the data to meet the geo fence settings.

**Comment by elek** [comment]
https://review.dev.storj.io/c/storj/storj/+/10508
https://review.dev.storj.io/c/storj/storj/+/10507
https://review.dev.storj.io/c/storj/storj/+/10505
