### ISSUE TITLE
ix-system starter package screen. Clicking on set session timeout banner automatically set "Free Account" for user

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#5883]
ix-system starter package screen. Clicking on set session timeout banner automatically set "Free Account" for user
<img width="1137" alt="Screenshot 2023-05-15 at 18 51 25" src="https://github.com/storj/storj/assets/14928042/fa0510ae-9128-4210-95ff-cbe7fc87263b">

**Comment by mobyvb** [comment]
just saw this, but I ended up making a duplicate ticket with more general requirements: https://github.com/storj/storj/issues/5884
Do you have a preference for which ticket to keep @andriikotko? If not, I will close this ticket and keep #5884
