### ISSUE TITLE
Security: Better use ECDSA Signatures than Basic Auth

### ISSUE THREAD

**Issue by BlackDuck888** [storj/storj#59]
The current Bridge is able to handle ECDSA signatures already, why STORJ step back in security and uses Basic Auth again.

https://github.com/storj/storj/blob/7fde8b908a8fe72639747e0aaeb30d8d3eb390e5/pkg/client/buckets.go#L29

**Comment by jtolds** [comment]
Just for context - the code in storj/pkg/client is for interop with v2. v3 will work differently

**Comment by BlackDuck888** [comment]
Why this work, to interop with vv? v2 is dead!

**Comment by kaloyan-raev** [comment]
This was a sort of experiment for the team to try out Go. Once we have enough v3 pieces ready, the client will be update to work with v3.

**Comment by BlackDuck888** [comment]
I think in this case i was to fast with this issue, better close is that this does not mess github. i keep track of the code if i find simelar things i can open a new one, when the time is ready for it.

**Comment by kaloyan-raev** [comment]
Thanks for keeping an eye on the code. We need more eyes like these.
