### ISSUE TITLE
Add testautomation for adding geofencing on exiting bucket

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5901]
https://github.com/storj/storj-private/issues/276

Write 2 automated tests. 1 test should already exist.
1. Not enough nodes in the geofence region for repair download:
Testplanet network with 5 nodes or so. An upload is originally stored on 3 of the 5 nodes in a way that only one is located in a specific geonfence region. 2 piece are required to reconstruct the file. The remaining 2 nodes are not holding any data yet but also located the the target geofence region. Add geofencing to the bucket.
Expectation: The repair job should kick in. Does it respect the geofence setting for downloading the file? In this edge case it should ignore geofencing, download the file from the 3 storage nodes even if they are outside the target region, reconstruct the file, replace the 2 nodes that are outside the region with the 2 nodes that are inside the region. Result should be that the file is stored on 3 nodes inside the geofence region.
2. Remove pointer with no repair upload:
Testplanet network with 5 nodes or so. An upload is originally stored on 3 nodes. 1 extra piece because of `overlay.repair-excluded-country-codes`. That one extra node is outside the target geofencing region. Add geofencing to the bucket.
Expectation: The repair job should kick in and just delete that 1 extra node. Does this still work even if the file has the maximum number of pieces? There is no repair download or upload needed. We just need some job to remove that one extra piece created by `overlay.repair-excluded-country-codes`
3. I believe we already have one automated test for a bucket that has geofencing set, customer uploads a file, one node moves to a different location, repair should remove the piece that is now stored outside the region. If it doesn't exist we should add it.

**Comment by ihaid** [comment]
I see that we have test for bucket geofencing and not for node geofencing
https://github.com/storj/storj/blob/6f2d6a97a606d331d6f25fa609b243e09b00579b/satellite/metainfo/endpoint_object_test.go#L1467

**Comment by mniewrzal** [comment]
I think at the moment point 1 and 3 will fail as repair is not taking into account segment placement. We are just now implementing changes to cover that:
https://github.com/storj/storj/issues/5895
https://github.com/storj/storj/issues/5896

Point 2 I think should pass.

**Comment by ihaid** [comment]
https://github.com/storj/storj/blob/c48bd81e5ffddaafbd725d0a92ad072d348c51d6/satellite/audit/verifier_test.go#L1088

**Comment by ihaid** [comment]
https://review.dev.storj.io/c/storj/storj/+/10452
This PR introduce the logic and test for 3 TC

**Comment by littleskunk** [comment]
@ihaid I would like to add one test case to the mix.

Test number 2 is about removing any additional node from the pointer. Let's repeat that test but with one modification. What happens if the segment has not reached the repair threshold but also has not reached the optimal threshold. With the original numbers of test 2 that doesn work. So new idea would be:
2/2/4/4 as the RS setting and by the time we trigger repair the segment has 3 pieces + 1 extra piece (2a) and 4+1 (2b). That way we cover a bit more of the possible range that we might find in production.
