### ISSUE TITLE
One big bug. Latest 1.76.2. Node under latest. Email: Your Node is Below the Minimum Version

### ISSUE THREAD

**Issue by Quake4** [storj/storj#5936]
![Screenshot_2023-05-31-21-39-26-74_21da60175e70af211acc4f26191b7a77](https://github.com/storj/storj/assets/29517243/efc270ba-e44a-4dea-8e93-778f789b3e0b)

**Comment by Quake4** [comment]
![Screenshot_2023-05-31-21-46-56-38_21da60175e70af211acc4f26191b7a77](https://github.com/storj/storj/assets/29517243/bcb8a5fc-e2dc-4b87-bacb-32d556a8bf59)

**Comment by littleskunk** [comment]
The trigger for the email is the minimum version set in our satellite config. The satellite config is not public so you are not able to see the current value. That is the reason we implemented the email to give feedback to outdated node. The current value is: `overlay.node.minimum-version: v1.77.0`. 

That means the email is correct. v1.76 is indeed not getting selected for any uploads.

For updating your storage node I would suggest to not look at the latest release tag on docker. Better use our version control for that. https://version.storj.io/
```
"storagenode":{
"minimum":{"version":"1.78.3","url":"https://github.com/storj/storj/releases/download/v1.78.3/storagenode_{os}_{arch}.zip"},
"suggested":{"version":"1.79.4","url":"https://github.com/storj/storj/releases/download/v1.79.4/storagenode_{os}_{arch}.zip"},
```

That should keep your node up to date. We offer an autoupdater that will keep care of that.
