### ISSUE TITLE
Add support link to /activate page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5940]
We want to remove the support link from the signup success pages, e.g. https://www.storj.io/signup-success/ap1. That way, we first direct users to try and resend the activation email on their own, and then contacting support is a last resort.

In order to do this, we should add the support link to the /activate route in the satellite UI, e.g. https://us1.storj.io/activate

Such as "If you still do not see a verification email within 5 minutes of submitting this form, please [contact the support team](link)"

AC:

* /activate page contains a link to the support team
* after these changes are deployed, signup success pages on webflow are updated to remove the link to submit a support ticket:
  * https://www.storj.io/signup-success/us1
  * https://www.storj.io/signup-success/eu1
  * https://www.storj.io/signup-success/ap1

**Comment by VitaliiShpital** [comment]
Hey @mobyvb! I don't think that we even need to add support link to /activate route because we have it on success screen after initial resend. See the video

https://github.com/storj/storj/assets/46756926/08682095-641f-4725-9c19-a685d72664a4

**Comment by mobyvb** [comment]
changes have been published to www.storj.io. Closing and moving to "done"
