### ISSUE TITLE
Run Versions Test has an intermittent error

### ISSUE THREAD

**Issue by elek** [storj/storj#5948]
Run Versions Test is failing on `main` / release builds.

Having failures on almost every day:

2489
2490
release builds...

**Comment by elek** [comment]
The biggest problem is it downloads a lot of thing. We need to rewrite this test IMHO. Delivery team already planned this, but it was not prioritized. Until that we can separate it from the mail build.

https://review.dev.storj.io/c/storj/storj/+/11786

**Comment by elek** [comment]
@shaupt131 One remaining part is prioritize the fix (probably Team Delivery?), or remove the test if not important any more...

**Comment by shaupt131** [comment]
Thanks! Captured and will discuss with the Delivery team during sprint pre-plan.

**Comment by shaupt131** [comment]
Discussed during sprint planning call with delivery team.  We will get back to finishing up test migrations to Storj-Up in a future sprint.

**Comment by iglesiasbrandon** [comment]
going to close this ticket since the missing fix is captured in the ticket @shaupt131 mentioned above.
