### ISSUE TITLE
Satellite UI Freezes When Entering Wrong Passphrase on Bucket with Millions of Objects

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#5954]
**Description**

When you skip entering your project passphrase then click on a bucket with millions of objects, then enter a different passphrase than was used in the bucket, the UI just freezes.

**Screenshots**
![image](https://github.com/storj/storj/assets/7063002/2325ce70-95fd-4d54-83b1-04dbeb4667b9)

**Steps to reproduce the issue:**

1. Open project and skip entering your project passphrase
2. Open a bucket with millions of objects
3. Enter a wrong passphrase

**Describe the results you expected:**

Would expect either an error or an empty bucket (since there are no objects uploaded using the entered passphrase).

**Describe the results you received:**

Application freezes.

**Comment by NiaStorj** [comment]
Timebox: 1 day
