### ISSUE TITLE
Satellite UI limit area shows wrong free tier usage

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#5958]
**Expected Behavior**
Customer with 2 project should see how much of his estimated invoice amount is covered by the free tier coupon.
![image](https://github.com/storj/storj/assets/6333390/a0625a0b-4a8b-4cd1-9d41-3b1416f8a2b0)

**Actual Behavior**
The free tier coupon usage only shows the project that is currently selected. The customer might think that everything is covered by the free tier coupon when in reality other projects are eating up the free tier coupon.
![image](https://github.com/storj/storj/assets/6333390/a48ae4e4-7088-4131-beff-1707d06aa67c)

**Comment by NiaStorj** [comment]
@mobyvb @andriikotko is this still relevant?

**Comment by boshevski** [comment]
Not relevant anymore.
