### ISSUE TITLE
Satellite UI / Bucket Sharing

### ISSUE THREAD

**Issue by boshevski** [storj/storj#5964]
Add option to share a bucket from the bucket menu in the buckets page.

Figma design:
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=23541-319019&t=4nJD8l0pAclR1XPy-0

**Comment by mobyvb** [comment]
v1.84 https://github.com/storj/storj/commit/062ca285a0f4b53cf8db23efb92317bf88bd9a8f
