### ISSUE TITLE
Update storj/infra to support separate API and UI container

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#5967]
### Objective 
Update infrastructure and deployment process to deploy satellite ui and api separately.

### Acceptance

- Front end and back end containers are deployed separately and can communicate as needed
- Document created that outlines the  new setup/process
- Feature flag in place

This is a prerequisite to deploy the changes made here: https://github.com/storj/storj/issues/5843
```[tasklist]
### Tasks
- [ ] https://github.com/storj/infra/issues/4636
```

**Comment by mobyvb** [comment]
@NiaStorj @ferristocrat @cam-a @ethanadams I added a tasklist to this ticket with two followup tasks, based on the discussion we had today. Please review and let me know if I missed anything:
https://github.com/storj/infra/issues/4636
https://github.com/storj/infra/issues/4637

**Comment by cam-a** [comment]
waiting on QA to smoke test it
