### ISSUE TITLE
Satellite UI project role design updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5972]
Low contrast "member" tag on project dashboard:

![Image](https://user-images.githubusercontent.com/1323312/245629455-2336e7b8-a5a7-4de0-a628-dca946ae3a1f.png)

Desired (white bg)

![Image](https://user-images.githubusercontent.com/1323312/245629522-9fd6ff9b-a494-4574-b2fe-c7bf671ab63a.png)

[Designs for separating projects based on role in navbar dropdown](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=19586-192799&t=AIUKSnTQ6toUuU2C-0)

AC:
* use a white background for the "member" tag so that the text is easily visible regardless of the background
* separate "my projects" from projects "shared with me" in the navbar dropdown according to the designs in the figma link above

**Comment by boshevski** [comment]
Please also change the project member role color to #00ac26

**Comment by wilfred-asomanii** [comment]
fixed in 361f9fdb

**Comment by wilfred-asomanii** [comment]
@boshevski is the last AC correct?

**Comment by boshevski** [comment]
@wilfred-asomanii i updated the AC, thanks
