### ISSUE TITLE
Upload hover component functional updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5973]
### Summary 
This issue focuses on enhancements the upload experience. It involves refining the upload count to exclude files already uploaded, making completed uploads clickable for preview, and adding a "cancel all" button to terminate all current and upcoming uploads.

### Acceptance Criteria
* When a new upload is started, the message in the hover component `uploading <x> items` should _not_ include files that were already finished uploading prior to the new upload
* Files that have completed uploading in the hover component should be clickable. Clicking them should open the object preview in the filebrowser
* A "cancel all" button should be added to the hover component; when clicked, _all_ current and upcoming uploads should be canceled

### Designs

- Figma Link: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=24798-332385&t=vAfhyugIhOA7tsYT-0
- Starting a new upload after a completed upload:
  ![Image](https://user-images.githubusercontent.com/1323312/245630716-ef3f7b3b-debd-4873-a335-1f052b7b06a9.png)

**Comment by boshevski** [comment]
Here are the designs for cancel all feature:
 
https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=24798-332385&t=vAfhyugIhOA7tsYT-0

**Comment by mobyvb** [comment]
v1.84 https://github.com/storj/storj/commit/4e876fbdbabef87af1839807bdf73d88c5104d90
