### ISSUE TITLE
Upload hover component styling updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5974]
Current upload hover component:

![Image](https://user-images.githubusercontent.com/1323312/245630474-f9280b4a-ee8e-42de-b543-fdcd3a43c7ec.png)

Desired shadow styling for upload hover component:

![Image](https://user-images.githubusercontent.com/1323312/245630501-f966b79a-a6f0-4370-9681-c3c27e75c827.png)

File list icons:

![Image](https://user-images.githubusercontent.com/1323312/245632009-8e074f4e-21d9-4773-bd7b-f34b8f86a3c1.png)

Hover component icons:

![Image](https://user-images.githubusercontent.com/1323312/245632107-71f2a031-a5a2-4728-891f-895b74eb6836.png)

AC:
* same shadow styles for banner notifications (second screenshot) should be applied to upload hover component (first screenshot)
* same file icons from file list (third screenshot) should be applied to upload hover component (fourth screenshot)

**Comment by boshevski** [comment]
Hey @VitaliiShpital the shadow is added in the figma. Also could you please add success check icon for completed uploads? 

https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=12654-66742&t=vAfhyugIhOA7tsYT-0
