### ISSUE TITLE
Display pending STORJ transactions in UI

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#5978]
### Objective 
Display STORJ transactions that are in progress, so that we can display the number of confirmations and/or a success notification when enough confirmations have occurred

Location in the UI: Billing -> Payment Methods

### Acceptance Criteria
- Front end matches design
  - Shows pending and number of confirmations
  - Once enough confirmations have occurred, shows success
- User upgraded to Pro Account automatically after verifying completed transaction that is more than $10

**Comment by boshevski** [comment]
Link to design:

https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=24185-332617&t=sbTRvQCJ6z3rzUi0-0

**Comment by boshevski** [comment]
Upgrade user to Pro Account automatically after verifying completed transaction is more than $10.

**Comment by mobyvb** [comment]
v1.85 https://github.com/storj/storj/commit/2d2f1b858e382d801712fb6f79c0371c07ce45d2
