### ISSUE TITLE
Signed node tag reporting

### ISSUE THREAD

**Issue by jtolio** [storj/storj#5982]
Following along from https://github.com/storj/storj/issues/5981, we want to have a basic facility for storage nodes to be able to be configured to report a signed node tag. Though https://review.dev.storj.io/c/storj/storj/+/9978/6/docs/blueprints/certified-nodes.md imagines many possible node tag signature processes, for now we are just going to have storage nodes be able to be configured in their config file a comma-separated list of serialized signed node tag protobufs (base64?)

Along with other tickets (e.g. #5983), the expected flow for something like Project Mustang will be for someone to provide a list of node ids, for us to generate a bunch of signed node tags with a small CLI tool, and then for the Project Mustang operator to configure their nodes with the right signed node tags in their config files.

AC:
 * Configuration for comma separated signed node tags
 * Node reports these signed node tags up through node checkin

Bonus points:
 * maybe we don't report every checkin, but at some low-resource-using rate.

Notes:
 * There is ongoing discussion about whether storage node tag signing can be improved for operators of many nodes, and this configuration described above is no exception. However, these protocol buffers are forwards compatible, and so the basic functionality of a node taking a serialized protocol buffer and submitting it on checkin is still useful even if we make some larger changes to who signs and when, so this ticket is useful either way.

**Comment by elek** [comment]
> Along with other tickets (e.g. https://github.com/storj/storj/issues/5983), the expected flow for something like Project Mustang will be for someone to provide a list of node ids, for us to generate a bunch of signed node tags with a small CLI tool, and then for the Project Mustang operator to configure their nodes with the right signed node tags in their config files.

This doesn't scale very well. It means that each individual storagenodes should be signed manually. 

I would create a simple dss service which would issue tags automatically based on a secret.

1. configure your (personal) secret + dss endpoint in storagenode config
2. during startup SN will replace the secret with node specific tags calling the dss

But agree, this is not for this ticket anyway, we need this reporting.

> However, these protocol buffers are forwards compatible

Still I am wondering if enabling multiple signatures would be more forward compatible... But it complicates the database schema on the satellite site...

Just to cover this more advanced use case:

![image](https://github.com/storj/storj/assets/170549/39372312-a2bb-4bcb-b62b-c42e93638b23)

But probably this person based signature magic should be part only the SNO/SN --> DSS communication which would simplify the SN -->  SATELLITE checkin...
