### ISSUE TITLE
Basic node tag signing CLI tool

### ISSUE THREAD

**Issue by jtolio** [storj/storj#5983]
This ticket creates a small standalone tool that will take a list of node ids, and a full node identity, and sign CLI argument provided tags for each of the node ids, generating serialized signed node tag protocol buffer data structures, one per node id.

See note on #5982

**Comment by ifraixedes** [comment]
As far as I can remember each node has its own identity, so, if an operator has several nodes, it creates an identity for each individual node. The identity contains the Node ID.

Assuming that I'm not wrong about what I wrote above, how the tool can only use one identity to sign tags for different nodes IDs?

**Comment by ifraixedes** [comment]
I'm responding myself. The identity to pass isn't the identity of a Storagenode, it's of Node which can be whatever (Satellite, etc.).

Sorry for my misunderstanding.
