### ISSUE TITLE
Node selection based on signed node tags

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5991]

**Comment by shaupt131** [comment]
Need reviews on:
https://review.dev.storj.io/c/storj/storj/+/10711/13
https://review.dev.storj.io/c/storj/storj/+/10710

**Comment by shaupt131** [comment]
Looks like everything is merged here?  Anyone know of any outstanding tasks?

**Comment by shaupt131** [comment]
Tags were generated for all of the US3 nodes as of late last night (7/17).  Seems to be working, but will await confirmation from @kristaxox before we close this issue on the SPC project board.  Cc: @iglesiasbrandon
