### ISSUE TITLE
Errors are displayed when logging out of Team page

### ISSUE THREAD

**Issue by jewharton** [storj/storj#5995]
**Description**

When logging out of the satellite UI while in the Team page, unexpected error notifications are always displayed.

**Acceptance Criteria**

- The source of these errors is addressed so that the error notifications are not displayed anymore.

**Screenshots**

![Image](https://user-images.githubusercontent.com/18622881/248386658-e6f5fdbf-4467-455d-aea2-978c90013764.png)

**Comment by VitaliiShpital** [comment]
this bug can't be reproduced using storj-up nor in production
