### ISSUE TITLE
Add the ability to update invoice status with a new command

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#5999]
## Description
We need the ability to bulk-update invoice statues from past invoices that are essentially uncollectible. 

The name of the command should be updateInvoiceStatues? (or whatever the engineer who works on this thinks it should be)

## Acceptance Criteria
- The command must allow you to specify what you want the invoice status to be updated to for "OPEN" invoices.
    - paid, void, or uncollectible (https://stripe.com/docs/invoicing/overview#invoice-statuses)
- The command must allow you to input a date range (start and end date) to find invoices on Stripe to update the invoice status
- The command should NOT change the invoice status for any invoice that is draft, paid, void, or uncollectible

**Comment by iglesiasbrandon** [comment]
@dorrie55 this command will NOT look for specific customers it will look for ALL invoices within a specific time range that are "open" and it will update the status of all of those invoices to what ever we specify

**Comment by dlamarmorgan** [comment]
peer review
https://review.dev.storj.io/c/storj/storj/+/10668
