### ISSUE TITLE
Security: Passing passwords as pointer than as values

### ISSUE THREAD

**Issue by BlackDuck888** [storj/storj#60]
It could be better to pass the password or security relevant parts as pointer, in this case only one copy resists in memory and could be better removed, otherwise there are multiple copies of password in ram, and could be find easier, you have to rely on the garbage collector doing its job correct and fast.

https://github.com/storj/storj/blob/7fde8b908a8fe72639747e0aaeb30d8d3eb390e5/pkg/client/buckets.go#L48

**Comment by jtolds** [comment]
better would be to use https://github.com/awnumar/memguard or the techniques in it. that said, our threat model isn't robust to client side eavesdropping anyway

**Comment by BlackDuck888** [comment]
Moving around or hundreds of copys both is bad, but a first step could be limit the points where the devs have control over the data, memguard and other solutions where great in final version.

**Comment by dv29** [comment]
Is this valid anymore? Or what are other instances that this is valid for?

**Comment by jtolds** [comment]
I'm going to close this for now
