### ISSUE TITLE
Account activity will be suspended in 15 days

### ISSUE THREAD

**Issue by Th3Van** [storj/storj#6000]
I just got this email today : 

![image](https://github.com/storj/storj/assets/18688983/2a0e05b7-44f6-4542-809d-f0623cba47e2)

Not knowing which particular account, the email are referring to, id assumed that it's my most active DCS account.

But when looking at my account, I can't figure out why I'm getting this email and notification while logged in.
I'd say that my payment information should be fine, for paying Storj for it's services :)

![image](https://github.com/storj/storj/assets/18688983/c084ffa1-6d76-43ba-b261-ee4f2cc70b71)

![image](https://github.com/storj/storj/assets/18688983/b7cb135d-4c5d-4057-b676-0fbc843de5b1)

Am I overlooking something ?

Th3Van.dk

**Comment by heunland** [comment]
@Th3Van please could you file a support ticket on our [help desk](https://supportdcs.storj.io/hc/en-us/requests/new) so we can look into correcting this issue. Thanks!
