### ISSUE TITLE
Make separate Vuetify app (with no backend) and deploy it

### ISSUE THREAD

**Issue by VitaliiShpital** [storj/storj#6002]
The main idea here is to make public what we have now. New Vuetify app doesn't have to be connected with backend since it's just a UI thing. Consider github pages?

**Comment by boshevski** [comment]
Can we also make sure it gets updated automatically when there is updates in the repo?

**Comment by ferristocrat** [comment]
I'm not sure what the problem we're solving here is...  is that the current Vuetify app is coupled with the deployment of our backend?
