### ISSUE TITLE
Remove warned users from account freeze table

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6004]
### Summary
Since we are toggling the account suspension flow off for now, we want to remove the relevant entries regarding the users that have been warned.

### Acceptance
- Remove entries that were inserted with an event of 1 (warning) in account freeze table on production satellites
  - leave all the entries with an event of 0 (suspension/freeze)

**Comment by littleskunk** [comment]
```
DELETE FROM account_freeze_events WHERE event=1
```

**Comment by thepaul** [comment]
185 rows deleted from us1
31 rows deleted from ap1
152 rows deleted from eu1
