### ISSUE TITLE
Missing account unfreeze with STORJ token payment

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#6010]
**Expected Behavior**
The STORJ token is a utility token. Customers should be allowed to use the service with STORJ tokens. Customers with a failed invoice should be processed by automated account freeze. Adding STORJ tokens to cover the outstanding invoice should unfreeze them.

**Actual Behavior**
The first failed invoice will trigger the automated account freeze but there is no way to avoid the account freeze at the end. Adding STORJ tokens doesn't unfreeze the account. Now we have a customer with enough balance for the failed invoice but nothing happens. Because the failed invoice still is in the system the account freeze process will continue sending emails, freezing the account, and potentially even deleting the account.
The customer is forced to file a support ticket. That is not acceptable.

**Alternative Solution**
Don't freeze customers with a STORJ balance and no CC. Let them continue using the service for free. This is not a long-term solution. It is just a workaround to make sure customers with STORJ balance don't get trapped. Maybe handle these customers with the hands-on account freeze process that we have in place for bigger customers.

**Comment by ferristocrat** [comment]
What about just creating a prod owner tasks (assuming prod own has ability to run the command) for these occurrences to run `AttemptPayOverdueInvoices`. We could update the email with something like "If you use Storj token, please contact support when you have added token.

Then we could follow up with a custom list perhaps like the >$100 scenario, or just build in the check for Token deposit as a trigger to retry payment

**Comment by littleskunk** [comment]
For a utility token that still feels wrong. The long-term solution should be the same treatment as CC without support tickets.

Furthermore, I am not sure if `AttemptPayOverdueInvoices` will work here. The token amount is an additional invoice item. So from my understanding, we need to correct the invoice first.

**Comment by NiaStorj** [comment]
has already been implemented
