### ISSUE TITLE
Resending project invitation not possible before expiration

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#6031]
**Expected Behavior*
Customer has invited one of his coworkers. The coworker deleted the invitation email by accident. He asks if the project owner can resend the invite.

**Actual Behavior**
Resending an invite is only possible after 7 days. We should show the resend button also on any pending invite.
![image](https://github.com/storj/storj/assets/6333390/9302fd72-bf6f-4d0c-a24e-5af7a227e019)

**Comment by ferristocrat** [comment]
This may have been fixed by the latest changes to the invite flow. If it's not an issue, whoever picks it up can just close it out.

**Comment by wilfred-asomanii** [comment]
The decision to do it this way was made in [this thread](https://storj.slack.com/archives/C0490040EDR/p1686874535667719). The alternative to resending we provided is copying the invite link.
