### ISSUE TITLE
List/table view for all projects dashboard

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6036]
### Overview

- **Section**: All Projects Dashboard -- Projects View
- **Description**: The all projects dashboard doesn't yet have the table view for projects or the ability to toggle between table and card view.

### Acceptance Criteria
- Table component added to all projects dashboard
  - Use the same table component that is already implemented elsewhere in the Vuetify app
- User has the ability to toggle between table and card view
- Default view is: Less than or equal to 8 projects: Card (otherwise Table)
- The users choice will be "remembered"
  - Use the same method for remembering in the prod app (localstorage)

### Out of Scope
- Table functionality such as adding a new project, deleting a project

**Comment by boshevski** [comment]
I added the  table view and the toggle, plus remember the toggle choice in local storage.
