### ISSUE TITLE
Remove reference to limits in upgrade banner

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6040]
### Summary
We don't want to dissuade customers from upgrading and using Storj by implying that there is a ceiling to what they can store and egress with Storj. Therefore, we should update the upgrade banner to remove wording of limits.

### Acceptance Criteria
- Upgrade banner should read:
  > Ready to upgrade? Increase your limits and only pay for what you use - no minimum. {free amount}GB free still included. Upgrade Now

### Screenshot of current state
![image](https://github.com/storj/storj/assets/7063002/c21d67a0-e1b0-4d3f-8333-9f162cf805f1)

**Comment by mobyvb** [comment]
v1.85 https://github.com/storj/storj/commit/ae5e742a121cfefedce152b566001b893b45418d
