### ISSUE TITLE
SNO: Incorrect accounting of total disc space

### ISSUE THREAD

**Issue by Quake4** [storj/storj#6041]
Was:

**Description**
~~The used space is incorrectly taken into account. Approximately 100 gigabytes are lost.~~

**Screenshots**
![image](https://github.com/storj/storj/assets/29517243/79b06a14-e7ae-4212-88a3-819f6f14b1c2)

**Describe the results you expected:**
~~1.04 Tb or 1.05 Tb~~

**Describe the results you received:**
~~0.95 Tb~~

**Your environment**
- SNO: v1.80.10
- Operating system and version: Windows 10

**Comment by Quake4** [comment]
In general, it sucks with total disk space

trash:
![image](https://github.com/storj/storj/assets/29517243/673a4cc9-b1df-45a4-ac4a-972aca9132ce)


![image](https://github.com/storj/storj/assets/29517243/5bac2334-184e-490c-a557-71366a7bb546)
It turns out 0.95 is similar to the truth, and 1.05 is wrong.

blobs:
![image](https://github.com/storj/storj/assets/29517243/7ba66df7-20ac-4fa8-896d-ddea0601a6ac)

**Comment by Quake4** [comment]
**Description**
The Total disk space is incorrectly taken into account.

**Screenshots**
![image](https://github.com/storj/storj/assets/29517243/79b06a14-e7ae-4212-88a3-819f6f14b1c2)

**Describe the results you expected:**
0.95 TB

**Describe the results you received:**
1.05 TB

**Your environment**
- SNO: v1.80.10
- Operating system and version: Windows 10

**Comment by profclems** [comment]
@Quake4 what was the value of the used space on any day before the drop?

**Comment by Quake4** [comment]
I do not remember

**Comment by profclems** [comment]
> I do not remember

Oh sorry, I meant on the graph

**Comment by Quake4** [comment]
1.35, 1.35, 1.35, 1.32, 1.37, 1.33, 1.36, 1.36, 1.38, 1.34, 1.07, 0.95, 0,93

**Comment by profclems** [comment]
Thank you.

This can be associated to deleted pieces which have not been garbage collected yet

**Comment by Quake4** [comment]
How long can it take?

**Comment by littleskunk** [comment]
It will take about a week.

**Comment by Quake4** [comment]
The used space is shown incorrectly, what does cleaning the trash have to do with it?

**Comment by Quake4** [comment]
showed 1.06:
![image](https://github.com/storj/storj/assets/29517243/f766a719-7abf-467b-b361-875dcc1f7156)

on disk 0,959:
![image](https://github.com/storj/storj/assets/29517243/55c5dfc5-fc7e-4701-95a3-af80cd41ec0e)

**Comment by Quake4** [comment]
is sno account total space used with cluster waste?

**Comment by littleskunk** [comment]
The output is correct. A lot of data has been deleted. See https://forum.storj.io/t/announcement-storj-to-shut-down-europe-north-1-and-us2/22956 for more details.

Now the graph is showing the satellite point of view. Data was deleted = You get paid for less data.
Your storage node doesn't know which data has been deleted and will get that information with the next garbage collection run. So for the meantime used space on disk and paid space reported by satellites will differ.

**Comment by Quake4** [comment]
total: blobs + garbage + temp+ trash:
![image](https://github.com/storj/storj/assets/29517243/186d012b-4024-4456-8010-ed381b2b8772)

`config:`
```
# total allocated disk space in bytes
storage.allocated-disk-space: 1.8 TB
```
1.8 * 1 000 000 000 / 1024 / 1024/ 1024 = 1,67 TB

FREE SPACE MUST BEE ABOVE 100Gb - AROUND 130 Gb

**Comment by Quake4** [comment]
Incorrectly calculates data.

**Comment by Quake4** [comment]
Satellite is show 0.95, on disk 0.96. SNO board show 1.06.
What does the link have to do with it, about deletion?

**Comment by littleskunk** [comment]
I can repeat it once more if you like. A lot of data has been deleted. Your node doesn't know about that until next garbage collection run. In the meantime the used space reported by the satellite will be lower than the used space on your disk.

**Comment by Quake4** [comment]
on disk 0.96. SNO board show 1.06 
They have already been deleted.

**Comment by profclems** [comment]
> Satellite is show 0.95, on disk 0.96. SNO board show 1.06. What does the link have to do with it, about deletion?

The values on the graph are approximate values and that’s correct enough in your case (not much difference). The satellite returns the value in bytes*hour and the node tries to convert to bytes.

**Comment by littleskunk** [comment]
That is not how garbage collection works. Garbage collection will delete about 90% of the deleted data. On the next run it will delete 90% of the missing 10% and so on.
