### ISSUE TITLE
Revamp Graceful Exit

### ISSUE THREAD

**Issue by thepaul** [storj/storj#6042]
**Description**

Currently, graceful exit is a complicated subsystem that keeps a queue of all pieces expected to be on a node, and asks the node to transfer those pieces to other nodes one by one. The complexity of the system has, unfortunately, led to numerous bugs and unexpected behaviors.

We have decided to remove this entire subsystem and restructure graceful exit as follows:

1. Nodes will signal their intent to exit gracefully
2. The satellite not send any new pieces to gracefully exiting nodes
3. Pieces on gracefully exiting nodes will be considered by the repair subsystem as "retrievable but unhealthy", similar to the way out-of-placement pieces are currently treated. They will be repaired off of the exiting node as needed.
4. After one month (with an appropriately high online score), the node will be considered exited, and held amounts for the node will be released. The repair worker will continue to fetch pieces from the node as long as the node stays online.

**Acceptance Criteria**

1. A transition plan is created that will allow a clean live upgrade of satellites, handling nodes that are already gracefully exiting appropriately
2. Node software is updated so it informs the satellite of its intention to graceful exit however appropriate, and it no longer tries to use the piece processing loop
3. Satellite software is updated so it tracks gracefully exiting nodes appropriately, and does not use the piece processing loop
4. (Once transition is complete) remaining old graceful exit code is removed from codebase.

**Comment by thepaul** [comment]
Plan for already-exiting nodes, or nodes with old software that initiate graceful exit after the satellite has been upgraded:

* Nodes calling `(*DRPCSatelliteGracefulExitClient).Process()` will always receive one of the following from the satellite:
    * `rpcstatus.FailedPrecondition`, if they are not yet eligible to call graceful exit.
    * `*pb.SatelliteMessage_ExitFailed`, if they have been offline too much since starting graceful exit.
    * `*pb.SatelliteMessage_ExitCompleted`, if the graceful exit time period has elapsed.
    * `*pb.SatelliteMessage_NotReady`, otherwise.
* Each of those messages should be handled correctly with the existing node software. The main difference is that nodes will no longer receive any `*pb.SatelliteMessage_TransferPiece` or `*pb.SatelliteMessage_DeletePiece` messages.
* The new version of the node software will work the same as the old one, except without any need to handle TransferPiece or DeletePiece instructions, and with a 4-hour loop retry time instead of 1-minute.

**Comment by thepaul** [comment]
Plan for DB and for coexisting with processes running older version of satellite software:

* Nodes table: will use `exit_initiated_at`, `exit_finished_at`, and `exit_success` with essentially the same meanings they had before.
* We will ignore `exit_loop_completed_at` and avoid using it. We can drop `exit_loop_completed_at` with the next version.
* Will stop using `graceful_exit_progress` table entirely. Can drop table after all satellite processes are updated.
* Will stop using `graceful_exit_segment_transfer_queue` table entirely. Can drop table after all satellite processes are updated.

**Comment by shaupt131** [comment]
https://review.dev.storj.io/c/storj/storj/+/10875

**Comment by shaupt131** [comment]
@thepaul what are our next steps or blockers here?

**Comment by thepaul** [comment]
I have one test flaking out that needs to be fixed, one test that I don't know how it's supposed to work, and then I will just need reviews.

**Comment by ihaid** [comment]
I added [PR](https://github.com/storj/storj/pull/6355) with test plan for this. @thepaul could you please take a look on it to check if we cover everything?
