### ISSUE TITLE
New `pending_objects` table definition

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#6045]
Define and implement new `pending_objects` metabase table. Initial design can look like this
```sql
CREATE TABLE pending_objects (
	project_id   BYTEA NOT NULL,
	bucket_name  BYTEA NOT NULL,
	object_key   BYTEA NOT NULL,
	stream_id    BYTEA NOT NULL,

	created_at TIMESTAMPTZ NOT NULL default now(),
	expires_at TIMESTAMPTZ,

	encrypted_metadata_nonce         BYTEA default NULL,
	encrypted_metadata               BYTEA default NULL,
	encrypted_metadata_encrypted_key BYTEA default NULL,

	encryption INT8 NOT NULL default 0,

	zombie_deletion_deadline TIMESTAMPTZ default now() + '1 day',

	PRIMARY KEY (project_id, bucket_name, object_key, stream_id)
);

```
but it needs to be discussed with more people and get some acceptance.

Acceptance Criteria:
* define and discuss new table definition
* implement source migration add final version of the table (migrations folder)

**Comment by iglesiasbrandon** [comment]
@egonelbre for visibility ^

**Comment by shaupt131** [comment]
Please also include someone from the @storj/edge-team when you push this for review.
