### ISSUE TITLE
Create a guide for node operators "how to forget a satellite"

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6068]
## Background:

As part of https://github.com/storj/storj/issues/5984, we need to create a how-to guide for storage node operators to remove a satellite from their node.  This will be accomplished by having by having the SNO's manually delete the `trust-cache.json` which would mostly be in the config directory specified by `--config-dir`, delete the satellites data from the `reputation.db` and `satellites.db` databases and the blobs folder. The trust cache will be regenerated on restart.

## Acceptance Criteria:

- Write a tool that SNOs can run to forget satellite
- A clear set of instructions on how to remove a satellite from your node
- Instructions reviewed/approved and added to docs.storj.io
- A form post with a link to the document.

**Comment by profclems** [comment]
JG posted on [slack](https://storj.slack.com/archives/CKTAXNND7/p1691091114232219) that there is 

> a project in flight to migrate from Archbee to a new documentation platform that will be easier to manage update workflows via GitHub. Please hold off on any further major changes to Archbee (typos and minor edits are ok).

I will hold off adding the docs to docs.storj.io and only make the forum post once the PR which adds the subcommand is merged.

**Comment by iglesiasbrandon** [comment]
@profclems can you add a link to a google doc with the guide so that we can post it in the forum and then add it to our docs site later on after the migration is finished. this ticket should be blocked by the doc site migration

**Comment by profclems** [comment]
https://docs.google.com/document/d/1_rHAkAIFvsquC2KlatYCky1iKIogLFZyWv4kmLCpZks/edit?usp=sharing

**Comment by shaupt131** [comment]
@profclems It looks like the new docs site is live.  Dan provides a tutorial of sorts here: https://storj.slack.com/archives/CKTAXNND7/p1692978971520809.  Can you look into adding your instructions to new site?  Also, does anyone know if it's been posted to the forums yet?

**Comment by shaupt131** [comment]
What are our next steps here?

**Comment by profclems** [comment]
@shaupt131 The change https://review.dev.storj.io/c/storj/storj/+/10876 has not been merged yet. One feedback from Marton needs to be addressed and involves some e2e tests, and then I will need more reviews to complete it as quickly as possible. It looks like SNOs are getting impatient. 

Regarding the docs, it will entirely be based on the new `forget-satellite` subcommand because we realized it will require a lot of work to do it manually and might be almost impossible to get the data properly cleaned up.

**Comment by profclems** [comment]
> Also, does anyone know if it's been posted to the forums yet?

No, it has not been posted yet since it'll entirely be based on the new subcommand.

**Comment by profclems** [comment]
Announce is now posted on the forum https://forum.storj.io/t/how-to-forget-untrusted-satellites/23821?u=clement

**Comment by iglesiasbrandon** [comment]
We made the announcement, but the change in the storage node software that actually includes the command has not been rolled out yet. It's going to be included in https://github.com/storj/storj/releases/tag/v1.88.2, which we plan to start rolling out next week.
