### ISSUE TITLE
Merge settled/allocated lines on bandwidth graph

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6072]
There is a lot of confusion about what "settled" vs. "allocated" means, and we decided in the design sync meeting that it would be more straightforward to show a single line to the user on their egress graph, with a disclaimer that the most recent data points may change as traffic moves from "allocated" to "settled"

## Acceptance
- Egress chart only shows Allocated (which includes Settled)
- Chart just says Egress Usage (and Egress in the label) -- note the design says "Download" but we should use "Egress"

**Comment by boshevski** [comment]
Only show one line, and one label. Then show information in the tooltip.

![Image](https://github.com/storj/storj/assets/3217669/49ec48c4-a0b6-49bf-9052-71489325b612)
