### ISSUE TITLE
Mistaken storage node garbage collection alerting

### ISSUE THREAD

**Issue by jtolio** [storj/storj#6073]
Context: In a conversation in arch review, we discovered we have a bit of a problem. 

Imagine the following scenario:
 * We have a mistaken garbage collection. A storage node moves a piece we want into the trash.
 * We do an audit on that piece and the storage node says "I don't have that piece."
 * The Satellite will update its own tracking to say "stop pestering that node about that piece, it doesn't have it".
 * Let's say we discover that the garbage collection was a mistake, so we run restore from trash
 * The node now has the piece again, but it doesn't matter, since we deleted the metadata about that piece.

What should we do about this? Here is how we decided to fix it. We have three steps:

 * If a node can't find a piece it is asked for, it should look for it in the trash. If it's in the trash, it should first restore it out of the trash and then do the request as expected.
 * When it responds to the request, it should include a new flag indicating whether the piece was found in the trash.
 * The Satellite should track if this "found in trash" flag is ever true, and we should set up alerts for if the flag is true. We should use logs or eventkit that include the node id, so we can track if a sudden rash of "found in trash" responses is just one single node (something is broken with that one node) or if it's a network-wide issue. We should get slack notices if this happens.

This resolves our issue without making other things more complicated. In the case that the piece is really lost and not in the garbage, restoring from trash wouldn't have helped anyway.

This discussion occurred in the 2023-07-13 Arch review

**Comment by iglesiasbrandon** [comment]
this ticket will be done after #6145 and #6146 are done
