### ISSUE TITLE
Improve upload progress bar for large files

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6075]
When uploading large files that are split into multiple parts being uploaded in parallel, the upload bar in the hover component does not display an accurate state of the overall upload.

More details needed

AC:
* the upload bar in the hover component displays an accurate state of the overall upload for large (>1GB) objects

**Comment by VitaliiShpital** [comment]
I think this issue was introduced when we switched to a different part sizes for uploads. So I guess it is not relevant anymore because we are back to 64MB for uploads

**Comment by ferristocrat** [comment]
Closing - see vitalii's comment above
