### ISSUE TITLE
Satellite UI: object count may be inaccurate after deleting files

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6080]
Reported reproduction steps:
* Some objects were uploaded in the bucket, and they were all deleted
* 9 new objects were uploaded
* `uplink ls -o json -r --encrypted sj://releases/ | wc -l` shows `9`
* web UI shows 17 total objects in the bucket, even though there are only 9 (screenshot 1)
* web UI shows "you have at least 8 objects locked with a different passphrase", because it is only listing the 9 files in the bucket
* only one passphrase has been used the entire time
* the issue eventually disappeared, indicating that there is some delay between deletion the object browser list count.

Basically, the object browser is including deleted objects shortly after deletion. Can we investigate why and fix any bugs?

Screenshot 1:

![Image](https://user-images.githubusercontent.com/1323312/255647061-49e3a4ec-e6e8-46d0-9f28-f5ee7915fee1.png)

Screenshot 2: 

![Image](https://user-images.githubusercontent.com/1323312/255647184-1a4af4de-20d4-4579-a265-d6634f7002a7.png)

AC:
* the object count used in the file browser does not include files that were recently deleted 
* if you are unable to improve the responsiveness of the UI after deletes, determine the maximum delay that would be expected in production between a delete and updated UI, and comment on this ticket with the delay, and the reason it cannot be improved easily

[Context in Slack](https://storj.slack.com/archives/C019JQJ4LTV/p1689046476667349)

**Comment by VitaliiShpital** [comment]
https://storj.slack.com/archives/CG5A95JBC/p1696422440343339?thread_ts=1696312633.056329&cid=CG5A95JBC

**Comment by mobyvb** [comment]
we discussed with edge team about adding an endpoint on edge services to get the object count
maybe console team could implement this endpoint, as long as Edge says it's a good idea

**Comment by mobyvb** [comment]
related to https://github.com/storj/gateway-mt/issues/373

**Comment by ferristocrat** [comment]
Few options we need to evaluate:

1. Implement a custom endpoint: https://github.com/storj/edge/issues/373
2. Remove the "objects are locked" banner
3. Update the "objects are locked" banner to be more clear as to why the user is seeing the message (objects could be locked, a recent delete that hasn't been reflected yet on satellite, etc)
