### ISSUE TITLE
Fix internal db errors that are making it out through public API

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6081]
### Background: 
It was reported in https://storj.slack.com/archives/CTLAYRPQB/p1690240513514939 that we have internal crdb errors that are making it out through the public API.  We need to resolve this.  

### Acceptance Criteria:

- Internal errors are no longer visible on the public API

**Comment by iglesiasbrandon** [comment]
Once we complete this item, we should notify @dominickmarino so that they can communicate our changes back to the customer.

**Comment by mniewrzal** [comment]
one example how to fix internal errors going out:
```
change:
	bucket, err := endpoint.buckets.GetMinimalBucket(ctx, req.GetName(), keyInfo.ProjectID)
	if err != nil {
		if buckets.ErrBucketNotFound.Has(err) {
			return nil, rpcstatus.Error(rpcstatus.NotFound, err.Error())
		}
		endpoint.log.Error("internal", zap.Error(err))
		return nil, rpcstatus.Error(rpcstatus.Internal, err.Error())
	}
into:
	bucket, err := endpoint.buckets.GetMinimalBucket(ctx, req.GetName(), keyInfo.ProjectID)
	if err != nil {
		if buckets.ErrBucketNotFound.Has(err) {
			return nil, rpcstatus.Error(rpcstatus.NotFound, err.Error())
		}
		endpoint.log.Error("internal", zap.Error(err))
		return nil, rpcstatus.Error(rpcstatus.Internal, "unable to get bucket metadata")
	}

```

**Comment by shaupt131** [comment]
@dominickmarino Just FYI this issue is completed.  I've moved it to retest on the security board, but unsure if there is anything here for you to actually retest. Just close if not :)
