### ISSUE TITLE
Vuetify app: Implement user error notifications

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6087]
Use the component(s) related to notification banners from https://github.com/storj/vuetify-storj in the storj/storj vuetify app

![Image](https://user-images.githubusercontent.com/1323312/256253128-ebfc747b-9124-4401-8004-ec4df36f8500.png)

AC:
* in the vuetify app, when a call is made to the notifications store, e.g. `notify.error(error.message, null);`, display a visual error notification to the user
* Ensure that the notificator is called whenever a user-facing error occurs in the code, otherwise errors will be "swallowed up" and invisible to the end user
* try to use the existing notificator plugin from the production app

**Comment by ferristocrat** [comment]
I see a few different notifications in the current Satellite UI. @boshevski can you advise on what to do with each?

I see vuetify has https://vuetifyjs.com/en/components/snackbars/ that looks similar to the first screenshot.

![image](https://github.com/storj/storj/assets/7063002/e22c0886-2ead-42d5-9723-ebb48eac7dda)
![image](https://github.com/storj/storj/assets/7063002/85f0c193-bd95-4e48-aeaf-c45995ec347b)
![image](https://github.com/storj/storj/assets/7063002/97e48edd-0ba9-4d47-986f-19ab3692302a)
