### ISSUE TITLE
Vuetify Buckets page: view bucket details

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6115]
###Existing Design

https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=12444%3A77581&mode=design&t=vSaVrv1jtAXnMPU0-1

###Acceptance
- User can see bucket details
  - Name
  - Date Created
  - Last Updated
  - Object Count
  - Users (if this is part of production today)

### Production Today:
![image](https://github.com/storj/storj/assets/7063002/ecb14718-8a9c-47ee-be95-2a755bf67d19)

**Comment by boshevski** [comment]
New bucket details design as a dialog. [Figma](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=26261-14963&mode=design&t=514Ag8qGkcCuKWtY-0)
