### ISSUE TITLE
Satellite UI / Login Signup region selection shows the current satellite twice

### ISSUE THREAD

**Issue by boshevski** [storj/storj#6121]
Remove the duplicated satellite.

![Image](https://user-images.githubusercontent.com/3217669/256607777-ab23e5a2-97f2-4dab-98a7-efdd9b3f3a84.png)
![Image](https://user-images.githubusercontent.com/3217669/256607778-3e69ff0f-5a37-4830-9f1e-e02e8dfbc738.png)

**Comment by mobyvb** [comment]
v1.87 https://github.com/storj/storj/commit/614d213432f878c184c04af447c5228d6b41ed09
