### ISSUE TITLE
Verify all analytics events in Vuetify app

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6123]
### Acceptance
- verify all existing client side analytics events from the production app are in the new vuetify app

**Comment by ferristocrat** [comment]
Dependent on https://github.com/storj/storj/issues/6122

**Comment by mobyvb** [comment]
[Spreadsheet with list of analytics events we need to ensure we have in Vuetify](https://docs.google.com/spreadsheets/d/1QHeH4J2NIp_qZQygtOjsTNBoJcMxhyuVGCXfzgrNkP8/edit#gid=0)
