### ISSUE TITLE
Support configuration of default placement rules

### ISSUE THREAD

**Issue by elek** [storj/storj#6126]
There are cases where we would like to apply placement rules by default for all the placements (except a few of them):

Use case 1: certified dedicated nodes.
 * One node provider might be certified with node tags. By default, they shouldn't be chosen, only if the given placement rule is used.

Use case 2: optional net24 rule
 * Apply net24 node selection rule (pick only one node from each /24 subnet) only for selected placement rules (for example, when dedicated nodes are not used)

**Comment by elek** [comment]
cc @kristaxox, we chat about this one, yesterday...

**Comment by iglesiasbrandon** [comment]
https://review.dev.storj.io/c/storj/storj/+/10854
https://review.dev.storj.io/c/storj/storj/+/10879
https://review.dev.storj.io/c/storj/storj/+/10878

**Comment by kristaxox** [comment]
cc @shaupt131 PRs for default node placements

**Comment by shaupt131** [comment]
@elek Please make this your top priority when you return on Monday.  We are aiming to have this merged by Monday afternoon so that we can do some testing and a point release on Tuesday.

**Comment by elek** [comment]
Found during the tests:

https://review.dev.storj.io/c/storj/private/+/10985

I think it's more safe to fix...

**Comment by shaupt131** [comment]
Everything here should be deployed as of today.  Closing this issue.
