### ISSUE TITLE
Design for enabling/disabling object versioning

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6127]
### Background:
One of the things that we identified that could be done in parallel to the [object versioning prerequisite work](https://github.com/storj/storj/milestone/46) is a way to manage object versioning for projects/buckets.  Having this done early will also enable us to perform better testing throughout the project.  

### Acceptance Criteria:

- Support the S3 API for enabling or disabling it
- Only impact version-based operations and replacing existing objects
- Store the information in the bucket-level metadata
   - Done in a way that would support other potential S3 bucket-level config options in the future
- Ability to use this feature internally to enable features (flags) bucket-by-bucket to minimize risk or test performance 
- Ability to also set project-wide defaults
- Additional ticket(s) for the implementation work of this design

**Comment by jenlij** [comment]
waiting for decision on 1 vs 2 table design.
