### ISSUE TITLE
storj/common: any chance to update github.com/quic-go/quic-go to 0.37.0 for Golang 1.21

### ISSUE THREAD

**Issue by eclipseo** [storj/storj#6128]
**Describe the feature or problem you'd like to solve**
We're package storj in Fedora to use with Rclone.

We are not bundling everything, but we are packaging each separate Golang library.

Currently we have an issue with storj/common as it depends on an old version of github.com/quic-go/quic-go [0.32.0](https://github.com/quic-go/quic-go/releases/tag/v0.32.0) but we'd like to use version [0.37.0](https://github.com/quic-go/quic-go/releases/tag/v0.37.0) as we have Golang 1.21 rc3 on Fedora Rawhide.

**Propose a Solution**
Can a kind soul update storj/common to use github.com/quic-go/quic-go to 0.37.0?

Thanks

**Comment by thepaul** [comment]
Unfortunately, 0.37.0 depends on Go 1.21 and no longer includes support for Go 1.19. Go 1.21 isn't quite released yet, and we have a requirement to support the latest two official Go releases.

When Go 1.21 is actually released (they say it'll be in August) we'll certainly be upgrading.

**Comment by thepaul** [comment]
We started using quic 0.37.4 as of commit 1f261bcc70f.
