### ISSUE TITLE
api/projects.delete() -> GraphQL to HTTP

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6133]
AC:

- create corresponding http handler in web/satellite/console/consoleweb/consoleapi to accomplish the equivalent behavior of the GQL endpoint
- switch the frontend to use the new http endpoint rather than the graphql handler
- don't worry about removing the GraphQL backend handling in this task

**Comment by jewharton** [comment]
Closing because this endpoint is unused and nonfunctional. We currently do not support deleting projects from within the satellite UI.
