### ISSUE TITLE
Storage Nodes should reject clients who send them data too slowly

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#614]
---
👋 Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! 😄
---

When a Client is sending data to a Storage Node very slowly they actually might be attacking that Storage Node. This is a denial of service attack called 'SlowLoris'. A Slowloris attack tries to keep as many connections open as possible for as long as possible so that the person being attacked runs out of available open connections.  

Storage nodes must be able to defend against clients who are attempting to Slowloris attack them but closing connections with those clients automatically.

https://en.wikipedia.org/wiki/Slowloris_(computer_security)

**Comment by cpustejovsky** [comment]
Will be looking into this issue this month :+1:

**Comment by manesioz** [comment]
Hey, any updates on this?
