### ISSUE TITLE
Notify the satellite if a node responds with a piece from its trash

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6146]
## Description

If a node responds to the request with the piece it found in the trash, it should include a new flag indicating whether the piece was found in the trash.

2 of 3 - Related to https://github.com/storj/storj/issues/6073

## Acceptance Criteria
- The node MUST specify if the piece was restored from the trash (protocol buffer response)
- Add it to event kit

**Comment by shaupt131** [comment]
@iglesiasbrandon let's discuss this during sprint planning

**Comment by shaupt131** [comment]
It looks like this is not fully deployed yet, is that correct @profclems ?

**Comment by iglesiasbrandon** [comment]
hey @profclems @shaupt131 it looks like this has been deployed. i am going to close this issue.
