### ISSUE TITLE
Auto-renew session

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6147]
### Summary

Need to implement session refresh/expiration for Vuetify app.

### Acceptance Criteria
- User should be prompted when their session is ending due to inactivity so that they can refresh their session:
  - If the user doesn't refresh the session, the user should be logged out
    - The user should be presented a dialog informing them that they have been logged out due to inactivity
  - If the user refreshes the session, it should be extended based on their user selected preferences

**Comment by NiaStorj** [comment]
@jewharton this needs effort points
