### ISSUE TITLE
S/Kademlia extensions - Secured routing table maintenance

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#615]
---
👋 Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! 😄
---

Implement the secure routing table maintenance S/Kademlia extension our Go library, changing nodes if possible and where appropriate

This ticket will require that we have signed and secure node-to-node communication, either via TLS with client certs or something else

* [http://www.spovnet.de/files/publications/SKademlia2007.pdf]

Acceptance Criteria:

1. Our Go Kad implementation is resistant to the attacks S/Kademlia mitigates

[https://storj-labs.mingle.thoughtworks.com/projects/team_rocket/cards/92]

**Comment by jtolds** [comment]
https://storj.io/blog/2019/08/so-youre-a-storage-node-operator.-which-satellites-do-you-trust/
