### ISSUE TITLE
Satellite UI: Improve wording of "total estimated charges" info

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6150]
See https://forum.storj.io/t/documentation-error/23390

### AC
* the wording in the attached image, on the billing -> overview page is improved to address the confusion in the linked forum post
  * Wording should be:
  * > This estimate includes all use before subtracting any discounts. Pro accounts will only be charged for usage above the free tier limits, and free accounts will not be charged.

![Image](https://user-images.githubusercontent.com/1323312/257641275-fd6733a9-318b-4c43-a57b-db63b38d21cd.png)

**Comment by ferristocrat** [comment]
@VitaliiShpital @mobyvb - updated the wording based on conversation in Slack. Added to AC above.

**Comment by mobyvb** [comment]
v1.87 https://github.com/storj/storj/commit/5abed63f5370586fb59e5220d050e1997ee5eb25
