### ISSUE TITLE
Access creation design updates

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6169]
In the access creation flow we want to consider the following:

What will remain the same:

1. User doesn't have a project level passphrase stored locally
2. Click Access > New Access
3. Enter a name and select "Access Grant" and press "Next"
4. Choose permissions and click next<br />

| Current State | New flow to consider |
| --- | --- |
| ~~5.  Select the radio button for entering a project passphrase and click "Next"~~<br /> ~~6.  Enter your passphrase~~  |  _5.  Select the radio button for entering a project passphrase and enter passphrase in the same section_ |
| ![Image](https://github.com/storj/storj/assets/7063002/9841988b-843b-4e95-bb52-767a2420a26e) | ![Image](https://github.com/storj/storj/assets/7063002/095195d9-b1b0-41b1-a286-042ba3449d35) |

**Comment by boshevski** [comment]
[Figma design](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=26259-10219&mode=design&t=514Ag8qGkcCuKWtY-0)
