### ISSUE TITLE
Test server side copy on object with 10k segments

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#6175]
We would like to test in production server side copy operation for object with 10k segments. 10k segments its current limitation we have for SSC. To make this test easier we can configure/modify uplink to create smaller segments e.g. 0.5MiB instead 64MiB.

**Comment by mniewrzal** [comment]
I was able to do server side copy with current maximum segment size (10k, 5MiB segment size). What I did:
* run test program to upload exactly 10k segments https://gist.github.com/mniewrzal/274123be8860abdde3e733697ecd88da
* double check with Redash that uploaded object have exactly 10k segments
* run uplink CLI copy command
```
wywrzal@wywex:~/git/storj/storj/cmd/ssc-test$ time uplink cp sj://michal-test/ssc-test/10k-segments sj://michal-test/ssc-test/10k-segments-copy
upload sj://michal-test/ssc-test/10k-segments to sj://michal-test/ssc-test/10k-segments-copy

real	0m19,829s
user	0m0,073s
sys	0m0,030s
```

To try with object with higher number of segments we would need to change limits that are currently hardcoded on satellite side.

cc @onionjake @littleskunk

**Comment by shaupt131** [comment]
@onionjake Can we call this issue resolved, or should we try to push it beyond 10k segments to see what happens?  See @mniewrzal's note above about how it will require hardcoded changes.

**Comment by shaupt131** [comment]
Original conversation: https://storj.slack.com/archives/C047KSGPPQ8/p1691690857034499

**Comment by onionjake** [comment]
In S3 they allow file sizes up to 5TB. With 10k segments optimally uploaded that would be 640 gigabytes.

If we are OK with that limitation we should document it in the limits section of the documentation? Does this limit not exist otherwise if customers don't use SSC?

**Comment by mniewrzal** [comment]
> In S3 they allow file sizes up to 5TB. With 10k segments optimally uploaded that would be 640 gigabytes.

Isn't 5TB a general limit for storing single object? not related to SSC? We don't have official limit for max object uploaded. In theory we should be able to go above 5TB without SSC (or UploadPartCopy) but I don't think we even tested this 5TB.

> If we are OK with that limitation we should document it in the limits section of the documentation? Does this limit not exist otherwise if customers don't use SSC?

I agree we need to document this limitation but I guess we will be OK with this limit until important customer will have problem with it :)
