### ISSUE TITLE
S/Kademlia extensions - disjoint path lookup

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#618]
---
👋 Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! 😄
---

Implement the disjoint path lookup S/Kademlia extension our Go library, changing nodes if possible and where appropriate
http://www.spovnet.de/files/publications/SKademlia2007.pdf

Acceptance Criteria:
1. Our Go Kad implementation is resistant to the attacks S/Kademlia mitigates

**Comment by BlackDuck888** [comment]
Link is not working for me

**Comment by jtolds** [comment]
https://storj.io/blog/2019/08/so-youre-a-storage-node-operator.-which-satellites-do-you-trust/
