### ISSUE TITLE
api/projects.create -> GraphQL to HTTP

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#6195]
AC:

create corresponding http handler in web/satellite/console/consoleweb/consoleapi to accomplish the equivalent behavior of the GQL endpoint
switch the frontend to use the new http endpoint rather than the graphql handler
don't worry about removing the GraphQL backend handling in this task

**Comment by mobyvb** [comment]
v1.87 https://github.com/storj/storj/commit/9cf9721abe7f652ab94fc0af7f9cb9ced8a39ebb
