### ISSUE TITLE
Write instructions for using duplicity backup with Storj

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#620]
---
:wave: Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! :smile:
---

Job Story: When I need to use Duplicity to encrypt and store my backups I want a simple step by step guide on how to set it up with the Storj Network so that I can start storing my Duplicity backups on a decentralized network.

These instructions should include how to set up the Storj S3 gateway. 

More information about duplicity can be found here: http://duplicity.nongnu.org/

This is a great example of the kind of instructions we are looking for: https://icicimov.github.io/blog/devops/Duplicity-encrypted-backups-to-Amazon-S3/

**Comment by cpustejovsky** [comment]
Will be looking into this issue this month :+1:

**Comment by arno01** [comment]
> These instructions should include how to set up the Storj S3 gateway.

The S3 gateway is not working in smaller environments with low RAM.
I've tried running storj S3 gateway v0.30.5, and have used aws s3 cp for getting the file of 128MiB size from it. The gateway gets killed shortly:

```
[Sun Jan 26 12:46:21 2020] Out of memory: Kill process 6933 (gateway_linux_a) score 505 or sacrifice child
[Sun Jan 26 12:46:21 2020] Killed process 6933 (gateway_linux_a) total-vm:685200kB, anon-rss:524600kB, file-rss:0kB, shmem-rss:0kB
[Sun Jan 26 12:46:21 2020] oom_reaper: reaped process 6933 (gateway_linux_a), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```

I have 600 MiB RAM free:

```
# free -mh
              total        used        free      shared  buff/cache   available
Mem:           985M        229M        588M        880K        166M        618M
Swap:            0B          0B          0B
```

The best would be to add Storj backend support directly to the duplicity tool.

**Comment by stefanbenten** [comment]
@arno01 As the ETAG Handling now is fixed, do you want to give this another try?
We also have a integration test that might be a good starter here:
https://github.com/storj/gateway/testsuite/integration/aws-cli/duplicity.sh

**Comment by arno01** [comment]
> @arno01 As the ETAG Handling now is fixed, do you want to give this another try?
> We also have a integration test that might be a good starter here:
> https://github.com/storj/gateway/testsuite/integration/aws-cli/duplicity.sh

Confirming, the recent storj gateway (v1.1.3) does not have the ETag issue anymore.
Thank you!

**Comment by RishmithaRaheem** [comment]
If you have any questions about how to get started or want to discuss further, add a comment.
 
 Can somebody send me a document or a youtube video that will get me started on working on this ticket (setup project in local etc.,) ? Im very new to open source contribution hence need some mentorship to start off!

**Comment by iglesiasbrandon** [comment]
This issue is stale and not currently relevant at this point. 
We are going to close this issue until it becomes relevant again.
