### ISSUE TITLE
Verify current functionality of API Generator

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6203]
### Background:

- General investigation into the API generator to understand it's functionality and any missing functionality that we may need for the admin UI API.  

### Acceptance Criteria:

- Identify any gaps in functionality
- Create follow-up tickets to implement any missing features/functionality

**Comment by ifraixedes** [comment]
For now, I only see one thing missing and I created an issue for it.
We may find more when we start to define the API and start using the auto-generated code, hence, we'll create new issues at that time.

**Comment by shaupt131** [comment]
@ifraixedes do you have a link to the new ticket you reference above?

**Comment by ifraixedes** [comment]
Yes, it's https://github.com/storj/storj/issues/6243

I thought that the message posted by Github just above my last comment was enough. I'm sorry :pray:
