### ISSUE TITLE
Fail satellite startup if placement config is invalid

### ISSUE THREAD

**Issue by elek** [storj/storj#6211]
Easy to make a mistake and problems are reported only on INFO level.

Broader scope is discussed on archreview: we can improve the error handling of configuration loading...

**Comment by shaupt131** [comment]
@elek how can I tell if this is deployed?

**Comment by elek** [comment]
Ok, probably an easier way. Check which private version is used in storj/storj:

https://github.com/storj/storj/blob/main/go.mod

Or even better, check this from the latest release:

https://github.com/storj/storj/blob/v1.91.2/go.mod

The important line is `storj.io/private v0.0.0-20230912093002-ca2d4ab44679`

This means that we have everything from private, which is merged before 2023-09-12 09:30...

Compare it with the merge line in the patch:

![image](https://github.com/storj/storj/assets/170549/47a9bfd4-3dc1-4d5b-a5a9-9dc6dff19556)


--> it's earlier, so it's deployed

**Comment by shaupt131** [comment]
Oh cool!  That's gonna be super helpful.  Thanks.
