### ISSUE TITLE
Satellite UI / Update sharing dialogs

### ISSUE THREAD

**Issue by boshevski** [storj/storj#6213]
[Figma designs](https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=26375-3527&mode=design&t=WpVAiIxTycU6wYan-0)

Updates to sharing dialogs:

1. Add notification explaining that the share will be public to anyone with the link.
2. Remove the cancel button as it may be interpreted as cancelling or revoking the shared access.
3. Make the copy link full width block button.

**Comment by mobyvb** [comment]
v1.87 https://github.com/storj/storj/commit/d6e0987dd9585f053628205355675c0e712284d8
