### ISSUE TITLE
Satellite UI / Bug / Saving changed storage limits shows error notification "Authorization required" and logs out users

### ISSUE THREAD

**Issue by boshevski** [storj/storj#6214]
Saving changed storage limits shows error notification "Authorization required" and logs out users

![Image](https://user-images.githubusercontent.com/3217669/263090419-a7764e0c-7cb6-4b63-9f68-ea2e7b9e3512.png)

**Comment by mobyvb** [comment]
v1.87 https://github.com/storj/storj/commit/4964ca5ffbe83f187f256c571635c937bfc0308b
