### ISSUE TITLE
Implement private uplink method for Enabling/Disabling versioning on a bucket

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6223]
### Description:
The purpose of this ticket is to implement the private uplink method for Enabling/Disabling versioning on a bucket.

This is an example/ starting point: 
https://github.com/storj/uplink/blob/358f7f956649c2c861d68b38a4382f45a8948f16/bucket.go#L111

### Acceptance Criteria: 
- The private uplink method for Enabling/Disabling versioning on a bucket is implemented.

**Comment by shaupt131** [comment]
This ticket is a duplicate to https://github.com/storj/storj/issues/6387.  We will track this work within https://github.com/storj/storj/issues/6387 and close this issue.
