### ISSUE TITLE
Implement private uplink method for put/get/delete object tags and object metadata with versions.

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6224]
### Description
- The purpose of this ticket is to implement the private uplink method for put/get/delete object tags and object metadata with versions.

### Acceptance Criteria
- the put/get/delete object tags and object metadata with versions method is implemented.

**Comment by shaupt131** [comment]
https://github.com/storj/storj/issues/6520 and https://github.com/storj/storj/issues/6521 are the replacement tickets for this issue.
