### ISSUE TITLE
[storagenode] Order service should archive unsent orders when the satellite is no longer trusted

### ISSUE THREAD

**Issue by profclems** [storj/storj#6262]

**Comment by shaupt131** [comment]
@profclems is this the only thing needing review for this?  Any other action items?

https://review.dev.storj.io/c/storj/storj/+/11300

**Comment by profclems** [comment]
@shaupt131  The PR only needs review and it's done

**Comment by shaupt131** [comment]
@profclems is there anything left to review here or are you all set?

**Comment by profclems** [comment]
I'm all set now. The PR will be merged any minute from now
