### ISSUE TITLE
Release-v1.88 Test Satellite UI Edge Service Override

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#6274]
[b671641](https://github.com/storj/storj/commit/b671641) satellite/console: update CSP to include [storjapi.io](http://storjapi.io/)
[c8f4f52](https://github.com/storj/storj/commit/c8f4f52) satellite/console: return edge URL overrides in project info responses
[4f86975](https://github.com/storj/storj/commit/4f86975) web/satellite: use edge service URL overrides

Required
- [x] File browser should register access grant on the correct edge service endpoint.
- [x] File browser should list, upload and download with the correct edge service endpoint.
- [ ] File browser should contact private linksharing URL for internal use like file preview.
- [x] File browser should contact public linksharing for any object, folder or bucket share links.
- [x] Object map contacts the correct edge service.
- [x] Access grant wizard should register on the correct edge service endpoint.

Nice to have
- [ ] Access grant wizard should generate a restriced API key that can be used in uplink CLI but still contacts the correct edge service endpoint.
- [ ] Try to register an access grant on the wrong edge service by setting the URL in uplink CLI. Edge services should reject that request with an error message.
- [ ] Try to use an access grant on the wrong edge service by contacting the wrong URL. Edge service should reject that request with an error message.

**Comment by littleskunk** [comment]
I had no luck with storj-up so far. Maybe I am missing some config change. History can be found here: https://github.com/storj/storj/issues/6188

**Comment by ihaid** [comment]
```
curl 'http://127.0.0.1:10005/api/projects/{projectID}/geofence?region=EU' \
  -X 'POST' \
  -H 'Accept: */*' \
  -H 'Accept-Language: q=0.9,en-US;q=0.8,en;q=0.7' \
  -H 'Connection: keep-alive' \
  -H 'Referer: http://127.0.0.1:10005/' \
  -H 'authorization: {very secret key}' \
  --compressed
```

**Comment by ihaid** [comment]
Generate a restriced API key and used in uplink to share:
`  uplink share  sj://del/new.txt --url --not-after=none
Sharing access to satellite 1GGZktUwmMKTwTWNcmGnFJ3n7rjE58QnNcRp98Y23MmbDnVoiU@satellite.qa.storj.io:7777
=========== ACCESS RESTRICTIONS ==========================================================
Download     : Allowed
Upload       : Disallowed
Lists        : Allowed
Deletes      : Disallowed
NotBefore    : No restriction
NotAfter     : No restriction
MaxObjectTTL : Not set
Paths        : sj://del/new.txt
=========== SERIALIZED ACCESS WITH THE ABOVE RESTRICTIONS TO SHARE WITH OTHERS ===========
Access       : 16s2NeXq1o18Y9wxNhGWii33JkAck6ieczPJz927yhc33WDaDvudLAA49qFQoW3q3G7agTkmUphfj4yiPWdCioaWKLDwbsxUEnG1FyF5mfbjW7gxMEAExSxERXPgV7CJH8CPgYRQ7ragdNKQhsJCj1oPqRuPDpgSUWqbQx2sZnVyqx4pS6Sfr1u9h28MmmDDQZHSJ3Ef7WEGNnemCF5XmKghWTD3gCjJngfXK6SngoXxjG3e6Y9SfvtdKDqAYaFhooizwihWkL6FW7ssDn2kZpwqEhehFrtVMt4CkBRTq2zYeYQmkRoRmp4BNEHuNDwvD31krFatQ5uoDYCZcHVifRFsM4b2q2coUE6PbrSWSXEeqRtiUkPSTWRhnL2YTfnwTok3pXt7PHP7XHKt35Px1qQXWy7Ce6gr7Rf1pzCKe8jczcRR5CVnDvcsbpyGJAak94a2UL1dB6LzE
uplink: register access for edge services failed: access grant: disallowed satellite: "1GGZktUwmMKTwTWNcmGnFJ3n7rjE58QnNcRp98Y23MmbDnVoiU@satellite.qa.storj.io:7777"
	storj.io/uplink/edge.(*Config).RegisterAccess:91
	main.RegisterAccess:243
	main.(*cmdShare).Execute:119
	main.(*external).Wrap:375
	github.com/zeebo/clingy.(*Environment).dispatchDesc:127
	github.com/zeebo/clingy.(*Environment).dispatch:59
	github.com/zeebo/clingy.(*Environment).dispatchDesc:66
	github.com/zeebo/clingy.Environment.Run:41
	main.main:35
	runtime.main:250`

**Comment by ihaid** [comment]
```
➜   aws s3 --endpoint=http://localhost:7777 mb s3://bucket-name
make_bucket failed: s3://bucket-name Could not connect to the endpoint URL: "http://localhost:7777/bucket-name"
➜   aws s3 --endpoint=https://ngb1-hz.stargate.staging.tardigradeshare.io mb s3://bucket-name
make_bucket: bucket-name
```
