### ISSUE TITLE
Create Testplan for Object Versioning

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#6275]
Slack channel "object-versioning"
Design documents can be found here: https://github.com/storj/qa-storj/issues/517

First Brainstorming:
Customer and storage node payments for a bucket with multiple versions of the same file
Server side copy and server side move across buckets with different version settings
1. To a bucket that has versioning enabled. Should add one version to it.
2. To a bucket that has version disabled. Should override existing version.

Create 3 versions of the same file and delete the middle one.
Create new bucket should inherrit version from project level. Same goes for creating a project inherrits from user level.
Admin UI should behave the same.
Suspend versioning on a bucket that had versioning enabled. 3 versions of a file exists. Try to upload the same file again. -> the newsest file gets overriden. The older 2 versions stay intact.
Can a project member with an restriced access grant modify the version flag on a bucket? Which permissions does the access grant need?
Does updating file metadata create a new version?
List old versions in order
Restore old version

Bonus:
Can a customer set a maximum number of versions?
Can a customer pin specific versions to make sure they can't be deleted by maleware?

**Comment by shaupt131** [comment]
One thing that might be good to add to the test plan: Make sure that the UI shows the latest version of each object.

**Comment by ihaid** [comment]
Good idea!
I created the test plan and going to merge it soon

**Comment by ihaid** [comment]
# Object Versioning

## Background

This testplan covers Object Versioning#6275
&nbsp;

| Test Scenario     | Test Case                               | Description                                                                                                                                                                                      | Comments                                                  |   
|-------------------|-----------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------|
| Copy              | To a bucket that has versioning enabled | Should add one version to it(make a new version and make in latest)                                                                                                                              | check the column "versioning_state" in  "bucket_metainfo" |  
|                   | To a bucket that has version disabled   | Make sure GE was not initiated for the disqualified node.                                                                                                                                        |                                                           |
|                   | Copy object                             | Should support copying a specific version, should copy the latest version of an object if not specified                                                                                          |                                                           |
| Move              | To a bucket that has versioning enabled | Should add one version to it                                                                                                                                                                     | check the column "versioning_state" in  "bucket_metainfo" | 
|                   | To a bucket that has version disabled   | Perform GE on node with less then 50% of score. Node should fail to GE                                                                                                                           |                                                           |
| Delete            | Delete one from many versions           | Create 3 versions of the same file and delete the middle one indicating the version id                                                                                                           |                                                           |
|                   | All versions                            | Unconditionally deletes all versions of an object                                                                                                                                                |                                                           |
|                   | Delete bucket                           | Force delete bucket with files that has versioning. We should keep all versions of the files unless manually deleted                                                                             |                                                           |
| Restore           | Delete and restore                      | Delete version of the file and restore from that version                                                                                                                                         |                                                           |
|                   | Restore                                 | Create few versions of the file and restore from latest to older version                                                                                                                         |                                                           |
| Create            | Create new bucket                       | Versioning should be inherited from project level                                                                                                                                                |                                                           |
| Suspend           | Suspend versioning                      | Suspend versioning on a bucket that had versioning enabled. 3 versions of a file exists. Try to upload the same file again. -> the newsest file gets overriden. The older 2 versions stay intact |                                                           |
| Update            | Update metadata                         | Metadata update should not create new version. Takes the version as input but does not use it. Only updates the metadata for the highest committed object version.                               |                                                           |
| List              | all versions                            | Unconditionally returns all object versions. Listing all versions should include delete markers                                                                                                  |                                                           |
| UI                | UI                                      | UI should always show the latest version of each object                                                                                                                                          |                                                           |
| Buckets           | Old                                     | Old buckets created before the feature should be in "unsupported" state                                                                                                                          |                                                           |

## Questions
* Can a customer set a maximum number of versions?
* Can a customer pin specific versions to make sure they can't be deleted by malware?
* Can a project member with an restricted access grant modify the version flag on a bucket? Which permissions does the access grant need?

**Comment by NiaStorj** [comment]
Can we add S3 test suite added to this test plan.  @artur will be able to provide you with the important links to assist you with QA.

**Comment by ihaid** [comment]
@NiaStorj yes, sure

**Comment by amwolff** [comment]
okay, so I think it would be worth including testing the gateway and maybe replicating tests from the below test suites natively:

- https://github.com/storj/gateway-mint/tree/main/build/versioning
- https://github.com/ceph/s3-tests/blob/master/s3tests_boto3/functional/test_s3.py
    - this test suite is the most interesting one
- https://github.com/storj/splunk-s3-tests/blob/main/s3tests/functional/test_s3.py
    - this is roughly the same as the previous one
- https://github.com/snowflakedb/snowflake-s3compat-api-test-suite

**Comment by ihaid** [comment]
@amwolff Here is [updated PR](https://github.com/storj/storj/pull/6444)
