### ISSUE TITLE
Create a Storj backed IPFS node

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#628]
👋 Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! 😄

---

Job Story: 
When I pin data on IPFS, I want it to save and serve the data from the Storj Network so that it does not happen from my local computer. The goal is to be an IPFS node that does not store any data locally. It can use libstorj/bucket store to save and serve IPFS data you pin using the Storj Network. 

This service should run on the customer side, not on the storage node side. This would mean that the customer is paying for the service. The service can be named something like ipfs-gateway

**Comment by heunland** [comment]
added comma after "IPFS" and changed "storj network" to "Storj Network"

**Comment by iglesiasbrandon** [comment]
Closing this issue. We have an IPFS pinning service that is a beta product.
