### ISSUE TITLE
Update wording of limit increase request notification

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6291]
Currently, when a user requests a bandwidth or storage limit increase within the satellite UI, it just says that their request has been submitted, but does not indicate a timeline for how long to wait.

**AC**

Add information to the "success" notification for limit increase requests:
* indicate that it could take 2 to 3 business days in order for the limit increase to be applied

**Comment by ferristocrat** [comment]
How about:

Current: **Your request for limits increase has been submitted.** Support will get back to you.

New: **Your request for limits increase has been submitted.** Limit increases may take up to 3 business days to be updated and reflected in your limits.
