### ISSUE TITLE
Apply "pending deletion" status at end of billing freeze flow

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6303]
**AC**
* Add a new config to the [account freezes chore](https://github.com/storj/storj/blob/22261146bef98c6d7a81bbbf9c34ba515141f7a6/satellite/payments/accountfreeze/chore.go#L31-L37) that defines a duration between a "billing freeze" occurring, and a user's account being marked for deletion.
* If a user is frozen and still has unpaid invoices after being frozen for the duration defined in the new config, apply the new [pending deletion status](https://github.com/storj/storj/issues/6302).

Dependent on https://github.com/storj/storj/issues/6302

**Comment by ferristocrat** [comment]
@wilfred-asomanii  - when this is deployed: existing customers that have been in the "suspended" status for a long time, will they automatically be moved to "pending delete"?
