### ISSUE TITLE
Vuetify: shorten project ID in url

### ISSUE THREAD

**Issue by jewharton** [storj/storj#6308]
### Motivation

Currently, the entire project ID - all 37 characters - is stored in project-related URLs. is We wish to shorten the project ID in order to make the URL more aesthetically pleasing and for users to be able to see the full URL in the address bar rather than it being obscured due to the length of the ID. Additionally, shorter URLs are perceived as more trustworthy compared to longer URLs which may be seen as scammy / phishing-related.

### Acceptance Criteria

- Project IDs in Vuetify URLs are 10 characters long, only exceeding this in case of a collision.

**Comment by egonelbre** [comment]
Did we consider using something like a random unique uint64 instead?

**Comment by jewharton** [comment]
@egonelbre We could do that. There's no requirement that the project's URL ID should be derived from the project's public ID.

**Comment by onionjake** [comment]
Is the project ID already random? If it is then there is no benefit to adding and additional column, but using the first 64 bits of it would be equivalent?

**Comment by elek** [comment]
What's the plan to get the next short integer? We had some performance issues with internal object versions (which uses integer seq). Cockroach recommends using UUID (/random numbers) instead of sequence, as it's more cheaper to get the next value. 

(But may not be a problem as project insert is not very common...)

**Comment by jewharton** [comment]
We recently decided not to store integers in the database for the short ID, instead opting for client-side code that generates short IDs from unique public ID prefixes.
