### ISSUE TITLE
/usage-limits endpoint returns updated limits with some delay

### ISSUE THREAD

**Issue by VitaliiShpital** [storj/storj#6317]
steps to reproduce:
1. create account
2. upgrade to paid tier
3. update storage or bandwidth limit
4. reload page

you'd see old limits for some time. Endpoint would return new limits in about 1 min

**Comment by ferristocrat** [comment]
Would adding a note like "Limit updates may take up to X minutes to be reflected here." be a solution? Or is it that were not clearing/refreshing some cache?

**Comment by cam-a** [comment]
+1 to adding text indicating that it may take some time for changes to be reflected in data. We used to have this I believe.

**Comment by onionjake** [comment]
Can we clarify if this is a frontend cache or a satellite cache causing this? In either case this should be solvable (frontend should invalidate its cache on pro upgrade, if it is satellite side then either a new un cached endpoint can be added foe the UI or the existing one made to not cache).

**Comment by mobyvb** [comment]
@onionjake it is a satellite cache causing this as far as I know. We can create another ticket to add an endpoint for bypassing the cache. This ticket was just to do a quickfix message and we can work on a better solution next

**Comment by mobyvb** [comment]
actually, it does not appear that we are getting limits in the UI from the limits cache used by metainfo. That info should be coming directly from the DB.
@VitaliiShpital can you confirm what endpoints are used to retrieve limits in the UI, and whether they come from the DB vs. a cache? It looks like they come from the DB to me.
