### ISSUE TITLE
Multipart upload - Add the ability to continue multipart uploads

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#632]
---
👋 Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! 😄
---

Our current implementation uses an in-memory implementation of the uploading state. It also writes the parts as a single stream rather than separate segments. However, in case of an error, the whole upload fails.

This causes several problems:
1. there isn’t a way to continue a failed segment
2. we are unable to atomically swap out the object based on versions

This needs several enhancements:
1. Separate namespace for partially uploaded objects
2. Listing failed segments
3. Uploading part as a single segment
4. Supporting varying segment sizes

Also for improved usage:
1. Versioning support in piecestore
2. Atomic path swaps in piecestore

**Comment by jtolds** [comment]
waiting on multipart upload until after beta is over
