### ISSUE TITLE
tag-signer should warn when comma is used

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6336]
We have a tag-signer to generate the value of a storagenode configuration (CONTACT_TAGS)

https://github.com/storj/storj/tree/main/cmd/tools/tag-signer

Example usage:

```
tag-signer sign --identity-dir ~/j/us3 --node-id ... soc2=true --log-level=ERROR
```

It also supports multiple tags with repeating `key=value` multiple times.

However when we started to use it, we accidentally used it in a wrong way. Instead of using tag-signer sign ... key1=value1 key2=value2` we used `tag-signer sign key1=value1,key2=value2`. 

This created one tag which the value `=value1,key2=value2` instead of two tags...

To avoid similar accident in the future, we would like the validate a value and enable comma in value, only if a `--confirm` flag is used.

**Comment by profclems** [comment]
@shaupt131 I just noticed we never estimated this
