### ISSUE TITLE
placement level health stat

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6339]
1. we have only general `checker_segment_healthy_count`, we don't have information about placement level numbers
2. probably we also need some additional stat for duratbility / node providers

**Comment by elek** [comment]
https://review.dev.storj.io/c/storj/storj/+/11372

**Comment by elek** [comment]
https://review.dev.storj.io/c/storj/storj/+/11391

**Comment by elek** [comment]
One more patch is required here to adopt the suggestion from @egonelbre 


![Image](https://github.com/storj/storj/assets/170549/1a68a721-7753-4077-a965-1f226f3a5302)

**Comment by shaupt131** [comment]
@elek do you have a link to your above-mentioned patch?

**Comment by elek** [comment]
They are not yet created.

**Comment by elek** [comment]
https://review.dev.storj.io/c/storj/storj/+/11632/1
https://review.dev.storj.io/c/storj/storj/+/11633/1

**Comment by iglesiasbrandon** [comment]
@elek it looks like all of these patches have been deployed to production. I am going to close this issue. @shaupt131
