### ISSUE TITLE
monkit metric for hash / io speed

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6340]
We realized that the uplink process executed from the OVH nodes are very slow.

After some investigation, it turned out that the nodes are quite slow (they have a 8 years old Xeon processors).

We need to understand of they are fast enough to serve the traffic...

Solution: let's measure the hash time and io time per pieces to make it easier to compare different nodes...

**Comment by elek** [comment]
https://review.dev.storj.io/c/storj/storj/+/11328
