### ISSUE TITLE
Multipart upload - PointerDB atomic swaps when committing an object stream

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#635]
---
👋 Hey! This is an issue that Storj would love the community's help on. If you have any questions about how to get started or want to discuss further, add a comment. Likewise, if you want to jump in, say so below. PRs accepted! 😄
---

We should separate objects that are being uploaded and objects that have been uploaded. This ensures that we can properly figure out failed parts and avoids partial state being shown to end-user.

**Comment by jtolds** [comment]
waiting on multipart upload until after beta is over
