### ISSUE TITLE
Migrate metabase `objects` table `version` column from INT4 to INT8

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#6352]
We need to migrate metabase objects table version column from INT4 to INT8.

Acceptance Criteria:
* if its possible we should do this with regular deployment migrations, if it turns out that migration is not async or it takes too much time we should apply schema changes manually to all satellites and with deployment migration cover only case if migration was not applied manually

**Comment by egonelbre** [comment]
There's some test code in https://github.com/storj/storj/issues/6220#issuecomment-1695831471 that sets up tables for testing and it seemed to work fine.
