### ISSUE TITLE
Investigate Possibility of Using Stripe Elements

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6380]
### Overview
We have a need to collect address information for billing as well as zip code specifically for US based tax purposes. Some of the design is  captured here: https://github.com/storj/storj/issues/5484 for managing a users billing address.

There is quite a bit of logic that determines what information needs to be collected as part of an address (and VAT number) based on the billing country. This seems like a lot to manage so we want to look into "off the shelf" options Stripe has to support this.

### Acceptance Criteria

- look into viability and feasibility of implementing https://stripe.com/en-gb-pt/payments/elements
  - https://stripe.com/docs/payments/payment-element
  - https://stripe.com/docs/elements/address-element?platform=web
  - https://stripe.com/partners/directory/vue-stripe
  - https://stripe.com/docs/js
  - also check if there are vuetify components for the above
- create tasklist on this ticket for integrating these stripe elements into the UI
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6436
```

**Comment by wilfred-asomanii** [comment]
It is feasible and simple enough to implement stripe elements. We already use one, the card element, to collect card details. However, that element is marked as legacy by Stripe and we might want to change to using the payment element instead.
The payment element is more extensible in that, it supports different types of payment methods (e.g. Apple/Google Pay, Cash App), though what we want is only the card payment.

The address element is just as easy to implement though it does not have the capability to collect tax information. Tax information is something we might have to collect separately in our own form. The only automatic way I saw is by using [Stripe checkout](https://stripe.com/docs/tax/checkout/tax-ids#testing), which won't work for our billing flow.

Last, the vue-stripe is a vue2 project, it also may be a hindrance for us with the [custom behavior](https://stripe.com/docs/payments/finalize-payments-on-the-server?platform=web&type=payment&client=html#create-pm) we want with the payment element anyway.

**Comment by heunland** [comment]
We have at least 1 Canadian customer who is unable to use their Canadian AMEX card because we have not implemented this feature so they cannot add their Canadian zip code. See screenshot attached. Please give resolving this issue priority as we may be losing potential customers because of this.
![billing-issue](https://github.com/storj/storj/assets/8723695/cd500839-c318-462c-8c9e-cf308087f94f)

**Comment by mobyvb** [comment]
@ferristocrat create tickets for subsequent tasks to add stripe/billing-related improvements

**Comment by ferristocrat** [comment]
Andi is digging into billing/stripe related stuff, so I'm going to close this one out of blocked.
