### ISSUE TITLE
Implement "feature flag" to allow enabling logic for object versioning per project

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6383]
### Background:
We wish to enable the ability to use the new object versioning on a subset of projects, for testing purposes, before rolling out the feature to the entire network. This has been done in the past for other large features such as changes to the pending objects table.

Related to https://github.com/storj/storj/issues/6222

### Acceptance Criteria:
New object versioning logic can be used by projects specified in a config file.

**Comment by mniewrzal** [comment]
Commits for pending_objects table support:
https://github.com/storj/storj/commit/67371c43bda420fba81af39b8fb549042affc4f4
https://github.com/storj/storj/commit/fb04a22088acb6cb5c4eb8501a18d06513aceae8
