### ISSUE TITLE
Create bucket-level versioning DB schema

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6385]
### Background:
Add the DB schema changes to support bucket level configuration of object versioning. Use the [design doc](https://github.com/storj/design-docs/blob/main/20230801-bucket-level-versioning-configuration.md) as needed.

### Acceptance Criteria:
DB Schema created, and basic implementation methods created to set/update bucket level configuration for object versioning.

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/storj/+/11453
