### ISSUE TITLE
Update Copy on Signup Page

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6396]
### Describe the feature or problem you'd like to solve

Storj's message has changed, so we need to update the sign up page to reflect our current customer focus.

### Acceptance Criteria
- Update the left side of the sign up page with the following (see images and figma for details):
  - New logo (just "Storj" instead of "Storj | DCS"
  - Updated copy
- Default the selection to "Business" rather than "Personal"

*Screens*
| Old | New |
| --- | --- |
| <img width="1440" alt="sign-up-before" src="https://github.com/storj/storj/assets/7063002/c1bb3982-0033-4cd6-af94-0eb39212b992"> | <img width="1323" alt="sign-up-after" src="https://github.com/storj/storj/assets/7063002/6d130a3d-d270-4fbd-aa47-bfcdf76c1d94"> |

**Figma Link:**
- https://www.figma.com/file/D6Jys8Q9Oke2M4GBBp8xdP/Storj-Website-2023?type=design&node-id=308%3A76513&mode=design&t=69KMf3gu7vcBJLUO-1

### Out of scope
- The input form for signup (right side of the designs)
  - This will be a separate issue

**Comment by boshevski** [comment]
https://github.com/storj/storj/pull/6409
