### ISSUE TITLE
Repair checker should fix durability issues

### ISSUE THREAD

**Issue by elek** [storj/storj#6405]
Our new segment loop https://review.dev.storj.io/c/storj/storj/+/11372 will report durability issues, like single country or SNO controls too much pieces from a segment.

Would be nice to improve the repair checker / repair process to fix these problems in addition to the alerts.

**Comment by shaupt131** [comment]
Let's complete https://github.com/storj/storj-private/issues/465 first then we can prioritize this issue accordingly.

**Comment by shaupt131** [comment]
@elek is this now addressed by your efforts under https://github.com/storj/roadmap-private/issues/95?

**Comment by elek** [comment]
Yes, it is covered by the new placement configs. Let me close sthis one.
