### ISSUE TITLE
Revert pending_objects table changes (code/configurations)

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#6421]
We decided that for now we won't keep `pending_objects` table because of performance impact of processing two tables. We need to revert changes we did for this feature.

Acceptance Criteria:
* disable pending objects table feature flag on satellites
* remove pending_objects implementation (save it under `pending_objects` branch)

**Comment by shaupt131** [comment]
Going to delay doing this until metabase/metainfo changes are complete to avoid complications and confusion.
