### ISSUE TITLE
Vuetify: copy over login and signup pages from storj-vuetify repo

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6425]

**Comment by mobyvb** [comment]
@boshevski let us know when this is ready to be worked on

**Comment by boshevski** [comment]
This is ready, the pages are in the static vuetify repo.

**Comment by wilfred-asomanii** [comment]
The change that adds the authentication pages includes some (styling) changes on unrelated pages. Should those changes be copied over as well or should be done as part of another ticket?
