### ISSUE TITLE
Satellite admin web App: Create list users functionality

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#6432]
## Motivation / Why?

We want to have the first functionality for the new satellite admin web App from the front-end to the back-end.
Because listing the user's accounts is the entry point for all the operations that we are going to expose on it, we want this one to be the first.

## What needs to be done?

- Define the API endpoint to list the users using the API generator. This API endpoint must allow searching and sorting by some fields, and pagination.
- Implement the business logic of the endpoint.
- Wire the front-end with the API client generated by the API generator.
- Implement the needed fornt-end logic to accommodate the API client call.

## Acceptance criteria

- The new web App lists the users' accounts of the satellite.
- The new web App allows one to search for the defined fields to retrieve the list of users' accounts that match the search criteria.
- The new web App allows sorting by the defined fields of the list of users' accounts.
- The new web App paginates the results and allows navigating to the next and previous pages.

Depends on #6422

**Comment by mobyvb** [comment]
It looks like there was a decision to delay implementing this until after the "view single user" functionality. See conversation [here](https://storj.slack.com/archives/C05HM17RAUF/p1699539435569549). cc @NiaStorj

**Comment by shaupt131** [comment]
@mobyvb @jewharton Can we swap out for https://github.com/storj/storj/issues/6503 this sprint in its place?

**Comment by mobyvb** [comment]
@shaupt131 yes we should be able to do that. cc @NiaStorj
