### ISSUE TITLE
durability: add exemplar and report time to the reported results

### ISSUE THREAD

**Issue by elek** [storj/storj#6443]
Exemplars are representative elements for the stat. For example if a stat min is `30`, we can save one example with that value.

More details about the concept is here: https://grafana.com/docs/grafana/latest/fundamentals/exemplars/

In our context, which save the segment + position in case of min is updated, to make it easier to look after the segment in danger.

**Comment by elek** [comment]
https://review.dev.storj.io/c/storj/storj/+/11517

**Comment by iglesiasbrandon** [comment]
Hey @elek I am going to close this issue since its been deployed to production. @shaupt131
