### ISSUE TITLE
cmd/storagenode: forget-satellite does not work as expected

### ISSUE THREAD

**Issue by egonelbre** [storj/storj#6465]
https://build.dev.storj.tools/job/uplink-gerrit/2678/testReport/junit/storj/io_storj_cmd_storagenode/Build___Verification___Integration__storj_storj____Test_cmdForgetSatellite_Postgres/

```
   log.go:70: 00:00.609	INFO	storage0.reputation:service	node scores updated	{"Satellite ID": "1xTwTPLWfiqffa5VbA9c7ZZgkhZuAqdp4aphJ6udVWU2LadQF", "Total Audits": 0, "Successful Audits": 0, "Audit Score": 1, "Online Score": 1, "Suspension Score": 1, "Audit Score Delta": 1, "Online Score Delta": 1, "Suspension Score Delta": 1}
    cmd_forget_satellite_test.go:148: 
        	Error Trace:	/go/pkg/mod/storj.io/storj@v0.12.1-0.20231028044343-1fa918c255e4/cmd/storagenode/cmd_forget_satellite_test.go:148
        	            				/go/pkg/mod/storj.io/storj@v0.12.1-0.20231028044343-1fa918c255e4/private/testplanet/run.go:83
        	            				/go/pkg/mod/storj.io/storj@v0.12.1-0.20231028044343-1fa918c255e4/private/testmonkit/run.go:49
        	            				/go/pkg/mod/storj.io/storj@v0.12.1-0.20231028044343-1fa918c255e4/private/testmonkit/run.go:43
        	            				/go/pkg/mod/storj.io/storj@v0.12.1-0.20231028044343-1fa918c255e4/private/testplanet/run.go:51
        	Error:      	Not equal: 
        	            	expected: &reputation.Stats{SatelliteID:storj.NodeID{0x2, 0x2b, 0xde, 0x36, 0xdb, 0x58, 0x59, 0xa3, 0xc, 0xa5, 0x47, 0x6b, 0x5c, 0x98, 0x53, 0xbc, 0xbe, 0x45, 0x17, 0x8a, 0xf7, 0x5e, 0x79, 0x9a, 0xd8, 0xb, 0x5, 0x7d, 0xe8, 0x2a, 0xd0, 0x0}, Audit:reputation.Metric{TotalCount:0, SuccessCount:0, Alpha:0, Beta:0, UnknownAlpha:0, UnknownBeta:0, Score:0, UnknownScore:0}, OnlineScore:0, DisqualifiedAt:<nil>, SuspendedAt:<nil>, OfflineSuspendedAt:<nil>, OfflineUnderReviewAt:<nil>, VettedAt:<nil>, AuditHistory:(*pb.AuditHistory)(nil), UpdatedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), JoinedAt:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC)}
        	            	actual  : &reputation.Stats{SatelliteID:storj.NodeID{0x2, 0x2b, 0xde, 0x36, 0xdb, 0x58, 0x59, 0xa3, 0xc, 0xa5, 0x47, 0x6b, 0x5c, 0x98, 0x53, 0xbc, 0xbe, 0x45, 0x17, 0x8a, 0xf7, 0x5e, 0x79, 0x9a, 0xd8, 0xb, 0x5, 0x7d, 0xe8, 0x2a, 0xd0, 0x0}, Audit:reputation.Metric{TotalCount:0, SuccessCount:0, Alpha:1000, Beta:0, UnknownAlpha:1, UnknownBeta:0, Score:1, UnknownScore:1}, OnlineScore:1, DisqualifiedAt:<nil>, SuspendedAt:<nil>, OfflineSuspendedAt:<nil>, OfflineUnderReviewAt:<nil>, VettedAt:<nil>, AuditHistory:(*pb.AuditHistory)(0xc0019fee00), UpdatedAt:time.Date(2023, time.October, 30, 11, 19, 32, 310795665, time.UTC), JoinedAt:time.Date(2023, time.October, 30, 11, 19, 32, 282254000, time.UTC)}
```

**Comment by egonelbre** [comment]
In `CacheReputationStats` it fetches multiple satellites which then do a store into the reputation service, which upserts causing a forgotten satellite to be reinserted into the database.

See https://review.dev.storj.io/c/storj/storj/+/11609 for a repro and some other fixes.

**Comment by egonelbre** [comment]
Related https://github.com/storj/storj/issues/6068

**Comment by shaupt131** [comment]
Lets treat this as an investigation ticket to devise a plan.  More tickets will possibly follow up.

**Comment by profclems** [comment]
We can redesign it to work like the `storagenode exit-satellite` command for graceful exit which sends a drpc request to the main storagenode process to initiate graceful exit.

**Comment by shaupt131** [comment]
@profclems how would you estimate the lift to redesign the command to a drpc request?  3?  5?  8+?

**Comment by egonelbre** [comment]
> This will not be an issue practically, because in the [instructions](https://forum.storj.io/t/how-to-forget-untrusted-satellites/23821) we provided, it is expected that the node be restarted after successfully running the forget-satellite subcommand.

The current `forget-satellite` would only work when the storage node is completely shutdown while running the command.

I think the approach should be that we shouldn't require a storagenode restart to forget a satellite.

**Comment by profclems** [comment]
> I think the approach should be that we shouldn't require a storagenode restart to forget a satellite.

Yes https://github.com/storj/storj/issues/6465#issuecomment-1805691604

**Comment by shaupt131** [comment]
ok, @profclems is this a major redesign?  Or something that could be done within a single, reasonably sized ticket?

**Comment by shaupt131** [comment]
Also, have we had many complaints from the forums or support about this issue?

**Comment by profclems** [comment]
Yes @shaupt131, it is a major redesign because it will change how it works. I will give this ticket a size 5. I will create minor follow up tickets.

We haven't had any major complaints about this on the forum. The only issues that were brought up were somehow related to used space calculation which remains the same after running the forget-satellite command unless the node is restarted.

**Comment by shaupt131** [comment]
Could not restarting the node possibly cause https://github.com/storj/customer-issues/issues/1191?

**Comment by profclems** [comment]
Yes @shaupt131

**Comment by shaupt131** [comment]
@profclems to create follow-up tickets that will be available when we decide to implement this.

**Comment by shaupt131** [comment]
https://github.com/storj/storj/issues/6539 and https://github.com/storj/storj/issues/6540 would be required to remove the node reboot from this process.  Closing this investigation ticket, and we can promote those issues when we deem it necessary.
