### ISSUE TITLE
Satellite admin web App: Create view user functionality

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6469]
## What needs to be done?

- Create an API endpoint that returns a verified user based on a provided email address.
- Create a UI element wherein a satellite operator can enter the email address of the user to be accessed.

## Acceptance criteria

- The operator accesses the admin UI and has a search box that asks for a user's email address.
- Upon submitting:
  - If a verified user with the provided email address was found, the operator should be redirected to the Account Details page. This page should be populated with the user's information.
  - If a user was not found, a notification should be displayed informing the operator of this.

**Comment by shaupt131** [comment]
At this time, we only want to return verified accounts.  This will prevent the possibility of returning duplicate accounts (verified and unverified).  We can add a way to search for unverified accounts in a future phase of the project.

**Comment by jewharton** [comment]
The issue description has been updated in accordance with recent discussion.
