### ISSUE TITLE
Satellite admin web App: Update project information

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#6477]
## Motivation / Why?

The new satellite administration Web App allows users to update project information.

## What needs to be done?

- Define API endpoint to update project information through the API generator. 
	-  It has to support all the data that can be updated. This implies name, description, value attribution, placement, and limits.
	- Limits are:
		- Storage (GB)
		- Egress (GB)
		- Segments limits. Maximum number of segments
        - Buckets limits. Maximum number of buckets.
    - It has to be a patch endpoint because we only want to update the data that is sent.
- Implement the business logic of the endpoint.
- Wire the front-end with the API client generated by the API generator.
- Implement the needed front-end logic to accommodate the API client call.

## Acceptance criteria

- The new web App allows modifying the project information from the project information page and the UI widgets for this matter.
- The new web App doesn't allow the user to update the data if the new data isn't valid (font-end validation).
- The new web App shows an error to the user if the update API call returns an error.
- The new web App allows the user to cancel a modification before submitting it.

**Comment by shaupt131** [comment]
This is dependent on the completion of https://github.com/storj/team-delivery/issues/461

**Comment by ifraixedes** [comment]
As we discussed in the sync meeting on the 4th of January 2024, we decided to implement several endpoints to update the project's data instead of implementing a single endpoint to update all the project's data.

I canceled this issue after I created a single ticket for each endpoint: #6664 #6665 #6666 #6667
