### ISSUE TITLE
XDG Base Directory Specification

### ISSUE THREAD

**Issue by BlackDuck888** [storj/storj#648]
Storj is creating a folder `~/.storj` according to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) it should be placed at `~/.config/storj` or `~/.local/storj`

**Comment by iglesiasbrandon** [comment]
Hey, @BlackDuck888 the PR (684) @egonelbre mentioned above fixed this issue so I am going to go ahead and close this Github Issue. Please let us know if you see any other issues!
