### ISSUE TITLE
Retain procedure appears to crash or get canceled when it fails to delete a piece

### ISSUE THREAD

**Issue by thepaul** [storj/storj#6482]
When we are running a Retain operation, and we fail to delete a piece, we should continue with deleting the rest of the pieces, rather than crashing or quitting.

See, in particular, https://forum.storj.io/t/us1-storj-io-disk-average-30-lower-than-actual-disk-usage/24197/16

**Comment by iglesiasbrandon** [comment]
closing this issue because the fix has been deployed to production. @thepaul @shaupt131
