### ISSUE TITLE
[storagenode] Ability to turn off the storagenode version checker chore

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6486]
Docker nodes contain a storagenode-updater that checks the storagenode version and automatically updates it. The storagenode also has a version checker chore that checks if the node is up to date and notifies on the dashboard's notification center. So for docker nodes, both the updater and storagenode runs a version checker chore, and you will never receive a notification about an outdated node binary if ypu're running a docker node because the updater will always update the node before the node's version checker will find out that the software needs update.

Acceptance criteria:
- Add a config flag that allows to disable the version checker chore on the storagenode
- Add an environment variable to the docker container which by default, disables the version checker chore

Value
- this will reduce the amount of errors on the storage node if the checker fails
- This will allow us to run storage nodes in an air-gapped environment so that we can disable to checker that reaches out to external services (which fails in this senario)

**Comment by iglesiasbrandon** [comment]
i dont understand the value of being able to disable to version checker chore on the storage node. can you please elaborate? @profclems 

If the updater fails then you would receive an update when the version checker runs

**Comment by littleskunk** [comment]
> This will allow us to run storage nodes in an air-gapped environment so that we can disable to checker that reaches out to external services (which fails in this senario)

I also don't get it. If version control is unreachable we end up with a docker contain with no storage node binary in it. Currently the storage node binary has to be downloaded from github otherwise the docker container doesn't work. Disabling the version doesn't make the docker container work.

**Comment by profclems** [comment]
@littleskunk Disabling it on the storagenode binary isn't the same as disabling it on the updater. And this is entirely different from the docker container directly downloading the binary because it does not depend on this flag. It will still download the binaries on start.

Also for air-gapped nodes, we have https://github.com/storj/storj-private/issues/382 to include a storagenode binary to the docker image.

**Comment by iglesiasbrandon** [comment]
moving to deployed.
