### ISSUE TITLE
satellite/durability: use single classifier per observer instance

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6488]
The problem here is some durability metrics are not very meaningful, as we have known durability risks for specific placements.

For example: we know that we will loose data if all the US nodes are down, because we have a US geofencing region.

But instead of placement exclusion, I think it would be enough to separate country and other classifiers. At least for no.

**Comment by elek** [comment]
https://review.dev.storj.io/c/storj/storj/+/11759
