### ISSUE TITLE
Move API generator inline writing to a template

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#6491]
## Motivation / Why?

The API generator doesn't adapt to some satellite admin API needs.

We can update the API generator to have options that only apply to the admin API, however, the generator will have options for each generated code (so far, satellite console API and satellite admin API).

Having options that only apply to one generated code makes its usage more complicated for the users and the logic of the generator more difficult to follow.

## What needs to be done?

Move the current generator inline writing to a template and add two options, one for specifying a template and another for passing extra parameters to each endpoint that the template can use.

## Acceptance criteria

- Move the API generator inline writing to a template. The template will be the default one and it has to be embedded.
- Add one option to the API definition to specify a custom template. If it isn't used, the default one is used.
- Add one option to each endpoint definition that can hold any type (i.e. `any`). This allows custom templates can use this field to generate custom code with data that isn't available in the endpoint fields.

Caused by #6467
Needs #6474

**Comment by ifraixedes** [comment]
I started the implementaiton as described in the issue, however I faced a wall of complexity to compose a template from the inline writing.

I had a quick call with Egon to exchange ideas and we though that we could have a some customizations that can be injected with implementations. My approach to that solution is implemented in https://review.dev.storj.io/c/storj/storj/+/11754 which is ready for reviews.

**Comment by shaupt131** [comment]
@egonelbre to review ^

**Comment by ifraixedes** [comment]
The following commit is also related to this because it was commented on in the review of the above commit, but it got merged without addressing it.

https://review.dev.storj.io/c/storj/storj/+/11810

**Comment by ifraixedes** [comment]
Deployed in [v1.94.1](https://github.com/storj/storj/releases/tag/v1.94.1)
