### ISSUE TITLE
Release-v1.92 Test Uplink Download Refactor

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#6499]
Quick performance comparison between old and new uplink. Also check if higher concurrency makes it faster. Last time we messed up the concurrency flag and big customers complained about the performance with just default concurrency.

**Comment by ihaid** [comment]
<google-sheets-html-origin style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none; caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0);">

Upload | 10MB | 5,524 | 10MB | 5,905 | 0,381
-- | -- | -- | -- | -- | --
100MB | 22,578 | 100MB | 24,945 | 2,367
1000MB | 138,83 | 1000MB | 144,82 | 5,99
Download | 10MB | 1,039 | 10MB | 1,071 | 0,032
100MB | 3,646 | 100MB | 4,16 | 0,514
1000MB | 38,484 | 1000MB | 73,7 | 35,216

</google-sheets-html-origin>
