### ISSUE TITLE
Stripe Invoice Process Failing

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6500]
### Summary
Some customers have so many projects that when an invoice is generated, it has more line items than Stripe supports and the invoice process fails.

From Arch review:
>Special invoice generation for large customers with tons of projects. Have only a minimal invoice line numbers for their total usage. Send the customer an Excel sheet with the project-based breakdown. Or put the breakdown in the invoice description.

### Acceptance Criteria
- Invoices should not fail due to having too many line items
- Customers should have a way to see their detailed usage by project (if they can't see it on their invoice)

### Solution Proposal
Part 1: If invoices would have greater than X number of line items (where X is the maximum allowed by Stripe), aggregate usage for the Stripe invoice. Aggregate by sum of egress, storage, and segment fees.
Part 2: Improve the Detailed Usage Report to enable customers to download historical usage (currently it only allows download of the current month's usage) -- in the meantime we will send a CSV file with their detailed usage for the month.

### Questions
1. Detailed usage reports
    - Is this something we can already generate for them? (If not we should have a second issue here)
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6512
- [ ] https://github.com/storj/storj/issues/6513
```

**Comment by iglesiasbrandon** [comment]
This item is merged and deployed. I am going to close it.
