### ISSUE TITLE
Use Stripe Idempotency

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6501]
Fix invoice and line item creation to use [idempotency with Stripe](https://stripe.com/docs/api/idempotent_requests), and not mark creation completed until the idempotent call to Stripe is done.

See [this helpful Stripe Developers video](https://www.youtube.com/watch?v=sUkZnCvmQ8g) for information about how to use idempotency keys in Go.

The criteria for the idempotency keys should be:
* the idempotency key must always be the same for the _same_ invoice line item, even on a different run
* the idempotency key must be _unique_ for each invoice line item, so that there is never a collision
  * it should also be unique across separate invoice cycles

Given these criteria, we could likely craft the idempotency key by concatenating multiple segments:
* project identifier (could be project public ID)
* line item identifier (e.g. "storage" or "egress" or "segment")
* time period identifier (e.g. the month and year of the current invoice cycle being run)

### AC
* when invoicing is halted partway through, then started again, duplicate invoice items are never created
* the satellite database is not updated indicating that a new invoice record was created until/unless Stripe successfully creates the invoice item

**Comment by ferristocrat** [comment]
From grooming: idempotency isn't relevant without retries, so maybe we should add retries AND idempotency? Thoughts @jtolio , or did you have something specific already in mind?

**Comment by mobyvb** [comment]
@jtolio could you take a look at the details I added to the ticket and let me know if it looks good to you?
