### ISSUE TITLE
Satellite admin web App: Create find user by e-mail functionality

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#6503]
## Motivation / why?

We are not going to build the list users functionality for phase 1 and in the current UI is the entry point to access a user's account information.

## What needs to be done?

- Create an API endpoint that returns a list of users based on email that contains the indicated text.
- Create a UI element that asks the user for part of the user's email that the operator would like to access.

## Acceptance criteria

- The operator accesses the admin UI and has a search box that asks for text that a user's email must contain.
- The operator sees the list of users that matches the text that they have introduced.
- The operator can click on one of the listed users to access to that user's account information page.

**Comment by jewharton** [comment]
We've decided not to implement this functionality for the time being. Alternative behavior is described in #6469.
