### ISSUE TITLE
Aggregate invoices with many projects

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6512]
### Summary
Stripe bills have too many line items for some customers with many projects, breaking the billing process

### Acceptance Criteria
- If invoices would have greater than X number of line items (where X is the maximum allowed by Stripe), aggregate usage for the Stripe invoice
  - Aggregate by sum of egress, storage, and segment fees.

**Comment by iglesiasbrandon** [comment]
this was the correct PR https://review.dev.storj.io/c/storj/storj/+/11795
