### ISSUE TITLE
Historical Detailed Usage Report

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6513]
### What is the problem/pain point?

- The Storj web console currently allows downloading of a "Detailed Usage Report" for the current month only. Customers need similar information for their entire history. At present, historical data is available only through monthly invoices, which aggregate usage at the project level or higher, lacking detail.

### Who is impacted?

- Customers requiring detailed historical data, particularly those managing multiple projects. Also, internal teams like customer support and solutions engineering are impacted.

### What is the impact?

- This limitation hinders customers' ability to perform in-depth analysis of their usage over time. It leads to increased reliance on manual processes and potential dissatisfaction due to the lack of detailed historical data.

### Why now?

- Addressing this need is crucial for enhancing customer satisfaction and value, especially for enterprise customers.

### User Story

- As a Storj user, I want to access a "Historical Detailed Usage Report" that includes granular data for all my projects and buckets, so I can analyze my long-term usage patterns and manage resources more effectively.

### Acceptance Criteria

- The ability to generate detailed historical reports encompassing all the same information that is currently contained in the "Detailed Usage Report" download:
  - For a particular month
  - For a particular date range

### Success Metrics

- Reduction in customer inquiries for detailed historical data
- Increased usage of historical reports

**Comment by ferristocrat** [comment]
Wondering if we should also add:
- rate limiting
- caching of results, so that we don't need to refetch/query the same data multiple times
-

**Comment by onionjake** [comment]
Suggest adding some sort of limitation to the date ranges, or perhaps not even date ranges at all but simply months? Don't allow picking more than some amount as well to reduce the chance that all time is picked?

If we want all time able to be picked, then it should be tested on years worth of data up to 100 bucket and ~80 projects to make sure we won't have issues with it being generated?

**Comment by ferristocrat** [comment]
Some additional context: the request just takes in a UTC date range as request params, so theoretically customers can request whatever date range they want today - so my recommendation (based on Jacob's suggestion above) assuming we're not going to change this endpoint is:
1. Restrict the date range that this endpoint accepts, perhaps 13 months such that we can be sure customers can get a year
2. In the UI just have month range selection, up to 12 months
3. Test the edge cases of maximum projects X maximum buckets

**Comment by ferristocrat** [comment]
@boshevski - tagging you to provide your input with regard to design

**Comment by boshevski** [comment]
Added designs for selecting past month, past year, and custom date range for downloading detailed usage reports in the billing section at https://storj.github.io/vuetify-storj/
