### ISSUE TITLE
Vuetify: remember dismissed UI notifications at the user level

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6516]
There are certain tooltips/notifications that are displayed to the user. When they are dismissed, we often use a localstorage variable to remember this. However, we want to remember that these notifications are dismissed even if the user logs in on a different device or in a different browser.

One option would be to add field(s) to the `user_settings` table that allows us to track information like that a user has dismissed a notification.

### AC:
* Identify all notifications/tooltips that are dismissable in the vuetify app
  * implement a way to remember that these notifications/tooltips have been dismissed at the user-level, so that dismissals are remembered on different devices/browsers/after cache clear

**Comment by wilfred-asomanii** [comment]
v1.97.2   7534277
