### ISSUE TITLE
Support multi-node placement rules

### ISSUE THREAD

**Issue by elek** [storj/storj#6524]
The very heart of the the node selection is this code fragment:

https://github.com/storj/storj/blob/c2029294131ed0baf136ce9107085a1383bb1476/satellite/nodeselection/selector.go#L19-L39

This uses NodeFilter which is defined as:

```
type NodeFilter interface {
   Match(node *SelectedNode) bool
}
```

We worked hard to remove any statefulness in NodeFilters. Unfortunately for declumping / rack-awareness we need a state, or list of all selected nodes.

Possible the easiest way to do this is returning with function which supposed to be executed at the beginning of the check:

```
type NodeFilter interface {
   Matcher func(node *SelectedNode) bool
}
```

**Comment by elek** [comment]
cc @egonelbre

**Comment by egonelbre** [comment]
Could we add the already selected nodes as an argument?

**Comment by elek** [comment]
Yes, we considered this version:

```
type NodeFilter interface {
   Match(alreadySelected []*SelectedNode, node *SelectedNode) bool 
}
```

But it can be slower in some cases, as you must iterate over all the selected nodes again and again.

While with a function you can build an internal cache.

For low number of nodes it can be the same, but after a while it can be different..

**Comment by egonelbre** [comment]
You can also have it as:

```
type PartialSelection struct {
    Selected []*SelectedNodes
    SomeCache map[string]bool
}

type NodeFilter interface {
   Match(partial *PartialSelection, node *SelectedNode) bool 
}
```

or

```
type PartialSelection struct {
    Selected []*SelectedNodes
    SomeCache map[string]bool
}

type NodeFilter interface {
   Match(partial *PartialSelection, node *SelectedNode) bool
   // for those that need to update the cache
   Update(partial *PartialSelection, node *SelectedNode)
}
```

**Comment by elek** [comment]
Yes, I can, but I liked the simplicity of the previous approaches.

Meantime I started to wondering if we need one interface for all.

Now I am planning to use sg. like

```
type Placement struct {
       ID                  storj.PlacementConstraint
       NodeFilter          nodeselection.NodeFilter
       Labels              map[string]string
       NodeSelectionFilter NodeSelectionFilter
}

type NodeSelectionFilter func([]nodeselection.SelectedNode) []nodeselection.SelectedNode
```

Because `nodeselection.NodeFilter` results still can be cached for each Node, but not the NodeSelectionFilter...

So this conversation mainly applies to the NodeSelectionFilter which can be stateful (returns a new function) or just stateless as here.

I think we prefer stateless unless we have good performance reasons (--> we need to do benchmarks)

**Comment by elek** [comment]
Better link to the full chain: https://review.dev.storj.io/c/storj/storj/+/11931/5

**Comment by elek** [comment]
Closing this one. I created separated issues for the remaining part of the chain...
