### ISSUE TITLE
Repair queue statistic

### ISSUE THREAD

**Issue by elek** [storj/storj#6530]
The goal here is to have statistic about the repair queue and create alerts.

![Image](https://github.com/storj/storj/assets/170549/452c0ce6-28e1-418b-876c-d4a0e0520b5d)

**Comment by shaupt131** [comment]
Related to https://storj.slack.com/archives/C065MGA32A3

**Comment by iglesiasbrandon** [comment]
closing this issue since its been deployed tp production. @elek @shaupt131
