### ISSUE TITLE
API generator: allow to customize where middlewares are injected

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#6542]
## Motivation / Why?

We have enhanced the [API generator to allow to injection of custom middleware] (https://github.com/storj/storj/issues/6491).

We want to be able to configure if the middleware is called before anything, after query and path parameters validation, or after the business logic.

## What needs to be done?

Enhance the middleware injection to choose where the custom logic is injected inside of the endpoint handlers.

## Acceptance criteria

- Enhance the middleware configuration per group API to specify where the middleware logic is injected. Before anything, after the query and path parameter validations, to after the business logic is executed.
- Modify the API generator to consider this new configuration and inject the middleware logic in the specified place.

**Comment by ifraixedes** [comment]
I was thinking of executing the new satellite admin Web App authorization before the parameter initialization because it doesn't involve the DB, however, it's fine to do it after it.

I will move this issue to TODO and I will send a commit to change the position of the inject.

**Comment by shaupt131** [comment]
We don't have a use case for this enhancement right now, so we will close this ticket.
