### ISSUE TITLE
Investigate missed billing data on US1

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6564]
### Background:

https://storj.slack.com/archives/C047KSGPPQ8/p1701201744681799

### Acceptance Criteria:

- Complete investigation and report out findings.  
   - If easy (1 or 2 effort) implement the fix.
   - If not, create follow-up ticket(s) and post here.

**Comment by cam-a** [comment]
https://storj.slack.com/archives/C047KSGPPQ8/p1702927638213669

**Comment by mniewrzal** [comment]
I think I can confirm its some tally issue. Looking at the same metric but collected with ranged loop there is no such drop in segments and total bytes stored
![image](https://github.com/storj/storj/assets/7313031/5ac7cb57-9244-4ce8-afbe-e7da9e739e14)
https://thanos.storj.rodeo/d/0IrtEUzIk/satellite-statistics?orgId=1&from=1699833600000&to=1701647999000

**Comment by mniewrzal** [comment]
Fro graphs its looks that problem started to appear in November and its common for all prod satellites.

**Comment by shaupt131** [comment]
@mniewrzal Is there any way to confirm if this instance reported by Colby over the break is related?  And if so, will it be resolved by this fix?  https://storj.slack.com/archives/C0210TV0V0X/p1703826354156909

**Comment by mniewrzal** [comment]
> Is there any way to confirm if this instance reported by Colby over the break is related? 
I cannot confirm that for 100% but it looks that reported problem is at least partially related to this issue.

> And if so, will it be resolved by this fix?
Yes, I think it will help with this problem but it will fix only further data. It won't fix historical data.
