### ISSUE TITLE
Check how old uplink works with versioned bucket

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#6565]
New versioning support will be initially accessible only via gateway but we need to check if older uplink at least won't break with bucket that contains multiple versions.

Acceptance Criteria:
* write basic automatic test to verify that versioned bucket won't break older uplink

**Comment by shaupt131** [comment]
@mniewrzal I believe with the change above, we can now close this issue.  Correct?

**Comment by mniewrzal** [comment]
Yes. Let's close it.
