### ISSUE TITLE
Billing: Improve ordering of invoice items

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6573]
Invoice items don't appear to be added to Stripe invoices in a guaranteed order. This means that invoice items are not grouped by project. Each project has three invoice items associated with it. So if I have 10 projects, I may have to scroll around between 30 invoice items in order to find the 3 for a specific project.

### AC
* invoice items on Stripe invoice are grouped by project
  * so for any project `X`, `X Storage`, `X Egress`, and `X Segment` all appear next to each other on the Stripe invoice

**Comment by VitaliiShpital** [comment]
we have to rework our invoice items generation approach to accomplish this. Basically, we have to iterate over customers instead of project records, right? I mean, there is no way to fix ordering if we don't have all the customer's project records at a time, right?
