### ISSUE TITLE
Execute object versioning test plan and Ceph/Minio test suites

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6579]
Link to the test plan: [link](https://github.com/storj/storj/blob/720b75ad7356ad31e7170b96d2406301c046b772/docs/testplan/object-versioning-testplan.md)

**Comment by shaupt131** [comment]
QA still underway.  Will carry over into sprint 30.

**Comment by shaupt131** [comment]
Documenting known problems on the #object-versioning slack channel canvas: https://storj.slack.com/canvas/C03AHET16CR

**Comment by iglesiasbrandon** [comment]
how can I see what tests have been executed? @ihaid, i see the canvas has issues that have been found but i dont know whats been tested from the plan.

**Comment by ihaid** [comment]
@iglesiasbrandon previous iteration was more like smoke tests because not everything was finished/merged. I executed all test from the test plan that we have and run the test suites from splunk locally. I have the reports locally and important things I added to the canvas. I can generate some kind of report next time.

**Comment by ihaid** [comment]
| Test Scenario | Test Case                               | Description                                                                                                                                                                                     | Result                        |   
|---------------|-----------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------|
| Copy          | To a bucket that has versioning enabled | When object with same name uploaded to a bucket we should create new unique version of the object                                                                                               | PASS (we don't have latest)   |  
|               | To a bucket that has version disabled   | Latest version of the object is overwritten by the new object, new object has a version ID of null                                                                                              | PASS                          |
|               | Copy object by version ID               | Should support copying a specific version, should copy the latest version of an object if not specified                                                                                         | FAIL                          |
|               | Multipart                               | Multipart upload with versioning enabled                                                                                                                                                        | PASS                          |
|               | Expiration                              | Create object with expiration in versioned bucket, delete marker should be applied to it                                                                                                        | FAIL (we do hard delete)      |
|               | From versioned to unversioned\suspended |                                                                                                                                                                                                 | PASS                          |
|               | From unversioned\suspended to versioned |                                                                                                                                                                                                 | PASS                          |
| Move          | To a bucket that has versioning enabled | Should add one version to it                                                                                                                                                                    | PASS                          | 
|               | To a bucket that has version disabled   | Regular move                                                                                                                                                                                    | PASS                          |
| Delete        | Delete one from many versions           | Create 3 versions of the same file and delete the middle one indicating the version id                                                                                                          | PASS                          |
|               | All versions                            | Unconditionally deletes all versions of an object                                                                                                                                               | PASS                          |
|               | Delete bucket                           | Force delete bucket with files that has versioning. We should keep all versions of the files unless manually deleted                                                                            | PASS                          |
|               | Delete marker                           | Create delete marker by delete specific version and then delete the delete marker. All versions of the file should kept, delete marker should be deleted                                        | PASS                          |
| Restore       | Delete and restore                      | Delete version of the file and restore from that version                                                                                                                                        | PASS                          |
|               | Restore                                 | Create few versions of the file and restore from latest to older version                                                                                                                        | PASS                          |
| Create        | Create new bucket                       | Versioning should be inherited from project level                                                                                                                                               | PASS                          |
| Suspend       | Suspend versioning                      | Suspend versioning on a bucket that had versioning enabled. 3 versions of a file exists. Try to upload the same file again. -> the newest file gets overriden. The older 2 versions stay intact | PASS                          |
| Update        | Update metadata                         | Metadata update should not create new version. Takes the version as input but does not use it. Only updates the metadata for the highest committed object version.                              |                               |
| List          | all versions                            | Unconditionally returns all object versions. Listing all versions should include delete markers. Versions come out created last to first                                                        | FAIL (listing order is wrong) |
| UI            | UI                                      | UI should always show the latest version of each object                                                                                                                                         | PASS                          |
| Buckets       | Old                                     | Old buckets created before the feature should be in "unsupported" state                                                                                                                         | PASS                          |
|               | Enable versioning after upload          | Upload obj to a bucket with versioning disabled and then enable versioning. Check version of the object                                                                                         | PASS                          |
