### ISSUE TITLE
API generator: support embed fields with JSON tags

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#6581]
## Motivation / Why?

Sometimes we want to specify base structs that are used by other structs that we return as a response for not having to duplicate them.

For example:

```go
type User struct {
  ID        uuid.UUID   `json:"id"`
  Name string           `json:"name"`

  ProjectUsage []UserProjectUsage   `json:"projectUsage"`
}

type UserProjectUsage struct {
  ID    uuid.UUID `json:"id"`
  ProjectUsage
}

type Project struct {
  ID                  uuid.UUID `json:"id"`
  Description string          `json:"description"`

  ProjectUsage
}

type ProjectUsage struct {
  Storage int64 `json:"storage"
}
```

The API generator panics because `ProjectUsage` field in `UserProjectUsage` and `Project` struct types don't have a JSON tag.

If we add a tag to those the fields don't get merged into the parent struct creating a nested field, which is what we don't want. 

## What needs to be done?

Modify the API generator to support embedded fields of struct types whose all fields have struct tags, without requiring a JSON tag.

## Acceptance criteria

- Modify the API generator to support embedded struct fields with all their fields having a JSON tag, without requiring a JSON tag.

**Comment by ifraixedes** [comment]
@egonelbre Some people think we don't need this and should avoid allowing embedded structs without a JSON tab.

I'm fine with that, but I'd like your input before closing it. For now, I leave it open and keep it in the sprint, but added the `blocked` label.

**Comment by egonelbre** [comment]
Generally, I'm fine with either way. Although, it may cut down on conversion funcs we need to write.

**Comment by ifraixedes** [comment]
Yeah, I found it that useful for that without having to nest them in a sub-level.
I'll keep for this sprint and if I don't get into it, I will move it to the backlog.

**Comment by ifraixedes** [comment]
Commit ready for reviews https://review.dev.storj.io/c/storj/storj/+/11995

**Comment by ifraixedes** [comment]
Deployed in [v1.95.1](https://github.com/storj/storj/releases/tag/v1.95.1)
