### ISSUE TITLE
Satellite UI: Allow user to save file access credentials in local storage

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6582]
The end goal of this task is to enable users to save access credentials in local storage so that the app can be refreshed without the user needing to re-enter encryption passphrase.

### AC:
* when doing an operation that involves getting the encryption passphrase from the user, add a checkbox which allows the user to choose to "save my encryption credentials locally so that I don't need to enter them again in this session"
  * if checked, store the access or passphrase in local storage (with some expiration)
* on app load, if encryption credentials are accessible in localstorage, autoload them so that user does not need to enter a passphrase
* on logout, these credentials should be cleared from localstorage

**Comment by VitaliiShpital** [comment]
After discussing with @kaloyan-raev, we decided not to implement this, at least for now. We don't want to store any sensitive data in browser local storage. Instead, we may want to rework the entire approach for users who don't care about encryption and an additional layer of security.

**Comment by kaloyan-raev** [comment]
Random article on why we should not use local storage for any sensitive data: https://www.horangi.com/blog/misuse-of-local-storage
