### ISSUE TITLE
Move latest playwright tests to the storj/storj repo

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6597]
In order to keep UI tests up to date and set the foundation for running playwright tests for CI/CD, we should move the latest playwright tests to the storj/storj repo. 

## AC:
* Playwright tests in storj/storj ([link](https://github.com/storj/storj/tree/main/testsuite/playwright-ui)) are updated with the latest tests from storj/qa-storj ([link](https://github.com/storj/qa-storj/tree/main/uitests))
* Tests can be executed with `npm run test` from the playwright ui folder in storj/storj
  * Tests **do not** need to pass for this issue to be completed - we will have a separate task to update the tests
  * A lot of the work has already been done in this [draft PR](https://github.com/storj/storj/pull/6014/files) - feel free to pull the necessary changes from that branch, but do not worry about CI/Jenkins-related things 
* README added to testsuite/playwright-ui with instructions for installation and local execution of tests

**Comment by NiaStorj** [comment]
@wilfred-asomanii please add effort points
