### ISSUE TITLE
Vuetify: update Billing History data table

### ISSUE THREAD

**Issue by boshevski** [storj/storj#6600]
### Problem
A couple problems with https://us1.storj.io/v2/account/billing?tab=billing-history:
- Changing "Items Per Page" doesn't do anything
- Sort order gets whacky when changing page (bug seems to exist in v1)

### Solution

- Update the data-table to be same as the others, ie. the Storj transactions table in the billing.
- Billing History table is the only different component. It also has issues with pagination, and there is no search, or sorting.

**Comment by VitaliiShpital** [comment]
after fix applied

https://github.com/storj/storj/assets/46756926/5631adfa-5582-4d03-a754-7689997e7e60
