### ISSUE TITLE
migrate: v142: migrate: ERROR

### ISSUE THREAD

**Issue by ohari5336** [storj/storj#6613]
$ satellite run --identity-dir ./satellite/ --config-dir ./config/ migration 

2023-12-20T10:45:48+05:30	INFO	Configuration loaded	{"Location": "/Users/hariom/Downloads/builds/config/config.yaml"}
2023-12-20T10:45:48+05:30	INFO	Anonymized tracing enabled
Error: Error creating tables for master database on satellite: migrate: v142: migrate: ERROR: unimplemented: cannot drop UNIQUE constraint "bucket_metainfos_name_project_id_key" using ALTER TABLE DROP CONSTRAINT, use DROP INDEX CASCADE instead (SQLSTATE 0A000)
	storj.io/storj/private/migrate.(*Migration).Run:209
	storj.io/storj/satellite/satellitedb.(*satelliteDB).MigrateToLatest:80
	storj.io/storj/satellite/satellitedb.(*satelliteDBCollection).MigrateToLatest:325
	main.cmdMigrationRun:593
	storj.io/private/process.cleanup.func1.4:393
	storj.io/private/process.cleanup.func1:411
	github.com/spf13/cobra.(*Command).execute:852
	github.com/spf13/cobra.(*Command).ExecuteC:960
	github.com/spf13/cobra.(*Command).Execute:897
	storj.io/private/process.ExecWithCustomOptions:112
	storj.io/private/process.ExecWithCustomConfigAndLogger:77
	storj.io/private/process.ExecWithCustomConfig:72
	storj.io/private/process.ExecCustomDebug:67
	main.main:1149
	runtime.main:267

**Comment by mniewrzal** [comment]
Could you provide what DB you are using and what version?

**Comment by ohari5336** [comment]
<img width="667" alt="Screenshot 2023-12-20 at 3 01 50 PM" src="https://github.com/storj/storj/assets/22674877/91591c88-6e64-467d-aa00-1cd85fc4292b">
<img width="1153" alt="Screenshot 2023-12-20 at 3 02 05 PM" src="https://github.com/storj/storj/assets/22674877/4984c8c7-6f10-4f82-ae31-4043af908ae4">

**Comment by ohari5336** [comment]
i fixed the issue temporarily

**Comment by mniewrzal** [comment]
Could you also paste `database` url from your config.yaml?

**Comment by ohari5336** [comment]
database: postgresql://root@localhost:26257/postgres?sslmode=disable
metainfo.database-url: postgresql://root@localhost:26257/defaultdb?sslmode=disable

**Comment by mniewrzal** [comment]
Thanks. If you change `postgresql://` into `cockroach://` issue should be resolved. In some cases we have different handling for cockraoch DB than postgres.

**Comment by ohari5336** [comment]
ok thanks
