### ISSUE TITLE
Update passwords to follow best practices (such as NIST guidelines)

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6629]
See https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html and https://pages.nist.gov/800-63-3/sp800-63b.html

**Comment by ferristocrat** [comment]
- update allowed "characters" to be in line with NIST standards
- Possibly update helper to reflect the above (and possible force the password to be at least "Strong"

**Comment by ferristocrat** [comment]
Perhaps also consider a third party (open source or not) identify provider which will likely provide front end hooks that incorporate all these standards by default.

**Comment by ferristocrat** [comment]
Also think through adding backend password rules/checks/limits/etc as part of this

**Comment by NiaStorj** [comment]
12/19/24:

Already following the NIST guidelines
