### ISSUE TITLE
Navigation from projects page to project settings broken

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6636]
### Summary
When I navigate from the My Projects page directly to project settings (either from the card view or the table view) it doesn't take me to the project settings, but rather the dashboard/overview
![image](https://github.com/storj/storj/assets/7063002/8a475d7b-7dfe-47ad-b57e-60d5a3a9d717)

**Comment by wilfred-asomanii** [comment]
This has been fixed in 87ab8dc4
