### ISSUE TITLE
Satellite admin web App: Hide all the UI components that show mock data

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#6645]
## Motivation / Why?

We want to hide all the UI components that show mock data until we have the API endpoints that allow us to show real data.

## What needs to be done?

Hook the configuration API endpoint into the Web App and modify each view/component to hide or show depending on the state of their associated feature flag returned by the endpoint.

## Acceptance criteria

- Request the configuration API endpoint and store the configuration in the store.
- Parametrize each view/component according to their associated feature flag to show or hide it.

---

Depends on https://github.com/storj/storj/issues/6644

**Comment by ifraixedes** [comment]
Commit ready for reviews https://review.dev.storj.io/c/storj/storj/+/12126

**Comment by ifraixedes** [comment]
Merged

**Comment by ifraixedes** [comment]
Reopening because it's merged, but it isn't deployed yet. Expected for v 1.97.x

**Comment by shaupt131** [comment]
@ifraixedes to confirm if this was released on Monday
