### ISSUE TITLE
Introduce Name for Placements

### ISSUE THREAD

**Issue by elek** [storj/storj#6655]
see https://review.dev.storj.io/c/storj/storj/+/11966

**Comment by iglesiasbrandon** [comment]
will this change also add human-readable names to the placements we already have defined?

**Comment by iglesiasbrandon** [comment]
@elek poke ^

**Comment by elek** [comment]
What do you mean on human readable names? I am aware of the AWS region like identifiers. They can be used in the future, but the configuration is different (it's a real name, not an annotation hack any more).

**Comment by onionjake** [comment]
Brandon might be referring to this: https://docs.google.com/spreadsheets/d/1DrpdbNkSdzIrmGbP3WQn92HGqVnCTNRokq3UBql3Kcw/edit#gid=0

It looks like this is still what we called 'short code' in that spreadsheet, not what we called 'customer facing name'.

**Comment by elek** [comment]
Ah, I see. In this case the answer is no. This one is not included in the change. 

But now we have a yaml structure, it's very easy to include a description field, if required.
