### ISSUE TITLE
Disable durabilty observer for countries

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6659]
We have lot of OOM problem with ranged loop. We are planning to use the same indexing in all durability loops, but until that we can disable the country based durability loop, as it's not very important: we don't expect any internet breakdown in any countries...

**Comment by shaupt131** [comment]
https://review.dev.storj.io/c/storj/storj/+/12040

**Comment by iglesiasbrandon** [comment]
I am going to close this issue since its been deployed into production. @elek @shaupt131
