### ISSUE TITLE
V2: Stripe user not created when user prompted for package

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6671]
The stripe user is created via the /account/setup endpoint. However, this endpoint is not called early enough in the situation that a user signs up with a partner associated with a package plan. In this case, the user is prompted to sign up for a pro account during onboarding, but before the stripe user exists, resulting in an error:

![Image](https://github.com/storj/storj/assets/1323312/839b462d-112f-42aa-bda3-85c74d94d7a6)

### AC:
* stripe user is created before user is prompted to select a package plan during onboarding
    * option 1: move the call to /account/setup to the beginning of onboarding
    * option 2: do what /account/setup does as part of account activation automatically, so that an additional endpoint for this purpose is not needed

**Comment by wilfred-asomanii** [comment]
v1.96.6  20d389b
