### ISSUE TITLE
Test around geofencing, placement constraints, object versioning to make sure we’re not overwriting any other unrelated defaults by mistake.

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6693]
@littleskunk to add a description

Sorry, it took me a bit longer to come up with a good description.

By now we have 3 admin UIs. That means if one of the admin UIs doesn't work we can still perform the task with one of the other admin UIs and fix the bug later. -> I am not worried about any usability bugs. We can deploy to production and wait for feedback.

I am worried about consistency bugs. Some fields in our DB are more important than others and shouldn't be changed by accident. -> We need automated tests that:
1. Set soc2 geofencing on the bucket level, project level and user level. Perform all possible modifications and verify that geofencing hasn't been overwritten. If we ever overwrite it in production without noticing it that could be game-ending. Please better do one check too many than missing one.
2. Same test for any other important field. Project limits, user agent, rate limits. If we overwrite one of these values it wouldn't be game-ending but we might lose one of our bigger customers.  Please better do one check too many than missing one.

**Comment by shaupt131** [comment]
@littleskunk or @ihaid is this issue still relevant?  I believe we tested for this, correct?

**Comment by ihaid** [comment]
> @littleskunk or @ihaid is this issue still relevant? I believe we tested for this, correct?

Yes we do.
