### ISSUE TITLE
Satellite UI/invoices: CO2 savings info

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6694]
https://github.com/storj/experiments/blob/main/carbon-assessment/green.go

### AC:
* remove segments card
* add CO2 savings info to project dashboard + tooltips
* add CO2 savings info to invoice
  * if possible, add some sort of emphasis (e.g. underline, bold) to the information on the invoice

### Code:
https://storj.github.io/vuetify-storj/

### Preview:
![Image](https://github.com/storj/storj/assets/3217669/e0241b2c-1ada-44f8-a0bd-c66b9303d757)

### Part of invoice example: 
<img width="1357" alt="invoice" src="https://github.com/storj/storj/assets/3217669/b45f18e4-d026-4397-80ab-485fe5cff3d9">

### AC:
* move something like the experiment script above to the backend (or storj/common) so that we can calculate carbon savings from the console code
* expose a carbon savings endpoint to the frontend
* update UI to display carbon savings on dashboard
* update invoice to display carbon savings at bottom of invoice

**Comment by onionjake** [comment]
@VitaliiShpital Do you have any screenshots of what this will look like?

**Comment by VitaliiShpital** [comment]
@onionjake 
![image](https://github.com/storj/storj/assets/46756926/3938d3d6-5c03-4a01-8c2e-2d07ab8904f6)
![image](https://github.com/storj/storj/assets/46756926/b3167fe5-c695-4158-a781-cd6d389c19f3)

**Comment by boshevski** [comment]
working on putting this information in a nice dialog (modal) instead of a tooltip, thanks Vitalii 
![image](https://github.com/storj/storj/assets/3217669/52c88547-c227-4d1e-8a8c-6c8e55d0a75d)

**Comment by boshevski** [comment]
Updated design for a dialog with more information replacing the tooltips.

<img width="1722" alt="sustainability" src="https://github.com/storj/storj/assets/3217669/e7bdfbc0-85f3-4c34-a6cf-4d9c6d97bdde">
