### ISSUE TITLE
[storagenode] Avoid crashing the node running below the minimum allowed version

### ISSUE THREAD

**Issue by profclems** [storj/storj#6700]
The latest version control is more strict about allowing versions below the minimum version to run. Before this fix (https://github.com/storj/storj/issues/5673), the minimum version returned was always the old semver, which is 1.24.0. So always, the nodes will never be considered to be running a version below the actual minimum (unless they were running below 1.24.0) because it was checked against the old format.

Now that is fixed, nodes running below the minimum version set on the version control server will be crashed. Instead of crashing, we should just log an error that they're running below the minimum and continue.

Discussed here https://storj.slack.com/archives/CE7F4G21Z/p1705520390564439?thread_ts=1705508535.134369&cid=CE7F4G21Z

**Comment by iglesiasbrandon** [comment]
moving to deployed.
