### ISSUE TITLE
Content security policy error log in UI

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6701]
![image](https://github.com/storj/storj/assets/1323312/da58eb2a-ed54-4b39-959a-ef2fc5959a41)

This issue appears in unclear conditions. See conversation below for details.

### AC:
*  there  are no content security policy issues in the UI in any browser

**Comment by VitaliiShpital** [comment]
CSP error is thrown only on auth pages i.e. login, signup or forgot-password. Also, this error is thrown on v1 app auth pages too. I suspect it's related to hcaptcha

**Comment by mobyvb** [comment]
@VitaliiShpital https://satellite.qa.storj.io/login does not show this error but https://satellite.qa.storj.io/v2/login does
@andriikotko also mentioned that this error was not present in previous releases

**Comment by mobyvb** [comment]
Commenting here  that this behavior is not consistent. Vitalii was right that in certain situations, this issue is present in both production and QA, on both V1 and V2. 

Vitalii tested with Chrome on Mac, and saw this issue in QA V1 and V2, as well as EU1 V1 and V2
Andrii also tested with Chrome on Mac, and saw the issue only in QA V2.
I tested with Brave on Linux and  saw the issue only in QA V2
I also tested with Firefox on Linux and saw the issue in QA V1 and V2, as well as US1 V1 and V2

For now, I am going to remove this from our "required tasks to turn on V2 as default", because it does not appear to break the app. We  should still fix the issue, but it is not a blocker.

**Comment by mobyvb** [comment]
more useful screenshots from Andrii:

Firefox QA V2:

![Image](https://github.com/storj/storj/assets/1323312/5f8ad9c7-4520-4d9f-8c34-d5e85876dbe5)

Firefox QA V1 and prod:


![Image](https://github.com/storj/storj/assets/1323312/3fde93bd-e6c0-483e-b4ef-9b03a7746546)

Safari QA V2:

![Image](https://github.com/storj/storj/assets/1323312/6ea416d8-5059-486f-8a17-55ff4e2427f4)

**Comment by VitaliiShpital** [comment]
After investigation I realised that this is related to hcaptcha. If hcaptcha is disabled then errors go away. I tried to update dependency and play with types/sizes but it didn't help.

Also, we have different errors. Guys above provided error messages related to style-src directive. Here is my error in prod app (EU1)
![Image](https://github.com/storj/storj/assets/46756926/c8c4539d-ee2a-4b6e-8dec-9fce9d0bba3a)

**Comment by VitaliiShpital** [comment]
official hcaptcha [docs](https://docs.hcaptcha.com/#content-security-policy-settings) have this statement which is a bit suspicious

```
If you are an enterprise customer and would like to enable additional verification to be performed, you can optionally choose the following CSP strategy:

unsafe-eval and unsafe-inline should include https://hcaptcha.com, https://*.hcaptcha.com
```

**Comment by VitaliiShpital** [comment]
ok, I figured out `style-src` violation issue. It was presented by new app loader styles
![Image](https://github.com/storj/storj/assets/46756926/bd72f3ca-0c5e-4601-acd5-29e827b1888f)

CC @wilfred-asomanii
