### ISSUE TITLE
Satellite UI: multiple-select updates for file browser, team, and access pages

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6715]
### AC:
* file browser:
  * multiple-select + delete file has a confirmation dialog, like deleting from preview
  * make sure the confirmation dialog for multiple items is using plural language i.e. files, folders.
* team page:
  * "remove user" does not appear next to search bar when invites/users are selected
  * instead, match the snackbar delete functionality on the file browser
  * make sure there is a confirmation before delete happens
* access page:
  * add multiple select capabilities to the access table
  * support deleting multiple accesses at once, matching the delete snackbar from the filebrowser
  * make sure there is a confirmation before delete happens

**Comment by wilfred-asomanii** [comment]
v1.97.2  7534277
