### ISSUE TITLE
Onboarding Stepper on Dashboard

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6721]
### Objective
Enhance the onboarding experience for new Storj users, particularly those integrating with third-party tools like iX Systems TrueNAS. The aim is to simplify the process of setting up and retrieving S3 credentials, ensuring a smooth, guided journey through the necessary steps.

### Problem/Pain Point
New users encounter difficulties during the onboarding phase, often getting lost in the complexities of Storj, especially when integrating with third-party tools. The current process can be overwhelming, leading to a suboptimal user experience and user drop off.

### Propose a Solution

Implement an onboarding stepper on the dashboard that:
1. Guides Users Through Default Steps:
   - As a user, I want a straightforward, guided process for onboarding, ensuring I can quickly start leveraging Storj with minimal effort.
2. Caters to iX Systems TrueNAS Users:
   - As an iX Systems TrueNAS user, I want clear, step-by-step guidance to obtain the necessary S3 credentials, ensuring a hassle-free setup for my TrueNAS integration with Storj.

### Design
Figma Designs: https://www.figma.com/file/HlmasFJNHxs2lzGerq3WYH/Satellite-GUI?type=design&node-id=27285%3A30813&mode=design&t=9TssDEU0AgPgkM2y-1 
| Description | Design |
| --- | --- |
| iX Systems specific flow | ![image](https://github.com/storj/storj/assets/7063002/22a4773b-662b-4f3f-93f3-c150b86d6edd) |
| Default flow | ![image](https://github.com/storj/storj/assets/7063002/b35e2705-ad5c-40d3-9e63-cfc3c7980f48) |

### Technical Decisions/Discussion
**Database changes**
- We have existing column in the database for "onboarding step" that doesn't seem to be used in v2
   - Confirm this isn't being used and repurpose it for this flow
   - This should include onboarding steps prior to the stepper (setup user info, prompt for package plan) as well as the onboarding steps in the stepper
- What about existing users? By default we should just not show this stepper. There's another column called something like "onboarding end" and if it's true we could just not show the flow 
- Assumption is that the onboarding is tied to a specific user. In the case that a new user was invited to a project, and doesn't create their own, but goes straight to a shared project -- do they see this stepper? The current assumption and what will be implemented is YES.

**Comment by ferristocrat** [comment]
Open questions:
1. Encryption passphrase - if there is no "browser remembered" passphrase do we show this as "incomplete"? Or should it be "complete" if the user has EVER created an encryption passphrase...
2. Should it remain after complete - assume yes for now. Consider hiding it... consider allowing users to hide/dismiss it
3. You could create S3 credentials before step 2 or 3... do we need to do anything in this scenario?

**Comment by boshevski** [comment]
1. The initial encryption passphrase setup counts this as complete. 
2. Should remain complete, yes. We can add "dismiss" option for the whole onboarding after it's done.
3. Passphrase is needed for S3 credentials, also a created bucket to select during access creation flow. 
4. Yes, that's better. We can open the dialog for S3 immediately in the same page.
5. Set a passphrase opens the dialog for new passphrase we already have.
6. Create a bucket can open the new bucket dialog in the same page.
7. Yes.

**Comment by wilfred-asomanii** [comment]
v1.98.2  7534277
