### ISSUE TITLE
Execute test plan against new admin UI

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6737]
### Background:
We need to make sure the new satellite admin tool is ready for use in production.  It is currently deployed to the QA satellite, and we have an existing test plan that we can use from the previous admin tool we were developing.

### Acceptance Criteria:

- Test plan has been executed
- Concerns or failures have been documented and shared with the team.
   - Team will review and prioritize.

**Comment by shaupt131** [comment]
Admin UI test plan: https://github.com/storj/qa-storj/issues/583

**Comment by jenlij** [comment]
done
