### ISSUE TITLE
Satellite UI: Improve validation for invite emails

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#6743]
Reproduction steps:
- invite user with ',' in email address
- try to delete it
Actual result: impossible to delete user with coma in the email - `{"error":"validation: There are no team members with the email 'ansd@sdf.sdf'. Please try again."}`
<img width="1231" alt="Screenshot 2024-01-31 at 19 33 43" src="https://github.com/storj/storj/assets/14928042/f36cd98c-71e3-4ac6-815c-b7e6868035bd">

### AC:
* invite email address field has proper validation, preventing emails with invalid characters (like `,`), on both frontend and backend
* if an invite was previously sent to a user with an invalid email address (e.g. containing `,`), it should be possible to delete this invitation

**Comment by wilfred-asomanii** [comment]
For the second AC, it has been determined that there are no invited emails in production that have `,` in them, so it may not be worth the effort to support deleting.

**Comment by wilfred-asomanii** [comment]
v1.98.2  39ad43b
