### ISSUE TITLE
Bucket name. Make validation the same as in the backend

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#6744]
for not it's possible to create name with '.' (period) or '-' (hyphen) in the end - but it's rejected by backend 
(in the middle of bucket name - it's ok)
<img width="1587" alt="Screenshot 2024-01-31 at 19 51 49" src="https://github.com/storj/storj/assets/14928042/a735ad21-a8d2-4564-afb3-5be6e4328adc">

**Comment by mobyvb** [comment]
@andriikotko I believe this is a duplicate of https://github.com/storj/storj/issues/6704
please confirm
