### ISSUE TITLE
Satellite UI: onboarding use case changes

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6746]
If user selects "other" during onboarding for "Use Case", we should collect an additional optional text field where user can specify their use case.

This data should be sent to Segment along with the other onboarding info.

Personal: 

![Image](https://github.com/storj/storj/assets/1323312/1ff6426e-bf7b-40ae-b209-30c27f8ce873)

Business: 

![Image](https://github.com/storj/storj/assets/1323312/53248962-3a90-4f2a-92c5-bac65354ed56)

### AC:
* when a new user selects a use case of "other" during onboarding:
    * allow user to enter their use case in a new text field
    * send this new field to Segment with the other onboarding data

**Comment by NiaStorj** [comment]
@boshevski can we get a design for the text box mentioned above.

**Comment by ferristocrat** [comment]
> @boshevski can we get a design for the text box mentioned above.

See vuetify repo for designs

**Comment by boshevski** [comment]
Design:
<img width="506" alt="other-use-case" src="https://github.com/user-attachments/assets/440d3466-1220-40c3-95ea-6388f061f0df">

Code is in the vuetify repo.
We display this input field only if user clicks on the "Other" option in the Use Case select field. 
It would be great if we can do autofocus on the Specify Other Use Case field once it's shown.

**Comment by boshevski** [comment]
Here is the design for the Other use case in the Business setup.
<img width="738" alt="other-business" src="https://github.com/user-attachments/assets/5dd13df0-6756-41f0-aa81-34e8c2cc6cc0">
