### ISSUE TITLE
Update copy on sign up page(s)

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6750]
### Summary

This update aims to align the sign up pages with marketing's latest strategies, focusing on our target audience seeking S3 compatible storage solutions. The update involves a simplified version of the "default" sign up page as well as the partner specific sign up page.

### Acceptance Criteria
- Default sign up page updated to match the messaging for desktop and mobile (should be done already)
- Partner specific page (and template) updated to match the logo + messaging for desktop and mobile
- "Generic partner view" added to handle /signup?partner=xyz for partners on the [partners page](https://www.storj.io/partners/our-partners); display the logo next to Storj logo and partner name in heading. Config for these partners should be added to branding repository
- A satellite config is added for "schedule meeting link". When a user clicks "Schedule a meeting" they are taken to the link [defined here](https://github.com/storj/storj/blob/6a527018bcbcafe4f360d9457713f6d0424dd947/web/satellite/src/views/Signup.vue#L243). This occurrence of the link should be replaced with the config value. If no schedule meeting link is configured, omit this portion of the signup text
- Screenshots are from V1 UI - we are not matching it visually; keep the V2 styling, and only update text and logos

### Designs
Figma link (source of truth): https://www.figma.com/file/D6Jys8Q9Oke2M4GBBp8xdP/Storj-Website-2023?type=design&node-id=889-2785&mode=design&t=l88rGDK8TMMCYMSl-0

Screenshots for reference:
| Description | Screen |
| --- | --- |
| Default view - Desktop | ![Image](https://github.com/storj/storj/assets/7063002/2f38172c-31c8-480e-8940-affb58ce892f) |
| Default view - Mobile | ![Image](https://github.com/storj/storj/assets/7063002/6abcf003-705f-47a1-8a35-a868f64da8d0) |
| Partner specific specific view (generic) | ![Image](https://github.com/storj/storj/assets/7063002/cc1bf8a7-2873-4430-9b71-071c3611e799) |
| Partner specific view (example) | ![Image](https://github.com/storj/storj/assets/7063002/f47846ff-706c-441a-8a6b-104f7cde6ac2) |

**Comment by ferristocrat** [comment]
@boshevski - can you review these designs from DJ, with updates marketing wants to make? The only divergence that's obvious to me is the Satellite selection that I know we made more prominent because users weren't even noticing it before and we wanted to ensure they are choosing the right satellite...

**Comment by mobyvb** [comment]
Some  questions:
* if we don't have a partner logo for a  particular partner (or a partner configuration), do we still show the generic partner page?
* "generic" partners might not have a configuration or logo - do we still show the generic partner page in this case? Or is it assumed that we have a configuration for every "generic" partner?
* we need links for "schedule a meeting"

**Comment by boshevski** [comment]
If we don't have logo or custom config for copy, we should default (generic) partner page.
The screenshots are using the old style, so definitely we don't want to add the footer or anything else, just the copy update for now. 
For partners that have specific signup copy, we don't change the agreed copy. The screenshots were for a default partner page for everyone else who doesn't have custom copy and/or logo.

**Comment by boshevski** [comment]
I updated the designs for the signup page to include the new default sign up copy, schedule a meeting link, and updated styling. What's left is the partner's configurations.

**Comment by mobyvb** [comment]
What does "schedule a meeting" link to @boshevski ?

**Comment by boshevski** [comment]
It's already linked in the updated signup page.

**Comment by mobyvb** [comment]
Thanks @boshevski. I updated acceptance criteria of this task to include adding a satellite configuration for the schedule a meeting link, and remove the hardcoded occurrence of it - that way, non-production and private satellites do not have this link on the signup page
