### ISSUE TITLE
Add "Congratulations ..." banner if user add credit card on Billing page

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#6752]
For now if user add credit card from Billing page - their account is updated to Pro  but they don't see Congratulations banner

https://github.com/storj/storj/assets/14928042/b5148061-021e-4619-b07c-16bad7741c65

### AC:
* ensure that [success step] is displayed upon successfully upgrading to pro, for both CC and token

**Comment by andriikotko** [comment]
NOTE: the same behaviour with adding Storj tokens

**Comment by boshevski** [comment]
Here is the success step: https://github.com/storj/storj/blob/main/web/satellite/src/components/dialogs/upgradeAccountFlow/SuccessStep.vue

**Comment by mobyvb** [comment]
@boshevski that step is shown in the upgrade modal. Should we still show it in Andrii's video, when payment method is added via billing  screen, and not upgrade modal?

**Comment by wilfred-asomanii** [comment]
> NOTE: the same behaviour with adding Storj tokens

Currently, the success step shows up in the upgrade dialog after the "Add tokens" step (if user was in free tier)
And a success banner show at the bottom of the "Add tokens" step if the user is in paid tier
Can you confirm it does not work this way?

**Comment by mobyvb** [comment]
cc @boshevski can you see the above comments and video?

**Comment by wilfred-asomanii** [comment]
v1.99.3  e8f9782
