### ISSUE TITLE
Satellite UI: Improve "cancel" action in dialogs

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6757]
On certain dialogs (modals) in the Satellite UI, there is a brief loading animation when the "cancel" action is performed.

"cancel" means that no work needs to be done, and that the dialog should be closed. So when a user performs this type of action, it should be almost instant, and no loading animation should be displayed.

### AC:
* identify dialogs with cancellation actions, and update them so that there is no unnecessary delay between user input and closing the dialog

**Comment by wilfred-asomanii** [comment]
v1.98.2  39ad43b
