### ISSUE TITLE
Update Stripe JS library version to comply with upcoming changes in Chrome

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6763]
> third party cookies will be blocked in Chrome around october this year  and it seems our version of stripe.js is affected
https://developers.google.com/privacy-sandbox/blog/cookie-countdown-2023oct

[slack link](https://storj.slack.com/archives/C019JQJ4LTV/p1707245831735749)

### AC:
* TODO - we need to research whether Stripe has any information on how to address this

**Comment by amozoss** [comment]
Unofficial response from stripe support from someone on reddit 😄 

https://www.reddit.com/r/stripe/comments/191k96p/comment/kk2sby1/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by mobyvb** [comment]
Awesome, thanks for finding that. So I guess we just wait for news from Stripe

**Comment by NiaStorj** [comment]
@mobyvb please check to see if there are any additional updates that needs to be made

**Comment by mobyvb** [comment]
According to [this](https://support.stripe.com/questions/chrome-third-party-cookie-warnings-for-websites-using-stripe-js) support answer from Stripe:
> You do not need to take any action, nor will your users be impacted.

They are handling/handled it on their side and we do not need to do anything. Closing.
