### ISSUE TITLE
Report the storage discrepancies with eventkit

### ISSUE THREAD

**Issue by elek** [storj/storj#6770]
We want to follow the improvements of the bloom filter bump and this will help us do that.

**Comment by elek** [comment]
Patches are merged, waiting for new storagenode rollout:

```
* f60620b9e N - storagenode: reported the used space reported by satellites (9 days ago) <Márton Elek> <Storj Robot>
* b4b96b154 N - storagenode/pieces: report used space per satellite to monkit (12 days ago) <Márton Elek> <Storj Robot>
```

**Comment by iglesiasbrandon** [comment]
This was just rolled out last week with the storage node rollout. We can not check the results with the stats receiver. (the metrics were just added to our whitelist.

**Comment by shaupt131** [comment]
Marton is pretty sure he has this query somewhere.  This isn't worth tracking as a ticket.  Closing this issue.
