### ISSUE TITLE
Investigate potential places where we can do more DB query caching.

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/storj#6772]
Figure out where we can do caching and how it would work in each of those places
 
The outcome of this issue should be new issues to implement all of the areas we found we could improve or do caching.

**Comment by mniewrzal** [comment]
https://docs.google.com/document/d/1mYFcGRWNMsPmlhr8DsUhaj0iU0sQw9y0waOS8v_TkDc/edit?pli=1
