### ISSUE TITLE
Drag&Drop functionality throw error and not uploading files

### ISSUE THREAD

**Issue by andriikotko** [storj/storj#6777]
Drag&Drop functionality throw error and not uploading files
<img width="1711" alt="Screenshot 2024-02-16 at 16 57 12" src="https://github.com/storj/storj/assets/14928042/0aca56c8-bc55-4d10-8f3d-b8ce71ad7628">
tested with Chrome, Firefox, Safari 

### AC:
* drag and drop functionality in UI filebrowser works

**Comment by wilfred-asomanii** [comment]
v1.99.2  30075dd
