### ISSUE TITLE
Prompt for passphrase when user opens or switches projects

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6778]
In V1, when a user opened a project or switched projects, they would be prompted to enter the encryption passphrase for that project. If the user only wants to be prompted to enter passphrase when necessary, they have the option to "skip" entering the passphrase, and are also asked whether or not to remember to skip entering passphrase on opening a project.

It seems like we missed migrating this particular behavior in V2.

![Image](https://github.com/storj/storj/assets/1323312/b4813267-fc69-45a2-b147-2cec86a5f707)

### AC:
* when user opens or switches to a different project (e.g. via sidebar), they are prompted to enter passphrase, unless user has requested to always skip requesting passphrase when opening a project
* If user chooses to skip entering passphrase, and chooses to always remember to skip, the user is not prompted to enter passphrase when opening a project
* If it is the user's first time opening the project:
    * if user is still in onboarding, just direct to project dashboard with onboarding stepper
    * if it is a new project, but user has completed onboarding, prompt user to "create new passphrase"

**Comment by wilfred-asomanii** [comment]
v1.99.3  e8f9782
