### ISSUE TITLE
Do not automatically enter bucket after creation

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6779]
Currently, the satellite UI will automatically attempt to enter the filebrowser for a bucket after it is created (including prompting user for encryption passphrase if needed). However, in some cases, users just want to create a bucket, and use tools outside of the UI to upload/download files with. We want to allow these users to create buckets without thinking about encryption passphrases or the file browser.

### AC:
* after a bucket is created, stay on the page it was created from (e.g. buckets page or project dashboard). The user should click on the bucket in the bucket list view in order to open it and view files.

**Comment by wilfred-asomanii** [comment]
v1.99.3  e8f9782
