### ISSUE TITLE
Make onboarding stepper dismissable

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6780]
Currently, the onboarding stepper only disappears after the user has completed the fourth step (create access). It should be possible for a user to dismiss the stepper whenever they want, and "complete" onboarding. Not all users will necessarily want/need to complete all the steps.

### AC:
* add a close icon to the onboarding stepper. When the user clicks it, the onboarding stepper permanently disappears, and the user is updated to have completed onboarding in the DB

**Comment by wilfred-asomanii** [comment]
1.99.3  e8f9782
