### ISSUE TITLE
Satellite UI: shorten long bucket names

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6791]
If the user has a very long bucket name, it takes up a lot of space in the bucket table view. We should shorten it using an ellipsis.

### AC:
* restrict the maximum width of the bucket name column in the buckets table
* keep the entire bucket name in the html (so that table search is not affected), but visually truncate the bucket name with an ellipsis, e.g. using CSS

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.101.2
