### ISSUE TITLE
[Suggestion] Link to `Terms of Use` on Add CC modal

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#6801]
![image](https://github.com/storj/storj/assets/15882196/3329f72e-b1b0-48d3-841c-485b8d1c1e9a)

A hyperlink to the word "terms" should lead to `Terms of Use` as a way to easily access those terms.

_PS: Absolutely ❤️ the dark theme_

**Comment by boshevski** [comment]
Thanks @nerdatwork, I will make an update for this :)

**Comment by boshevski** [comment]
Update merged. Will be deployed on the next release.
