### ISSUE TITLE
Satellite UI: Segment dashboard updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6809]
### AC:
* add info icon to Segment usage component on dashboard (like in Download)
  * in tooltip, briefly explain what segments are and link to [here](https://docs.storj.io/dcs/pricing#per-segment-fee) as "learn more"

<img width="205" alt="segments" src="https://github.com/storj/storj/assets/3217669/4061df4d-1088-477b-88e1-a5aee9246095">

<img width="327" alt="download" src="https://github.com/storj/storj/assets/3217669/859efb74-b70d-4aaf-b8a0-dd3b102972dc">

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.101.2
