### ISSUE TITLE
Plausible satellite integration: Review plausible code

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6819]
In the satellite, we want to implement the "manual" plausible script. This should only send data to plausible that we explicitly request.
The entire script is at https://github.com/plausible/analytics/blob/master/tracker/src/plausible.js, but by using "manual", only a portion of the script will execute.

Supplementary reading: https://plausible.io/data-policy

### AC:
* review the JS code that would execute on the Satellite UI client side when we add Plausible
  * Our dependency guide: https://github.com/storj/storj/wiki/Dependencies#adding-new-dependencies
  * Ensure that there are no problems with putting this script in the Satellite UI
* decide if we should use the plausible.io-hosted script, or self-host it from the satellite
  * if we need to self-host on the satellite, check if the licensing of the Plausible code is compatible with the licensing of storj/storj

**Comment by wilfred-asomanii** [comment]
Plausible looks good to use, judging by our (applicable) dependency guidelines.
* Its license, AGPL-v3 is compatible with ours so it is possible to self-host the script
* It is well/actively maintained
* It is a small JS script that should not be difficult to maintain ourselves if the need arises.
* It has no external dependencies
There are no problems importing this script into the SateliteUI.
Regarding hosting, the plausible hosted and managed is preferable, offloading the work of hosting this extra script and keeping it updated. Also, we already use the plausible hosted script on our main site.
