### ISSUE TITLE
Plausible satellite integration: trigger Plausible events when page changes

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6821]
Blocked by https://github.com/storj/storj/issues/6820

Add triggers to send page views to Plausible analytics when the user navigates throughout the Satellite UI.

Code examples for reference with `script.manual.js` or `script.manual.local.js`: 
```
// example of sending page view for buckets page; host would need to come from config, or retrieve it on the client side before sending
plausible('pageview', { u: "https://mobytest.storj.io/projects/x/buckets" + window.location.search});
// example of sending page view for signup page, with a property set
plausible('pageview', { u: "https://mobytest.storj.io/signup" + window.location.search, props: {satellite: "mobytest"}});
// example of sending a custom "Signup" event, including url where event occurs, and setting an example property
// this event needs to be created in Plausible as a "goal" to show up on the dashboard
plausible('Signup', { u: "https://x.mobytest.storj.io/lol" + window.location.search, props: {paid: false}});
```

### AC: 
* when the path of the Vue app changes, trigger a "pageview" request to Plausible
  * paths should include "satellite" property with satellite name, so that they can be filtered in the plausible dashboard, to distinguish from website traffic and other satellites
  * paths should be "anonymized" before sending to Plausible:
    * Project IDs, bucket names, file paths, etc... should not be in URL. E.g. use path `/projects/x/buckets` instead of `/projects/<actual project ID>/buckets` - this way the same path is tracked for all users and there is not identifying information sent to Plausible
    * Remove identifying query-param information from the URL. It is okay to keep query params like `/signup?partner=...` or `utm` parameters. However, if we have query params like `email` or `token` - anything that is unique to a user - we should remove it before sending to Plausible

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.101.2
