### ISSUE TITLE
Add "No credit card required" to signup

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6822]
### Objective
Make it clear that a prospective customer/user doesn't need to enter a credit card to try  the product.

### Acceptance Criteria
- Add "No credit card required." to the unordered list on the sign up page:
![image](https://github.com/storj/storj/assets/7063002/170aeef6-405c-490b-a628-39fce62dce64)

_Note: we may update this in the future to call out the free trial specifically_

**Comment by ferristocrat** [comment]
@mobyvb - this says merged but I don't see the bullet point at us1.storj.io/signup

**Comment by mobyvb** [comment]
@ferristocrat it is merged, just not deployed. You can see the bullet point on QA - should go out to production next week
(this change was not included in the v1.100.5 cherry-pick that was deployed yesterday)
