### ISSUE TITLE
Update use case selection

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6823]
### Summary
We want to update the use case selection to be reflective of how our sales/marketing teams are grouping customers.

### Acceptance Criteria
- Update the list of use cases (selected during onboarding) to the following:
   - Active Archive
   - Backup & Recovery
   - CDN Origin
   - Generative AI
   - Media Workflows
   - Other
- Ensure that these are feeding into HubSpot still

For reference the list we currently have:
![image](https://github.com/storj/storj/assets/7063002/8344d2b3-afaa-40cd-a6c3-3cd1a20df2d4)

**Comment by ferristocrat** [comment]
Is there anything blocking this from being merged/released? cc @NiaStorj

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.101.3
