### ISSUE TITLE
Test S3 Browser

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#6826]
S3 Browser have Versions table. We should check if this tool will display versions correctly for our implementation.

![image](https://github.com/storj/storj/assets/7313031/f3cfebdd-67da-4dcb-9f7d-1c08e2a27352)

**Comment by ihaid** [comment]
List of issues I fount so far:

- [ ] Can't create delete marker when deleting specific tag(maybe paid feature)
- [ ] Can't delete\restore the delete marker
- [ ] Error on list all versions for specific object like `[W] [2024-03-04 17:26:23] Task failed (InternalError: We encountered an internal error, please try again.: cause(uplink: metainfo: prefix should end with slash)) TaskID: 300`
- [ ] Every single upload is a new version even if file is not changed 
- [ ] File renaming will hard delete all version and keep the latest 
- [ ] Move file also moving just last version, other will be deleted(?)
