### ISSUE TITLE
Cyberduck doesn't work with our object versioning

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#6827]
@dominickmarino Tested our versioning with cyberduck and its not detecting that bucket is versioned.

```
I’m testing Cyberduck and it appears versioning is not working. I enabled my test bucket using rclone and then connected with cyberduck which does not detect the bucket as versioned. Rclone does report versioning as enabled for this bucket.
I’ll test mountainduck next.
Cyberduck doco - https://docs.cyberduck.io/cyberduck/info/#versions
Mountain duck doco - https://docs.cyberduck.io/protocols/s3/#versions (edited) 
```
![image](https://github.com/storj/storj/assets/7313031/f02723fb-a9cf-4b65-8d4c-fcbeaf8aacf8)

Full convo:
https://storj.slack.com/archives/C03AHET16CR/p1709239243067799

**Comment by dominickmarino** [comment]
This is broken using our cyberduck profile but works using the generic s3 configuration. This must mean the configuration file needs to be updated here

https://github.com/iterate-ch/profiles

**Comment by dominickmarino** [comment]
Its line 36, ill get it fixed. 

https://github.com/iterate-ch/profiles/blob/main/Storj.cyberduckprofile

     <string>s3.versioning.enable=false</string>

**Comment by dominickmarino** [comment]
They accepted, merged and closed in under a minute https://github.com/iterate-ch/profiles/pull/108
