### ISSUE TITLE
Satellite UI: versioning in file browser

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6833]
When versioning is enabled on a bucket, users can use the toggle on the right to view the versions. Versions show name, size, type, date, version id, and actions to download, share, and delete.
<img width="1241" alt="versioning" src="https://github.com/storj/storj/assets/3217669/279ef59d-d602-4073-b0b2-a72d08a01070">

Adding option to hide/show version id column from the bucket settings dialog.
<img width="1240" alt="hide" src="https://github.com/storj/storj/assets/3217669/f08e1325-b869-4aab-849e-0e23cd639525">

### AC:
* Users should be able to toggle between seeing just the latest version of objects and seeing all versions of objects (chevron icon in screenshots above)
    * Each object should have a dropdown to show available versions and include the same metadata that is shown for unversioned buckets AND the addition of the version id
    * old versions of objects should be downloadable
* toggle added in filebrowser for turning version visibility off
  * when off, user cannot toggle to see older versions of an object, nor version ID
  * when on, user can use chevron to expand older versions of an object, and see version ID  column

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.103.2
