### ISSUE TITLE
Windows node shows total amount of free space instead of total amount of disk space

### ISSUE THREAD

**Issue by profclems** [storj/storj#6834]
The node shows the total amount of free space instead of the total space available

Image below copied from the forum:
![](https://storj-s3.bcdn.literatehosting.net/original/2X/d/db7a33b9ca313c145a6fa27ba28a0f87f5722aac.png)

Could be the reason for this issue https://github.com/storj/storj/issues/6818

Links 
- https://forum.storj.io/t/storage-allocated-disk-space-not-updating-in-config/25303/8?u=alexey
- https://forum.storj.io/t/1-98-storage-allocated-disk-space/25417/5?u=alexey

**Comment by profclems** [comment]
Related PR: https://review.dev.storj.io/c/storj/storj/+/12627

**Comment by shaupt131** [comment]
Included in v1.100.2
