### ISSUE TITLE
Add partnership with storj selection

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6849]
### Summary
We want to identify potential partners signing up with Storj.

### Acceptance Criteria
- Add a field/checkbox to business information form during onboarding to allow prospective partners to indicate their interest
- When the checkbox is selected, a field in HubSpot should be updated to "true" (this will enable sales/marketing to follow up)

![image](https://github.com/storj/storj/assets/7063002/676d21bb-0f79-402d-b77e-9b6089b0056e)

**Comment by ferristocrat** [comment]
@boshevski - any opinions/thoughts on this "I am interested in partnership with Storj"?

**Comment by boshevski** [comment]
This could go into the onboarding for business accounts.
