### ISSUE TITLE
Satellite UI: Allow user to update preference for being prompted for encryption passphrase

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6857]
Currently, users are automatically prompted to enter encryption passphrase whenever opening a project. If the user selects to "skip", they are then asked if they would like to remember this decision every time. If "yes" is selected, the `user_settings` database table is updated so that the user will _only_ be prompted for encryption passphrase when necessary (e.g. opening file browser or creating access)

There is no way for a user to revert the choice to not automatically be prompted for the encryption passphrase. We should add this.

### AC
* add setting on user settings page allowing the user to change the value of `userSettings.PassphrasePrompt` whenever they want
* show a notification when enabled or disabled

### Designs
#Disable asking for passphrase
<img width="416" alt="ask-disable" src="https://github.com/storj/storj/assets/3217669/2070f60d-806d-4e7a-bdf1-e00b344e1f55">
#Enable asking for passphrase
 <img width="415" alt="skip-enable" src="https://github.com/storj/storj/assets/3217669/7bae5191-590f-4495-a3a3-b164cd61ac96">
#Whole page
<img width="1717" alt="settings" src="https://github.com/storj/storj/assets/3217669/65f586fc-9cd7-4ab3-a15e-ad78f38b11e7">

**Comment by boshevski** [comment]
Added designs.

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.101.2
