### ISSUE TITLE
Satellite UI / Add info about 10% bonus for STORJ token payment

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6883]
Consider adding to the updated STORJ token flow the fact that we still offer 10% bonus on STORJ deposits: https://us1.storj.io/account/billing?tab=payment-methods

Context:

- https://forum.storj.io/t/discontinuation-of-the-storj-free-tier/25332/125
- https://storj.slack.com/archives/C3T10U9AP/p1710579177667149

**Comment by boshevski** [comment]
Done. Included in this PR: https://github.com/storj/storj/pull/6886
