### ISSUE TITLE
Add clarification text for carbon emissions on invoices

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6884]
### Acceptance Criteria
- Add an explanation of the carbon estimates on invoices. Specifically:
   - "The carbon emissions displayed are estimated based on the total account usage, calculated for the dates of this invoice."
   - Confirm that we are passing in terabyte hours into the calculation (update that we're making here: https://github.com/storj/storj/issues/6875)

Note: to engineering - confirm that the above statement is true

**Comment by ferristocrat** [comment]
Issue where it was originally implemented: https://github.com/storj/storj/issues/6694

**Comment by NiaStorj** [comment]
@mobyvb to get an copy of a most recent invoice

**Comment by ferristocrat** [comment]
Invoice from the latest cycle (April): [Invoice-BAA7F6CB-0026.pdf](https://github.com/storj/storj/files/14919459/Invoice-BAA7F6CB-0026.pdf)

**Comment by VitaliiShpital** [comment]
```
Confirm that we are passing in terabyte hours into the calculation
```
https://github.com/storj/storj/blob/main/satellite/payments/stripe/service.go#L1176-L1180
