### ISSUE TITLE
Investigation: Add internal satellite health check

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6887]
### AC:
* investigate what needs to be done to implement a general "internal health check" service for the satellite, so that we can be paged when certain components of the satellite are not working
* create a ticket with next steps

Old ticket details below - implementation will be a separate ticket.

---

The goal of this task is to create a way for the satellite to internally monitor its own health, and then serve information about the health of these services over a public endpoint that can be monitored for orbiter checks. This way, if one of these internal services breaks, orbiter can use this endpoint to determine whether the on call engineer should be paged.

Some criteria:
* individual checks should be defined by some simple interface - like a function to get the unique "name" of the check (e.g. "stripe service"), and a function to execute the check that returns true/false depending on the success of the check
* some process within the health check service should execute on a configured interval (e.g. every 5 minutes), which will iterate over each individual check, and store the true/false returned in memory
* the health check service should serve a single endpoint that returns the status of every health check at once (e.g. `{"stripe service": true, ....}`) - should be 200 status code if everything is true and 5xx status code otherwise

### AC:

* create a new package for satellite health checks based on the criteria above
* implement a single health check - stripe service - which executes a simple Stripe API request to determine whether the satellite has connectivity to Stripe
* start the satellite health check in the core and/or api

**Comment by elek** [comment]
> some process within the health check service should execute on a configured interval (e.g. every 5 minutes), which will iterate over each individual check, and store the true/false returned in memory

That's fine. But an other possible approach is just executing health check every time when the endpoint is called. We can just cache the last results for a few minutes, if we would like to reduce the load. But a `/health?force=true` may check everything immediately, which can help debug.

> start the satellite health check in the core and/or api

I would prefer to make it a `mud` extension point. An example is here: https://review.dev.storj.io/c/storj/storj/+/12466 but happy to explain it better or help with the implementation.

Kubernetes notes: in Kubernetes nodes we have readiness/healthyness (first one doesn't trigger restart, just removes the pod from scheduling). Wondering if this is a flag, which can be part of the healthcheck interface...

**Comment by mobyvb** [comment]
closing due to https://github.com/storj/storj/issues/6938 being created
