### ISSUE TITLE
satellite/metabase: add tests for ListObjects

### ISSUE THREAD

**Issue by egonelbre** [storj/storj#6891]
Currently scenarios `opts.Pending && opts.AllVersions` and `!opts.Pending && !opts.AllVersions` are untested in the ListObjects implementation. Currently nothing is directly using them, however, there will be probably follow-up work to use them when we replace all other uses of object iterators.

AC:
* Add comprehensive tests for `opts.Pending && opts.AllVersions` 
* Add comprehensive tests for `!opts.Pending && !opts.AllVersions`

**Comment by ihaid** [comment]
@shaupt131 yes, It can be approved
