### ISSUE TITLE
Satellite UI: Hide link for STORJ bonus in transaction list

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6898]
The 10% STORJ bonus not actually a transaction on the blockchain, but we have a record representing it in the database, and details about it are visible in the transaction list view in the billing page of the satellite UI.

The block explorer link that appears next to the STORJ bonus transaction is currently broken. Since there is no actual blockchain entry associated with it, we should just hide the link, while continuing to display the record of the bonus to the user.

### AC:
* no link appears next to STORJ bonus in the transaction list on the billing page

**Comment by wilfred-asomanii** [comment]
https://github.com/storj/storj/releases/tag/v1.102.3
