### ISSUE TITLE
Design Doc: Customer self-serve deletion

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6911]
Design Doc for self-serve deletion of **account**. Project deletion and transfer are separate tasks, outside the scope of this design.

Goal: MVP self-serve deletion; it is okay if some prodowner tasks are involved, e.g. if user flags themselves for deletion, but actual deletion happens some time afterwards, triggered by satellite admin.

### AC:
* write plan and/or create tickets for implementation of self-serve deletion
* user should be able to trigger deletion within the UI
* pro users should not be deleted until their final invoice is generated
* pro user invoices should only include usage up until self-serve deletion was triggered
* admin should be able to get a CSV of users eligible for deletion - this CSV should only include pro users who have finished invoice finalization
* include details of what the CSV-processing deletion script will need to do. Maybe we can use a modified version of this: https://github.com/storj/team-delivery/pull/746

---

OLD ticket details:

* Delete account self-serve functionality
  a. allow delete bucket for trial expiration frozen users
  b. Possibly allow recovery within 30 days - giving us the ability to undo in extreme circumstances
* Allow delete project
  a. Do we let the account run through the rest of the month and then generate invoice and then delete account?
* Transfer project
  a. Open questions: how do we handle invoice generation?
    - in the design, mention a couple options for how invoice generation can be handled, and outline technical approach; later, finance and product teams will make a decision
    - e.g. we could bill original user for usage until transfer, and new user for usage after transfer; or we could bill new user for entire billing period, including prior to transfer

**Comment by iglesiasbrandon** [comment]
hey @mobyvb & @NiaStorj can we prioritize this for the next sprint? These prod owner tickets are getting out of hand :(

**Comment by boshevski** [comment]
Added flows for delete and email change to the [vuetify repo](https://storj.github.io/vuetify-storj/)
