### ISSUE TITLE
Satellite UI / Bug / Can't delete access with special characters in the name

### ISSUE THREAD

**Issue by boshevski** [storj/storj#6919]
It's not possible to delete the access grant with special characters in the name

![Image](https://github.com/storj/storj/assets/3217669/ea2d4efe-8655-40d6-acfa-b5e1d4869fe3)

**Comment by heunland** [comment]
Fixing this should be high priority because if customers can't delete their own access grants, prod owners will need to force delete them via war crimes when these customers ask for account deletion, which should be avoided.

**Comment by VitaliiShpital** [comment]
Hey @heunland! When this change is merged prod owners will be able to delete projects even if API keys still exist
[prod owners](https://review.dev.storj.io/c/storj/storj/+/12960)
