### ISSUE TITLE
Satellite UI: Minor versioning enhancements

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6927]
### AC:
* when hovering on the date that a version was uploaded, display hover text with a precise date + time (localized)
* add hover text to "unversioned" and "not supported" tags to make it clear what the difference is:
  - "unversioned" means that versioning is not currently enabled on the bucket, but it is possible to turn on
  - "not supported" means that the bucket does not support enabling versioning
* when enabling or suspending versioning on a bucket, display a success toast notification

**Comment by NiaStorj** [comment]
ticket is not needed based on the comment above
