### ISSUE TITLE
Satellite UI: Encryption passphrase preference updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6928]
This issue is about the "Passphrase Preference" setting on the "Account Settings" page

### AC:
* Change heading to "Passphrase Prompt Preference"
* Change text describing this to depend on the current state (enabled vs. disabled):
  - if enabled, the text should say something like "Ask for encryption passphrase when opening a project"
  - if disabled, the text should say something like "Only ask for encryption passphrase when necessary"
* When Enable/Disable button is clicked, instead of changing the setting immediately, display a dialog explaining more info about the change:
  - if "Enable", dialog should contain text like "If you proceed, you will be prompted to enter your project encryption passphrase as soon as you open a project, so that you do not need to enter it later"
  - if "Disable", dialog should contain text like "If you proceed, you will only be prompted to enter your project encryption passphrase when it is necessary (e.g. opening a bucket, creating an access grant)"
  - Should contain "continue" and "cancel" button - "cancel" does not change anything and "continue" proceeds with updating the user setting
* After changing the setting, display a success toast notification
* Ensure that the setting is implemented correctly - if enabled, passphrase prompt should occur whenever a project is opened/switched. If disabled, passphrase prompt should only occur when it is necessary to provide functionality to the user

**Comment by mobyvb** [comment]
cc @boshevski let me know if anything should change in this ticket

**Comment by boshevski** [comment]
Looks good overall. I will think about the dialog information and update the description if necessary.
