### ISSUE TITLE
Update relevant Object Versioning documentation

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#6934]
### Background:

We need to update and publish relevant object versioning documentation.  

Links:

- https://github.com/storj/docs/pull/358
- https://storj-docs--pr358-357-update-object-ve-gfprw67u.web.app/dcs/buckets/object-versioning

**Comment by kmozurkewich** [comment]
just noticed this page was empty - glad someone else noticed and is tracking..

https://docs.storj.io/dcs/buckets/object-versioning

**Comment by ferristocrat** [comment]
> just noticed this page was empty - glad someone else noticed and is tracking..
> 
> https://docs.storj.io/dcs/buckets/object-versioning

We've got something there now. Was waiting on our beta being open/live in the Satellite UI before pushing the doc live.
