### ISSUE TITLE
Add Commvault to list of applications in web console

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6936]
### Acceptance

- Add Commvault to the [storj.io](http://storj.io/) applications list 
  - Docs link: https://docs.storj.io/dcs/third-party-tools/commvault
  - Description TBD
  - Category: 

Logo:
![image](https://github.com/storj/storj/assets/7063002/9621522a-8029-425a-b755-751b6062cac3)

Logo web optimized:
![commvault-logo](https://github.com/storj/storj/assets/3217669/42becb9a-115b-48aa-9b35-d3832e7cf5eb)

**Comment by mobyvb** [comment]
This is what my WIP looks like so far

![Image](https://github.com/storj/storj/assets/1323312/4c868be3-161f-4609-9ad4-151139243c13)

Some notes:
* logo is very large (even after reducing dimensions 4x, it is the largest filesize of any logo - but can likely get the filesize even lower)
* does the whitespace around the logo look fine? I can crop it more, but I can't change the background color without a transparent version of the logo
* the description of Commvault above is too many words. We need a single sentence description like the ones here: https://www.storj.io/integration-categories/backup-disaster-recovery
