### ISSUE TITLE
Satellite UI: Object lock selection during bucket creation

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6942]
See vuetify repo for design. Main idea:
* when creating a bucket, if eligible to create with versioning:
  * first ask the user if they would like to enable object lock (see design)
    * if "yes", in the step asking to enable/disable versioning, _do not_ allow user to select "versioning disabled" - it is required for object lock
    * if "no", proceed in asking user to enable/disable versioning

We should also add a "bucket creation confirmation" step at the end of the dialog flow, before actually creating the bucket. 

### AC:

*Add a closed beta feature flag for Object Lock, similar to Object Versioning closed beta
* if project is marked as being in closed Beta for Object Lock:
  * add step to bucket creation flow for selecting whether object lock is enabled or not
* add confirmation step to the end of bucket creation dialog _if_ it is a multi-step dialog (confirmation step is not needed on projects where object versioning is not enabled, because it is only one step: enter bucket name)

##### New Bucket -  Step 2 - Object Lock
<img width="523" alt="bucket-step-2" src="https://github.com/storj/storj/assets/3217669/7cac152c-1550-4fff-9f94-3aa563c41da4">

##### New Bucket - Step 3 - Versioning
<img width="507" alt="Screenshot 2024-05-29 at 18 06 31" src="https://github.com/storj/storj/assets/3217669/b596cad7-ef01-4f8a-89ce-5df31034bf46">

##### New Bucket - Step 4 - Confirm
<img width="517" alt="bucket-confirm" src="https://github.com/storj/storj/assets/3217669/a0932e59-6ced-4567-bc39-07a74d231b07">

**Comment by boshevski** [comment]
Added designs and updated the code too.

**Comment by boshevski** [comment]
We should make sure the multi-step dialog doesn't close by clicking away / [related ticket](https://github.com/storj/storj/issues/6940)

**Comment by NiaStorj** [comment]
@wilfred-asomanii why is this in "blocked"?

**Comment by wilfred-asomanii** [comment]
@NiaStorj there is a change to uplink that needs to be merged first

**Comment by NiaStorj** [comment]
is it possible to add the copy: "Only compliance mode is currently supported. Legal hold and governance mode are coming soon" to the first screen shot for object lock?

cc @mobyvb @ferristocrat @boshevski
