### ISSUE TITLE
Satellite UI: Versioning updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6969]
### AC
* add confirmation dialog step when user accepts to try versioning beta, which includes next steps
* if user has accepted versioning beta, display versioning columns on buckets table, even if all the user's buckets are versioning=unsupported
* allow user to opt in to versioning beta from account settings, even if they already declined/dismissed on project dashboard
* update icons and help text for versioning column on buckets table (check vuetify repo):
  - update tooltips
  - update icons

##### Project Settings
<img width="458" alt="account-settings" src="https://github.com/storj/storj/assets/3217669/c920ff49-dde9-4695-aaff-e1a78a95c94a">

##### Dialog - Step 1
<img width="531" alt="dialog-step-1" src="https://github.com/storj/storj/assets/3217669/7e4c39ec-d77a-4637-90da-1db91df10447">

##### Dialog - Step 2
<img width="499" alt="dialog-step-2" src="https://github.com/storj/storj/assets/3217669/783e2839-7ec1-4815-acb5-2066e012e89b">

##### Dialog - Step 2 expanded
<img width="514" alt="step-2-expanded" src="https://github.com/storj/storj/assets/3217669/d282f54b-881c-4405-8477-2d278357d643">

##### Status icons in the buckets table
<img width="168" alt="icons" src="https://github.com/storj/storj/assets/3217669/5e6222fb-da94-4baa-8d0f-b2fa2d0a66d1">

**Comment by boshevski** [comment]
Added designs to the ticket, and updated the code in the vuetify repo.

**Comment by boshevski** [comment]
Updated the icons and the tooltips too.
