### ISSUE TITLE
Satellite UI: Daily usage graph updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6972]
### AC:
* use unambiguous date format for x-axis - similar to the format used for other times throughout the UI: "May 4" instead of "4/5" or "5/4"
* remove unit from y-axis heading and add unit to y-axis labels (e.g. "MB" removed from axis heading, and "10" in axis label changed to "10 MB")
* change graph line colors (TODO design - possibly use "sparkline" from Vuetify 3.6 if #6970 is complete and sparkline works with our existing graph components)

**Comment by wilfred-asomanii** [comment]
The sparkline component may not fit our purposes. its a simple graph with no y-axis; it can not be a drop in replacement for our current graph.
