### ISSUE TITLE
Object Lock - Object Browser Operations

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6976]
Acceptance Criteria
- In the object browser: 
   - Allow the locking of individual object versions
- Update bucket details dialog to show "lock" status of bucket
- handle the error that occurs when you try to delete a locked object version 

Out of scope and not needed currently:
 - Show object versions that are locked and the date the lock expires (out of scope because there's no method to get all lock statuses of all object versions in a single call)

**Comment by mobyvb** [comment]
cc @boshevski

**Comment by boshevski** [comment]
We have designs in the vuetify repo for lock status in the object browser, and for locking of individual object versions. 

<img width="1170" alt="versions" src="https://github.com/storj/storj/assets/3217669/d6ea21df-e77d-4d51-ac9d-8d65b352e256">

**Comment by NiaStorj** [comment]
Blocked due to needing further discussion how we want this feature to work. 
is fetching for each status okay?

**Comment by ferristocrat** [comment]
> [@boshevski](https://github.com/boshevski) are you able to create a design for this ticket

Specifically, I think we're missing "handle the error that occurs when you try to delete a locked object version"

**Comment by NiaStorj** [comment]
@boshevski please see Michael's comment above

**Comment by boshevski** [comment]
Design for error state when deleting a locked object version.
<img width="500" alt="error-delete-object-locked" src="https://github.com/user-attachments/assets/9337a2e3-f386-4805-8b62-7d25d9072b48">

Learn more should link to the object lock page in the documentation.
https://storj.dev/dcs/api/s3/object-lock
