### ISSUE TITLE
Satellite UI: Onboarding account type updates

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6979]
There are two goals:
* prompt all users during onboarding about whether they want to upgrade to pro immediately or proceed with the free trial
* unify this prompt with the existing "package plan" onboarding flow so that we only need to maintain one

### AC:
* During onboarding, all users are prompted about whether they want to upgrade to pro or not
  * prompt should not occur if billing is disabled on the satellite
* The existing "package plan selection" component in onboarding is repurposed to apply for all users. Style according to design above
  * if it is easier to create a new component and get rid of the old package plan selection component, that's fine
* Analytics are tracked for whatever option user selects during onboarding

### Design:
<img width="1486" alt="onboarding-plan-selection" src="https://github.com/storj/storj/assets/3217669/9b0e0aff-4395-4ac9-834f-e6529e698491">

**Comment by mobyvb** [comment]
cc @boshevski

**Comment by boshevski** [comment]
Added design and code is already in the vuetify repo onboarding flow.
