### ISSUE TITLE
Satellite-managed encryption passphrase: Remove passphrase step from onboarding stepper

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#6993]
Projects that have Satellite-managed encryption passphrase enabled should not have the "Set passphrase" step of the onboarding stepper.

**AC**:
* "Set Passphrase" step is not visible for these projects.

**Comment by NiaStorj** [comment]
7/2/24:

will follow up with Tome

cc @mobyvb @boshevski

**Comment by boshevski** [comment]
Design:
<img width="1225" alt="onboarding-managed" src="https://github.com/storj/storj/assets/3217669/f75d2532-fdfe-4103-9c0e-e89bcbe701e2">

Code is in the vuetify repo
