### ISSUE TITLE
Satellite-managed encryption passphrase: Show information about managed encryption passphrase

### ISSUE THREAD

**Issue by wilfred-asomanii** [storj/storj#6994]
Users should be able to see information about this feature and what it means for their opted-in project from the project's settings.

**AC**:
* UI capability to view more information about Satellite vs user-managed encryption passphrase.

**Comment by NiaStorj** [comment]
needs design @boshevski

**Comment by boshevski** [comment]
Design:
<img width="1225" alt="onboarding-managed" src="https://github.com/storj/storj/assets/3217669/a7335003-0f09-4ac5-b5b7-6699bdf2b605">

Code is in the vuetify repo

**Comment by boshevski** [comment]
Design:
<img width="1230" alt="project-settings" src="https://github.com/storj/storj/assets/3217669/1f6ccf51-658f-4355-be76-f896fd175ec1">

**Comment by boshevski** [comment]
This change should move the Delete Project card to the bottom in a new section Danger Zone (same as account settings page) and replace it with a new card for the project encryption information which links to the documentation.

**Comment by boshevski** [comment]
Created another [ticket ](https://github.com/storj/storj/issues/7049) for displaying more information.
