### ISSUE TITLE
storagenode updater should remove older binaries after update

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#7004]
The updater after updating itself or the storagenode, only renames the old binary by appending `.old.<version>` to the binary name (in the case of the storagenode) or appending `.old` (in the case of the storagenode-updater).

This accumulates a lot of binary files on the storage location unless manually deleted:

![Image](https://github.com/storj/storj/assets/41906128/28efc84e-f72d-49ab-823c-56e7323c9466)

The updater should delete the older binaries on restart.

**Comment by shaupt131** [comment]
Marton cleared this partition out today, but we still need the changes implemented that will do this automatically moving forward.

**Comment by shaupt131** [comment]
Clement will be returning to this today.

**Comment by shaupt131** [comment]
Ready for review.  Ivan, Damein, and JT will review.

**Comment by shaupt131** [comment]
Ivan reviewed and left a comment.  

#### Next steps:

- Review https://review.dev.storj.io/c/storj/storj/+/14013

**Comment by shaupt131** [comment]
#### Work completed since last standup:
- PR was reviewed and approved.  One outstanding comment to resolve. 

#### Work to be completed by next standup:
- Clement will resolve comment and merge (hopefully)

Once deployed to QA, we can check if it had the desired effect on the QA nodes.  This will then go out in the next Storagenode rollout in roughly 3 weeks.

**Comment by shaupt131** [comment]
Can we verify that this had the desired impact in QA and thus in production?

**Comment by iglesiasbrandon** [comment]
closing this issue for now; @profclems please verify its working as desired
