### ISSUE TITLE
Investigate why Jaeger isn't working and fix.

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#7005]
Jaeger is not working it seems.
I can't find any traces currently.

**Comment by shaupt131** [comment]
{"type": "server", "timestamp": "2024-06-12T14:39:51,330Z", "level": "WARN", "component": "o.e.c.r.a.DiskThresholdMonitor", "cluster.name": "jaeger-elasticsearch", "node.name": "jaeger-elasticsearch-primary-0", "message": "high disk watermark [90%] exceeded on [iNkOYtJTSGGzJAuHMKOACA][jaeger-elasticsearch-primary-0][/usr/share/elasticsearch/data/nodes/0] free: 22.3gb[7.5%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to

We probably don't have enough space for the database.

**Comment by dlamarmorgan** [comment]
This is resolved, and Jaeger is running again. I think you are correct @shaupt131 and we ran out of space, but it's not clear if our cron job to remove old traces stopped working correctly, or we just ran out of space despite keeping only the previous few days of traces. I'll keep an eye out for this.
