### ISSUE TITLE
Object Versioning stopped working on my buckets?

### ISSUE THREAD

**Issue by villisek** [storj/storj#7006]
Hello!
Hopefully it is the right place to report this...

**Description**

I've been using Storj for object storage since April, and I enabled "Object versioning beta" via the menu that showed on the project dashboard. I already used it to restore files on my bucket. 
However, **now the bucket's object versioning is marked as "not supported"** on the web UI. 

So I'm wondering: 
1. Is it "normal"?
2. Was object versioning disabled?
3. How to make it supported and enabled (if there's any way to achieve that)? 

I'm not sure what details i can provide to help solving the "issue" (if there's any) though... 

**Describe the results you expected:**

The object versioning should be marked as "enabled" on the WebUI

**Describe the results you received:**

The object versioning is "not supported" according to the Web UI

**Your environment**

Linux (openSUSE), using Firefox to access the Web UI.
I generally use rclone for my individual object storage bucket, and restic for my "backups" bucket.

Thanks!

**Comment by onionjake** [comment]
Thanks for reporting! Can you submit a support ticket here as well with your account email, this ticket, and which bucket it is? https://supportdcs.storj.io/hc/en-us/requests/new

We will look into it.

**Comment by ferristocrat** [comment]
@villisek - For buckets created before object versioning was available, versioning cannot be enabled (it's not backwards compatible with "old" buckets. So for those the expected message is "Not Supported."

**Comment by villisek** [comment]
Hello, sorry for the delay. 

> Can you confirm that the buckets that say "Not Support" are even buckets that you created new after enrolling in the beta?

Oh... I'm not sure of that :-/ 
But what I'm sure of is that I've been able to restore my files after an accidental delete using the S3 object versioning API. 

So, in such case, may I open a ticket anyway?

**Comment by ferristocrat** [comment]
> So, in such case, may I open a ticket anyway?

Yeah, it would be good to create the ticket so we can see if there was in fact an issue with the versioning state of the bucket. The useful information to investigate would be: project ID, bucket name, and a link to this github issue (https://github.com/storj/storj/issues/7006).

**Comment by heunland** [comment]
The customer @villisek has submitted a support ticket https://supportdcs.zendesk.com/agent/tickets/29567 on the help desk now:

> Hello, 
> I am opening this ticket following this issue reported on GitHub: https://github.com/storj/storj/issues/7006#issuecomment-2170637096
> 
> My account e-mail is : storj@villisek.mozmail.com
> 
> The problem is that I enabled Object versioning on several of my buckets before the “object versioning” indicator was visible in the bucket lists. 
> 
> I already used object versioning to recover some of my files but the updated web UI says that object versioning isn't supported on these buckets : 
> * “My Storj Project” → bucket “cvillisek” (I used S3 API for object versioning on this one) 
> * “server-backups” → bucket “mail” (I haven't tried restoring files on it, but I remember enabling object versioning on it as well)
> 
> Thank you.

@onionjake @ferristocrat could you please continue with troubleshooting the issue, bucket and project names are posted above. The account is on EU1.

**Comment by ferristocrat** [comment]
We haven't been able to replicate the issue, and based on the implementation it is unlikely that the "Unsupported" buckets were ever versioned. Opting into the Object Versioning from the Beta doesn't mean that new buckets will have versioning enabled by default, just that versioning can be enabled for new buckets.

Running the following test to try to enable versioning on an `unsupported` bucket and it doesn't work:
```
aws s3api put-bucket-versioning --bucket example-s3-bucket1 --versioning-configuration Status=Enabled
```
404 response:
```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>NoSuchBucket</Code>
    <Message>The specified bucket does not exist</Message>
    <BucketName>thisisatest</BucketName>
    <Resource>/thisisatest/</Resource>
    <RequestId>17E13C7ED69CAFBC</RequestId>
    <HostId></HostId>
</Error>
```

For buckets that are `unversioned` or `suspended` I just get a 200 success as expected. Unversioned is the state a bucket is in after "suspending" versioning after it has already been enabled.

So while the error is a bit weird that we do return, it's an error nonetheless and doesn't lead to an `unsupported` bucket having versioning enabled.

**Comment by ferristocrat** [comment]
Documentation on Object Versioning and the beta: https://storj.dev/dcs/buckets/object-versioning
