### ISSUE TITLE
[Suggestion] - Proactive notification for expired Credit Cards

### ISSUE THREAD

**Issue by nerdatwork** [storj/storj#7007]
Proactive notification for expired credit cards or payment methods.

As shown below the credit card has expired but there is no visual notification that it has expired. Maybe a red border or removing `Default` and replacing it with `Expired` text would be ideal. A red banner at the top would be ideal too.

![image](https://github.com/storj/storj/assets/15882196/05d9aa26-45e4-4460-81a6-22dccb957421)

It can be seen on any Amazon accounts as 👇 

![image](https://github.com/storj/storj/assets/15882196/e92485ab-0a9f-4ff3-be0d-64c7661a9ee6)

**Comment by boshevski** [comment]
Design:
<img width="402" alt="expired-card" src="https://github.com/user-attachments/assets/46c479c2-747a-40c2-8f29-5185efd84d6c">

**Comment by boshevski** [comment]
Thank you @nerdatwork

**Comment by nerdatwork** [comment]
I would also like to suggest to show a banner/notification at the top of the page after user logs in to remind updating the card **as long as its the `default` card**.

This notification should be dismissible after clicking X and **shows only once after every login** till the issue is fixed.

**Comment by boshevski** [comment]
Alert for expired credit card:

<img width="1205" alt="Screenshot 2024-07-23 at 16 00 17" src="https://github.com/user-attachments/assets/599b6d95-dcbe-4aba-b138-ddcc428b6909">

**Comment by nerdatwork** [comment]
It looks perfect. I can't wait to test this on QA satellite.

**Comment by boshevski** [comment]
Design for card expiring soon:
<img width="645" alt="card-expiring-soon" src="https://github.com/user-attachments/assets/bc1b73b5-06a0-463c-a4fc-4c909aca226e">

@VitaliiShpital please check this alert notification which should be sent 1 month before expiry date. Added to the vuetify repo.
