### ISSUE TITLE
Satellites stop uploading to nodes that have n bytes + pieces configurable per placement

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#7026]
As nodes continue to grow, we will continue to experience associated pains.  We want to encourage SNO's to scale the number of nodes, NOT to have larger nodes.  
```[tasklist]
### Tasks
```

**Comment by MaxMaximus** [comment]
As an SNO who has been engaged in detailed monitoring of work of few large (10-16 TB) nodes in the last few weeks, I can say
that all these "pains" on large nodes are associated with a very large number of pieces (and, accordingly, files stored on the file system).
The number of bytes stored in itself does not cause any problems.

So if it is decided to introduce such limits later, I am sure that it is enough to limit only the max number of already stored pieces when choosing a nodes list for an upload.

**Comment by shaupt131** [comment]
https://review.dev.storj.io/c/storj/storj/+/13742
