### ISSUE TITLE
Satellite managed encryption: Styling updates for create project

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7033]
Currently, we use the same component to set satellite vs. user managed encryption during project creation as we do during onboarding.
This component is full-screen, which looks inconsistent when creating a project, which occurs in a dialog.

### AC:
* when creating a project outside of onboarding, make selecting satellite vs. user managed encryption a dialog step, rather than a full-screen step

### Designs:
<img width="501" alt="automatic" src="https://github.com/storj/storj/assets/3217669/bd4f11c8-143f-436e-b88f-7a182003679c">

<img width="498" alt="manual" src="https://github.com/storj/storj/assets/3217669/560bf492-43b8-4a18-88b0-99831386a7ae">

### UI Code:
* in the vuetify repo

**Comment by boshevski** [comment]
Updated the ticket with designs.
