### ISSUE TITLE
Satellite UI: "domains" page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7034]
Add a page to assist the user in setting up a custom domain to serve linksharing content ([link to docs](https://docs.storj.io/dcs/code/static-site-hosting/custom-domains))

Due to the database schema freeze, we are not able to add any tables or columns that would allow us to persist custom domain data within the satellite UI, so this task is more limited in scope. We should simply add a page to help guide the user through creating an access and setting up a custom linksharing domain without needing to go to the docs.

### AC:
* add feature flag to enable/disable the new page
* add a "domains" page to the project navigation sidebar
* add a flow to set up a new custom domain on the domains page 
  * the flow should allow the user to select a bucket to serve as a static site
  * necessary credentials should be created in the background during the flow, and the UI should display the DNS records the user must set in order to serve the bucket on their domain
  * the final step of the flow should allow the user to trigger a check to confirm whether the DNS records are correct
  
### Design:
<img width="1422" alt="domains" src="https://github.com/storj/storj/assets/3217669/1b31cf26-90d3-4741-a82f-7db9fbb7314b">
<img width="475" alt="domain-step-1" src="https://github.com/storj/storj/assets/3217669/6681032c-77b5-4d73-9139-a4e4b752aa8f">
<img width="462" alt="domain-step-2" src="https://github.com/storj/storj/assets/3217669/10c384d2-fa88-44f9-8140-d4d547672597">
<img width="459" alt="domain-step-3" src="https://github.com/storj/storj/assets/3217669/507b64cf-c7f7-43cd-b5a8-552c26aa8752">
<img width="465" alt="domain-step-4" src="https://github.com/storj/storj/assets/3217669/07777a84-7745-4090-8b44-370924c281ee">
<img width="449" alt="domain-step-5" src="https://github.com/storj/storj/assets/3217669/f84c8891-4c19-4c68-a56b-bdae63b111e9">

Check the code in the vuetify repo.

**Comment by boshevski** [comment]
Updated the ticket to add designs.

**Comment by ferristocrat** [comment]
Can we persist the DNS check results? Like perpetually show the user the result? and possible allow the user to trigger the check again?

**Comment by mobyvb** [comment]
@ferristocrat I believe we can only persist the DNS check results with schema updates, which is a no-go due to the freeze.
So the implementation for now will only be able to "remember" the domain the user is attempting to set up during the session, until refresh.
Unless domains configured for static site sharing are persisted somewhere on edge (I don't think they are), we don't currently have a way to track what domains the user is setting up.

Given a particular domain, we can check whether DNS is configured correctly, but the user would need to provide that in order to check, until we have a way to save it in the DB.
