### ISSUE TITLE
Satellite UI: improve session invalidation logic for "change password"

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7036]
Currently, when a user changes their password, all of their active sessions, including the one they are using, are invalidated. This means you are immediately logged out after successfully changing your password.

Instead, we would like to invalidate all sessions _except_ for the session performing the "change password" request

### AC:
* when the user changes their password or email, invalidate all sessions except for the session performing the request

**Comment by iglesiasbrandon** [comment]
hey @mobyvb @NiaStorj @ferristocrat @wilfred-asomanii @andriikotko this patch looks to be deployed to production. I am going to close this issue.
