### ISSUE TITLE
Satellite UI: Active session info on account settings page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7037]
We already have a `webapp_sessions` table, which stores all active sessions for the satellite UI. On the account settings page, we would like users to be able to see what sessions are currently active for their account.

The fields of the webapp sessions table are:
```
	field user_id    blob
	field ip_address text
	field user_agent text
	field status     int       ( updatable, autoinsert )
	field expires_at timestamp ( updatable )
```

### AC:
* add a section on the account settings page listing all active sessions for a user
  * only show valid sessions
  * display user agent and expiration time of each session

### Design:
<img width="923" alt="active-sessions" src="https://github.com/user-attachments/assets/9b8991a7-90e8-4810-b3ad-08f89e498a26">
Check the vuetify repo.

**Comment by ferristocrat** [comment]
Would we be able to allow expiring of all/individual sessions from here?

**Comment by mobyvb** [comment]
@ferristocrat yes, that would be the next step after this ticket

**Comment by boshevski** [comment]
Updated the ticket to include design.
