### ISSUE TITLE
Update Project Settings with Object Lock Info

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7057]
Since we will be adding Object Lock to the Object Versioning beta we should update the title, descriptions and documentation links on the profile settings page to include both Object Versioning and Object Lock.

**Comment by ferristocrat** [comment]
@boshevski - created a placeholder so we don't forget to do this.

**Comment by boshevski** [comment]
Adding another card in the Project Settings page for Object Lock:

![Image](https://github.com/user-attachments/assets/222613fd-971c-4474-90ba-c08fa1965d78)

**Comment by boshevski** [comment]
Enable object lock (beta) on a project level:

![Image](https://github.com/user-attachments/assets/4ccb768e-a094-457e-bf68-0aaccfafb40e)

**Comment by boshevski** [comment]
Step 2: Enabled object lock / show more information and next steps. Same as object versioning, we want to show this info dialog when it's enabled from the project settings page.

![Image](https://github.com/user-attachments/assets/78dc1176-b51a-478c-a362-6d97649278e2)

**Comment by boshevski** [comment]
Designs and code in the vuetify repo.

**Comment by onionjake** [comment]
I believe they will be the same beta? Object lock will be added to the existing versioning beta?

**Comment by boshevski** [comment]
@ferristocrat @onionjake can you please check now?

**Comment by ferristocrat** [comment]
It makes sense to me. I'm wondering if we just point people to the docs rather than describing in the UI... 

I guess regardless, we should probably specifically call out that it's not feature complete... say something like "for the latest information on feature availability, please refer to the docs"
