### ISSUE TITLE
Add Object lock  to Versioning beta in UI 

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7063]
- Add object lock information to the project settings related to versioning beta
- Update versioning beta to include information about object lock

**Comment by ferristocrat** [comment]
@boshevski created this placeholder

**Comment by NiaStorj** [comment]
@boshevski what eta on the design?

**Comment by boshevski** [comment]
Looks like this is a copy of another ticket where the designs for review are attached: https://github.com/storj/storj/issues/7057

**Comment by mobyvb** [comment]
we need to talk with @jewharton and @wilfred-asomanii to make sure we combine object lock with the versioning beta in an appropriate way

**Comment by wilfred-asomanii** [comment]
Closing as duplicate of #7057 which has more information
