### ISSUE TITLE
Get current list of existing object versioning beta users when object lock is added

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7064]
### AC:
make a list of all emails that have opted in beta from production. 
remove duplicates 

Query:
```
select default_versioning, prompted_for_versioning_beta, count(*) from projects group by default_versioning, prompted_for_versioning_beta 
```
^where `default_versioning=1` and `prompted_for_versioning_beta=true`

needs to be modified with the information above:

**Comment by ferristocrat** [comment]
@mobyvb - the above gets us a count of projects, but not the underlying users...

**Comment by mobyvb** [comment]
@ferristocrat yes that query looks correct
