### ISSUE TITLE
Satellite Admin set/delete project geofence isn't documented and accessible from the UI

### ISSUE THREAD

**Issue by ifraixedes** [storj/storj#7065]
**Description**

The following two endpoints were added to the satellite admin

- `POST /api/projects/{project-id}/geofence?region={number}`
- `DELETE /api/projects/{project-id}/geofence`

Ref: https://github.com/storj/storj/blob/main/satellite/admin/server.go#L172

However, they don't appear [README](https://github.com/storj/storj/blob/main/satellite/admin/README.md) and in the [UI](https://github.com/storj/storj/blob/main/satellite/admin/ui/src/lib/api.ts#L163)

**Steps to reproduce the issue:**

The implementation of them is the proof, however, you can call those endpoints using `curl` and see how they work.

**Describe the results you expected:**

Those endpoints should appear in the README and the UI,

**Describe the results you received:**

They don't appear in the README and the UI.

**Possible Fix**

Update README and UI.

**Comment by ifraixedes** [comment]
Commit ready to review https://review.dev.storj.io/c/storj/storj/+/13986/2

**Comment by ifraixedes** [comment]
Merged

**Comment by shaupt131** [comment]
Once deployed, we just need to check that this functionality is in the admin UI.  If so, we're clear to close.

**Comment by shaupt131** [comment]
#### Definition of done:

- [ ] A project's geofence can be set & deleted via the admin UI
- [ ] New geofence API endpoints are documented in the README

**Comment by ifraixedes** [comment]
Deployed
