### ISSUE TITLE
Satellite UI: Fix preview issues for .pdf and .aiff

### ISSUE THREAD

**Issue by NiaStorj** [storj/storj#7067]
PDF preview does not seem to be working in the object browser.
.aiff files are not previewed as audio files

### AC:
* fix pdf previews
* fix aiff audio previews

**Comment by wilfred-asomanii** [comment]
Caveat for aiff audio; support for playing these files in browsers is very limited. I tested it on Brave and Arc, all chromium browsers, and Safari. Only safari was able to play the file.
