### ISSUE TITLE
Satellite UI: Update Delete Bucket

### ISSUE THREAD

**Issue by boshevski** [storj/storj#7083]
Update Delete Bucket dialog to prevent accidental deletes with additional confirmation and explanation.
- add information about versions, process, and statistics.
- show bucket name
- show bucket size
- show object count
- add confirm delete input
- disable the Delete Bucket button until users type DELETE in the input field to confirm

Design:
![Image](https://github.com/user-attachments/assets/e0b02938-9a7f-4531-8a30-11c6397facd0)

Code is in the vuetify repo.

**Comment by cam-a** [comment]
Do we need to require all caps?
It's fine with me either way, but I expected lowercase to work

**Comment by boshevski** [comment]
lowercase is fine too, caps don't matter.
