### ISSUE TITLE
Satellite UI: Fix layout for upgrade to pro during onboarding

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7086]
The table formatting in the onboarding upgrade to pro page looks wrong:

![Image](https://github.com/user-attachments/assets/6efc48b7-0ae8-4a94-9e9a-94f023a34187)

### AC
* fix table formatting for upgrade step during onboarding

**Comment by boshevski** [comment]
Working on improvements on the account onboarding including this step.
