### ISSUE TITLE
Satellite UI: Change order of steps during onboarding

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7087]
The current order of onboarding steps, if satellite managed encryption is enabled looks like:
* enter onboarding info
* ask for user vs. satellite managed encryption
* ask for free vs. upgrade to pro
^ this might not be exact, but the main issue is:
most of these steps, you can go "back" and modify, but not user vs. satellite managed encryption. So if user selects "user managed encryption", then goes to the next onboarding step, they cannot go back and change what kind of encryption they want on their project.
It would be better to ask the user for user vs. satellite managed encryption as the final step before going to the project dashboard, to reduce confusion if the user attempts to go "back" in onboarding after choosing an encryption management option for their project.

### AC:
* ask user about user vs. satellite managed encryption as the last step of first-login-onboarding, before navigating to project dashboard

**Comment by wilfred-asomanii** [comment]
Shouldn't user vs. satellite managed encryption be right before the success step?
