### ISSUE TITLE
Satellite UI: File version delete/list improvements

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7093]
Object deletion in a versioned bucket can be confusing: it is possible to "delete" an object while preserving previous versions of it. This type of deletion is represented with a "delete marker", and it is the default deletion behavior for a versioned object. If a user wants to completely delete an object in a versioned bucket, they must delete each previous version of the object. We should make this clear to the user.

One option might be to just inform the user about how deletes work (add some simple text). Another option would be to provide two different "delete" behaviors for versioned objects - one to use the delete marker, and the other to delete all the versions and the object completely.

Note: deleting folders might be complicated to deal with, since objects in a prefix could all have different versioning states. By default, deleting a folder would result in delete markers being created for all objects within it, but the objects wouldn't be fully deleted.

When versions for an object are expanded, they are ordered from most recent to oldest version. We should make this more obvious, e.g. by adding a chip on the topmost that says "latest". Also, having a timestamp for each version would help to distinguish them - right now, there is only a date (could be on hover if it takes up too much space)

### Designs: 

Delete File (with versioning):
<img width="482" alt="Delete-File-Versioning" src="https://github.com/user-attachments/assets/13ccdceb-796f-41c7-a056-6f31f332c21f">

Delete Folder (with versioning):
<img width="490" alt="Delete-Folder-Versioning" src="https://github.com/user-attachments/assets/8cca9dd8-d54f-47e5-a6d4-ab4d54868050">

Latest tag on latest version:
<img width="294" alt="latest-tag" src="https://github.com/user-attachments/assets/77d4d332-b4bb-4ce9-9599-a7e1cd3e7daf">

Delete marker in the type column:
<img width="751" alt="delete-marker" src="https://github.com/user-attachments/assets/d8bd310a-36ef-453c-89c8-9d59649c1bfa">

**Comment by ferristocrat** [comment]
@boshevski - do we have designs yet?

**Comment by boshevski** [comment]
@ferristocrat added the designs to the ticket

**Comment by boshevski** [comment]
Objects with "delete marker" should not appear in the browser when versions are not shown. If you enable "Show Versions" in the bucket settings menu, only then the "delete marker" objects and all their versions should appear. We need to update the functionality so it works this way. 

<img width="563" alt="show-versions" src="https://github.com/user-attachments/assets/c9ffa236-2cd2-45a5-9054-71eb8a7980ff">

**Comment by boshevski** [comment]
Would be nice to prioritize [Optimize S3 Bulk Delete Operations](https://github.com/storj/roadmap/issues/91) to have a better delete folders experience.
