### ISSUE TITLE
Satellite UI: Help users debug captcha errors better

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7095]
Sometimes users may get captcha errors due to using VPNs or accessing the satellite UI via VMs running in the cloud. In some cases, users may even be prevented from successfully completing a captcha.

Users who experience these issues are often funneled to support, but we can add an additional suggestion in the UI to try some basic things that could help. In many users' situations, a quick solution is to disable VPN to create an account and/or login, and this does not require using support's resources.

Example issue: https://forum.storj.io/t/cannot-login-into-ap1-storj-io-got-error-hcaptcha-is-required/24701?u=alexey

### AC:
* if user fails captcha due to failed challenge, do not change behavior
* if user fails captcha due to some other reason, display an error message to suggest disabling VPN if one is being used, or contact support otherwise 
* if it doesn't make sense to split behavior depending on error type, just show the VPN/support message for any hCaptcha error

**Comment by mobyvb** [comment]
@boshevski see updated error message in this change: https://review.dev.storj.io/c/storj/storj/+/14736

**Comment by boshevski** [comment]
Looks good.
