### ISSUE TITLE
Satellite UI: Support "applications" flow from Access creation page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7096]
If a user is on the "access creation" page, and selects "s3 credentials" in the creation dialog, display an optional autofill field.

The field is a list of applications from the "applications" page. If the user selects one, proceed through access setup as it is implemented for that application on the "applications" page.

If an application is not selected in the optional field, proceed with normal s3 credential setup.

### AC:

* optional application field added to first step of access creation flow, when user selects "s3 credentials"

**Comment by boshevski** [comment]
Awesome work @VitaliiShpital
