### ISSUE TITLE
Delete object versions retains selection when cleared 🐛

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7111]
**Description**

When I toggle between showing/hiding versions, the count for file deletion gets messed up. See video.

**Screenshots**

https://github.com/user-attachments/assets/d91554f5-f759-41d2-8bb8-753a260ec062

**Steps to reproduce the issue:**

1. Toggle "show" versions
2. Select versions to delete
3. Toggle "hide" versions
4. Versions now unselected, but count doesn't change
5. Select the same versions - count goes up

**Describe the results you expected:**
- Numbers are accurate and reflect what is actually selected

**Describe the results you received:**
- Numbers are wrong

**Comment by wilfred-asomanii** [comment]
[this change](https://review.dev.storj.io/c/storj/storj/+/14218/9) fixes this
