### ISSUE TITLE
Verify repair takes placement-specific RS settings into account

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#7116]
Recently we introduced change were we can set placement-specific RS settings. 

Mentioned change https://github.com/storj/storj/commit/f9293ef6f5d081dbc9941476182952af2c3ceb28

Acceptance Criteria:
* write unit tests to confirm that repair is working as intended
* fix problem if new test will uncover repair issue with placement-specific RS settings

**Comment by dlamarmorgan** [comment]
https://review.dev.storj.io/c/storj/storj/+/14343

**Comment by mniewrzal** [comment]
Its test so no need for deploy.
