### ISSUE TITLE
Ability to add custom information to invoices

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7131]
### Summary
Customers have requested the ability to include an arbitrary reference number or string on their invoices for legal or internal tracking purposes. Currently, this is being manually added by modifying the customer's name field in Stripe, which is not ideal and can lead to confusion. This feature should provide a dedicated field for such information, which is clearly labeled and separated from other billing details. 

The support team has been handling this by adding the reference number to the customer name field, but a more robust solution is needed to properly accommodate this requirement.

### Acceptance Criteria
1. **Add new field in billing information**: 
   - Provide a dedicated text field for customers to add an arbitrary reference number or string, which will be included on invoices.
   - The field should be clearly labeled as "Custom Reference" or similar to ensure it is distinct from the customer name or other billing details.
   
2. **Ensure visibility on invoices**: 
   - The custom reference field should be included on the invoice in a separate section (e.g., "Custom Reference"), appearing beneath the standard billing information (name, address, email, etc.).
   - The field should be optional, and left blank if not filled by the customer.
   
3. **Validation**: 
   - No specific format or validation required for the content of the custom reference field, but it should allow alphanumeric characters and punctuation commonly used in reference codes.

### Design

<img width="1728" alt="invoice-ref" src="https://github.com/user-attachments/assets/a360ef8d-2d98-440e-bd67-4c7e5845e086">

<img width="1728" alt="invoice-ref-dialog" src="https://github.com/user-attachments/assets/efdba545-0b87-4176-8feb-d8b5c3eb7378">

**Comment by NiaStorj** [comment]
@boshevski please create designs

**Comment by boshevski** [comment]
@NiaStorj added designs to the ticket

**Comment by VitaliiShpital** [comment]
could it be this?
https://docs.stripe.com/api/customers/object#customer_object-invoice_settings-custom_fields
