### ISSUE TITLE
Update the logic for garbage collection to use the production database instead of backup

### ISSUE THREAD

**Issue by mniewrzal** [storj/storj#7135]

**Comment by mniewrzal** [comment]
It looks that we cannot move to live DB with GC as we still have case were executing SSC we can skip segment to cause pieces deletion from SN. Case is:
- we have original segment at the and of StreamID space
- GC loop already processed first half of StreamID space
- we are doing SSC and copy of segment is created in a first half of StreamID space
- we are deleting original segment before GC reach it
- original segment is never visited by GC
- copy of segment is never visited by GC

**Comment by onionjake** [comment]
Does the GC complete fast enough to use AS OF SYSTEM TIME?

**Comment by mniewrzal** [comment]
In the past setting fixed as of system time was causing huge slow down after some period of time. Maybe things changed but still GC requires at least several hours of processing.

One alternative I'm thinking about is to start running GC from backups like avro instead full db instance. In the past crdb was not able to do that, now its possible. Spanner have it too.
