### ISSUE TITLE
Satellite UI: When creating bucket with lock, explain why versioning is required

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7140]
When creating a bucket, if the user selects to use object lock, there is still a "versioning" step, where users can read about versioning, but are not allowed to change versioning from "enabled". 

### AC:
* If user is creating a bucket and has selected to enable object lock, add explanation to versioning step saying that versioning is required for lock

**Comment by boshevski** [comment]
<img width="537" alt="design" src="https://github.com/user-attachments/assets/ee0ccde4-c9c7-46ab-ac62-16374d1c5182">
