### ISSUE TITLE
Satellite UI: improve partially-successful delete for versioned/locked objects

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7142]
Reproduction steps:
* upload multiple versions (e.g. 3) of the same file
* navigate to "show versions" view in file browser
* lock some (but not all) versions of the file
* select all files/versions with the checkboxes in the table view
* click to delete
  - an error is displayed that the delete failed (but it only failed for the locked versions)
  - the successfully-deleted version(s) still appear in the file browser, until refresh

### AC:
* when deleting all versions of a file in the "show versions" view:
  * If possible, indicate the number of deletes that succeeded vs. failed
  * Re-fetch versions for file(s) that were deleted if there is a partial failure

**Comment by ferristocrat** [comment]
@boshevski any particular designs you want to include for this?
