### ISSUE TITLE
Satellite UI: Prevent attempting "suspend versioning" on bucket with lock enabled

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7143]
Versioning cannot be suspended on a bucket with object lock enabled. We should probably prevent the user from performing this action. Currently, a user can attempt to suspend versioning on a lock-enabled bucket, but an error will occur and nothing will change on the bucket.

### AC:
* if a bucket has lock enabled, disable the option to "suspend versioning" for this bucket in both the buckets list view, and the file browser.
  - add a tooltip explaining that versioning cannot be suspended on a bucket with object lock enabled

### Screenshots of current state
| Page | Screenshot | 
| --- | --- |
| Buckets list view | ![image](https://github.com/user-attachments/assets/449d95e9-5728-42ad-b156-ffc662649889) |
| File browser (within bucket) | ![image](https://github.com/user-attachments/assets/3efaf432-cdd3-4210-917f-471a8e2126ca) |

**Comment by ferristocrat** [comment]
@boshevski any specific design considerations?
