### ISSUE TITLE
Satellite UI: improve lock dialog for versions

### ISSUE THREAD

**Issue by boshevski** [storj/storj#7152]
When locking a version, the dialog should be updated to reflect that.
Replace "file" with "version".
Add version id under the name.

![Image](https://github.com/user-attachments/assets/6f5762ea-9f4a-46f3-8f5b-dbbfad52d20d)

**Comment by wilfred-asomanii** [comment]
I think we should also indicate if the object in question has already been locked, showing the retention period.

**Comment by boshevski** [comment]
Yes, here is a design for it: 

<img width="505" alt="lock-status" src="https://github.com/user-attachments/assets/44a3be9c-9a26-45e5-a23c-c0f6d611b2af">

**Comment by VitaliiShpital** [comment]
@boshevski @wilfred-asomanii I don't think this design is correct because the user must be able to extend the retention period. Should we reuse this modal, or create a new one specifically for already locked versions that would display lock information and allow the user to extend the retention period?

**Comment by wilfred-asomanii** [comment]
Actually, what i meant was for the existing retention period to be on the previous dialog.
This would allow the user to extend the lock period, but we'll also have the chance to disable dates before the original retention period.

**Comment by boshevski** [comment]
@VitaliiShpital @wilfred-asomanii here is a design that works for already locked file plus adding the ability to extend the lock:

<img width="489" alt="extend-lock" src="https://github.com/user-attachments/assets/7a10d2a8-55bc-4279-89e2-f365ea4f18b2">

**Comment by boshevski** [comment]
We should also show a confirmation step with the new lock date:

<img width="447" alt="confirmation-extend-lock" src="https://github.com/user-attachments/assets/cc0e83d8-c1d7-47d5-9018-95050e9da85b">

**Comment by boshevski** [comment]
And here is a confirmation for initial lock:

<img width="451" alt="lock-confirmation" src="https://github.com/user-attachments/assets/e4616062-0a60-4ba6-a10c-94499cc8857f">
