### ISSUE TITLE
Satellite UI: show browser view switch in "versions" mode

### ISSUE THREAD

**Issue by VitaliiShpital** [storj/storj#7155]
Add the browser table/card view switch to the "versions" table view so as not to confuse users that they can not use the card view.

**AC**

- The view switch is added to the "versions" table view
- The switch is disabled
- Hovering over the switch shows a tool tip that informs the user to "hide versions" to toggle the view

**Comment by SneakPeak2003** [comment]
try this
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
I put the necessary dlls in the archive
