### ISSUE TITLE
Satellite UI: Add bucket details in settings menu

### ISSUE THREAD

**Issue by boshevski** [storj/storj#7161]
Bucket Details option is only available in the buckets table at the moment.
Add Bucket Details option in the bucket settings menu when browsing a bucket.

![Image](https://github.com/user-attachments/assets/c843cb60-b4d9-4f6c-a1c6-5088c9853f0c)

![Image](https://github.com/user-attachments/assets/f006b538-e625-4f9e-a65f-b3ae9081bb71)

**Comment by ptdatta** [comment]
@boshevski @VitaliiShpital please review [this PR](https://github.com/storj/storj/pull/7168)

**Comment by VitaliiShpital** [comment]
https://github.com/storj/storj/pull/7168
