### ISSUE TITLE
Add Object Lock to the versioning beta banner

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7163]
### Acceptance Criteria
Update the banner prompting users to enable object versioning beta to include object lock.

| Existing | New |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/169fa258-f403-413c-b9b4-8b4a615c4492) | ![image](https://github.com/user-attachments/assets/18fd0548-2fd6-4565-9849-ff5194828e02) |

**Comment by ptdatta** [comment]
Hey @ferristocrat currently it looks like this 
![image](https://github.com/user-attachments/assets/81c78757-74cd-4975-8b43-233eec870719)
Should I change according to your proposal.
