### ISSUE TITLE
Object Versioning UI: Update folder actions in list versions view

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7167]
### AC:
* in "view versions" view:
  * allow selecting a folder for multiselect (checkbox on table)
  * remove version expand toggle for folders (caret icon that shows or hides versions for object)
  * add menu actions to folders with share and delete actions

**Comment by wilfred-asomanii** [comment]
> @mobyvb @wilfred-asomanii Can I work on it?

I've already begun work on this. Thanks for offering!
