### ISSUE TITLE
Update UI to include Governance Mode and Legal Hold

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7169]
### Summary

As we are about to add Governance Mode and Legal Hold to our S3-compatible API, we want to expose this functionality to users in the UI.

### Acceptance Criteria

1. Add the ability to choose governance/compliance mode when you "lock" an object

<img width="498" alt="lock-mode" src="https://github.com/user-attachments/assets/2e8f3351-64d7-40cc-bef9-eb4004a5148e">

2 Pass along the Mode (compliance/governance) wherever we show the retention date (like when you try to delete). We want to show "Legal Hold" too when that's preventing a deletion

3. Add an option for legal hold (use file-lock-2 icon)

![Image](https://github.com/user-attachments/assets/81ff123b-e156-40c7-95ab-996b992d1cf5)

<img width="503" alt="lhold" src="https://github.com/user-attachments/assets/1f9e7994-2ca0-46fb-8ffe-9171d0f867e8">

<img width="499" alt="remove-lh" src="https://github.com/user-attachments/assets/805c544d-0567-4b50-ad46-1f5a019cfd73">

**Comment by ferristocrat** [comment]
@boshevski - some additional updates to make based on adding Governance Mode and Legal Hold... Please review/edit/change as you see fit!

**Comment by boshevski** [comment]
Updated the ticket with designs.
