### ISSUE TITLE
Restrict access grants for Object Lock actions

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7170]
### Summary

Currently, there is no way to restrict access grants via the UI for object lock related permissions. We want to enable this ability. The new permissions (restrictions) are:
- PutObjectRetention
- GetObjectRetention
- BypassGovernanceRetention
- PutObjectLegalHold
- GetObjectLegalHold

### Acceptance Criteria
1. Users should be able to create S3 credentials with specific restrictions/permissions for object lock related actions.
2. The meaning of each permission should be clear to the user
   a. Most importantly, `BypassGovernanceRetention` should be an exception or non-default option for users wanting object lock related access grants

### Designs
Separate step that shows up after the standard permissions step (only for projects with object versioning/lock enabled)

<img width="501" alt="lock-permissions" src="https://github.com/user-attachments/assets/9071367a-e205-4d61-b36a-63f3b172683b">

Permissions information expanded:

<img width="521" alt="lock-permissions-expanded" src="https://github.com/user-attachments/assets/5d79846b-8f7b-4837-8662-6cdbbd7a1081">

Use the same functionality for All Permissions as the previous permissions step (read, write...).

### Open questions/comments

1. It'd be great to be able to see the restrictions for these access grants in the list of accesses in the UI - i know we investigated this in the past and it'd be weird considering access grants can be created outside the UI as well as child access grants
4. Users/roles/permissions - As we potentially create different roles/sets of permissions (right now just "owner" and "member") perhaps it makes sense to restrict the types of access grants that certain users can/cannot create
5. Perhaps we should consider an option/path where non-s3 actions are restricted outside the UI? Basically getting rid of the ability to create "unknown" access grants. Perhaps this is a consideration for the "storj-managed passphrases" option, where with that option S3 is the only path?

**Comment by ferristocrat** [comment]
@boshevski - this is the other thing we should talk about related to object lock

**Comment by boshevski** [comment]
Updated ticket with design and notest.

**Comment by NiaStorj** [comment]
@boshevski do you have any more updates to make before this can be worked on?

**Comment by boshevski** [comment]
@NiaStorj updated with final designs and info.

**Comment by NiaStorj** [comment]
@wilfred-asomanii are you able to start work on this ASAP?  the goal is to have it merged by the 9th, IF POSSIBLE. 

cc @ferristocrat @mobyvb

**Comment by wilfred-asomanii** [comment]
Yes, I can
