### ISSUE TITLE
Add support for `PutObjectLockConfiguration` in the UI

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#7171]
### Summary

We want to give users the ability to view and update object lock settings in the UI after bucket creation. These settings are managed via the `PutObjectLockConfiguration` S3 action.

### Acceptance Criteria
`GetObjectLockConfiguration`
- Users can view object lock settings for a bucket, which may or may not have a default mode/retention. These settings can also be removed via PutObjectLockConfiguration. The settings include:
- Default Mode: Displays if set (e.g., GOVERNANCE or COMPLIANCE)
- Default Retention Period: Displays the retention period in either days or years

`PutObjectLockConfiguration`
- Users can update object lock settings from the UI for a bucket that already has object lock enabled. This includes:
   - Default Mode: Users can select GOVERNANCE or COMPLIANCE
   - Default Retention Period: Users can set the retention period as an integer in either days or years (but not both simultaneously)
- Users can enable object lock for a bucket that does not currently have object lock enabled.
   - _Note: Versioning must be enabled for object lock to be applied. If versioning is not already enabled, users will need to enable it when enabling object lock._

### Design

Add object lock option in bucket settings menu, both in the buckets table and the settings menu when viewing the bucket.
<img width="261" alt="object-lock" src="https://github.com/user-attachments/assets/11d1d578-b678-430c-9b42-59135e8d8822">

Update Bucket Details dialog to show:
- Object Lock
- Default Lock Mode (if not set, use "Not set")
- Default Retention Period (if not set, use "Not set")
- Legal Hold
<img width="521" alt="details" src="https://github.com/user-attachments/assets/61277890-4982-4ed6-a0ad-659a10511995">

Update the lock step in the New Bucket dialog to include: 
- Select object lock mode (only show if object lock is enabled and it's optional)
- If object lock is enabled, show the other options like selecting a default object lock mode and default retention period.
- Change the alert to explain the chosen type
- Add optional default retention period (Days, Weeks, Months, Years / parse in the frontend).
<img width="543" alt="lock-new" src="https://github.com/user-attachments/assets/5ce15725-d1ad-4855-ab32-e4b075ab7ee4">

Dialog when enabling object lock on a bucket and/or choosing a default lock mode plus retention period:

<img width="489" alt="set-lock" src="https://github.com/user-attachments/assets/5fe897ab-f77e-4654-aaff-b6b4fbb736df">

**Comment by ferristocrat** [comment]
@boshevski - the last object lock related UI thing

**Comment by boshevski** [comment]
Updated the ticket with the latest designs.

**Comment by VitaliiShpital** [comment]
@boshevski I've just realized that users might be able to remove the default retention mode and period from a bucket. How should we handle this functionality in the UI?

**Comment by boshevski** [comment]
Hey @VitaliiShpital, we should have the v-chip-filter to not be required and let users uncheck the default mode. This would remove the default retention period input and update the alert message to:
**Object Lock Enabled (No Default Mode)**: Objects in this bucket will follow retention settings applied at the object level during upload or by your applications.
