### ISSUE TITLE
Satellite UI: Make object version submenu more responsive

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7181]
For performance reasons, we should not request the lock status of every object version displayed in the satellite UI. Otherwise we might be making 100 simultaneous "get lock status" requests for a single page.

However, the current experience of locking an object version is confusing. The submenu for an object version always displays "lock version", even if the particular version is already locked. It would be better if this part of the submenu had a "loading" state while we request the lock status of the version (triggered by clicking three-dot icon). Once we retrieve lock status of the version, we can display different text in the submenu depending on whether the version is already locked or not.

### AC:
* request version lock status when submenu is opened for object version in browser

* display different text for "lock object" operation in submenu depending on whether version is locked or not

##### Show Lock option when object is not locked:
<img width="219" alt="menu-lock" src="https://github.com/user-attachments/assets/acb99e87-362a-411d-9b10-0fb0a7a3a7e8">

##### Show Locked option when object is locked:
<img width="221" alt="menu-locked" src="https://github.com/user-attachments/assets/6837cc5c-1669-4077-b5f1-7ee54ba90094">

##### Show loading in prepend icon and disable the Lock action until the status is requested successfully. 
Use same height and width as the icon for the loader, and use the primary blue color. Consult with Tome if you need any help on this.

**Comment by NiaStorj** [comment]
@boshevski this issue needs design. Thanks!

**Comment by boshevski** [comment]
Updated the ticket with designs and info.
