### ISSUE TITLE
Satellite UI: Disable "set lock" button when lock type is not selected

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7201]
When locking a version, you can select lock retention period, and attempt to proceed to the next step. Since selecting "governance" or "compliance" mode is required, we should disable the button until it is selected.
![Image](https://github.com/user-attachments/assets/e05445e4-88e2-4e3e-aef3-8aa5af75c9f7)
![Image](https://github.com/user-attachments/assets/94af301a-61dc-4452-ae8b-ecfb83ccef14)

### AC:
* user must select lock type before "Set Lock" button becomes enabled

**Comment by nakul-py** [comment]
\assign
