### ISSUE TITLE
Satellite UI: Improve STORJ token upgrade experience

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7207]
There are a couple experience issues related to upgrading with STORJ token:
* During onboarding, there is no "next step" when attempting to upgrade via STORJ token
* When the user is automatically upgraded after paying with STORJ token, the UI does not obviously update indicating that they have been upgraded
* Additionally, if the user opens the "upgrade with STORJ token" dialog, there is no indicator of the current wallet balance, so it may not be clear how much the user needs to send in order to be upgraded

### AC:
* Upgrade with STORJ during onboarding:
  * Allow user to proceed past STORJ token upgrade dialog, add Next button (disabled until there is a transaction pending with 1 confirmation)
  * Add information indicating that the user can proceed and use the app, and they will be automatically upgraded when their STORJ tokens are received
  * Once the transaction is fully confirmed, replace the transaction pending alert with a success alert saying "Successful deposit of X STORJ tokens. You received an additional bonus of X STORJ tokens. ".  If the dialog is already closed, show this as an alert in the UI.

* STORJ token upgrade dialog:
  * Display current STORJ balance processed (in USD, so that it is clear how much needs to be added to get to the required threshold)
* Async upgrade while app is in use:
  * If the STORJ dialog was opened and transactions started being sent, occasionally refresh user data from the API
    * If/when user switches from "free" to "paid", display a success notification, and update the UI/project store/etc... so that user does not need to refresh manually

Remove account upgrade step where users choose card/vs/token and merge both steps into one step using tabs (like the billing).

##### Remove this step:
![Image](https://github.com/user-attachments/assets/8ae7c8eb-13a3-4284-bf6e-d4d01f860e22)

##### Combine steps like this:
![Image](https://github.com/user-attachments/assets/84d88baa-f91e-4b59-8d4b-1fdb1a45f16b)

##### Add the next button:
![Image](https://github.com/user-attachments/assets/d1fd9e55-bcef-42f8-a2ae-562bf06fc0cc)

**Comment by VitaliiShpital** [comment]
Hey @boshevski! I think there might be an issue with merging the card and token steps due to the pricing plan logic. How should it work if I'm an ix-systems user and I want to purchase a pricing plan? If we merge those steps, the user might mistakenly believe they can buy a pricing plan with STORJ tokens, which isn't the case.

**Comment by boshevski** [comment]
Hey @VitaliiShpital for that case just hide the token tab :) 
also we could add an option in the future to send an exact amount of tokens for the ix plan.
