### ISSUE TITLE
Satellite UI: improve object lock time behavior

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#7209]
**Case 1: Select prefilled retention period**

"1 day" selected on Oct 15, 2024 at 10:24am
![Image](https://github.com/user-attachments/assets/df92610b-7186-401e-b0c7-610339a78d1a)
Resulting lock expiration is Oct 16 at 10:24
![Image](https://github.com/user-attachments/assets/3a5d35c4-492e-4b49-9410-aa5a37ca7ff2)

**Case 2: Select custom retention period**

Custom date selected (Nov 1st)
![Image](https://github.com/user-attachments/assets/92df1f76-cf78-4c54-8b95-2e416ece6a2f)

Resulting lock expiration is Nov 1st at 00:00
![Image](https://github.com/user-attachments/assets/a55f00ce-c97f-4d51-b9c3-9b4334b3b217)

Questions/comments:
* when user selects "custom date", how should expiration time be determined? Should it be expired at the beginning or the end of the day? Should it be dependent on the time of the lock?
* when user selects range like "1 day" or "1 week", should it continue to expire exactly <duration> after the lock time? E.g. if locked at 10am, it will expire at 10am
* we should probably add timezone to the lock expiration time we display to the user

**Comment by ferristocrat** [comment]
Questions/comments:

- when user selects "custom date", how should expiration time be determined? Should it be expired at the beginning or the end of the day? Should it be dependent on the time of the lock?
   - I think how it works is fine, as long as we document it. It looks like AWS always uses the time of the lock... there is no concept of specifying a specific date, just a number of days or years. So if we wanted to be in line with this, we should use the current timestamp even when choosing a specific date -- I somewhat like how we have it though... perhaps we consider adding a time selector?
- when user selects range like "1 day" or "1 week", should it continue to expire exactly after the lock time? E.g. if locked at 10am, it will expire at 10am
   - Yes. This is how it's done according to the S3 standard: https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock.html#object-lock-overview
- we should probably add timezone to the lock expiration time we display to the user
   - Agreed -- and if we're actually using UTC we should include this in the docs
