### ISSUE TITLE
Storj for arm

### ISSUE THREAD

**Issue by forsam47** [storj/storj#868]
Hi, i would try compile storj to arm, but library "loov" wroten for  amd64 and software does not work properly. So does any body try  compile to arm or will be storj ported to arm ( use another library instead of loov)

**Comment by egonelbre** [comment]
Currently only `s3-benchmark` uses `github.com/loov/hrtime`. `s3-benchmark`-s purpose is to benchmark different API-s with good precision. It is not necessary for the general functionaly of storj, so you can safely ignore that.

I'll look into fixing it nevertheless.

**Comment by egonelbre** [comment]
We haven't yet tested the system properly on ARM, but it is in our plans and do let us know when you hit other issues.

**Comment by forsam47** [comment]
captplanet working with  error "2018-12-17T23:55:27.719+0300    DEBUG   Kicking off refresh
". How to switch on more powerfull log
