### ISSUE TITLE
FreeBSD support

### ISSUE THREAD

**Issue by AlexandrTyshchenko** [storj/storj#980]
Please add FreeBSD support for storj v3, because at this moment we have a problem with [gosigar](https://github.com/cloudfoundry/gosigar) package dependendency. **This package does not support FreeBSD.** 

Here is the problem with build test v3 network on FreeBSD:

- [ ] install latest [Go language for freebsd](https://golang.org/dl/)
`wget https://dl.google.com/go/go1.11.4.freebsd-amd64.tar.gz`
`tar -xvf go1.11.4.freebsd-amd64.tar.gz`
`sudo mv go /usr/local`

- [ ] Setup Go Enviroment
Open your `.profile`file and add global variable as follow at the end of the file. You may want to add this into .zshrc or.bashrc file as per your shell configuration.
```
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH
```

- [ ] Update current shell session
`source ~/.profile`

- [ ] Verify Installation
`go version`
> go version go1.11.4 freebsd/amd64

`go env`

> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/storj/.cache/go-build"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="freebsd"
> GOOS="freebsd"
> GOPATH="/home/storj/go"
> GOPROXY=""
> GORACE=""
> GOROOT="/usr/local/go"
> GOTMPDIR=""
> GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
> GCCGO="gccgo"
> CC="clang"
> CXX="clang++"
> CGO_ENABLED="1"
> GOMOD="/home/storj/storj/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build436043875=/tmp/go-build -gno-record-gcc-switches"

- [ ] Install [test storj v3 network](https://github.com/storj/storj/wiki/Test-network)
```
git clone https://github.com/storj/storj.git storj
cd storj
go install ./cmd/captplanet
```
- [ ] Got Error

> # github.com/cloudfoundry/gosigar
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:20:11: cpuUsage.Get undefined (type Cpu has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:30:13: cpuUsage.Get undefined (type Cpu has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:49:10: l.Get undefined (type LoadAverage has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:55:10: m.Get undefined (type Mem has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:61:10: s.Get undefined (type Swap has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/sigar_shared.go:12:20: procTime.Get undefined (type *ProcTime has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/sigar_unix.go:21:17: cannot use stat.Ffree (type int64) as type uint64 in assignment
> 

If we look into this [link](https://github.com/prebid/prebid-server/issues/17) you can find similar problem with **gosigar** package

> It looks like https://github.com/cloudfoundry/gosigar **is missing FreeBSD support**. We can fix this by adding support to the gosigar project or investigating a package/way to obtaining resource information.

> I think it would be more simple to **just remove the go-sigar dependency and replace it with gopsutil**. I have searched and found this solution. I don't know if this is a reliable thing to do.

**Comment by kaloyan-raev** [comment]
https://github.com/cloudfoundry/gosigar is used only by https://github.com/jtolds/monkit-hw in our dependency graph.

@jtolds Would it be possible to replace gosigar with gopsutils as suggested?

**Comment by kaloyan-raev** [comment]
Oh I see @egonelbre has just disabled gosigar in https://github.com/storj/storj/pull/984.

**Comment by jtolds** [comment]
gopsutil might be good

**Comment by AlexandrTyshchenko** [comment]
Thanks all for looking into this issue!
I see that all changes was merged into master and i try to rebuild storj test v3 network.
Unfortunately I got this error again:

>  github.com/cloudfoundry/gosigar
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:20:11: cpuUsage.Get undefined (type Cpu has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:30:13: cpuUsage.Get undefined (type Cpu has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:49:10: l.Get undefined (type LoadAverage has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:55:10: m.Get undefined (type Mem has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/concrete_sigar.go:61:10: s.Get undefined (type Swap has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/sigar_shared.go:12:20: procTime.Get undefined (type *ProcTime has no field or method Get)
> ../go/pkg/mod/github.com/cloudfoundry/gosigar@v1.1.0/sigar_unix.go:21:17: cannot use stat.Ffree (type int64) as type uint64 in assignment

I think it still using somewhere...

**Comment by AlexandrTyshchenko** [comment]
I found issue, please change separators on this [commit](https://github.com/jtolds/monkit-hw/pull/2#issue-242607511) 

shoul be:
`// +build !freebsd,!darwin,darwin,cgo`

**Comment by egonelbre** [comment]
I made https://github.com/jtolds/monkit-hw/pull/3, unfortunately I haven't yet had time to setup FreeBSD builder/VM to verify everything, so I'm making mistakes.

**Comment by AlexandrTyshchenko** [comment]
Thanks @egonelbre !
Not a problem, I will test it and share results.

**Comment by AlexandrTyshchenko** [comment]
I already test https://github.com/jtolds/monkit-hw/pull/3 on freebsd, and everything working fine.
Let's waiting merge to master and close this issue.

**Comment by jtolds** [comment]
jtolds/monkit-hw#3 merged

**Comment by egonelbre** [comment]
Merged

**Comment by AlexandrTyshchenko** [comment]
Now evrything build fine on freebds.
@egonelbre Thanks you so much!
